triSYCL implementation of SYCL: cl::sycl::detail::opencl_context Class Reference
cl::sycl::detail::opencl_context Class Reference
SYCL OpenCL context.
#include <opencl_context.hpp>
Public Member Functions
cl_context get () const override
Return the underlying cl_context of the cl::sycl::context.
boost::compute::context & get_boost_compute () override
Return the underlying boost::compute::context of the cl::sycl::context.
boost::compute::command_queue & get_boost_queue () override
Return the queue that is associated to the context.
bool is_host () const override
Return false because the context is not a SYCL host context.
cl::sycl::platform get_platform () const override
Return the platform of the context.
vector_class< cl::sycl::device > get_devices () const override
Returns the set of devices that are part of this context.
cl::sycl::cl_uint get_reference_count () const override
Returns the reference count of underlying CL context, or 0 on host.
~opencl_context () override
Unregister from the cache on destruction.
Public Member Functions inherited from cl::sycl::detail::context
virtual ~context ()
Virtual to call the real destructor.
Static Public Member Functions
static std::shared_ptr< opencl_context > instance (const boost::compute::context &c)
Get a singleton instance of the opencl_context.
Private Member Functions
opencl_context (const boost::compute::context &c)
Only the instance factory can build it.
Private Attributes
boost::compute::context c
User the Boost Compute abstraction of the OpenCL context.
boost::compute::command_queue q
A boost command_queue associated to an OpenCL context for when we need to transfer data but no queue is given (eg.
Static Private Attributes
static detail::cache< cl_context, detail::opencl_context > cache
A cache to always return the same alive context for a given OpenCL context.
Detailed Description
SYCL OpenCL context.
Definition at line 30 of file opencl_context.hpp.
Constructor & Destructor Documentation
opencl_context()
cl::sycl::detail::opencl_context::opencl_context (const boost::compute::context & c) inline private
Only the instance factory can build it.
Definition at line 128 of file opencl_context.hpp.
References c.
                                                :
     c { c },
     q { boost::compute::command_queue { c, c.get_device() } } {}
~opencl_context()
cl::sycl::detail::opencl_context::~opencl_context () inline override
Unregister from the cache on destruction.
Definition at line 135 of file opencl_context.hpp.
References cache, cl::sycl::detail::cache< Key, Value >::remove(), and TRISYCL_WEAK_ATTRIB_PREFIX.
{
     cache.remove(c.get());
   }
Member Function Documentation
get()
cl_context cl::sycl::detail::opencl_context::get () const inline override virtual
Return the underlying cl_context of the cl::sycl::context.
Implements cl::sycl::detail::context.
Definition at line 51 of file opencl_context.hpp.
{
     return c.get();
   }
get_boost_compute()
boost::compute::context& cl::sycl::detail::opencl_context::get_boost_compute () inline override virtual
Return the underlying boost::compute::context of the cl::sycl::context.
Implements cl::sycl::detail::context.
Definition at line 59 of file opencl_context.hpp.
References c.
{
     return c;
   }
get_boost_queue()
boost::compute::command_queue& cl::sycl::detail::opencl_context::get_boost_queue () inline override virtual
Return the queue that is associated to the context.
Implements cl::sycl::detail::context.
Definition at line 65 of file opencl_context.hpp.
References q.
{
     return q;
   }
get_devices()
vector_class<cl::sycl::device> cl::sycl::detail::opencl_context::get_devices () const inline override virtual
Returns the set of devices that are part of this context.
Todo:
To be implemented
Implements cl::sycl::detail::context.
Definition at line 105 of file opencl_context.hpp.
{
     vector_class<cl::sycl::device> devices;
     for (const auto &d : c.get_devices())
       devices.push_back(d);
     return devices;
   }
get_platform()
cl::sycl::platform cl::sycl::detail::opencl_context::get_platform () const inline override virtual
Return the platform of the context.
Return synchronous errors via the SYCL exception class.
Todo:
To be implemented
Implements cl::sycl::detail::context.
Definition at line 96 of file opencl_context.hpp.
{
     return cl::sycl::platform(c.get_devices()[0].platform());
   }
get_reference_count()
cl::sycl::cl_uint cl::sycl::detail::opencl_context::get_reference_count () const inline override virtual
Returns the reference count of underlying CL context, or 0 on host.
Implements cl::sycl::detail::context.
Definition at line 113 of file opencl_context.hpp.
{
     return c.get_info<CL_CONTEXT_REFERENCE_COUNT>();
   }
instance()
static std::shared_ptr<opencl_context> cl::sycl::detail::opencl_context::instance (const boost::compute::context & c) inline static
Get a singleton instance of the opencl_context.
Definition at line 119 of file opencl_context.hpp.
References cl::sycl::detail::cache< Key, Value >::get_or_register().
Referenced by cl::sycl::context::context().
{
     return cache.get_or_register(c.get(),
                                  [&] { return new opencl_context { c }; });
   }
is_host()
bool cl::sycl::detail::opencl_context::is_host () const inline override virtual
Return false because the context is not a SYCL host context.
Implements cl::sycl::detail::context.
Definition at line 71 of file opencl_context.hpp.
References TRISYCL_UNIMPL.
{
     return false;
   }
Member Data Documentation
c
boost::compute::context cl::sycl::detail::opencl_context::c private
User the Boost Compute abstraction of the OpenCL context.
Definition at line 33 of file opencl_context.hpp.
Referenced by get_boost_compute(), and opencl_context().
cache
detail::cache<cl_context, detail::opencl_context> cl::sycl::detail::opencl_context::cache static private
A cache to always return the same alive context for a given OpenCL context.
C++11 guaranties the static construction is thread-safe
Definition at line 46 of file opencl_context.hpp.
Referenced by ~opencl_context().
q
boost::compute::command_queue cl::sycl::detail::opencl_context::q private
A boost command_queue associated to an OpenCL context for when we need to transfer data but no queue is given (eg.
When an buffer accessor is created)
Definition at line 39 of file opencl_context.hpp.
Referenced by get_boost_queue().
The documentation for this class was generated from the following file:
include/CL/sycl/context/detail/opencl_context.hpp