triSYCL implementation of SYCL: trisycl::detail::opencl_event Class Reference
trisycl::detail::opencl_event Class Reference
#include <opencl_event.hpp>
Public Member Functions
cl_event get () const override
Return the cl_event of the underlying OpenCL event.
const boost::compute::event & get_boost_compute () const override
Return the underlying Boost.Compute event, if any.
bool is_host () const override
info::event_command_status get_command_execution_status () const override
cl_ulong get_profiling_info (info::event_profiling param) const override
trisycl::cl_uint get_reference_count () const override
void wait () const override
~opencl_event () override
Public Member Functions inherited from trisycl::detail::event
virtual ~event ()
Static Public Member Functions
static std::shared_ptr< opencl_event > instance (const boost::compute::event &e)
Get a singleton instance of the opencl_event.
Private Member Functions
opencl_event (const boost::compute::event &e)
Only the instance factory can build it.
Private Attributes
boost::compute::event e
Static Private Attributes
static detail::cache< cl_event, detail::opencl_event > cache
A cache to always return the same alive event for a given OpenCL event.
Detailed Description
Definition at line 15 of file opencl_event.hpp.
Constructor & Destructor Documentation
opencl_event()
trisycl::detail::opencl_event::opencl_event (const boost::compute::event & e) inline private
Only the instance factory can build it.
Definition at line 61 of file opencl_event.hpp.
                                            :
     e { e } {}
~opencl_event()
trisycl::detail::opencl_event::~opencl_event () inline override
Definition at line 65 of file opencl_event.hpp.
References trisycl::detail::cache< Key, Value >::remove().
{
     cache.remove(e.get());
   }
Member Function Documentation
get()
cl_event trisycl::detail::opencl_event::get () const inline override virtual
Return the cl_event of the underlying OpenCL event.
Implements trisycl::detail::event.
Definition at line 25 of file opencl_event.hpp.
{
     return e.get();
   }
get_boost_compute()
const boost::compute::event& trisycl::detail::opencl_event::get_boost_compute () const inline override virtual
Return the underlying Boost.Compute event, if any.
Implements trisycl::detail::event.
Definition at line 29 of file opencl_event.hpp.
References e.
{
     return e;
   }
get_command_execution_status()
info::event_command_status trisycl::detail::opencl_event::get_command_execution_status () const inline override virtual
Implements trisycl::detail::event.
Definition at line 37 of file opencl_event.hpp.
{
     return static_cast<info::event_command_status>(e.status());
   }
get_profiling_info()
cl_ulong trisycl::detail::opencl_event::get_profiling_info (info::event_profiling param) const inline override virtual
Implements trisycl::detail::event.
Definition at line 41 of file opencl_event.hpp.
{
     return e.get_profiling_info<cl_ulong>(static_cast<cl_profiling_info>(param));
   }
get_reference_count()
trisycl::cl_uint trisycl::detail::opencl_event::get_reference_count () const inline override virtual
Implements trisycl::detail::event.
Definition at line 45 of file opencl_event.hpp.
{
     return e.get_info<CL_EVENT_REFERENCE_COUNT>();
   }
instance()
static std::shared_ptr<opencl_event> trisycl::detail::opencl_event::instance (const boost::compute::event & e) inline static
Get a singleton instance of the opencl_event.
Definition at line 55 of file opencl_event.hpp.
References trisycl::detail::cache< Key, Value >::get_or_register().
Referenced by trisycl::event::event().
{
     return cache.get_or_register(e.get(),
                                  [&] { return new opencl_event { e }; });
   }
is_host()
bool trisycl::detail::opencl_event::is_host () const inline override virtual
Implements trisycl::detail::event.
Definition at line 33 of file opencl_event.hpp.
{
     return false;
   }
wait()
void trisycl::detail::opencl_event::wait () const inline override virtual
Implements trisycl::detail::event.
Definition at line 49 of file opencl_event.hpp.
{
     e.wait();
   }
Member Data Documentation
cache
detail::cache<cl_event, detail::opencl_event> trisycl::detail::opencl_event::cache static private
A cache to always return the same alive event for a given OpenCL event.
C++11 guaranties the static construction is thread-safe
Definition at line 23 of file opencl_event.hpp.
e
boost::compute::event trisycl::detail::opencl_event::e private
Definition at line 16 of file opencl_event.hpp.
Referenced by get_boost_compute().
The documentation for this class was generated from the following file:
include/triSYCL/event/detail/opencl_event.hpp