triSYCL implementation of OpenCL SYCL: cl::sycl::detail::opencl_kernel Class Reference
cl::sycl::detail::opencl_kernel Class Reference
An abstraction of the OpenCL kernel.
#include <opencl_kernel.hpp>
Public Member Functions
cl_kernel get () const override
Return the underlying OpenCL object.
boost::compute::kernel get_boost_compute () const override
Return the Boost.Compute OpenCL kernel object for this kernel.
TRISYCL_ParallelForKernel_RANGE (1) TRISYCL_ParallelForKernel_RANGE(2) TRISYCL_ParallelForKernel_RANGE(3)~opencl_kernel() override
Unregister from the cache on destruction.
Public Member Functions inherited from cl::sycl::detail::kernel
TRISYCL_ParallelForKernel_RANGE (1) TRISYCL_ParallelForKernel_RANGE(2) TRISYCL_ParallelForKernel_RANGE(3) virtual ~kernel()
Return the context that this kernel is defined for.
Static Public Member Functions
static std::shared_ptr< opencl_kernel > instance (const boost::compute::kernel &k)
Private Member Functions
opencl_kernel (const boost::compute::kernel &k)
Private Attributes
boost::compute::kernel k
Use the Boost Compute abstraction of the OpenCL kernel.
Static Private Attributes
static detail::cache< cl_kernel, detail::opencl_kernel > cache
A cache to always return the same alive kernel for a given OpenCL kernel.
Detailed Description
An abstraction of the OpenCL kernel.
Definition at line 29 of file opencl_kernel.hpp.
Constructor & Destructor Documentation
cl::sycl::detail::opencl_kernel::opencl_kernel (const boost::compute::kernel & k) inline private
Definition at line 42 of file opencl_kernel.hpp.
 : k { k } {}
Member Function Documentation
cl_kernel cl::sycl::detail::opencl_kernel::get () const inline override virtual
Return the underlying OpenCL object.
Todo:
Improve the spec to deprecate C OpenCL host API and move to C++ instead to avoid this ugly ownership management
Todo:
Test error and throw. Externalize this feature in Boost.Compute?
Implements cl::sycl::detail::kernel.
Definition at line 58 of file opencl_kernel.hpp.
{
     /// \todo Test error and throw. Externalize this feature in Boost.Compute?
     clRetainKernel(k);
     return k.get();
   }
boost::compute::kernel cl::sycl::detail::opencl_kernel::get_boost_compute () const inline override virtual
Return the Boost.Compute OpenCL kernel object for this kernel.
This is an extension.
Implements cl::sycl::detail::kernel.
Definition at line 69 of file opencl_kernel.hpp.
References k, and cl::sycl::detail::unimplemented().
{
     return k;
   }
static std::shared_ptr<opencl_kernel> cl::sycl::detail::opencl_kernel::instance (const boost::compute::kernel & k) inline static
Definition at line 48 of file opencl_kernel.hpp.
References cl::sycl::detail::cache< Key, Value >::get_or_register().
Referenced by cl::sycl::kernel::kernel().
{
     return cache.get_or_register(k.get(),
                                  [&] { return new opencl_kernel { k }; });
   }
cl::sycl::detail::opencl_kernel::TRISYCL_ParallelForKernel_RANGE (1) inline override
Unregister from the cache on destruction.
Definition at line 111 of file opencl_kernel.hpp.
References cache, cl::sycl::detail::cache< Key, Value >::remove(), TRISYCL_WEAK_ATTRIB_PREFIX, and cl::sycl::detail::TRISYCL_WEAK_ATTRIB_SUFFIX.
{
     cache.remove(k.get());
   }
Member Data Documentation
detail::cache<cl_kernel, detail::opencl_kernel> cl::sycl::detail::opencl_kernel::cache static private
A cache to always return the same alive kernel for a given OpenCL kernel.
C++11 guaranties the static construction is thread-safe
Definition at line 40 of file opencl_kernel.hpp.
Referenced by TRISYCL_ParallelForKernel_RANGE().
boost::compute::kernel cl::sycl::detail::opencl_kernel::k private
Use the Boost Compute abstraction of the OpenCL kernel.
Definition at line 33 of file opencl_kernel.hpp.
Referenced by get_boost_compute().
The documentation for this class was generated from the following file:
include/CL/sycl/kernel/detail/opencl_kernel.hpp