triSYCL implementation of SYCL: trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA > Class Template Reference
trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA > Class Template Reference
Generic DMA.
#include <dma.hpp>
Public Member Functions
dma (::trisycl::detail::fiber_pool &fe)
Start the DMA engine using an executor.
~dma ()
Destructor handling the correct infrastructure shutdown.
SpecializedDMA & wait ()
Wait for the transfers to complete.
dma (::trisycl::detail::fiber_pool &fe)
Start the DMA engine using an executor.
~dma ()
Destructor handling the correct infrastructure shutdown.
SpecializedDMA & wait ()
Wait for the transfers to complete.
Protected Member Functions
template<typename Cmd >
void push_command (Cmd &&command)
Enqueue a DMA command.
template<typename Cmd >
void push_command (Cmd &&command)
Enqueue a DMA command.
Private Types
using dma_command = std::function< void(void)>
Use std::span for 1D contiguous transfers only for now.
using dma_command = std::function< void(void)>
Use std::span for 1D contiguous transfers only for now.
Private Member Functions
void join ()
Wait for the fiber to complete.
template<typename Invocable >
void launch (::trisycl::detail::fiber_pool &fiber_executor, Invocable &&f)
Launch the data mover on the execution pool.
auto pop_command (auto &command)
Dequeue a DMA command.
void commit_command ()
Notify a command has been processed.
void join ()
Wait for the fiber to complete.
template<typename Invocable >
void launch (::trisycl::detail::fiber_pool &fiber_executor, Invocable &&f)
Launch the data mover on the execution pool.
auto pop_command (auto &command)
Dequeue a DMA command.
void commit_command ()
Notify a command has been processed.
Private Attributes
boost::fibers::buffered_channel< dma_command > c { 8 }
Queue for generic DMA commands.
::trisycl::detail::fiber_pool::future< void > data_mover
To shepherd the fiber playing the data mover behind the DMA.
std::atomic< int > nb_command { 0 }
Count the in-flight commands.
boost::fibers::condition_variable waiting_room
To wait for the DMA command queue to drain.
boost::fibers::mutex waiting_mutex
To protect the waiting mechanism.
Additional Inherited Members
Static Private Member Functions inherited from trisycl::detail::debug< SpecializedDMA >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Detailed Description
template<typename AXIStreamSwitch, typename SpecializedDMA>
class trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >
Generic DMA.
Definition at line 103 of file dma.hpp.
Member Typedef Documentation
dma_command [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > using trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma_command = std::function<void(void)> private
Use std::span for 1D contiguous transfers only for now.
The type of commands executable by the DMA. Very generic for now
Definition at line 110 of file dma.hpp.
dma_command [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > using trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma_command = std::function<void(void)> private
Use std::span for 1D contiguous transfers only for now.
The type of commands executable by the DMA. Very generic for now
Definition at line 110 of file dma.hpp.
Constructor & Destructor Documentation
dma() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma (::trisycl::detail::fiber_pool & fe) inline
Start the DMA engine using an executor.
Definition at line 156 of file dma.hpp.
{
    data_mover = fe.submit([&] {
      dma_command sp;
      for (;;) {
        // Read a DMA command
        if (this->pop_command(sp) != boost::fibers::channel_op_status::success)
          // The channel is closed, stop working
          break;
        // Execute the command
        sp();
        commit_command();
      }
    });
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::commit_command(), trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::data_mover, trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::pop_command(), and trisycl::detail::fiber_pool::submit().
~dma() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::~dma () inline
Destructor handling the correct infrastructure shutdown.
Definition at line 172 of file dma.hpp.
         {
    // Close the command queue so the DMA does not accept any work
    c.close();
    /* Wait for the commands to drain to avoid calling
       std::terminate on destruction... */
    join();
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::c, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::join().
dma() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma (::trisycl::detail::fiber_pool & fe) inline
Start the DMA engine using an executor.
Definition at line 156 of file dma.hpp.
{
    data_mover = fe.submit([&] {
      dma_command sp;
      for (;;) {
        // Read a DMA command
        if (this->pop_command(sp) != boost::fibers::channel_op_status::success)
          // The channel is closed, stop working
          break;
        // Execute the command
        sp();
        commit_command();
      }
    });
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::commit_command(), trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::data_mover, trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::pop_command(), and trisycl::detail::fiber_pool::submit().
~dma() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::~dma () inline
Destructor handling the correct infrastructure shutdown.
Definition at line 172 of file dma.hpp.
         {
    // Close the command queue so the DMA does not accept any work
    c.close();
    /* Wait for the commands to drain to avoid calling
       std::terminate on destruction... */
    join();
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::c, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::join().
Member Function Documentation
commit_command() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::commit_command () inline private
Notify a command has been processed.
Definition at line 141 of file dma.hpp.
{
    if (--nb_command == 0)
      // Warn anyone waiting for the DMA queue to drain it might be empty now
      waiting_room.notify_all();
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::nb_command, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_room.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma().
commit_command() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::commit_command () inline private
Notify a command has been processed.
Definition at line 141 of file dma.hpp.
{
    if (--nb_command == 0)
      // Warn anyone waiting for the DMA queue to drain it might be empty now
      waiting_room.notify_all();
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::nb_command, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_room.
join() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::join () inline private
Wait for the fiber to complete.
Definition at line 128 of file dma.hpp.
              {
    // Get the value of the future, to get an exception if any
    data_mover.get();
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::data_mover.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::~dma().
join() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::join () inline private
Wait for the fiber to complete.
Definition at line 128 of file dma.hpp.
              {
    // Get the value of the future, to get an exception if any
    data_mover.get();
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::data_mover.
launch() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::launch (::trisycl::detail::fiber_pool & fiber_executor, Invocable && f) inline private
Launch the data mover on the execution pool.
Definition at line 135 of file dma.hpp.
{}
launch() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::launch (::trisycl::detail::fiber_pool & fiber_executor, Invocable && f) inline private
Launch the data mover on the execution pool.
Definition at line 135 of file dma.hpp.
{}
pop_command() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > auto trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::pop_command (auto & command) inline private
Dequeue a DMA command.
Definition at line 138 of file dma.hpp.
{ return c.pop(command); }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::c.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma().
pop_command() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > auto trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::pop_command (auto & command) inline private
Dequeue a DMA command.
Definition at line 138 of file dma.hpp.
{ return c.pop(command); }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::c.
push_command() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > template<typename Cmd > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::push_command (Cmd && command) inline protected
Enqueue a DMA command.
Definition at line 149 of file dma.hpp.
{
    ++nb_command;
    c.push(std::forward<Cmd>(command));
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::c, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::nb_command.
push_command() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > template<typename Cmd > void trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::push_command (Cmd && command) inline protected
Enqueue a DMA command.
Definition at line 149 of file dma.hpp.
{
    ++nb_command;
    c.push(std::forward<Cmd>(command));
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::c, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::nb_command.
wait() [1/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > SpecializedDMA & trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::wait () inline
Wait for the transfers to complete.
The API assumes that the program is written in such a way that at some point the queue will be empty so there is no continuous DMA command enqueuing for example.
Definition at line 185 of file dma.hpp.
{
    if (nb_command != 0) {
      // We need to wait because there are still operations executing
      std::unique_lock lk { waiting_mutex };
      waiting_room.wait(lk, [&] { return nb_command == 0; });
    }
    /* To be able to chain another DMA operation on it, return the DMA
       object itself */
    return static_cast<SpecializedDMA&>(*this);
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::nb_command, trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_mutex, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_room.
Referenced by trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::wait().
wait() [2/2]
template<typename AXIStreamSwitch , typename SpecializedDMA > SpecializedDMA & trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::wait () inline
Wait for the transfers to complete.
The API assumes that the program is written in such a way that at some point the queue will be empty so there is no continuous DMA command enqueuing for example.
Definition at line 185 of file dma.hpp.
{
    if (nb_command != 0) {
      // We need to wait because there are still operations executing
      std::unique_lock lk { waiting_mutex };
      waiting_room.wait(lk, [&] { return nb_command == 0; });
    }
    /* To be able to chain another DMA operation on it, return the DMA
       object itself */
    return static_cast<SpecializedDMA&>(*this);
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::nb_command, trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_mutex, and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_room.
Member Data Documentation
c
template<typename AXIStreamSwitch , typename SpecializedDMA > boost::fibers::buffered_channel< dma_command > trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::c { 8 } private
Queue for generic DMA commands.
Definition at line 113 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::pop_command(), trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::push_command(), and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::~dma().
data_mover
template<typename AXIStreamSwitch , typename SpecializedDMA > trisycl::detail::fiber_pool::future< void > trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::data_mover private
To shepherd the fiber playing the data mover behind the DMA.
Definition at line 116 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma(), and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::join().
nb_command
template<typename AXIStreamSwitch , typename SpecializedDMA > std::atomic< int > trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::nb_command { 0 } private
Count the in-flight commands.
Definition at line 119 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::commit_command(), trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::push_command(), and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::wait().
waiting_mutex
template<typename AXIStreamSwitch , typename SpecializedDMA > boost::fibers::mutex trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_mutex private
To protect the waiting mechanism.
Definition at line 125 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::wait().
waiting_room
template<typename AXIStreamSwitch , typename SpecializedDMA > boost::fibers::condition_variable trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::waiting_room private
To wait for the DMA command queue to drain.
Definition at line 122 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::commit_command(), and trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::wait().
The documentation for this class was generated from the following files:
include/sycl/vendor/Xilinx/acap/aie/dma.hpp
include/triSYCL/vendor/Xilinx/acap/aie/dma.hpp