triSYCL implementation of SYCL: trisycl::vendor::xilinx::acap::aie::device< Layout > Class Template Reference
trisycl::vendor::xilinx::acap::aie::device< Layout > Class Template Reference
Create a SYCL-like device view of an AI Engine CGRA with some layout.
#include <device.hpp>
Public Types
using geo = typename dd::geo
Expose some useful internal implementation. Look at them for their documentation.
using cass = typename dd::cass
using csp = typename dd::csp
using cmp = typename dd::cmp
using sass = typename dd::sass
using ssp = typename dd::ssp
using smp = typename dd::smp
using geo = typename dd::geo
Expose some useful internal implementation. Look at them for their documentation.
using cass = typename dd::cass
using csp = typename dd::csp
using cmp = typename dd::cmp
using sass = typename dd::sass
using ssp = typename dd::ssp
using smp = typename dd::smp
Public Types inherited from trisycl::facade::device< device< Layout >, detail::device< Layout > >
using implementation_t = detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >
The type encapsulating the implementation.
using detail_t = detail::device< Layout >
The real detail type doing the work behind the scene.
Public Member Functions
device ()
The default constructor makes a new device.
template<typename F >
void for_each_tile_index (F &&f)
Apply a function for each tile index of the device.
template<typename F >
void for_each_tile (F &&f)
Apply a function for each tile infrastructure of the device.
template<typename F >
void for_each_tile_x_index (F &&f)
Apply a function for each x tile index of the device.
template<typename F >
void for_each_tile_y_index (F &&f)
Apply a function for each y tile index of the device.
auto & tile (int x, int y)
Access to the common infrastructure part of a tile.
auto & mem (int x, int y)
Access to the common infrastructure part of a tile memory.
auto & shim (int x)
Access to the shim tile.
auto & cascade ()
Access the cascade connections.
auto queue ()
Create a queue on this device.
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
auto program ()
Create a program execution for this device.
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
void run ()
Shortcut to run synchronously a program on this queue.
template<typename Invocable >
void run (Invocable &&f)
Shortcut to run synchronously an heterogeneous invocable on this queue.
template<typename Invocable >
void uniform_run (Invocable &&f)
Shortcut to run synchronously a uniform invocable on this queue.
template<typename SrcPort , typename DstPort >
void connect (SrcPort &&src, DstPort &&dst)
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
template<typename F >
void for_each_tile_neighborhood (F &&f)
Apply a invocable on all the AXI stream of the neighborhood of each tile.
auto display (const std::string &file_name={})
Display the device layout.
device ()
The default constructor makes a new device.
template<typename F >
void for_each_tile_index (F &&f)
Apply a function for each tile index of the device.
template<typename F >
void for_each_tile (F &&f)
Apply a function for each tile infrastructure of the device.
template<typename F >
void for_each_tile_x_index (F &&f)
Apply a function for each x tile index of the device.
template<typename F >
void for_each_tile_y_index (F &&f)
Apply a function for each y tile index of the device.
auto & tile (int x, int y)
Access to the common infrastructure part of a tile.
auto & mem (int x, int y)
Access to the common infrastructure part of a tile memory.
auto & shim (int x)
Access to the shim tile.
auto & cascade ()
Access the cascade connections.
auto queue ()
Create a queue on this device.
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
auto program ()
Create a program execution for this device.
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
void run ()
Shortcut to run synchronously a program on this queue.
template<typename Invocable >
void run (Invocable &&f)
Shortcut to run synchronously an heterogeneous invocable on this queue.
template<typename Invocable >
void uniform_run (Invocable &&f)
Shortcut to run synchronously a uniform invocable on this queue.
template<typename SrcPort , typename DstPort >
void connect (SrcPort &&src, DstPort &&dst)
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
template<typename F >
void for_each_tile_neighborhood (F &&f)
Apply a invocable on all the AXI stream of the neighborhood of each tile.
auto display (const std::string &file_name={})
Display the device layout.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >
shared_ptr_implementation (std::shared_ptr< detail::device< Layout > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::device< Layout > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Static Public Attributes
static auto constexpr x_min = geo::x_min
Minimum horizontal coordinate.
static auto constexpr x_max = geo::x_max
Maximum horizontal coordinate.
static auto constexpr x_size = geo::x_size
Number of tile horizontally in the CGRA.
static auto constexpr y_min = geo::y_min
Minimum vertical coordinate.
static auto constexpr y_max = geo::y_max
Maximum vertical coordinate.
static auto constexpr y_size = geo::y_size
Number of tile vertically in the CGRA.
static auto constexpr size = geo::size
Total number of tiles in the CGRA.
Private Types
using dd = detail::device< Layout >
The type encapsulating the implementation.
using facade_t = facade::device< device< Layout >, dd >
The faade used to implement part of the use facing type.
using dd = detail::device< Layout >
The type encapsulating the implementation.
using facade_t = facade::device< device< Layout >, dd >
The faade used to implement part of the use facing type.
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >
std::shared_ptr< detail::device< Layout > > implementation
The implementation forward everything to this... implementation.
Detailed Description
template<typename Layout>
class trisycl::vendor::xilinx::acap::aie::device< Layout >
Create a SYCL-like device view of an AI Engine CGRA with some layout.
Parameters
Layout is the layout description of the machine to instantiate with the physical size
Definition at line 30 of file device.hpp.
Member Typedef Documentation
cass [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::cass = typename dd::cass
Definition at line 44 of file device.hpp.
cass [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::cass = typename dd::cass
Definition at line 44 of file device.hpp.
cmp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::cmp = typename dd::cmp
Definition at line 46 of file device.hpp.
cmp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::cmp = typename dd::cmp
Definition at line 46 of file device.hpp.
csp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::csp = typename dd::csp
Definition at line 45 of file device.hpp.
csp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::csp = typename dd::csp
Definition at line 45 of file device.hpp.
dd [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::dd = detail::device<Layout> private
The type encapsulating the implementation.
Definition at line 32 of file device.hpp.
dd [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::dd = detail::device<Layout> private
The type encapsulating the implementation.
Definition at line 32 of file device.hpp.
facade_t [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::facade_t = facade::device<device<Layout>, dd> private
The faade used to implement part of the use facing type.
Definition at line 35 of file device.hpp.
facade_t [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::facade_t = facade::device<device<Layout>, dd> private
The faade used to implement part of the use facing type.
Definition at line 35 of file device.hpp.
geo [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::geo = typename dd::geo
Expose some useful internal implementation. Look at them for their documentation.
Definition at line 43 of file device.hpp.
geo [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::geo = typename dd::geo
Expose some useful internal implementation. Look at them for their documentation.
Definition at line 43 of file device.hpp.
sass [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::sass = typename dd::sass
Definition at line 47 of file device.hpp.
sass [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::sass = typename dd::sass
Definition at line 47 of file device.hpp.
smp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::smp = typename dd::smp
Definition at line 49 of file device.hpp.
smp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::smp = typename dd::smp
Definition at line 49 of file device.hpp.
ssp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::ssp = typename dd::ssp
Definition at line 48 of file device.hpp.
ssp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::device< Layout >::ssp = typename dd::ssp
Definition at line 48 of file device.hpp.
Constructor & Destructor Documentation
device() [1/2]
template<typename Layout > trisycl::vendor::xilinx::acap::aie::device< Layout >::device () inline
The default constructor makes a new device.
Definition at line 75 of file device.hpp.
      : facade_t { std::make_shared<dd>() } {}
device() [2/2]
template<typename Layout > trisycl::vendor::xilinx::acap::aie::device< Layout >::device () inline
The default constructor makes a new device.
Definition at line 75 of file device.hpp.
      : facade_t { std::make_shared<dd>() } {}
Member Function Documentation
cascade() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::cascade () inline
Access the cascade connections.
Todo:
To remove?
Definition at line 144 of file device.hpp.
{ return implementation->cascade(); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
cascade() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::cascade () inline
Access the cascade connections.
Todo:
To remove?
Definition at line 144 of file device.hpp.
{ return implementation->cascade(); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
connect() [1/2]
template<typename Layout > template<typename SrcPort , typename DstPort > void trisycl::vendor::xilinx::acap::aie::device< Layout >::connect (SrcPort && src, DstPort && dst) inline
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
This is used to speed up communication in emulation and to skip the need of a routing planner.
Todo:
To deprecate and implement in another way?
Parameters
[in] T is the type of the data to be transferred
[in] SrcPort is the type of the source port, such as port::tile or port::shim
[in] DstPort is the type of the destination port, such as port::tile or port::shim
Exceptions
trisycl::runtime_error if some coordinates or port numbers are invalid
Todo:
Refactor, make the difference between user & physical ports
Definition at line 223 of file device.hpp.
{
    implementation->connect(std::forward<SrcPort>(src),
                            std::forward<DstPort>(dst));
  }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, and src.
connect() [2/2]
template<typename Layout > template<typename SrcPort , typename DstPort > void trisycl::vendor::xilinx::acap::aie::device< Layout >::connect (SrcPort && src, DstPort && dst) inline
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
This is used to speed up communication in emulation and to skip the need of a routing planner.
Todo:
To deprecate and implement in another way?
Parameters
[in] T is the type of the data to be transferred
[in] SrcPort is the type of the source port, such as port::tile or port::shim
[in] DstPort is the type of the destination port, such as port::tile or port::shim
Exceptions
trisycl::runtime_error if some coordinates or port numbers are invalid
Todo:
Refactor, make the difference between user & physical ports
Definition at line 223 of file device.hpp.
{
    implementation->connect(std::forward<SrcPort>(src),
                            std::forward<DstPort>(dst));
  }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, and src.
display() [1/2]
template<typename Layout > auto trisycl::vendor::xilinx::acap::aie::device< Layout >::display (const std::string & file_name = {}) inline
Display the device layout.
Parameters
[in] file_name is the name of the file to write the LaTeX drawing into or use std::cerr by default
Definition at line 239 of file device.hpp.
                                            {}) {
    return implementation->display(file_name);
  }
display() [2/2]
template<typename Layout > auto trisycl::vendor::xilinx::acap::aie::device< Layout >::display (const std::string & file_name = {}) inline
Display the device layout.
Parameters
[in] file_name is the name of the file to write the LaTeX drawing into or use std::cerr by default
Definition at line 239 of file device.hpp.
                                            {}) {
    return implementation->display(file_name);
  }
for_each_tile() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile (F && f) inline
Apply a function for each tile infrastructure of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 92 of file device.hpp.
{
    implementation->for_each_tile(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile (F && f) inline
Apply a function for each tile infrastructure of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 92 of file device.hpp.
{
    implementation->for_each_tile(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_index() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_index (F && f) inline
Apply a function for each tile index of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 83 of file device.hpp.
{
    implementation->for_each_tile_index(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_index() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_index (F && f) inline
Apply a function for each tile index of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 83 of file device.hpp.
{
    implementation->for_each_tile_index(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_neighborhood() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_neighborhood (F && f) inline
Apply a invocable on all the AXI stream of the neighborhood of each tile.
Definition at line 230 of file device.hpp.
{
    implementation->for_each_tile_neighborhood(std::forward<F>(f));
  }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_neighborhood() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_neighborhood (F && f) inline
Apply a invocable on all the AXI stream of the neighborhood of each tile.
Definition at line 230 of file device.hpp.
{
    implementation->for_each_tile_neighborhood(std::forward<F>(f));
  }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_x_index() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_x_index (F && f) inline
Apply a function for each x tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each horizontal index value
Definition at line 101 of file device.hpp.
{
    implementation->for_each_tile_x_index(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_x_index() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_x_index (F && f) inline
Apply a function for each x tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each horizontal index value
Definition at line 101 of file device.hpp.
{
    implementation->for_each_tile_x_index(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_y_index() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_y_index (F && f) inline
Apply a function for each y tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each vertical index value
Definition at line 110 of file device.hpp.
{
    implementation->for_each_tile_y_index(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
for_each_tile_y_index() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::device< Layout >::for_each_tile_y_index (F && f) inline
Apply a function for each y tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each vertical index value
Definition at line 110 of file device.hpp.
{
    implementation->for_each_tile_y_index(std::forward<F>(f));
  };
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation.
mem() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::mem (int x, int y) inline
Access to the common infrastructure part of a tile memory.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 132 of file device.hpp.
{ return implementation->mem(x, y); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, x, and trisycl::y.
mem() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::mem (int x, int y) inline
Access to the common infrastructure part of a tile memory.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 132 of file device.hpp.
{ return implementation->mem(x, y); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, x, and trisycl::y.
program() [1/2]
template<typename Layout > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> auto trisycl::vendor::xilinx::acap::aie::device< Layout >::program () inline
Create a program execution for this device.
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
Definition at line 161 of file device.hpp.
                 {
    return aie::program<device, Tile, Memory> { *this };
  }
program() [2/2]
template<typename Layout > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> auto trisycl::vendor::xilinx::acap::aie::device< Layout >::program () inline
Create a program execution for this device.
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
Definition at line 161 of file device.hpp.
                 {
    return aie::program<device, Tile, Memory> { *this };
  }
queue() [1/2]
template<typename Layout > auto trisycl::vendor::xilinx::acap::aie::device< Layout >::queue () inline
Create a queue on this device.
Definition at line 147 of file device.hpp.
{ return vendor::xilinx::acap::aie::queue { *this }; }
Referenced by trisycl::vendor::xilinx::acap::aie::device< Layout >::run(), and trisycl::vendor::xilinx::acap::aie::device< Layout >::uniform_run().
queue() [2/2]
template<typename Layout > auto trisycl::vendor::xilinx::acap::aie::device< Layout >::queue () inline
Create a queue on this device.
Definition at line 147 of file device.hpp.
{ return vendor::xilinx::acap::aie::queue { *this }; }
run() [1/4]
template<typename Layout > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::device< Layout >::run () inline
Shortcut to run synchronously a program on this queue.
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
Definition at line 177 of file device.hpp.
             {
    queue().template run<Tile, Memory>();
  }
References trisycl::vendor::xilinx::acap::aie::device< Layout >::queue().
run() [2/4]
template<typename Layout > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::device< Layout >::run () inline
Shortcut to run synchronously a program on this queue.
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
Definition at line 177 of file device.hpp.
             {
    queue().template run<Tile, Memory>();
  }
References trisycl::vendor::xilinx::acap::aie::device< Layout >::queue().
run() [3/4]
template<typename Layout > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::device< Layout >::run (Invocable && f) inline
Shortcut to run synchronously an heterogeneous invocable on this queue.
Parameters
f is an invocable taking an heterogeneous tile handler
Definition at line 186 of file device.hpp.
{
    queue().run(std::forward<Invocable>(f));
  }
References trisycl::vendor::xilinx::acap::aie::device< Layout >::queue().
run() [4/4]
template<typename Layout > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::device< Layout >::run (Invocable && f) inline
Shortcut to run synchronously an heterogeneous invocable on this queue.
Parameters
f is an invocable taking an heterogeneous tile handler
Definition at line 186 of file device.hpp.
{
    queue().run(std::forward<Invocable>(f));
  }
References trisycl::vendor::xilinx::acap::aie::device< Layout >::queue().
shim() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::shim (int x) inline
Access to the shim tile.
Parameters
[in] x is the horizontal coordinate of the shim tile
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 140 of file device.hpp.
{ return implementation->shim(x); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, and x.
shim() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::shim (int x) inline
Access to the shim tile.
Parameters
[in] x is the horizontal coordinate of the shim tile
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 140 of file device.hpp.
{ return implementation->shim(x); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, and x.
tile() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::tile (int x, int y) inline
Access to the common infrastructure part of a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 122 of file device.hpp.
{ return implementation->tile(x, y); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, x, and trisycl::y.
tile() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::device< Layout >::tile (int x, int y) inline
Access to the common infrastructure part of a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 122 of file device.hpp.
{ return implementation->tile(x, y); }
References trisycl::detail::shared_ptr_implementation< device< Layout >, detail::device< Layout > >::implementation, x, and trisycl::y.
uniform_run() [1/2]
template<typename Layout > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::device< Layout >::uniform_run (Invocable && f) inline
Shortcut to run synchronously a uniform invocable on this queue.
Parameters
f is an invocable taking a uniform tile handler
Definition at line 195 of file device.hpp.
{
    queue().uniform_run(std::forward<Invocable>(f));
    queue().wait();
  }
References trisycl::vendor::xilinx::acap::aie::device< Layout >::queue().
uniform_run() [2/2]
template<typename Layout > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::device< Layout >::uniform_run (Invocable && f) inline
Shortcut to run synchronously a uniform invocable on this queue.
Parameters
f is an invocable taking a uniform tile handler
Definition at line 195 of file device.hpp.
{
    queue().uniform_run(std::forward<Invocable>(f));
    queue().wait();
  }
References trisycl::vendor::xilinx::acap::aie::device< Layout >::queue().
Member Data Documentation
size
template<typename Layout > auto constexpr trisycl::vendor::xilinx::acap::aie::device< Layout >::size = geo::size static constexpr
Total number of tiles in the CGRA.
Definition at line 72 of file device.hpp.
x_max
template<typename Layout > auto constexpr trisycl::vendor::xilinx::acap::aie::device< Layout >::x_max = geo::x_max static constexpr
Maximum horizontal coordinate.
Definition at line 57 of file device.hpp.
x_min
template<typename Layout > auto constexpr trisycl::vendor::xilinx::acap::aie::device< Layout >::x_min = geo::x_min static constexpr
Minimum horizontal coordinate.
Definition at line 54 of file device.hpp.
x_size
template<typename Layout > auto constexpr trisycl::vendor::xilinx::acap::aie::device< Layout >::x_size = geo::x_size static constexpr
Number of tile horizontally in the CGRA.
Definition at line 60 of file device.hpp.
y_max
template<typename Layout > auto constexpr trisycl::vendor::xilinx::acap::aie::device< Layout >::y_max = geo::y_max static constexpr
Maximum vertical coordinate.
Definition at line 66 of file device.hpp.
y_min
template<typename Layout > auto constexpr trisycl::vendor::xilinx::acap::aie::device< Layout >::y_min = geo::y_min static constexpr
Minimum vertical coordinate.
Definition at line 63 of file device.hpp.
y_size
template<typename Layout > auto constexpr trisycl::vendor::xilinx::acap::aie::device< Layout >::y_size = geo::y_size static constexpr
Number of tile vertically in the CGRA.
Definition at line 69 of file device.hpp.
The documentation for this class was generated from the following files:
include/sycl/vendor/Xilinx/acap/aie/device.hpp
include/triSYCL/vendor/Xilinx/acap/aie/device.hpp