triSYCL implementation of SYCL: cl::sycl::detail::vec< DataType, NumElements > Class Template Reference
cl::sycl::detail::vec< DataType, NumElements > Class Template Reference
Small OpenCL vector class.
#include <vec.hpp>
Public Member Functions
template<typename... Types>
vec (const Types... args)
Construct a vec from anything from a scalar (to initialize all the elements with this value) up to an aggregate of scalar and vector types (in this case the total number of elements must match the size of the vector)
vec ()=default
Use classical constructors too.
auto get_count () const
Return the number of elements in the vector.
auto get_size () const
Return the number of bytes.
template<typename convertT , rounding_mode roundingMode>
vec< convertT, NumElements > convert () const
template<typename asT >
asT as () const
template<int... swizzleIndexs>
__swizzled_vec__< DataType, sizeof...(swizzleIndexs)> swizzle () const
Public Member Functions inherited from cl::sycl::detail::small_array< DataType, cl::sycl::vec< DataType, NumElements >, NumElements >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
auto get (std::size_t index) const
Return the element of the array.
operator cl::sycl::vec< DataType, NumElements > ()
Add + like operations on the id<> and others.
Public Member Functions inherited from cl::sycl::detail::display_vector< cl::sycl::vec< DataType, NumElements > >
void display () const
To debug and test.
Protected Member Functions
template<typename... Ts>
__swizzled_base_vec__< DataType, sizeof...(Ts)> swizzle (Ts... swizzleIndexes) const
Apply a swizzle operation from swizzleIndexes parameters.
Private Types
using basic_type = typename detail::small_array< DataType, cl::sycl::vec< DataType, NumElements >, NumElements >
Static Private Member Functions
template<typename V , typename Element , int s>
static auto flatten (const vec< Element, s > i)
Flattening helper that does not change scalar values but flatten a vec<T, n> v into a tuple<T, T,..., T>{ v[0], v[1],..., v[n-1] }.
template<typename V , typename Element , int s>
static auto flatten (const cl::sycl::vec< Element, s > i)
template<typename V , typename Type >
static auto flatten (const Type i)
If we do not have a vector, just forward it as a tuple up to the final initialization.
template<typename V , typename... Types>
static auto flatten_to_tuple (const Types... i)
Take some initializer values and apply flattening on each value.
Additional Inherited Members
Public Types inherited from cl::sycl::detail::small_array< DataType, cl::sycl::vec< DataType, NumElements >, NumElements >
using element_type = DataType
Static Public Attributes inherited from cl::sycl::detail::small_array< DataType, cl::sycl::vec< DataType, NumElements >, NumElements >
static const auto dimensionality
static const size_t dimension
Detailed Description
template<typename DataType, int NumElements>
class cl::sycl::detail::vec< DataType, NumElements >
Small OpenCL vector class.
Definition at line 21 of file vec.hpp.
Member Typedef Documentation
basic_type
template<typename DataType, int NumElements> using cl::sycl::detail::vec< DataType, NumElements >::basic_type = typename detail::small_array<DataType, cl::sycl::vec<DataType, NumElements>, NumElements> private
Definition at line 33 of file vec.hpp.
Constructor & Destructor Documentation
vec() [1/2]
template<typename DataType, int NumElements> template<typename... Types> cl::sycl::detail::vec< DataType, NumElements >::vec (const Types... args) inline
Construct a vec from anything from a scalar (to initialize all the elements with this value) up to an aggregate of scalar and vector types (in this case the total number of elements must match the size of the vector)
Definition at line 42 of file vec.hpp.
     : basic_type { detail::expand<vec>(flatten_to_tuple<vec>(args...)) } { }
vec() [2/2]
template<typename DataType, int NumElements> cl::sycl::detail::vec< DataType, NumElements >::vec () default
Use classical constructors too.
Referenced by cl::sycl::detail::vec< DataType, 8 >::vec().
Member Function Documentation
as()
template<typename DataType, int NumElements> template<typename asT > asT cl::sycl::detail::vec< DataType, NumElements >::as () const inline
Definition at line 132 of file vec.hpp.
{
     asT result;
     assert(result.get_size() == this->get_size());
     std::memcpy(result.data(), this->data(), this->get_size());
     return result;
   };
convert()
template<typename DataType, int NumElements> template<typename convertT , rounding_mode roundingMode> vec<convertT, NumElements> cl::sycl::detail::vec< DataType, NumElements >::convert () const inline
Definition at line 122 of file vec.hpp.
{
     vec<convertT, NumElements> result;
     assert(result.get_count() == this->get_count());
     for (int n = 0; n < NumElements; n++) {
       result[n] = (*this)[n];
     }
     return result;
   };
flatten() [1/3]
template<typename DataType, int NumElements> template<typename V , typename Element , int s> static auto cl::sycl::detail::vec< DataType, NumElements >::flatten (const vec< Element, s > i) inline static private
Flattening helper that does not change scalar values but flatten a vec<T, n> v into a tuple<T, T,..., T>{ v[0], v[1],..., v[n-1] }.
If we have a vector, just forward its array content since an array has also a tuple interface :-) (23.3.2.9 Tuple interface to class template array [array.tuple])
Definition at line 63 of file vec.hpp.
{
     static_assert(s <= V::dimension,
                   "The element i will not fit in the vector");
     return static_cast<std::array<Element, s>>(i);
   }
flatten() [2/3]
template<typename DataType, int NumElements> template<typename V , typename Element , int s> static auto cl::sycl::detail::vec< DataType, NumElements >::flatten (const cl::sycl::vec< Element, s > i) inline static private
Definition at line 70 of file vec.hpp.
{
     static_assert(s <= V::dimension,
                   "The element i will not fit in the vector");
     return static_cast<std::array<Element, s>>(i);
   }
flatten() [3/3]
template<typename DataType, int NumElements> template<typename V , typename Type > static auto cl::sycl::detail::vec< DataType, NumElements >::flatten (const Type i) inline static private
If we do not have a vector, just forward it as a tuple up to the final initialization.
Returns
typically tuple<double>{ 2.4 } from 2.4 input for example
Definition at line 83 of file vec.hpp.
{
     return std::make_tuple(i);
   }
flatten_to_tuple()
template<typename DataType, int NumElements> template<typename V , typename... Types> static auto cl::sycl::detail::vec< DataType, NumElements >::flatten_to_tuple (const Types... i) inline static private
Take some initializer values and apply flattening on each value.
Returns
a tuple of scalar initializer values
Definition at line 93 of file vec.hpp.
{
     // Concatenate the tuples returned by each flattening
     return std::tuple_cat(flatten<V>(i)...);
   }
get_count()
template<typename DataType, int NumElements> auto cl::sycl::detail::vec< DataType, NumElements >::get_count () const inline
Return the number of elements in the vector.
Definition at line 112 of file vec.hpp.
Referenced by cl::sycl::detail::vec< DataType, 8 >::convert().
{
     return NumElements;
   }
get_size()
template<typename DataType, int NumElements> auto cl::sycl::detail::vec< DataType, NumElements >::get_size () const inline
Return the number of bytes.
Definition at line 117 of file vec.hpp.
Referenced by cl::sycl::detail::vec< DataType, 8 >::as().
{
     return NumElements * sizeof(DataType);
   }
swizzle() [1/2]
template<typename DataType, int NumElements> template<typename... Ts> __swizzled_base_vec__<DataType, sizeof...(Ts)> cl::sycl::detail::vec< DataType, NumElements >::swizzle (Ts... swizzleIndexes) const inline protected
Apply a swizzle operation from swizzleIndexes parameters.
Definition at line 103 of file vec.hpp.
{
     // Construct a new vector from an elemental swizzle of each element
     return __swizzled_base_vec__<DataType, sizeof...(Ts)> {
       (*this)[swizzleIndexes]... };
   }
swizzle() [2/2]
template<typename DataType, int NumElements> template<int... swizzleIndexs> __swizzled_vec__<DataType, sizeof...(swizzleIndexs)> cl::sycl::detail::vec< DataType, NumElements >::swizzle () const inline
Definition at line 141 of file vec.hpp.
Referenced by cl::sycl::detail::vec< DataType, 8 >::swizzle().
{
     return static_cast<__swizzled_vec__<DataType, sizeof...(swizzleIndexs)>>(swizzle(swizzleIndexs...));
   }
The documentation for this class was generated from the following file:
include/CL/sycl/vec/detail/vec.hpp