triSYCL implementation of SYCL: trisycl::detail::opencl_device Class Reference
trisycl::detail::opencl_device Class Reference
SYCL OpenCL device.
#include <opencl_device.hpp>
Public Member Functions
cl_device_id get () const override
Return the cl_device_id of the underlying OpenCL device.
boost::compute::device & get_boost_compute () override
Return the underlying Boost.Compute device.
bool is_host () const override
Return false since an OpenCL device is not the SYCL host device.
bool is_cpu () const override
Test if the OpenCL is a CPU device.
bool is_gpu () const override
Test if the OpenCL is a GPU device.
bool is_accelerator () const override
Test if the OpenCL is an accelerator device.
trisycl::platform get_platform () const override
Return the platform of device.
std::any get_info (info::device param) const override
Query the device for OpenCL info::device info.
bool has_extension (const string_class &extension) const override
Specify whether a specific extension is supported on the device.
~opencl_device () override
Unregister from the cache on destruction.
Public Member Functions inherited from trisycl::detail::device
virtual ~device ()
Static Public Member Functions
static std::shared_ptr< opencl_device > instance (const boost::compute::device &d)
Private Member Functions
template<info::device param>
std::any get_info () const
opencl_device (const boost::compute::device &d)
Only the instance factory can build it.
Private Attributes
boost::compute::device d
Use the Boost Compute abstraction of the OpenCL device.
Static Private Attributes
static detail::cache< cl_device_id, detail::opencl_device > cache
A cache to always return the same alive device for a given OpenCL device.
Detailed Description
SYCL OpenCL device.
Definition at line 28 of file opencl_device.hpp.
Constructor & Destructor Documentation
opencl_device()
trisycl::detail::opencl_device::opencl_device (const boost::compute::device & d) inline private
Only the instance factory can build it.
Definition at line 114 of file opencl_device.hpp.
 : d { d } {}
~opencl_device()
trisycl::detail::opencl_device::~opencl_device () inline override
Unregister from the cache on destruction.
Definition at line 119 of file opencl_device.hpp.
References cache, trisycl::detail::cache< Key, Value >::remove(), TRISYCL_WEAK_ATTRIB_PREFIX, and trisycl::detail::TRISYCL_WEAK_ATTRIB_SUFFIX.
{
     cache.remove(d.id());
   }
Member Function Documentation
get()
cl_device_id trisycl::detail::opencl_device::get () const inline override virtual
Return the cl_device_id of the underlying OpenCL device.
Implements trisycl::detail::device.
Definition at line 43 of file opencl_device.hpp.
{
     return d.id();
   }
get_boost_compute()
boost::compute::device& trisycl::detail::opencl_device::get_boost_compute () inline override virtual
Return the underlying Boost.Compute device.
Implements trisycl::detail::device.
Definition at line 49 of file opencl_device.hpp.
References d.
{
     return d;
   }
get_info() [1/2]
std::any trisycl::detail::opencl_device::get_info (info::device param) const inline override virtual
Query the device for OpenCL info::device info.
Return synchronous errors via the SYCL exception class.
Implements trisycl::detail::device.
Definition at line 12 of file opencl_device_tail.hpp.
References trisycl::info::cpu, d, trisycl::info::gpu, trisycl::info::local, trisycl::info::no_partition, trisycl::info::none, trisycl::info::not_applicable, TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE, and TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE.
{
   switch (param) {
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(
   device_type,
   d.get_info<CL_DEVICE_TYPE>() == CL_DEVICE_TYPE_CPU
   ? info::device_type::cpu : info::device_type::gpu);
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(vendor_id, VENDOR_ID)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_compute_units, MAX_COMPUTE_UNITS )
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_work_item_dimensions,
                                        MAX_WORK_ITEM_DIMENSIONS)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(
   max_work_item_sizes,
   (::trisycl::id<3> { d.get_info<CL_DEVICE_MAX_WORK_ITEM_SIZES>()[0]
                     , d.get_info<CL_DEVICE_MAX_WORK_ITEM_SIZES>()[1]
                     , d.get_info<CL_DEVICE_MAX_WORK_ITEM_SIZES>()[2] }))
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_work_group_size, MAX_WORK_GROUP_SIZE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(preferred_vector_width_char,
                                        PREFERRED_VECTOR_WIDTH_CHAR)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(preferred_vector_width_short,
                                        PREFERRED_VECTOR_WIDTH_SHORT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(preferred_vector_width_int,
                                        PREFERRED_VECTOR_WIDTH_INT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(preferred_vector_width_long,
                                        PREFERRED_VECTOR_WIDTH_LONG)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(preferred_vector_width_float,
                                        PREFERRED_VECTOR_WIDTH_FLOAT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(preferred_vector_width_double,
                                        PREFERRED_VECTOR_WIDTH_DOUBLE)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(preferred_vector_width_half,
                                     ::trisycl::cl_uint { 0 })
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(native_vector_width_char,
                                        NATIVE_VECTOR_WIDTH_CHAR)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(native_vector_width_short,
                                        NATIVE_VECTOR_WIDTH_SHORT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(native_vector_width_int,
                                        NATIVE_VECTOR_WIDTH_INT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(native_vector_width_long,
                                        NATIVE_VECTOR_WIDTH_LONG)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(native_vector_width_float,
                                        NATIVE_VECTOR_WIDTH_FLOAT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(native_vector_width_double,
                                        NATIVE_VECTOR_WIDTH_DOUBLE)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(native_vector_width_half,
                                     ::trisycl::cl_uint { 0 })
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_clock_frequency, MAX_CLOCK_FREQUENCY)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(address_bits, ADDRESS_BITS)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_mem_alloc_size, MAX_MEM_ALLOC_SIZE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(image_support, IMAGE_SUPPORT )
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_read_image_args, MAX_READ_IMAGE_ARGS)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_write_image_args,
                                        MAX_WRITE_IMAGE_ARGS)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(image2d_max_width, IMAGE2D_MAX_WIDTH)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(image2d_max_height, IMAGE2D_MAX_HEIGHT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(image3d_max_width, IMAGE3D_MAX_WIDTH)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(image3d_max_height, IMAGE3D_MAX_HEIGHT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(image3d_max_depth, IMAGE3D_MAX_DEPTH)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(image_max_buffer_size, size_t { 0 })
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(image_max_array_size, size_t { 0 })
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_samplers, MAX_SAMPLERS)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(max_parameter_size, MAX_PARAMETER_SIZE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(mem_base_addr_align, MEM_BASE_ADDR_ALIGN)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(half_fp_config,
                                     vector_class<info::fp_config>{} )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(single_fp_config,
                                     vector_class<info::fp_config>{} )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(double_fp_config,
                                     vector_class<info::fp_config>{} )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(global_mem_cache_type,
                                     info::global_mem_cache_type::none )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(
   global_mem_cache_line_size,
   ::trisycl::cl_uint { static_cast<::trisycl::cl_uint>
       (d.get_info<CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE>()) })
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(global_mem_cache_size,
                                        GLOBAL_MEM_CACHE_SIZE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(global_mem_size, GLOBAL_MEM_SIZE)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(max_constant_buffer_size,
                                     ::trisycl::cl_ulong { 0 } )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(max_constant_args,
                                     ::trisycl::cl_uint { 0 } )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(local_mem_type, info::local_mem_type::local)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(local_mem_size, LOCAL_MEM_SIZE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(error_correction_support,
                                        ERROR_CORRECTION_SUPPORT)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(host_unified_memory,
                                        HOST_UNIFIED_MEMORY)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(profiling_timer_resolution,
                                        PROFILING_TIMER_RESOLUTION)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(is_endian_little, ENDIAN_LITTLE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(is_available, AVAILABLE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(is_compiler_available,
                                        COMPILER_AVAILABLE)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(is_linker_available, false)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(execution_capabilities,
                                     vector_class<info::execution_capability>{} )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(queue_profiling, false)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(built_in_kernels,
                                     vector_class<string_class>{} )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(platform, ::trisycl::platform{} )
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(name, NAME)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(vendor, VENDOR)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(driver_version,
                                     d.get_info<CL_DRIVER_VERSION>())
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(profile, PROFILE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(version, VERSION)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(opencl_c_version, OPENCL_C_VERSION )
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(extensions, vector_class<string_class>{} )
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(printf_buffer_size, PRINTF_BUFFER_SIZE)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(preferred_interop_user_sync,
                                        PREFERRED_INTEROP_USER_SYNC)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(parent_device, ::trisycl::device{})
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(partition_max_sub_devices,
                                     ::trisycl::cl_uint { 0 })
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(partition_properties,
                                     vector_class<info::partition_property>{})
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(
   partition_affinity_domains,
   vector_class<info::partition_affinity_domain>{})
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(partition_type_property,
                                     info::partition_property::no_partition)
 TRISYCL_DEFINE_DEVICE_INFO_TEMPLATE(
   partition_type_affinity_domain,
   info::partition_affinity_domain::not_applicable)
 TRISYCL_DEFINE_DEVICE_INFO_CL_TEMPLATE(reference_count, REFERENCE_COUNT)
   default:
     return 0;
   }
 }
get_info() [2/2]
template<info::device param> std::any trisycl::detail::opencl_device::get_info () const inline private
Referenced by get_platform(), and instance().
get_platform()
trisycl::platform trisycl::detail::opencl_device::get_platform () const inline override virtual
Return the platform of device.
Return synchronous errors via the SYCL exception class.
Implements trisycl::detail::device.
Definition at line 85 of file opencl_device.hpp.
References get_info(), and trisycl::platform::platform().
{
     return d.platform();
   }
has_extension()
bool trisycl::detail::opencl_device::has_extension (const string_class & extension) const inline override virtual
Specify whether a specific extension is supported on the device.
Implements trisycl::detail::device.
Definition at line 97 of file opencl_device.hpp.
{
     return d.supports_extension(extension);
   }
instance()
static std::shared_ptr<opencl_device> trisycl::detail::opencl_device::instance (const boost::compute::device & d) inline static
Definition at line 104 of file opencl_device.hpp.
References get_info(), and trisycl::detail::cache< Key, Value >::get_or_register().
Referenced by trisycl::device::device().
{
     return cache.get_or_register(d.id(),
                                  [&] { return new opencl_device { d }; });
   }
is_accelerator()
bool trisycl::detail::opencl_device::is_accelerator () const inline override virtual
Test if the OpenCL is an accelerator device.
Implements trisycl::detail::device.
Definition at line 75 of file opencl_device.hpp.
{
     // Even in Boost.Compute the type is a bit-field, so use & instead of ==
     return d.type() & boost::compute::device::accelerator;
   }
is_cpu()
bool trisycl::detail::opencl_device::is_cpu () const inline override virtual
Test if the OpenCL is a CPU device.
Implements trisycl::detail::device.
Definition at line 61 of file opencl_device.hpp.
{
     // Even in Boost.Compute the type is a bit-field, so use & instead of ==
     return d.type() & boost::compute::device::cpu;
   }
is_gpu()
bool trisycl::detail::opencl_device::is_gpu () const inline override virtual
Test if the OpenCL is a GPU device.
Implements trisycl::detail::device.
Definition at line 68 of file opencl_device.hpp.
{
     // Even in Boost.Compute the type is a bit-field, so use & instead of ==
     return d.type() & boost::compute::device::gpu;
   }
is_host()
bool trisycl::detail::opencl_device::is_host () const inline override virtual
Return false since an OpenCL device is not the SYCL host device.
Implements trisycl::detail::device.
Definition at line 55 of file opencl_device.hpp.
{
     return false;
   }
Member Data Documentation
cache
detail::cache<cl_device_id, detail::opencl_device> trisycl::detail::opencl_device::cache static private
A cache to always return the same alive device for a given OpenCL device.
C++11 guaranties the static construction is thread-safe
Definition at line 38 of file opencl_device.hpp.
Referenced by ~opencl_device().
d
boost::compute::device trisycl::detail::opencl_device::d private
Use the Boost Compute abstraction of the OpenCL device.
Definition at line 31 of file opencl_device.hpp.
Referenced by get_boost_compute(), and get_info().
The documentation for this class was generated from the following files:
include/triSYCL/device/detail/opencl_device.hpp
include/triSYCL/device/detail/opencl_device_tail.hpp