triSYCL implementation of SYCL: trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch > Class Template Reference
trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch > Class Template Reference
Receiving DMA.
#include <dma.hpp>
Public Member Functions
receiving_dma (AXIStreamSwitch &axi_ss, ::trisycl::detail::fiber_pool &fe)
Start the receiving DMA engine using an executor.
void receive (std::span< axi_packet::value_type > sp)
Enqueue a DMA transfer to receive a span.
void write (const axi_packet &v) override
The network sends some data to the DMA receiver input.
bool try_write (const axi_packet &v) override
The network try to send some data to the DMA receiver input.
axi_packet::value_type read () override
Waiting read by a tile program on a core input port from the switch.
bool try_read (axi_packet::value_type &v) override
Non-blocking read to a core input port.
receiving_dma (AXIStreamSwitch &axi_ss, ::trisycl::detail::fiber_pool &fe)
Start the receiving DMA engine using an executor.
void receive (std::span< axi_packet::value_type > sp)
Enqueue a DMA transfer to receive a span.
void write (const axi_packet &v) override
The network sends some data to the DMA receiver input.
bool try_write (const axi_packet &v) override
The network try to send some data to the DMA receiver input.
axi_packet::value_type read () override
Waiting read by a tile program on a core input port from the switch.
bool try_read (axi_packet::value_type &v) override
Non-blocking read to a core input port.
Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, receiving_dma< AXIStreamSwitch > >
dma (::trisycl::detail::fiber_pool &fe)
Start the DMA engine using an executor.
dma (::trisycl::detail::fiber_pool &fe)
Start the DMA engine using an executor.
~dma ()
Destructor handling the correct infrastructure shutdown.
~dma ()
Destructor handling the correct infrastructure shutdown.
receiving_dma< AXIStreamSwitch > & wait ()
Wait for the transfers to complete.
receiving_dma< AXIStreamSwitch > & wait ()
Wait for the transfers to complete.
Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::communicator_port
virtual void write (const axi_packet &)=0
Enqueue a packet on the communicator input.
auto & operator<< (const axi_packet::value_type &v)
Alias to enqueue a packet on the communicator input.
virtual bool try_write (const axi_packet &)=0
Try to enqueue a packet to input.
virtual axi_packet::value_type read ()=0
Waiting read to a core input port.
virtual bool try_read (axi_packet::value_type &)=0
Non-blocking read from a communicator output port.
template<typename T >
auto & operator>> (T &v)
Alias to the waiting read to a communicator output port.
virtual ~communicator_port ()=default
Nothing specific to do but need a virtual destructor to avoid slicing.
virtual void write (const axi_packet &)=0
Enqueue a packet on the communicator input.
auto & operator<< (const axi_packet::value_type &v)
Alias to enqueue a packet on the communicator input.
virtual bool try_write (const axi_packet &)=0
Try to enqueue a packet to input.
virtual axi_packet::value_type read ()=0
Waiting read to a core input port.
virtual bool try_read (axi_packet::value_type &)=0
Non-blocking read from a communicator output port.
template<typename T >
auto & operator>> (T &v)
Alias to the waiting read to a communicator output port.
virtual ~communicator_port ()=default
Nothing specific to do but need a virtual destructor to avoid slicing.
Private Types
using dma_base = dma< AXIStreamSwitch, receiving_dma< AXIStreamSwitch > >
using dma_base = dma< AXIStreamSwitch, receiving_dma< AXIStreamSwitch > >
Private Attributes
boost::fibers::buffered_channel< axi_packet > fifo { 8 }
AXIStreamSwitch & axi_ss
Keep track of the AXI stream switch owning this port for debugging.
Additional Inherited Members
Protected Member Functions inherited from trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, receiving_dma< AXIStreamSwitch > >
void push_command (Cmd &&command)
Enqueue a DMA command.
void push_command (Cmd &&command)
Enqueue a DMA command.
Detailed Description
template<typename AXIStreamSwitch>
class trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >
Receiving DMA.
Todo:
Factorize out the FIFO port
Todo:
Factorize out the FIFO port
Definition at line 202 of file dma.hpp.
Member Typedef Documentation
dma_base [1/2]
template<typename AXIStreamSwitch > using trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::dma_base = dma<AXIStreamSwitch, receiving_dma<AXIStreamSwitch> > private
Definition at line 205 of file dma.hpp.
dma_base [2/2]
template<typename AXIStreamSwitch > using trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::dma_base = dma<AXIStreamSwitch, receiving_dma<AXIStreamSwitch> > private
Definition at line 205 of file dma.hpp.
Constructor & Destructor Documentation
receiving_dma() [1/2]
template<typename AXIStreamSwitch > trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::receiving_dma (AXIStreamSwitch & axi_ss, ::trisycl::detail::fiber_pool & fe) inline
Start the receiving DMA engine using an executor.
Definition at line 219 of file dma.hpp.
      : dma_base { fe }
      , axi_ss { axi_ss } {}
receiving_dma() [2/2]
template<typename AXIStreamSwitch > trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::receiving_dma (AXIStreamSwitch & axi_ss, ::trisycl::detail::fiber_pool & fe) inline
Start the receiving DMA engine using an executor.
Definition at line 219 of file dma.hpp.
      : dma_base { fe }
      , axi_ss { axi_ss } {}
Member Function Documentation
read() [1/2]
template<typename AXIStreamSwitch > axi_packet::value_type trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::read () inline override virtual
Waiting read by a tile program on a core input port from the switch.
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 253 of file dma.hpp.
{ return fifo.value_pop().data; }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo.
Referenced by trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::receive().
read() [2/2]
template<typename AXIStreamSwitch > axi_packet::value_type trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::read () inline override virtual
Waiting read by a tile program on a core input port from the switch.
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 253 of file dma.hpp.
{ return fifo.value_pop().data; }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo.
receive() [1/2]
template<typename AXIStreamSwitch > void trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::receive (std::span< axi_packet::value_type > sp) inline
Enqueue a DMA transfer to receive a span.
Use std::span for 1D contiguous transfers only for now
Definition at line 227 of file dma.hpp.
{
    this->push_command([=, this] {
      /* Write each element received from input router port into the
         memory described by DMA operation */
      for (auto& e : sp) {
        e = read();
      }
    });
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, receiving_dma< AXIStreamSwitch > >::push_command(), and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::read().
receive() [2/2]
template<typename AXIStreamSwitch > void trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::receive (std::span< axi_packet::value_type > sp) inline
Enqueue a DMA transfer to receive a span.
Use std::span for 1D contiguous transfers only for now
Definition at line 227 of file dma.hpp.
{
    this->push_command([=, this] {
      /* Write each element received from input router port into the
         memory described by DMA operation */
      for (auto& e : sp) {
        e = read();
      }
    });
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, receiving_dma< AXIStreamSwitch > >::push_command(), and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::read().
try_read() [1/2]
template<typename AXIStreamSwitch > bool trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::try_read (axi_packet::value_type & v) inline override virtual
Non-blocking read to a core input port.
Returns
true if the value was correctly read
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 259 of file dma.hpp.
{
    axi_packet p;
    if (fifo.try_pop(p) == boost::fibers::channel_op_status::success) {
      v = p.data;
      return true;
    }
    return false;
  }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo, and p.
try_read() [2/2]
template<typename AXIStreamSwitch > bool trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::try_read (axi_packet::value_type & v) inline override virtual
Non-blocking read to a core input port.
Returns
true if the value was correctly read
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 259 of file dma.hpp.
{
    axi_packet p;
    if (fifo.try_pop(p) == boost::fibers::channel_op_status::success) {
      v = p.data;
      return true;
    }
    return false;
  }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo, and p.
try_write() [1/2]
template<typename AXIStreamSwitch > bool trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::try_write (const axi_packet & v) inline override virtual
The network try to send some data to the DMA receiver input.
Returns
true if the packet is correctly enqueued or if the stream is closed, in order to to move on since we are in the tear-down phase of the infrastructure
Todo:
think about it again...
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 248 of file dma.hpp.
{
    return this->fifo.try_push(v) != boost::fibers::channel_op_status::full;
  }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo.
try_write() [2/2]
template<typename AXIStreamSwitch > bool trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::try_write (const axi_packet & v) inline override virtual
The network try to send some data to the DMA receiver input.
Returns
true if the packet is correctly enqueued or if the stream is closed, in order to to move on since we are in the tear-down phase of the infrastructure
Todo:
think about it again...
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 248 of file dma.hpp.
{
    return this->fifo.try_push(v) != boost::fibers::channel_op_status::full;
  }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo.
write() [1/2]
template<typename AXIStreamSwitch > void trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::write (const axi_packet & v) inline override virtual
The network sends some data to the DMA receiver input.
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 238 of file dma.hpp.
{ fifo.push(v); }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo.
write() [2/2]
template<typename AXIStreamSwitch > void trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::write (const axi_packet & v) inline override virtual
The network sends some data to the DMA receiver input.
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 238 of file dma.hpp.
{ fifo.push(v); }
References trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo.
Member Data Documentation
axi_ss
template<typename AXIStreamSwitch > AXIStreamSwitch & trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::axi_ss private
Keep track of the AXI stream switch owning this port for debugging.
Definition at line 215 of file dma.hpp.
fifo
template<typename AXIStreamSwitch > boost::fibers::buffered_channel< axi_packet > trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::fifo { 8 } private
Definition at line 212 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::read(), trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::try_read(), trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::try_write(), and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >::write().
The documentation for this class was generated from the following files:
include/sycl/vendor/Xilinx/acap/aie/dma.hpp
include/triSYCL/vendor/Xilinx/acap/aie/dma.hpp