triSYCL implementation of OpenCL SYCL: cl::sycl::detail::opencl_queue Class Reference
cl::sycl::detail::opencl_queue Class Reference
Some implementation details about the SYCL queue.
#include <opencl_queue.hpp>
Public Member Functions
~opencl_queue () override
Unregister from the cache on destruction.
Public Member Functions inherited from cl::sycl::detail::queue
queue ()
Initialize the queue with 0 running kernel.
void wait_for_kernel_execution ()
Wait for all kernel completion.
void kernel_start ()
Signal that a new kernel started on this queue.
void kernel_end ()
Signal that a new kernel finished on this queue.
virtual ~queue ()
Wait for all kernel completion before the queue destruction.
Static Public Member Functions
static std::shared_ptr< opencl_queue > instance (const boost::compute::command_queue &q)
Get a singleton instance of the opencl_queue.
static std::shared_ptr< detail::queue > instance (const cl::sycl::device &d)
Create a new queue associated to this device.
Private Member Functions
cl_command_queue get () const override
Return the cl_command_queue of the underlying OpenCL queue.
boost::compute::command_queue & get_boost_compute () override
Return the underlying Boost.Compute command queue.
cl::sycl::context get_context () const override
Return the SYCL context associated to the queue.
cl::sycl::device get_device () const override
Return the SYCL device associated to the queue.
bool is_host () const override
Claim proudly that an OpenCL queue cannot be the SYCL host queue.
opencl_queue (const boost::compute::command_queue &q)
Only the instance factory can built it.
Private Attributes
boost::compute::command_queue q
Use the Boost Compute abstraction of the OpenCL command queue.
Static Private Attributes
static detail::cache< cl_command_queue, detail::opencl_queue > cache
A cache to always return the same alive queue for a given OpenCL command queue.
Additional Inherited Members
Public Attributes inherited from cl::sycl::detail::queue
std::atomic< size_t > running_kernels
Track the number of kernels still running to wait for their completion.
std::condition_variable finished
To signal when all the kernels have completed.
std::mutex finished_mutex
To protect the access to the condition variable.
Detailed Description
Some implementation details about the SYCL queue.
Definition at line 23 of file opencl_queue.hpp.
Constructor & Destructor Documentation
opencl_queue()
cl::sycl::detail::opencl_queue::opencl_queue (const boost::compute::command_queue & q) inline private
Only the instance factory can built it.
Definition at line 67 of file opencl_queue.hpp.
 : q { q } {}
~opencl_queue()
cl::sycl::detail::opencl_queue::~opencl_queue () inline override
Unregister from the cache on destruction.
Definition at line 96 of file opencl_queue.hpp.
References cache, cl::sycl::detail::cache< Key, Value >::remove(), TRISYCL_WEAK_ATTRIB_PREFIX, and cl::sycl::detail::TRISYCL_WEAK_ATTRIB_SUFFIX.
{
     cache.remove(q.get());
   }
Member Function Documentation
get()
cl_command_queue cl::sycl::detail::opencl_queue::get () const inline override private virtual
Return the cl_command_queue of the underlying OpenCL queue.
Implements cl::sycl::detail::queue.
Definition at line 36 of file opencl_queue.hpp.
{
     return q.get();
   }
get_boost_compute()
boost::compute::command_queue& cl::sycl::detail::opencl_queue::get_boost_compute () inline override private virtual
Return the underlying Boost.Compute command queue.
Implements cl::sycl::detail::queue.
Definition at line 42 of file opencl_queue.hpp.
References q.
{
     return q;
   }
get_context()
cl::sycl::context cl::sycl::detail::opencl_queue::get_context () const inline override private virtual
Return the SYCL context associated to the queue.
Implements cl::sycl::detail::queue.
Definition at line 48 of file opencl_queue.hpp.
{
     return q.get_context();
   }
get_device()
cl::sycl::device cl::sycl::detail::opencl_queue::get_device () const inline override private virtual
Return the SYCL device associated to the queue.
Implements cl::sycl::detail::queue.
Definition at line 54 of file opencl_queue.hpp.
{
     return q.get_device();
   }
instance() [1/2]
static std::shared_ptr<opencl_queue> cl::sycl::detail::opencl_queue::instance (const boost::compute::command_queue & q) inline static
Get a singleton instance of the opencl_queue.
Definition at line 73 of file opencl_queue.hpp.
References cl::sycl::detail::cache< Key, Value >::get_or_register().
Referenced by instance(), and cl::sycl::queue::queue().
{
     return cache.get_or_register(q.get(),
                                  [&] { return new opencl_queue { q }; });
   }
instance() [2/2]
static std::shared_ptr<detail::queue> cl::sycl::detail::opencl_queue::instance (const cl::sycl::device & d) inline static
Create a new queue associated to this device.
Todo:
Check with SYCL committee what is the expected behaviour here about the context. Is this a new context everytime, or always the same for a given device?
Definition at line 86 of file opencl_queue.hpp.
References cl::sycl::device::get_boost_compute(), and instance().
{
     return instance (boost::compute::command_queue {
         // For now, create a new context every time
         boost::compute::context { d.get_boost_compute() },
         d.get_boost_compute()
           });
   }
is_host()
bool cl::sycl::detail::opencl_queue::is_host () const inline override private virtual
Claim proudly that an OpenCL queue cannot be the SYCL host queue.
Implements cl::sycl::detail::queue.
Definition at line 60 of file opencl_queue.hpp.
{
     return false;
   }
Member Data Documentation
cache
detail::cache<cl_command_queue, detail::opencl_queue> cl::sycl::detail::opencl_queue::cache static private
A cache to always return the same alive queue for a given OpenCL command queue.
C++11 guaranties the static construction is thread-safe
Definition at line 33 of file opencl_queue.hpp.
Referenced by ~opencl_queue().
q
boost::compute::command_queue cl::sycl::detail::opencl_queue::q private
Use the Boost Compute abstraction of the OpenCL command queue.
Definition at line 26 of file opencl_queue.hpp.
Referenced by get_boost_compute().
The documentation for this class was generated from the following file:
include/CL/sycl/queue/detail/opencl_queue.hpp