triSYCL implementation of SYCL: trisycl::detail::fiber_pool Class Reference
trisycl::detail::fiber_pool Class Reference
#include <fiber_pool.hpp>
Public Types
enum class sched { round_robin , shared_work , work_stealing }
To select some various Boost.Fibers schedulers.
template<typename T >
using future = boost::fibers::future< T >
The type of the future used by the implementation underneath.
Public Member Functions
fiber_pool (int thread_number, sched scheduler, bool suspend)
Create a fiber_pool.
template<typename Callable >
auto submit (Callable &&work)
Submit some work on a new fiber.
void close ()
Close the submission.
void join ()
Wait for all the threads are done.
~fiber_pool ()
Wait for some remaining work to be done.
Private Member Functions
void run (int i)
The thread worker job.
Private Attributes
std::vector< std::future< void > > working_threads
The thread running the Boost.Fiber schedulers to do the work.
boost::fibers::unbuffered_channel< std::function< void(void)> > submission
The queue to submit work.
boost::barrier starting_block
To synchronize all the threads before they can run some fibers.
boost::fibers::barrier finish_line
To synchronize all the threads after their last fiber.
bool joinable = true
To avoid joining several times.
sched s
The model of scheduler.
pooled_work_stealing::ctx pc_stealing
pooled_shared_work::ctx pc_shared
Static Private Attributes
static auto constexpr starting_mode = boost::fibers::launch::dispatch
Detailed Description
Definition at line 38 of file fiber_pool.hpp.
Member Typedef Documentation
future
template<typename T > using trisycl::detail::fiber_pool::future = boost::fibers::future<T>
The type of the future used by the implementation underneath.
Definition at line 83 of file fiber_pool.hpp.
Member Enumeration Documentation
sched
enum class trisycl::detail::fiber_pool::sched strong
To select some various Boost.Fibers schedulers.
Enumerator
round_robin
shared_work
work_stealing
Definition at line 43 of file fiber_pool.hpp.
                   {
    round_robin,
    shared_work,
    work_stealing
    // \todo Add numa
  };
Constructor & Destructor Documentation
fiber_pool()
trisycl::detail::fiber_pool::fiber_pool (int thread_number, sched scheduler, bool suspend) inline
Create a fiber_pool.
Definition at line 86 of file fiber_pool.hpp.
    : starting_block { static_cast<unsigned int>(thread_number) + 1 }
    , finish_line { static_cast<unsigned int>(thread_number) }
    , s { scheduler }
  {
    if (scheduler == sched::shared_work)
      // This scheduler needs a shared context
      pc_shared = pooled_shared_work::create_pool_ctx(suspend);
    else if (scheduler == sched::work_stealing)
      // This scheduler needs a shared context
      pc_stealing = pooled_work_stealing::create_pool_ctx
        (thread_number, suspend);
    // Start the working threads
    working_threads = ranges::iota_view { 0, thread_number }
                    | ranges::views::transform([&] (int i) {
                        return std::async(std::launch::async,
                                          [&, i] { run(i); }); })
                    | ranges::to<std::vector>;
    // Wait for all thread workers to be ready
    starting_block.count_down_and_wait();
  }
References trisycl::detail::pooled_shared_work::create_pool_ctx(), trisycl::detail::pooled_work_stealing::create_pool_ctx(), i, pc_shared, pc_stealing, run(), shared_work, starting_block, work_stealing, and working_threads.
~fiber_pool()
trisycl::detail::fiber_pool::~fiber_pool () inline
Wait for some remaining work to be done.
Definition at line 156 of file fiber_pool.hpp.
                {
    // Join first if not done already
    join();
    // There is a circular dependecy of shared_ptr/intrusive_ptr between
    // pc_stealing and its schedulers_. after we join we know none of the
    // schedulers_ are still running so we break the cycle and everything
    // cleansup itself.
    if (pc_stealing)
      pc_stealing->schedulers_.clear();
  }
References join(), and pc_stealing.
Member Function Documentation
close()
void trisycl::detail::fiber_pool::close () inline
Close the submission.
Definition at line 134 of file fiber_pool.hpp.
               {
    // Can be done many times, so no protection required here
    submission.close();
  }
References submission.
Referenced by join().
join()
void trisycl::detail::fiber_pool::join () inline
Wait for all the threads are done.
Definition at line 141 of file fiber_pool.hpp.
              {
    // Can be done only once
    if (joinable) {
      // Close the submission if not done already
      close();
      for (auto &t : working_threads)
        // A Boost.Fiber scheduler will block its thread if they still
        // have some work to do
        t.get();
      joinable = false;
    }
  }
References close(), joinable, and working_threads.
Referenced by ~fiber_pool().
run()
void trisycl::detail::fiber_pool::run (int i) inline private
The thread worker job.
Definition at line 170 of file fiber_pool.hpp.
                  {
    if (s == sched::shared_work)
      boost::fibers::use_scheduling_algorithm<pooled_shared_work>(pc_shared);
    else if (s == sched::work_stealing)
      boost::fibers::use_scheduling_algorithm
        <pooled_work_stealing>(pc_stealing);
    // Otherwise a round-robin scheduler is used and the fibers will
    // use only 1 thread since there is no thread migration in that
    // case
    // Wait for all thread workers to be ready
    starting_block.count_down_and_wait();
    // Only the first thread receives and starts the work
    if (i == 0) {
      // Keep track of each fiber execution to avoid quitting before completion
      std::vector<boost::fibers::fiber> fibers;
      for (;;) {
        decltype(submission)::value_type work;
        if (submission.pop(work)
            == boost::fibers::channel_op_status::closed)
          // Someone asked to stop accepting work
          break;
        // Launch the work on a new fiber
        fibers.emplace_back(starting_mode, std::move(work));
      }
      // Now wait for the completion of each fiber
      for (auto &f : fibers)
        f.join();
    }
    // Wait for all the threads to finish their fiber execution
    finish_line.wait();
  }
References finish_line, i, pc_shared, pc_stealing, s, shared_work, starting_block, starting_mode, submission, and work_stealing.
Referenced by fiber_pool().
submit()
template<typename Callable > auto trisycl::detail::fiber_pool::submit (Callable && work) inline
Submit some work on a new fiber.
Parameters
[in] work is the callable to execute, taking no arguments and returning a result of some type R
Returns
a future<R>
Definition at line 119 of file fiber_pool.hpp.
{
    // Put the packaged_task into a shared_ptr to fit it later in a
    // lambda in a std::function since the type is move-only
    auto pt = std::make_shared<boost::fibers::packaged_task<void(void)>>
      ([w = std::forward<Callable>(work)] () mutable { return w(); });
    auto f = pt->get_future();
    // Submit a lambda to do the type erasure so the submission queue
    // type is independent of the type of the packaged_task
    submission.push([p = std::move(pt)] () mutable { (*p)(); });
    // Return the future to the client to get the result or the exception
    return f;
  }
References p, and submission.
Referenced by trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::dma(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::router_minion(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::single_task().
Member Data Documentation
finish_line
boost::fibers::barrier trisycl::detail::fiber_pool::finish_line private
To synchronize all the threads after their last fiber.
Definition at line 65 of file fiber_pool.hpp.
Referenced by run().
joinable
bool trisycl::detail::fiber_pool::joinable = true private
To avoid joining several times.
Definition at line 68 of file fiber_pool.hpp.
Referenced by join().
pc_shared
pooled_shared_work::ctx trisycl::detail::fiber_pool::pc_shared private
Definition at line 77 of file fiber_pool.hpp.
Referenced by fiber_pool(), and run().
pc_stealing
pooled_work_stealing::ctx trisycl::detail::fiber_pool::pc_stealing private
Definition at line 74 of file fiber_pool.hpp.
Referenced by fiber_pool(), run(), and ~fiber_pool().
s
sched trisycl::detail::fiber_pool::s private
The model of scheduler.
Definition at line 71 of file fiber_pool.hpp.
Referenced by run().
starting_block
boost::barrier trisycl::detail::fiber_pool::starting_block private
To synchronize all the threads before they can run some fibers.
Definition at line 62 of file fiber_pool.hpp.
Referenced by fiber_pool(), and run().
starting_mode
auto constexpr trisycl::detail::fiber_pool::starting_mode = boost::fibers::launch::dispatch static constexpr private
Definition at line 59 of file fiber_pool.hpp.
Referenced by run().
submission
boost::fibers::unbuffered_channel<std::function<void(void)> > trisycl::detail::fiber_pool::submission private
The queue to submit work.
Definition at line 56 of file fiber_pool.hpp.
Referenced by close(), run(), and submit().
working_threads
std::vector<std::future<void> > trisycl::detail::fiber_pool::working_threads private
The thread running the Boost.Fiber schedulers to do the work.
Definition at line 53 of file fiber_pool.hpp.
Referenced by fiber_pool(), and join().
The documentation for this class was generated from the following file:
include/triSYCL/detail/fiber_pool.hpp