triSYCL implementation of SYCL: trisycl::property_list Class Reference
trisycl::property_list Class Reference
SYCL property list.
#include <property_list.hpp>
Public Member Functions
template<typename... propsT, typename = std::enable_if_t<detail::all_true<std::is_convertible<propsT, detail::property>::value ...>::value>>
property_list (propsT... props)
Construct a property list from a list of classes derived from the detail::property.
property_list ()
Protected Member Functions
template<typename propertyT >
bool has_property () const
template<typename propertyT >
propertyT get_property () const
Private Member Functions
TRISYCL_PROPERTY_CREATE (queue, enable_profiling)
template<typename T , typename... propsT, typename = std::enable_if_t<detail::all_true<std::is_convertible<propsT, detail::property>::value ...>::value>>
void addproperty (T first, propsT... next)
Detailed Description
SYCL property list.
Definition at line 16 of file property_list.hpp.
Constructor & Destructor Documentation
property_list() [1/2]
template<typename... propsT, typename = std::enable_if_t<detail::all_true<std::is_convertible<propsT, detail::property>::value ...>::value>> trisycl::property_list::property_list (propsT... props) inline
Construct a property list from a list of classes derived from the detail::property.
The detail::property and all_true are required to disambiguate queue/buffer constructors, so that property_lists are only created from property classes.
Definition at line 46 of file property_list.hpp.
{
    addproperty(props...);
  }
References addproperty().
property_list() [2/2]
trisycl::property_list::property_list () inline
Definition at line 50 of file property_list.hpp.
{}
Member Function Documentation
addproperty()
template<typename T , typename... propsT, typename = std::enable_if_t<detail::all_true<std::is_convertible<propsT, detail::property>::value ...>::value>> void trisycl::property_list::addproperty (T first, propsT... next) inline private
Definition at line 35 of file property_list.hpp.
{
    addproperty(next...);
  }
References addproperty().
Referenced by addproperty(), and property_list().
get_property()
template<typename propertyT > propertyT trisycl::property_list::get_property () const inline protected
has_property()
template<typename propertyT > bool trisycl::property_list::has_property () const inline protected
TRISYCL_PROPERTY_CREATE()
trisycl::property_list::TRISYCL_PROPERTY_CREATE (queue , enable_profiling) private
The documentation for this class was generated from the following file:
include/triSYCL/property_list.hpp