triSYCL implementation of OpenCL SYCL: cl::sycl::buffer< T, Dimensions, Allocator > Class Template Reference
cl::sycl::buffer< T, Dimensions, Allocator > Class Template Reference
<T, Dimensions, Mode, Target>up data Data access and storage in SYCL
#include <accessor.hpp>
Public Types
using value_type = T
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
using allocator_type = Allocator
Public Member Functions
buffer ()=default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or an r-value (for std::move() for example).
buffer (const range< Dimensions > &r, Allocator allocator={})
Create a new buffer of the given size with storage managed by the SYCL runtime.
template<typename Dependent = T, typename = std::enable_if_t<!std::is_const<Dependent>::value>>
buffer (const T *host_data, const range< Dimensions > &r, Allocator allocator={})
Create a new buffer with associated host memory.
buffer (T *host_data, const range< Dimensions > &r, Allocator allocator={})
Create a new buffer with associated host memory.
buffer (shared_ptr_class< T > &host_data, const range< Dimensions > &buffer_range, cl::sycl::mutex_class &m, Allocator allocator={})
Create a new buffer with associated memory, using the data in host_data.
buffer (shared_ptr_class< T > host_data, const range< Dimensions > &buffer_range, Allocator allocator={})
Create a new buffer with associated memory, using the data in host_data.
buffer (unique_ptr_class< T > &&host_data, const range< Dimensions > &r, Allocator allocator={})
Create a new buffer which is initialized by host_data.
template<typename InputIterator , typename ValueType = typename std::iterator_traits<InputIterator>::value_type>
buffer (InputIterator start_iterator, InputIterator end_iterator, Allocator allocator={})
Create a new allocated 1D buffer initialized from the given elements ranging from first up to one before last.
buffer (buffer< T, Dimensions, Allocator > &b, const id< Dimensions > &base_index, const range< Dimensions > &sub_range, Allocator allocator={})
Create a new sub-buffer without allocation to have separate accessors later.
buffer (cl_mem mem_object, queue from_queue, event available_event={}, Allocator allocator={})
Create a buffer from an existing OpenCL memory object associated with a context after waiting for an event signaling the availability of the OpenCL data.
template<access::mode Mode, access::target Target = access::target::global_buffer>
accessor< T, Dimensions, Mode, Target > get_access (handler &command_group_handler)
Get an accessor to the buffer with the required mode.
void mark_as_written ()
Force the buffer to behave like if we had created an accessor in write mode.
template<access::mode Mode, access::target Target = access::target::host_buffer>
accessor< T, Dimensions, Mode, Target > get_access ()
Get a host accessor to the buffer with the required mode.
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
auto get_count () const
Returns the total number of elements in the buffer.
size_t get_size () const
Returns the size of the buffer storage in bytes.
auto use_count () const
Returns the number of buffers that are shared/referenced.
bool constexpr is_read_only () const
Ask for read-only status of the buffer.
void set_final_data (shared_ptr_class< T > finalData)
Set destination of buffer data on destruction.
void set_final_data (weak_ptr_class< T > finalData)
Set destination of buffer data on destruction.
void set_final_data (std::nullptr_t)
Disable write-back on buffer destruction.
template<typename Iterator >
void set_final_data (Iterator &&finalData)
Set destination of buffer data on destruction.
Public Member Functions inherited from cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >
shared_ptr_implementation (std::shared_ptr< detail::buffer_waiter< T, Dimensions, Allocator > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::buffer_waiter< T, Dimensions, Allocator > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const buffer< T, Dimensions, Allocator > &other) const
Equality operator.
bool operator< (const buffer< T, Dimensions, Allocator > &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename buffer::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >
std::shared_ptr< detail::buffer_waiter< T, Dimensions, Allocator > > implementation
The implementation forward everything to this... implementation.
Detailed Description
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>>
class cl::sycl::buffer< T, Dimensions, Allocator >
<T, Dimensions, Mode, Target>up data Data access and storage in SYCL
A SYCL buffer is a multidimensional variable length array (à la C99 VLA or even Fortran before) that is used to store data to work on.
Todo:
There is a naming inconsistency in the specification between buffer and accessor on T versus datatype
Todo:
Finish allocator implementation
Todo:
Think about the need of an allocator when constructing a buffer from other buffers
Todo:
Update the specification to have a non-const allocator for const buffer? Or do we rely on rebind_alloc<T>. But does this work with astate-full allocator?
Todo:
Add constructors from arrays so that in C++17 the range and type can be infered from the constructor
Todo:
Add constructors from array_ref
Definition at line 29 of file accessor.hpp.
Member Typedef Documentation
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using cl::sycl::buffer< T, Dimensions, Allocator >::allocator_type = Allocator
Definition at line 75 of file buffer.hpp.
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using cl::sycl::buffer< T, Dimensions, Allocator >::const_reference = const value_type&
Definition at line 74 of file buffer.hpp.
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using cl::sycl::buffer< T, Dimensions, Allocator >::implementation_t = typename buffer::shared_ptr_implementation private
Definition at line 80 of file buffer.hpp.
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using cl::sycl::buffer< T, Dimensions, Allocator >::reference = value_type&
Definition at line 73 of file buffer.hpp.
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using cl::sycl::buffer< T, Dimensions, Allocator >::value_type = T
The STL-like types.
Definition at line 72 of file buffer.hpp.
Constructor & Destructor Documentation
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer () default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or an r-value (for std::move() for example).
Since we just copy the shared_ptr<> from the shared_ptr_implementation above, this is where/how the sharing magic is happening with reference counting in this case.
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (const range< Dimensions > & r, Allocator allocator = {}) inline
Create a new buffer of the given size with storage managed by the SYCL runtime.
The default behavior is to use the default host buffer allocator, in order to allow for host accesses. If the type of the buffer, has the const qualifier, then the default allocator will remove the qualifier to allow host access to the data.
Parameters
[in] r defines the size
[in] allocator is to be used by the SYCL runtime
Definition at line 113 of file buffer.hpp.
References cl::sycl::detail::waiter().
                                                            {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { r }) }
       {}
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<typename Dependent = T, typename = std::enable_if_t<!std::is_const<Dependent>::value>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (const T * host_data, const range< Dimensions > & r, Allocator allocator = {}) inline
Create a new buffer with associated host memory.
Parameters
[in] host_data points to the storage and values used by the buffer
[in] r defines the size
[in] allocator is to be used by the SYCL runtime, of type cl::sycl::buffer_allocator<T> by default
The host address is
const T*
, so the host memory is read-only.
However, the typename T is not const so the device accesses can be both read and write accesses. Since, the host_data is const, this buffer is only initialized with this memory and there is no write after its destruction, unless there is another final data address given after construction of the buffer.
Only enable this constructor if it is not the same as the one with
const T *host_data
, which is when T is already a constant type.
Todo:
Actually this is redundant.
Definition at line 146 of file buffer.hpp.
References cl::sycl::detail::waiter().
                                {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { host_data, r }) }
   {}
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (T * host_data, const range< Dimensions > & r, Allocator allocator = {}) inline
Create a new buffer with associated host memory.
Parameters
[in,out] host_data points to the storage and values used by the buffer
[in] r defines the size
[in] allocator is to be used by the SYCL runtime, of type cl::sycl::buffer_allocator<T> by default
The memory is owned by the runtime during the lifetime of the object. Data is copied back to the host unless the user overrides the behavior using the set_final_data method. host_data points to the storage and values used by the buffer and range<Dimensions> defines the size.
Definition at line 170 of file buffer.hpp.
References cl::sycl::detail::waiter().
                                {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { host_data, r }) }
   {}
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (shared_ptr_class< T > & host_data, const range< Dimensions > & buffer_range, cl::sycl::mutex_class & m, Allocator allocator = {}) inline
Create a new buffer with associated memory, using the data in host_data.
Parameters
[in,out] host_data points to the storage and values used by the buffer
[in] r defines the size
[in] allocator is to be used by the SYCL runtime, of type cl::sycl::buffer_allocator<T> by default
The ownership of the host_data is shared between the runtime and the user. In order to enable both the user application and the SYCL runtime to use the same pointer, a cl::sycl::mutex_class is used. The mutex m is locked by the runtime whenever the data is in use and unlocked otherwise. Data is synchronized with host_data, when the mutex is unlocked by the runtime.
Todo:
update the specification to replace the pointer by a reference and provide the constructor with and without a mutex
Definition at line 199 of file buffer.hpp.
References cl::sycl::detail::unimplemented().
                                {}) {
     detail::unimplemented();
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (shared_ptr_class< T > host_data, const range< Dimensions > & buffer_range, Allocator allocator = {}) inline
Create a new buffer with associated memory, using the data in host_data.
Parameters
[in,out] host_data points to the storage and values used by the buffer
[in] r defines the size
[in,out] m is the mutex used to protect the data access
[in] allocator is to be used by the SYCL runtime, of type cl::sycl::buffer_allocator<T> by default
The ownership of the host_data is shared between the runtime and the user. In order to enable both the user application and the SYCL runtime to use the same pointer, a cl::sycl::mutex_class is used.
Todo:
add this mutex-less constructor to the specification
Definition at line 227 of file buffer.hpp.
References cl::sycl::detail::waiter().
                                {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { host_data, buffer_range }) }
   {}
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (unique_ptr_class< T > && host_data, const range< Dimensions > & r, Allocator allocator = {}) inline
Create a new buffer which is initialized by host_data.
Parameters
[in] host_data points to the storage and values used to initialize the buffer
[in] r defines the size
[in] allocator is to be used by the SYCL runtime, of type cl::sycl::buffer_allocator<T> by default
The SYCL runtime receives full ownership of the host_data unique_ptr and there in effect there is no synchronization with the application code using host_data.
Todo:
Update the API to add template <typename D = std::default_delete<T>> because the unique_ptr_class/std::unique_ptr have the destructor type as dependent
Definition at line 254 of file buffer.hpp.
References cl::sycl::detail::waiter().
                                {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { std::move(host_data), r }) }
   {}
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<typename InputIterator , typename ValueType = typename std::iterator_traits<InputIterator>::value_type> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (InputIterator start_iterator, InputIterator end_iterator, Allocator allocator = {}) inline
Create a new allocated 1D buffer initialized from the given elements ranging from first up to one before last.
The data is copied to an intermediate memory position by the runtime. Data is written back to the same iterator set if the iterator is not a const iterator.
Parameters
[in,out] start_iterator points to the first element to copy
[in] end_iterator points to just after the last element to copy
[in] allocator is to be used by the SYCL runtime, of type cl::sycl::buffer_allocator<T> by default
Todo:
Implement the copy back at buffer destruction
Todo:
Generalize this for n-D and provide column-major and row-major initialization
Todo:
a reason to have this nD is that set_final_data(weak_ptr_class<T> & finalData) is actually doing this linearization anyway
Todo:
Allow read-only buffer construction too
Todo:
update the specification to deal with forward iterators instead and rewrite back only when it is non const and output iterator at least
Todo:
Allow initialization from ranges and collections à la STL
Definition at line 299 of file buffer.hpp.
References cl::sycl::detail::waiter().
                                {}) :
     implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                        { start_iterator, end_iterator }) }
   {}
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (buffer< T, Dimensions, Allocator > & b, const id< Dimensions > & base_index, const range< Dimensions > & sub_range, Allocator allocator = {}) inline
Create a new sub-buffer without allocation to have separate accessors later.
Parameters
[in,out] b is the buffer with the real data
[in] base_index specifies the origin of the sub-buffer inside the buffer b
[in] sub_range specifies the size of the sub-buffer
Todo:
To be implemented
Todo:
Update the specification to replace index by id
Definition at line 321 of file buffer.hpp.
References cl::sycl::detail::unimplemented().
                                {}) { detail::unimplemented(); }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> cl::sycl::buffer< T, Dimensions, Allocator >::buffer (cl_mem mem_object, queue from_queue, event available_event = {}, Allocator allocator = {}) inline
Create a buffer from an existing OpenCL memory object associated with a context after waiting for an event signaling the availability of the OpenCL data.
Parameters
[in,out] mem_object is the OpenCL memory object to use
[in,out] from_queue is the queue associated to the memory object
[in] available_event specifies the event to wait for if non null
Note that a buffer created from a cl_mem object will only have one underlying cl_mem for the lifetime of the buffer and use on an incompatible queue constitues an error.
Todo:
To be implemented
Todo:
Improve the specification to allow CLHPP objects too
Definition at line 348 of file buffer.hpp.
References cl::sycl::access::global_buffer, and cl::sycl::detail::unimplemented().
                                  {},
          Allocator allocator = {}) { detail::unimplemented();  }
Member Function Documentation
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<access::mode Mode, access::target Target = access::target::global_buffer> accessor<T, Dimensions, Mode, Target> cl::sycl::buffer< T, Dimensions, Allocator >::get_access (handler & command_group_handler) inline
Get an accessor to the buffer with the required mode.
Parameters
Mode is the requested access mode
Target is the type of object to be accessed
[in] command_group_handler is the command group handler in which the kernel is to be executed
Todo:
Do we need for an accessor to increase the reference count of a buffer object? It does make more sense for a host-side accessor.
Todo:
Implement the modes and targets
Definition at line 374 of file buffer.hpp.
References cl::sycl::access::constant_buffer, cl::sycl::access::global_buffer, and cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     static_assert(Target == access::target::global_buffer
                   || Target == access::target::constant_buffer,
                   "get_access(handler) can only deal with access::global_buffer"
                   " or access::constant_buffer (for host_buffer accessor"
                   " do not use a command group handler");
     implementation->implementation->template track_access_mode<Mode, Target>();
     return { *this, command_group_handler };
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<access::mode Mode, access::target Target = access::target::host_buffer> accessor<T, Dimensions, Mode, Target> cl::sycl::buffer< T, Dimensions, Allocator >::get_access () inline
Get a host accessor to the buffer with the required mode.
Parameters
Mode is the requested access mode
Todo:
Implement the modes
Todo:
More elegant solution
Definition at line 404 of file buffer.hpp.
References cl::sycl::access::host_buffer, and cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
                {
     static_assert(Target == access::target::host_buffer,
                   "get_access() without a command group handler is only"
                   " for host_buffer accessor");
     implementation->implementation->template track_access_mode<Mode, Target>();
     return { *this };
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> auto cl::sycl::buffer< T, Dimensions, Allocator >::get_count () const inline
Returns the total number of elements in the buffer.
Equal to get_range()[0] * ... * get_range()[Dimensions-1].
Definition at line 434 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->get_count();
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> auto cl::sycl::buffer< T, Dimensions, Allocator >::get_range () const inline
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
Todo:
rename to the equivalent from array_ref proposals? Such as size() in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0009r2.html
Definition at line 421 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     /* Interpret the shape which is a pointer to the first element as an
        array of Dimensions elements so that the range<Dimensions>
        constructor is happy with this collection
     */
     return implementation->implementation->get_range();
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> size_t cl::sycl::buffer< T, Dimensions, Allocator >::get_size () const inline
Returns the size of the buffer storage in bytes.
Equal to get_count()*sizeof(T).
Todo:
rename to something else. In http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0122r0.pdf it is named bytes() for example
Definition at line 447 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->get_size();
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> bool constexpr cl::sycl::buffer< T, Dimensions, Allocator >::is_read_only () const inline
Ask for read-only status of the buffer.
Todo:
Add to specification
Definition at line 474 of file buffer.hpp.
{
     return std::is_const<T>::value;
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> void cl::sycl::buffer< T, Dimensions, Allocator >::mark_as_written () inline
Force the buffer to behave like if we had created an accessor in write mode.
Definition at line 388 of file buffer.hpp.
References cl::sycl::access::host_buffer, and cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->mark_as_written();
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> void cl::sycl::buffer< T, Dimensions, Allocator >::set_final_data (shared_ptr_class< T > finalData) inline
Set destination of buffer data on destruction.
The finalData points to the host memory to which, the outcome of all the buffer processing is going to be copied to.
This is the final pointer, which is going to be accessible after the destruction of the buffer and in the case where this is a valid pointer, the data are going to be copied to this host address.
finalData is different from the original host address, if the buffer was created associated with one. This is mainly to be used when a shared_ptr is given in the constructor and the output data will reside in a different location from the initialization data.
It is defined as a weak_ptr referring to a shared_ptr that is not associated with the cl::sycl::buffer, and so the cl::sycl::buffer will have no ownership of finalData.
Todo:
Update the API to take finalData by value instead of by reference. This way we can have an implicit conversion possible at the API call from a shared_ptr<>, avoiding an explicit weak_ptr<> creation
Todo:
figure out how set_final_data() interact with the other way to write back some data or with some data sharing with the host that can not be undone
Definition at line 506 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
Referenced by cl::sycl::buffer< T, Dimensions, Allocator >::set_final_data().
{
     implementation->implementation->set_final_data(std::move(finalData));
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> void cl::sycl::buffer< T, Dimensions, Allocator >::set_final_data (weak_ptr_class< T > finalData) inline
Set destination of buffer data on destruction.
Definition at line 513 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     implementation->implementation->set_final_data(std::move(finalData));
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> void cl::sycl::buffer< T, Dimensions, Allocator >::set_final_data (std::nullptr_t) inline
Disable write-back on buffer destruction.
Definition at line 520 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     implementation->implementation->set_final_data(nullptr);
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<typename Iterator > void cl::sycl::buffer< T, Dimensions, Allocator >::set_final_data (Iterator && finalData) inline
Set destination of buffer data on destruction.
WARNING: the user has to ensure that the object refered to by the iterator will be alive after buffer destruction, otherwise the behaviour is undefined.
Definition at line 532 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation, and cl::sycl::buffer< T, Dimensions, Allocator >::set_final_data().
{
     implementation->implementation->
       set_final_data(std::forward<Iterator>(finalData));
   }
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> auto cl::sycl::buffer< T, Dimensions, Allocator >::use_count () const inline
Returns the number of buffers that are shared/referenced.
For example
cl::sycl::buffer<int> b { 1000 };
// Here b.use_count() should return 1
cl::sycl::buffer<int> c { b };
// Here b.use_count() and b.use_count() should return 2
Todo:
Add to the specification, useful for validation
Definition at line 464 of file buffer.hpp.
References cl::sycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     // Rely on the shared_ptr<> use_count()
     return implementation.use_count();
   }
Member Data Documentation
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> friend cl::sycl::buffer< T, Dimensions, Allocator >::implementation_t private
Definition at line 83 of file buffer.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/accessor.hpp
include/CL/sycl/buffer.hpp