triSYCL implementation of SYCL: trisycl::detail::vec< DataType, NumElements > Class Template Reference
trisycl::detail::vec< DataType, NumElements > Class Template Reference
forward declaration to use in the detail class
#include <vec.hpp>
Public Member Functions
template<typename... Types>
requires (sizeof...(Types) != NumElements)
vec (const Types... args)
Construct a vec from anything from a scalar (to initialize all the elements with this value) up to an aggregate of scalar and vector types (in this case the total number of elements must match the size of the vector).
vec ()=default
Use classical constructors too.
auto get_count () const
Return the number of elements in the vector.
auto get_size () const
Return the number of bytes.
template<typename convertT , rounding_mode roundingMode>
vec< convertT, NumElements > convert () const
template<typename asT >
asT as () const
template<int... swizzleIndexs>
__swizzled_vec__< DataType, sizeof...(swizzleIndexs)> swizzle () const
template<typename F >
auto map (F f) const
template<typename T , int size, typename F >
auto zip (::trisycl::vec< T, size > x, F f) const
template<typename T , int size, typename F >
auto zip (::trisycl::vec< T, size > y, ::trisycl::vec< T, size > z, F f) const
Public Member Functions inherited from trisycl::detail::small_array< DataType, ::trisycl::vec< DataType, NumElements >, NumElements >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of exactly Dims elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
auto get (std::size_t index) const
Return the element of the array.
operator::trisycl::vec< DataType, NumElements > ()
Add + like operations on the id<> and others.
Public Member Functions inherited from trisycl::detail::display_vector< ::trisycl::vec< DataType, NumElements > >
void display () const
To debug and test.
Protected Member Functions
template<typename... Ts>
__swizzled_base_vec__< DataType, sizeof...(Ts)> swizzle (Ts... swizzleIndexes) const
Apply a swizzle operation from swizzleIndexes parameters.
Private Types
using basic_type = typename detail::small_array< DataType, ::trisycl::vec< DataType, NumElements >, NumElements >
Static Private Member Functions
template<typename V , typename Element , int s>
static auto flatten (const vec< Element, s > i)
Flattening helper that does not change scalar values but flatten a vec<T, n> v into a tuple<T, T,..., T>{ v[0], v[1],..., v[n-1] }.
template<typename V , typename Element , int s>
static auto flatten (const ::trisycl::vec< Element, s > i)
template<typename V , typename Type >
static auto flatten (const Type i)
If we do not have a vector, just forward it as a tuple up to the final initialization.
template<typename V , typename... Types>
static auto flatten_to_tuple (const Types... i)
Take some initializer values and apply flattening on each value.
template<typename T , typename F , std::size_t... Is>
static auto apply_unary_functor_impl (T tuple, F f, std::index_sequence< Is... >)
template<typename T , typename F >
static auto apply_unary_functor (const T x, F f)
template<typename T , typename T2 , typename F , std::size_t... Is>
static auto apply_binary_functor_impl (T xTuple, T2 yTuple, F f, std::index_sequence< Is... >)
template<typename T , typename T2 , typename T3 , typename F , std::size_t... Is>
static auto apply_ternary_functor_impl (T xTuple, T2 yTuple, T3 zTuple, F f, std::index_sequence< Is... >)
template<typename T , typename T2 , typename F >
static auto apply_binary_functor (const T x, const T2 y, F f)
Additional Inherited Members
Public Types inherited from trisycl::detail::small_array< DataType, ::trisycl::vec< DataType, NumElements >, NumElements >
using element_type = DataType
Static Public Attributes inherited from trisycl::detail::small_array< DataType, ::trisycl::vec< DataType, NumElements >, NumElements >
static constexpr size_t dimension
Detailed Description
template<typename DataType, int NumElements>
class trisycl::detail::vec< DataType, NumElements >
forward declaration to use in the detail class
Small SYCL vector class.
Definition at line 41 of file vec.hpp.
Member Typedef Documentation
basic_type
template<typename DataType , int NumElements> using trisycl::detail::vec< DataType, NumElements >::basic_type = typename detail::small_array<DataType, ::trisycl::vec<DataType, NumElements>, NumElements> private
Definition at line 45 of file vec.hpp.
Constructor & Destructor Documentation
vec() [1/2]
template<typename DataType , int NumElements> template<typename... Types> requires (sizeof...(Types) != NumElements) trisycl::detail::vec< DataType, NumElements >::vec (const Types... args) inline
Construct a vec from anything from a scalar (to initialize all the elements with this value) up to an aggregate of scalar and vector types (in this case the total number of elements must match the size of the vector).
Do not use this constructor with NumElements to avoid ambiguity with the inherited small_array constructor.
Definition at line 61 of file vec.hpp.
      : basic_type { detail::expand<vec>(flatten_to_tuple<vec>(args...)) } {}
vec() [2/2]
template<typename DataType , int NumElements> trisycl::detail::vec< DataType, NumElements >::vec () default
Use classical constructors too.
Member Function Documentation
apply_binary_functor()
template<typename DataType , int NumElements> template<typename T , typename T2 , typename F > static auto trisycl::detail::vec< DataType, NumElements >::apply_binary_functor (const T x, const T2 y, F f) inline static private
Definition at line 156 of file vec.hpp.
{
    auto xTuple = flatten_to_tuple<T>(x);
    auto yTuple = flatten_to_tuple<T>(y);
    return apply_binary_functor_impl(xTuple, yTuple, f,
        std::make_index_sequence<std::tuple_size<decltype(xTuple)>::value>());
  }
References trisycl::detail::vec< DataType, NumElements >::apply_binary_functor_impl(), x, and trisycl::y.
Referenced by trisycl::detail::vec< DataType, NumElements >::zip().
apply_binary_functor_impl()
template<typename DataType , int NumElements> template<typename T , typename T2 , typename F , std::size_t... Is> static auto trisycl::detail::vec< DataType, NumElements >::apply_binary_functor_impl (T xTuple, T2 yTuple, F f, std::index_sequence< Is... >) inline static private
Definition at line 140 of file vec.hpp.
{
    return ::trisycl::vec<DataType, NumElements>{f(std::get<Is>(xTuple),
       std::get<Is>(yTuple))...};
  }
Referenced by trisycl::detail::vec< DataType, NumElements >::apply_binary_functor().
apply_ternary_functor_impl()
template<typename DataType , int NumElements> template<typename T , typename T2 , typename T3 , typename F , std::size_t... Is> static auto trisycl::detail::vec< DataType, NumElements >::apply_ternary_functor_impl (T xTuple, T2 yTuple, T3 zTuple, F f, std::index_sequence< Is... >) inline static private
Definition at line 148 of file vec.hpp.
{
    return ::trisycl::vec<DataType, NumElements>{f(std::get<Is>(xTuple),
       std::get<Is>(yTuple),  std::get<Is>(zTuple))...};
  }
apply_unary_functor()
template<typename DataType , int NumElements> template<typename T , typename F > static auto trisycl::detail::vec< DataType, NumElements >::apply_unary_functor (const T x, F f) inline static private
Definition at line 128 of file vec.hpp.
{
    auto tuple = flatten_to_tuple<T>(x);
    return apply_unary_functor_impl(tuple, f,
        std::make_index_sequence<std::tuple_size<decltype(tuple)>::value>());
  }
References trisycl::detail::vec< DataType, NumElements >::apply_unary_functor_impl(), and x.
Referenced by trisycl::detail::vec< DataType, NumElements >::map().
apply_unary_functor_impl()
template<typename DataType , int NumElements> template<typename T , typename F , std::size_t... Is> static auto trisycl::detail::vec< DataType, NumElements >::apply_unary_functor_impl (T tuple, F f, std::index_sequence< Is... >) inline static private
Definition at line 122 of file vec.hpp.
{
    return ::trisycl::vec<DataType, NumElements>{f(std::get<Is>(tuple))...};
  }
Referenced by trisycl::detail::vec< DataType, NumElements >::apply_unary_functor().
as()
template<typename DataType , int NumElements> template<typename asT > asT trisycl::detail::vec< DataType, NumElements >::as () const inline
Definition at line 202 of file vec.hpp.
{
    asT result;
    assert(result.get_size() == this->get_size());
    std::memcpy(result.data(), this->data(), this->get_size());
    return result;
  };
convert()
template<typename DataType , int NumElements> template<typename convertT , rounding_mode roundingMode> vec< convertT, NumElements > trisycl::detail::vec< DataType, NumElements >::convert () const inline
Definition at line 191 of file vec.hpp.
{
    vec<convertT, NumElements> result;
    assert(result.get_count() == this->get_count());
    for (int n = 0; n < NumElements; n++) {
      result[n] = (*this)[n];
    }
    return result;
  };
References trisycl::detail::vec< DataType, NumElements >::get_count(), and n.
flatten() [1/3]
template<typename DataType , int NumElements> template<typename V , typename Element , int s> static auto trisycl::detail::vec< DataType, NumElements >::flatten (const ::trisycl::vec< Element, s > i) inline static private
Definition at line 88 of file vec.hpp.
{
    static_assert(s <= V::dimension,
                  "The element i will not fit in the vector");
    return static_cast<std::array<Element, s>>(i);
  }
References i.
flatten() [2/3]
template<typename DataType , int NumElements> template<typename V , typename Type > static auto trisycl::detail::vec< DataType, NumElements >::flatten (const Type i) inline static private
If we do not have a vector, just forward it as a tuple up to the final initialization.
Returns
typically tuple<double>{ 2.4 } from 2.4 input for example
Definition at line 101 of file vec.hpp.
{
    return std::make_tuple(i);
  }
References i.
flatten() [3/3]
template<typename DataType , int NumElements> template<typename V , typename Element , int s> static auto trisycl::detail::vec< DataType, NumElements >::flatten (const vec< Element, s > i) inline static private
Flattening helper that does not change scalar values but flatten a vec<T, n> v into a tuple<T, T,..., T>{ v[0], v[1],..., v[n-1] }.
If we have a vector, just forward its array content since an array has also a tuple interface :-) (23.3.2.9 Tuple interface to class template array [array.tuple])
Definition at line 81 of file vec.hpp.
{
    static_assert(s <= V::dimension,
                  "The element i will not fit in the vector");
    return static_cast<std::array<Element, s>>(i);
  }
References i.
flatten_to_tuple()
template<typename DataType , int NumElements> template<typename V , typename... Types> static auto trisycl::detail::vec< DataType, NumElements >::flatten_to_tuple (const Types... i) inline static private
Take some initializer values and apply flattening on each value.
Returns
a tuple of scalar initializer values
Definition at line 111 of file vec.hpp.
{
    // Concatenate the tuples returned by each flattening
    return std::tuple_cat(flatten<V>(i)...);
  }
References i.
get_count()
template<typename DataType , int NumElements> auto trisycl::detail::vec< DataType, NumElements >::get_count () const inline
Return the number of elements in the vector.
Definition at line 177 of file vec.hpp.
{
    return NumElements;
  }
Referenced by trisycl::detail::vec< DataType, NumElements >::convert().
get_size()
template<typename DataType , int NumElements> auto trisycl::detail::vec< DataType, NumElements >::get_size () const inline
Return the number of bytes.
Definition at line 182 of file vec.hpp.
{
    // The alignment for the vec classes are equivalent to the vec's size e.g.
    // a vec of 4 floats would be aligned to 16 bytes which is also the vec's
    // size.
    return alignment_v<::trisycl::vec<DataType, NumElements>>;
  }
map()
template<typename DataType , int NumElements> template<typename F > auto trisycl::detail::vec< DataType, NumElements >::map (F f) const inline
Definition at line 221 of file vec.hpp.
                      {
    return apply_unary_functor(*this, f);
  }
References trisycl::detail::vec< DataType, NumElements >::apply_unary_functor().
swizzle() [1/2]
template<typename DataType , int NumElements> template<int... swizzleIndexs> __swizzled_vec__< DataType, sizeof...(swizzleIndexs)> trisycl::detail::vec< DataType, NumElements >::swizzle () const inline
Definition at line 212 of file vec.hpp.
{
    return static_cast<__swizzled_vec__<DataType, sizeof...(swizzleIndexs)>>(
        swizzle(swizzleIndexs...));
  }
References trisycl::detail::vec< DataType, NumElements >::swizzle().
Referenced by trisycl::detail::vec< DataType, NumElements >::swizzle().
swizzle() [2/2]
template<typename DataType , int NumElements> template<typename... Ts> __swizzled_base_vec__< DataType, sizeof...(Ts)> trisycl::detail::vec< DataType, NumElements >::swizzle (Ts... swizzleIndexes) const inline protected
Apply a swizzle operation from swizzleIndexes parameters.
Definition at line 168 of file vec.hpp.
{
    // Construct a new vector from an elemental swizzle of each element
    return __swizzled_base_vec__<DataType, sizeof...(Ts)> {
      (*this)[swizzleIndexes]... };
  }
zip() [1/2]
template<typename DataType , int NumElements> template<typename T , int size, typename F > auto trisycl::detail::vec< DataType, NumElements >::zip (::trisycl::vec< T, size > x, F f) const inline
Definition at line 235 of file vec.hpp.
{
     static_assert(size == NumElements,
       "zip currently does not support vec's of differing element size");
     return apply_binary_functor(*this, x, f);
  }
References trisycl::detail::vec< DataType, NumElements >::apply_binary_functor(), and x.
zip() [2/2]
template<typename DataType , int NumElements> template<typename T , int size, typename F > auto trisycl::detail::vec< DataType, NumElements >::zip (::trisycl::vec< T, size > y, ::trisycl::vec< T, size > z, F f) const inline
Todo:
this should be generalized to any arity
Definition at line 244 of file vec.hpp.
{
     static_assert(size == NumElements,
       "zip currently does not support vec's of differing element size");
     return apply_ternary_functor(*this, y, z, f);
  }
References trisycl::y, and trisycl::z.
The documentation for this class was generated from the following file:
include/triSYCL/vec/detail/vec.hpp