triSYCL implementation of SYCL: trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion Class Reference
trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion Class Reference
A router input port with routing skills.
#include <axi_stream_switch.hpp>
Public Types
using value_type = axi_packet::value_type
using value_type = axi_packet::value_type
Public Member Functions
void join ()
Wait for the fibers to complete.
void write (const axi_packet &v) override
Enqueue a packet on the router input.
bool try_write (const axi_packet &v) override
Try to enqueue a packet on the router input.
value_type read () override
Waiting read to a core input port.
bool try_read (value_type &v) override
Non-blocking read to a core input port.
void connect_to (axi_stream_switch::mpl port_dest, std::shared_ptr< communicator_port > dest)
Connect this routing input to a switch output.
const auto & get_master_port_dests ()
Return a vector of the master ports this router is forwarding.
router_minion (axi_stream_switch &axi_ss, ::trisycl::detail::fiber_pool &fiber_executor, int capacity=axi_ss_geo::latency)
Create a router minion on this switch using a fiber executor.
~router_minion () override
Destructor handling the correct infrastructure shutdown.
void join ()
Wait for the fibers to complete.
void write (const axi_packet &v) override
Enqueue a packet on the router input.
bool try_write (const axi_packet &v) override
Try to enqueue a packet on the router input.
value_type read () override
Waiting read to a core input port.
bool try_read (value_type &v) override
Non-blocking read to a core input port.
void connect_to (axi_stream_switch::mpl port_dest, std::shared_ptr< communicator_port > dest)
Connect this routing input to a switch output.
const auto & get_master_port_dests ()
Return a vector of the master ports this router is forwarding.
router_minion (axi_stream_switch &axi_ss, ::trisycl::detail::fiber_pool &fiber_executor, int capacity=axi_ss_geo::latency)
Create a router minion on this switch using a fiber executor.
~router_minion () override
Destructor handling the correct infrastructure shutdown.
Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::communicator_port
virtual void write (const axi_packet &)=0
Enqueue a packet on the communicator input.
auto & operator<< (const axi_packet::value_type &v)
Alias to enqueue a packet on the communicator input.
virtual bool try_write (const axi_packet &)=0
Try to enqueue a packet to input.
virtual axi_packet::value_type read ()=0
Waiting read to a core input port.
virtual bool try_read (axi_packet::value_type &)=0
Non-blocking read from a communicator output port.
template<typename T >
auto & operator>> (T &v)
Alias to the waiting read to a communicator output port.
virtual ~communicator_port ()=default
Nothing specific to do but need a virtual destructor to avoid slicing.
virtual void write (const axi_packet &)=0
Enqueue a packet on the communicator input.
auto & operator<< (const axi_packet::value_type &v)
Alias to enqueue a packet on the communicator input.
virtual bool try_write (const axi_packet &)=0
Try to enqueue a packet to input.
virtual axi_packet::value_type read ()=0
Waiting read to a core input port.
virtual bool try_read (axi_packet::value_type &)=0
Non-blocking read from a communicator output port.
template<typename T >
auto & operator>> (T &v)
Alias to the waiting read to a communicator output port.
virtual ~communicator_port ()=default
Nothing specific to do but need a virtual destructor to avoid slicing.
Public Attributes
const int capacity
Router ingress capacity queue.
boost::fibers::buffered_channel< axi_packet > c { static_cast<std::size_t>(capacity) }
Ingress packet queue.
std::vector< axi_stream_switch::mpl > mpl_outputs
The ids of the outputs port the router minion has to forward to. Used by introspection to track current routing configuration.
std::vector< std::shared_ptr< communicator_port > > outputs
The outputs the router minion has to forward to.
std::vector<::trisycl::detail::fiber_pool::future< void > > futures
To shepherd the routing fibers.
axi_stream_switch & axi_ss
Keep track of the AXI stream switch owning this port for debugging.
Detailed Description
template<typename AXIStreamGeography>
class trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion
A router input port with routing skills.
Definition at line 61 of file axi_stream_switch.hpp.
Member Typedef Documentation
value_type [1/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::value_type = axi_packet::value_type
Definition at line 95 of file axi_stream_switch.hpp.
value_type [2/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::value_type = axi_packet::value_type
Definition at line 95 of file axi_stream_switch.hpp.
Constructor & Destructor Documentation
router_minion() [1/2]
template<typename AXIStreamGeography > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::router_minion (axi_stream_switch & axi_ss, ::trisycl::detail::fiber_pool & fiber_executor, int capacity = axi_ss_geo::latency) inline
Create a router minion on this switch using a fiber executor.
Use a fiber as a data mover from the input queue
Definition at line 166 of file axi_stream_switch.hpp.
      : capacity { capacity }
      , axi_ss { axi_ss }
    {
      /// Use a fiber as a data mover from the input queue
      futures.push_back(fiber_executor.submit([&] {
         TRISYCL_DUMP_T("router_minion " << this << " on tile("
                        << router_minion::axi_ss.x_coordinate
                        << ',' << router_minion::axi_ss.y_coordinate
                        << ") on fiber " << boost::this_fiber::get_id()
                        << " starting with buffered_channel " << &c);
          for (;;) {
            TRISYCL_DUMP_T("router_minion " << this << " on tile("
                           << router_minion::axi_ss.x_coordinate
                           << ',' << router_minion::axi_ss.y_coordinate
                           << ") on fiber " << boost::this_fiber::get_id()
                           << " reading from buffered_channel "
                           << &c << " ...");
            auto v = c.value_pop();
            if (v.shutdown_request)
              // End the execution on shutdown packet reception
              break;
            TRISYCL_DUMP_T("router_minion " << this << " on tile("
                           << router_minion::axi_ss.x_coordinate
                           << ',' << router_minion::axi_ss.y_coordinate
                           << ") on fiber " << boost::this_fiber::get_id()
                           << " routing data value " << v.data
                           << " received from buffered_channel " << &c);
            // The routing itself is a blocking write on each output
            for (auto &o : outputs) {
              TRISYCL_DUMP_T("router_minion " << this << " on tile("
                             << router_minion::axi_ss.x_coordinate
                             << ',' << router_minion::axi_ss.y_coordinate
                             << ") on fiber " << boost::this_fiber::get_id()
                             << " forwarding to router_minion " << o.get());
               o->write(v);
            }
          }
          TRISYCL_DUMP_T("router_minion " << this << " on tile("
                         << router_minion::axi_ss.x_coordinate
                         << ',' << router_minion::axi_ss.y_coordinate
                         << ") on fiber " << boost::this_fiber::get_id()
                         << " shutting down");
      }));
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::futures, trisycl::detail::fiber_pool::submit(), TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
~router_minion() [1/2]
template<typename AXIStreamGeography > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::~router_minion () inline override
Destructor handling the correct infrastructure shutdown.
Definition at line 216 of file axi_stream_switch.hpp.
{
      // Send a special packet to shutdown the routing process
      write(axi_packet::shutdown);
      // Wait for shutdown to avoid calling std::terminate on destruction...
      join();
    }
References trisycl::vendor::xilinx::acap::aie::axi_packet::shutdown.
router_minion() [2/2]
template<typename AXIStreamGeography > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::router_minion (axi_stream_switch & axi_ss, ::trisycl::detail::fiber_pool & fiber_executor, int capacity = axi_ss_geo::latency) inline
Create a router minion on this switch using a fiber executor.
Use a fiber as a data mover from the input queue
Definition at line 166 of file axi_stream_switch.hpp.
      : capacity { capacity }
      , axi_ss { axi_ss }
    {
      /// Use a fiber as a data mover from the input queue
      futures.push_back(fiber_executor.submit([&] {
         TRISYCL_DUMP_T("router_minion " << this << " on tile("
                        << router_minion::axi_ss.x_coordinate
                        << ',' << router_minion::axi_ss.y_coordinate
                        << ") on fiber " << boost::this_fiber::get_id()
                        << " starting with buffered_channel " << &c);
          for (;;) {
            TRISYCL_DUMP_T("router_minion " << this << " on tile("
                           << router_minion::axi_ss.x_coordinate
                           << ',' << router_minion::axi_ss.y_coordinate
                           << ") on fiber " << boost::this_fiber::get_id()
                           << " reading from buffered_channel "
                           << &c << " ...");
            auto v = c.value_pop();
            if (v.shutdown_request)
              // End the execution on shutdown packet reception
              break;
            TRISYCL_DUMP_T("router_minion " << this << " on tile("
                           << router_minion::axi_ss.x_coordinate
                           << ',' << router_minion::axi_ss.y_coordinate
                           << ") on fiber " << boost::this_fiber::get_id()
                           << " routing data value " << v.data
                           << " received from buffered_channel " << &c);
            // The routing itself is a blocking write on each output
            for (auto &o : outputs) {
              TRISYCL_DUMP_T("router_minion " << this << " on tile("
                             << router_minion::axi_ss.x_coordinate
                             << ',' << router_minion::axi_ss.y_coordinate
                             << ") on fiber " << boost::this_fiber::get_id()
                             << " forwarding to router_minion " << o.get());
               o->write(v);
            }
          }
          TRISYCL_DUMP_T("router_minion " << this << " on tile("
                         << router_minion::axi_ss.x_coordinate
                         << ',' << router_minion::axi_ss.y_coordinate
                         << ") on fiber " << boost::this_fiber::get_id()
                         << " shutting down");
      }));
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::futures, trisycl::detail::fiber_pool::submit(), TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
~router_minion() [2/2]
template<typename AXIStreamGeography > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::~router_minion () inline override
Destructor handling the correct infrastructure shutdown.
Definition at line 216 of file axi_stream_switch.hpp.
{
      // Send a special packet to shutdown the routing process
      write(axi_packet::shutdown);
      // Wait for shutdown to avoid calling std::terminate on destruction...
      join();
    }
References trisycl::vendor::xilinx::acap::aie::axi_packet::shutdown.
Member Function Documentation
connect_to() [1/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::connect_to (axi_stream_switch::mpl port_dest, std::shared_ptr< communicator_port > dest) inline
Connect this routing input to a switch output.
Definition at line 147 of file axi_stream_switch.hpp.
{
      TRISYCL_DUMP_T("connect_to router_minion " << this << " on tile("
                     << router_minion::axi_ss.x_coordinate
                     << ',' << router_minion::axi_ss.y_coordinate
                     << ") on fiber " << boost::this_fiber::get_id()
                     << " to dest " << &*dest);
      mpl_outputs.push_back(port_dest);
      outputs.push_back(dest);
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::mpl_outputs, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::outputs, TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
connect_to() [2/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::connect_to (axi_stream_switch::mpl port_dest, std::shared_ptr< communicator_port > dest) inline
Connect this routing input to a switch output.
Definition at line 147 of file axi_stream_switch.hpp.
{
      TRISYCL_DUMP_T("connect_to router_minion " << this << " on tile("
                     << router_minion::axi_ss.x_coordinate
                     << ',' << router_minion::axi_ss.y_coordinate
                     << ") on fiber " << boost::this_fiber::get_id()
                     << " to dest " << &*dest);
      mpl_outputs.push_back(port_dest);
      outputs.push_back(dest);
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::mpl_outputs, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::outputs, TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
get_master_port_dests() [1/2]
template<typename AXIStreamGeography > const auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::get_master_port_dests () inline
Return a vector of the master ports this router is forwarding.
Definition at line 160 of file axi_stream_switch.hpp.
{
      return mpl_outputs;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::mpl_outputs.
get_master_port_dests() [2/2]
template<typename AXIStreamGeography > const auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::get_master_port_dests () inline
Return a vector of the master ports this router is forwarding.
Definition at line 160 of file axi_stream_switch.hpp.
{
      return mpl_outputs;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::mpl_outputs.
join() [1/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::join () inline
Wait for the fibers to complete.
Definition at line 86 of file axi_stream_switch.hpp.
                {
      // Wait on all the fibers to finish
      for (auto &f : futures)
        // Get the value of the future, to get an exception if any
        f.get();
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::futures.
join() [2/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::join () inline
Wait for the fibers to complete.
Definition at line 86 of file axi_stream_switch.hpp.
                {
      // Wait on all the fibers to finish
      for (auto &f : futures)
        // Get the value of the future, to get an exception if any
        f.get();
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::futures.
read() [1/2]
template<typename AXIStreamGeography > value_type trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::read () inline override virtual
Waiting read to a core input port.
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 121 of file axi_stream_switch.hpp.
{
      TRISYCL_DUMP_T("router_minion " << this << " on tile("
                     << router_minion::axi_ss.x_coordinate
                     << ',' << router_minion::axi_ss.y_coordinate
                     << ") on fiber " << boost::this_fiber::get_id()
                     << " reading from buffered_channel " << &c << " ...");
      return c.value_pop().data;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c, TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
read() [2/2]
template<typename AXIStreamGeography > value_type trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::read () inline override virtual
Waiting read to a core input port.
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 121 of file axi_stream_switch.hpp.
{
      TRISYCL_DUMP_T("router_minion " << this << " on tile("
                     << router_minion::axi_ss.x_coordinate
                     << ',' << router_minion::axi_ss.y_coordinate
                     << ") on fiber " << boost::this_fiber::get_id()
                     << " reading from buffered_channel " << &c << " ...");
      return c.value_pop().data;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c, TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
try_read() [1/2]
template<typename AXIStreamGeography > bool trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::try_read (value_type & v) inline override virtual
Non-blocking read to a core input port.
Returns
true if the value was correctly read
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 135 of file axi_stream_switch.hpp.
{
      axi_packet p;
      if (c.try_pop(p) == boost::fibers::channel_op_status::success) {
        v = p.data;
        return true;
      }
      return false;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c, and p.
try_read() [2/2]
template<typename AXIStreamGeography > bool trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::try_read (value_type & v) inline override virtual
Non-blocking read to a core input port.
Returns
true if the value was correctly read
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 135 of file axi_stream_switch.hpp.
{
      axi_packet p;
      if (c.try_pop(p) == boost::fibers::channel_op_status::success) {
        v = p.data;
        return true;
      }
      return false;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c, and p.
try_write() [1/2]
template<typename AXIStreamGeography > bool trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::try_write (const axi_packet & v) inline override virtual
Try to enqueue a packet on the router input.
Returns
true if the packet is correctly enqueued
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 115 of file axi_stream_switch.hpp.
{
      return c.try_push(v) != boost::fibers::channel_op_status::full;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c.
try_write() [2/2]
template<typename AXIStreamGeography > bool trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::try_write (const axi_packet & v) inline override virtual
Try to enqueue a packet on the router input.
Returns
true if the packet is correctly enqueued
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 115 of file axi_stream_switch.hpp.
{
      return c.try_push(v) != boost::fibers::channel_op_status::full;
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c.
write() [1/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::write (const axi_packet & v) inline override virtual
Enqueue a packet on the router input.
Todo:
Clean up the API to separate data from signaling
Todo:
separate debug from shutdown case
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 99 of file axi_stream_switch.hpp.
{
      /// \todo separate debug from shutdown case
      TRISYCL_DUMP_T("router_minion " << this
                     << " on tile(" << router_minion::axi_ss.x_coordinate << ','
                     << router_minion::axi_ss.y_coordinate
                     << ") on fiber " << boost::this_fiber::get_id()
                     << " write data value " << v.data
                     << " to buffered_channel " << &c);
      c.push(v);
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c, trisycl::vendor::xilinx::acap::aie::axi_packet::data, TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
write() [2/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::write (const axi_packet & v) inline override virtual
Enqueue a packet on the router input.
Todo:
Clean up the API to separate data from signaling
Todo:
separate debug from shutdown case
Implements trisycl::vendor::xilinx::acap::aie::communicator_port.
Definition at line 99 of file axi_stream_switch.hpp.
{
      /// \todo separate debug from shutdown case
      TRISYCL_DUMP_T("router_minion " << this
                     << " on tile(" << router_minion::axi_ss.x_coordinate << ','
                     << router_minion::axi_ss.y_coordinate
                     << ") on fiber " << boost::this_fiber::get_id()
                     << " write data value " << v.data
                     << " to buffered_channel " << &c);
      c.push(v);
    }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c, trisycl::vendor::xilinx::acap::aie::axi_packet::data, TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate.
Member Data Documentation
axi_ss
template<typename AXIStreamGeography > axi_stream_switch & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::axi_ss
Keep track of the AXI stream switch owning this port for debugging.
Definition at line 83 of file axi_stream_switch.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::connect_to(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::read(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::router_minion(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::write().
c
template<typename AXIStreamGeography > boost::fibers::buffered_channel< axi_packet > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::c { static_cast<std::size_t>(capacity) }
Ingress packet queue.
Definition at line 67 of file axi_stream_switch.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::read(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::try_read(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::try_write(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::write().
capacity
template<typename AXIStreamGeography > const int trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::capacity
Router ingress capacity queue.
Definition at line 64 of file axi_stream_switch.hpp.
futures
template<typename AXIStreamGeography > std::vector<::trisycl::detail::fiber_pool::future< void > > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::futures
To shepherd the routing fibers.
Definition at line 80 of file axi_stream_switch.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::join(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::router_minion().
mpl_outputs
template<typename AXIStreamGeography > std::vector< axi_stream_switch::mpl > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::mpl_outputs
The ids of the outputs port the router minion has to forward to. Used by introspection to track current routing configuration.
Definition at line 72 of file axi_stream_switch.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::connect_to(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::get_master_port_dests().
outputs
template<typename AXIStreamGeography > std::vector< std::shared_ptr< communicator_port > > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::outputs
The outputs the router minion has to forward to.
This what is used to speed up the routing itself even if the id could be enough
Definition at line 77 of file axi_stream_switch.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::connect_to().
The documentation for this class was generated from the following files:
include/sycl/vendor/Xilinx/acap/aie/axi_stream_switch.hpp
include/triSYCL/vendor/Xilinx/acap/aie/axi_stream_switch.hpp