triSYCL implementation of OpenCL SYCL: cl::sycl::cl_float3 Class Reference
cl::sycl::cl_float3 Class Reference
Wrapper of Boost::compute's cl_float3.
#include <opencl_type.hpp>
Public Member Functions
cl_float3 ()=default
cl_float3 (::cl_float3 self_)
cl_float3 (float x, float y, float z)
auto & x ()
auto & y ()
auto & z ()
Private Attributes
::cl_float3 self
Detailed Description
Wrapper of Boost::compute's cl_float3.
Definition at line 18 of file opencl_type.hpp.
Constructor & Destructor Documentation
cl::sycl::cl_float3::cl_float3 () default
cl::sycl::cl_float3::cl_float3 (::cl_float3 self_) inline
Definition at line 27 of file opencl_type.hpp.
                               : self { self_ }
   {}
cl::sycl::cl_float3::cl_float3 (float x, float y, float z) inline
Definition at line 31 of file opencl_type.hpp.
References x(), and y().
                                         : self { x, y, z }
   {}
Member Function Documentation
auto& cl::sycl::cl_float3::x () inline
Definition at line 37 of file opencl_type.hpp.
Referenced by cl_float3().
             {
     return self.s[0];
   }
auto& cl::sycl::cl_float3::y () inline
Definition at line 44 of file opencl_type.hpp.
Referenced by cl_float3().
             {
     return self.s[1];
   }
auto& cl::sycl::cl_float3::z () inline
Definition at line 51 of file opencl_type.hpp.
             {
     return self.s[2];
   }
Member Data Documentation
::cl_float3 cl::sycl::cl_float3::self private
Definition at line 20 of file opencl_type.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/opencl_type.hpp