triSYCL implementation of SYCL: trisycl::detail::cache< Key, Value > Class Template Reference
trisycl::detail::cache< Key, Value > Class Template Reference
A simple thread safe cache mechanism to cache std::shared_ptr of values indexed by keys.
#include <cache.hpp>
Public Types
using key_type = Key
The type of the keys used to indexed the cache.
using value_type = Value
The base type of the values stored in the cache.
Public Member Functions
template<typename Functor >
std::shared_ptr< value_type > get_or_register (const key_type &k, Functor &&create_element)
Get a value stored in the cache if present or insert by calling a generator function.
void remove (const key_type &k)
Remove an entry from the cache.
Private Attributes
std::unordered_map< key_type, std::weak_ptr< value_type > > c
The caching storage.
std::mutex m
To make the cache thread-safe.
Detailed Description
template<typename Key, typename Value>
class trisycl::detail::cache< Key, Value >
A simple thread safe cache mechanism to cache std::shared_ptr of values indexed by keys.
Since internally only std::weak_ptr are stored, this does not prevent object deletion but it is up to the programmer not to use this cache to retrieve deleted objects.
Definition at line 27 of file cache.hpp.
Member Typedef Documentation
key_type
template<typename Key , typename Value > using trisycl::detail::cache< Key, Value >::key_type = Key
The type of the keys used to indexed the cache.
Definition at line 32 of file cache.hpp.
value_type
template<typename Key , typename Value > using trisycl::detail::cache< Key, Value >::value_type = Value
The base type of the values stored in the cache.
Definition at line 35 of file cache.hpp.
Member Function Documentation
get_or_register()
template<typename Key , typename Value > template<typename Functor > std::shared_ptr< value_type > trisycl::detail::cache< Key, Value >::get_or_register (const key_type & k, Functor && create_element) inline
Get a value stored in the cache if present or insert by calling a generator function.
Parameters
[in] k is the key used to retrieve the value
[in] create_element is the function to be called if the key is not found in the cache to generate a value which is inserted for the key. This function has to produce a value convertible to a shared_ptr
Returns
a shared_ptr to the value retrieved or inserted
Definition at line 60 of file cache.hpp.
{
    std::lock_guard<std::mutex> lg { m };
    auto i = c.find(k);
    if (i != c.end())
      if (auto observe = i->second.lock())
        // Returns \c shared_ptr only if target object is still alive
        return observe;
    // Otherwise create and insert a new element
    std::shared_ptr<value_type> e { create_element() };
    c.insert({ k, e });
    return e;
  }
References trisycl::detail::cache< Key, Value >::c, i, and trisycl::detail::cache< Key, Value >::m.
Referenced by trisycl::detail::opencl_queue::instance(), trisycl::detail::opencl_context::instance(), trisycl::detail::opencl_device::instance(), trisycl::detail::opencl_event::instance(), trisycl::detail::opencl_kernel::instance(), and trisycl::detail::opencl_platform::instance().
remove()
template<typename Key , typename Value > void trisycl::detail::cache< Key, Value >::remove (const key_type & k) inline
Remove an entry from the cache.
Parameters
[in] k is the key associated to the value to remove from the cache
Definition at line 82 of file cache.hpp.
{
    std::lock_guard<std::mutex> lg { m };
    c.erase(k);
  }
References trisycl::detail::cache< Key, Value >::c, and trisycl::detail::cache< Key, Value >::m.
Referenced by trisycl::detail::opencl_kernel::TRISYCL_ParallelForKernel_RANGE(), trisycl::detail::opencl_context::~opencl_context(), trisycl::detail::opencl_device::~opencl_device(), trisycl::detail::opencl_event::~opencl_event(), trisycl::detail::opencl_platform::~opencl_platform(), and trisycl::detail::opencl_queue::~opencl_queue().
Member Data Documentation
c
template<typename Key , typename Value > std::unordered_map<key_type, std::weak_ptr<value_type> > trisycl::detail::cache< Key, Value >::c private
The caching storage.
Definition at line 40 of file cache.hpp.
Referenced by trisycl::detail::cache< Key, Value >::get_or_register(), and trisycl::detail::cache< Key, Value >::remove().
m
template<typename Key , typename Value > std::mutex trisycl::detail::cache< Key, Value >::m private
To make the cache thread-safe.
Definition at line 43 of file cache.hpp.
Referenced by trisycl::detail::cache< Key, Value >::get_or_register(), and trisycl::detail::cache< Key, Value >::remove().
The documentation for this class was generated from the following file:
include/triSYCL/detail/cache.hpp