triSYCL implementation of SYCL: trisycl::vendor::xilinx::acap::aie::communicator_port Class Reference
trisycl::vendor::xilinx::acap::aie::communicator_port Class Reference abstract
Abstract interface for a communication port.
#include <connection.hpp>
Public Member Functions
virtual void write (const axi_packet &)=0
Enqueue a packet on the communicator input.
auto & operator<< (const axi_packet::value_type &v)
Alias to enqueue a packet on the communicator input.
virtual bool try_write (const axi_packet &)=0
Try to enqueue a packet to input.
virtual axi_packet::value_type read ()=0
Waiting read to a core input port.
virtual bool try_read (axi_packet::value_type &)=0
Non-blocking read from a communicator output port.
template<typename T >
auto & operator>> (T &v)
Alias to the waiting read to a communicator output port.
virtual ~communicator_port ()=default
Nothing specific to do but need a virtual destructor to avoid slicing.
virtual void write (const axi_packet &)=0
Enqueue a packet on the communicator input.
auto & operator<< (const axi_packet::value_type &v)
Alias to enqueue a packet on the communicator input.
virtual bool try_write (const axi_packet &)=0
Try to enqueue a packet to input.
virtual axi_packet::value_type read ()=0
Waiting read to a core input port.
virtual bool try_read (axi_packet::value_type &)=0
Non-blocking read from a communicator output port.
template<typename T >
auto & operator>> (T &v)
Alias to the waiting read to a communicator output port.
virtual ~communicator_port ()=default
Nothing specific to do but need a virtual destructor to avoid slicing.
Additional Inherited Members
Static Private Member Functions inherited from trisycl::detail::debug< communicator_port >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Detailed Description
Abstract interface for a communication port.
For example a router output is actually implemented as an input to some other consumer (router, core...).
Definition at line 67 of file connection.hpp.
Constructor & Destructor Documentation
~communicator_port() [1/2]
virtual trisycl::vendor::xilinx::acap::aie::communicator_port::~communicator_port () virtual default
Nothing specific to do but need a virtual destructor to avoid slicing.
~communicator_port() [2/2]
virtual trisycl::vendor::xilinx::acap::aie::communicator_port::~communicator_port () virtual default
Nothing specific to do but need a virtual destructor to avoid slicing.
Member Function Documentation
operator<<() [1/2]
auto & trisycl::vendor::xilinx::acap::aie::communicator_port::operator<< (const axi_packet::value_type & v) inline
Alias to enqueue a packet on the communicator input.
Definition at line 76 of file connection.hpp.
{
    write(v);
    return *this;
  }
References write().
operator<<() [2/2]
auto & trisycl::vendor::xilinx::acap::aie::communicator_port::operator<< (const axi_packet::value_type & v) inline
Alias to enqueue a packet on the communicator input.
Definition at line 76 of file connection.hpp.
{
    write(v);
    return *this;
  }
References write().
operator>>() [1/2]
template<typename T > auto & trisycl::vendor::xilinx::acap::aie::communicator_port::operator>> (T & v) inline
Alias to the waiting read to a communicator output port.
Definition at line 102 of file connection.hpp.
{
    v = static_cast<T>(read());
    return *this;
  }
References read().
operator>>() [2/2]
template<typename T > auto & trisycl::vendor::xilinx::acap::aie::communicator_port::operator>> (T & v) inline
Alias to the waiting read to a communicator output port.
Definition at line 102 of file connection.hpp.
{
    v = static_cast<T>(read());
    return *this;
  }
References read().
read() [1/2]
virtual axi_packet::value_type trisycl::vendor::xilinx::acap::aie::communicator_port::read () pure virtual
Waiting read to a core input port.
Implemented in trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >.
Referenced by operator>>().
read() [2/2]
virtual axi_packet::value_type trisycl::vendor::xilinx::acap::aie::communicator_port::read () pure virtual
Waiting read to a core input port.
Implemented in trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >.
try_read() [1/2]
virtual bool trisycl::vendor::xilinx::acap::aie::communicator_port::try_read (axi_packet::value_type &) pure virtual
Non-blocking read from a communicator output port.
Returns
true if the value was correctly read
Implemented in trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, and trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >.
try_read() [2/2]
virtual bool trisycl::vendor::xilinx::acap::aie::communicator_port::try_read (axi_packet::value_type &) pure virtual
Non-blocking read from a communicator output port.
Returns
true if the value was correctly read
Implemented in trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, and trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >.
try_write() [1/2]
virtual bool trisycl::vendor::xilinx::acap::aie::communicator_port::try_write (const axi_packet &) pure virtual
Try to enqueue a packet to input.
Returns
true if the packet is correctly enqueued
Implemented in trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >.
try_write() [2/2]
virtual bool trisycl::vendor::xilinx::acap::aie::communicator_port::try_write (const axi_packet &) pure virtual
Try to enqueue a packet to input.
Returns
true if the packet is correctly enqueued
Implemented in trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >.
write() [1/2]
virtual void trisycl::vendor::xilinx::acap::aie::communicator_port::write (const axi_packet &) pure virtual
Enqueue a packet on the communicator input.
Implemented in trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >.
Referenced by operator<<().
write() [2/2]
virtual void trisycl::vendor::xilinx::acap::aie::communicator_port::write (const axi_packet &) pure virtual
Enqueue a packet on the communicator input.
Implemented in trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion, trisycl::vendor::xilinx::acap::aie::fifo_channel, trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >, and trisycl::vendor::xilinx::acap::aie::receiving_dma< AXIStreamSwitch >.
The documentation for this class was generated from the following files:
include/sycl/vendor/Xilinx/acap/aie/connection.hpp
include/triSYCL/vendor/Xilinx/acap/aie/connection.hpp