triSYCL implementation of SYCL: trisycl::detail::opencl_kernel Class Reference
trisycl::detail::opencl_kernel Class Reference
An abstraction of the OpenCL kernel.
#include <opencl_kernel.hpp>
Public Member Functions
cl_kernel get () const override
Return the underlying OpenCL object.
boost::compute::kernel & get_boost_compute () override
Return the Boost.Compute OpenCL kernel object for this kernel.
void single_task (std::shared_ptr< detail::task > task, std::shared_ptr< detail::queue > q) override
Launch a single task of the OpenCL kernel.
TRISYCL_ParallelForKernel_RANGE (1) TRISYCL_ParallelForKernel_RANGE(2) TRISYCL_ParallelForKernel_RANGE(3) ~opencl_kernel() override
Unregister from the cache on destruction.
Public Member Functions inherited from trisycl::detail::kernel
TRISYCL_ParallelForKernel_RANGE (1) TRISYCL_ParallelForKernel_RANGE(2) TRISYCL_ParallelForKernel_RANGE(3) virtual ~kernel()
Return the context that this kernel is defined for.
Static Public Member Functions
static std::shared_ptr< opencl_kernel > instance (const boost::compute::kernel &k)
Private Member Functions
opencl_kernel (const boost::compute::kernel &k)
Private Attributes
boost::compute::kernel k
Use the Boost Compute abstraction of the OpenCL kernel.
Static Private Attributes
static detail::cache< cl_kernel, detail::opencl_kernel > cache
A cache to always return the same alive kernel for a given OpenCL kernel.
Detailed Description
An abstraction of the OpenCL kernel.
Definition at line 27 of file opencl_kernel.hpp.
Constructor & Destructor Documentation
opencl_kernel()
trisycl::detail::opencl_kernel::opencl_kernel (const boost::compute::kernel & k) inline private
Definition at line 40 of file opencl_kernel.hpp.
 : k { k } {}
Member Function Documentation
get()
cl_kernel trisycl::detail::opencl_kernel::get () const inline override virtual
Return the underlying OpenCL object.
Todo:
Improve the spec to deprecate C OpenCL host API and move to C++ instead to avoid this ugly ownership management
Todo:
Test error and throw. Externalize this feature in Boost.Compute?
Implements trisycl::detail::kernel.
Definition at line 56 of file opencl_kernel.hpp.
{
     /// \todo Test error and throw. Externalize this feature in Boost.Compute?
     clRetainKernel(k);
     return k.get();
   }
get_boost_compute()
boost::compute::kernel& trisycl::detail::opencl_kernel::get_boost_compute () inline override virtual
Return the Boost.Compute OpenCL kernel object for this kernel.
This is an extension.
Implements trisycl::detail::kernel.
Definition at line 67 of file opencl_kernel.hpp.
References k, and TRISYCL_UNIMPL.
{
     return k;
   }
instance()
static std::shared_ptr<opencl_kernel> trisycl::detail::opencl_kernel::instance (const boost::compute::kernel & k) inline static
Definition at line 46 of file opencl_kernel.hpp.
References trisycl::detail::cache< Key, Value >::get_or_register().
Referenced by trisycl::kernel::kernel().
{
     return cache.get_or_register(k.get(),
                                  [&] { return new opencl_kernel { k }; });
   }
single_task()
void trisycl::detail::opencl_kernel::single_task (std::shared_ptr< detail::task > task, std::shared_ptr< detail::queue > q) inline override virtual
Launch a single task of the OpenCL kernel.
Todo:
Remove either task or q
Implements trisycl::detail::kernel.
Definition at line 89 of file opencl_kernel.hpp.
{
     q->get_boost_compute().enqueue_task(k);
     /* For now use a crude synchronization mechanism to map directly a
        host task to an accelerator task */
     q->get_boost_compute().finish();
   }
TRISYCL_ParallelForKernel_RANGE()
trisycl::detail::opencl_kernel::TRISYCL_ParallelForKernel_RANGE (1) inline override
Unregister from the cache on destruction.
Definition at line 124 of file opencl_kernel.hpp.
References cache, trisycl::detail::cache< Key, Value >::remove(), TRISYCL_WEAK_ATTRIB_PREFIX, and trisycl::detail::TRISYCL_WEAK_ATTRIB_SUFFIX.
{
     cache.remove(k.get());
   }
Member Data Documentation
cache
detail::cache<cl_kernel, detail::opencl_kernel> trisycl::detail::opencl_kernel::cache static private
A cache to always return the same alive kernel for a given OpenCL kernel.
C++11 guaranties the static construction is thread-safe
Definition at line 38 of file opencl_kernel.hpp.
Referenced by TRISYCL_ParallelForKernel_RANGE().
k
boost::compute::kernel trisycl::detail::opencl_kernel::k private
Use the Boost Compute abstraction of the OpenCL kernel.
Definition at line 31 of file opencl_kernel.hpp.
Referenced by get_boost_compute().
The documentation for this class was generated from the following file:
include/triSYCL/kernel/detail/opencl_kernel.hpp