triSYCL implementation of SYCL: trisycl::event Class Reference
trisycl::event Class Reference
SYCL event.
#include <event.hpp>
Public Member Functions
event ()
event (cl_event clEvent, const context &syclContext)
Construct an event class using the clEvent from OpenCL.
event (const boost::compute::event &e)
Construct an event class using the boost::compute::event.
bool is_host () const
Return true if the event is a SYCL host event.
cl_event get ()
Return the cl_event from the underlying OpenCL event.
boost::compute::event get_boost_compute () const
Return the underlying boost compute event.
vector_class< event > get_wait_list ()
void wait ()
Wait for the event and the command associated with it to complete.
void wait_and_throw ()
template<info::event param>
auto get_info () const
Query the event for information.
template<info::event_profiling param>
auto get_profiling_info () const
Query the event for event profiling.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< event, detail::event >
shared_ptr_implementation (std::shared_ptr< detail::event > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::event *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const event &other) const
Equality operator.
bool operator< (const event &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Static Public Member Functions
static void wait (const vector_class< event > &eventList)
static void wait_and_throw (const vector_class< event > &eventList)
Private Types
using implementation_t = typename event::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< event, detail::event >
std::shared_ptr< detail::event > implementation
The implementation forward everything to this... implementation.
Detailed Description
SYCL event.
Definition at line 21 of file event.hpp.
Member Typedef Documentation
implementation_t
using trisycl::event::implementation_t = typename event::shared_ptr_implementation private
Definition at line 24 of file event.hpp.
Constructor & Destructor Documentation
event() [1/3]
trisycl::event::event () inline
Definition at line 29 of file event.hpp.
References trisycl::detail::singleton< host_event >::instance().
 : implementation_t { detail::host_event::instance() } {}
event() [2/3]
trisycl::event::event (cl_event clEvent, const context & syclContext) inline
Construct an event class using the clEvent from OpenCL.
This is a triSYCL extension for boost::compute interoperation.
Definition at line 36 of file event.hpp.
References event.
     : event { boost::compute::event { clEvent } } {}
event() [3/3]
trisycl::event::event (const boost::compute::event & e) inline
Construct an event class using the boost::compute::event.
This is a triSYCL extension for boost::compute interoperation.
Definition at line 43 of file event.hpp.
References trisycl::detail::opencl_event::instance().
     : implementation_t { detail::opencl_event::instance(e) } {}
Member Function Documentation
get()
cl_event trisycl::event::get () inline
Return the cl_event from the underlying OpenCL event.
Definition at line 52 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
                  {
     return implementation->get();
   }
get_boost_compute()
boost::compute::event trisycl::event::get_boost_compute () const inline
Return the underlying boost compute event.
This is a triSYCL extension
Definition at line 60 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
{
     return implementation->get_boost_compute();
   }
get_info()
template<info::event param> auto trisycl::event::get_info () const inline
Query the event for information.
Referenced by wait_and_throw().
get_profiling_info()
template<info::event_profiling param> auto trisycl::event::get_profiling_info () const inline
Query the event for event profiling.
Referenced by wait_and_throw().
get_wait_list()
vector_class<event> trisycl::event::get_wait_list () inline
Definition at line 65 of file event.hpp.
References TRISYCL_UNIMPL.
{
     TRISYCL_UNIMPL;
     return {};
   }
is_host()
bool trisycl::event::is_host () const inline
Return true if the event is a SYCL host event.
Definition at line 48 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
 { return implementation->is_host(); }
wait() [1/2]
void trisycl::event::wait () inline
Wait for the event and the command associated with it to complete.
Definition at line 73 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
               {
     implementation->wait();
   }
wait() [2/2]
static void trisycl::event::wait (const vector_class< event > & eventList) inline static
Definition at line 77 of file event.hpp.
References TRISYCL_UNIMPL.
{
     TRISYCL_UNIMPL;
   }
wait_and_throw() [1/2]
void trisycl::event::wait_and_throw () inline
Definition at line 81 of file event.hpp.
References TRISYCL_UNIMPL.
{
     TRISYCL_UNIMPL;
   }
wait_and_throw() [2/2]
static void trisycl::event::wait_and_throw (const vector_class< event > & eventList) inline static
Definition at line 85 of file event.hpp.
References get_info(), get_profiling_info(), and TRISYCL_UNIMPL.
{
     TRISYCL_UNIMPL;
   }
Member Data Documentation
implementation_t
friend trisycl::event::implementation_t private
Definition at line 26 of file event.hpp.
The documentation for this class was generated from the following file:
include/triSYCL/event.hpp