triSYCL implementation of SYCL: Platforms, contexts, accessors and queues
Platforms, contexts, accessors and queues
Namespaces
namespace trisycl::detail
Some global triSYCL configuration.
namespace trisycl::info
Classes
class trisycl::facade::accessor< AccessorMixIn >
SYCL accessor facade providing multi-dimensional access features.
class trisycl::mixin::accessor< T, Dimensions >
SYCL accessor mixin providing multi-dimensional access features.
class trisycl::context
SYCL context.
class trisycl::detail::context
class trisycl::detail::host_context
SYCL host context.
class trisycl::device
SYCL device.
class trisycl::detail::device
An abstract class representing various models of SYCL devices.
class trisycl::facade::device< UserFacing, ImplementationDetail >
SYCL device.
class trisycl::device_selector
The SYCL heuristics to select a device.
class trisycl::device_type_selector
A device selector by device_type.
class trisycl::device_typename_selector< DeviceType >
Select a device by template device_type parameter.
class trisycl::handler
Command group handler class.
class trisycl::kernel
SYCL kernel.
class trisycl::detail::kernel
Abstract SYCL kernel.
class trisycl::platform
Abstract the OpenCL platform.
class trisycl::detail::host_platform
SYCL host platform.
class trisycl::detail::opencl_platform
SYCL OpenCL platform.
class trisycl::detail::platform
An abstract class representing various models of SYCL platforms.
class trisycl::queue
SYCL queue, similar to the OpenCL queue concept.
Macros
#define PLATFORM_GET_INFO_STRING(X)
Typedefs
using trisycl::default_selector = device_typename_selector< info::device_type::automatic >
Devices selected by heuristics of the system.
using trisycl::gpu_selector = device_typename_selector< info::device_type::gpu >
Select devices according to device type info::device::device_type::gpu from all the available OpenCL devices.
using trisycl::cpu_selector = device_typename_selector< info::device_type::cpu >
Select devices according to device type info::device::device_type::cpu from all the available devices and heuristics.
using trisycl::host_selector = device_typename_selector< info::device_type::host >
Selects the SYCL host CPU device that does not require an OpenCL runtime.
using trisycl::info::device_fp_config = unsigned int
using trisycl::info::device_exec_capabilities = unsigned int
using trisycl::info::device_queue_properties = unsigned int
Enumerations
enum class trisycl::info::context : int { trisycl::info::context::reference_count , trisycl::info::context::platform , trisycl::info::context::devices }
Context information descriptors.
enum class trisycl::info::device_type : unsigned int {
trisycl::info::device_type::cpu , trisycl::info::device_type::gpu , trisycl::info::device_type::accelerator , trisycl::info::device_type::custom ,
trisycl::info::device_type::automatic , trisycl::info::device_type::host , trisycl::info::device_type::opencl , trisycl::info::device_type::all
}
Type of devices.
enum class trisycl::info::device : int {
trisycl::info::device::device_type , trisycl::info::device::vendor_id , trisycl::info::device::max_compute_units , trisycl::info::device::max_work_item_dimensions ,
trisycl::info::device::max_work_item_sizes , trisycl::info::device::max_work_group_size , trisycl::info::device::preferred_vector_width_char , trisycl::info::device::preferred_vector_width_short ,
trisycl::info::device::preferred_vector_width_int , trisycl::info::device::preferred_vector_width_long , trisycl::info::device::preferred_vector_width_float , trisycl::info::device::preferred_vector_width_double ,
trisycl::info::device::preferred_vector_width_half , trisycl::info::device::native_vector_width_char , trisycl::info::device::native_vector_width_short , trisycl::info::device::native_vector_width_int ,
trisycl::info::device::native_vector_width_long , trisycl::info::device::native_vector_width_float , trisycl::info::device::native_vector_width_double , trisycl::info::device::native_vector_width_half ,
trisycl::info::device::max_clock_frequency , trisycl::info::device::address_bits , trisycl::info::device::max_mem_alloc_size , trisycl::info::device::image_support ,
trisycl::info::device::max_read_image_args , trisycl::info::device::max_write_image_args , trisycl::info::device::image2d_max_width , trisycl::info::device::image2d_max_height ,
trisycl::info::device::image3d_max_width , trisycl::info::device::image3d_max_height , trisycl::info::device::image3d_max_depth , trisycl::info::device::image_max_buffer_size ,
trisycl::info::device::image_max_array_size , trisycl::info::device::max_samplers , trisycl::info::device::max_parameter_size , trisycl::info::device::mem_base_addr_align ,
trisycl::info::device::half_fp_config , trisycl::info::device::single_fp_config , trisycl::info::device::double_fp_config , trisycl::info::device::global_mem_cache_type ,
trisycl::info::device::global_mem_cache_line_size , trisycl::info::device::global_mem_cache_size , trisycl::info::device::global_mem_size , trisycl::info::device::max_constant_buffer_size ,
trisycl::info::device::max_constant_args , trisycl::info::device::local_mem_type , trisycl::info::device::local_mem_size , trisycl::info::device::error_correction_support ,
trisycl::info::device::host_unified_memory , trisycl::info::device::profiling_timer_resolution , trisycl::info::device::is_endian_little , trisycl::info::device::is_available ,
trisycl::info::device::is_compiler_available , trisycl::info::device::is_linker_available , trisycl::info::device::execution_capabilities , trisycl::info::device::queue_profiling ,
trisycl::info::device::built_in_kernels , trisycl::info::device::platform , trisycl::info::device::name , trisycl::info::device::vendor ,
trisycl::info::device::driver_version , trisycl::info::device::profile , trisycl::info::device::version , trisycl::info::device::opencl_c_version ,
trisycl::info::device::extensions , trisycl::info::device::printf_buffer_size , trisycl::info::device::preferred_interop_user_sync , trisycl::info::device::parent_device ,
trisycl::info::device::partition_max_sub_devices , trisycl::info::device::partition_properties , trisycl::info::device::partition_affinity_domains , trisycl::info::device::partition_type_property ,
trisycl::info::device::partition_type_affinity_domain , trisycl::info::device::reference_count
}
Device information descriptors.
enum class trisycl::info::partition_property : int { trisycl::info::partition_property::no_partition , trisycl::info::partition_property::partition_equally , trisycl::info::partition_property::partition_by_counts , trisycl::info::partition_property::partition_by_affinity_domain }
enum class trisycl::info::partition_affinity_domain : int {
trisycl::info::partition_affinity_domain::not_applicable , trisycl::info::partition_affinity_domain::numa , trisycl::info::partition_affinity_domain::L4_cache , trisycl::info::partition_affinity_domain::L3_cache ,
trisycl::info::partition_affinity_domain::L2_cache , trisycl::info::partition_affinity_domain::L1_cache , trisycl::info::partition_affinity_domain::next_partitionable
}
enum class trisycl::info::local_mem_type : int { trisycl::info::local_mem_type::none , trisycl::info::local_mem_type::local , trisycl::info::local_mem_type::global }
enum class trisycl::info::fp_config : int {
trisycl::info::fp_config::denorm , trisycl::info::fp_config::inf_nan , trisycl::info::fp_config::round_to_nearest , trisycl::info::fp_config::round_to_zero ,
trisycl::info::fp_config::round_to_inf , trisycl::info::fp_config::fma , trisycl::info::fp_config::correctly_rounded_divide_sqrt , trisycl::info::fp_config::soft_float
}
enum class trisycl::info::global_mem_cache_type : int { trisycl::info::global_mem_cache_type::none , trisycl::info::global_mem_cache_type::read_only , trisycl::info::global_mem_cache_type::write_only }
enum class trisycl::info::execution_capability : unsigned int { trisycl::info::execution_capability::exec_kernel , trisycl::info::execution_capability::exec_native_kernel }
enum class trisycl::info::platform : unsigned int {
trisycl::info::platform::TRISYCL_OPENCL_ONLY =(= CL_PLATFORM_PROFILE) , trisycl::info::platform::TRISYCL_OPENCL_ONLY =(= CL_PLATFORM_VERSION) , trisycl::info::platform::TRISYCL_OPENCL_ONLY =(= CL_PLATFORM_NAME) , trisycl::info::platform::TRISYCL_OPENCL_ONLY =(= CL_PLATFORM_VENDOR) ,
trisycl::info::platform::TRISYCL_OPENCL_ONLY =(= CL_PLATFORM_EXTENSIONS)
}
Platform information descriptors.
Functions
template<>
auto trisycl::context::get_info< info::context::reference_count > () const
template<>
auto trisycl::context::get_info< info::context::platform > () const
template<>
auto trisycl::context::get_info< info::context::devices > () const
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image2d_max_width, size_t)
Query the return type for get_info() on context stuff.
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image2d_max_height, size_t)
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image3d_max_width, size_t)
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image3d_max_height, size_t)
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image3d_max_depth, size_t)
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image_max_buffer_size, size_t)
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image_max_array_size, size_t)
template<>
auto trisycl::platform::get_info< info::platform::extensions > () const
template<>
auto trisycl::queue::get_info< info::queue::device > () const
template<>
auto trisycl::queue::get_info< info::queue::context > () const
template<>
auto trisycl::queue::get_info< info::queue::reference_count > () const
device trisycl::device_selector::select_device (vector_class< platform > platforms) const
device trisycl::device_selector::select_device () const
Returns a selected device using the functor operator defined in sub-classes operator()(const device &dev)
vector_class< trisycl::device > trisycl::detail::host_platform::get_devices (const device_selector &device_selector) const override
Get all the available devices for the host platform.
vector_class< trisycl::device > trisycl::detail::opencl_platform::get_devices (const device_selector &device_selector) const override
Get all the available devices for this OpenCL platform.
Variables
TRISYCL_WEAK_ATTRIB_PREFIX detail::cache< cl_context, detail::opencl_context > opencl_context::cache trisycl::detail::TRISYCL_WEAK_ATTRIB_SUFFIX
Detailed Description
Class Documentation
trisycl::facade::accessor
class trisycl::facade::accessor
template<typename AccessorMixIn>
class trisycl::facade::accessor< AccessorMixIn >
SYCL accessor facade providing multi-dimensional access features.
Definition at line 28 of file accessor.hpp.
Public Types
using iterator = typename mixin::pointer
using const_iterator = typename mixin::const_pointer
using reverse_iterator = typename std::reverse_iterator< iterator >
using const_reverse_iterator = typename std::reverse_iterator< const_iterator >
Public Member Functions
template<std::integral... T>
decltype(auto) operator[] (T... indices)
Use the accessor with integers la [i1][i2][i3] or C++23 [i1, i2,...].
template<std::integral... T>
decltype(auto) operator[] (T... indices) const
Use the accessor with integers la [i1][i2][i3] or C++23 [i1, i2,...].
decltype(auto) operator[] (const id< mixin::rank()> &index)
To use the accessor with [id<>].
decltype(auto) operator[] (const id< mixin::rank()> &index) const
To use the accessor with [id<>].
decltype(auto) operator[] (const item< mixin::rank()> &index)
To use an accessor with [item<>].
decltype(auto) operator[] (const item< mixin::rank()> &index) const
To use an accessor with [item<>].
decltype(auto) operator[] (const nd_item< mixin::rank()> &index)
To use an accessor with an [nd_item<>].
decltype(auto) operator[] (const nd_item< mixin::rank()> &index) const
To use an accessor with an [nd_item<>].
mixin::reference operator* ()
Get the first element of the accessor.
mixin::reference operator* () const
Get the first element of the accessor.
auto get_pointer ()
Return the pointer to the data.
iterator begin ()
Forward all the iterator functions to the implementation.
iterator end ()
const_iterator cbegin ()
const_iterator cend ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
Private Types
using mixin = AccessorMixIn
Member Typedef Documentation
const_iterator
template<typename AccessorMixIn > using trisycl::facade::accessor< AccessorMixIn >::const_iterator = typename mixin::const_pointer
Definition at line 34 of file accessor.hpp.
const_reverse_iterator
template<typename AccessorMixIn > using trisycl::facade::accessor< AccessorMixIn >::const_reverse_iterator = typename std::reverse_iterator<const_iterator>
Definition at line 36 of file accessor.hpp.
iterator
template<typename AccessorMixIn > using trisycl::facade::accessor< AccessorMixIn >::iterator = typename mixin::pointer
Definition at line 33 of file accessor.hpp.
mixin
template<typename AccessorMixIn > using trisycl::facade::accessor< AccessorMixIn >::mixin = AccessorMixIn private
Definition at line 30 of file accessor.hpp.
reverse_iterator
template<typename AccessorMixIn > using trisycl::facade::accessor< AccessorMixIn >::reverse_iterator = typename std::reverse_iterator<iterator>
Definition at line 35 of file accessor.hpp.
Member Function Documentation
begin()
template<typename AccessorMixIn > iterator trisycl::facade::accessor< AccessorMixIn >::begin () inline
Forward all the iterator functions to the implementation.
Todo:
Add these functions to the specification
Todo:
The fact that the lambda capture make a const copy of the accessor is not yet elegantly managed... The issue is that begin()/end() dispatch is made according to the accessor constness and not from the array member constness...
Todo:
try to solve it by using some enable_if on array constness?
Todo:
The issue is that the end may not be known if it is implemented by a raw OpenCL cl_mem... So only provide on the device the iterators related to the start? Actually the accessor needs to know a part of the shape to have the multidimentional addressing. So this only require a size_t more...
Todo:
Factor out these in a template helper
Todo:
Do we need this in detail::accessor too or only in accessor?
Definition at line 155 of file accessor.hpp.
{ return mixin::data(); }
Referenced by trisycl::facade::accessor< AccessorMixIn >::rend().
cbegin()
template<typename AccessorMixIn > const_iterator trisycl::facade::accessor< AccessorMixIn >::cbegin () inline
Definition at line 159 of file accessor.hpp.
{ return mixin::data(); }
Referenced by trisycl::facade::accessor< AccessorMixIn >::crend().
cend()
template<typename AccessorMixIn > const_iterator trisycl::facade::accessor< AccessorMixIn >::cend () inline
Definition at line 161 of file accessor.hpp.
{ return mixin::data() + mixin::get_count(); }
Referenced by trisycl::facade::accessor< AccessorMixIn >::crbegin().
crbegin()
template<typename AccessorMixIn > const_reverse_iterator trisycl::facade::accessor< AccessorMixIn >::crbegin () const inline
Definition at line 170 of file accessor.hpp.
{
    return std::reverse_iterator(cend());
  }
References trisycl::facade::accessor< AccessorMixIn >::cend().
crend()
template<typename AccessorMixIn > const_reverse_iterator trisycl::facade::accessor< AccessorMixIn >::crend () const inline
Definition at line 174 of file accessor.hpp.
{
    return std::reverse_iterator(cbegin());
  }
References trisycl::facade::accessor< AccessorMixIn >::cbegin().
end()
template<typename AccessorMixIn > iterator trisycl::facade::accessor< AccessorMixIn >::end () inline
Definition at line 157 of file accessor.hpp.
{ return mixin::data() + mixin::get_count(); }
Referenced by trisycl::facade::accessor< AccessorMixIn >::rbegin().
get_pointer()
template<typename AccessorMixIn > auto trisycl::facade::accessor< AccessorMixIn >::get_pointer () inline
Return the pointer to the data.
Todo:
Implement the various pointer address spaces
Definition at line 130 of file accessor.hpp.
{ return mixin::data(); }
operator*() [1/2]
template<typename AccessorMixIn > mixin::reference trisycl::facade::accessor< AccessorMixIn >::operator* () inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add to the specification
Definition at line 112 of file accessor.hpp.
{ return *mixin::data(); }
operator*() [2/2]
template<typename AccessorMixIn > mixin::reference trisycl::facade::accessor< AccessorMixIn >::operator* () const inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add to the specification?
Todo:
Add the concept of 0-dim buffer and accessor for scalar and use an implicit conversion to value_type reference to access the value with the accessor?
Definition at line 124 of file accessor.hpp.
{ return *mixin::data(); }
operator[]() [1/8]
template<typename AccessorMixIn > decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (const id< mixin::rank()> & index) inline
To use the accessor with [id<>].
Definition at line 71 of file accessor.hpp.
{
    return mixin::tuple_indexed_access(index);
  }
operator[]() [2/8]
template<typename AccessorMixIn > decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (const id< mixin::rank()> & index) const inline
To use the accessor with [id<>].
Definition at line 76 of file accessor.hpp.
{
    return mixin::tuple_indexed_access(index);
  }
operator[]() [3/8]
template<typename AccessorMixIn > decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (const item< mixin::rank()> & index) inline
To use an accessor with [item<>].
Definition at line 81 of file accessor.hpp.
{
    return (*this)[index.get()];
  }
operator[]() [4/8]
template<typename AccessorMixIn > decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (const item< mixin::rank()> & index) const inline
To use an accessor with [item<>].
Definition at line 86 of file accessor.hpp.
{
    return (*this)[index.get()];
  }
operator[]() [5/8]
template<typename AccessorMixIn > decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (const nd_item< mixin::rank()> & index) inline
To use an accessor with an [nd_item<>].
Todo:
Add to the specification because used by HPC-GPU slide 22
Definition at line 94 of file accessor.hpp.
{
    return (*this)[index.get_global()];
  }
operator[]() [6/8]
template<typename AccessorMixIn > decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (const nd_item< mixin::rank()> & index) const inline
To use an accessor with an [nd_item<>].
Todo:
Add to the specification because used by HPC-GPU slide 22
Definition at line 102 of file accessor.hpp.
{
    return (*this)[index.get_global()];
  }
operator[]() [7/8]
template<typename AccessorMixIn > template<std::integral... T> decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (T... indices) inline
Use the accessor with integers la [i1][i2][i3] or C++23 [i1, i2,...].
Returns
decltype(auto) to return either a reference to the final element when the indexing has been fully resolved or a proxy object to handle the remaining []
Definition at line 43 of file accessor.hpp.
{
    if constexpr (sizeof...(T) == 1)
      /* The [][][] case uses a proxy object to track all the [index]
         and aggregate them to resolve the indexing */
      return
          typename mixin::template track_index<1> { mixin::access }[indices...];
    else
      // Or just the C++23 [i1, i2,...] case
      return mixin::access[indices...];
  }
operator[]() [8/8]
template<typename AccessorMixIn > template<std::integral... T> decltype(auto) trisycl::facade::accessor< AccessorMixIn >::operator[] (T... indices) const inline
Use the accessor with integers la [i1][i2][i3] or C++23 [i1, i2,...].
Returns
decltype(auto) to return either a reference to the final element when the indexing has been fully resolved or a proxy object to handle the remaining []
Definition at line 59 of file accessor.hpp.
{
    if constexpr (sizeof...(T) == 1)
      /* The [][][] case uses a proxy object to track all the [index]
         and aggregate them to resolve the indexing */
      return
          typename mixin::template track_index<1> { mixin::access }[indices...];
    else
      // Or just the C++23 [i1, i2,...] case
      return mixin::access[indices...];
  }
rbegin()
template<typename AccessorMixIn > reverse_iterator trisycl::facade::accessor< AccessorMixIn >::rbegin () inline
Definition at line 163 of file accessor.hpp.
{ return std::reverse_iterator(end()); }
References trisycl::facade::accessor< AccessorMixIn >::end().
rend()
template<typename AccessorMixIn > reverse_iterator trisycl::facade::accessor< AccessorMixIn >::rend () inline
Definition at line 165 of file accessor.hpp.
{
    return std::reverse_iterator(begin());
    ;
  }
References trisycl::facade::accessor< AccessorMixIn >::begin().
trisycl::mixin::accessor
class trisycl::mixin::accessor
template<typename T, int Dimensions>
class trisycl::mixin::accessor< T, Dimensions >
SYCL accessor mixin providing multi-dimensional access features.
Definition at line 26 of file accessor.hpp.
Public Types
using element_type = T
Extension to SYCL: provide pieces of STL container interface from mdspan.
using value_type = std::remove_cv_t< element_type >
Even if the buffer is read-only use a non-const type so at least the current implementation can copy the data too.
using non_const_pointer = value_type *
using pointer = typename mdspan::accessor_type::data_handle_type
Pointer type to element.
using const_pointer = const element_type *
Pointer type to const element.
using reference = typename mdspan::reference
Reference type to the elements.
Public Member Functions
accessor ()=default
Used by the local accessor hack on top of host accessor.
accessor (pointer data, const range< rank()> &r)
Create an accessor of dimensions r on top of data storage.
accessor (const mdspan &m)
Create an accessor from another mdspan.
void update (pointer data, const range< rank()> &r)
Update the accessor to target somewhere else.
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
std::size_t get_count () const
Returns the total number of elements in the buffer.
std::size_t get_size () const
Returns the size of the buffer storage in bytes.
auto data ()
Get the underlying storage.
decltype(auto) tuple_indexed_access (const auto &tuple_like_indices)
Access to an element with indices implementing a tuple interface.
Static Public Member Functions
static auto constexpr rank ()
Get the number of dimensions of the buffer.
static decltype(auto) tuple_indexed_mdspan_access (auto &&some_mdspan, const auto &tuple_like_indices)
Access to an mdspan element with indices implementing a tuple interface.
Protected Types
using mdspan = std::mdspan< element_type, std::dextents< std::size_t, Dimensions > >
The memory lay-out of a buffer is a dynamic multidimensional array.
Protected Member Functions
template<typename BasicType , typename FinalType >
const std::array< typename mdspan::size_type, rank()> & extents_cast (const detail::small_array< BasicType, FinalType, rank()> &sa)
Cast a SYCL range/id-like into a mdspan index array, which is an array of std::size_t into an array of std::ptrdiff_t.
void set_access (const mdspan &a)
Set later the mdspan associated to this accessor.
Protected Attributes
mdspan access
This is the multi-dimensional interface to the data that may point to either allocation in the case of storage managed by SYCL itself or to some other memory location in the case of host memory or storage<> abstraction use.
Member Typedef Documentation
const_pointer
template<typename T , int Dimensions> using trisycl::mixin::accessor< T, Dimensions >::const_pointer = const element_type*
Pointer type to const element.
Definition at line 75 of file accessor.hpp.
element_type
template<typename T , int Dimensions> using trisycl::mixin::accessor< T, Dimensions >::element_type = T
Extension to SYCL: provide pieces of STL container interface from mdspan.
Definition at line 31 of file accessor.hpp.
mdspan
template<typename T , int Dimensions> using trisycl::mixin::accessor< T, Dimensions >::mdspan = std::mdspan<element_type, std::dextents<std::size_t, Dimensions> > protected
The memory lay-out of a buffer is a dynamic multidimensional array.
Definition at line 47 of file accessor.hpp.
non_const_pointer
template<typename T , int Dimensions> using trisycl::mixin::accessor< T, Dimensions >::non_const_pointer = value_type*
Definition at line 37 of file accessor.hpp.
pointer
template<typename T , int Dimensions> using trisycl::mixin::accessor< T, Dimensions >::pointer = typename mdspan::accessor_type::data_handle_type
Pointer type to element.
Definition at line 72 of file accessor.hpp.
reference
template<typename T , int Dimensions> using trisycl::mixin::accessor< T, Dimensions >::reference = typename mdspan::reference
Reference type to the elements.
Definition at line 78 of file accessor.hpp.
value_type
template<typename T , int Dimensions> using trisycl::mixin::accessor< T, Dimensions >::value_type = std::remove_cv_t<element_type>
Even if the buffer is read-only use a non-const type so at least the current implementation can copy the data too.
Definition at line 34 of file accessor.hpp.
Constructor & Destructor Documentation
accessor() [1/3]
template<typename T , int Dimensions> trisycl::mixin::accessor< T, Dimensions >::accessor () default
Used by the local accessor hack on top of host accessor.
accessor() [2/3]
template<typename T , int Dimensions> trisycl::mixin::accessor< T, Dimensions >::accessor (pointer data, const range< rank()> & r) inline
Create an accessor of dimensions r on top of data storage.
Definition at line 84 of file accessor.hpp.
      : access { data, extents_cast(r) } {}
accessor() [3/3]
template<typename T , int Dimensions> trisycl::mixin::accessor< T, Dimensions >::accessor (const mdspan & m) inline
Create an accessor from another mdspan.
Definition at line 88 of file accessor.hpp.
      : access { m } {}
Member Function Documentation
data()
template<typename T , int Dimensions> auto trisycl::mixin::accessor< T, Dimensions >::data () inline
Get the underlying storage.
Definition at line 133 of file accessor.hpp.
{ return access.data_handle(); }
References trisycl::mixin::accessor< T, Dimensions >::access.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::accessor(), trisycl::detail::accessor< T, Dimensions, Mode, Target >::copy_in_cl_buffer(), and trisycl::mixin::accessor< T, Dimensions >::update().
extents_cast()
template<typename T , int Dimensions> template<typename BasicType , typename FinalType > const std::array< typename mdspan::size_type, rank()> & trisycl::mixin::accessor< T, Dimensions >::extents_cast (const detail::small_array< BasicType, FinalType, rank()> & sa) inline protected
Cast a SYCL range/id-like into a mdspan index array, which is an array of std::size_t into an array of std::ptrdiff_t.
Definition at line 62 of file accessor.hpp.
{
    return reinterpret_cast<
        const std::array<typename mdspan::size_type, rank()>&>(sa);
  }
References trisycl::mixin::accessor< T, Dimensions >::rank().
Referenced by trisycl::mixin::accessor< T, Dimensions >::update().
get_count()
template<typename T , int Dimensions> std::size_t trisycl::mixin::accessor< T, Dimensions >::get_count () const inline
Returns the total number of elements in the buffer.
Equal to get_range()[0] * ... * get_range()[Dimensions-1].
Todo:
Move these kinds of functions into a mixin between buffers and accessors?
Todo:
Cache it since it is const?
Definition at line 118 of file accessor.hpp.
{
    return access.mapping().required_span_size();
  }
References trisycl::mixin::accessor< T, Dimensions >::access.
Referenced by trisycl::mixin::accessor< T, Dimensions >::get_size().
get_range()
template<typename T , int Dimensions> auto trisycl::mixin::accessor< T, Dimensions >::get_range () const inline
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
Todo:
Cache it since it is const?
Definition at line 102 of file accessor.hpp.
{
    range<Dimensions> r;
    for (std::size_t i = 0; i < Dimensions; ++i)
      r[i] = access.extent(i);
    return r;
  }
References trisycl::mixin::accessor< T, Dimensions >::access, and i.
get_size()
template<typename T , int Dimensions> std::size_t trisycl::mixin::accessor< T, Dimensions >::get_size () const inline
Returns the size of the buffer storage in bytes.
Todo:
rename to something else. In http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0122r0.pdf it is named bytes() for example
Todo:
Cache it since it is const?
Definition at line 130 of file accessor.hpp.
{ return get_count() * sizeof(value_type); }
References trisycl::mixin::accessor< T, Dimensions >::get_count().
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::accessor(), and trisycl::detail::accessor< T, Dimensions, Mode, Target >::copy_in_cl_buffer().
rank()
template<typename T , int Dimensions> static auto constexpr trisycl::mixin::accessor< T, Dimensions >::rank () inline static constexpr
Get the number of dimensions of the buffer.
Name inspired from ISO C++ P0009 mdspan papers
Definition at line 43 of file accessor.hpp.
{ return Dimensions; }
Referenced by trisycl::mixin::accessor< T, Dimensions >::extents_cast(), and trisycl::mixin::accessor< T, Dimensions >::track_index< N >::operator[]().
set_access()
template<typename T , int Dimensions> void trisycl::mixin::accessor< T, Dimensions >::set_access (const mdspan & a) inline protected
Set later the mdspan associated to this accessor.
Definition at line 68 of file accessor.hpp.
{ access = a; }
References a, and trisycl::mixin::accessor< T, Dimensions >::access.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::accessor().
tuple_indexed_access()
template<typename T , int Dimensions> decltype(auto) trisycl::mixin::accessor< T, Dimensions >::tuple_indexed_access (const auto & tuple_like_indices) inline
Access to an element with indices implementing a tuple interface.
Parameters
[in] tuple_like_indices are the indices to use
Returns
a reference to the accessor element
Definition at line 160 of file accessor.hpp.
{
    return tuple_indexed_mdspan_access(access, tuple_like_indices);
  }
References trisycl::mixin::accessor< T, Dimensions >::access, and trisycl::mixin::accessor< T, Dimensions >::tuple_indexed_mdspan_access().
tuple_indexed_mdspan_access()
template<typename T , int Dimensions> static decltype(auto) trisycl::mixin::accessor< T, Dimensions >::tuple_indexed_mdspan_access (auto && some_mdspan, const auto & tuple_like_indices) inline static
Access to an mdspan element with indices implementing a tuple interface.
Parameters
[in,out] some_mdspan is the mdspan to access
[in] tuple_like_indices are the indices to use
Returns
a reference to the element
Definition at line 145 of file accessor.hpp.
{
    // Otherwise use the C++23 mdspan[i1, i2,...] indexing syntax
    return std::invoke(
        [&](auto... i) -> decltype(auto) { return some_mdspan[i...]; },
        tuple_like_indices);
  }
References i.
Referenced by trisycl::mixin::accessor< T, Dimensions >::track_index< N >::operator[](), and trisycl::mixin::accessor< T, Dimensions >::tuple_indexed_access().
update()
template<typename T , int Dimensions> void trisycl::mixin::accessor< T, Dimensions >::update (pointer data, const range< rank()> & r) inline
Update the accessor to target somewhere else.
Definition at line 92 of file accessor.hpp.
{
    access = mdspan { data, extents_cast(r) };
  }
References trisycl::mixin::accessor< T, Dimensions >::access, trisycl::mixin::accessor< T, Dimensions >::data(), and trisycl::mixin::accessor< T, Dimensions >::extents_cast().
Member Data Documentation
access
template<typename T , int Dimensions> mdspan trisycl::mixin::accessor< T, Dimensions >::access protected
This is the multi-dimensional interface to the data that may point to either allocation in the case of storage managed by SYCL itself or to some other memory location in the case of host memory or storage<> abstraction use.
Definition at line 55 of file accessor.hpp.
Referenced by trisycl::mixin::accessor< T, Dimensions >::data(), trisycl::mixin::accessor< T, Dimensions >::get_count(), trisycl::mixin::accessor< T, Dimensions >::get_range(), trisycl::mixin::accessor< T, Dimensions >::set_access(), trisycl::mixin::accessor< T, Dimensions >::tuple_indexed_access(), and trisycl::mixin::accessor< T, Dimensions >::update().
trisycl::context
class trisycl::context
SYCL context.
The context class encapsulates an OpenCL context, which is implicitly created and the lifetime of the context instance defines the lifetime of the underlying OpenCL context instance.
On destruction clReleaseContext is called.
The default context is the SYCL host context containing only the SYCL host device.
Todo:
The implementation is quite minimal for now.
Definition at line 46 of file context.hpp.
Public Member Functions
context (async_handler asyncHandler)
Constructs a context object for SYCL host using an async_handler for handling asynchronous errors.
context (cl_context clContext, async_handler asyncHandler=nullptr)
Make a SYCL context from an OpenCL context.
context (const boost::compute::context &c, async_handler asyncHandler=nullptr)
Build a SYCL context from a Boost.Compute context.
context (const device_selector &deviceSelector, async_handler asyncHandler=nullptr)
Constructs a context object using a device_selector object.
context (const device &dev, async_handler asyncHandler=nullptr)
Constructs a context object using a device object.
context (const platform &plt, async_handler asyncHandler=nullptr)
Constructs a context object using a platform object.
context (const vector_class< device > &deviceList, async_handler asyncHandler=nullptr)
context ()
Default constructor that chooses the context according the heuristics of the default selector.
cl_context get () const
Return the underlying cl_context object, after retaining the cl_context.
boost::compute::context & get_boost_compute () const
Return the underlying boost::compute::context of the trisycl::context.
boost::compute::command_queue & get_boost_queue () const
Return the internal queue that is associated to the context and used by triSYCL to move data between some different contests for example.
bool is_host () const
Specifies whether the context is in SYCL Host Execution Mode.
platform get_platform () const
Returns the SYCL platform that the context is initialized for.
vector_class< device > get_devices () const
Returns the set of devices that are part of this context.
template<info::context param>
auto get_info () const
Queries OpenCL information for the under-lying cl context.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< context, detail::context >
shared_ptr_implementation (std::shared_ptr< detail::context > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::context *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = detail::shared_ptr_implementation< context, detail::context >
Private Member Functions
context (vector_class< device > devList, async_handler asyncHandler, const device_selector &deviceSelector)
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< context, detail::context >
std::shared_ptr< detail::context > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
implementation_t
using trisycl::context::implementation_t = detail::shared_ptr_implementation<context, detail::context> private
Definition at line 53 of file context.hpp.
Constructor & Destructor Documentation
context() [1/9]
trisycl::context::context (vector_class< device > devList, async_handler asyncHandler, const device_selector & deviceSelector) inline private
Definition at line 56 of file context.hpp.
{
    if (devList.empty())
      devList = {deviceSelector.select_device()};
    if (devList[0].is_host())
      implementation = detail::host_context::instance();
#ifdef TRISYCL_OPENCL
    else
      implementation = detail::opencl_context::instance(
        boost::compute::context { devList[0].get_boost_compute () }
      );
#endif
  }
References trisycl::detail::shared_ptr_implementation< context, detail::context >::implementation, trisycl::detail::singleton< host_context >::instance(), trisycl::detail::opencl_context::instance(), is_host(), and trisycl::device_selector::select_device().
context() [2/9]
trisycl::context::context (async_handler asyncHandler) inline explicit
Constructs a context object for SYCL host using an async_handler for handling asynchronous errors.
Note that the default case asyncHandler = nullptr is handled by the default constructor.
Definition at line 81 of file context.hpp.
   : context { device{}, asyncHandler } {}
context() [3/9]
trisycl::context::context (cl_context clContext, async_handler asyncHandler = nullptr) inline
Make a SYCL context from an OpenCL context.
The constructor executes a retain on the cl_context.
Return synchronous errors via the SYCL exception class and asynchronous errors are handled via the async_handler, if provided.
Definition at line 93 of file context.hpp.
    : context { boost::compute::context { clContext }, asyncHandler } {}
context() [4/9]
trisycl::context::context (const boost::compute::context & c, async_handler asyncHandler = nullptr) inline
Build a SYCL context from a Boost.Compute context.
Definition at line 98 of file context.hpp.
    : implementation_t { detail::opencl_context::instance(c) } {}
context() [5/9]
trisycl::context::context (const device_selector & deviceSelector, async_handler asyncHandler = nullptr) inline
Constructs a context object using a device_selector object.
The context is constructed with a single device retrieved from the device_selector object provided.
Return synchronous errors via the SYCL exception class and asynchronous errors are handled via the async_handler, if provided.
Definition at line 111 of file context.hpp.
    : context (vector_class<device>{}, asyncHandler, deviceSelector) {}
context() [6/9]
trisycl::context::context (const device & dev, async_handler asyncHandler = nullptr) inline
Constructs a context object using a device object.
Return synchronous errors via the SYCL exception class and asynchronous errors are handled via the async_handler, if provided.
Definition at line 119 of file context.hpp.
    : context { vector_class<device>{dev}, asyncHandler } {}
context() [7/9]
trisycl::context::context (const platform & plt, async_handler asyncHandler = nullptr) inline
Constructs a context object using a platform object.
Return synchronous errors via the SYCL exception class and asynchronous errors are handled via the async_handler, if provided.
Definition at line 127 of file context.hpp.
    : context { plt.get_devices(), asyncHandler } {}
context() [8/9]
trisycl::context::context (const vector_class< device > & deviceList, async_handler asyncHandler = nullptr)
context() [9/9]
trisycl::context::context () inline
Default constructor that chooses the context according the heuristics of the default selector.
Return synchronous errors via the SYCL exception class.
Get the default constructors back.
Definition at line 148 of file context.hpp.
: context { async_handler {} } {}
Member Function Documentation
get()
cl_context trisycl::context::get () const inline
Return the underlying cl_context object, after retaining the cl_context.
Retains a reference to the returned cl_context object.
Caller should release it when finished.
Definition at line 158 of file context.hpp.
{
    return implementation->get();
  }
get_boost_compute()
boost::compute::context & trisycl::context::get_boost_compute () const inline
Return the underlying boost::compute::context of the trisycl::context.
Definition at line 165 of file context.hpp.
{
    return implementation->get_boost_compute();
  }
Referenced by trisycl::detail::buffer_base::create_in_cache().
get_boost_queue()
boost::compute::command_queue & trisycl::context::get_boost_queue () const inline
Return the internal queue that is associated to the context and used by triSYCL to move data between some different contests for example.
Definition at line 173 of file context.hpp.
{
    return implementation->get_boost_queue();
  }
Referenced by trisycl::detail::buffer_base::update_buffer_state().
get_devices()
vector_class< device > trisycl::context::get_devices () const inline
Returns the set of devices that are part of this context.
Todo:
To be implemented
Definition at line 198 of file context.hpp.
{
    return implementation->get_devices();
  }
get_info()
template<info::context param> auto trisycl::context::get_info () const inline
Queries OpenCL information for the under-lying cl context.
Todo:
To be implemented
get_platform()
platform trisycl::context::get_platform () const inline
Returns the SYCL platform that the context is initialized for.
Todo:
To be implemented
Definition at line 189 of file context.hpp.
{
    return implementation->get_platform();
  };
is_host()
bool trisycl::context::is_host () const inline
Specifies whether the context is in SYCL Host Execution Mode.
Definition at line 180 of file context.hpp.
                       {
    return implementation->is_host();
  }
Referenced by context(), and trisycl::detail::buffer_base::update_buffer_state().
trisycl::detail::context
class trisycl::detail::context
Definition at line 22 of file context.hpp.
Public Member Functions
virtual cl_context get () const =0
Return the underlying cl_context of the trisycl::context.
virtual boost::compute::context & get_boost_compute ()=0
Return the underlying boost::compute::context of the trisycl::context.
virtual boost::compute::command_queue & get_boost_queue ()=0
Return the underlying boost::compute::command_queue associated with the context.
virtual bool is_host () const =0
Returns true is the context is a SYCL host context.
virtual trisycl::platform get_platform () const =0
Returns the SYCL platform that the context is initialized for.
virtual vector_class< trisycl::device > get_devices () const =0
Returns the set of devices that are part of this context.
virtual trisycl::cl_uint get_reference_count () const =0
Returns the reference count of underlying CL context, or 0 on host.
virtual ~context ()
Virtual to call the real destructor.
Constructor & Destructor Documentation
~context()
virtual trisycl::detail::context::~context () inline virtual
Virtual to call the real destructor.
Definition at line 59 of file context.hpp.
{}
Member Function Documentation
get()
virtual cl_context trisycl::detail::context::get () const pure virtual
Return the underlying cl_context of the trisycl::context.
Implemented in trisycl::detail::host_context, and trisycl::detail::opencl_context.
get_boost_compute()
virtual boost::compute::context & trisycl::detail::context::get_boost_compute () pure virtual
Return the underlying boost::compute::context of the trisycl::context.
Implemented in trisycl::detail::host_context, and trisycl::detail::opencl_context.
get_boost_queue()
virtual boost::compute::command_queue & trisycl::detail::context::get_boost_queue () pure virtual
Return the underlying boost::compute::command_queue associated with the context.
Implemented in trisycl::detail::host_context, and trisycl::detail::opencl_context.
get_devices()
virtual vector_class< trisycl::device > trisycl::detail::context::get_devices () const pure virtual
Returns the set of devices that are part of this context.
Todo:
virtual cannot be templated template <info::context Param> typename info::param_traits<info::context, Param>::type get_info() const = 0;
Implemented in trisycl::detail::host_context, and trisycl::detail::opencl_context.
get_platform()
virtual trisycl::platform trisycl::detail::context::get_platform () const pure virtual
Returns the SYCL platform that the context is initialized for.
Implemented in trisycl::detail::host_context, and trisycl::detail::opencl_context.
get_reference_count()
virtual trisycl::cl_uint trisycl::detail::context::get_reference_count () const pure virtual
Returns the reference count of underlying CL context, or 0 on host.
Implemented in trisycl::detail::host_context, and trisycl::detail::opencl_context.
is_host()
virtual bool trisycl::detail::context::is_host () const pure virtual
Returns true is the context is a SYCL host context.
Implemented in trisycl::detail::host_context, and trisycl::detail::opencl_context.
trisycl::detail::host_context
class trisycl::detail::host_context
SYCL host context.
Todo:
The implementation is quite minimal for now. :-)
Definition at line 31 of file host_context.hpp.
Public Member Functions
cl_context get () const override
Return the underlying cl_context of the trisycl::context.
boost::compute::context & get_boost_compute () override
Return the SYCL platform that the context is initialized for.
boost::compute::command_queue & get_boost_queue () override
Return the internal OpenCL queue that is associated to the host context.
bool is_host () const override
Return true since the context is a SYCL host context.
trisycl::platform get_platform () const override
Return the platform of the context.
vector_class< trisycl::device > get_devices () const override
Returns the set of devices that are part of this context.
trisycl::cl_uint get_reference_count () const override
Return 0 since the context is a SYCL host context.
Public Member Functions inherited from trisycl::detail::context
virtual cl_context get () const =0
Return the underlying cl_context of the trisycl::context.
virtual boost::compute::context & get_boost_compute ()=0
Return the underlying boost::compute::context of the trisycl::context.
virtual boost::compute::command_queue & get_boost_queue ()=0
Return the underlying boost::compute::command_queue associated with the context.
virtual bool is_host () const =0
Returns true is the context is a SYCL host context.
virtual trisycl::platform get_platform () const =0
Returns the SYCL platform that the context is initialized for.
virtual vector_class< trisycl::device > get_devices () const =0
Returns the set of devices that are part of this context.
virtual trisycl::cl_uint get_reference_count () const =0
Returns the reference count of underlying CL context, or 0 on host.
virtual ~context ()
Virtual to call the real destructor.
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::singleton< host_context >
static std::shared_ptr< host_context > instance ()
Get a singleton instance of T.
Member Function Documentation
get()
cl_context trisycl::detail::host_context::get () const inline override virtual
Return the underlying cl_context of the trisycl::context.
This throws an error since there is no OpenCL context associated to the host device.
Implements trisycl::detail::context.
Definition at line 42 of file host_context.hpp.
{
    throw non_cl_error("The host context has no OpenCL context");
  }
get_boost_compute()
boost::compute::context & trisycl::detail::host_context::get_boost_compute () inline override virtual
Return the SYCL platform that the context is initialized for.
This throws an error since there is no boost::compute context associated to the host device.
Implements trisycl::detail::context.
Definition at line 52 of file host_context.hpp.
{
    throw non_cl_error("The host context has no OpenCL context");
  }
get_boost_queue()
boost::compute::command_queue & trisycl::detail::host_context::get_boost_queue () inline override virtual
Return the internal OpenCL queue that is associated to the host context.
This throws an error since there is no boost::compute::command_queue associated to the host context.
Implements trisycl::detail::context.
Definition at line 63 of file host_context.hpp.
{
    throw non_cl_error("The host context cannot have an OpenCL queue");
  }
Referenced by trisycl::detail::buffer_base::sync_with_host().
get_devices()
vector_class< trisycl::device > trisycl::detail::host_context::get_devices () const inline override virtual
Returns the set of devices that are part of this context.
It should only return the host device itself.
Todo:
To be implemented
Implements trisycl::detail::context.
Definition at line 106 of file host_context.hpp.
{
    // Return just the host device
    return { {} };
  }
get_platform()
trisycl::platform trisycl::detail::host_context::get_platform () const inline override virtual
Return the platform of the context.
Return synchronous errors via the SYCL exception class.
Implements trisycl::detail::context.
Definition at line 79 of file host_context.hpp.
{
    // Return the host platform
    return {};
  }
get_reference_count()
trisycl::cl_uint trisycl::detail::host_context::get_reference_count () const inline override virtual
Return 0 since the context is a SYCL host context.
Implements trisycl::detail::context.
Definition at line 112 of file host_context.hpp.
{
    return 0;
  }
is_host()
bool trisycl::detail::host_context::is_host () const inline override virtual
Return true since the context is a SYCL host context.
Implements trisycl::detail::context.
Definition at line 70 of file host_context.hpp.
{
    return true;
  }
trisycl::device
class trisycl::device
SYCL device.
Definition at line 44 of file device.hpp.
Public Member Functions
device ()
The default constructor uses the SYCL host device.
device (cl_device_id device_id)
Construct a device class instance using cl_device_id of the OpenCL device.
device (const boost::compute::device &d)
Construct a device class instance using a boost::compute::device.
device (const device_selector &ds)
Construct a device class instance using the device selector provided.
cl_device_id get () const
Return the cl_device_id of the underlying OpenCL platform.
boost::compute::device get_boost_compute () const
Return the underlying Boost.Compute device if it is an OpenCL device.
bool is_host () const
Return true if the device is the SYCL host device.
bool is_cpu () const
Return true if the device is an OpenCL CPU device.
bool is_gpu () const
Return true if the device is an OpenCL GPU device.
bool is_accelerator () const
Return true if the device is an OpenCL accelerator device.
info::device_type type () const
Return the device_type of a device.
platform get_platform () const
Return the platform of device.
template<info::device param>
info::param_traits< info::device, param >::return_type get_info () const
Query the device for OpenCL info::device info.
bool has_extension (const string_class &extension) const
Test if a specific extension is supported on the device.
template<info::partition_property prop>
vector_class< device > create_sub_devices (size_t nbSubDev) const
template<info::partition_property prop>
vector_class< device > create_sub_devices (const vector_class< size_t > &counts) const
template<info::partition_property prop>
vector_class< device > create_sub_devices (info::partition_affinity_domain affinityDomain) const
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< device, detail::device >
shared_ptr_implementation (std::shared_ptr< detail::device > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::device *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Static Public Member Functions
static vector_class< device > get_devices (info::device_type device_type=info::device_type::all) TRISYCL_WEAK_ATTRIB_SUFFIX
Return a list of all available devices.
Private Types
using implementation_t = facade::device< device, detail::device >
Additional Inherited Members
Public Types inherited from trisycl::facade::device< device, detail::device >
using implementation_t = detail::shared_ptr_implementation< device, detail::device >
The type encapsulating the implementation.
using detail_t = detail::device
The real detail type doing the work behind the scene.
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< device, detail::device >
std::shared_ptr< detail::device > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
implementation_t
using trisycl::device::implementation_t = facade::device<device, detail::device> private
Definition at line 50 of file device.hpp.
Constructor & Destructor Documentation
device() [1/4]
trisycl::device::device () inline
The default constructor uses the SYCL host device.
Definition at line 58 of file device.hpp.
: implementation_t { detail::host_device::instance() } {}
device() [2/4]
trisycl::device::device (cl_device_id device_id) inline
Construct a device class instance using cl_device_id of the OpenCL device.
Return synchronous errors via the SYCL exception class.
Retain a reference to the OpenCL device and if this device was an OpenCL subdevice the device should be released by the caller when it is no longer needed.
Definition at line 71 of file device.hpp.
    : device { boost::compute::device { device_id } } {}
device() [3/4]
trisycl::device::device (const boost::compute::device & d) inline
Construct a device class instance using a boost::compute::device.
This is a triSYCL extension for boost::compute interoperation.
Return synchronous errors via the SYCL exception class.
Definition at line 81 of file device.hpp.
    : implementation_t { detail::opencl_device::instance(d) } {}
device() [4/4]
trisycl::device::device (const device_selector & ds) inline explicit
Construct a device class instance using the device selector provided.
Return errors via C++ exception class.
Todo:
Make it non-explicit in the specification?
Definition at line 93 of file device.hpp.
{
    auto devices = device::get_devices();
    if (devices.empty())
      // \todo Put a SYCL exception
      throw std::domain_error("No device at all! Internal error...");
    /* Find the device with the best score according to the given
       device_selector */
    auto max = std::max_element(devices.cbegin(), devices.cend(),
                                [&] (const device &d1, const device &d2) {
                                  return ds(d1) < ds(d2);
                                });
    if (ds(*max) < 0)
      // \todo Put a SYCL exception
      throw std::domain_error("No device selected because no positive "
                              "device_selector score found");
    // Create the current device as a shared copy of the selected one
    implementation = max->implementation;
  }
References get_devices(), trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation, and trisycl::max().
Member Function Documentation
create_sub_devices() [1/3]
template<info::partition_property prop> vector_class< device > trisycl::device::create_sub_devices (const vector_class< size_t > & counts) const inline
Definition at line 240 of file device.hpp.
  {
    throw trisycl::feature_not_supported("unsupported feature\n");
  }
create_sub_devices() [2/3]
template<info::partition_property prop> vector_class< device > trisycl::device::create_sub_devices (info::partition_affinity_domain affinityDomain) const inline
Definition at line 247 of file device.hpp.
  {
    throw trisycl::feature_not_supported("unsupported feature\n");
  }
create_sub_devices() [3/3]
template<info::partition_property prop> vector_class< device > trisycl::device::create_sub_devices (size_t nbSubDev) const inline
Definition at line 233 of file device.hpp.
  {
    throw trisycl::feature_not_supported("unsupported feature\n");
  }
get()
cl_device_id trisycl::device::get () const inline
Return the cl_device_id of the underlying OpenCL platform.
Return synchronous errors via the SYCL exception class.
Retain a reference to the returned cl_device_id object. Caller should release it when finished.
In the case where this is the SYCL host device it will throw an exception.
Definition at line 126 of file device.hpp.
{
    return implementation->get();
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
get_boost_compute()
boost::compute::device trisycl::device::get_boost_compute () const inline
Return the underlying Boost.Compute device if it is an OpenCL device.
This is a triSYCL extension
Definition at line 136 of file device.hpp.
{
    return implementation->get_boost_compute();
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
Referenced by trisycl::detail::opencl_queue::instance().
get_devices()
static vector_class< device > trisycl::device::get_devices (info::device_type device_type = info::device_type::all) static
Return a list of all available devices.
Return synchronous errors via SYCL exception classes.
Referenced by device().
get_info()
template<info::device param> info::param_traits< info::device, param >::return_type trisycl::device::get_info () const inline
Query the device for OpenCL info::device info.
Return synchronous errors via the SYCL exception class.
Todo:
Query the device for OpenCL info::device info
Return synchronous errors via the SYCL exception class.
Todo:
Definition at line 220 of file device.hpp.
                   {
    return std::any_cast<
      typename info::param_traits<info::device, param>::return_type
      >(implementation->get_info(param));
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
get_platform()
platform trisycl::device::get_platform () const inline
Return the platform of device.
Return synchronous errors via the SYCL exception class.
Definition at line 190 of file device.hpp.
{
    return implementation->get_platform();
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
has_extension()
bool trisycl::device::has_extension (const string_class & extension) const inline
Test if a specific extension is supported on the device.
Definition at line 227 of file device.hpp.
{
    return implementation->has_extension(extension);
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
is_accelerator()
bool trisycl::device::is_accelerator () const inline
Return true if the device is an OpenCL accelerator device.
Definition at line 161 of file device.hpp.
{
    return implementation->is_accelerator();
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
Referenced by type().
is_cpu()
bool trisycl::device::is_cpu () const inline
Return true if the device is an OpenCL CPU device.
Definition at line 149 of file device.hpp.
                      {
    return implementation->is_cpu();
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
Referenced by type().
is_gpu()
bool trisycl::device::is_gpu () const inline
Return true if the device is an OpenCL GPU device.
Definition at line 155 of file device.hpp.
                      {
    return implementation->is_gpu();
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
Referenced by type().
is_host()
bool trisycl::device::is_host () const inline
Return true if the device is the SYCL host device.
Definition at line 143 of file device.hpp.
                       {
    return implementation->is_host();
  }
References trisycl::detail::shared_ptr_implementation< device, detail::device >::implementation.
Referenced by trisycl::device_type_selector::operator()(), and type().
type()
info::device_type trisycl::device::type () const inline
Return the device_type of a device.
Todo:
Present in Boost.Compute, to be added to the specification
Definition at line 171 of file device.hpp.
{
    if (is_host())
      return info::device_type::host;
    else if (is_cpu())
      return info::device_type::cpu;
    else if (is_gpu())
      return info::device_type::gpu;
    else if (is_accelerator())
      return info::device_type::accelerator;
    else
      // \todo Put a SYCL exception
      throw std::domain_error("Unknown trisycl::info::device_type");
  }
References trisycl::info::accelerator, trisycl::info::cpu, trisycl::info::gpu, trisycl::info::host, is_accelerator(), is_cpu(), is_gpu(), and is_host().
Referenced by trisycl::device_type_selector::operator()().
trisycl::detail::device
class trisycl::detail::device
An abstract class representing various models of SYCL devices.
Definition at line 23 of file device.hpp.
Public Member Functions
virtual cl_device_id get () const =0
Return the cl_device_id of the underlying OpenCL platform.
virtual boost::compute::device & get_boost_compute ()=0
Return the underlying Boost.Compute device, if any.
virtual bool is_host () const =0
Return true if the device is a SYCL host device.
virtual bool is_cpu () const =0
Return true if the device is an OpenCL CPU device.
virtual bool is_gpu () const =0
Return true if the device is an OpenCL GPU device.
virtual bool is_accelerator () const =0
Return true if the device is an OpenCL accelerator device.
virtual trisycl::platform get_platform () const =0
Return the platform of device.
virtual std::any get_info (info::device param) const =0
Query the device for OpenCL info::device info.
virtual bool has_extension (const string_class &extension) const =0
Specify whether a specific extension is supported on the device.
virtual ~device ()
Constructor & Destructor Documentation
~device()
virtual trisycl::detail::device::~device () inline virtual
Definition at line 65 of file device.hpp.
{}
Member Function Documentation
get()
virtual cl_device_id trisycl::detail::device::get () const pure virtual
Return the cl_device_id of the underlying OpenCL platform.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
get_boost_compute()
virtual boost::compute::device & trisycl::detail::device::get_boost_compute () pure virtual
Return the underlying Boost.Compute device, if any.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
get_info()
virtual std::any trisycl::detail::device::get_info (info::device param) const pure virtual
Query the device for OpenCL info::device info.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
get_platform()
virtual trisycl::platform trisycl::detail::device::get_platform () const pure virtual
Return the platform of device.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
has_extension()
virtual bool trisycl::detail::device::has_extension (const string_class & extension) const pure virtual
Specify whether a specific extension is supported on the device.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
is_accelerator()
virtual bool trisycl::detail::device::is_accelerator () const pure virtual
Return true if the device is an OpenCL accelerator device.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
is_cpu()
virtual bool trisycl::detail::device::is_cpu () const pure virtual
Return true if the device is an OpenCL CPU device.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
is_gpu()
virtual bool trisycl::detail::device::is_gpu () const pure virtual
Return true if the device is an OpenCL GPU device.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
is_host()
virtual bool trisycl::detail::device::is_host () const pure virtual
Return true if the device is a SYCL host device.
Implemented in trisycl::detail::host_device, and trisycl::detail::opencl_device.
trisycl::facade::device
class trisycl::facade::device
template<typename UserFacing, typename ImplementationDetail>
class trisycl::facade::device< UserFacing, ImplementationDetail >
SYCL device.
Definition at line 21 of file device.hpp.
Public Types
using implementation_t = detail::shared_ptr_implementation< UserFacing, ImplementationDetail >
The type encapsulating the implementation.
using detail_t = ImplementationDetail
The real detail type doing the work behind the scene.
Additional Inherited Members
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< UserFacing, ImplementationDetail >
shared_ptr_implementation (std::shared_ptr< ImplementationDetail > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (ImplementationDetail *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< UserFacing, ImplementationDetail >
std::shared_ptr< ImplementationDetail > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
detail_t
template<typename UserFacing , typename ImplementationDetail > using trisycl::facade::device< UserFacing, ImplementationDetail >::detail_t = ImplementationDetail
The real detail type doing the work behind the scene.
Definition at line 33 of file device.hpp.
implementation_t
template<typename UserFacing , typename ImplementationDetail > using trisycl::facade::device< UserFacing, ImplementationDetail >::implementation_t = detail::shared_ptr_implementation<UserFacing, ImplementationDetail>
The type encapsulating the implementation.
Definition at line 29 of file device.hpp.
trisycl::device_selector
class trisycl::device_selector
The SYCL heuristics to select a device.
The device with the highest score is selected
Definition at line 22 of file device_selector.hpp.
Public Member Functions
device select_device () const
Returns a selected device using the functor operator defined in sub-classes operator()(const device &dev)
virtual int operator() (const device &dev) const =0
This pure virtual operator allows the customization of device selection.
virtual ~device_selector ()
Virtual destructor so the final destructor can be called if any.
Private Member Functions
device select_device (vector_class< platform > platforms) const
Constructor & Destructor Documentation
~device_selector()
virtual trisycl::device_selector::~device_selector () inline virtual
Virtual destructor so the final destructor can be called if any.
Definition at line 46 of file device_selector.hpp.
{}
Member Function Documentation
operator()()
virtual int trisycl::device_selector::operator() (const device & dev) const pure virtual
This pure virtual operator allows the customization of device selection.
It defines the behavior of the device_selector functor called by the SYCL runtime on device selection. It returns a "score" for each device in the system and the highest rated device will be used by the SYCL runtime.
Implemented in trisycl::device_type_selector.
Referenced by select_device().
trisycl::device_type_selector
class trisycl::device_type_selector
A device selector by device_type.
Todo:
To be added to the specification
Definition at line 54 of file device_selector_tail.hpp.
Public Member Functions
device_type_selector (info::device_type device_type)
int operator() (const device &dev) const override
This pure virtual operator allows the customization of device selection.
Public Member Functions inherited from trisycl::device_selector
device select_device () const
Returns a selected device using the functor operator defined in sub-classes operator()(const device &dev)
virtual int operator() (const device &dev) const =0
This pure virtual operator allows the customization of device selection.
virtual ~device_selector ()
Virtual destructor so the final destructor can be called if any.
Private Attributes
info::device_type device_type
The device_type to select.
device default_device
Cache the default device to select with the default device selector.
Constructor & Destructor Documentation
device_type_selector()
trisycl::device_type_selector::device_type_selector (info::device_type device_type) inline
Definition at line 70 of file device_selector_tail.hpp.
    : device_type { device_type } {
    // The default device selection heuristic
#ifdef TRISYCL_OPENCL
    if (device_type == info::device_type::automatic) {
      // Ask Boost.Compute for the default OpenCL device
      try {
        default_device = boost::compute::system::default_device();
      }
      catch (...) {
        /* If there is no OpenCL device, just keep the
           default-constructed device, which is the host device */
      }
    }
#endif
  }
References trisycl::info::automatic, default_device, and device_type.
Member Function Documentation
operator()()
int trisycl::device_type_selector::operator() (const device & dev) const inline override virtual
This pure virtual operator allows the customization of device selection.
It defines the behavior of the device_selector functor called by the SYCL runtime on device selection. It returns a "score" for each device in the system and the highest rated device will be used by the SYCL runtime.
Implements trisycl::device_selector.
Definition at line 89 of file device_selector_tail.hpp.
{
    if (device_type == info::device_type::all)
      // All devices fit all
      return 1;
    if (device_type == info::device_type::automatic)
      // Only select the default device
      return dev == default_device ? 1 : -1;
    if (device_type == info::device_type::opencl)
      // For now, any non host device is an OpenCL device
      return dev.is_host() ? -1 : 1;
    return dev.type() == device_type ? 1 : -1;
  }
References trisycl::info::all, trisycl::info::automatic, default_device, device_type, trisycl::device::is_host(), trisycl::info::opencl, and trisycl::device::type().
Member Data Documentation
default_device
device trisycl::device_type_selector::default_device private
Cache the default device to select with the default device selector.
This is the host device at construction time and remains as is if there is no openCL device
Definition at line 66 of file device_selector_tail.hpp.
Referenced by device_type_selector(), and operator()().
device_type
info::device_type trisycl::device_type_selector::device_type private
The device_type to select.
Definition at line 59 of file device_selector_tail.hpp.
Referenced by device_type_selector(), and operator()().
trisycl::device_typename_selector
class trisycl::device_typename_selector
template<info::device_type DeviceType>
class trisycl::device_typename_selector< DeviceType >
Select a device by template device_type parameter.
Todo:
To be added to the specification
Definition at line 113 of file device_selector_tail.hpp.
Public Member Functions
device_typename_selector ()
Public Member Functions inherited from trisycl::device_type_selector
device_type_selector (info::device_type device_type)
int operator() (const device &dev) const override
This pure virtual operator allows the customization of device selection.
Public Member Functions inherited from trisycl::device_selector
device select_device () const
Returns a selected device using the functor operator defined in sub-classes operator()(const device &dev)
virtual int operator() (const device &dev) const =0
This pure virtual operator allows the customization of device selection.
virtual ~device_selector ()
Virtual destructor so the final destructor can be called if any.
Constructor & Destructor Documentation
device_typename_selector()
template<info::device_type DeviceType> trisycl::device_typename_selector< DeviceType >::device_typename_selector () inline
Definition at line 117 of file device_selector_tail.hpp.
: device_type_selector { DeviceType } {}
trisycl::handler
class trisycl::handler
Command group handler class.
A command group handler object can only be constructed by the SYCL runtime.
All of the accessors defined in the command group scope take as a parameter an instance of the command group handler and all the kernel invocation functions are methods of this class.
Definition at line 46 of file handler.hpp.
Public Member Functions
handler (const std::shared_ptr< detail::queue > &q)
template<typename DataType , int Dimensions, access::mode Mode, access::target Target = access::target::global_buffer>
void set_arg (int arg_index, accessor< DataType, Dimensions, Mode, Target > &&acc_obj)
Set accessor kernel arg for an OpenCL kernel which is used through the SYCL/OpenCL interop interface.
template<typename T , typename = std::enable_if_t<is_wrapper<T>::value>>
void set_arg (int arg_index, T &&scalar_value)
Set kernel args for an OpenCL kernel which is used through the SYCL/OpenCL interoperability interface with a wrapper type.
template<typename T >
std::enable_if_t<!is_wrapper< T >::value > set_arg (int arg_index, T &&scalar_value)
Set kernel args for an OpenCL kernel which is used through the SYCL/OpenCL interoperability interface without a wrapper type.
template<typename... Ts>
void set_args (Ts &&... args)
Set all kernel args for an OpenCL kernel which is used through the SYCL/OpenCL interop interface.
template<typename KernelName = std::nullptr_t, typename ParallelForFunctor >
void single_task (ParallelForFunctor &&f)
Kernel invocation method of a kernel defined as a lambda or functor.
template<typename KernelName = std::nullptr_t, int Dims, typename ParallelForFunctor >
requires (!std::derived_from<ParallelForFunctor, kernel>)
void parallel_for (const range< Dims > &global_size, ParallelForFunctor f)
SYCL parallel_for launches a data parallel computation with parallelism specified at launch time by a range<>
template<typename KernelName = std::nullptr_t, int Dims, typename ParallelForFunctor >
void parallel_for (const std::size_t(&global_size)[Dims], ParallelForFunctor f)
SYCL parallel_for launches a data parallel computation with parallelism specified at launch time with a range defined with a { dim1, dim2, dim3... } syntax.
template<typename KernelName = std::nullptr_t, typename ParallelForFunctor >
requires (!std::derived_from<ParallelForFunctor, kernel>)
void parallel_for (std::size_t global_size, ParallelForFunctor f)
SYCL parallel_for launches a data parallel computation with parallelism specified at launch time with a range defined with a single dimension as an integer.
template<typename KernelName = std::nullptr_t, int Dims, typename ParallelForFunctor >
void parallel_for (range< Dims > global_size, id< Dims > offset, ParallelForFunctor f)
Kernel invocation method of a kernel defined as a lambda or functor, for the specified range and offset and given an id or item for indexing in the indexing space defined by range.
template<typename KernelName = std::nullptr_t, int Dimensions, typename ParallelForFunctor >
void parallel_for (nd_range< Dimensions > r, ParallelForFunctor f)
Kernel invocation method of a kernel defined as a lambda or functor, for the specified nd_range and given an nd_item for indexing in the indexing space defined by the nd_range.
template<typename KernelName = std::nullptr_t, int Dimensions = 1, typename ParallelForFunctor >
void parallel_for_work_group (nd_range< Dimensions > r, ParallelForFunctor f)
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
template<typename KernelName = std::nullptr_t, int Dimensions = 1, typename ParallelForFunctor >
void parallel_for_work_group (range< Dimensions > r1, range< Dimensions > r2, ParallelForFunctor f)
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
void single_task (kernel sycl_kernel)
Kernel invocation method of a kernel defined as pointer to a kernel object, described in detail in 3.5.3.
template<int Dimensions = 1, typename SYCLrange >
requires (std::derived_from<SYCLrange, range<Dimensions>> || std::integral<SYCLrange>)
void parallel_for (SYCLrange num_work_items, kernel sycl_kernel)
Kernel invocation method of a kernel defined as a kernel object, for the specified range and given an id or item for indexing in the indexing space defined by range, described in detail in 5.4.
template<int Dimensions = 1>
void parallel_for (nd_range< Dimensions >, kernel syclKernel)
Kernel invocation method of a kernel defined as pointer to a kernel object, for the specified nd_range and given an nd_item for indexing in the indexing space defined by the nd_range, described in detail in 3.5.3.
Public Attributes
std::shared_ptr< detail::task > task
Attach the task and accessors to it.
Private Member Functions
template<std::size_t... Is, typename... Ts>
void dispatch_set_arg (std::index_sequence< Is... >, Ts &&... args)
Helper to individually call set_arg() for each argument.
template<typename KernelName , typename Kernel >
void schedule_kernel (Kernel k)
Schedule the kernel.
template<typename KernelName , typename Kernel , int N>
void schedule_parallel_for_kernel (Kernel k, const range< N > &num_work_items)
Schedule a parallel for kernel.
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::debug< handler >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Constructor & Destructor Documentation
handler()
trisycl::handler::handler (const std::shared_ptr< detail::queue > & q) inline
Definition at line 64 of file handler.hpp.
{
    // Create a new task for this command_group
    task = std::make_shared<detail::task>(q);
  }
References task.
Member Function Documentation
dispatch_set_arg()
template<std::size_t... Is, typename... Ts> void trisycl::handler::dispatch_set_arg (std::index_sequence< Is... > , Ts &&... args) inline private
Helper to individually call set_arg() for each argument.
Definition at line 132 of file handler.hpp.
{
    // Use an intermediate tuple to ease individual argument access
    auto &&t = std::make_tuple(std::forward<Ts>(args)...);
    // Dispatch individual set_arg() for each argument
    auto just_to_evaluate = {
      0 /*< At least 1 element to deal with empty set_args() */,
      ( set_arg(Is, std::forward<Ts>(std::get<Is>(t))), 0)...
    };
    // Remove the warning about unused variable
    static_cast<void>(just_to_evaluate);
  }
References set_arg().
Referenced by set_args().
parallel_for() [1/7]
template<typename KernelName = std::nullptr_t, int Dims, typename ParallelForFunctor > requires (!std::derived_from<ParallelForFunctor, kernel>) void trisycl::handler::parallel_for (const range< Dims > & global_size, ParallelForFunctor f) inline
SYCL parallel_for launches a data parallel computation with parallelism specified at launch time by a range<>
Kernel invocation method of a kernel defined as a lambda or functor, for the specified range and given an id or item for indexing in the indexing space defined by range.
If it is a lambda function or the if the functor type is globally visible there is no need for the developer to provide a kernel name type (typename KernelName) for it.
Parameters
global_size is the full size of the range<>
Template Parameters
Dims dimensionality of the iteration space
KernelName is a class type that defines the name to be used for the underlying kernel
Parameters
f is the kernel functor to execute
Template Parameters
ParallelForFunctor is the type of the kernel functor
Definition at line 264 of file handler.hpp.
{
    if constexpr (detail::use_native_work_item) {
      // Use a normal parallel for
      schedule_parallel_for_kernel<KernelName>(
          [=] { detail::parallel_for(global_size, f); }, global_size);
    } else
      // Launch a single-task kernel containing the loop nests
      schedule_kernel<KernelName>(
          [=] { detail::parallel_for(global_size, f); });
  }
References trisycl::detail::parallel_for(), and trisycl::detail::use_native_work_item.
Referenced by trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::parallel_for().
parallel_for() [2/7]
template<typename KernelName = std::nullptr_t, int Dims, typename ParallelForFunctor > void trisycl::handler::parallel_for (const std::size_t(&) global_size[Dims], ParallelForFunctor f) inline
SYCL parallel_for launches a data parallel computation with parallelism specified at launch time with a range defined with a { dim1, dim2, dim3... } syntax.
Kernel invocation method of a kernel defined as a lambda or functor, for the specified range and given an id or item for indexing in the indexing space defined by range.
If it is a lambda function or the if the functor type is globally visible there is no need for the developer to provide a kernel name type (typename KernelName) for it.
Parameters
global_size is the full size of the range<> defined as a C array to allow type deduction from a list-initialization with { args... }
Template Parameters
Dims dimensionality of the iteration space
KernelName is a class type that defines the name to be used for the underlying kernel
Parameters
f is the kernel functor to execute
Template Parameters
ParallelForFunctor is the type of the kernel functor
Definition at line 302 of file handler.hpp.
{
    parallel_for<KernelName>(range<Dims> { global_size }, f);
  }
parallel_for() [3/7]
template<typename KernelName = std::nullptr_t, int Dimensions, typename ParallelForFunctor > void trisycl::handler::parallel_for (nd_range< Dimensions > r, ParallelForFunctor f) inline
Kernel invocation method of a kernel defined as a lambda or functor, for the specified nd_range and given an nd_item for indexing in the indexing space defined by the nd_range.
If it is a lambda function or the if the functor type is globally visible there is no need for the developer to provide a kernel name type (typename KernelName) for it, as described in detail in 3.5.3
Parameters
r defines the iteration space with the work-group layout and offset
Dimensions dimensionality of the iteration space
f is the kernel functor to execute
ParallelForFunctor is the kernel functor type
KernelName is a class type that defines the name to be used for the underlying kernel
Definition at line 388 of file handler.hpp.
{
    schedule_kernel<KernelName>([=] { detail::parallel_for(r, f); });
  }
References trisycl::detail::parallel_for().
parallel_for() [4/7]
template<int Dimensions = 1> void trisycl::handler::parallel_for (nd_range< Dimensions > , kernel syclKernel) inline
Kernel invocation method of a kernel defined as pointer to a kernel object, for the specified nd_range and given an nd_item for indexing in the indexing space defined by the nd_range, described in detail in 3.5.3.
Todo:
Add in the spec a version taking a kernel and a functor, to have host fall-back
Todo:
To be implemented
Definition at line 519 of file handler.hpp.
{
    TRISYCL_UNIMPL;
  }
References TRISYCL_UNIMPL.
parallel_for() [5/7]
template<typename KernelName = std::nullptr_t, int Dims, typename ParallelForFunctor > void trisycl::handler::parallel_for (range< Dims > global_size, id< Dims > offset, ParallelForFunctor f) inline
Kernel invocation method of a kernel defined as a lambda or functor, for the specified range and offset and given an id or item for indexing in the indexing space defined by range.
If it is a lambda function or the if the functor type is globally visible there is no need for the developer to provide a kernel name type (typename KernelName) for it, as described in detail in 3.5.3
Parameters
global_size is the global size of the range<>
offset is the offset to be add to the id<> during iteration
f is the kernel functor to execute
ParallelForFunctor is the kernel functor type
KernelName is a class type that defines the name to be used for the underlying kernel
Definition at line 359 of file handler.hpp.
{
    schedule_kernel<KernelName>(
        [=] { detail::parallel_for_global_offset(global_size, offset, f); });
  }
References offset, and trisycl::detail::parallel_for_global_offset().
parallel_for() [6/7]
template<typename KernelName = std::nullptr_t, typename ParallelForFunctor > requires (!std::derived_from<ParallelForFunctor, kernel>) void trisycl::handler::parallel_for (std::size_t global_size, ParallelForFunctor f) inline
SYCL parallel_for launches a data parallel computation with parallelism specified at launch time with a range defined with a single dimension as an integer.
Kernel invocation method of a kernel defined as a lambda or functor, for the specified range and given an id or item for indexing in the indexing space defined by range.
If it is a lambda function or the if the functor type is globally visible there is no need for the developer to provide a kernel name type (typename KernelName) for it.
Parameters
global_size is the full size of the range<1> defined as an integer
Template Parameters
KernelName is a class type that defines the name to be used for the underlying kernel
Parameters
f is the kernel functor to execute
Template Parameters
ParallelForFunctor is the type of the kernel functor
Definition at line 333 of file handler.hpp.
{
    parallel_for<KernelName>(range { global_size }, f);
  }
parallel_for() [7/7]
template<int Dimensions = 1, typename SYCLrange > requires (std::derived_from<SYCLrange, range<Dimensions>> || std::integral<SYCLrange>) void trisycl::handler::parallel_for (SYCLrange num_work_items, kernel sycl_kernel) inline
Kernel invocation method of a kernel defined as a kernel object, for the specified range and given an id or item for indexing in the indexing space defined by range, described in detail in 5.4.
Todo:
Add in the spec a version taking a kernel and a functor, to have host fall-back
Definition at line 489 of file handler.hpp.
{
    /* For now just use the usual host task system to schedule
       manually the OpenCL kernels instead of using OpenCL event-based
       scheduling
       todo Move the tracing inside the kernel implementation
       todo Simplify this 2 step ugly interface
    */
    task->set_kernel(sycl_kernel.implementation);
    /* Use an intermediate variable to capture task by copy because
       otherwise "this" is captured by reference and havoc with task
       just accessing the dead "this". Nasty bug to find... */
    task->schedule(detail::trace_kernel<kernel>([=, t = task] {
      sycl_kernel.implementation->parallel_for(t, t->get_queue(),
                                               detail::rangeify(num_work_items));
    }));
  }
References trisycl::detail::shared_ptr_implementation< Parent, Implementation >::implementation, trisycl::detail::rangeify(), and task.
parallel_for_work_group() [1/2]
template<typename KernelName = std::nullptr_t, int Dimensions = 1, typename ParallelForFunctor > void trisycl::handler::parallel_for_work_group (nd_range< Dimensions > r, ParallelForFunctor f) inline
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
May contain multiple kernel built-in parallel_for_work_item functions representing the execution on each work-item.
Launch num_work_groups work-groups of runtime-defined size. Described in detail in 3.5.3.
Parameters
r defines the iteration space with the work-group layout and offset
Dimensions dimensionality of the iteration space
f is the kernel functor to execute
ParallelForFunctor is the kernel functor type
KernelName is a class type that defines the name to be used for the underlying kernel
Definition at line 418 of file handler.hpp.
{
    schedule_kernel<KernelName>([=] {
        detail::parallel_for_workgroup(r, f);
      });
  }
References trisycl::detail::parallel_for_workgroup().
Referenced by parallel_for_work_group().
parallel_for_work_group() [2/2]
template<typename KernelName = std::nullptr_t, int Dimensions = 1, typename ParallelForFunctor > void trisycl::handler::parallel_for_work_group (range< Dimensions > r1, range< Dimensions > r2, ParallelForFunctor f) inline
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
May contain multiple kernel built-in parallel_for_work_item functions representing the execution on each work-item.
Launch num_work_groups work-groups of runtime-defined size. Described in detail in 3.5.3.
Parameters
r defines the iteration space with the work-group layout and offset
Dimensions dimensionality of the iteration space
f is the kernel functor to execute
ParallelForFunctor is the kernel functor type
KernelName is a class type that defines the name to be used for the underlying kernel
Definition at line 450 of file handler.hpp.
{
    parallel_for_work_group(nd_range<Dimensions> { r1, r2 }, f);
  }
References parallel_for_work_group().
schedule_kernel()
template<typename KernelName , typename Kernel > void trisycl::handler::schedule_kernel (Kernel k) inline private
Schedule the kernel.
Add a traced version of the kernel in host mode or add the kernel in an instantiating function for later extraction by the compiler
Definition at line 171 of file handler.hpp.
{
    /* Explicitly capture task by copy instead of having this captured
       by reference and task by reference by side effect */
    task->schedule(detail::trace_kernel<KernelName>([=, t = task] () mutable {
          if (t->owner_queue->is_host())
            k();
          else {
            TRISYCL_DUMP_T("schedule_kernel &k = " << (void *) &k);
            // Structure the kernel code so it can be outlined and called
            detail::launch_device_kernel<KernelName>(*t, k);
            // \todo for now only deal with 1 physical work-item only
            t->get_kernel().single_task(t, t->get_queue());
          }
        }));
  }
References task, and TRISYCL_DUMP_T.
schedule_parallel_for_kernel()
template<typename KernelName , typename Kernel , int N> void trisycl::handler::schedule_parallel_for_kernel (Kernel k, const range< N > & num_work_items) inline private
Schedule a parallel for kernel.
Todo:
Add host fall-back execution for parallel_for_kernel
Add a traced version of the kernel in host mode or add the kernel in an instantiating function for later extraction by the compiler and then execute it using parallel_for
Definition at line 199 of file handler.hpp.
{
    task->schedule(detail::trace_kernel<KernelName>([=, t = task] () mutable {
          // if (t->owner_queue->is_host())
             // k();
          // else {
            TRISYCL_DUMP_T("schedule_parallel_for_kernel &k = " << (void *) &k);
            // Structure the kernel code so it can be outlined and called
            detail::launch_device_kernel<KernelName>(*t, k);
            t->get_kernel().parallel_for(t, t->get_queue(), num_work_items);
      // }
    }));
  }
References task, and TRISYCL_DUMP_T.
set_arg() [1/3]
template<typename DataType , int Dimensions, access::mode Mode, access::target Target = access::target::global_buffer> void trisycl::handler::set_arg (int arg_index, accessor< DataType, Dimensions, Mode, Target > && acc_obj) inline
Set accessor kernel arg for an OpenCL kernel which is used through the SYCL/OpenCL interop interface.
The index value specifies which parameter of the OpenCL kernel is being set and the accessor object, which OpenCL buffer or image is going to be given as kernel argument.
Todo:
Update the specification to use a ref && to the accessor instead?
Todo:
It is not that clean to have set_arg() associated to a command handler. Rethink the specification?
Todo:
It seems more logical to have these methods on kernel instead
Definition at line 89 of file handler.hpp.
{
    /* Think about setting the kernel argument before actually calling
       the kernel.
       Explicitly capture task by copy instead of having this captured
       by reference and task by reference by side effect */
    task->add_prelude([=, task = task] {
        task->set_arg(arg_index, acc_obj.implementation->get_cl_buffer());
      });
  }
References task.
Referenced by dispatch_set_arg().
set_arg() [2/3]
template<typename T , typename = std::enable_if_t<is_wrapper<T>::value>> void trisycl::handler::set_arg (int arg_index, T && scalar_value) inline
Set kernel args for an OpenCL kernel which is used through the SYCL/OpenCL interoperability interface with a wrapper type.
Definition at line 106 of file handler.hpp.
{
    /* Explicitly capture task by copy instead of having this captured
       by reference and task by reference by side effect */
    task->add_prelude([=, task = task] {
        task->set_arg(arg_index, scalar_value.unwrap());
      });
  }
References task.
set_arg() [3/3]
template<typename T > std::enable_if_t<!is_wrapper< T >::value > trisycl::handler::set_arg (int arg_index, T && scalar_value) inline
Set kernel args for an OpenCL kernel which is used through the SYCL/OpenCL interoperability interface without a wrapper type.
Definition at line 120 of file handler.hpp.
{
    /* Explicitly capture task by copy instead of having this captured
       by reference and task by reference by side effect */
    task->add_prelude([=, task = task] {
        task->set_arg(arg_index, scalar_value);
      });
  }
References task.
set_args()
template<typename... Ts> void trisycl::handler::set_args (Ts &&... args) inline
Set all kernel args for an OpenCL kernel which is used through the SYCL/OpenCL interop interface.
Todo:
Update the specification to add this function according to https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15978 proposal
Definition at line 153 of file handler.hpp.
{
    /* Construct a set of increasing argument index to be able to call
       the real set_arg */
    dispatch_set_arg(std::index_sequence_for<Ts...>{},
                     std::forward<Ts>(args)...);
  }
References dispatch_set_arg().
single_task() [1/2]
void trisycl::handler::single_task (kernel sycl_kernel) inline
Kernel invocation method of a kernel defined as pointer to a kernel object, described in detail in 3.5.3.
Todo:
Add in the spec a version taking a kernel and a functor, to have host fall-back
Definition at line 462 of file handler.hpp.
{
    /* For now just use the usual host task system to schedule
       manually the OpenCL kernels instead of using OpenCL event-based
       scheduling
       \todo Move the tracing inside the kernel implementation
       \todo Simplify this 2 step ugly interface
    */
    task->set_kernel(sycl_kernel.implementation);
    task->schedule(detail::trace_kernel<kernel>([=, t = task] {
          sycl_kernel.implementation->single_task(t, t->get_queue());
        }));
  }
References trisycl::detail::shared_ptr_implementation< Parent, Implementation >::implementation, and task.
single_task() [2/2]
template<typename KernelName = std::nullptr_t, typename ParallelForFunctor > void trisycl::handler::single_task (ParallelForFunctor && f) inline
Kernel invocation method of a kernel defined as a lambda or functor.
If it is a lambda function or the functor type is globally visible there is no need for the developer to provide a kernel name type (typename KernelName) for it, as described in 3.5.3
SYCL single_task launches a computation without parallelism at launch time.
Parameters
F specify the kernel to be launched as a single_task
KernelName is a class type that defines the name to be used for the underlying kernel
Definition at line 231 of file handler.hpp.
{
    TRISYCL_DUMP_T("single_task &f = " << (void *) &f);
    schedule_kernel<KernelName>(std::forward<ParallelForFunctor>(f));
  }
References TRISYCL_DUMP_T.
Referenced by trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::single_task().
Member Data Documentation
task
std::shared_ptr<detail::task> trisycl::handler::task
Attach the task and accessors to it.
Definition at line 52 of file handler.hpp.
Referenced by trisycl::detail::add_buffer_to_task(), handler(), parallel_for(), schedule_kernel(), schedule_parallel_for_kernel(), set_arg(), and single_task().
trisycl::kernel
class trisycl::kernel
SYCL kernel.
Todo:
To be implemented
Todo:
Check specification
Definition at line 37 of file kernel.hpp.
Public Member Functions
kernel ()=delete
The default object is not valid because there is no program or.
kernel (cl_kernel k)
Constructor for SYCL kernel class given an OpenCL kernel object with set arguments, valid for enqueuing.
kernel (const boost::compute::kernel &k)
Construct a kernel class instance using a boost::compute::kernel.
cl_kernel get () const
Return the OpenCL kernel object for this kernel.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< kernel, detail::kernel >
shared_ptr_implementation (std::shared_ptr< detail::kernel > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::kernel *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename kernel::shared_ptr_implementation
Private Attributes
friend implementation_t
Friends
class handler
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< kernel, detail::kernel >
std::shared_ptr< detail::kernel > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
implementation_t
using trisycl::kernel::implementation_t = typename kernel::shared_ptr_implementation private
Definition at line 43 of file kernel.hpp.
Constructor & Destructor Documentation
kernel() [1/3]
trisycl::kernel::kernel () delete
The default object is not valid because there is no program or.
cl_kernel
associated with it
kernel() [2/3]
trisycl::kernel::kernel (cl_kernel k) inline
Constructor for SYCL kernel class given an OpenCL kernel object with set arguments, valid for enqueuing.
Retains a reference to the cl_kernel object. The Caller should release the passed cl_kernel object when it is no longer needed.
Definition at line 68 of file kernel.hpp.
: kernel { boost::compute::kernel { k } } {}
kernel() [3/3]
trisycl::kernel::kernel (const boost::compute::kernel & k) inline
Construct a kernel class instance using a boost::compute::kernel.
This is a triSYCL extension for boost::compute interoperation.
Return synchronous errors via the SYCL exception class.
Definition at line 77 of file kernel.hpp.
    : implementation_t { detail::opencl_kernel::instance(k) } {}
Member Function Documentation
get()
cl_kernel trisycl::kernel::get () const inline
Return the OpenCL kernel object for this kernel.
Retains a reference to the returned cl_kernel object. Caller should release it when finished.
Definition at line 86 of file kernel.hpp.
{
    return implementation->get();
  }
References trisycl::detail::shared_ptr_implementation< kernel, detail::kernel >::implementation.
Friends And Related Function Documentation
handler
friend class handler friend
Definition at line 46 of file kernel.hpp.
Member Data Documentation
implementation_t
friend trisycl::kernel::implementation_t private
Definition at line 49 of file kernel.hpp.
trisycl::detail::kernel
class trisycl::detail::kernel
Abstract SYCL kernel.
Definition at line 29 of file kernel.hpp.
Public Member Functions
virtual cl_kernel get () const =0
Return the OpenCL kernel object for this kernel.
virtual boost::compute::kernel & get_boost_compute ()=0
Return the Boost.Compute OpenCL kernel object for this kernel.
virtual void single_task (std::shared_ptr< detail::task > task, std::shared_ptr< detail::queue > q)=0
Launch a single task of the kernel.
TRISYCL_ParallelForKernel_RANGE (1) TRISYCL_ParallelForKernel_RANGE(2) TRISYCL_ParallelForKernel_RANGE(3) virtual ~kernel()
Return the context that this kernel is defined for.
Additional Inherited Members
Static Private Member Functions inherited from trisycl::detail::debug< detail::kernel >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Function Documentation
get()
virtual cl_kernel trisycl::detail::kernel::get () const pure virtual
Return the OpenCL kernel object for this kernel.
Retains a reference to the returned cl_kernel object. Caller should release it when finished.
Implemented in trisycl::detail::opencl_kernel.
get_boost_compute()
virtual boost::compute::kernel & trisycl::detail::kernel::get_boost_compute () pure virtual
Return the Boost.Compute OpenCL kernel object for this kernel.
This is an extension.
Implemented in trisycl::detail::opencl_kernel.
Referenced by trisycl::detail::task::set_arg().
single_task()
virtual void trisycl::detail::kernel::single_task (std::shared_ptr< detail::task > task, std::shared_ptr< detail::queue > q) pure virtual
Launch a single task of the kernel.
Implemented in trisycl::detail::opencl_kernel.
TRISYCL_ParallelForKernel_RANGE()
trisycl::detail::kernel::TRISYCL_ParallelForKernel_RANGE (1) inline
Return the context that this kernel is defined for.
Return the program that this kernel is part of
Definition at line 65 of file kernel.hpp.
                    {}
trisycl::platform
class trisycl::platform
Abstract the OpenCL platform.
Todo:
triSYCL Implementation
Definition at line 40 of file platform.hpp.
Public Member Functions
platform ()
Default constructor for platform which is the host platform.
platform (cl_platform_id platform_id)
Construct a platform class instance using cl_platform_id of the OpenCL device.
platform (const boost::compute::platform &p)
Construct a platform class instance using a boost::compute::platform.
platform (const device_selector &dev_selector)
Construct a platform object from the device selected by a device selector of the user's choice.
cl_platform_id get () const
Returns the cl_platform_id of the underlying OpenCL platform.
const boost::compute::platform get_boost_compute () const
Return the underlying Boost.Compute platform if it is an OpenCL platform.
template<info::platform param>
auto get_info () const
Get the OpenCL information about the requested parameter.
bool has_extension (const string_class &extension) const
Test if an extension is available on the platform.
bool is_host () const
Test if this platform is a host platform.
vector_class< device > get_devices (info::device_type device_type=info::device_type::all) const
Get all the available devices for this platform.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< platform, detail::platform >
shared_ptr_implementation (std::shared_ptr< detail::platform > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::platform *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Static Public Member Functions
static vector_class< platform > get_platforms ()
Get the list of all the platforms available to the application.
Private Attributes
friend shared_ptr_implementation
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< platform, detail::platform >
std::shared_ptr< detail::platform > implementation
The implementation forward everything to this... implementation.
Constructor & Destructor Documentation
platform() [1/4]
trisycl::platform::platform () inline
Default constructor for platform which is the host platform.
Returns errors via the SYCL exception class.
Definition at line 57 of file platform.hpp.
             :
    shared_ptr_implementation { detail::host_platform::instance() } {}
platform() [2/4]
trisycl::platform::platform (cl_platform_id platform_id) inline explicit
Construct a platform class instance using cl_platform_id of the OpenCL device.
Return synchronous errors via the SYCL exception class.
Retain a reference to the OpenCL platform.
Definition at line 69 of file platform.hpp.
    : platform { boost::compute::platform { platform_id } } {}
platform() [3/4]
trisycl::platform::platform (const boost::compute::platform & p) inline
Construct a platform class instance using a boost::compute::platform.
This is a triSYCL extension for boost::compute interoperation.
Return synchronous errors via the SYCL exception class.
Definition at line 79 of file platform.hpp.
    : shared_ptr_implementation { detail::opencl_platform::instance(p) } {}
platform() [4/4]
trisycl::platform::platform (const device_selector & dev_selector) explicit
Construct a platform object from the device selected by a device selector of the user's choice.
Returns errors via the SYCL exception class.
Member Function Documentation
get()
cl_platform_id trisycl::platform::get () const inline
Returns the cl_platform_id of the underlying OpenCL platform.
If the platform is not a valid OpenCL platform, for example if it is the SYCL host, an exception is thrown
Todo:
Define a SYCL exception for this
Definition at line 99 of file platform.hpp.
{
    return implementation->get();
  }
References trisycl::detail::shared_ptr_implementation< platform, detail::platform >::implementation.
get_boost_compute()
const boost::compute::platform trisycl::platform::get_boost_compute () const inline
Return the underlying Boost.Compute platform if it is an OpenCL platform.
This is a triSYCL extension
Definition at line 109 of file platform.hpp.
{
    return implementation->get_boost_compute();
  }
References trisycl::detail::shared_ptr_implementation< platform, detail::platform >::implementation.
get_devices()
vector_class< device > trisycl::platform::get_devices (info::device_type device_type = info::device_type::all) const
Get all the available devices for this platform.
Parameters
[in] device_type is the device type to filter the selection or info::device_type::all by default to return all the devices
Returns
the device list
Referenced by trisycl::device_selector::select_device().
get_info()
template<info::platform param> auto trisycl::platform::get_info () const inline
Get the OpenCL information about the requested parameter.
Todo:
Add to the specification
get_platforms()
static vector_class< platform > trisycl::platform::get_platforms () inline static
Get the list of all the platforms available to the application.
Definition at line 116 of file platform.hpp.
{
    // Start with the default platform
    vector_class<platform> platforms { {} };
#ifdef TRISYCL_OPENCL
    // Then add all the OpenCL platforms
    for (const auto &d : boost::compute::system::platforms())
      platforms.emplace_back(d);
#endif
    return platforms;
  }
Referenced by trisycl::device_selector::select_device().
has_extension()
bool trisycl::platform::has_extension (const string_class & extension) const inline
Test if an extension is available on the platform.
Definition at line 138 of file platform.hpp.
{
    return implementation->has_extension(extension);
  }
References trisycl::detail::shared_ptr_implementation< platform, detail::platform >::implementation.
is_host()
bool trisycl::platform::is_host () const inline
Test if this platform is a host platform.
Definition at line 144 of file platform.hpp.
                       {
    return implementation->is_host();
  }
References trisycl::detail::shared_ptr_implementation< platform, detail::platform >::implementation.
Member Data Documentation
shared_ptr_implementation
friend trisycl::platform::shared_ptr_implementation private
Definition at line 46 of file platform.hpp.
trisycl::detail::host_platform
class trisycl::detail::host_platform
SYCL host platform.
Definition at line 35 of file host_platform.hpp.
Public Member Functions
cl_platform_id get () const override
Return the cl_platform_id of the underlying OpenCL platform.
boost::compute::platform & get_boost_compute () const override
Return the underlying Boost.Compute platform.
bool is_host () const override
Return true since this platform is the SYCL host platform.
string_class get_info_string (info::platform param) const override
Returning the information parameters for the host platform implementation.
vector_class< string_class > get_extension_strings (void) const override
bool has_extension (const string_class &extension) const override
Specify whether a specific extension is supported on the platform.
vector_class< trisycl::device > get_devices (const device_selector &device_selector) const override
Get all the available devices for the host platform.
Public Member Functions inherited from trisycl::detail::platform
virtual cl_platform_id get () const =0
Return the cl_platform_id of the underlying OpenCL platform.
virtual const boost::compute::platform & get_boost_compute () const =0
Return the underlying Boost.Compute platform, if any.
virtual bool is_host () const =0
Return true if the platform is a SYCL host platform.
virtual string_class get_info_string (info::platform param) const =0
Query the platform for OpenCL string info::platform info.
virtual vector_class< string_class > get_extension_strings () const =0
virtual bool has_extension (const string_class &extension) const =0
Specify whether a specific extension is supported on the platform.
virtual vector_class< device > get_devices (const device_selector &device_selector) const =0
Get all the available devices for this platform.
virtual ~platform ()
Private Attributes
vector_class< string_class > platform_extensions { "Xilinx_blocking_pipes" }
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::singleton< host_platform >
static std::shared_ptr< host_platform > instance ()
Get a singleton instance of T.
Member Function Documentation
get()
cl_platform_id trisycl::detail::host_platform::get () const inline override virtual
Return the cl_platform_id of the underlying OpenCL platform.
This throws an error since there is no OpenCL platform associated to the host platform.
Implements trisycl::detail::platform.
Definition at line 51 of file host_platform.hpp.
{
    throw non_cl_error("The host platform has no OpenCL platform");
  }
get_boost_compute()
boost::compute::platform & trisycl::detail::host_platform::get_boost_compute () const inline override virtual
Return the underlying Boost.Compute platform.
This throws an error since there is no Boost Compute platform associated to the host platform.
Implements trisycl::detail::platform.
Definition at line 61 of file host_platform.hpp.
{
    throw
      non_cl_error("The host device has no underlying Boost Compute platform");
  }
get_extension_strings()
vector_class< string_class > trisycl::detail::host_platform::get_extension_strings (void) const inline override virtual
Implements trisycl::detail::platform.
Definition at line 101 of file host_platform.hpp.
{
    return platform_extensions;
  }
References platform_extensions.
get_info_string()
string_class trisycl::detail::host_platform::get_info_string (info::platform param) const inline override virtual
Returning the information parameters for the host platform implementation.
Implements trisycl::detail::platform.
Definition at line 77 of file host_platform.hpp.
{
    switch (param) {
    case info::platform::profile:
      /* Well... Is the host platform really a full profile whereas it
         is not really OpenCL? */
      return "FULL_PROFILE";
    case info::platform::version:
      // \todo I guess it should include the software version too...
      return "2.2";
    case info::platform::name:
      return "triSYCL host platform";
    case info::platform::vendor:
      return "triSYCL Open Source project";
    default:
      // \todo Define some SYCL exception type for this type of errors
      throw std::invalid_argument {
        "Unknown parameter value for SYCL platform information" };
    }
  }
has_extension()
bool trisycl::detail::host_platform::has_extension (const string_class & extension) const inline override virtual
Specify whether a specific extension is supported on the platform.
Todo:
To be implemented
Implements trisycl::detail::platform.
Definition at line 110 of file host_platform.hpp.
{
    return std::find(platform_extensions.begin(), platform_extensions.end(), extension) !=
           platform_extensions.end();
  }
References platform_extensions.
is_host()
bool trisycl::detail::host_platform::is_host () const inline override virtual
Return true since this platform is the SYCL host platform.
Implements trisycl::detail::platform.
Definition at line 69 of file host_platform.hpp.
{
    return true;
  }
Member Data Documentation
platform_extensions
vector_class<string_class> trisycl::detail::host_platform::platform_extensions { "Xilinx_blocking_pipes" } private
Definition at line 41 of file host_platform.hpp.
Referenced by get_extension_strings(), and has_extension().
trisycl::detail::opencl_platform
class trisycl::detail::opencl_platform
SYCL OpenCL platform.
Definition at line 34 of file opencl_platform.hpp.
Public Member Functions
cl_platform_id get () const override
Return the cl_platform_id of the underlying OpenCL platform.
const boost::compute::platform & get_boost_compute () const override
Return the underlying Boost.Compute platform.
bool is_host () const override
Return false since an OpenCL platform is not the SYCL host platform.
string_class get_info_string (info::platform param) const override
Returning the information string parameters for the OpenCL platform.
vector_class< string_class > get_extension_strings () const override
bool has_extension (const string_class &extension) const override
Specify whether a specific extension is supported on the platform.
vector_class< trisycl::device > get_devices (const device_selector &device_selector) const override
Get all the available devices for this OpenCL platform.
~opencl_platform () override
Unregister from the cache on destruction.
Public Member Functions inherited from trisycl::detail::platform
virtual cl_platform_id get () const =0
Return the cl_platform_id of the underlying OpenCL platform.
virtual const boost::compute::platform & get_boost_compute () const =0
Return the underlying Boost.Compute platform, if any.
virtual bool is_host () const =0
Return true if the platform is a SYCL host platform.
virtual string_class get_info_string (info::platform param) const =0
Query the platform for OpenCL string info::platform info.
virtual vector_class< string_class > get_extension_strings () const =0
virtual bool has_extension (const string_class &extension) const =0
Specify whether a specific extension is supported on the platform.
virtual vector_class< device > get_devices (const device_selector &device_selector) const =0
Get all the available devices for this platform.
virtual ~platform ()
Static Public Member Functions
static std::shared_ptr< opencl_platform > instance (const boost::compute::platform &p)
Private Member Functions
opencl_platform (const boost::compute::platform &p)
Only the instance factory can built it.
Private Attributes
boost::compute::platform p
Use the Boost Compute abstraction of the OpenCL platform.
Static Private Attributes
static detail::cache< cl_platform_id, detail::opencl_platform > cache
A cache to always return the same live platform for a given OpenCL platform.
Constructor & Destructor Documentation
opencl_platform()
trisycl::detail::opencl_platform::opencl_platform (const boost::compute::platform & p) inline private
Only the instance factory can built it.
Definition at line 107 of file opencl_platform.hpp.
: p { p } {}
~opencl_platform()
trisycl::detail::opencl_platform::~opencl_platform () inline override
Unregister from the cache on destruction.
Definition at line 112 of file opencl_platform.hpp.
{
    cache.remove(p.id());
  }
References p, and trisycl::detail::cache< Key, Value >::remove().
Member Function Documentation
get()
cl_platform_id trisycl::detail::opencl_platform::get () const inline override virtual
Return the cl_platform_id of the underlying OpenCL platform.
Implements trisycl::detail::platform.
Definition at line 49 of file opencl_platform.hpp.
{
    return p.id();
  }
References p.
get_boost_compute()
const boost::compute::platform & trisycl::detail::opencl_platform::get_boost_compute () const inline override virtual
Return the underlying Boost.Compute platform.
Implements trisycl::detail::platform.
Definition at line 55 of file opencl_platform.hpp.
{
    return p;
  }
References p.
Referenced by get_devices().
get_extension_strings()
vector_class< string_class > trisycl::detail::opencl_platform::get_extension_strings (void) const inline override virtual
Implements trisycl::detail::platform.
Definition at line 74 of file opencl_platform.hpp.
{
    return p.extensions();
  }
References p.
get_info_string()
string_class trisycl::detail::opencl_platform::get_info_string (info::platform param) const inline override virtual
Returning the information string parameters for the OpenCL platform.
Implements trisycl::detail::platform.
Definition at line 67 of file opencl_platform.hpp.
{
    /* Use the fact that the triSYCL info values are the same as the
       OpenCL ones used in Boost.Compute to just cast the enum class
       to the int value */
    return p.get_info<std::string>(static_cast<cl_platform_info>(param));
  }
References p.
has_extension()
bool trisycl::detail::opencl_platform::has_extension (const string_class & extension) const inline override virtual
Specify whether a specific extension is supported on the platform.
Implements trisycl::detail::platform.
Definition at line 80 of file opencl_platform.hpp.
{
    return p.supports_extension(extension);
  }
References p.
instance()
static std::shared_ptr< opencl_platform > trisycl::detail::opencl_platform::instance (const boost::compute::platform & p) inline static
Definition at line 87 of file opencl_platform.hpp.
{
    return cache.get_or_register(p.id(),
                                 [&] { return new opencl_platform { p }; });
  }
References trisycl::detail::cache< Key, Value >::get_or_register(), and p.
is_host()
bool trisycl::detail::opencl_platform::is_host () const inline override virtual
Return false since an OpenCL platform is not the SYCL host platform.
Implements trisycl::detail::platform.
Definition at line 61 of file opencl_platform.hpp.
{
    return false;
  }
Member Data Documentation
cache
detail::cache<cl_platform_id, detail::opencl_platform> trisycl::detail::opencl_platform::cache static private
A cache to always return the same live platform for a given OpenCL platform.
C++11 guaranties the static construction is thread-safe
Definition at line 44 of file opencl_platform.hpp.
p
boost::compute::platform trisycl::detail::opencl_platform::p private
Use the Boost Compute abstraction of the OpenCL platform.
Definition at line 37 of file opencl_platform.hpp.
Referenced by get(), get_boost_compute(), get_extension_strings(), get_info_string(), has_extension(), and instance().
trisycl::detail::platform
class trisycl::detail::platform
An abstract class representing various models of SYCL platforms.
Definition at line 28 of file platform.hpp.
Public Member Functions
virtual cl_platform_id get () const =0
Return the cl_platform_id of the underlying OpenCL platform.
virtual const boost::compute::platform & get_boost_compute () const =0
Return the underlying Boost.Compute platform, if any.
virtual bool is_host () const =0
Return true if the platform is a SYCL host platform.
virtual string_class get_info_string (info::platform param) const =0
Query the platform for OpenCL string info::platform info.
virtual vector_class< string_class > get_extension_strings () const =0
virtual bool has_extension (const string_class &extension) const =0
Specify whether a specific extension is supported on the platform.
virtual vector_class< device > get_devices (const device_selector &device_selector) const =0
Get all the available devices for this platform.
virtual ~platform ()
Constructor & Destructor Documentation
~platform()
virtual trisycl::detail::platform::~platform () inline virtual
Definition at line 64 of file platform.hpp.
{}
Member Function Documentation
get()
virtual cl_platform_id trisycl::detail::platform::get () const pure virtual
Return the cl_platform_id of the underlying OpenCL platform.
Implemented in trisycl::detail::host_platform, and trisycl::detail::opencl_platform.
get_boost_compute()
virtual const boost::compute::platform & trisycl::detail::platform::get_boost_compute () const pure virtual
Return the underlying Boost.Compute platform, if any.
Implemented in trisycl::detail::host_platform, and trisycl::detail::opencl_platform.
get_devices()
virtual vector_class< device > trisycl::detail::platform::get_devices (const device_selector & device_selector) const pure virtual
Get all the available devices for this platform.
Parameters
[in] device_selector is used to filter the selection.
Returns
the device list
Implemented in trisycl::detail::host_platform, and trisycl::detail::opencl_platform.
get_extension_strings()
virtual vector_class< string_class > trisycl::detail::platform::get_extension_strings () const pure virtual
Implemented in trisycl::detail::opencl_platform, and trisycl::detail::host_platform.
get_info_string()
virtual string_class trisycl::detail::platform::get_info_string (info::platform param) const pure virtual
Query the platform for OpenCL string info::platform info.
Implemented in trisycl::detail::host_platform, and trisycl::detail::opencl_platform.
has_extension()
virtual bool trisycl::detail::platform::has_extension (const string_class & extension) const pure virtual
Specify whether a specific extension is supported on the platform.
Implemented in trisycl::detail::host_platform, and trisycl::detail::opencl_platform.
is_host()
virtual bool trisycl::detail::platform::is_host () const pure virtual
Return true if the platform is a SYCL host platform.
Implemented in trisycl::detail::host_platform, and trisycl::detail::opencl_platform.
trisycl::queue
class trisycl::queue
SYCL queue, similar to the OpenCL queue concept.
Todo:
The implementation is quite minimal for now. :-)
Todo:
All the queue methods should return a queue& instead of void to it is possible to chain opoerations
Definition at line 52 of file queue.hpp.
Public Member Functions
queue (const property_list &propList={})
Default constructor for queue from the default queue selector.
queue (const async_handler &asyncHandler, const property_list &propList={})
This constructor creates a SYCL queue from an OpenCL queue.
queue (const device_selector &deviceSelector, const property_list &propList={})
Creates a queue for the device provided by the device selector.
queue (const device_selector &deviceSelector, const async_handler &asyncHandler, const property_list &propList={})
Creates a queue for the device provided by the device selector.
queue (const device &d, const async_handler &asyncHandler, const property_list &propList={})
A queue is created for a SYCL device.
queue (const device &d, const property_list &propList={})
A queue is created for a SYCL device.
queue (const context &syclContext, const device_selector &deviceSelector, const async_handler &asyncHandler, const property_list &propList={})
This constructor chooses a device based on the provided device_selector, which needs to be in the given context.
queue (const context &syclContext, const device_selector &deviceSelector, const property_list &propList={})
This constructor chooses a device based on the provided device_selector, which needs to be in the given context.
queue (const cl_command_queue &q, const context &syclContext, const async_handler &ah={})
This constructor creates a SYCL queue from an OpenCL queue.
queue (const boost::compute::command_queue &q, async_handler ah=nullptr)
Construct a queue instance using a boost::compute::command_queue.
cl_command_queue get () const
Return the underlying OpenCL command queue after doing a retain.
boost::compute::command_queue get_boost_compute () const
Return the underlying Boost.Compute command queue if it is an OpenCL queue.
context get_context () const
Return the SYCL queue's context.
device get_device () const
Return the SYCL device the queue is associated with.
bool is_host () const
Return whether the queue is executing on a SYCL host device.
void wait ()
Performs a blocking wait for the completion all enqueued tasks in the queue.
void wait_and_throw ()
Perform a blocking wait for the completion all enqueued tasks in the queue.
void throw_asynchronous ()
Checks to see if any asynchronous errors have been produced by the queue and if so reports them by passing them to the async_handler passed to the queue on construction.
template<info::queue param>
auto get_info () const
Queries the platform for cl_command_queue info.
template<typename Handler_Functor >
event submit (Handler_Functor cgf)
Submit a command group functor to the queue, in order to be scheduled for execution on the device.
template<typename Handler_Functor >
event submit (Handler_Functor cgf, queue &secondaryQueue)
Submit a command group functor to the queue, in order to be scheduled for execution on the device.
template<typename propertyT >
bool has_property () const
Check if the queue was constructed with the specified property.
template<typename propertyT >
propertyT get_property () const
Return a copy of the property that the queue was constructed with.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< queue, detail::queue >
shared_ptr_implementation (std::shared_ptr< detail::queue > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::queue *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Public Member Functions inherited from trisycl::property_list
template<typename... propsT, typename = std::enable_if_t<detail::all_true<std::is_convertible<propsT, detail::property>::value ...>::value>>
property_list (propsT... props)
Construct a property list from a list of classes derived from the detail::property.
property_list ()
Private Types
using implementation_t = typename queue::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< queue, detail::queue >
std::shared_ptr< detail::queue > implementation
The implementation forward everything to this... implementation.
Protected Member Functions inherited from trisycl::property_list
template<typename propertyT >
bool has_property () const
template<typename propertyT >
propertyT get_property () const
Static Private Member Functions inherited from trisycl::detail::debug< queue >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Typedef Documentation
implementation_t
using trisycl::queue::implementation_t = typename queue::shared_ptr_implementation private
Definition at line 61 of file queue.hpp.
Constructor & Destructor Documentation
queue() [1/10]
trisycl::queue::queue (const property_list & propList = {}) explicit
Default constructor for queue from the default queue selector.
Returns errors via the SYCL exception class.
queue() [2/10]
trisycl::queue::queue (const async_handler & asyncHandler, const property_list & propList = {})
This constructor creates a SYCL queue from an OpenCL queue.
At construction it does a retain on the queue memory object.
Retain a reference to the cl_command_queue object. Caller should release the passed cl_command_queue object when it is no longer needed.
Return synchronous errors regarding the creation of the queue and report asynchronous errors via the async_handler callback function in conjunction with the synchronization and throw methods.
Note that the default case asyncHandler = nullptr is handled by the default constructor.
queue() [3/10]
trisycl::queue::queue (const device_selector & deviceSelector, const property_list & propList = {}) inline
Creates a queue for the device provided by the device selector.
If no device is selected, an error is reported.
Return synchronous errors regarding the creation of the queue and report asynchronous errors via the async_handler callback function if and only if there is an async_handler provided.
Definition at line 106 of file queue.hpp.
                                        {})
    // Just create the queue from the selected device
    : queue { device { deviceSelector }, nullptr, propList } { }
queue() [4/10]
trisycl::queue::queue (const device_selector & deviceSelector, const async_handler & asyncHandler, const property_list & propList = {}) inline
Creates a queue for the device provided by the device selector.
Return synchronous errors regarding the creation of the queue and report asynchronous errors via the async_handler callback function if and only if there is an async_handler provided.
Definition at line 117 of file queue.hpp.
                                        {})
    // Just create the queue from the selected device
    : queue { device { deviceSelector }, asyncHandler, propList } { }
queue() [5/10]
trisycl::queue::queue (const device & d, const async_handler & asyncHandler, const property_list & propList = {}) inline
A queue is created for a SYCL device.
Return asynchronous errors via the async_handler callback function.
Definition at line 128 of file queue.hpp.
                                        {}) : implementation_t {
#ifdef TRISYCL_OPENCL
    d.is_host()
      ? std::shared_ptr<detail::queue>{ new detail::host_queue }
      : detail::opencl_queue::instance(d)
#else
    new detail::host_queue
#endif
  }, property_list { propList } { }
queue() [6/10]
trisycl::queue::queue (const device & d, const property_list & propList = {}) inline
A queue is created for a SYCL device.
Definition at line 143 of file queue.hpp.
                                        {})
    : queue { d, {}, propList } {}
queue() [7/10]
trisycl::queue::queue (const context & syclContext, const device_selector & deviceSelector, const async_handler & asyncHandler, const property_list & propList = {}) inline
This constructor chooses a device based on the provided device_selector, which needs to be in the given context.
If no device is selected, an error is reported.
Return synchronous errors regarding the creation of the queue.
If and only if there is an asyncHandler provided, it reports asynchronous errors via the async_handler callback function in conjunction with the synchronization and throw methods.
Definition at line 158 of file queue.hpp.
                                        {})
    : property_list { propList } {
    device d = deviceSelector.select_device();
    vector_class<device> ctx_devs = syclContext.get_devices();
    if (std::find(ctx_devs.begin(), ctx_devs.end(), d) == ctx_devs.end())
      throw trisycl::invalid_object_error("Device doesn't belong to context\n");
    implementation =
#ifdef TRISYCL_OPENCL
      d.is_host() ? std::shared_ptr<detail::queue>{ new detail::host_queue }
    : detail::opencl_queue::instance(d);
#else
    std::shared_ptr<detail::queue>{ new detail::host_queue };
#endif
  }
queue() [8/10]
trisycl::queue::queue (const context & syclContext, const device_selector & deviceSelector, const property_list & propList = {}) inline
This constructor chooses a device based on the provided device_selector, which needs to be in the given context.
If no device is selected, an error is reported.
Return synchronous errors regarding the creation of the queue.
Definition at line 183 of file queue.hpp.
                                        {})
    : queue { syclContext, deviceSelector, {}, propList } {}
queue() [9/10]
trisycl::queue::queue (const cl_command_queue & q, const context & syclContext, const async_handler & ah = {}) inline
This constructor creates a SYCL queue from an OpenCL queue.
At construction it does a retain on the queue memory object.
Return synchronous errors regarding the creation of the queue. If and only if there is an async_handler provided, it reports asynchronous errors via the async_handler callback function in conjunction with the synchronization and throw methods.
Definition at line 198 of file queue.hpp.
                                  {})
    : queue { boost::compute::command_queue { q }, ah } {}
queue() [10/10]
trisycl::queue::queue (const boost::compute::command_queue & q, async_handler ah = nullptr) inline
Construct a queue instance using a boost::compute::command_queue.
This is a triSYCL extension for boost::compute interoperation.
Return synchronous errors via the SYCL exception class.
Todo:
Deal with handler
Definition at line 211 of file queue.hpp.
    : implementation_t { detail::opencl_queue::instance(q) }, property_list {} {}
Member Function Documentation
get()
cl_command_queue trisycl::queue::get () const inline
Return the underlying OpenCL command queue after doing a retain.
This memory object is expected to be released by the developer.
Retain a reference to the returned cl_command_queue object.
Caller should release it when finished.
If the queue is a SYCL host queue then an exception is thrown.
Definition at line 227 of file queue.hpp.
{
    return implementation->get();
  }
References trisycl::detail::shared_ptr_implementation< queue, detail::queue >::implementation.
get_boost_compute()
boost::compute::command_queue trisycl::queue::get_boost_compute () const inline
Return the underlying Boost.Compute command queue if it is an OpenCL queue.
This is a triSYCL extension
Definition at line 237 of file queue.hpp.
{
    return implementation->get_boost_compute();
  }
References trisycl::detail::shared_ptr_implementation< queue, detail::queue >::implementation.
get_context()
context trisycl::queue::get_context () const inline
Return the SYCL queue's context.
Report errors using SYCL exception classes.
Definition at line 247 of file queue.hpp.
{
    return implementation->get_context();
  }
References trisycl::detail::shared_ptr_implementation< queue, detail::queue >::implementation.
get_device()
device trisycl::queue::get_device () const inline
Return the SYCL device the queue is associated with.
Report errors using SYCL exception classes.
Definition at line 256 of file queue.hpp.
{
    return implementation->get_device();
  }
References trisycl::detail::shared_ptr_implementation< queue, detail::queue >::implementation.
get_info()
template<info::queue param> auto trisycl::queue::get_info () const inline
Queries the platform for cl_command_queue info.
get_property()
template<typename propertyT > propertyT trisycl::queue::get_property () const inline
Return a copy of the property that the queue was constructed with.
Definition at line 355 of file queue.hpp.
{
    return property_list::get_property<propertyT>();
  }
has_property()
template<typename propertyT > bool trisycl::queue::has_property () const inline
Check if the queue was constructed with the specified property.
Definition at line 347 of file queue.hpp.
{
    return property_list::has_property<propertyT>();
  }
is_host()
bool trisycl::queue::is_host () const inline
Return whether the queue is executing on a SYCL host device.
Definition at line 262 of file queue.hpp.
                       {
    return implementation->is_host();
  }
References trisycl::detail::shared_ptr_implementation< queue, detail::queue >::implementation.
submit() [1/2]
template<typename Handler_Functor > event trisycl::queue::submit (Handler_Functor cgf) inline
Submit a command group functor to the queue, in order to be scheduled for execution on the device.
Use an explicit functor parameter taking a handler& so we can use "auto" in submit() lambda parameter.
Todo:
Add in the spec an implicit conversion of event to queue& so it is possible to chain operations on the queue
Definition at line 320 of file queue.hpp.
{
    handler command_group_handler { implementation };
    cgf(command_group_handler);
    return {};
  }
References trisycl::detail::shared_ptr_implementation< queue, detail::queue >::implementation.
Referenced by submit().
submit() [2/2]
template<typename Handler_Functor > event trisycl::queue::submit (Handler_Functor cgf, queue & secondaryQueue) inline
Submit a command group functor to the queue, in order to be scheduled for execution on the device.
On kernel error, this command group functor, then it is scheduled for execution on the secondary queue.
Return a command group functor event, which is corresponds to the queue the command group functor is being enqueued on.
Definition at line 337 of file queue.hpp.
{
    TRISYCL_UNIMPL;
    // Since it is not implemented, always submit on the main queue
    return submit(cgf);
  }
References submit(), and TRISYCL_UNIMPL.
throw_asynchronous()
void trisycl::queue::throw_asynchronous () inline
Checks to see if any asynchronous errors have been produced by the queue and if so reports them by passing them to the async_handler passed to the queue on construction.
If no async_handler was provided then asynchronous exceptions will be lost.
Definition at line 301 of file queue.hpp.
{
    TRISYCL_UNIMPL;
  }
References TRISYCL_UNIMPL.
wait()
void trisycl::queue::wait () inline
Performs a blocking wait for the completion all enqueued tasks in the queue.
Synchronous errors will be reported through SYCL exceptions.
Definition at line 272 of file queue.hpp.
              {
    implementation->wait_for_kernel_execution();
  }
References trisycl::detail::shared_ptr_implementation< queue, detail::queue >::implementation.
Referenced by wait_and_throw().
wait_and_throw()
void trisycl::queue::wait_and_throw () inline
Perform a blocking wait for the completion all enqueued tasks in the queue.
Synchronous errors will be reported via SYCL exceptions.
Asynchronous errors will be passed to the async_handler passed to the queue on construction.
If no async_handler was provided then asynchronous exceptions will be lost.
Definition at line 287 of file queue.hpp.
{
    // \todo Implement the throw part of wait_and_throw
    wait();
    TRISYCL_UNIMPL;
  }
References TRISYCL_UNIMPL, and wait().
Member Data Documentation
implementation_t
friend trisycl::queue::implementation_t private
Definition at line 67 of file queue.hpp.
Macro Definition Documentation
PLATFORM_GET_INFO_STRING
#define PLATFORM_GET_INFO_STRING (X)
#include <include/triSYCL/platform.hpp>
Value:
template<>                          \
inline auto platform::get_info<info::platform::X>() const { \
  return implementation->get_info_string(info::platform::X);    \
}
Definition at line 166 of file platform.hpp.
Typedef Documentation
cpu_selector
using trisycl::cpu_selector = typedef device_typename_selector<info::device_type::cpu>
#include <include/triSYCL/device_selector/detail/device_selector_tail.hpp>
Select devices according to device type info::device::device_type::cpu from all the available devices and heuristics.
If no OpenCL CPU device is found the selector fails.
Definition at line 155 of file device_selector_tail.hpp.
default_selector
using trisycl::default_selector = typedef device_typename_selector<info::device_type::automatic>
#include <include/triSYCL/device_selector/detail/device_selector_tail.hpp>
Devices selected by heuristics of the system.
If no OpenCL device is found then it defaults to the SYCL host device.
To influence the default device selection, use the Boost.Compute environment variables:
BOOST_COMPUTE_DEFAULT_DEVICE
BOOST_COMPUTE_DEFAULT_DEVICE_TYPE
BOOST_COMPUTE_DEFAULT_PLATFORM
BOOST_COMPUTE_DEFAULT_VENDOR
Definition at line 137 of file device_selector_tail.hpp.
device_exec_capabilities
using trisycl::info::device_exec_capabilities = typedef unsigned int
#include <include/triSYCL/info/device.hpp>
Definition at line 180 of file device.hpp.
device_fp_config
using trisycl::info::device_fp_config = typedef unsigned int
#include <include/triSYCL/info/device.hpp>
Definition at line 179 of file device.hpp.
device_queue_properties
using trisycl::info::device_queue_properties = typedef unsigned int
#include <include/triSYCL/info/device.hpp>
Definition at line 181 of file device.hpp.
gpu_selector
using trisycl::gpu_selector = typedef device_typename_selector<info::device_type::gpu>
#include <include/triSYCL/device_selector/detail/device_selector_tail.hpp>
Select devices according to device type info::device::device_type::gpu from all the available OpenCL devices.
If no OpenCL GPU device is found the selector fails.
Select the best GPU, if any.
Definition at line 147 of file device_selector_tail.hpp.
host_selector
using trisycl::host_selector = typedef device_typename_selector<info::device_type::host>
#include <include/triSYCL/device_selector/detail/device_selector_tail.hpp>
Selects the SYCL host CPU device that does not require an OpenCL runtime.
Definition at line 161 of file device_selector_tail.hpp.
Enumeration Type Documentation
context
enum class trisycl::info::context : int strong
#include <include/triSYCL/info/context.hpp>
Context information descriptors.
Todo:
Should be unsigned int to be consistent with others?
Enumerator
reference_count
platform
devices
Definition at line 25 of file context.hpp.
                   : int {
  reference_count,
  platform,
  devices
};
device
enum class trisycl::info::device : int strong
#include <include/triSYCL/info/device.hpp>
Device information descriptors.
From specs/latex/headers/deviceInfo.h in the specification
Todo:
Should be unsigned int?
Enumerator
device_type
vendor_id
max_compute_units
max_work_item_dimensions
max_work_item_sizes
max_work_group_size
preferred_vector_width_char
preferred_vector_width_short
preferred_vector_width_int
preferred_vector_width_long
preferred_vector_width_float
preferred_vector_width_double
preferred_vector_width_half
native_vector_width_char
native_vector_width_short
native_vector_width_int
native_vector_width_long
native_vector_width_float
native_vector_width_double
native_vector_width_half
max_clock_frequency
address_bits
max_mem_alloc_size
image_support
max_read_image_args
max_write_image_args
image2d_max_width
image2d_max_height
image3d_max_width
image3d_max_height
image3d_max_depth
image_max_buffer_size
image_max_array_size
max_samplers
max_parameter_size
mem_base_addr_align
half_fp_config
single_fp_config
double_fp_config
global_mem_cache_type
global_mem_cache_line_size
global_mem_cache_size
global_mem_size
max_constant_buffer_size
max_constant_args
local_mem_type
local_mem_size
error_correction_support
host_unified_memory
profiling_timer_resolution
is_endian_little
is_available
is_compiler_available
is_linker_available
execution_capabilities
queue_profiling
built_in_kernels
platform
name
vendor
driver_version
profile
version
opencl_c_version
extensions
printf_buffer_size
preferred_interop_user_sync
parent_device
partition_max_sub_devices
partition_properties
partition_affinity_domains
partition_type_property
partition_type_affinity_domain
reference_count
Definition at line 56 of file device.hpp.
                  : int {
  device_type,
  vendor_id,
  max_compute_units,
  max_work_item_dimensions,
  max_work_item_sizes,
  max_work_group_size,
  preferred_vector_width_char,
  preferred_vector_width_short,
  preferred_vector_width_int,
  preferred_vector_width_long,
  preferred_vector_width_float,
  preferred_vector_width_double,
  preferred_vector_width_half,
  native_vector_width_char,
  native_vector_width_short,
  native_vector_width_int,
  native_vector_width_long,
  native_vector_width_float,
  native_vector_width_double,
  native_vector_width_half,
  max_clock_frequency,
  address_bits,
  max_mem_alloc_size,
  image_support,
  max_read_image_args,
  max_write_image_args,
  image2d_max_width,
  image2d_max_height,
  image3d_max_width,
  image3d_max_height,
  image3d_max_depth,
  image_max_buffer_size,
  image_max_array_size,
  max_samplers,
  max_parameter_size,
  mem_base_addr_align,
  half_fp_config,
  single_fp_config,
  double_fp_config,
  global_mem_cache_type,
  global_mem_cache_line_size,
  global_mem_cache_size,
  global_mem_size,
  max_constant_buffer_size,
  max_constant_args,
  local_mem_type,
  local_mem_size,
  error_correction_support,
  host_unified_memory,
  profiling_timer_resolution,
  is_endian_little,
  is_available,
  is_compiler_available,
  is_linker_available,
  execution_capabilities,
  queue_profiling,
  built_in_kernels,
  platform,
  name,
  vendor,
  driver_version,
  profile,
  version,
  opencl_c_version,
  extensions,
  printf_buffer_size,
  preferred_interop_user_sync,
  parent_device,
  partition_max_sub_devices,
  partition_properties,
  partition_affinity_domains,
  partition_type_property,
  partition_type_affinity_domain,
  reference_count
};
device_type
enum class trisycl::info::device_type : unsigned int strong
#include <include/triSYCL/info/device.hpp>
Type of devices.
To be used either to define a device type or to select more broadly a kind of device
Todo:
To be moved in the specification from platform to device
Todo:
Add opencl to the specification
Todo:
there is no accelerator_selector and custom_accelerator
Enumerator
cpu
gpu
accelerator
custom
automatic
host
opencl
all
Definition at line 38 of file device.hpp.
                       : unsigned int {
  cpu,
  gpu,
  accelerator,
  custom,
  automatic,
  host,
  opencl,
  all
};
execution_capability
enum class trisycl::info::execution_capability : unsigned int strong
#include <include/triSYCL/info/device.hpp>
Enumerator
exec_kernel
exec_native_kernel
Definition at line 173 of file device.hpp.
                                : unsigned int {
  exec_kernel,
  exec_native_kernel
};
fp_config
enum class trisycl::info::fp_config : int strong
#include <include/triSYCL/info/device.hpp>
Enumerator
denorm
inf_nan
round_to_nearest
round_to_zero
round_to_inf
fma
correctly_rounded_divide_sqrt
soft_float
Definition at line 156 of file device.hpp.
                     : int {
  denorm,
  inf_nan,
  round_to_nearest,
  round_to_zero,
  round_to_inf,
  fma,
  correctly_rounded_divide_sqrt,
  soft_float
};
global_mem_cache_type
enum class trisycl::info::global_mem_cache_type : int strong
#include <include/triSYCL/info/device.hpp>
Enumerator
none
read_only
write_only
Definition at line 167 of file device.hpp.
                                 : int {
  none,
  read_only,
  write_only
};
local_mem_type
enum class trisycl::info::local_mem_type : int strong
#include <include/triSYCL/info/device.hpp>
Enumerator
none
local
global
Definition at line 150 of file device.hpp.
                          : int {
  none,
  local,
  global
};
partition_affinity_domain
enum class trisycl::info::partition_affinity_domain : int strong
#include <include/triSYCL/info/device.hpp>
Enumerator
not_applicable
numa
L4_cache
L3_cache
L2_cache
L1_cache
next_partitionable
Definition at line 140 of file device.hpp.
                                     : int {
  not_applicable,
  numa,
  L4_cache,
  L3_cache,
  L2_cache,
  L1_cache,
  next_partitionable
};
partition_property
enum class trisycl::info::partition_property : int strong
#include <include/triSYCL/info/device.hpp>
Enumerator
no_partition
partition_equally
partition_by_counts
partition_by_affinity_domain
Definition at line 133 of file device.hpp.
                              : int {
  no_partition,
  partition_equally,
  partition_by_counts,
  partition_by_affinity_domain,
};
platform
enum class trisycl::info::platform : unsigned int strong
#include <include/triSYCL/info/platform.hpp>
Platform information descriptors.
A SYCL platform can be queried for all of the following information using the get_info function.
In this implementation, the values are mapped to OpenCL values to avoid further remapping later when OpenCL is used
Enumerator
TRISYCL_OPENCL_ONLY
Returns the profile name (as a string_class) supported by the implementation.
Can be either FULL PROFILE or EMBEDDED PROFILE.
TRISYCL_OPENCL_ONLY
Returns the OpenCL software driver version string in the form major number.minor number (as a string_class)
TRISYCL_OPENCL_ONLY
Returns the name of the platform (as a string_class)
TRISYCL_OPENCL_ONLY
Returns the string provided by the platform vendor (as a string_class)
TRISYCL_OPENCL_ONLY
Returns a space-separated list of extension names supported by the platform (as a string_class)
Definition at line 30 of file platform.hpp.
                    : unsigned int {
  /** Returns the profile name (as a string_class) supported by the
      implementation.
      Can be either FULL PROFILE or EMBEDDED PROFILE.
  */
  profile TRISYCL_OPENCL_ONLY(= CL_PLATFORM_PROFILE),
  /** Returns the OpenCL software driver version string in the form major
      number.minor number (as a string_class)
  */
  version TRISYCL_OPENCL_ONLY(= CL_PLATFORM_VERSION),
  /** Returns the name of the platform (as a string_class)
  */
  name TRISYCL_OPENCL_ONLY(= CL_PLATFORM_NAME),
  /** Returns the string provided by the platform vendor (as a string_class)
  */
  vendor TRISYCL_OPENCL_ONLY(= CL_PLATFORM_VENDOR),
  /** Returns a space-separated list of extension names supported by the
      platform (as a string_class)
  */
  extensions TRISYCL_OPENCL_ONLY(= CL_PLATFORM_EXTENSIONS),
#if CL_SYCL_LANGUAGE_VERSION >= 220 && defined(CL_VERSION_2_1)
  /** Returns the resolution of the host timer in nanoseconds as used by
      clGetDeviceAndHostTimer
  */
  host_timer_resolution
    TRISYCL_OPENCL_ONLY(= CL_PLATFORM_HOST_TIMER_RESOLUTION)
#endif
};
Function Documentation
context::get_info< info::context::devices >()
template<> auto trisycl::context::get_info< info::context::devices > () const inline
#include <include/triSYCL/context.hpp>
Definition at line 223 of file context.hpp.
{
  return get_devices();
}
context::get_info< info::context::platform >()
template<> auto trisycl::context::get_info< info::context::platform > () const inline
#include <include/triSYCL/context.hpp>
Definition at line 218 of file context.hpp.
{
  return get_platform();
}
context::get_info< info::context::reference_count >()
template<> auto trisycl::context::get_info< info::context::reference_count > () const inline
#include <include/triSYCL/context.hpp>
Definition at line 213 of file context.hpp.
{
  return implementation->get_reference_count();
}
get_devices() [1/2]
vector_class<::trisycl::device > trisycl::detail::host_platform::get_devices (const device_selector & device_selector) const inline override virtual
#include <include/triSYCL/platform/detail/host_platform.hpp>
Get all the available devices for the host platform.
Get all the available devices for this platform.
Parameters
[in] device_type is the device type to filter the selection or info::device_type::all by default to return all the devices
Returns
the device list
If get_devices is called with the host platform and the right device type, returns the host_device.
Implements trisycl::detail::platform.
Definition at line 29 of file host_platform_tail.hpp.
{
  /** If \c get_devices is called with the host platform
      and the right device type, returns the host_device.
  */
  if (device_selector(::trisycl::device {}) > 0)
    // Return 1 default device, i.e. the host device
    return { {} };
  else
    // No matching device
    return {};
}
get_devices() [2/2]
vector_class<::trisycl::device > trisycl::detail::opencl_platform::get_devices (const device_selector & device_selector) const inline override virtual
#include <include/triSYCL/platform/detail/opencl_platform.hpp>
Get all the available devices for this OpenCL platform.
Returns a vector class containing all SYCL devices associated with this OpenCL platform.
Parameters
[in] device_type is the device type to filter the selection or info::device_type::all by default to return all the devices
Returns
the device list
Implements trisycl::detail::platform.
Definition at line 30 of file opencl_platform_tail.hpp.
{
  vector_class<::trisycl::device> devices;
  // Add the desired OpenCL devices
  for (const auto &d : get_boost_compute().devices()) {
    // Get the SYCL device from the Boost Compute device
    ::trisycl::device sycl_dev { d };
    /* Return the devices with the good criterion according to the selector.
       By calling devices on the \c boost::compute::platform we know that
       we iterate only over the device belonging to the current platform,
    */
    if (device_selector(sycl_dev) > 0)
      devices.push_back(sycl_dev);
  }
  return devices;
}
References trisycl::detail::opencl_platform::get_boost_compute().
platform::get_info< info::platform::extensions >()
template<> auto trisycl::platform::get_info< info::platform::extensions > () const inline
#include <include/triSYCL/platform.hpp>
Definition at line 162 of file platform.hpp.
{
  return implementation->get_extension_strings();
}
queue::get_info< info::queue::context >()
template<> auto trisycl::queue::get_info< info::queue::context > () const inline
#include <include/triSYCL/queue.hpp>
Definition at line 366 of file queue.hpp.
{
  return implementation->get_context();
}
queue::get_info< info::queue::device >()
template<> auto trisycl::queue::get_info< info::queue::device > () const inline
#include <include/triSYCL/queue.hpp>
Definition at line 361 of file queue.hpp.
{
  return implementation->get_device();
}
queue::get_info< info::queue::reference_count >()
template<> auto trisycl::queue::get_info< info::queue::reference_count > () const inline
#include <include/triSYCL/queue.hpp>
Definition at line 371 of file queue.hpp.
{
  return trisycl::cl_uint {0};
}
select_device() [1/2]
device trisycl::device_selector::select_device () const inline
#include <include/triSYCL/device_selector.hpp>
Returns a selected device using the functor operator defined in sub-classes operator()(const device &dev)
Todo:
Remove this from specification
Definition at line 46 of file device_selector_tail.hpp.
{
  return select_device(platform::get_platforms());
}
References trisycl::platform::get_platforms(), and trisycl::device_selector::select_device().
Referenced by trisycl::device_selector::select_device().
select_device() [2/2]
device trisycl::device_selector::select_device (vector_class< platform > platforms) const inline private
#include <include/triSYCL/device_selector.hpp>
Definition at line 25 of file device_selector_tail.hpp.
{
  int best_id = -1;
  int best_score = -1;
  device best_device;
  for (auto &platform : platforms) {
    for (auto &dev : platform.get_devices()) {
      int score = operator()(dev);
      if (score > best_score) {
        best_id = 1;
        best_device = dev;
        best_score = score;
      }
    }
  }
  if (best_id == -1)
    throw ::trisycl::runtime_error("Could not find device");
  return best_device;
}
References trisycl::platform::get_devices(), and trisycl::device_selector::operator()().
Referenced by trisycl::context::context().
TRISYCL_INFO_PARAM_TRAITS() [1/7]
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image2d_max_height , size_t)
#include <include/triSYCL/info/device.hpp>
TRISYCL_INFO_PARAM_TRAITS() [2/7]
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image2d_max_width , size_t)
#include <include/triSYCL/info/device.hpp>
Query the return type for get_info() on context stuff.
Todo:
To be implemented, return always void.
TRISYCL_INFO_PARAM_TRAITS() [3/7]
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image3d_max_depth , size_t)
#include <include/triSYCL/info/device.hpp>
TRISYCL_INFO_PARAM_TRAITS() [4/7]
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image3d_max_height , size_t)
#include <include/triSYCL/info/device.hpp>
TRISYCL_INFO_PARAM_TRAITS() [5/7]
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image3d_max_width , size_t)
#include <include/triSYCL/info/device.hpp>
TRISYCL_INFO_PARAM_TRAITS() [6/7]
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image_max_array_size , size_t)
#include <include/triSYCL/info/device.hpp>
TRISYCL_INFO_PARAM_TRAITS() [7/7]
trisycl::info::TRISYCL_INFO_PARAM_TRAITS (info::device::image_max_buffer_size , size_t)
#include <include/triSYCL/info/device.hpp>
Variable Documentation
TRISYCL_WEAK_ATTRIB_SUFFIX
TRISYCL_WEAK_ATTRIB_PREFIX detail::cache< cl_command_queue, detail::opencl_queue > opencl_queue::cache trisycl::detail::TRISYCL_WEAK_ATTRIB_SUFFIX
#include <include/triSYCL/context/detail/opencl_context.hpp>
Definition at line 146 of file opencl_context.hpp.