triSYCL implementation of OpenCL SYCL: Debugging and tracing support
Debugging and tracing support
Classes
struct cl::sycl::detail::debug< T >
Class used to trace the construction, copy-construction, move-construction and destruction of classes that inherit from it.
struct cl::sycl::detail::display_vector< T >
Class used to display a vector-like type of classes that inherit from it.
Functions
void cl::sycl::detail::unimplemented ()
Display an "unimplemented" message.
Detailed Description
Class Documentation
struct cl::sycl::detail::debug
template<typename T>
struct cl::sycl::detail::debug< T >
Class used to trace the construction, copy-construction, move-construction and destruction of classes that inherit from it.
Parameters
T is the real type name to be used in the debug output.
Definition at line 62 of file debug.hpp.
Public Member Functions
debug ()
Trace the construction with the compiler-dependent mangled named.
debug (debug const &)
Trace the copy construction with the compiler-dependent mangled named.
debug (debug &&)
Trace the move construction with the compiler-dependent mangled named.
~debug ()
Trace the destruction with the compiler-dependent mangled named.
Constructor & Destructor Documentation
template<typename T> cl::sycl::detail::debug< T >::debug () inline
Trace the construction with the compiler-dependent mangled named.
Definition at line 65 of file debug.hpp.
           {
     TRISYCL_DUMP("Constructor of " << typeid(*this).name()
                  << " " << (void*) this);
   }
template<typename T> cl::sycl::detail::debug< T >::debug (debug< T > const &) inline
Trace the copy construction with the compiler-dependent mangled named.
Definition at line 73 of file debug.hpp.
{
     TRISYCL_DUMP("Copy of " << typeid(*this).name() << " " << (void*) this);
   }
template<typename T> cl::sycl::detail::debug< T >::debug (debug< T > &&) inline
Trace the move construction with the compiler-dependent mangled named.
Definition at line 80 of file debug.hpp.
                   {
     TRISYCL_DUMP("Move of " << typeid(*this).name() << " " << (void*) this);
   }
template<typename T> cl::sycl::detail::debug< T >::~debug () inline
Trace the destruction with the compiler-dependent mangled named.
Definition at line 86 of file debug.hpp.
            {
     TRISYCL_DUMP("~ Destructor of " << typeid(*this).name()
                  << " " << (void*) this);
   }
struct cl::sycl::detail::display_vector
template<typename T>
struct cl::sycl::detail::display_vector< T >
Class used to display a vector-like type of classes that inherit from it.
Parameters
T is the real type name to be used in the debug output.
Calling the display() method dump the values on std::cout
Definition at line 102 of file debug.hpp.
Public Member Functions
void display () const
To debug and test.
Member Function Documentation
template<typename T> void cl::sycl::detail::display_vector< T >::display () const inline
To debug and test.
Definition at line 105 of file debug.hpp.
Referenced by cl::sycl::nd_range< dims >::display().
{
 #ifdef TRISYCL_DEBUG
     std::cout << typeid(T).name() << ":";
 #endif
     // Get a pointer to the real object
     for (auto e : *static_cast<const T *>(this))
       std::cout << " " << e;
     std::cout << std::endl;
   }
Function Documentation
void cl::sycl::detail::unimplemented () inline
#include <include/CL/sycl/detail/unimplemented.hpp>
Display an "unimplemented" message.
Can be changed to call assert(0) or whatever.
Definition at line 25 of file unimplemented.hpp.
Referenced by cl::sycl::nd_item< dims >::barrier(), cl::sycl::context::context(), cl::sycl::device::create_sub_devices(), cl::sycl::device::device(), cl::sycl::platform::get(), cl::sycl::context::get(), cl::sycl::queue::get(), cl::sycl::device::get(), cl::sycl::queue::get_context(), cl::sycl::queue::get_device(), cl::sycl::platform::get_devices(), cl::sycl::context::get_devices(), cl::sycl::device::get_devices(), cl::sycl::platform::get_info(), cl::sycl::context::get_info(), cl::sycl::queue::get_info(), cl::sycl::device::get_info(), cl::sycl::device::get_platform(), cl::sycl::platform::get_platforms(), cl::sycl::platform::has_extension(), cl::sycl::device::has_extension(), cl::sycl::device::is_accelerator(), cl::sycl::device::is_cpu(), cl::sycl::device::is_gpu(), cl::sycl::queue::is_host(), cl::sycl::device::is_host(), cl::sycl::default_selector::operator()(), cl::sycl::gpu_selector::operator()(), cl::sycl::cpu_selector::operator()(), cl::sycl::host_selector::operator()(), cl::sycl::handler::parallel_for(), cl::sycl::platform::platform(), cl::sycl::queue::queue(), cl::sycl::device_selector::select_device(), cl::sycl::handler::set_arg(), cl::sycl::handler::single_task(), cl::sycl::queue::submit(), cl::sycl::queue::throw_asynchronous(), cl::sycl::queue::wait(), and cl::sycl::queue::wait_and_throw().
{
   std::cerr << "Error: using a non implemented feature!!!" << std::endl
             << "Please contribute to the open source implementation. :-)"
             << std::endl;
 }