triSYCL implementation of SYCL: Device-side runtime implementation
Device-side runtime implementation
Namespaces
cl::sycl::drt
The device-side runtime.
cl::sycl::drt::code
The binary code of the kernels.
Classes
class cl::sycl::drt::accessor< Accessor >
SYCL accessor seen from a device perspective.
Functions
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::serialize_arg (detail::task &task, std::size_t index, void *arg, std::size_t arg_size)
Set an argument value of the kernel.
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::serialize_accessor_arg (detail::task &task, std::size_t index, void *arg, std::size_t arg_size)
Set an accessor argument of the kernel.
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::set_kernel (detail::task &task, const char *kernel_name, const char *kernel_short_name)
Set the kernel for a later invocation.
Variables
TRISYCL_WEAK_ATTRIB_PREFIX std::map< std::string, std::vector< unsigned char > > TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::kernel_IR
The code of the kernels arranged by name.
Detailed Description
Class Documentation
cl::sycl::drt::accessor
class cl::sycl::drt::accessor
template<typename Accessor>
class cl::sycl::drt::accessor< Accessor >
SYCL accessor seen from a device perspective.
Definition at line 53 of file device_runtime.hpp.
Public Member Functions
accessor (Accessor &a)
Capture the minimal accessor features.
auto & operator[] (std::size_t index) const noexcept
use the accessor with integers à la []
Private Attributes
TRISYCL_GLOBAL_AS Accessor::value_type * buffer
The pointer to the data.
std::size_t size
The size of the accessor.
Additional Inherited Members
Public Types inherited from cl::sycl::detail::container_element_aspect< Accessor::value_type >
using value_type = Accessor::value_type
using pointer = value_type *
using const_pointer = const value_type *
using reference = value_type &
using const_reference = const value_type &
Constructor & Destructor Documentation
accessor()
template<typename Accessor > cl::sycl::drt::accessor< Accessor >::accessor (Accessor & a) inline
Capture the minimal accessor features.
Definition at line 77 of file device_runtime.hpp.
References a, TRISYCL_DUMP_T, and TRISYCL_GLOBAL_AS.
                         :
     /* Initialize the buffer with actually a \c cl_mem since it will be
        overridden with the kernel argument by the serializer at
        run-time, but at least from the kernel point of view it has to
        look like an \c Accessor::value_type * for the kernel
        outlining */
     buffer {
       reinterpret_cast<TRISYCL_GLOBAL_AS typename Accessor::value_type *>
         (a.implementation->get_order())
         },
     size { a.get_count() }
   {
 #ifndef TRISYCL_DEVICE
     /* Register the buffer address to be updated with the final
        version before the kernel set arg */
     TRISYCL_DUMP_T("drt::accessor(Accessor &a) : &a = "
                    << (void *) &a << '\n'
                    << "\t&buffer = " << (void *) &buffer
                    << ", Order = " << a.implementation->get_order());
 #endif
   }
Member Function Documentation
operator[]()
template<typename Accessor > auto& cl::sycl::drt::accessor< Accessor >::operator[] (std::size_t index) const inline noexcept
use the accessor with integers à la []
Definition at line 101 of file device_runtime.hpp.
References TRISYCL_WEAK_ATTRIB_PREFIX, and TRISYCL_WEAK_ATTRIB_SUFFIX.
{
     return buffer[index];
   }
Member Data Documentation
buffer
template<typename Accessor > TRISYCL_GLOBAL_AS Accessor::value_type* cl::sycl::drt::accessor< Accessor >::buffer private
The pointer to the data.
For now none of the following works yet for various reasons:
 cl::sycl::global_ptr<typename Accessor::value_type> buffer;
 cl::sycl::global<typename Accessor::value_type *> buffer;
__global typename Accessor::pointer buffer;
So use a more trivial approach
Definition at line 67 of file device_runtime.hpp.
size
template<typename Accessor > std::size_t cl::sycl::drt::accessor< Accessor >::size private
The size of the accessor.
The compiler should optimize it out if it is unused
Definition at line 72 of file device_runtime.hpp.
Function Documentation
serialize_accessor_arg()
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::serialize_accessor_arg (detail::task & task, std::size_t index, void * arg, std::size_t arg_size)
#include <include/CL/sycl/device_runtime.hpp>
Set an accessor argument of the kernel.
Parameters
[in] task is the implementation detail of a triSYCL kernel
[in] index is the order of the argument to set (0 is the first one)
[in] arg points to the argument value
[in] arg_size is the size of the argument
Definition at line 140 of file device_runtime.hpp.
References cl::sycl::detail::task::get_compute_buffer(), cl::sycl::detail::task::set_arg(), and TRISYCL_DUMP_T.
{
   TRISYCL_DUMP_T("serialize_accessor_arg index = " << index
                  << ", size = " << arg_size << ", arg = " << arg);
 #ifdef TRISYCL_OPENCL
   /* The address of the argument has been actually initialized by the
      accessor constructor to the accessor order to relate an argument
      to its accessor */
   task.set_arg(index,
                task.get_compute_buffer(reinterpret_cast<std::size_t>(arg)));
 #endif
 }
serialize_arg()
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::serialize_arg (detail::task & task, std::size_t index, void * arg, std::size_t arg_size)
#include <include/CL/sycl/device_runtime.hpp>
Set an argument value of the kernel.
Parameters
[in] task is the implementation detail of a triSYCL kernel
[in] index is the order of the argument to set (0 is the first one)
[in] arg points to the argument value
[in] arg_size is the size of the argument
Definition at line 119 of file device_runtime.hpp.
References cl::sycl::detail::task::set_arg(), TRISYCL_DUMP_T, TRISYCL_WEAK_ATTRIB_PREFIX, and TRISYCL_WEAK_ATTRIB_SUFFIX.
{
   TRISYCL_DUMP_T("serialize_arg index = " << index
                  << ", size = " << arg_size << ", arg = " << arg);
   task.set_arg(index, arg_size, arg);
 }
set_kernel()
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::set_kernel (detail::task & task, const char * kernel_name, const char * kernel_short_name)
#include <include/CL/sycl/device_runtime.hpp>
Set the kernel for a later invocation.
Parameters
[in] task is the implementation detail of a triSYCL kernel
[in] kernel_name is set by the device compiler to identify the kernel to call
Definition at line 201 of file device_runtime.hpp.
References cl::sycl::detail::task::get_queue(), cl::sycl::drt::code::program::p, cl::sycl::detail::task::set_kernel(), and TRISYCL_DUMP_T.
{
   TRISYCL_DUMP_T("set_kernel setting up " << kernel_name
                  << "\n\taka " << kernel_short_name);
   // \todo Add kernel caching per device
   // auto binary = kernel_IR.find(kernel_name);
   // if (binary == kernel_IR.end()) {
 #ifdef TRISYCL_OPENCL
   auto context = task.get_queue()->get_boost_compute().get_context();
   // Construct an OpenCL program from the precompiled kernel file
   auto
 #ifdef SDX_KERNEL_PROGRAM_OWNING_BUG
     /* There is a bug in Xilinx OpenCL runtime where the cl_kernel
        does not keep alive its own cl_program */
     static
 #endif
     program = boost::compute::program::create_with_binary
     (code::program::p->binary,
      code::program::p->binary_size,
      context);
   TRISYCL_DUMP_T("...on device with name "
                  << task.get_queue()->get_boost_compute().get_device().name());
   // Build the OpenCL program
   program.build();
   // Build a SYCL kernel from the OpenCL kernel
   cl::sycl::kernel k { boost::compute::kernel { program, kernel_short_name } };
   task.set_kernel(k.implementation);
 #endif
 }
Variable Documentation
kernel_IR
TRISYCL_WEAK_ATTRIB_PREFIX std::map<std::string, std::vector<unsigned char> > TRISYCL_WEAK_ATTRIB_SUFFIX cl::sycl::drt::kernel_IR
#include <include/CL/sycl/device_runtime.hpp>
The code of the kernels arranged by name.
Todo:
use std::byte when moving to C++17
Definition at line 190 of file device_runtime.hpp.