triSYCL implementation of SYCL: Data access and storage in SYCL
Data access and storage in SYCL
Namespaces
trisycl::access
Describe the type of access by kernels.
Classes
class trisycl::detail::accessor_base
The buffer accessor base is here mainly to be accessed from the task without dependency on the buffer data types.
class trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >
The local accessor specialization abstracts the way local memory is allocated to a kernel to be shared between work-items of the same work-group.
class trisycl::accessor< DataType, Dimensions, AccessMode, Target >
The accessor abstracts the way buffer or pipe data are accessed inside a kernel in a multidimensional variable length array way.
class trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
class trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
class trisycl::detail::accessor< T, Dimensions, Mode, Target >
The buffer accessor abstracts the way buffer data are accessed inside a kernel in a multidimensional variable length array way.
class trisycl::detail::buffer< T, Dimensions >
A SYCL buffer is a multidimensional variable length array (à la C99 VLA or even Fortran before) that is used to store data to work on.
struct trisycl::detail::buffer_base
Factorize some template independent buffer aspects in a base class.
class trisycl::detail::buffer_waiter< T, Dimensions, Allocator >
A helper class to wait for the final buffer destruction if the conditions for blocking are met.
class trisycl::buffer< T, Dimensions, Allocator >
A SYCL buffer is a multidimensional variable length array (à la C99 VLA or even Fortran before) that is used to store data to work on.
struct trisycl::image< Dimensions >
struct trisycl::detail::reserve_id< T >
A private description of a reservation station.
class trisycl::detail::pipe< T >
Implement a pipe object.
class trisycl::detail::pipe_accessor< T, AccessMode, Target >
The accessor abstracts the way pipe data are accessed inside a kernel.
class trisycl::pipe< T >
A SYCL pipe.
class trisycl::detail::pipe_reservation< PipeAccessor >
The implementation of the pipe reservation station.
struct trisycl::pipe_reservation< PipeAccessor >
The pipe reservation station allows to reserve an array-like view inside the pipe for ordered race-free access from various work-items for example.
class trisycl::static_pipe< T, Capacity >
A SYCL static-scoped pipe equivalent to an OpenCL program-scoped pipe.
Typedefs
template<typename T >
using trisycl::buffer_allocator = std::allocator< T >
The allocator objects give the programmer some control on how the memory is allocated inside SYCL.
template<typename T >
using trisycl::image_allocator = std::allocator< T >
The allocator used for the image inside SYCL.
template<typename T >
using trisycl::map_allocator = std::allocator< T >
The allocator used to map the memory at the same place.
Functions
template<typename Accessor >
static auto & trisycl::get_pipe_detail (Accessor &a)
Top-level function to break circular dependencies on the the types to get the pipe implementation.
template<typename BufferDetail >
static std::shared_ptr< detail::task > trisycl::detail::buffer_add_to_task (BufferDetail buf, handler *command_group_handler, bool is_write_mode)
Proxy function to avoid some circular type recursion.
static std::shared_ptr< detail::task > trisycl::detail::add_buffer_to_task (handler *command_group_handler, std::shared_ptr< detail::buffer_base > b, bool is_write_mode)
template<typename T , int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>>
auto trisycl::detail::waiter (detail::buffer< T, Dimensions > *b)
Helper function to create a new buffer_waiter.
Detailed Description
Class Documentation
trisycl::detail::accessor_base
class trisycl::detail::accessor_base
The buffer accessor base is here mainly to be accessed from the task without dependency on the buffer data types.
Definition at line 38 of file accessor_base.hpp.
Public Member Functions
void set_order (std::size_t o)
Set the order of the accessor.
auto get_order ()
Get the order of the accessor.
virtual boost::compute::buffer get_cl_buffer () const =0
Get the boost::compute::buffer or throw if unset.
virtual ~accessor_base ()
Protected Attributes
std::shared_ptr< detail::task > task
The task where the accessor is used in.
std::size_t order
The declaration order of the accessor.
Constructor & Destructor Documentation
~accessor_base()
virtual trisycl::detail::accessor_base::~accessor_base () inline virtual
Definition at line 67 of file accessor_base.hpp.
 {}
Member Function Documentation
get_cl_buffer()
virtual boost::compute::buffer trisycl::detail::accessor_base::get_cl_buffer () const pure virtual
Get the boost::compute::buffer or throw if unset.
Implemented in trisycl::detail::accessor< T, Dimensions, Mode, Target >.
Referenced by get_order().
get_order()
auto trisycl::detail::accessor_base::get_order () inline
Get the order of the accessor.
Definition at line 57 of file accessor_base.hpp.
References get_cl_buffer(), and order.
                    {
     return order;
   }
set_order()
void trisycl::detail::accessor_base::set_order (std::size_t o) inline
Set the order of the accessor.
Definition at line 51 of file accessor_base.hpp.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::register_accessor().
{
     order = o;
   }
Member Data Documentation
order
std::size_t trisycl::detail::accessor_base::order protected
The declaration order of the accessor.
Definition at line 46 of file accessor_base.hpp.
Referenced by get_order().
task
std::shared_ptr<detail::task> trisycl::detail::accessor_base::task protected
The task where the accessor is used in.
Definition at line 43 of file accessor_base.hpp.
trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >
class trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >
template<typename T, int Dimensions, access::mode Mode>
class trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >
The local accessor specialization abstracts the way local memory is allocated to a kernel to be shared between work-items of the same work-group.
Todo:
Use the access::mode
Definition at line 53 of file local_accessor.hpp.
Public Types
using value_type = T
using element = T
using reference = typename array_type::reference
using const_reference = typename array_type::const_reference
using iterator = typename array_type::iterator
Inherit the iterator types from the implementation.
using const_iterator = typename array_type::const_iterator
using reverse_iterator = typename array_type::reverse_iterator
using const_reverse_iterator = typename array_type::const_reverse_iterator
Public Member Functions
accessor (const range< Dimensions > &allocation_size, handler &command_group_handler)
Construct a device accessor from an existing buffer.
~accessor ()
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
auto get_count () const
Returns the total number of elements behind the accessor.
auto get_size () const
Returns the size of the underlying buffer storage in bytes.
reference operator[] (std::size_t index)
Use the accessor with integers à la [][][].
reference operator[] (std::size_t index) const
Use the accessor with integers à la [][][].
auto & operator[] (id< dimensionality > index)
To use the accessor with [id<>].
auto & operator[] (id< dimensionality > index) const
To use the accessor with [id<>].
auto & operator[] (item< dimensionality > index)
To use an accessor with [item<>].
auto & operator[] (item< dimensionality > index) const
To use an accessor with [item<>].
auto & operator[] (nd_item< dimensionality > index)
To use an accessor with an [nd_item<>].
auto & operator[] (nd_item< dimensionality > index) const
To use an accessor with an [nd_item<>].
reference operator* ()
Get the first element of the accessor.
reference operator* () const
Get the first element of the accessor.
constexpr bool is_read_access () const
Test if the accessor has a read access right.
constexpr bool is_write_access () const
Test if the accessor has a write access right.
iterator begin () const
Forward all the iterator functions to the implementation.
iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin () const
reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Types
using array_type = boost::multi_array_ref< T, Dimensions >
The implementation is a multi_array_ref wrapper.
using writable_array_type = typename std::remove_const< array_type >::type
Private Member Functions
auto allocate_accessor (const range< Dimensions > &r)
Allocate uninitialized buffer memory.
void deallocate_accessor ()
Deallocate accessor memory.
Private Attributes
writable_array_type array
The way the buffer is really accessed.
T * allocation = nullptr
The allocation on the host for the local accessor.
friend handler
Member Typedef Documentation
array_type
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::array_type = boost::multi_array_ref<T, Dimensions> private
The implementation is a multi_array_ref wrapper.
Definition at line 60 of file local_accessor.hpp.
const_iterator
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::const_iterator = typename array_type::const_iterator
Definition at line 103 of file local_accessor.hpp.
const_reference
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::const_reference = typename array_type::const_reference
Definition at line 96 of file local_accessor.hpp.
const_reverse_iterator
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::const_reverse_iterator = typename array_type::const_reverse_iterator
Definition at line 106 of file local_accessor.hpp.
element
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::element = T
Definition at line 94 of file local_accessor.hpp.
iterator
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::iterator = typename array_type::iterator
Inherit the iterator types from the implementation.
Todo:
Add iterators to accessors in the specification
Definition at line 102 of file local_accessor.hpp.
reference
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::reference = typename array_type::reference
Definition at line 95 of file local_accessor.hpp.
reverse_iterator
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::reverse_iterator = typename array_type::reverse_iterator
Definition at line 104 of file local_accessor.hpp.
value_type
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::value_type = T
Todo:
in the specification: store the types for user request as STL or C++AMP
Definition at line 93 of file local_accessor.hpp.
writable_array_type
template<typename T , int Dimensions, access::mode Mode> using trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::writable_array_type = typename std::remove_const<array_type>::type private
Definition at line 65 of file local_accessor.hpp.
Constructor & Destructor Documentation
accessor()
template<typename T , int Dimensions, access::mode Mode> trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::accessor (const range< Dimensions > & allocation_size, handler & command_group_handler) inline
Construct a device accessor from an existing buffer.
Todo:
fix the specification to rename target that shadows template param
Definition at line 114 of file local_accessor.hpp.
                                            :
     array { allocate_accessor(allocation_size) } {}
~accessor()
template<typename T , int Dimensions, access::mode Mode> trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::~accessor () inline
Definition at line 120 of file local_accessor.hpp.
               {
     deallocate_accessor();
   }
Member Function Documentation
allocate_accessor()
template<typename T , int Dimensions, access::mode Mode> auto trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::allocate_accessor (const range< Dimensions > & r) inline private
Allocate uninitialized buffer memory.
Definition at line 363 of file local_accessor.hpp.
References trisycl::range< Dimensions >::size().
{
     auto count = r.size();
     // Allocate uninitialized memory
     allocation = std::allocator<value_type>{}.allocate(count);
     return boost::multi_array_ref<value_type, Dimensions> { allocation, r };
   }
begin()
template<typename T , int Dimensions, access::mode Mode> iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::begin () const inline
Forward all the iterator functions to the implementation.
Todo:
Add these functions to the specification
Todo:
The fact that the lambda capture make a const copy of the accessor is not yet elegantly managed... The issue is that begin()/end() dispatch is made according to the accessor constness and not from the array member constness...
Todo:
try to solve it by using some enable_if on array constness?
Todo:
The issue is that the end may not be known if it is implemented by a raw OpenCL cl_mem... So only provide on the device the iterators related to the start? Actually the accessor needs to know a part of the shape to have the multidimentional addressing. So this only require a size_t more...
Todo:
Factor out these in a template helper
Todo:
Do we need this in detail::accessor too or only in accessor?
Definition at line 314 of file local_accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array, and trisycl::detail::accessor< T, Dimensions, Mode, Target >::begin().
{
     return const_cast<writable_array_type &>(array).begin();
   }
cbegin()
template<typename T , int Dimensions, access::mode Mode> const_iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::cbegin () const inline
Definition at line 331 of file local_accessor.hpp.
 { return array.begin(); }
cend()
template<typename T , int Dimensions, access::mode Mode> const_iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::cend () const inline
Definition at line 334 of file local_accessor.hpp.
 { return array.end(); }
crbegin()
template<typename T , int Dimensions, access::mode Mode> const_reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::crbegin () const inline
Definition at line 355 of file local_accessor.hpp.
 { return array.rbegin(); }
crend()
template<typename T , int Dimensions, access::mode Mode> const_reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::crend () const inline
Definition at line 358 of file local_accessor.hpp.
 { return array.rend(); }
deallocate_accessor()
template<typename T , int Dimensions, access::mode Mode> void trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::deallocate_accessor () inline private
Deallocate accessor memory.
Definition at line 372 of file local_accessor.hpp.
{
     std::allocator<value_type>{}.deallocate(allocation, array.num_elements());
   }
end()
template<typename T , int Dimensions, access::mode Mode> iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::end () const inline
Definition at line 320 of file local_accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array, and trisycl::detail::accessor< T, Dimensions, Mode, Target >::end().
{
     return const_cast<writable_array_type &>(array).end();
   }
get_count()
template<typename T , int Dimensions, access::mode Mode> auto trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::get_count () const inline
Returns the total number of elements behind the accessor.
Equal to get_range()[0] * ... * get_range()[Dimensions-1].
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 155 of file local_accessor.hpp.
{
     return array.num_elements();
   }
get_range()
template<typename T , int Dimensions, access::mode Mode> auto trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::get_range () const inline
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 133 of file local_accessor.hpp.
{
     /* Interpret the shape which is a pointer to the first element as an
        array of Dimensions elements so that the range<Dimensions>
        constructor is happy with this collection
        \todo Add also a constructor in range<> to accept a const
        std::size_t *?
     */
     return range<Dimensions> {
       *(const std::size_t (*)[Dimensions])(array.shape())
         };
   }
get_size()
template<typename T , int Dimensions, access::mode Mode> auto trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::get_size () const inline
Returns the size of the underlying buffer storage in bytes.
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 166 of file local_accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_count().
{
     return get_count()*sizeof(value_type);
   }
is_read_access()
template<typename T , int Dimensions, access::mode Mode> constexpr bool trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::is_read_access () const inline
Test if the accessor has a read access right.
Todo:
Strangely, it is not really constexpr because it is not a static method...
Todo:
to move in the access::mode enum class and add to the specification ?
Definition at line 266 of file local_accessor.hpp.
References trisycl::access::discard_read_write, trisycl::access::read, and trisycl::access::read_write.
{
     return Mode == access::mode::read
       || Mode == access::mode::read_write
       || Mode == access::mode::discard_read_write;
   }
is_write_access()
template<typename T , int Dimensions, access::mode Mode> constexpr bool trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::is_write_access () const inline
Test if the accessor has a write access right.
Todo:
Strangely, it is not really constexpr because it is not a static method...
Todo:
to move in the access::mode enum class and add to the specification ?
Definition at line 281 of file local_accessor.hpp.
References trisycl::access::discard_read_write, trisycl::access::discard_write, trisycl::access::read_write, and trisycl::access::write.
{
     return Mode == access::mode::write
       || Mode == access::mode::read_write
       || Mode == access::mode::discard_write
       || Mode == access::mode::discard_read_write;
   }
operator*() [1/2]
template<typename T , int Dimensions, access::mode Mode> reference trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator* () inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add in the specification
Definition at line 238 of file local_accessor.hpp.
{
     return *array.data();
   }
operator*() [2/2]
template<typename T , int Dimensions, access::mode Mode> reference trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator* () const inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add in the specification?
Todo:
Add the concept of 0-dim buffer and accessor for scalar and use an implicit conversion to value_type reference to access the value with the accessor?
Definition at line 253 of file local_accessor.hpp.
{
     return *array.data();
   }
operator[]() [1/8]
template<typename T , int Dimensions, access::mode Mode> reference trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (std::size_t index) inline
Use the accessor with integers à la [][][].
Use array_view_type::reference instead of auto& because it does not work in some dimensions.
Definition at line 176 of file local_accessor.hpp.
{
     return array[index];
   }
operator[]() [2/8]
template<typename T , int Dimensions, access::mode Mode> reference trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (std::size_t index) const inline
Use the accessor with integers à la [][][].
Use array_view_type::reference instead of auto& because it does not work in some dimensions.
Definition at line 186 of file local_accessor.hpp.
{
     return array[index];
   }
operator[]() [3/8]
template<typename T , int Dimensions, access::mode Mode> auto& trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (id< dimensionality > index) inline
To use the accessor with [id<>].
Definition at line 192 of file local_accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
{
     return array(index);
   }
operator[]() [4/8]
template<typename T , int Dimensions, access::mode Mode> auto& trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (id< dimensionality > index) const inline
To use the accessor with [id<>].
Definition at line 198 of file local_accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
{
     return array(index);
   }
operator[]() [5/8]
template<typename T , int Dimensions, access::mode Mode> auto& trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (item< dimensionality > index) inline
To use an accessor with [item<>].
Definition at line 204 of file local_accessor.hpp.
{
     return (*this)[index.get()];
   }
operator[]() [6/8]
template<typename T , int Dimensions, access::mode Mode> auto& trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (item< dimensionality > index) const inline
To use an accessor with [item<>].
Definition at line 210 of file local_accessor.hpp.
{
     return (*this)[index.get()];
   }
operator[]() [7/8]
template<typename T , int Dimensions, access::mode Mode> auto& trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (nd_item< dimensionality > index) inline
To use an accessor with an [nd_item<>].
Todo:
Add in the specification because used by HPC-GPU slide 22
Definition at line 219 of file local_accessor.hpp.
{
     return (*this)[index.get_global()];
   }
operator[]() [8/8]
template<typename T , int Dimensions, access::mode Mode> auto& trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[] (nd_item< dimensionality > index) const inline
To use an accessor with an [nd_item<>].
Todo:
Add in the specification because used by HPC-GPU slide 22
Definition at line 227 of file local_accessor.hpp.
{
     return (*this)[index.get_global()];
   }
rbegin()
template<typename T , int Dimensions, access::mode Mode> reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::rbegin () const inline
Definition at line 338 of file local_accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array, and trisycl::detail::accessor< T, Dimensions, Mode, Target >::rbegin().
{
     return const_cast<writable_array_type &>(array).rbegin();
   }
rend()
template<typename T , int Dimensions, access::mode Mode> reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::rend () const inline
Definition at line 344 of file local_accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array, and trisycl::detail::accessor< T, Dimensions, Mode, Target >::rend().
{
     return const_cast<writable_array_type &>(array).rend();
   }
Member Data Documentation
allocation
template<typename T , int Dimensions, access::mode Mode> T* trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::allocation = nullptr mutable private
The allocation on the host for the local accessor.
Note that this is uninitialized memory, as stated in SYCL specification.
Definition at line 81 of file local_accessor.hpp.
array
template<typename T , int Dimensions, access::mode Mode> writable_array_type trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::array mutable private
The way the buffer is really accessed.
Use a mutable member because the accessor needs to be captured by value in the lambda which is then read-only. This is to avoid the user to use mutable lambda or have a lot of const_cast as previously done in this implementation
Definition at line 74 of file local_accessor.hpp.
dimensionality
template<typename T , int Dimensions, access::mode Mode> constexpr auto trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::dimensionality = Dimensions static
Todo:
in the specification: store the dimension for user request
Todo:
Use another name, such as from C++17 committee discussions.
Definition at line 89 of file local_accessor.hpp.
handler
template<typename T , int Dimensions, access::mode Mode> friend trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::handler private
Definition at line 378 of file local_accessor.hpp.
trisycl::accessor
class trisycl::accessor
template<typename DataType, int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer>
class trisycl::accessor< DataType, Dimensions, AccessMode, Target >
The accessor abstracts the way buffer or pipe data are accessed inside a kernel in a multidimensional variable length array way.
Todo:
Implement it for images according so section 3.3.4.5
Definition at line 46 of file accessor.hpp.
Public Member Functions
template<typename Allocator >
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer, handler &command_group_handler)
Construct a buffer accessor from a buffer using a command group handler object from the command group scope.
template<typename Allocator >
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer)
Construct a buffer accessor from a buffer.
template<typename Allocator >
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer, handler &command_group_handler, const range< Dimensions > &offset, const range< Dimensions > &range)
Construct a buffer accessor from a buffer given a specific range for access permissions and an offset that provides the starting point for the access range using a command group handler object from the command group scope.
accessor (const range< Dimensions > &allocation_size, handler &command_group_handler)
Construct an accessor of dimension Dimensions with elements of type DataType using the passed range to specify the size in each dimension.
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
auto get_count () const
Returns the total number of elements behind the accessor.
auto get_size () const
Returns the size of the underlying buffer storage in bytes.
accessor_detail::reference operator[] (std::size_t index)
Use the accessor with integers à la [][][].
accessor_detail::reference operator[] (std::size_t index) const
Use the accessor with integers à la [][][].
auto & operator[] (id< dimensionality > index)
To use the accessor with [id<>].
auto & operator[] (id< dimensionality > index) const
To use the accessor with [id<>].
auto & operator[] (item< dimensionality > index)
To use an accessor with [item<>].
auto & operator[] (item< dimensionality > index) const
To use an accessor with [item<>].
auto & operator[] (nd_item< dimensionality > index)
To use an accessor with an [nd_item<>].
auto & operator[] (nd_item< dimensionality > index) const
To use an accessor with an [nd_item<>].
accessor_detail::reference operator* ()
Get the first element of the accessor.
accessor_detail::reference operator* () const
Get the first element of the accessor.
auto get_pointer () const
Get the pointer to the start of the data.
accessor_detail::iterator begin () const
Forward all the iterator functions to the implementation.
accessor_detail::iterator end () const
accessor_detail::const_iterator cbegin () const
accessor_detail::const_iterator cend () const
accessor_detail::reverse_iterator rbegin () const
accessor_detail::reverse_iterator rend () const
accessor_detail::const_reverse_iterator crbegin () const
accessor_detail::const_reverse_iterator crend () const
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >
shared_ptr_implementation (std::shared_ptr< detail::accessor< DataType, Dimensions, AccessMode, Target > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::accessor< DataType, Dimensions, AccessMode, Target > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const accessor< DataType, Dimensions, AccessMode, Target > &other) const
Equality operator.
bool operator< (const accessor< DataType, Dimensions, AccessMode, Target > &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Types
using accessor_detail = typename detail::accessor< DataType, Dimensions, AccessMode, Target >
using implementation_t = typename accessor::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Types inherited from trisycl::detail::container_element_aspect< DataType >
using value_type = DataType
using pointer = value_type *
using const_pointer = const value_type *
using reference = value_type &
using const_reference = const value_type &
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >
std::shared_ptr< detail::accessor< DataType, Dimensions, AccessMode, Target > > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
accessor_detail
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> using trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor_detail = typename detail::accessor<DataType, Dimensions, AccessMode, Target> private
Definition at line 67 of file accessor.hpp.
implementation_t
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> using trisycl::accessor< DataType, Dimensions, AccessMode, Target >::implementation_t = typename accessor::shared_ptr_implementation private
Definition at line 70 of file accessor.hpp.
Constructor & Destructor Documentation
accessor() [1/4]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> template<typename Allocator > trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (buffer< DataType, Dimensions, Allocator > & target_buffer, handler & command_group_handler) inline
Construct a buffer accessor from a buffer using a command group handler object from the command group scope.
Constructor only available for global_buffer or constant_buffer target.
access_target defines the form of access being obtained.
Todo:
Add template allocator type in all the accessor constructors in the specification or just use a more opaque Buffer type?
Todo:
fix specification where access mode should be target instead
Definition at line 96 of file accessor.hpp.
References trisycl::access::constant_buffer, trisycl::access::global_buffer, trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation, and trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
                                            : implementation_t {
     new detail::accessor<DataType, Dimensions, AccessMode, Target> {
       target_buffer.implementation->implementation, command_group_handler }
   } {
     static_assert(Target == access::target::global_buffer
                   || Target == access::target::constant_buffer,
                   "access target should be global_buffer or constant_buffer "
                   "when a handler is used");
     // Now the implementation is created, register it
     implementation->register_accessor();
   }
accessor() [2/4]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> template<typename Allocator > trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (buffer< DataType, Dimensions, Allocator > & target_buffer) inline
Construct a buffer accessor from a buffer.
Constructor only available for host_buffer target.
access_target defines the form of access being obtained.
Definition at line 117 of file accessor.hpp.
References trisycl::access::host_buffer, and trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
     : implementation_t {
     new detail::accessor<DataType, Dimensions, AccessMode, Target> {
       target_buffer.implementation->implementation }
   } {
     static_assert(Target == access::target::host_buffer,
                   "without a handler, access target should be host_buffer");
   }
accessor() [3/4]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> template<typename Allocator > trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (buffer< DataType, Dimensions, Allocator > & target_buffer, handler & command_group_handler, const range< Dimensions > & offset, const range< Dimensions > & range) inline
Construct a buffer accessor from a buffer given a specific range for access permissions and an offset that provides the starting point for the access range using a command group handler object from the command group scope.
This accessor limits the processing of the buffer to the [offset, offset+range[ for every dimension. Any other parts of the buffer will be unaffected.
Constructor only available for access modes global_buffer, and constant_buffer (see Table "Buffer accessor constructors"). access_target defines the form of access being obtained.
This accessor is recommended for discard-write and discard read write access modes, when the unaffected parts of the processing should be retained.
Definition at line 145 of file accessor.hpp.
References TRISYCL_UNIMPL.
{
     TRISYCL_UNIMPL;
   }
accessor() [4/4]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (const range< Dimensions > & allocation_size, handler & command_group_handler) inline
Construct an accessor of dimension Dimensions with elements of type DataType using the passed range to specify the size in each dimension.
It needs as a parameter a command group handler object from the command group scope. Constructor only available if AccessMode is local, see Table 3.25.
Definition at line 161 of file accessor.hpp.
References trisycl::access::local.
     : implementation_t { new detail::accessor<DataType,
                                               Dimensions,
                                               AccessMode,
                                               access::target::local> {
       allocation_size, command_group_handler
         }
   }
   {
     static_assert(Target == access::target::local,
                   "This accessor constructor requires "
                   "access target be local");
   }
Member Function Documentation
begin()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::begin () const inline
Forward all the iterator functions to the implementation.
Todo:
Add these functions to the specification
Todo:
The fact that the lambda capture make a const copy of the accessor is not yet elegantly managed... The issue is that begin()/end() dispatch is made according to the accessor constness and not from the array member constness...
Todo:
try to solve it by using some enable_if on array constness?
Todo:
The issue is that the end may not be known if it is implemented by a raw OpenCL cl_mem... So only provide on the device the iterators related to the start? Actually the accessor needs to know a part of the shape to have the multidimentional addressing. So this only require a size_t more...
Todo:
Factor out these in a template helper
Definition at line 345 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->begin();
   }
cbegin()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::const_iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::cbegin () const inline
Definition at line 362 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->cbegin();
   }
cend()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::const_iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::cend () const inline
Definition at line 367 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->cend();
   }
crbegin()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::const_reverse_iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::crbegin () const inline
Definition at line 388 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->rbegin();
   }
crend()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::const_reverse_iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::crend () const inline
Definition at line 393 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->rend();
   }
end()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::end () const inline
Definition at line 351 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->end();
   }
get_count()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto trisycl::accessor< DataType, Dimensions, AccessMode, Target >::get_count () const inline
Returns the total number of elements behind the accessor.
Equal to get_range()[0] * ... * get_range()[Dimensions-1].
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 205 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->get_count();
   }
get_pointer()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto trisycl::accessor< DataType, Dimensions, AccessMode, Target >::get_pointer () const inline
Get the pointer to the start of the data.
Todo:
Should it be named data() instead?
Definition at line 317 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
                       {
     return implementation->get_pointer();
   }
get_range()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto trisycl::accessor< DataType, Dimensions, AccessMode, Target >::get_range () const inline
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 185 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     /* Interpret the shape which is a pointer to the first element as an
        array of Dimensions elements so that the range<Dimensions>
        constructor is happy with this collection
        \todo Add also a constructor in range<> to accept a const
        std::size_t *?
     */
     return implementation->get_range();
   }
get_size()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto trisycl::accessor< DataType, Dimensions, AccessMode, Target >::get_size () const inline
Returns the size of the underlying buffer storage in bytes.
Todo:
It is incompatible with buffer get_size() in the spec
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 218 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->get_size();
   }
operator*() [1/2]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::reference trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator* () inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add in the specification
Definition at line 293 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return **implementation;
   }
operator*() [2/2]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::reference trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator* () const inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add in the specification?
Todo:
Add the concept of 0-dim buffer and accessor for scalar and use an implicit conversion to value_type reference to access the value with the accessor?
Definition at line 308 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return **implementation;
   }
operator[]() [1/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::reference trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (std::size_t index) inline
Use the accessor with integers à la [][][].
Use array_view_type::reference instead of auto& because it does not work in some dimensions.
Definition at line 228 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
 //#ifdef TRISYCL_DEVICE
 //#else
     return (*implementation)[index];
 //#endif
   }
operator[]() [2/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::reference trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (std::size_t index) const inline
Use the accessor with integers à la [][][].
Use array_view_type::reference instead of auto& because it does not work in some dimensions.
Definition at line 241 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return (*implementation)[index];
   }
operator[]() [3/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto& trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (id< dimensionality > index) inline
To use the accessor with [id<>].
Definition at line 247 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return (*implementation)[index];
   }
operator[]() [4/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto& trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (id< dimensionality > index) const inline
To use the accessor with [id<>].
Definition at line 253 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return (*implementation)[index];
   }
operator[]() [5/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto& trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (item< dimensionality > index) inline
To use an accessor with [item<>].
Definition at line 259 of file accessor.hpp.
References trisycl::item< Dimensions, with_offset >::get_id().
{
     return (*this)[index.get_id()];
   }
operator[]() [6/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto& trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (item< dimensionality > index) const inline
To use an accessor with [item<>].
Definition at line 265 of file accessor.hpp.
References trisycl::item< Dimensions, with_offset >::get_id().
{
     return (*this)[index.get_id()];
   }
operator[]() [7/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto& trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (nd_item< dimensionality > index) inline
To use an accessor with an [nd_item<>].
Todo:
Add in the specification because used by HPC-GPU slide 22
Definition at line 274 of file accessor.hpp.
References trisycl::nd_item< Dimensions >::get_global_id().
{
     return (*this)[index.get_global_id()];
   }
operator[]() [8/8]
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> auto& trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[] (nd_item< dimensionality > index) const inline
To use an accessor with an [nd_item<>].
Todo:
Add in the specification because used by HPC-GPU slide 22
Definition at line 282 of file accessor.hpp.
References trisycl::nd_item< Dimensions >::get_global_id().
{
     return (*this)[index.get_global_id()];
   }
rbegin()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::reverse_iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::rbegin () const inline
Definition at line 372 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->rbegin();
   };
rend()
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> accessor_detail::reverse_iterator trisycl::accessor< DataType, Dimensions, AccessMode, Target >::rend () const inline
Definition at line 377 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >::implementation.
{
     return implementation->rend();
   }
Member Data Documentation
dimensionality
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> constexpr auto trisycl::accessor< DataType, Dimensions, AccessMode, Target >::dimensionality = Dimensions static
Todo:
in the specification: store the dimension for user request
Definition at line 60 of file accessor.hpp.
implementation_t
template<typename DataType , int Dimensions, access::mode AccessMode, access::target Target = access::target::global_buffer> friend trisycl::accessor< DataType, Dimensions, AccessMode, Target >::implementation_t private
Definition at line 73 of file accessor.hpp.
trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
class trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
template<typename DataType, access::mode AccessMode>
class trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
A specialization for an non-blocking pipe
Definition at line 407 of file accessor.hpp.
Public Types
using accessor_detail = detail::pipe_accessor< DataType, AccessMode, access::target::pipe >
Public Types inherited from trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::pipe >
using value_type = DataType
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
Public Member Functions
accessor (pipe< DataType > &p, handler &command_group_handler)
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
pipe_reservation< accessor > reserve (std::size_t size) const
Make a reservation inside the pipe.
auto & get_pipe_detail ()
Get the underlying pipe implementation.
Public Member Functions inherited from trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::pipe >
pipe_accessor (const std::shared_ptr< detail::pipe< DataType >> &p)
Construct a pipe accessor from an existing pipe.
pipe_accessor (const std::shared_ptr< detail::pipe< DataType >> &p, handler &command_group_handler)
Construct a pipe accessor from an existing pipe.
pipe_accessor ()=default
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size () const
Get the current number of elements in the pipe.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
operator bool () const
In an explicit bool context, the accessor gives the success status of the last access.
const pipe_accessor & write (const value_type &value) const
Try to write a value to the pipe.
const pipe_accessor & operator<< (const value_type &value) const
Some syntactic sugar to use.
const pipe_accessor & read (value_type &value) const
Try to read a value from the pipe.
value_type read () const
Read a value from a blocking pipe.
const pipe_accessor & operator>> (value_type &value) const
Some syntactic sugar to use.
detail::pipe_reservation< pipe_accessor > reserve (std::size_t size) const
void set_debug (bool enable) const
Set debug mode.
auto & get_pipe_detail ()
~pipe_accessor ()
Additional Inherited Members
Static Public Attributes inherited from trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::pipe >
static constexpr auto rank
static constexpr auto mode
static constexpr auto target
static constexpr bool blocking
Member Typedef Documentation
accessor_detail
template<typename DataType , access::mode AccessMode> using trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::accessor_detail = detail::pipe_accessor<DataType, AccessMode, access::target::pipe>
Definition at line 412 of file accessor.hpp.
Constructor & Destructor Documentation
accessor()
template<typename DataType , access::mode AccessMode> trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::accessor (pipe< DataType > & p, handler & command_group_handler) inline
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
access_target defines the form of access being obtained.
Definition at line 421 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< pipe< T >, detail::pipe< T > >::implementation.
     : accessor_detail { p.implementation, command_group_handler } { }
Member Function Documentation
get_pipe_detail()
template<typename DataType , access::mode AccessMode> auto& trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::get_pipe_detail () inline
Get the underlying pipe implementation.
Definition at line 431 of file accessor.hpp.
References trisycl::get_pipe_detail().
{
     return accessor_detail::get_pipe_detail();
   }
reserve()
template<typename DataType , access::mode AccessMode> pipe_reservation<accessor> trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::reserve (std::size_t size) const inline
Make a reservation inside the pipe.
Definition at line 425 of file accessor.hpp.
{
     return accessor_detail::reserve(size);
   }
trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
class trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
template<typename DataType, access::mode AccessMode>
class trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
A specialization for a blocking pipe
Definition at line 445 of file accessor.hpp.
Public Types
using accessor_detail = detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
Public Types inherited from trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
using value_type = DataType
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
Public Member Functions
accessor (pipe< DataType > &p, handler &command_group_handler)
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
accessor (pipe< DataType > &p)
Construct a pipe accessor from a pipe outside of a normal kernel, for example in host code.
pipe_reservation< accessor > reserve (std::size_t size) const
Make a reservation inside the pipe.
auto & get_pipe_detail ()
Get the underlying pipe implementation.
Public Member Functions inherited from trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
pipe_accessor (const std::shared_ptr< detail::pipe< DataType >> &p)
Construct a pipe accessor from an existing pipe.
pipe_accessor (const std::shared_ptr< detail::pipe< DataType >> &p, handler &command_group_handler)
Construct a pipe accessor from an existing pipe.
pipe_accessor ()=default
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size () const
Get the current number of elements in the pipe.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
operator bool () const
In an explicit bool context, the accessor gives the success status of the last access.
const pipe_accessor & write (const value_type &value) const
Try to write a value to the pipe.
const pipe_accessor & operator<< (const value_type &value) const
Some syntactic sugar to use.
const pipe_accessor & read (value_type &value) const
Try to read a value from the pipe.
value_type read () const
Read a value from a blocking pipe.
const pipe_accessor & operator>> (value_type &value) const
Some syntactic sugar to use.
detail::pipe_reservation< pipe_accessor > reserve (std::size_t size) const
void set_debug (bool enable) const
Set debug mode.
auto & get_pipe_detail ()
~pipe_accessor ()
Additional Inherited Members
Static Public Attributes inherited from trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
static constexpr auto rank
static constexpr auto mode
static constexpr auto target
static constexpr bool blocking
Member Typedef Documentation
accessor_detail
template<typename DataType , access::mode AccessMode> using trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::accessor_detail = detail::pipe_accessor<DataType, AccessMode, access::target::blocking_pipe>
Definition at line 450 of file accessor.hpp.
Constructor & Destructor Documentation
accessor() [1/2]
template<typename DataType , access::mode AccessMode> trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::accessor (pipe< DataType > & p, handler & command_group_handler) inline
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
access_target defines the form of access being obtained.
Definition at line 459 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< pipe< T >, detail::pipe< T > >::implementation.
     : accessor_detail { p.implementation, command_group_handler } { }
accessor() [2/2]
template<typename DataType , access::mode AccessMode> trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::accessor (pipe< DataType > & p) inline
Construct a pipe accessor from a pipe outside of a normal kernel, for example in host code.
Definition at line 466 of file accessor.hpp.
References trisycl::detail::shared_ptr_implementation< pipe< T >, detail::pipe< T > >::implementation.
     : accessor_detail { p.implementation } { }
Member Function Documentation
get_pipe_detail()
template<typename DataType , access::mode AccessMode> auto& trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::get_pipe_detail () inline
Get the underlying pipe implementation.
Definition at line 477 of file accessor.hpp.
References trisycl::get_pipe_detail().
{
     return accessor_detail::get_pipe_detail();
   }
reserve()
template<typename DataType , access::mode AccessMode> pipe_reservation<accessor> trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::reserve (std::size_t size) const inline
Make a reservation inside the pipe.
Definition at line 471 of file accessor.hpp.
{
     return accessor_detail::reserve(size);
   }
trisycl::detail::accessor
class trisycl::detail::accessor
template<typename T, int Dimensions, access::mode Mode, access::target Target>
class trisycl::detail::accessor< T, Dimensions, Mode, Target >
The buffer accessor abstracts the way buffer data are accessed inside a kernel in a multidimensional variable length array way.
This implementation relies on boost::multi_array to provide this nice syntax and behaviour.
Right now the aim of this class is just to access to the buffer in a read-write mode, even if capturing the multi_array_ref from a lambda make it const (since in examples we have lambda with [=] without mutable lambda).
Todo:
Use the access::mode
Definition at line 38 of file local_accessor.hpp.
Public Types
using value_type = T
using element = T
using reference = typename array_view_type::reference
using const_reference = typename array_view_type::const_reference
using iterator = typename array_view_type::iterator
Inherit the iterator types from the implementation.
using const_iterator = typename array_view_type::const_iterator
using reverse_iterator = typename array_view_type::reverse_iterator
using const_reverse_iterator = typename array_view_type::const_reverse_iterator
Public Member Functions
accessor (std::shared_ptr< detail::buffer< T, Dimensions >> target_buffer)
Construct a host accessor from an existing buffer.
accessor (std::shared_ptr< detail::buffer< T, Dimensions >> target_buffer, handler &command_group_handler)
Construct a device accessor from an existing buffer.
void register_accessor ()
Register the accessor once a std::shared_ptr is created on it.
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
auto get_count () const
Returns the total number of elements behind the accessor.
auto get_size () const
Returns the size of the underlying buffer storage in bytes.
reference operator[] (std::size_t index)
Use the accessor with integers à la [][][].
reference operator[] (std::size_t index) const
Use the accessor with integers à la [][][].
auto & operator[] (id< dimensionality > index)
To use the accessor with [id<>].
auto & operator[] (id< dimensionality > index) const
To use the accessor with [id<>].
auto & operator[] (item< dimensionality > index)
To use an accessor with [item<>].
auto & operator[] (item< dimensionality > index) const
To use an accessor with [item<>].
auto & operator[] (nd_item< dimensionality > index)
To use an accessor with an [nd_item<>].
auto & operator[] (nd_item< dimensionality > index) const
To use an accessor with an [nd_item<>].
reference operator* ()
Get the first element of the accessor.
reference operator* () const
Get the first element of the accessor.
detail::buffer< T, Dimensions > & get_buffer ()
Get the buffer used to create the accessor.
constexpr bool is_read_access () const
Test if the accessor has a read access right.
constexpr bool is_write_access () const
Test if the accessor has a write access right.
auto get_pointer () const
Return the pointer to the data.
iterator begin () const
Forward all the iterator functions to the implementation.
iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin () const
reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
Public Member Functions inherited from trisycl::detail::accessor_base
void set_order (std::size_t o)
Set the order of the accessor.
auto get_order ()
Get the order of the accessor.
virtual ~accessor_base ()
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Types
using array_view_type = boost::multi_array_ref< T, Dimensions >
The implementation is a multi_array_ref wrapper.
using writable_array_view_type = typename std::remove_const< array_view_type >::type
Private Member Functions
boost::compute::buffer get_cl_buffer () const override
Get the boost::compute::buffer or throw if unset.
void copy_in_cl_buffer ()
Lazily associate a CL buffer to the SYCL buffer and copy data in it if required, updates the state of the data in the buffer across contexts.
void copy_back_cl_buffer ()
Does nothing.
Private Attributes
std::shared_ptr< detail::buffer< T, Dimensions > > buf
Keep a reference to the accessed buffer.
array_view_type array
The way the buffer is really accessed.
friend handler
Additional Inherited Members
Protected Attributes inherited from trisycl::detail::accessor_base
std::shared_ptr< detail::task > task
The task where the accessor is used in.
std::size_t order
The declaration order of the accessor.
Member Typedef Documentation
array_view_type
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::array_view_type = boost::multi_array_ref<T, Dimensions> private
The implementation is a multi_array_ref wrapper.
Definition at line 77 of file accessor.hpp.
const_iterator
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::const_iterator = typename array_view_type::const_iterator
Definition at line 112 of file accessor.hpp.
const_reference
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::const_reference = typename array_view_type::const_reference
Definition at line 105 of file accessor.hpp.
const_reverse_iterator
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::const_reverse_iterator = typename array_view_type::const_reverse_iterator
Definition at line 115 of file accessor.hpp.
element
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::element = T
Definition at line 103 of file accessor.hpp.
iterator
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::iterator = typename array_view_type::iterator
Inherit the iterator types from the implementation.
Todo:
Add iterators to accessors in the specification
Definition at line 111 of file accessor.hpp.
reference
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::reference = typename array_view_type::reference
Definition at line 104 of file accessor.hpp.
reverse_iterator
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::reverse_iterator = typename array_view_type::reverse_iterator
Definition at line 113 of file accessor.hpp.
value_type
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::value_type = T
Todo:
in the specification: store the types for user request as STL or C++AMP
Definition at line 102 of file accessor.hpp.
writable_array_view_type
template<typename T , int Dimensions, access::mode Mode, access::target Target> using trisycl::detail::accessor< T, Dimensions, Mode, Target >::writable_array_view_type = typename std::remove_const<array_view_type>::type private
Definition at line 81 of file accessor.hpp.
Constructor & Destructor Documentation
accessor() [1/2]
template<typename T , int Dimensions, access::mode Mode, access::target Target> trisycl::detail::accessor< T, Dimensions, Mode, Target >::accessor (std::shared_ptr< detail::buffer< T, Dimensions >> target_buffer) inline
Construct a host accessor from an existing buffer.
Todo:
fix the specification to rename target that shadows template parm
Definition at line 123 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_size(), trisycl::access::host_buffer, trisycl::detail::accessor< T, Dimensions, Mode, Target >::is_write_access(), and TRISYCL_DUMP_T.
                                                                      :
     buf { target_buffer }, array { target_buffer->access } {
     target_buffer->template track_access_mode<Mode>();
     TRISYCL_DUMP_T("Create a host accessor write = " << is_write_access());
     static_assert(Target == access::target::host_buffer,
                   "without a handler, access target should be host_buffer");
     /* The host needs to wait for all the producers of the buffer to
        have finished */
     buf->wait();
 #ifdef TRISYCL_OPENCL
     /* For the host context, we are obligated to update the buffer state
        during the accessors creation, otherwise we have no way of knowing
        if a buffer was modified on the host. This is only true because
        host accessors are blocking
      */
     trisycl::context ctx;
     buf->update_buffer_state(ctx, Mode, get_size(), array.data());
 #endif
   }
accessor() [2/2]
template<typename T , int Dimensions, access::mode Mode, access::target Target> trisycl::detail::accessor< T, Dimensions, Mode, Target >::accessor (std::shared_ptr< detail::buffer< T, Dimensions >> target_buffer, handler & command_group_handler) inline
Construct a device accessor from an existing buffer.
Todo:
fix the specification to rename target that shadows template parm
Definition at line 150 of file accessor.hpp.
References trisycl::detail::buffer_add_to_task(), trisycl::access::constant_buffer, trisycl::access::global_buffer, trisycl::detail::accessor< T, Dimensions, Mode, Target >::is_write_access(), and TRISYCL_DUMP_T.
                                            :
     buf { target_buffer }, array { target_buffer->access } {
     target_buffer->template track_access_mode<Mode>();
     TRISYCL_DUMP_T("Create a kernel accessor write = " << is_write_access());
     static_assert(Target == access::target::global_buffer
                   || Target == access::target::constant_buffer,
                   "access target should be global_buffer or constant_buffer "
                   "when a handler is used");
     // Register the buffer to the task dependencies
     task = buffer_add_to_task(buf, &command_group_handler, is_write_access());
   }
Member Function Documentation
begin()
template<typename T , int Dimensions, access::mode Mode, access::target Target> iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::begin () const inline
Forward all the iterator functions to the implementation.
Todo:
Add these functions to the specification
Todo:
The fact that the lambda capture make a const copy of the accessor is not yet elegantly managed... The issue is that begin()/end() dispatch is made according to the accessor constness and not from the array member constness...
Todo:
try to solve it by using some enable_if on array constness?
Todo:
The issue is that the end may not be known if it is implemented by a raw OpenCL cl_mem... So only provide on the device the iterators related to the start? Actually the accessor needs to know a part of the shape to have the multidimentional addressing. So this only require a size_t more...
Todo:
Factor out these in a template helper
Todo:
Do we need this in detail::accessor too or only in accessor?
Definition at line 403 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::begin().
{
     return const_cast<writable_array_view_type &>(array).begin();
   }
cbegin()
template<typename T , int Dimensions, access::mode Mode, access::target Target> const_iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::cbegin () const inline
Definition at line 420 of file accessor.hpp.
 { return array.begin(); }
cend()
template<typename T , int Dimensions, access::mode Mode, access::target Target> const_iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::cend () const inline
Definition at line 423 of file accessor.hpp.
 { return array.end(); }
copy_back_cl_buffer()
template<typename T , int Dimensions, access::mode Mode, access::target Target> void trisycl::detail::accessor< T, Dimensions, Mode, Target >::copy_back_cl_buffer () inline private
Does nothing.
Definition at line 476 of file accessor.hpp.
{
     /* The copy back is handled by the host accessor and the buffer destructor.
        We don't need to systematically transfer the data after the
        kernel execution
        \todo Figure out what to do with this function
     */
   }
copy_in_cl_buffer()
template<typename T , int Dimensions, access::mode Mode, access::target Target> void trisycl::detail::accessor< T, Dimensions, Mode, Target >::copy_in_cl_buffer () inline private
Lazily associate a CL buffer to the SYCL buffer and copy data in it if required, updates the state of the data in the buffer across contexts.
Definition at line 466 of file accessor.hpp.
References trisycl::detail::task::get_queue(), and trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_size().
{
     /* Create the OpenCL buffer and copy in it the data from the host if
        the buffer doesn't already exists or if the data is not up to date
     */
     auto ctx = task->get_queue()->get_context();
     buf->update_buffer_state(ctx, Mode, get_size(), array.data());
   }
crbegin()
template<typename T , int Dimensions, access::mode Mode, access::target Target> const_reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::crbegin () const inline
Definition at line 444 of file accessor.hpp.
 { return array.rbegin(); }
crend()
template<typename T , int Dimensions, access::mode Mode, access::target Target> const_reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::crend () const inline
Definition at line 447 of file accessor.hpp.
 { return array.rend(); }
end()
template<typename T , int Dimensions, access::mode Mode, access::target Target> iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::end () const inline
Definition at line 409 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::end().
{
     return const_cast<writable_array_view_type &>(array).end();
   }
get_buffer()
template<typename T , int Dimensions, access::mode Mode, access::target Target> detail::buffer<T, Dimensions>& trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_buffer () inline
Get the buffer used to create the accessor.
Definition at line 332 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::buf.
{
     return *buf;
   }
get_cl_buffer()
template<typename T , int Dimensions, access::mode Mode, access::target Target> boost::compute::buffer trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_cl_buffer () const inline override private virtual
Get the boost::compute::buffer or throw if unset.
Implements trisycl::detail::accessor_base.
Definition at line 456 of file accessor.hpp.
References trisycl::detail::task::get_queue().
{
     // This throws if not set
     auto ctx = task->get_queue()->get_context();
     return buf->get_cl_buffer(ctx);
   }
get_count()
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_count () const inline
Returns the total number of elements behind the accessor.
Equal to get_range()[0] * ... * get_range()[Dimensions-1].
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 228 of file accessor.hpp.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::get_size(), and trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_size().
{
     return array.num_elements();
   }
get_pointer()
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_pointer () const inline
Return the pointer to the data.
Todo:
Implement the various pointer address spaces
Definition at line 373 of file accessor.hpp.
                       {
     return array.data();
   }
get_range()
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_range () const inline
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 206 of file accessor.hpp.
{
     /* Interpret the shape which is a pointer to the first element as an
        array of Dimensions elements so that the range<Dimensions>
        constructor is happy with this collection
        \todo Add also a constructor in range<> to accept a const
        std::size_t *?
     */
     return range<Dimensions> {
       *(const std::size_t (*)[Dimensions])(array.shape())
         };
   }
get_size()
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_size () const inline
Returns the size of the underlying buffer storage in bytes.
Todo:
Move on https://cvs.khronos.org/bugzilla/show_bug.cgi?id=15564 and https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14404
Definition at line 239 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_count().
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::accessor(), and trisycl::detail::accessor< T, Dimensions, Mode, Target >::copy_in_cl_buffer().
{
     return get_count()*sizeof(value_type);
   }
is_read_access()
template<typename T , int Dimensions, access::mode Mode, access::target Target> constexpr bool trisycl::detail::accessor< T, Dimensions, Mode, Target >::is_read_access () const inline
Test if the accessor has a read access right.
Todo:
Strangely, it is not really constexpr because it is not a static method...
Todo:
to move in the access::mode enum class and add to the specification ?
Definition at line 345 of file accessor.hpp.
References trisycl::access::discard_read_write, trisycl::access::read, and trisycl::access::read_write.
{
     return Mode == access::mode::read
       || Mode == access::mode::read_write
       || Mode == access::mode::discard_read_write;
   }
is_write_access()
template<typename T , int Dimensions, access::mode Mode, access::target Target> constexpr bool trisycl::detail::accessor< T, Dimensions, Mode, Target >::is_write_access () const inline
Test if the accessor has a write access right.
Todo:
Strangely, it is not really constexpr because it is not a static method...
Todo:
to move in the access::mode enum class and add to the specification ?
Definition at line 360 of file accessor.hpp.
References trisycl::access::discard_read_write, trisycl::access::discard_write, trisycl::access::read_write, and trisycl::access::write.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::accessor().
{
     return Mode == access::mode::write
       || Mode == access::mode::read_write
       || Mode == access::mode::discard_write
       || Mode == access::mode::discard_read_write;
   }
operator*() [1/2]
template<typename T , int Dimensions, access::mode Mode, access::target Target> reference trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator* () inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add in the specification
Definition at line 311 of file accessor.hpp.
{
     return *array.data();
   }
operator*() [2/2]
template<typename T , int Dimensions, access::mode Mode, access::target Target> reference trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator* () const inline
Get the first element of the accessor.
Useful with an accessor on a scalar for example.
Todo:
Add in the specification?
Todo:
Add the concept of 0-dim buffer and accessor for scalar and use an implicit conversion to value_type reference to access the value with the accessor?
Definition at line 326 of file accessor.hpp.
{
     return *array.data();
   }
operator[]() [1/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> reference trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (std::size_t index) inline
Use the accessor with integers à la [][][].
Use array_view_type::reference instead of auto& because it does not work in some dimensions.
Definition at line 249 of file accessor.hpp.
{
     return array[index];
   }
operator[]() [2/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> reference trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (std::size_t index) const inline
Use the accessor with integers à la [][][].
Use array_view_type::reference instead of auto& because it does not work in some dimensions.
Definition at line 259 of file accessor.hpp.
{
     return array[index];
   }
operator[]() [3/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto& trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (id< dimensionality > index) inline
To use the accessor with [id<>].
Definition at line 265 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
{
     return array(index);
   }
operator[]() [4/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto& trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (id< dimensionality > index) const inline
To use the accessor with [id<>].
Definition at line 271 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
{
     return array(index);
   }
operator[]() [5/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto& trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (item< dimensionality > index) inline
To use an accessor with [item<>].
Definition at line 277 of file accessor.hpp.
{
     return (*this)[index.get()];
   }
operator[]() [6/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto& trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (item< dimensionality > index) const inline
To use an accessor with [item<>].
Definition at line 283 of file accessor.hpp.
{
     return (*this)[index.get()];
   }
operator[]() [7/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto& trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (nd_item< dimensionality > index) inline
To use an accessor with an [nd_item<>].
Todo:
Add in the specification because used by HPC-GPU slide 22
Definition at line 292 of file accessor.hpp.
{
     return (*this)[index.get_global()];
   }
operator[]() [8/8]
template<typename T , int Dimensions, access::mode Mode, access::target Target> auto& trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[] (nd_item< dimensionality > index) const inline
To use an accessor with an [nd_item<>].
Todo:
Add in the specification because used by HPC-GPU slide 22
Definition at line 300 of file accessor.hpp.
{
     return (*this)[index.get_global()];
   }
rbegin()
template<typename T , int Dimensions, access::mode Mode, access::target Target> reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::rbegin () const inline
Definition at line 427 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::rbegin().
{
     return const_cast<writable_array_view_type &>(array).rbegin();
   }
register_accessor()
template<typename T , int Dimensions, access::mode Mode, access::target Target> void trisycl::detail::accessor< T, Dimensions, Mode, Target >::register_accessor () inline
Register the accessor once a std::shared_ptr is created on it.
This is to be called from outside once the object is created. It has been tried directly inside the contructor, but calling shared_from_this() from the constructor dead-lock with libstdc++6
Todo:
Double-check with the C++ committee on this issue.
Definition at line 173 of file accessor.hpp.
References trisycl::detail::task::add_postlude(), trisycl::detail::task::add_prelude(), trisycl::detail::task::get_queue(), trisycl::detail::task::register_accessor(), and trisycl::detail::accessor_base::set_order().
{
     if (!task->get_queue()->is_host()) {
       // To keep alive this accessor in the following lambdas
       auto acc = this->shared_from_this();
       // Attach the accessor to the task and get its order
       set_order(task->register_accessor(acc));
 #ifdef TRISYCL_OPENCL
       /* Before running the kernel, make sure the cl_mem behind this
          accessor is up-to-date on the device if needed and pass it to
          the kernel */
       task->add_prelude([=] {
           acc->copy_in_cl_buffer();
         });
       // After running the kernel, deal with some copy-back if needed
       task->add_postlude([=] {
           /* Even if this function does nothing, it is required to
              have the capture of acc to keep the accessor alive across
              the kernel execution up to the execution postlude */
           acc->copy_back_cl_buffer();
         });
 #endif
     }
   }
rend()
template<typename T , int Dimensions, access::mode Mode, access::target Target> reverse_iterator trisycl::detail::accessor< T, Dimensions, Mode, Target >::rend () const inline
Definition at line 433 of file accessor.hpp.
References trisycl::detail::accessor< T, Dimensions, Mode, Target >::array.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::rend().
{
     return const_cast<writable_array_view_type &>(array).rend();
   }
Member Data Documentation
array
template<typename T , int Dimensions, access::mode Mode, access::target Target> array_view_type trisycl::detail::accessor< T, Dimensions, Mode, Target >::array mutable private
The way the buffer is really accessed.
Use a mutable member because the accessor needs to be captured by value in the lambda which is then read-only. This is to avoid the user to use mutable lambda or have a lot of const_cast as previously done in this implementation
Definition at line 90 of file accessor.hpp.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::begin(), trisycl::detail::accessor< T, Dimensions, Mode, Target >::begin(), trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::end(), trisycl::detail::accessor< T, Dimensions, Mode, Target >::end(), trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::operator[](), trisycl::detail::accessor< T, Dimensions, Mode, Target >::operator[](), trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::rbegin(), trisycl::detail::accessor< T, Dimensions, Mode, Target >::rbegin(), trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::rend(), and trisycl::detail::accessor< T, Dimensions, Mode, Target >::rend().
buf
template<typename T , int Dimensions, access::mode Mode, access::target Target> std::shared_ptr<detail::buffer<T, Dimensions> > trisycl::detail::accessor< T, Dimensions, Mode, Target >::buf private
Keep a reference to the accessed buffer.
Beware that it owns the buffer, which means that the accessor has to be destroyed to release the buffer and potentially unblock a kernel at the end of its execution
Definition at line 74 of file accessor.hpp.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_buffer().
dimensionality
template<typename T , int Dimensions, access::mode Mode, access::target Target> constexpr auto trisycl::detail::accessor< T, Dimensions, Mode, Target >::dimensionality = Dimensions static
Todo:
in the specification: store the dimension for user request
Todo:
Use another name, such as from C++17 committee discussions.
Definition at line 98 of file accessor.hpp.
handler
template<typename T , int Dimensions, access::mode Mode, access::target Target> friend trisycl::detail::accessor< T, Dimensions, Mode, Target >::handler private
Definition at line 453 of file accessor.hpp.
trisycl::detail::buffer
class trisycl::detail::buffer
template<typename T, int Dimensions = 1>
class trisycl::detail::buffer< T, Dimensions >
A SYCL buffer is a multidimensional variable length array (à la C99 VLA or even Fortran before) that is used to store data to work on.
In the case we initialize it from a pointer, for now we just wrap the data with boost::multi_array_ref to provide the VLA semantics without any storage.
Definition at line 35 of file accessor.hpp.
Public Types
using element = T
using value_type = T
using non_const_value_type = std::remove_const_t< value_type >
Public Member Functions
buffer (const range< Dimensions > &r)
Create a new read-write buffer of size.
buffer (T *host_data, const range< Dimensions > &r)
Create a new read-write buffer from.
template<typename Dependent = T, typename = std::enable_if_t<!std::is_const<Dependent>::value>>
buffer (const T *host_data, const range< Dimensions > &r)
Create a new read-only buffer from.
buffer (shared_ptr_class< T > &host_data, const range< Dimensions > &r)
Create a new buffer with associated memory, using the data in host_data.
template<typename Iterator >
buffer (Iterator start_iterator, Iterator end_iterator)
Create a new allocated 1D buffer from the given elements.
~buffer ()
Create a new sub-buffer without allocation to have separate accessors later.
void mark_as_written ()
Enforce the buffer to be considered as being modified.
template<access::mode Mode, access::target Target = access::target::host_buffer>
void track_access_mode ()
This method is to be called whenever an accessor is created.
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
auto get_count () const
Returns the total number of elements in the buffer.
auto get_size () const
Returns the size of the buffer storage in bytes.
void set_final_data (std::weak_ptr< T > final_data)
Set the weak pointer as destination for write-back on buffer destruction.
void set_final_data (std::nullptr_t)
Disable write-back on buffer destruction as an iterator.
template<typename Iterator , typename ValueType = typename std::iterator_traits<Iterator>::value_type>
void set_final_data (Iterator final_data)
Provide destination for write-back on buffer destruction as an iterator.
boost::optional< std::future< void > > get_destructor_future ()
Get a future to wait from inside the trisycl::buffer in case there is something to copy back to the host.
Public Member Functions inherited from trisycl::detail::buffer_base
buffer_base ()
Create a buffer base and marks the host context as the context that holds the most recent version of the data.
~buffer_base ()
The destructor waits for not being used anymore.
void wait ()
Wait for this buffer to be ready, which is no longer in use.
void use ()
Mark this buffer in use by a task.
void release ()
A task has released the buffer.
std::shared_ptr< detail::task > get_latest_producer ()
Return the latest producer for the buffer.
std::shared_ptr< detail::task > set_latest_producer (std::weak_ptr< detail::task > newer_latest_producer)
Return the latest producer for the buffer and set another future producer.
std::shared_ptr< detail::task > add_to_task (handler *command_group_handler, bool is_write_mode)
Add a buffer to the task running the command group.
bool is_data_up_to_date (const trisycl::context &ctx)
Check if the data of this buffer is up-to-date in a certain context.
bool is_cached (const trisycl::context &ctx)
Check if the buffer is already cached for a certain context.
void create_in_cache (const trisycl::context &ctx, size_t size, cl_mem_flags flags, void *data)
Create a boost::compute::buffer for this trisycl::buffer in the cache and associate it with a given context.
void sync_with_host (std::size_t size, void *data)
Transfer the most up-to-date version of the data to the host if the host version is not already up-to-date.
void update_buffer_state (const trisycl::context &target_ctx, access::mode mode, std::size_t size, void *data)
When a transfer is requested this function is called, it will update the state of the buffer according to the context in which the accessor is created and the access mode.
boost::compute::buffer get_cl_buffer (const trisycl::context &context)
Returns the cl_buffer for a given context.
Private Member Functions
auto allocate_buffer (const range< Dimensions > &r)
Allocate uninitialized buffer memory.
void deallocate_buffer ()
Deallocate buffer memory if required.
template<typename BaseType = T, typename DataType >
void call_update_buffer_state (trisycl::context ctx, access::mode mode, size_t size, DataType *data, std::enable_if_t<!std::is_const< BaseType > ::value > *=0)
Function pair to work around the fact that T might be a const type.
template<typename BaseType = T, typename DataType >
void call_update_buffer_state (trisycl::context ctx, access::mode mode, size_t size, DataType *data, std::enable_if_t< std::is_const< BaseType > ::value > *=0)
Version of call_update_buffer_state that does nothing.
Private Attributes
std::allocator< non_const_value_type > alloc
The allocator to be used when some memory is needed.
boost::multi_array_ref< value_type, Dimensions > access
This is the multi-dimensional interface to the data that may point to either allocation in the case of storage managed by SYCL itself or to some other memory location in the case of host memory or storage<> abstraction use.
non_const_value_type * allocation = nullptr
If some allocation is requested on the host for the buffer memory, this is where the memory is attached to.
boost::optional< std::function< void(void)> > final_write_back
shared_ptr_class< T > input_shared_pointer
bool data_host = false
bool copy_if_modified = false
bool modified = false
trisycl::context host_context { trisycl::device {} }
Friends
template<typename U , int D, access::mode Mode, access::target Target>
class detail::accessor
Additional Inherited Members
Public Attributes inherited from trisycl::detail::buffer_base
std::atomic< size_t > number_of_users
std::weak_ptr< detail::task > latest_producer
Track the latest task to produce this buffer.
std::mutex latest_producer_mutex
To protect the access to latest_producer.
std::condition_variable ready
To signal when this buffer ready.
std::mutex ready_mutex
To protect the access to the condition variable.
boost::optional< std::promise< void > > notify_buffer_destructor
If the SYCL user buffer destructor is blocking, use this to block until this buffer implementation is destroyed.
std::unordered_set< trisycl::context > fresh_ctx
To track contexts in which the data is up-to-date.
std::unordered_map< trisycl::context, boost::compute::buffer > buffer_cache
Buffer-side cache that keeps the boost::compute::buffer (and the underlying cl_buffer) so that if the buffer already exists inside the same context it is not recreated.
Member Typedef Documentation
element
template<typename T, int Dimensions = 1> using trisycl::detail::buffer< T, Dimensions >::element = T
Definition at line 47 of file buffer.hpp.
non_const_value_type
template<typename T, int Dimensions = 1> using trisycl::detail::buffer< T, Dimensions >::non_const_value_type = std::remove_const_t<value_type>
Definition at line 51 of file buffer.hpp.
value_type
template<typename T, int Dimensions = 1> using trisycl::detail::buffer< T, Dimensions >::value_type = T
Definition at line 48 of file buffer.hpp.
Constructor & Destructor Documentation
buffer() [1/5]
template<typename T, int Dimensions = 1> trisycl::detail::buffer< T, Dimensions >::buffer (const range< Dimensions > & r) inline
Create a new read-write buffer of size.
Parameters
r
Definition at line 107 of file buffer.hpp.
References trisycl::detail::buffer< T, Dimensions >::allocate_buffer().
 : access { allocate_buffer(r) } {}
buffer() [2/5]
template<typename T, int Dimensions = 1> trisycl::detail::buffer< T, Dimensions >::buffer (T * host_data, const range< Dimensions > & r) inline
Create a new read-write buffer from.
Parameters
host_data of size
r without further allocation
Definition at line 112 of file buffer.hpp.
                                                    :
     access { host_data, r },
     data_host { true }
   {}
buffer() [3/5]
template<typename T, int Dimensions = 1> template<typename Dependent = T, typename = std::enable_if_t<!std::is_const<Dependent>::value>> trisycl::detail::buffer< T, Dimensions >::buffer (const T * host_data, const range< Dimensions > & r) inline
Create a new read-only buffer from.
Parameters
host_data of size
r without further allocation
If the buffer is non const, use a copy-on-write mechanism with internal writable memory.
Todo:
Clarify the semantics in the spec. What happens if the host change the host_data after buffer creation?
Only enable this constructor if the value type is not constant, because if it is constant, the buffer is constant too.
Definition at line 132 of file buffer.hpp.
                                                          :
     /* The buffer is read-only, even if the internal multidimensional
        wrapper is not. If a write accessor is requested, there should
        be a copy on write. So this pointer should not be written and
        this const_cast should be acceptable. */
     access { const_cast<T *>(host_data), r },
     data_host { true },
     /* Set copy_if_modified to true, so that if an accessor with write
        access is created, data are copied before to be modified. */
     copy_if_modified { true }
   {}
buffer() [4/5]
template<typename T, int Dimensions = 1> trisycl::detail::buffer< T, Dimensions >::buffer (shared_ptr_class< T > & host_data, const range< Dimensions > & r) inline
Create a new buffer with associated memory, using the data in host_data.
The ownership of the host_data is shared between the runtime and the user. In order to enable both the user application and the SYCL runtime to use the same pointer, a trisycl::mutex_class is used.
Definition at line 153 of file buffer.hpp.
                                                                      :
     access { host_data.get(), r },
     input_shared_pointer { host_data },
     data_host { true }
   {}
buffer() [5/5]
template<typename T, int Dimensions = 1> template<typename Iterator > trisycl::detail::buffer< T, Dimensions >::buffer (Iterator start_iterator, Iterator end_iterator) inline
Create a new allocated 1D buffer from the given elements.
Definition at line 162 of file buffer.hpp.
References trisycl::detail::buffer< T, Dimensions >::allocate_buffer().
                                                          :
     access { allocate_buffer(std::distance(start_iterator, end_iterator)) }
     {
       /* Then assign allocation since this is the only multi_array
          method with this iterator interface */
       access.assign(start_iterator, end_iterator);
     }
~buffer()
template<typename T, int Dimensions = 1> trisycl::detail::buffer< T, Dimensions >::~buffer () inline
Create a new sub-buffer without allocation to have separate accessors later.
Todo:
To implement and deal with reference counting buffer(buffer<T, Dimensions> b, index<Dimensions> base_index, range<Dimensions> sub_range)
Todo:
Allow CLHPP objects too?
The buffer content may be copied back on destruction to some final location
Definition at line 191 of file buffer.hpp.
References trisycl::detail::buffer< T, Dimensions >::call_update_buffer_state(), trisycl::detail::buffer< T, Dimensions >::deallocate_buffer(), and trisycl::access::read.
             {
 #ifdef TRISYCL_OPENCL
     /* We ensure that the host has the most up-to-date version of the data
        before the buffer is destroyed. This is necessary because we do not
        systematically transfer the data back from a device with
        \c copy_back_cl_buffer any more.
        \todo Optimize for the case the buffer is not based on host memory
     */
     auto size = access.num_elements() * sizeof(value_type);
     call_update_buffer_state(host_context, access::mode::read, size, access.data());
 #endif
     if (modified && final_write_back)
       (*final_write_back)();
     // Allocate explicitly allocated memory if required
     deallocate_buffer();
   }
Member Function Documentation
allocate_buffer()
template<typename T, int Dimensions = 1> auto trisycl::detail::buffer< T, Dimensions >::allocate_buffer (const range< Dimensions > & r) inline private
Allocate uninitialized buffer memory.
Definition at line 336 of file buffer.hpp.
References trisycl::detail::buffer< T, Dimensions >::allocation, and trisycl::range< Dimensions >::size().
Referenced by trisycl::detail::buffer< T, Dimensions >::buffer(), and trisycl::detail::buffer< T, Dimensions >::track_access_mode().
{
     auto count = r.size();
     // Allocate uninitialized memory
     allocation = alloc.allocate(count);
     return boost::multi_array_ref<value_type, Dimensions> { allocation, r };
   }
call_update_buffer_state() [1/2]
template<typename T, int Dimensions = 1> template<typename BaseType = T, typename DataType > void trisycl::detail::buffer< T, Dimensions >::call_update_buffer_state (trisycl::context ctx, access::mode mode, size_t size, DataType * data, std::enable_if_t<!std::is_const< BaseType > ::value > * = 0) inline private
Function pair to work around the fact that T might be a const type.
We call update_buffer_state only if T is not const, we have to use enable_if otherwise the compiler will try to cast const void* to void* if we create a buffer with a const type
Todo:
Use if constexpr when it is available with C++17
Definition at line 359 of file buffer.hpp.
References trisycl::detail::buffer_base::update_buffer_state().
Referenced by trisycl::detail::buffer< T, Dimensions >::~buffer().
{
     update_buffer_state(ctx, mode, size, data);
   }
call_update_buffer_state() [2/2]
template<typename T, int Dimensions = 1> template<typename BaseType = T, typename DataType > void trisycl::detail::buffer< T, Dimensions >::call_update_buffer_state (trisycl::context ctx, access::mode mode, size_t size, DataType * data, std::enable_if_t< std::is_const< BaseType > ::value > * = 0) inline private
Version of call_update_buffer_state that does nothing.
It is called if the type of the data in the buffer is const
Definition at line 371 of file buffer.hpp.
                                              { }
deallocate_buffer()
template<typename T, int Dimensions = 1> void trisycl::detail::buffer< T, Dimensions >::deallocate_buffer () inline private
Deallocate buffer memory if required.
Definition at line 345 of file buffer.hpp.
Referenced by trisycl::detail::buffer< T, Dimensions >::~buffer().
{
     if (allocation)
       alloc.deallocate(allocation, access.num_elements());
   }
get_count()
template<typename T, int Dimensions = 1> auto trisycl::detail::buffer< T, Dimensions >::get_count () const inline
Returns the total number of elements in the buffer.
Equal to get_range()[0] * ... * get_range()[Dimensions-1].
Definition at line 279 of file buffer.hpp.
Referenced by trisycl::detail::buffer< T, Dimensions >::get_size().
{
     return access.num_elements();
   }
get_destructor_future()
template<typename T, int Dimensions = 1> boost::optional<std::future<void> > trisycl::detail::buffer< T, Dimensions >::get_destructor_future () inline
Get a future to wait from inside the trisycl::buffer in case there is something to copy back to the host.
Returns
A future in the optional if there is something to wait for, otherwise an empty optional
Todo:
Make the function private again
Definition at line 386 of file buffer.hpp.
References trisycl::none, and trisycl::detail::buffer_base::notify_buffer_destructor.
{
     /* If there is only 1 shared_ptr user of the buffer, this is the
        caller of this function, the \c buffer_waiter, so there is no
        need to get a \ future otherwise there will be a dead-lock if
        there is only 1 thread waiting for itself.
        Since \c use_count() is applied to a \c shared_ptr just created
        for this purpose, it actually increase locally the count by 1,
        so check for 1 + 1 use count instead...
     */
     // If the buffer's destruction triggers a write-back, wait
     if ((shared_from_this().use_count() > 2) &&
         modified && (final_write_back || data_host)) {
       // Create a promise to wait for
       notify_buffer_destructor = std::promise<void> {};
       // And return the future to wait for it
       return notify_buffer_destructor->get_future();
     }
     return boost::none;
   }
get_range()
template<typename T, int Dimensions = 1> auto trisycl::detail::buffer< T, Dimensions >::get_range () const inline
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
Definition at line 261 of file buffer.hpp.
Referenced by trisycl::detail::buffer< T, Dimensions >::track_access_mode().
{
     /* Interpret the shape which is a pointer to the first element as an
        array of Dimensions elements so that the range<Dimensions>
        constructor is happy with this collection
        \todo Add also a constructor in range<> to accept a const
        std::size_t *?
     */
     return range<Dimensions> {
       *(const std::size_t (*)[Dimensions])(access.shape())
         };
   }
get_size()
template<typename T, int Dimensions = 1> auto trisycl::detail::buffer< T, Dimensions >::get_size () const inline
Returns the size of the buffer storage in bytes.
Todo:
rename to something else. In http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0122r0.pdf it is named bytes() for example
Definition at line 290 of file buffer.hpp.
References trisycl::detail::buffer< T, Dimensions >::get_count().
{
     return get_count()*sizeof(value_type);
   }
mark_as_written()
template<typename T, int Dimensions = 1> void trisycl::detail::buffer< T, Dimensions >::mark_as_written () inline
Enforce the buffer to be considered as being modified.
Same as creating an accessor with write access.
Definition at line 213 of file buffer.hpp.
References trisycl::access::host_buffer.
{
     modified = true;
   }
set_final_data() [1/3]
template<typename T, int Dimensions = 1> void trisycl::detail::buffer< T, Dimensions >::set_final_data (std::weak_ptr< T > final_data) inline
Set the weak pointer as destination for write-back on buffer destruction.
Definition at line 298 of file buffer.hpp.
{
     // Capture this by reference is enough since the buffer will still exist
     final_write_back = [this, final_data = std::move(final_data)] {
       if (auto sptr = final_data.lock()) {
         std::copy_n(access.data(), access.num_elements(), sptr.get());
       }
     };
   }
set_final_data() [2/3]
template<typename T, int Dimensions = 1> void trisycl::detail::buffer< T, Dimensions >::set_final_data (std::nullptr_t) inline
Disable write-back on buffer destruction as an iterator.
Definition at line 310 of file buffer.hpp.
References trisycl::none.
{
     final_write_back = boost::none;
   }
set_final_data() [3/3]
template<typename T, int Dimensions = 1> template<typename Iterator , typename ValueType = typename std::iterator_traits<Iterator>::value_type> void trisycl::detail::buffer< T, Dimensions >::set_final_data (Iterator final_data) inline
Provide destination for write-back on buffer destruction as an iterator.
Definition at line 321 of file buffer.hpp.
{
     /*   using type_ = typename iterator_value_type<Iterator>::value_type;
          static_assert(std::is_same<type_, T>::value, "buffer type mismatch");
          static_assert(!(std::is_const<type_>::value),
                        "const iterator is not allowed");*/
     // Capture this by reference is enough since the buffer will still exist
     final_write_back = [this, final_data = std::move(final_data)] {
       std::copy_n(access.data(), access.num_elements(), final_data);
     };
   }
track_access_mode()
template<typename T, int Dimensions = 1> template<access::mode Mode, access::target Target = access::target::host_buffer> void trisycl::detail::buffer< T, Dimensions >::track_access_mode () inline
This method is to be called whenever an accessor is created.
Its current purpose is to track if an accessor with write access is created and acting accordingly.
Definition at line 225 of file buffer.hpp.
References trisycl::detail::buffer< T, Dimensions >::access, trisycl::detail::buffer< T, Dimensions >::allocate_buffer(), trisycl::access::atomic, trisycl::access::discard_read_write, trisycl::access::discard_write, trisycl::detail::buffer< T, Dimensions >::get_range(), trisycl::access::read_write, and trisycl::access::write.
{
     // test if write access is required
     if (   Mode == access::mode::write
         || Mode == access::mode::read_write
         || Mode == access::mode::discard_write
         || Mode == access::mode::discard_read_write
         || Mode == access::mode::atomic
        ) {
       modified = true;
       if (copy_if_modified) {
         // Implement the allocate & copy-on-write optimization
         copy_if_modified = false;
         data_host = false;
         // Since \c allocate_buffer() changes \c access, keep a copy first
         auto current_access = access;
         /* The range is actually computed from \c access itself, so
            save it */
         auto current_range = get_range();
         allocate_buffer(current_range);
         /* Then move everything to the new place
            \todo Use std::uninitialized_move instead, when we switch
            to full C++17
         */
         std::copy(current_access.begin(),
                   current_access.end(),
                   access.begin());
       }
     }
   }
Friends And Related Function Documentation
detail::accessor
template<typename T, int Dimensions = 1> template<typename U , int D, access::mode Mode, access::target Target> friend class detail::accessor friend
Definition at line 61 of file buffer.hpp.
Member Data Documentation
access
template<typename T, int Dimensions = 1> boost::multi_array_ref<value_type, Dimensions> trisycl::detail::buffer< T, Dimensions >::access private
This is the multi-dimensional interface to the data that may point to either allocation in the case of storage managed by SYCL itself or to some other memory location in the case of host memory or storage<> abstraction use.
Definition at line 74 of file buffer.hpp.
Referenced by trisycl::detail::buffer< T, Dimensions >::track_access_mode().
alloc
template<typename T, int Dimensions = 1> std::allocator<non_const_value_type> trisycl::detail::buffer< T, Dimensions >::alloc private
The allocator to be used when some memory is needed.
Todo:
Implement user-provided allocator
Definition at line 67 of file buffer.hpp.
allocation
template<typename T, int Dimensions = 1> non_const_value_type* trisycl::detail::buffer< T, Dimensions >::allocation = nullptr private
If some allocation is requested on the host for the buffer memory, this is where the memory is attached to.
Note that this is uninitialized memory, as stated in SYCL specification.
Definition at line 82 of file buffer.hpp.
Referenced by trisycl::detail::buffer< T, Dimensions >::allocate_buffer().
copy_if_modified
template<typename T, int Dimensions = 1> bool trisycl::detail::buffer< T, Dimensions >::copy_if_modified = false private
Definition at line 97 of file buffer.hpp.
data_host
template<typename T, int Dimensions = 1> bool trisycl::detail::buffer< T, Dimensions >::data_host = false private
Definition at line 94 of file buffer.hpp.
final_write_back
template<typename T, int Dimensions = 1> boost::optional<std::function<void(void)> > trisycl::detail::buffer< T, Dimensions >::final_write_back private
Definition at line 87 of file buffer.hpp.
host_context
template<typename T, int Dimensions = 1> trisycl::context trisycl::detail::buffer< T, Dimensions >::host_context { trisycl::device {} } private
Definition at line 102 of file buffer.hpp.
input_shared_pointer
template<typename T, int Dimensions = 1> shared_ptr_class<T> trisycl::detail::buffer< T, Dimensions >::input_shared_pointer private
Definition at line 90 of file buffer.hpp.
modified
template<typename T, int Dimensions = 1> bool trisycl::detail::buffer< T, Dimensions >::modified = false private
Definition at line 100 of file buffer.hpp.
trisycl::detail::buffer_base
struct trisycl::detail::buffer_base
Factorize some template independent buffer aspects in a base class.
Definition at line 49 of file buffer_base.hpp.
Public Member Functions
buffer_base ()
Create a buffer base and marks the host context as the context that holds the most recent version of the data.
~buffer_base ()
The destructor waits for not being used anymore.
void wait ()
Wait for this buffer to be ready, which is no longer in use.
void use ()
Mark this buffer in use by a task.
void release ()
A task has released the buffer.
std::shared_ptr< detail::task > get_latest_producer ()
Return the latest producer for the buffer.
std::shared_ptr< detail::task > set_latest_producer (std::weak_ptr< detail::task > newer_latest_producer)
Return the latest producer for the buffer and set another future producer.
std::shared_ptr< detail::task > add_to_task (handler *command_group_handler, bool is_write_mode)
Add a buffer to the task running the command group.
bool is_data_up_to_date (const trisycl::context &ctx)
Check if the data of this buffer is up-to-date in a certain context.
bool is_cached (const trisycl::context &ctx)
Check if the buffer is already cached for a certain context.
void create_in_cache (const trisycl::context &ctx, size_t size, cl_mem_flags flags, void *data)
Create a boost::compute::buffer for this trisycl::buffer in the cache and associate it with a given context.
void sync_with_host (std::size_t size, void *data)
Transfer the most up-to-date version of the data to the host if the host version is not already up-to-date.
void update_buffer_state (const trisycl::context &target_ctx, access::mode mode, std::size_t size, void *data)
When a transfer is requested this function is called, it will update the state of the buffer according to the context in which the accessor is created and the access mode.
boost::compute::buffer get_cl_buffer (const trisycl::context &context)
Returns the cl_buffer for a given context.
Public Attributes
std::atomic< size_t > number_of_users
std::weak_ptr< detail::task > latest_producer
Track the latest task to produce this buffer.
std::mutex latest_producer_mutex
To protect the access to latest_producer.
std::condition_variable ready
To signal when this buffer ready.
std::mutex ready_mutex
To protect the access to the condition variable.
boost::optional< std::promise< void > > notify_buffer_destructor
If the SYCL user buffer destructor is blocking, use this to block until this buffer implementation is destroyed.
std::unordered_set< trisycl::context > fresh_ctx
To track contexts in which the data is up-to-date.
std::unordered_map< trisycl::context, boost::compute::buffer > buffer_cache
Buffer-side cache that keeps the boost::compute::buffer (and the underlying cl_buffer) so that if the buffer already exists inside the same context it is not recreated.
Constructor & Destructor Documentation
buffer_base()
trisycl::detail::buffer_base::buffer_base () inline
Create a buffer base and marks the host context as the context that holds the most recent version of the data.
Todo:
Use lazy allocation for the context tracking set
Definition at line 86 of file buffer_base.hpp.
                 : number_of_users { 0 },
                   fresh_ctx { trisycl::context {} } {}
~buffer_base()
trisycl::detail::buffer_base::~buffer_base () inline
The destructor waits for not being used anymore.
Definition at line 91 of file buffer_base.hpp.
References wait().
                  {
     wait();
     // If there is the last SYCL user buffer waiting, notify it
     if (notify_buffer_destructor)
       notify_buffer_destructor->set_value();
   }
Member Function Documentation
add_to_task()
std::shared_ptr<detail::task> trisycl::detail::buffer_base::add_to_task (handler * command_group_handler, bool is_write_mode) inline
Add a buffer to the task running the command group.
Definition at line 153 of file buffer_base.hpp.
References trisycl::detail::add_buffer_to_task().
{
     return add_buffer_to_task(command_group_handler,
                               shared_from_this(),
                               is_write_mode);
   }
create_in_cache()
void trisycl::detail::buffer_base::create_in_cache (const trisycl::context & ctx, size_t size, cl_mem_flags flags, void * data) inline
Create a boost::compute::buffer for this trisycl::buffer in the cache and associate it with a given context.
Definition at line 176 of file buffer_base.hpp.
References trisycl::context::get_boost_compute().
Referenced by update_buffer_state().
{
     buffer_cache[ctx] = boost::compute::buffer
       { ctx.get_boost_compute(),
         size,
         flags,
         data
       };
   }
get_cl_buffer()
boost::compute::buffer trisycl::detail::buffer_base::get_cl_buffer (const trisycl::context & context) inline
Returns the cl_buffer for a given context.
Definition at line 312 of file buffer_base.hpp.
{
     return buffer_cache[context];
   }
get_latest_producer()
std::shared_ptr<detail::task> trisycl::detail::buffer_base::get_latest_producer () inline
Return the latest producer for the buffer.
Definition at line 130 of file buffer_base.hpp.
{
     std::lock_guard<std::mutex> lg { latest_producer_mutex };
     // Return the valid shared_ptr to the task, if any
     return latest_producer.lock();
   }
is_cached()
bool trisycl::detail::buffer_base::is_cached (const trisycl::context & ctx) inline
Check if the buffer is already cached for a certain context.
Definition at line 168 of file buffer_base.hpp.
Referenced by update_buffer_state().
{
     return buffer_cache.count(ctx);
   }
is_data_up_to_date()
bool trisycl::detail::buffer_base::is_data_up_to_date (const trisycl::context & ctx) inline
Check if the data of this buffer is up-to-date in a certain context.
Definition at line 162 of file buffer_base.hpp.
Referenced by sync_with_host(), and update_buffer_state().
{
     return fresh_ctx.count(ctx);
   }
release()
void trisycl::detail::buffer_base::release () inline
A task has released the buffer.
Definition at line 117 of file buffer_base.hpp.
                  {
     std::unique_lock<std::mutex> lock { ready_mutex };
     if (--number_of_users == 0) {
       // Micro-optimization: unlock before the notification
       // https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all
       lock.unlock();
       // Notify the host consumers or the buffer destructor that it is ready
       ready.notify_all();
     }
   }
set_latest_producer()
std::shared_ptr<detail::task> trisycl::detail::buffer_base::set_latest_producer (std::weak_ptr< detail::task > newer_latest_producer) inline
Return the latest producer for the buffer and set another future producer.
Definition at line 141 of file buffer_base.hpp.
{
     std::lock_guard<std::mutex> lg { latest_producer_mutex };
     using std::swap;
     swap(newer_latest_producer, latest_producer);
     // Return the valid shared_ptr to the previous producing task, if any
     return newer_latest_producer.lock();
   }
sync_with_host()
void trisycl::detail::buffer_base::sync_with_host (std::size_t size, void * data) inline
Transfer the most up-to-date version of the data to the host if the host version is not already up-to-date.
Definition at line 190 of file buffer_base.hpp.
References trisycl::detail::host_context::get_boost_queue(), and is_data_up_to_date().
Referenced by update_buffer_state().
{
     trisycl::context host_context;
     if (!is_data_up_to_date(host_context) && !fresh_ctx.empty()) {
       /* We know that the context(s) in \c fresh_ctx hold the most recent
          version of the buffer
       */
       auto fresh_context = *(fresh_ctx.begin());
       auto fresh_q = fresh_context.get_boost_queue();
       fresh_q.enqueue_read_buffer(buffer_cache[fresh_context], 0, size, data);
       fresh_ctx.insert(host_context);
     }
   }
update_buffer_state()
void trisycl::detail::buffer_base::update_buffer_state (const trisycl::context & target_ctx, access::mode mode, std::size_t size, void * data) inline
When a transfer is requested this function is called, it will update the state of the buffer according to the context in which the accessor is created and the access mode.
Definition at line 208 of file buffer_base.hpp.
References trisycl::access::atomic, create_in_cache(), trisycl::access::discard_read_write, trisycl::access::discard_write, trisycl::context::get_boost_queue(), is_cached(), is_data_up_to_date(), trisycl::context::is_host(), trisycl::access::read, trisycl::access::read_write, sync_with_host(), and trisycl::access::write.
Referenced by trisycl::detail::buffer< T, Dimensions >::call_update_buffer_state().
{
     /* The \c cl_buffer we put in the cache might get accessed again in the
        future, this means that we have to always to create it in read/write
        mode to be able to write to it if it is accessed through a
        write accessor in the future
      */
     auto constexpr flag = CL_MEM_READ_WRITE;
     /* The buffer is accessed in read mode, we want to transfer the data only if
        necessary. We start a transfer if the data on the target context is not
        up to date and then update the fresh context set.
      */
     if (mode == access::mode::read) {
       if (is_data_up_to_date(target_ctx))
         // If read mode and the data is up-to-date there is nothing to do
         return;
       // The data is not up-to-date, we need a transfer
       // We also want to be sure that the host holds the most recent data
       sync_with_host(size, data);
       if (!target_ctx.is_host()) {
         // If the target context is a device context
         if (!is_cached(target_ctx)) {
           /* If not cached, we create the buffer and copy the data
              at the same time
           */
           create_in_cache(target_ctx, size,
                           (flag | CL_MEM_COPY_HOST_PTR), data);
           fresh_ctx.insert(target_ctx);
           return;
         }
         /* Else we transfer the data to the existing buffer associated
            with the target context buffer
         */
         auto q = target_ctx.get_boost_queue();
         q.enqueue_write_buffer(buffer_cache[target_ctx], 0, size, data);
         fresh_ctx.insert(target_ctx);
       }
       return;
     }
     /* The buffer might be written to, this means that we have to consider
        every version of the data obsolete except in the target context
        We go through the same process as in read mode but in addition
        we empty the fresh context set and just add the target context
        If the data is up to date on the target we just have to update
        the context set and nothing else
     */
     if (!is_data_up_to_date(target_ctx)) {
       if (   mode == access::mode::read_write
           || mode == access::mode::write
           || mode == access::mode::atomic) {
         // If the data is not up-to-date in the target context
         // We want to host to be up-to-date
         sync_with_host(size, data);
         if (!target_ctx.is_host()) {
           // If the target context is a device context
           if (!is_cached(target_ctx)) {
             create_in_cache(target_ctx, size,
                             (flag | CL_MEM_COPY_HOST_PTR), data);
           }
           else {
             // We update the buffer associated with the target context
             auto q = target_ctx.get_boost_queue();
             q.enqueue_write_buffer(buffer_cache[target_ctx], 0, size, data);
           }
         }
       }
       /* When in discard mode we don't need to transfer any data, we just create
          the \c cl_buffer if it doesn't exist in the cache
       */
       if (   mode == access::mode::discard_write
           || mode == access::mode::discard_read_write) {
         /* We only need to create the buffer if it doesn't exist
            but without copying any data because of the discard mode
         */
         if (!target_ctx.is_host() && !is_cached(target_ctx)) {
           // If the context doesn't exist we create it.
           /* We don't want to transfer any data so we don't
              add \c CL_MEM_COPY_HOST_PTR
           */
           create_in_cache(target_ctx, size, flag, 0);
         }
       }
     }
     /* Here we are sure that we are in some kind of write mode,
        we indicate that all contexts except the target context
        are not up-to-date anymore
     */
     fresh_ctx.clear();
     fresh_ctx.insert(target_ctx);
   }
use()
void trisycl::detail::buffer_base::use () inline
Mark this buffer in use by a task.
Definition at line 110 of file buffer_base.hpp.
References number_of_users.
              {
     // Increment the use count
     ++number_of_users;
   }
wait()
void trisycl::detail::buffer_base::wait () inline
Wait for this buffer to be ready, which is no longer in use.
Definition at line 100 of file buffer_base.hpp.
Referenced by ~buffer_base().
               {
     std::unique_lock<std::mutex> ul { ready_mutex };
     ready.wait(ul, [&] {
         // When there is no producer for this buffer, we are ready to use it
         return number_of_users == 0;
       });
   }
Member Data Documentation
buffer_cache
std::unordered_map<trisycl::context, boost::compute::buffer> trisycl::detail::buffer_base::buffer_cache
Buffer-side cache that keeps the boost::compute::buffer (and the underlying cl_buffer) so that if the buffer already exists inside the same context it is not recreated.
Definition at line 79 of file buffer_base.hpp.
fresh_ctx
std::unordered_set<trisycl::context> trisycl::detail::buffer_base::fresh_ctx
To track contexts in which the data is up-to-date.
Definition at line 72 of file buffer_base.hpp.
latest_producer
std::weak_ptr<detail::task> trisycl::detail::buffer_base::latest_producer
Track the latest task to produce this buffer.
Definition at line 55 of file buffer_base.hpp.
latest_producer_mutex
std::mutex trisycl::detail::buffer_base::latest_producer_mutex
To protect the access to latest_producer.
Definition at line 57 of file buffer_base.hpp.
notify_buffer_destructor
boost::optional<std::promise<void> > trisycl::detail::buffer_base::notify_buffer_destructor
If the SYCL user buffer destructor is blocking, use this to block until this buffer implementation is destroyed.
Use a void promise since there is no value to send, only waiting
Definition at line 69 of file buffer_base.hpp.
Referenced by trisycl::detail::buffer< T, Dimensions >::get_destructor_future().
number_of_users
std::atomic<size_t> trisycl::detail::buffer_base::number_of_users
Definition at line 52 of file buffer_base.hpp.
Referenced by use().
ready
std::condition_variable trisycl::detail::buffer_base::ready
To signal when this buffer ready.
Definition at line 60 of file buffer_base.hpp.
ready_mutex
std::mutex trisycl::detail::buffer_base::ready_mutex
To protect the access to the condition variable.
Definition at line 62 of file buffer_base.hpp.
trisycl::detail::buffer_waiter
class trisycl::detail::buffer_waiter
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>>
class trisycl::detail::buffer_waiter< T, Dimensions, Allocator >
A helper class to wait for the final buffer destruction if the conditions for blocking are met.
Definition at line 31 of file buffer_waiter.hpp.
Public Member Functions
buffer_waiter (detail::buffer< T, Dimensions > *b)
Create a new buffer_waiter on top of a detail::buffer.
~buffer_waiter ()
The buffer_waiter destructor waits for any data to be written back to the host, if any.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< buffer_waiter< T, Dimensions, Allocator >, detail::buffer< T, Dimensions > >
shared_ptr_implementation (std::shared_ptr< detail::buffer< T, Dimensions > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::buffer< T, Dimensions > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const buffer_waiter< T, Dimensions, Allocator > &other) const
Equality operator.
bool operator< (const buffer_waiter< T, Dimensions, Allocator > &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename buffer_waiter::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< buffer_waiter< T, Dimensions, Allocator >, detail::buffer< T, Dimensions > >
std::shared_ptr< detail::buffer< T, Dimensions > > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
implementation_t
template<typename T , int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using trisycl::detail::buffer_waiter< T, Dimensions, Allocator >::implementation_t = typename buffer_waiter::shared_ptr_implementation private
Definition at line 39 of file buffer_waiter.hpp.
Constructor & Destructor Documentation
buffer_waiter()
template<typename T , int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::detail::buffer_waiter< T, Dimensions, Allocator >::buffer_waiter (detail::buffer< T, Dimensions > * b) inline
Create a new buffer_waiter on top of a detail::buffer.
Definition at line 50 of file buffer_waiter.hpp.
 : implementation_t { b } {}
~buffer_waiter()
template<typename T , int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::detail::buffer_waiter< T, Dimensions, Allocator >::~buffer_waiter () inline
The buffer_waiter destructor waits for any data to be written back to the host, if any.
Definition at line 56 of file buffer_waiter.hpp.
References trisycl::detail::shared_ptr_implementation< buffer_waiter< T, Dimensions, Allocator >, detail::buffer< T, Dimensions > >::implementation, and TRISYCL_DUMP_T.
                    {
     /* Get a future from the implementation if we have to wait for its
        destruction */
     auto f = implementation->get_destructor_future();
     if (f) {
       /* No longer carry for the implementation buffer which is free to
          live its life up to its destruction */
       implementation.reset();
       TRISYCL_DUMP_T("~buffer_waiter() is waiting");
       // Then wait for its end in some other thread
       f->wait();
       TRISYCL_DUMP_T("~buffer_waiter() is done");
     }
   }
Member Data Documentation
implementation_t
template<typename T , int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> friend trisycl::detail::buffer_waiter< T, Dimensions, Allocator >::implementation_t private
Definition at line 42 of file buffer_waiter.hpp.
trisycl::buffer
class trisycl::buffer
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>>
class trisycl::buffer< T, Dimensions, Allocator >
A SYCL buffer is a multidimensional variable length array (à la C99 VLA or even Fortran before) that is used to store data to work on.
Todo:
There is a naming inconsistency in the specification between buffer and accessor on T versus datatype
Todo:
Finish allocator implementation
Todo:
Think about the need of an allocator when constructing a buffer from other buffers
Todo:
Update the specification to have a non-const allocator for const buffer? Or do we rely on rebind_alloc<T>. But does this work with astate-full allocator?
Todo:
Add constructors from arrays so that in C++17 the range and type can be infered from the constructor
Todo:
Add constructors from array_ref
Definition at line 28 of file accessor.hpp.
Public Types
using value_type = T
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
using allocator_type = Allocator
Public Member Functions
buffer ()=default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or an r-value (for std::move() for example).
buffer (const range< Dimensions > &r, Allocator allocator={})
Create a new buffer of the given size with storage managed by the SYCL runtime.
template<typename Dependent = T, typename = std::enable_if_t<!std::is_const<Dependent>::value>>
buffer (const T *host_data, const range< Dimensions > &r, Allocator allocator={})
Create a new buffer with associated host memory.
buffer (T *host_data, const range< Dimensions > &r, Allocator allocator={})
Create a new buffer with associated host memory.
buffer (shared_ptr_class< T > &host_data, const range< Dimensions > &buffer_range, trisycl::mutex_class &m, Allocator allocator={})
Create a new buffer with associated memory, using the data in host_data.
buffer (shared_ptr_class< T > host_data, const range< Dimensions > &buffer_range, Allocator allocator={})
Create a new buffer with associated memory, using the data in host_data.
template<typename InputIterator , typename ValueType = typename std::iterator_traits<InputIterator>::value_type>
buffer (InputIterator start_iterator, InputIterator end_iterator, Allocator allocator={})
Create a new allocated 1D buffer initialized from the given elements ranging from first up to one before last.
buffer (buffer< T, Dimensions, Allocator > &b, const id< Dimensions > &base_index, const range< Dimensions > &sub_range, Allocator allocator={})
Create a new sub-buffer without allocation to have separate accessors later.
buffer (cl_mem mem_object, queue from_queue, event available_event={}, Allocator allocator={})
Create a buffer from an existing OpenCL memory object associated with a context after waiting for an event signaling the availability of the OpenCL data.
template<access::mode Mode, access::target Target = access::target::global_buffer>
accessor< T, Dimensions, Mode, Target > get_access (handler &command_group_handler)
Get an accessor to the buffer with the required mode.
void mark_as_written ()
Force the buffer to behave like if we had created an accessor in write mode.
template<access::mode Mode>
accessor< T, Dimensions, Mode, access::target::host_buffer > get_access ()
Get a host accessor to the buffer with the required mode.
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
auto get_count () const
Returns the total number of elements in the buffer.
size_t get_size () const
Returns the size of the buffer storage in bytes.
auto use_count () const
Returns the number of buffers that are shared/referenced.
bool constexpr is_read_only () const
Ask for read-only status of the buffer.
void set_final_data (weak_ptr_class< T > finalData)
Set destination of buffer data on destruction.
void set_final_data (std::nullptr_t)
Disable write-back on buffer destruction.
bool is_cached (trisycl::context &ctx)
Check if the buffer is already cached in a certain context.
bool is_data_up_to_date (trisycl::context &ctx)
Check if the data stored in the buffer is up-to-date in a certain context.
template<typename Iterator , typename ValueType = typename std::iterator_traits< std::remove_reference_t<Iterator>>::value_type>
void set_final_data (Iterator &&finalData)
Set destination of buffer data on destruction.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >
shared_ptr_implementation (std::shared_ptr< detail::buffer_waiter< T, Dimensions, Allocator > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::buffer_waiter< T, Dimensions, Allocator > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const buffer< T, Dimensions, Allocator > &other) const
Equality operator.
bool operator< (const buffer< T, Dimensions, Allocator > &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename buffer::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >
std::shared_ptr< detail::buffer_waiter< T, Dimensions, Allocator > > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
allocator_type
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using trisycl::buffer< T, Dimensions, Allocator >::allocator_type = Allocator
Definition at line 74 of file buffer.hpp.
const_reference
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using trisycl::buffer< T, Dimensions, Allocator >::const_reference = const value_type&
Definition at line 73 of file buffer.hpp.
implementation_t
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using trisycl::buffer< T, Dimensions, Allocator >::implementation_t = typename buffer::shared_ptr_implementation private
Definition at line 79 of file buffer.hpp.
reference
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using trisycl::buffer< T, Dimensions, Allocator >::reference = value_type&
Definition at line 72 of file buffer.hpp.
value_type
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> using trisycl::buffer< T, Dimensions, Allocator >::value_type = T
The STL-like types.
Definition at line 71 of file buffer.hpp.
Constructor & Destructor Documentation
buffer() [1/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::buffer< T, Dimensions, Allocator >::buffer () default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or an r-value (for std::move() for example).
Since we just copy the shared_ptr<> from the shared_ptr_implementation above, this is where/how the sharing magic is happening with reference counting in this case.
buffer() [2/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::buffer< T, Dimensions, Allocator >::buffer (const range< Dimensions > & r, Allocator allocator = {}) inline
Create a new buffer of the given size with storage managed by the SYCL runtime.
The default behavior is to use the default host buffer allocator, in order to allow for host accesses. If the type of the buffer, has the const qualifier, then the default allocator will remove the qualifier to allow host access to the data.
Parameters
[in] r defines the size
[in] allocator is to be used by the SYCL runtime
Definition at line 112 of file buffer.hpp.
                                                            {})
     : implementation_t { detail::waiter<T, Dimensions, Allocator>(
                          new detail::buffer<T, Dimensions> { r }) }
       {}
buffer() [3/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<typename Dependent = T, typename = std::enable_if_t<!std::is_const<Dependent>::value>> trisycl::buffer< T, Dimensions, Allocator >::buffer (const T * host_data, const range< Dimensions > & r, Allocator allocator = {}) inline
Create a new buffer with associated host memory.
Parameters
[in] host_data points to the storage and values used by the buffer
[in] r defines the size
[in] allocator is to be used by the SYCL runtime, of type trisycl::buffer_allocator<T> by default
The host address is
const T*
, so the host memory is read-only.
However, the typename T is not const so the device accesses can be both read and write accesses. Since, the host_data is const, this buffer is only initialized with this memory and there is no write after its destruction, unless there is another final data address given after construction of the buffer.
Only enable this constructor if it is not the same as the one with
const T *host_data
, which is when T is already a constant type.
Todo:
Actually this is redundant.
Definition at line 145 of file buffer.hpp.
References trisycl::detail::waiter().
                                {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { host_data, r }) }
   {}
buffer() [4/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::buffer< T, Dimensions, Allocator >::buffer (T * host_data, const range< Dimensions > & r, Allocator allocator = {}) inline
Create a new buffer with associated host memory.
Parameters
[in,out] host_data points to the storage and values used by the buffer
[in] r defines the size
[in] allocator is to be used by the SYCL runtime, of type trisycl::buffer_allocator<T> by default
The memory is owned by the runtime during the lifetime of the object. Data is copied back to the host unless the user overrides the behavior using the set_final_data method. host_data points to the storage and values used by the buffer and range<Dimensions> defines the size.
Definition at line 169 of file buffer.hpp.
References trisycl::detail::waiter().
                                {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { host_data, r }) }
   {}
buffer() [5/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::buffer< T, Dimensions, Allocator >::buffer (shared_ptr_class< T > & host_data, const range< Dimensions > & buffer_range, trisycl::mutex_class & m, Allocator allocator = {}) inline
Create a new buffer with associated memory, using the data in host_data.
Parameters
[in,out] host_data points to the storage and values used by the buffer
[in] r defines the size
[in] allocator is to be used by the SYCL runtime, of type trisycl::buffer_allocator<T> by default
The ownership of the host_data is shared between the runtime and the user. In order to enable both the user application and the SYCL runtime to use the same pointer, a trisycl::mutex_class is used. The mutex m is locked by the runtime whenever the data is in use and unlocked otherwise. Data is synchronized with host_data, when the mutex is unlocked by the runtime.
Todo:
update the specification to replace the pointer by a reference and provide the constructor with and without a mutex
Definition at line 198 of file buffer.hpp.
References TRISYCL_UNIMPL.
                                {}) {
     TRISYCL_UNIMPL;
   }
buffer() [6/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::buffer< T, Dimensions, Allocator >::buffer (shared_ptr_class< T > host_data, const range< Dimensions > & buffer_range, Allocator allocator = {}) inline
Create a new buffer with associated memory, using the data in host_data.
Parameters
[in,out] host_data points to the storage and values used by the buffer
[in] r defines the size
[in,out] m is the mutex used to protect the data access
[in] allocator is to be used by the SYCL runtime, of type trisycl::buffer_allocator<T> by default
The ownership of the host_data is shared between the runtime and the user. In order to enable both the user application and the SYCL runtime to use the same pointer, a trisycl::mutex_class is used.
Todo:
add this mutex-less constructor to the specification
Definition at line 226 of file buffer.hpp.
References trisycl::detail::waiter().
                                {})
     : implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                          { host_data, buffer_range }) }
   {}
buffer() [7/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<typename InputIterator , typename ValueType = typename std::iterator_traits<InputIterator>::value_type> trisycl::buffer< T, Dimensions, Allocator >::buffer (InputIterator start_iterator, InputIterator end_iterator, Allocator allocator = {}) inline
Create a new allocated 1D buffer initialized from the given elements ranging from first up to one before last.
The data is copied to an intermediate memory position by the runtime. Data is written back to the same iterator set if the iterator is not a const iterator.
Parameters
[in,out] start_iterator points to the first element to copy
[in] end_iterator points to just after the last element to copy
[in] allocator is to be used by the SYCL runtime, of type trisycl::buffer_allocator<T> by default
Todo:
Implement the copy back at buffer destruction
Todo:
Generalize this for n-D and provide column-major and row-major initialization
Todo:
a reason to have this nD is that set_final_data(weak_ptr_class<T> & finalData) is actually doing this linearization anyway
Todo:
Allow read-only buffer construction too
Todo:
update the specification to deal with forward iterators instead and rewrite back only when it is non const and output iterator at least
Todo:
Allow initialization from ranges and collections à la STL
Definition at line 271 of file buffer.hpp.
References trisycl::detail::waiter().
                                {}) :
     implementation_t { detail::waiter(new detail::buffer<T, Dimensions>
                        { start_iterator, end_iterator }) }
   {}
buffer() [8/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::buffer< T, Dimensions, Allocator >::buffer (buffer< T, Dimensions, Allocator > & b, const id< Dimensions > & base_index, const range< Dimensions > & sub_range, Allocator allocator = {}) inline
Create a new sub-buffer without allocation to have separate accessors later.
Parameters
[in,out] b is the buffer with the real data
[in] base_index specifies the origin of the sub-buffer inside the buffer b
[in] sub_range specifies the size of the sub-buffer
Todo:
To be implemented
Todo:
Update the specification to replace index by id
Definition at line 293 of file buffer.hpp.
References TRISYCL_UNIMPL.
                                {}) { TRISYCL_UNIMPL; }
buffer() [9/9]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> trisycl::buffer< T, Dimensions, Allocator >::buffer (cl_mem mem_object, queue from_queue, event available_event = {}, Allocator allocator = {}) inline
Create a buffer from an existing OpenCL memory object associated with a context after waiting for an event signaling the availability of the OpenCL data.
Parameters
[in,out] mem_object is the OpenCL memory object to use
[in,out] from_queue is the queue associated to the memory object
[in] available_event specifies the event to wait for if non null
Note that a buffer created from a cl_mem object will only have one underlying cl_mem for the lifetime of the buffer and use on an incompatible queue constitues an error.
Todo:
To be implemented
Todo:
Improve the specification to allow CLHPP objects too
Definition at line 320 of file buffer.hpp.
References trisycl::access::global_buffer, and TRISYCL_UNIMPL.
                                  {},
          Allocator allocator = {}) { TRISYCL_UNIMPL;  }
Member Function Documentation
get_access() [1/2]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<access::mode Mode, access::target Target = access::target::global_buffer> accessor<T, Dimensions, Mode, Target> trisycl::buffer< T, Dimensions, Allocator >::get_access (handler & command_group_handler) inline
Get an accessor to the buffer with the required mode.
Parameters
Mode is the requested access mode
Target is the type of object to be accessed
[in] command_group_handler is the command group handler in which the kernel is to be executed
Todo:
Do we need for an accessor to increase the reference count of a buffer object? It does make more sense for a host-side accessor.
Todo:
Implement the modes and targets
Definition at line 346 of file buffer.hpp.
References trisycl::access::constant_buffer, trisycl::access::global_buffer, and trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     static_assert(Target == access::target::global_buffer
                   || Target == access::target::constant_buffer,
                   "get_access(handler) can only deal with access::global_buffer"
                   " or access::constant_buffer (for host_buffer accessor"
                   " do not use a command group handler");
     implementation->implementation->template track_access_mode<Mode, Target>();
     return { *this, command_group_handler };
   }
get_access() [2/2]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<access::mode Mode> accessor<T, Dimensions, Mode, access::target::host_buffer> trisycl::buffer< T, Dimensions, Allocator >::get_access () inline
Get a host accessor to the buffer with the required mode.
Parameters
Mode is the requested access mode
Todo:
Implement the modes
Todo:
More elegant solution
Definition at line 375 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
                {
     implementation->implementation->template track_access_mode<Mode, access::target::host_buffer>();
     return { *this };
   }
get_count()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> auto trisycl::buffer< T, Dimensions, Allocator >::get_count () const inline
Returns the total number of elements in the buffer.
Equal to get_range()[0] * ... * get_range()[Dimensions-1].
Definition at line 402 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->get_count();
   }
get_range()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> auto trisycl::buffer< T, Dimensions, Allocator >::get_range () const inline
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
Todo:
rename to the equivalent from array_ref proposals? Such as size() in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0009r2.html
Definition at line 389 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     /* Interpret the shape which is a pointer to the first element as an
        array of Dimensions elements so that the range<Dimensions>
        constructor is happy with this collection
     */
     return implementation->implementation->get_range();
   }
get_size()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> size_t trisycl::buffer< T, Dimensions, Allocator >::get_size () const inline
Returns the size of the buffer storage in bytes.
Equal to get_count()*sizeof(T).
Todo:
rename to something else. In http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0122r0.pdf it is named bytes() for example
Definition at line 415 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->get_size();
   }
is_cached()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> bool trisycl::buffer< T, Dimensions, Allocator >::is_cached (trisycl::context & ctx) inline
Check if the buffer is already cached in a certain context.
Definition at line 480 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->is_cached(ctx);
   }
is_data_up_to_date()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> bool trisycl::buffer< T, Dimensions, Allocator >::is_data_up_to_date (trisycl::context & ctx) inline
Check if the data stored in the buffer is up-to-date in a certain context.
Definition at line 487 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->is_data_up_to_date(ctx);
   }
is_read_only()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> bool constexpr trisycl::buffer< T, Dimensions, Allocator >::is_read_only () const inline
Ask for read-only status of the buffer.
Todo:
Add to specification
Definition at line 442 of file buffer.hpp.
{
     return std::is_const<T>::value;
   }
mark_as_written()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> void trisycl::buffer< T, Dimensions, Allocator >::mark_as_written () inline
Force the buffer to behave like if we had created an accessor in write mode.
Definition at line 360 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     return implementation->implementation->mark_as_written();
   }
set_final_data() [1/3]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> void trisycl::buffer< T, Dimensions, Allocator >::set_final_data (weak_ptr_class< T > finalData) inline
Set destination of buffer data on destruction.
The finalData points to the host memory to which, the outcome of all the buffer processing is going to be copied to.
This is the final pointer, which is going to be accessible after the destruction of the buffer and in the case where this is a valid pointer, the data are going to be copied to this host address.
finalData is different from the original host address, if the buffer was created associated with one. This is mainly to be used when a shared_ptr is given in the constructor and the output data will reside in a different location from the initialization data.
It is defined as a weak_ptr referring to a shared_ptr that is not associated with the trisycl::buffer, and so the trisycl::buffer will have no ownership of finalData.
Definition at line 465 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     implementation->implementation->set_final_data(std::move(finalData));
   }
set_final_data() [2/3]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> void trisycl::buffer< T, Dimensions, Allocator >::set_final_data (std::nullptr_t) inline
Disable write-back on buffer destruction.
Definition at line 472 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     implementation->implementation->set_final_data(nullptr);
   }
set_final_data() [3/3]
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> template<typename Iterator , typename ValueType = typename std::iterator_traits< std::remove_reference_t<Iterator>>::value_type> void trisycl::buffer< T, Dimensions, Allocator >::set_final_data (Iterator && finalData) inline
Set destination of buffer data on destruction.
WARNING: the user has to ensure that the object referred to by the iterator will be alive after buffer destruction, otherwise the behavior is undefined.
Definition at line 502 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     implementation->implementation->set_final_data(
       std::forward<Iterator>(finalData));
   }
use_count()
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> auto trisycl::buffer< T, Dimensions, Allocator >::use_count () const inline
Returns the number of buffers that are shared/referenced.
For example
trisycl::buffer<int> b { 1000 };
// Here b.use_count() should return 1
trisycl::buffer<int> c { b };
// Here b.use_count() and b.use_count() should return 2
Todo:
Add to the specification, useful for validation
Definition at line 432 of file buffer.hpp.
References trisycl::detail::shared_ptr_implementation< buffer< T, Dimensions, Allocator >, detail::buffer_waiter< T, Dimensions, Allocator > >::implementation.
{
     // Rely on the shared_ptr<> use_count()
     return implementation.use_count();
   }
Member Data Documentation
implementation_t
template<typename T, int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> friend trisycl::buffer< T, Dimensions, Allocator >::implementation_t private
Definition at line 82 of file buffer.hpp.
trisycl::image
struct trisycl::image
template<int Dimensions>
struct trisycl::image< Dimensions >
Todo:
implement image
Definition at line 22 of file image.hpp.
trisycl::detail::reserve_id
struct trisycl::detail::reserve_id
template<typename T>
struct trisycl::detail::reserve_id< T >
A private description of a reservation station.
Definition at line 38 of file pipe.hpp.
Public Member Functions
reserve_id (typename boost::circular_buffer< T >::iterator start, std::size_t size)
Track a reservation not committed yet.
Public Attributes
boost::circular_buffer< T >::iterator start
Start of the reservation in the pipe storage.
std::size_t size
Number of elements in the reservation.
bool ready = false
Constructor & Destructor Documentation
reserve_id()
template<typename T > trisycl::detail::reserve_id< T >::reserve_id (typename boost::circular_buffer< T >::iterator start, std::size_t size) inline
Track a reservation not committed yet.
Parameters
[in] start point to the start of the reservation in the pipe storage
[in] size is the number of elements in the reservation
Definition at line 56 of file pipe.hpp.
                              : start { start }, size { size } {}
Member Data Documentation
ready
template<typename T > bool trisycl::detail::reserve_id< T >::ready = false
Definition at line 47 of file pipe.hpp.
size
template<typename T > std::size_t trisycl::detail::reserve_id< T >::size
Number of elements in the reservation.
Definition at line 43 of file pipe.hpp.
Referenced by trisycl::detail::pipe< value_type >::empty(), trisycl::detail::pipe< value_type >::reserve_read(), trisycl::detail::pipe< value_type >::reserve_write(), and trisycl::detail::pipe< value_type >::size_with_lock().
start
template<typename T > boost::circular_buffer<T>::iterator trisycl::detail::reserve_id< T >::start
Start of the reservation in the pipe storage.
Definition at line 40 of file pipe.hpp.
trisycl::detail::pipe
class trisycl::detail::pipe
template<typename T>
class trisycl::detail::pipe< T >
Implement a pipe object.
Use some mutable members so that the pipe object can be changed even when the accessors are captured in a lambda.
Definition at line 68 of file pipe.hpp.
Public Types
using value_type = T
using implementation_t = boost::circular_buffer< value_type >
Implement the pipe with a circular buffer.
using rid_iterator = typename decltype(w_rid_q)::iterator
Public Member Functions
pipe (std::size_t capacity)
Create a pipe as a circular buffer of the required capacity.
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size_with_lock () const
The size() method used outside needs to lock the datastructure.
bool empty_with_lock () const
The empty() method used outside needs to lock the datastructure.
bool full_with_lock () const
bool write (const T &value, bool blocking=false)
Try to write a value to the pipe.
bool read (T &value, bool blocking=false)
Try to read a value from the pipe.
std::size_t reserved_for_reading () const
Compute the amount of elements blocked by read reservations, not yet committed.
std::size_t reserved_for_writing () const
Compute the amount of elements blocked by write reservations, not yet committed.
bool reserve_read (std::size_t s, rid_iterator &rid, bool blocking=false)
Reserve some part of the pipe for reading.
bool reserve_write (std::size_t s, rid_iterator &rid, bool blocking=false)
Reserve some part of the pipe for writing.
void move_read_reservation_forward ()
Process the read reservations that are ready to be released in the reservation queue.
void move_write_reservation_forward ()
Process the write reservations that are ready to be released in the reservation queue.
Public Attributes
bool used_for_reading = false
True when the pipe is currently used for reading.
bool used_for_writing = false
True when the pipe is currently used for writing.
Private Member Functions
std::size_t size () const
Get the current number of elements in the pipe that can be read.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
Private Attributes
boost::circular_buffer< value_type > cb
The circular buffer to store the elements.
std::mutex cb_mutex
To protect the access to the circular buffer.
std::deque< reserve_id< value_type > > w_rid_q
The queue of pending write reservations.
std::deque< reserve_id< value_type > > r_rid_q
The queue of pending read reservations.
std::size_t read_reserved_frozen
Track the number of frozen elements related to read reservations.
std::condition_variable read_done
To signal that a read has been successful.
std::condition_variable write_done
To signal that a write has been successful.
bool debug_mode = false
To control the debug mode, disabled by default.
Member Typedef Documentation
implementation_t
template<typename T> using trisycl::detail::pipe< T >::implementation_t = boost::circular_buffer<value_type>
Implement the pipe with a circular buffer.
Definition at line 75 of file pipe.hpp.
rid_iterator
template<typename T> using trisycl::detail::pipe< T >::rid_iterator = typename decltype(w_rid_q)::iterator
Definition at line 93 of file pipe.hpp.
value_type
template<typename T> using trisycl::detail::pipe< T >::value_type = T
Definition at line 72 of file pipe.hpp.
Constructor & Destructor Documentation
pipe()
template<typename T> trisycl::detail::pipe< T >::pipe (std::size_t capacity) inline
Create a pipe as a circular buffer of the required capacity.
Definition at line 124 of file pipe.hpp.
 : cb { capacity }, read_reserved_frozen { 0 } { }
Member Function Documentation
capacity()
template<typename T> std::size_t trisycl::detail::pipe< T >::capacity () const inline
Return the maximum number of elements that can fit in the pipe.
Definition at line 129 of file pipe.hpp.
{
     // No lock required since it is fixed and set at construction time
     return cb.capacity();
   }
empty()
template<typename T> bool trisycl::detail::pipe< T >::empty () const inline private
Test if the pipe is empty.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the write side (for example on FPGA).
Definition at line 164 of file pipe.hpp.
                      {
     TRISYCL_DUMP_T("empty() cb.size() = " << cb.size()
                    << " size() = " << size());
     // It is empty when the size is zero, taking into account reservations
     return size() ==  0;
   }
empty_with_lock()
template<typename T> bool trisycl::detail::pipe< T >::empty_with_lock () const inline
The empty() method used outside needs to lock the datastructure.
Definition at line 195 of file pipe.hpp.
{
     std::lock_guard<std::mutex> lg { cb_mutex };
     return empty();
   }
full()
template<typename T> bool trisycl::detail::pipe< T >::full () const inline private
Test if the pipe is full.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the read side (for example on FPGA).
Definition at line 180 of file pipe.hpp.
                     {
     return cb.full();
   }
full_with_lock()
template<typename T> bool trisycl::detail::pipe< T >::full_with_lock () const inline
Definition at line 202 of file pipe.hpp.
{
     std::lock_guard<std::mutex> lg { cb_mutex };
     return full();
   }
move_read_reservation_forward()
template<typename T> void trisycl::detail::pipe< T >::move_read_reservation_forward () inline
Process the read reservations that are ready to be released in the reservation queue.
Definition at line 429 of file pipe.hpp.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::commit().
{
     // Lock the pipe to avoid nuisance
     std::unique_lock<std::mutex> lock { cb_mutex };
     for (;;) {
       if (r_rid_q.empty())
         // No pending reservation, so nothing to do
         break;
       if (!r_rid_q.front().ready)
         /* If the first reservation is not ready to be released, stop
            because it is blocking all the following in the queue
            anyway */
         break;
       // Remove the reservation to be released from the queue
       r_rid_q.pop_front();
       std::size_t n_to_pop;
       if (r_rid_q.empty())
         // If it was the last one, remove all the reservation
         n_to_pop = read_reserved_frozen;
       else
         // Else remove everything up to the next reservation
         n_to_pop =  r_rid_q.front().start - cb.begin();
       // No longer take into account these reserved slots
       read_reserved_frozen -= n_to_pop;
       // Release the elements from the FIFO
       while (n_to_pop--)
         cb.pop_front();
       // Notify the clients waiting for some room to write in the pipe
       read_done.notify_all();
       /* ...and process the next reservation to see if it is ready to
          be released too */
     }
   }
move_write_reservation_forward()
template<typename T> void trisycl::detail::pipe< T >::move_write_reservation_forward () inline
Process the write reservations that are ready to be released in the reservation queue.
Definition at line 467 of file pipe.hpp.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::commit().
{
     // Lock the pipe to avoid nuisance
     std::lock_guard<std::mutex> lg { cb_mutex };
     for (;;) {
       if (w_rid_q.empty())
         // No pending reservation, so nothing to do
         break;
       // Get the first reservation
       const auto &rid = w_rid_q.front();
       if (!rid.ready)
         /* If the reservation is not ready to be released, stop
            because it is blocking all the following in the queue
            anyway */
         break;
       // Remove the reservation to be released from the queue
       w_rid_q.pop_front();
       // Notify the clients waiting to read something from the pipe
       write_done.notify_all();
       /* ...and process the next reservation to see if it is ready to
          be released too */
     }
   }
read()
template<typename T> bool trisycl::detail::pipe< T >::read (T & value, bool blocking = false) inline
Try to read a value from the pipe.
Parameters
[out] value is the reference to where to store what is read
[in] blocking specify if the call wait for the operation to succeed
Returns
true on success
If there is a pending reservation, read the next element to be read and update the number of reserved elements
Definition at line 259 of file pipe.hpp.
{
     // Lock the pipe to avoid being disturbed
     std::unique_lock<std::mutex> ul { cb_mutex };
     TRISYCL_DUMP_T("Read pipe empty = " << empty());
     if (blocking)
       /* If in blocking mode, wait for the not empty condition, that
          may be changed when a write is done */
       write_done.wait(ul, [&] { return !empty(); });
     else if (empty())
       return false;
     TRISYCL_DUMP_T("Read pipe front = " << cb.front()
                    << " back = " << cb.back()
                    << " reserved_for_reading() = " << reserved_for_reading());
     if (read_reserved_frozen)
       /** If there is a pending reservation, read the next element to
           be read and update the number of reserved elements */
       value = cb.begin()[read_reserved_frozen++];
     else {
       /* There is no pending read reservation, so pop the read value
          from the pipe */
       value = cb.front();
       cb.pop_front();
     }
     TRISYCL_DUMP_T("Read pipe value = " << value);
     // Micro-optimization: unlock before the notification
     // https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all
     ul.unlock();
     // Notify the clients waiting for some room to write in the pipe
     read_done.notify_all();
     return true;
   }
reserve_read()
template<typename T> bool trisycl::detail::pipe< T >::reserve_read (std::size_t s, rid_iterator & rid, bool blocking = false) inline
Reserve some part of the pipe for reading.
Parameters
[in] s is the number of element to reserve
[out] rid is an iterator to a description of the reservation that has been done if successful
[in] blocking specify if the call wait for the operation to succeed
Returns
true if the reservation was successful
Definition at line 339 of file pipe.hpp.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation().
{
     // Lock the pipe to avoid being disturbed
     std::unique_lock<std::mutex> ul { cb_mutex };
     TRISYCL_DUMP_T("Before read reservation cb.size() = " << cb.size()
                    << " size() = " << size());
     if (s == 0)
       // Empty reservation requested, so nothing to do
       return false;
     if (blocking)
       /* If in blocking mode, wait for enough elements to read in the
          pipe for the reservation. This condition can change when a
          write is done */
       write_done.wait(ul, [&] { return s <= size(); });
     else if (s > size())
       // Not enough elements to read in the pipe for the reservation
       return false;
     // Compute the location of the first element of the reservation
     auto first = cb.begin() + read_reserved_frozen;
     // Increment the number of frozen elements
     read_reserved_frozen += s;
     /* Add a description of the reservation at the end of the
        reservation queue */
     r_rid_q.emplace_back(first, s);
     // Return the iterator to the last reservation descriptor
     rid = r_rid_q.end() - 1;
     TRISYCL_DUMP_T("After reservation cb.size() = " << cb.size()
                    << " size() = " << size());
     return true;
   }
reserve_write()
template<typename T> bool trisycl::detail::pipe< T >::reserve_write (std::size_t s, rid_iterator & rid, bool blocking = false) inline
Reserve some part of the pipe for writing.
Parameters
[in] s is the number of element to reserve
[out] rid is an iterator to a description of the reservation that has been done if successful
[in] blocking specify if the call wait for the operation to succeed
Returns
true if the reservation was successful
Definition at line 387 of file pipe.hpp.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation().
{
     // Lock the pipe to avoid being disturbed
     std::unique_lock<std::mutex> ul { cb_mutex };
     TRISYCL_DUMP_T("Before write reservation cb.size() = " << cb.size()
                    << " size() = " << size());
     if (s == 0)
       // Empty reservation requested, so nothing to do
       return false;
     if (blocking)
       /* If in blocking mode, wait for enough room in the pipe, that
          may be changed when a read is done. Do not use a difference
          here because it is only about unsigned values */
       read_done.wait(ul, [&] { return cb.size() + s <= capacity(); });
     else if (cb.size() + s > capacity())
       // Not enough room in the pipe for the reservation
       return false;
     /* If there is enough room in the pipe, just create default values
          in it to do the reservation */
     for (std::size_t i = 0; i != s; ++i)
       cb.push_back();
     /* Compute the location of the first element a posteriori since it
          may not exist a priori if cb was empty before */
     auto first = cb.end() - s;
     /* Add a description of the reservation at the end of the
        reservation queue */
     w_rid_q.emplace_back(first, s);
     // Return the iterator to the last reservation descriptor
     rid = w_rid_q.end() - 1;
     TRISYCL_DUMP_T("After reservation cb.size() = " << cb.size()
                    << " size() = " << size());
     return true;
   }
reserved_for_reading()
template<typename T> std::size_t trisycl::detail::pipe< T >::reserved_for_reading () const inline
Compute the amount of elements blocked by read reservations, not yet committed.
This includes some normal reads to pipes between/after un-committed reservations
This function assumes that the data structure is locked
Definition at line 303 of file pipe.hpp.
{
     return read_reserved_frozen;
   }
reserved_for_writing()
template<typename T> std::size_t trisycl::detail::pipe< T >::reserved_for_writing () const inline
Compute the amount of elements blocked by write reservations, not yet committed.
This includes some normal writes to pipes between/after un-committed reservations
This function assumes that the data structure is locked
Definition at line 316 of file pipe.hpp.
{
     if (w_rid_q.empty())
       // No on-going reservation
       return 0;
     else
       /* The reserved size is from the first element of the first
          on-going reservation up to the end of the pipe content */
       return cb.end() - w_rid_q.front().start;
   }
size()
template<typename T> std::size_t trisycl::detail::pipe< T >::size () const inline private
Get the current number of elements in the pipe that can be read.
This is obviously a volatile value which is constrained by the theory of restricted relativity.
Note that on some devices it may be costly to implement (for example on FPGA).
Definition at line 144 of file pipe.hpp.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::end(), and trisycl::detail::pipe_reservation< PipeAccessor >::size().
{
     TRISYCL_DUMP_T("size() cb.size() = " << cb.size()
                    << " cb.end() = " << (void *)&*cb.end()
                    << " reserved_for_reading() = " << reserved_for_reading()
                    << " reserved_for_writing() = " << reserved_for_writing());
     /* The actual number of available elements depends from the
        elements blocked by some reservations.
        This prevents a consumer to read into reserved area. */
     return cb.size() - reserved_for_reading() - reserved_for_writing();
   }
size_with_lock()
template<typename T> std::size_t trisycl::detail::pipe< T >::size_with_lock () const inline
The size() method used outside needs to lock the datastructure.
Definition at line 188 of file pipe.hpp.
{
     std::lock_guard<std::mutex> lg { cb_mutex };
     return size();
   }
write()
template<typename T> bool trisycl::detail::pipe< T >::write (const T & value, bool blocking = false) inline
Try to write a value to the pipe.
Parameters
[in] value is what we want to write
[in] blocking specify if the call wait for the operation to succeed
Returns
true on success
Todo:
provide a && version
Definition at line 219 of file pipe.hpp.
{
     // Lock the pipe to avoid being disturbed
     std::unique_lock<std::mutex> ul { cb_mutex };
     TRISYCL_DUMP_T("Write pipe full = " << full()
                    << " value = " << value);
     if (blocking)
       /* If in blocking mode, wait for the not full condition, that
          may be changed when a read is done */
       read_done.wait(ul, [&] { return !full(); });
     else if (full())
       return false;
     cb.push_back(value);
     TRISYCL_DUMP_T("Write pipe front = " << cb.front()
                    << " back = " << cb.back()
                    << " cb.begin() = " << (void *)&*cb.begin()
                    << " cb.size() = " << cb.size()
                    << " cb.end() = " << (void *)&*cb.end()
                    << " reserved_for_reading() = " << reserved_for_reading()
                    << " reserved_for_writing() = " << reserved_for_writing());
     // Micro-optimization: unlock before the notification
     // https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all
     ul.unlock();
     // Notify the clients waiting to read something from the pipe
     write_done.notify_all();
     return true;
   }
Member Data Documentation
cb
template<typename T> boost::circular_buffer<value_type> trisycl::detail::pipe< T >::cb private
The circular buffer to store the elements.
Definition at line 80 of file pipe.hpp.
cb_mutex
template<typename T> std::mutex trisycl::detail::pipe< T >::cb_mutex mutable private
To protect the access to the circular buffer.
In case the object is capture in a lambda per copy, make it mutable.
Definition at line 86 of file pipe.hpp.
debug_mode
template<typename T> bool trisycl::detail::pipe< T >::debug_mode = false private
To control the debug mode, disabled by default.
Definition at line 113 of file pipe.hpp.
r_rid_q
template<typename T> std::deque<reserve_id<value_type> > trisycl::detail::pipe< T >::r_rid_q private
The queue of pending read reservations.
Definition at line 101 of file pipe.hpp.
read_done
template<typename T> std::condition_variable trisycl::detail::pipe< T >::read_done private
To signal that a read has been successful.
Definition at line 107 of file pipe.hpp.
read_reserved_frozen
template<typename T> std::size_t trisycl::detail::pipe< T >::read_reserved_frozen private
Track the number of frozen elements related to read reservations.
Definition at line 104 of file pipe.hpp.
used_for_reading
template<typename T> bool trisycl::detail::pipe< T >::used_for_reading = false
True when the pipe is currently used for reading.
Definition at line 118 of file pipe.hpp.
used_for_writing
template<typename T> bool trisycl::detail::pipe< T >::used_for_writing = false
True when the pipe is currently used for writing.
Definition at line 121 of file pipe.hpp.
w_rid_q
template<typename T> std::deque<reserve_id<value_type> > trisycl::detail::pipe< T >::w_rid_q private
The queue of pending write reservations.
Definition at line 89 of file pipe.hpp.
write_done
template<typename T> std::condition_variable trisycl::detail::pipe< T >::write_done private
To signal that a write has been successful.
Definition at line 110 of file pipe.hpp.
trisycl::detail::pipe_accessor
class trisycl::detail::pipe_accessor
template<typename T, access::mode AccessMode, access::target Target>
class trisycl::detail::pipe_accessor< T, AccessMode, Target >
The accessor abstracts the way pipe data are accessed inside a kernel.
Definition at line 43 of file pipe_accessor.hpp.
Public Types
using value_type = T
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
Public Member Functions
pipe_accessor (const std::shared_ptr< detail::pipe< T >> &p)
Construct a pipe accessor from an existing pipe.
pipe_accessor (const std::shared_ptr< detail::pipe< T >> &p, handler &command_group_handler)
Construct a pipe accessor from an existing pipe.
pipe_accessor ()=default
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size () const
Get the current number of elements in the pipe.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
operator bool () const
In an explicit bool context, the accessor gives the success status of the last access.
const pipe_accessor & write (const value_type &value) const
Try to write a value to the pipe.
const pipe_accessor & operator<< (const value_type &value) const
Some syntactic sugar to use.
const pipe_accessor & read (value_type &value) const
Try to read a value from the pipe.
value_type read () const
Read a value from a blocking pipe.
const pipe_accessor & operator>> (value_type &value) const
Some syntactic sugar to use.
detail::pipe_reservation< pipe_accessor > reserve (std::size_t size) const
void set_debug (bool enable) const
Set debug mode.
auto & get_pipe_detail ()
~pipe_accessor ()
Static Public Attributes
static constexpr auto rank = 1
static constexpr auto mode = AccessMode
static constexpr auto target = Target
static constexpr bool blocking
Private Attributes
std::shared_ptr< detail::pipe< T > > implementation
The real pipe implementation behind the hood.
bool ok = false
Store the success status of last pipe operation.
Member Typedef Documentation
const_reference
template<typename T, access::mode AccessMode, access::target Target> using trisycl::detail::pipe_accessor< T, AccessMode, Target >::const_reference = const value_type&
Definition at line 58 of file pipe_accessor.hpp.
reference
template<typename T, access::mode AccessMode, access::target Target> using trisycl::detail::pipe_accessor< T, AccessMode, Target >::reference = value_type&
Definition at line 57 of file pipe_accessor.hpp.
value_type
template<typename T, access::mode AccessMode, access::target Target> using trisycl::detail::pipe_accessor< T, AccessMode, Target >::value_type = T
The STL-like types.
Definition at line 56 of file pipe_accessor.hpp.
Constructor & Destructor Documentation
pipe_accessor() [1/3]
template<typename T, access::mode AccessMode, access::target Target> trisycl::detail::pipe_accessor< T, AccessMode, Target >::pipe_accessor (const std::shared_ptr< detail::pipe< T >> & p) inline
Construct a pipe accessor from an existing pipe.
Todo:
Use pipe_exception instead
Definition at line 82 of file pipe_accessor.hpp.
     : implementation { p } {
     //    TRISYCL_DUMP_T("Create a kernel pipe accessor write = "
     //                 << is_write_access());
     // Verify that the pipe is not already used in the requested mode
     if (mode == access::mode::write)
       if (implementation->used_for_writing)
         /// \todo Use pipe_exception instead
         throw std::logic_error { "The pipe is already used for writing." };
       else
         implementation->used_for_writing = true;
     else
       if (implementation->used_for_reading)
         throw std::logic_error { "The pipe is already used for reading." };
       else
         implementation->used_for_reading = true;
   }
pipe_accessor() [2/3]
template<typename T, access::mode AccessMode, access::target Target> trisycl::detail::pipe_accessor< T, AccessMode, Target >::pipe_accessor (const std::shared_ptr< detail::pipe< T >> & p, handler & command_group_handler) inline
Construct a pipe accessor from an existing pipe.
For now the handler is not used.
Definition at line 105 of file pipe_accessor.hpp.
     : pipe_accessor(p) {}
pipe_accessor() [3/3]
template<typename T, access::mode AccessMode, access::target Target> trisycl::detail::pipe_accessor< T, AccessMode, Target >::pipe_accessor () default
Referenced by trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >::pipe_accessor().
~pipe_accessor()
template<typename T, access::mode AccessMode, access::target Target> trisycl::detail::pipe_accessor< T, AccessMode, Target >::~pipe_accessor () inline
Free the pipe for a future usage for the current mode
Definition at line 279 of file pipe_accessor.hpp.
                    {
     /// Free the pipe for a future usage for the current mode
     if (mode == access::mode::write)
       implementation->used_for_writing = false;
     else
       implementation->used_for_reading = false;
   }
Member Function Documentation
capacity()
template<typename T, access::mode AccessMode, access::target Target> std::size_t trisycl::detail::pipe_accessor< T, AccessMode, Target >::capacity () const inline
Return the maximum number of elements that can fit in the pipe.
Definition at line 114 of file pipe_accessor.hpp.
{
     return implementation->capacity();
   }
empty()
template<typename T, access::mode AccessMode, access::target Target> bool trisycl::detail::pipe_accessor< T, AccessMode, Target >::empty () const inline
Test if the pipe is empty.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the write side (for example on FPGA).
Definition at line 139 of file pipe_accessor.hpp.
                      {
     return implementation->empty_with_lock();
   }
full()
template<typename T, access::mode AccessMode, access::target Target> bool trisycl::detail::pipe_accessor< T, AccessMode, Target >::full () const inline
Test if the pipe is full.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the read side (for example on FPGA).
Definition at line 152 of file pipe_accessor.hpp.
                     {
     return implementation->full_with_lock();
   }
get_pipe_detail()
template<typename T, access::mode AccessMode, access::target Target> auto& trisycl::detail::pipe_accessor< T, AccessMode, Target >::get_pipe_detail () inline
Definition at line 274 of file pipe_accessor.hpp.
{
     return implementation;
   }
operator bool()
template<typename T, access::mode AccessMode, access::target Target> trisycl::detail::pipe_accessor< T, AccessMode, Target >::operator bool () const inline explicit
In an explicit bool context, the accessor gives the success status of the last access.
It is not impacted by reservation success.
The explicitness is related to avoid
 some_pipe <<
some_value
to be interpreted as
 some_bool <<
some_value
when the type of
some_value
is not the same type as the pipe type.
Returns
true on success of the previous read or write operation
Definition at line 169 of file pipe_accessor.hpp.
{
     return ok;
   }
operator<<()
template<typename T, access::mode AccessMode, access::target Target> const pipe_accessor& trisycl::detail::pipe_accessor< T, AccessMode, Target >::operator<< (const value_type & value) const inline
Some syntactic sugar to use.
a << v
instead of
a.write(v)
Definition at line 199 of file pipe_accessor.hpp.
{
     static_assert(mode == access::mode::write,
                   "'<<' operator on a pipe accessor is only possible"
                   " with write access mode");
     // Return a reference to *this so we can apply a sequence of >>
     return write(value);
   }
operator>>()
template<typename T, access::mode AccessMode, access::target Target> const pipe_accessor& trisycl::detail::pipe_accessor< T, AccessMode, Target >::operator>> (value_type & value) const inline
Some syntactic sugar to use.
a >> v
instead of
a.read(v)
Definition at line 254 of file pipe_accessor.hpp.
{
     static_assert(mode == access::mode::read,
                   "'>>' operator on a pipe accessor is only possible"
                   " with read access mode");
     // Return a reference to *this so we can apply a sequence of >>
     return read(value);
   }
read() [1/2]
template<typename T, access::mode AccessMode, access::target Target> const pipe_accessor& trisycl::detail::pipe_accessor< T, AccessMode, Target >::read (value_type & value) const inline
Try to read a value from the pipe.
Parameters
[out] value is the reference to where to store what is read
Returns
this
so we can apply a sequence of read for example (but do not do this on a non blocking pipe...)
This function is const so it can work when the accessor is passed by copy in the [=] kernel lambda, which is not mutable by default
Definition at line 220 of file pipe_accessor.hpp.
{
     static_assert(mode == access::mode::read,
                   "'.read(value_type &value)' method on a pipe accessor"
                   " is only possible with read access mode");
     ok = implementation->read(value, blocking);
     // Return a reference to *this so we can apply a sequence of read
     return *this;
   }
read() [2/2]
template<typename T, access::mode AccessMode, access::target Target> value_type trisycl::detail::pipe_accessor< T, AccessMode, Target >::read () const inline
Read a value from a blocking pipe.
Returns
the read value directly, since it cannot fail on blocking pipe
This function is const so it can work when the accessor is passed by copy in the [=] kernel lambda, which is not mutable by default
Definition at line 239 of file pipe_accessor.hpp.
Referenced by trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >::operator>>().
{
     static_assert(mode == access::mode::read,
                   "'.read()' method on a pipe accessor is only possible"
                   " with read access mode");
     static_assert(blocking,
                   "'.read()' method on a pipe accessor is only possible"
                   " with a blocking pipe");
     value_type value;
     implementation->read(value, blocking);
     return value;
   }
reserve()
template<typename T, access::mode AccessMode, access::target Target> detail::pipe_reservation<pipe_accessor> trisycl::detail::pipe_accessor< T, AccessMode, Target >::reserve (std::size_t size) const inline
Definition at line 263 of file pipe_accessor.hpp.
{
     return { *implementation, size };
   }
set_debug()
template<typename T, access::mode AccessMode, access::target Target> void trisycl::detail::pipe_accessor< T, AccessMode, Target >::set_debug (bool enable) const inline
Set debug mode.
Definition at line 269 of file pipe_accessor.hpp.
{
     implementation->debug_mode = enable;
   }
size()
template<typename T, access::mode AccessMode, access::target Target> std::size_t trisycl::detail::pipe_accessor< T, AccessMode, Target >::size () const inline
Get the current number of elements in the pipe.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement (for example on FPGA).
Definition at line 126 of file pipe_accessor.hpp.
{
     return implementation->size_with_lock();
   }
write()
template<typename T, access::mode AccessMode, access::target Target> const pipe_accessor& trisycl::detail::pipe_accessor< T, AccessMode, Target >::write (const value_type & value) const inline
Try to write a value to the pipe.
Parameters
[in] value is what we want to write
Returns
this so we can apply a sequence of write for example (but do not do this on a non blocking pipe...)
Todo:
provide a && version
This function is const so it can work when the accessor is passed by copy in the [=] kernel lambda, which is not mutable by default
Definition at line 187 of file pipe_accessor.hpp.
Referenced by trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >::operator<<().
{
     static_assert(mode == access::mode::write,
                   "'.write(const value_type &value)' method on a pipe accessor"
                   " is only possible with write access mode");
     ok = implementation->write(value, blocking);
     // Return a reference to *this so we can apply a sequence of write
     return *this;
   }
Member Data Documentation
blocking
template<typename T, access::mode AccessMode, access::target Target> constexpr bool trisycl::detail::pipe_accessor< T, AccessMode, Target >::blocking static
Initial value:
=
    (target == trisycl::access::target::blocking_pipe)
Definition at line 52 of file pipe_accessor.hpp.
implementation
template<typename T, access::mode AccessMode, access::target Target> std::shared_ptr<detail::pipe<T> > trisycl::detail::pipe_accessor< T, AccessMode, Target >::implementation private
The real pipe implementation behind the hood.
Definition at line 63 of file pipe_accessor.hpp.
Referenced by trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >::get_pipe_detail(), and trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >::reserve().
mode
template<typename T, access::mode AccessMode, access::target Target> constexpr auto trisycl::detail::pipe_accessor< T, AccessMode, Target >::mode = AccessMode static
Definition at line 49 of file pipe_accessor.hpp.
ok
template<typename T, access::mode AccessMode, access::target Target> bool trisycl::detail::pipe_accessor< T, AccessMode, Target >::ok = false mutable private
Store the success status of last pipe operation.
It is not impacted by reservation success.
It does exist even if the pipe accessor is not evaluated in a boolean context for, but a use-def analysis can optimise it out in that case and not use some storage
Use a mutable state here so that it can work with a [=] lambda capture without having to declare the whole lambda as mutable
Definition at line 76 of file pipe_accessor.hpp.
Referenced by trisycl::detail::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >::operator bool().
rank
template<typename T, access::mode AccessMode, access::target Target> constexpr auto trisycl::detail::pipe_accessor< T, AccessMode, Target >::rank = 1 static
Definition at line 48 of file pipe_accessor.hpp.
target
template<typename T, access::mode AccessMode, access::target Target> constexpr auto trisycl::detail::pipe_accessor< T, AccessMode, Target >::target = Target static
Definition at line 50 of file pipe_accessor.hpp.
trisycl::pipe
class trisycl::pipe
template<typename T>
class trisycl::pipe< T >
A SYCL pipe.
Implement a FIFO-style object that can be used through accessors to send some objects T from the input to the output
Definition at line 30 of file accessor.hpp.
Public Types
using value_type = T
The STL-like types.
Public Member Functions
pipe (std::size_t capacity)
Construct a pipe able to store up to capacity T objects.
template<access::mode Mode, access::target Target = access::target::pipe>
accessor< value_type, 1, Mode, Target > get_access (handler &command_group_handler)
Get an accessor to the pipe with the required mode.
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< pipe< T >, detail::pipe< T > >
shared_ptr_implementation (std::shared_ptr< detail::pipe< T > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::pipe< T > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const pipe< T > &other) const
Equality operator.
bool operator< (const pipe< T > &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename pipe::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< pipe< T >, detail::pipe< T > >
std::shared_ptr< detail::pipe< T > > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
implementation_t
template<typename T> using trisycl::pipe< T >::implementation_t = typename pipe::shared_ptr_implementation private
Definition at line 39 of file pipe.hpp.
value_type
template<typename T> using trisycl::pipe< T >::value_type = T
The STL-like types.
Definition at line 52 of file pipe.hpp.
Constructor & Destructor Documentation
pipe()
template<typename T> trisycl::pipe< T >::pipe (std::size_t capacity) inline
Construct a pipe able to store up to capacity T objects.
Definition at line 56 of file pipe.hpp.
References trisycl::access::pipe.
     : implementation_t { new detail::pipe<T> { capacity } } { }
Member Function Documentation
capacity()
template<typename T> std::size_t trisycl::pipe< T >::capacity () const inline
Return the maximum number of elements that can fit in the pipe.
Definition at line 82 of file pipe.hpp.
References trisycl::detail::shared_ptr_implementation< pipe< T >, detail::pipe< T > >::implementation.
{
     return implementation->capacity();
     }
get_access()
template<typename T> template<access::mode Mode, access::target Target = access::target::pipe> accessor<value_type, 1, Mode, Target> trisycl::pipe< T >::get_access (handler & command_group_handler) inline
Get an accessor to the pipe with the required mode.
Parameters
Mode is the requested access mode
Target is the type of pipe access required
[in] command_group_handler is the command group handler in which the kernel is to be executed
Definition at line 72 of file pipe.hpp.
References trisycl::access::blocking_pipe, trisycl::detail::shared_ptr_implementation< pipe< T >, detail::pipe< T > >::implementation, and trisycl::access::pipe.
{
     static_assert(Target == access::target::pipe
                   || Target == access::target::blocking_pipe,
                   "get_access(handler) with pipes can only deal with "
                   "access::pipe or access::blocking_pipe");
     return { implementation, command_group_handler };
   }
Member Data Documentation
implementation_t
template<typename T> friend trisycl::pipe< T >::implementation_t private
Definition at line 42 of file pipe.hpp.
trisycl::detail::pipe_reservation
class trisycl::detail::pipe_reservation
template<typename PipeAccessor>
class trisycl::detail::pipe_reservation< PipeAccessor >
The implementation of the pipe reservation station.
Definition at line 31 of file pipe_reservation.hpp.
Public Types
using iterator = typename detail::pipe< value_type >::implementation_t::iterator
using const_iterator = typename detail::pipe< value_type >::implementation_t::const_iterator
Public Member Functions
void assume_validity ()
Test that the reservation is in a usable state.
pipe_reservation (detail::pipe< value_type > &p, std::size_t s)
Create a pipe reservation station that reserves the pipe itself.
pipe_reservation (const pipe_reservation &)=delete
No copy constructor with some spurious commit in the destructor of the original object.
pipe_reservation (pipe_reservation &&orig)
Only a move constructor is required to move it into the shared_ptr.
pipe_reservation ()=default
Keep the default constructors too.
operator bool ()
Test if the reservation succeeded and thus if the reservation can be committed.
iterator begin ()
Start of the reservation area.
iterator end ()
Past the end of the reservation area.
std::size_t size ()
Get the number of elements in the reservation station.
reference operator[] (std::size_t index)
Access to an element of the reservation.
void commit ()
Commit the reservation station.
~pipe_reservation ()
An implicit commit is made in the destructor.
Public Attributes
bool ok = false
True if the reservation was successful and still uncommitted.
detail::pipe< value_type >::rid_iterator rid
Point into the reservation buffer. Only valid if ok is true.
detail::pipe< value_type > & p
Keep a reference on the pipe to access to the data and methods.
Static Public Attributes
static constexpr access::mode mode = accessor_type::mode
static constexpr access::target target = accessor_type::target
Private Types
using accessor_type = PipeAccessor
using value_type = typename accessor_type::value_type
using reference = typename accessor_type::reference
Static Private Attributes
static constexpr bool blocking
Member Typedef Documentation
accessor_type
template<typename PipeAccessor> using trisycl::detail::pipe_reservation< PipeAccessor >::accessor_type = PipeAccessor private
Definition at line 33 of file pipe_reservation.hpp.
const_iterator
template<typename PipeAccessor> using trisycl::detail::pipe_reservation< PipeAccessor >::const_iterator = typename detail::pipe<value_type>::implementation_t::const_iterator
Definition at line 44 of file pipe_reservation.hpp.
iterator
template<typename PipeAccessor> using trisycl::detail::pipe_reservation< PipeAccessor >::iterator = typename detail::pipe<value_type>::implementation_t::iterator
Definition at line 42 of file pipe_reservation.hpp.
reference
template<typename PipeAccessor> using trisycl::detail::pipe_reservation< PipeAccessor >::reference = typename accessor_type::reference private
Definition at line 37 of file pipe_reservation.hpp.
value_type
template<typename PipeAccessor> using trisycl::detail::pipe_reservation< PipeAccessor >::value_type = typename accessor_type::value_type private
Definition at line 36 of file pipe_reservation.hpp.
Constructor & Destructor Documentation
pipe_reservation() [1/4]
template<typename PipeAccessor> trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation (detail::pipe< value_type > & p, std::size_t s) inline
Create a pipe reservation station that reserves the pipe itself.
Definition at line 76 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation(), trisycl::access::read, trisycl::detail::pipe< T >::reserve_read(), trisycl::detail::pipe< T >::reserve_write(), and trisycl::access::write.
                                                            : p { p } {
     static_assert(mode == access::mode::write
                   || mode == access::mode::read,
                   "A pipe can only be accesed in read or write mode,"
                   " exclusively");
     /* Since this test is constexpr and dependent of a template
        parameter, it should be equivalent to a specialization of the
        method but in a clearer way */
     if (mode == access::mode::write)
       ok = p.reserve_write(s, rid, blocking);
     else
       ok = p.reserve_read(s, rid, blocking);
   }
pipe_reservation() [2/4]
template<typename PipeAccessor> trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation (const pipe_reservation< PipeAccessor > &) delete
No copy constructor with some spurious commit in the destructor of the original object.
pipe_reservation() [3/4]
template<typename PipeAccessor> trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation (pipe_reservation< PipeAccessor > && orig) inline
Only a move constructor is required to move it into the shared_ptr.
Definition at line 99 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation().
                                             :
     ok {orig.ok },
     rid {orig.rid },
     p { orig.p } {
       /* Even when an object is moved, the destructor of the old
          object is eventually called, so leave the old object in a
          destructable state but without any commit capability */
       orig.ok = false;
     }
pipe_reservation() [4/4]
template<typename PipeAccessor> trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation () default
Keep the default constructors too.
Otherwise there is no move semantics and the copy is made by creating a new reservation and destructing the old one with a spurious commit in the meantime...
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::pipe_reservation().
~pipe_reservation()
template<typename PipeAccessor> trisycl::detail::pipe_reservation< PipeAccessor >::~pipe_reservation () inline
An implicit commit is made in the destructor.
Definition at line 183 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::commit().
                       {
     commit();
   }
Member Function Documentation
assume_validity()
template<typename PipeAccessor> void trisycl::detail::pipe_reservation< PipeAccessor >::assume_validity () inline
Test that the reservation is in a usable state.
Todo:
Throw exception instead
Definition at line 69 of file pipe_reservation.hpp.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::begin(), trisycl::detail::pipe_reservation< PipeAccessor >::end(), trisycl::detail::pipe_reservation< PipeAccessor >::operator[](), and trisycl::detail::pipe_reservation< PipeAccessor >::size().
{
     assert(ok);
   }
begin()
template<typename PipeAccessor> iterator trisycl::detail::pipe_reservation< PipeAccessor >::begin () inline
Start of the reservation area.
Definition at line 132 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::assume_validity().
                    {
     assume_validity();
     return rid->start;
   }
commit()
template<typename PipeAccessor> void trisycl::detail::pipe_reservation< PipeAccessor >::commit () inline
Commit the reservation station.
Todo:
Add to the specification that for simplicity a reservation can be commited several times but only the first one is taken into account
Definition at line 168 of file pipe_reservation.hpp.
References trisycl::detail::pipe< T >::move_read_reservation_forward(), trisycl::detail::pipe< T >::move_write_reservation_forward(), TRISYCL_DUMP_T, and trisycl::access::write.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::~pipe_reservation().
                 {
     if (ok) {
       // If the reservation is in a committable state, commit
       TRISYCL_DUMP_T("Commit");
       rid->ready = true;
       if (mode == access::mode::write)
         p.move_write_reservation_forward();
       else
         p.move_read_reservation_forward();
       ok = false;
     }
   }
end()
template<typename PipeAccessor> iterator trisycl::detail::pipe_reservation< PipeAccessor >::end () inline
Past the end of the reservation area.
Definition at line 139 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::assume_validity(), and trisycl::detail::pipe< T >::size().
                  {
     assume_validity();
     return rid->start + rid->size;
   }
operator bool()
template<typename PipeAccessor> trisycl::detail::pipe_reservation< PipeAccessor >::operator bool () inline
Test if the reservation succeeded and thus if the reservation can be committed.
Note that it is up to the user to ensure that all the reservation elements have been initialized correctly in the case of a write for example
Definition at line 126 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::ok.
                   {
     return ok;
   }
operator[]()
template<typename PipeAccessor> reference trisycl::detail::pipe_reservation< PipeAccessor >::operator[] (std::size_t index) inline
Access to an element of the reservation.
Definition at line 153 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::assume_validity(), and TRISYCL_DUMP_T.
{
     assume_validity();
     TRISYCL_DUMP_T("[] index = " << index
                    << " Reservation write address = " << &(rid->start[index]));
     return rid->start[index];
   }
size()
template<typename PipeAccessor> std::size_t trisycl::detail::pipe_reservation< PipeAccessor >::size () inline
Get the number of elements in the reservation station.
Definition at line 146 of file pipe_reservation.hpp.
References trisycl::detail::pipe_reservation< PipeAccessor >::assume_validity(), and trisycl::detail::pipe< T >::size().
                    {
     assume_validity();
     return rid->size;
   }
Member Data Documentation
blocking
template<typename PipeAccessor> constexpr bool trisycl::detail::pipe_reservation< PipeAccessor >::blocking static private
Initial value:
=
    (accessor_type::target == trisycl::access::target::blocking_pipe)
Definition at line 34 of file pipe_reservation.hpp.
mode
template<typename PipeAccessor> constexpr access::mode trisycl::detail::pipe_reservation< PipeAccessor >::mode = accessor_type::mode static
Definition at line 47 of file pipe_reservation.hpp.
ok
template<typename PipeAccessor> bool trisycl::detail::pipe_reservation< PipeAccessor >::ok = false
True if the reservation was successful and still uncommitted.
B default a pipe_reservation is not reserved and cannot be committed
Definition at line 53 of file pipe_reservation.hpp.
Referenced by trisycl::detail::pipe_reservation< PipeAccessor >::operator bool().
p
template<typename PipeAccessor> detail::pipe<value_type>& trisycl::detail::pipe_reservation< PipeAccessor >::p
Keep a reference on the pipe to access to the data and methods.
Note that with inlining and CSE it should not use more register when compiler optimization is in use.
Definition at line 62 of file pipe_reservation.hpp.
rid
template<typename PipeAccessor> detail::pipe<value_type>::rid_iterator trisycl::detail::pipe_reservation< PipeAccessor >::rid
Point into the reservation buffer. Only valid if ok is true.
Definition at line 56 of file pipe_reservation.hpp.
target
template<typename PipeAccessor> constexpr access::target trisycl::detail::pipe_reservation< PipeAccessor >::target = accessor_type::target static
Definition at line 48 of file pipe_reservation.hpp.
trisycl::pipe_reservation
struct trisycl::pipe_reservation
template<typename PipeAccessor>
struct trisycl::pipe_reservation< PipeAccessor >
The pipe reservation station allows to reserve an array-like view inside the pipe for ordered race-free access from various work-items for example.
Definition at line 29 of file pipe_reservation.hpp.
Public Types
using accessor_type = PipeAccessor
using accessor_detail = typename accessor_type::accessor_detail
using value_type = typename accessor_type::value_type
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
using pointer = value_type *
using const_pointer = const value_type *
using size_type = std::size_t
using difference_type = ptrdiff_t
using iterator = typename detail::pipe_reservation< accessor_detail >::iterator
using const_iterator = typename detail::pipe_reservation< accessor_detail >::const_iterator
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
pipe_reservation ()=default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or a r-value (for std::move() for example).
pipe_reservation (accessor_type &accessor, std::size_t s)
Create a pipe_reservation for an accessor and a number of elements.
pipe_reservation (detail::pipe_reservation< accessor_detail > &&pr)
Create a pipe_reservation from the implementation detail.
operator bool () const
Test if the pipe_reservation has been correctly allocated.
std::size_t size () const
Get the number of reserved element(s)
reference operator[] (std::size_t index) const
Access to a given element of the reservation.
void commit () const
Force a commit operation.
iterator begin () const
Get an iterator on the first element of the reservation station.
iterator end () const
Get an iterator past the end of the reservation station.
const_iterator cbegin () const
Build a constant iterator on the first element of the reservation station.
const_iterator cend () const
Build a constant iterator past the end of the reservation station.
reverse_iterator rbegin () const
Get a reverse iterator on the last element of the reservation station.
reverse_iterator rend () const
Get a reverse iterator on the first element past the end of the reservation station.
const_reverse_iterator crbegin () const
Get a constant reverse iterator on the last element of the reservation station.
const_reverse_iterator crend () const
Get a constant reverse iterator on the first element past the end of the reservation station.
Public Attributes
std::shared_ptr< detail::pipe_reservation< accessor_detail > > implementation
Point to the underlying implementation that can be shared in the SYCL model with a handler semantics.
Static Public Attributes
static constexpr bool blocking
Member Typedef Documentation
accessor_detail
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::accessor_detail = typename accessor_type::accessor_detail
Definition at line 33 of file pipe_reservation.hpp.
accessor_type
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::accessor_type = PipeAccessor
Definition at line 30 of file pipe_reservation.hpp.
const_iterator
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::const_iterator = typename detail::pipe_reservation<accessor_detail>::const_iterator
Definition at line 45 of file pipe_reservation.hpp.
const_pointer
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::const_pointer = const value_type*
Definition at line 39 of file pipe_reservation.hpp.
const_reference
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::const_reference = const value_type&
Definition at line 37 of file pipe_reservation.hpp.
const_reverse_iterator
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 47 of file pipe_reservation.hpp.
difference_type
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::difference_type = ptrdiff_t
Definition at line 41 of file pipe_reservation.hpp.
iterator
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::iterator = typename detail::pipe_reservation<accessor_detail>::iterator
Definition at line 43 of file pipe_reservation.hpp.
pointer
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::pointer = value_type*
Definition at line 38 of file pipe_reservation.hpp.
reference
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::reference = value_type&
Definition at line 36 of file pipe_reservation.hpp.
reverse_iterator
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 46 of file pipe_reservation.hpp.
size_type
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::size_type = std::size_t
Definition at line 40 of file pipe_reservation.hpp.
value_type
template<typename PipeAccessor > using trisycl::pipe_reservation< PipeAccessor >::value_type = typename accessor_type::value_type
The STL-like types.
Definition at line 35 of file pipe_reservation.hpp.
Constructor & Destructor Documentation
pipe_reservation() [1/3]
template<typename PipeAccessor > trisycl::pipe_reservation< PipeAccessor >::pipe_reservation () default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or a r-value (for std::move() for example).
Since we just copy the shared_ptr<> above, this is where/how the sharing magic is happening with reference counting in this case.
pipe_reservation() [2/3]
template<typename PipeAccessor > trisycl::pipe_reservation< PipeAccessor >::pipe_reservation (accessor_type & accessor, std::size_t s) inline
Create a pipe_reservation for an accessor and a number of elements.
Definition at line 65 of file pipe_reservation.hpp.
References trisycl::get_pipe_detail().
     : implementation {
     new detail::pipe_reservation<accessor_detail> {
       get_pipe_detail(accessor), s }
   } {}
pipe_reservation() [3/3]
template<typename PipeAccessor > trisycl::pipe_reservation< PipeAccessor >::pipe_reservation (detail::pipe_reservation< accessor_detail > && pr) inline
Create a pipe_reservation from the implementation detail.
This is an internal constructor to allow reserve() on the implementation to lift a full-fledged object through accessor::reserve().
Todo:
Make it private and add required friends
Definition at line 80 of file pipe_reservation.hpp.
     : implementation {
     new detail::pipe_reservation<accessor_detail> { std::move(pr) } }
   {}
Member Function Documentation
begin()
template<typename PipeAccessor > iterator trisycl::pipe_reservation< PipeAccessor >::begin () const inline
Get an iterator on the first element of the reservation station.
Definition at line 118 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
Referenced by trisycl::pipe_reservation< PipeAccessor >::rend().
{
     return implementation->begin();
   }
cbegin()
template<typename PipeAccessor > const_iterator trisycl::pipe_reservation< PipeAccessor >::cbegin () const inline
Build a constant iterator on the first element of the reservation station.
Definition at line 130 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
Referenced by trisycl::pipe_reservation< PipeAccessor >::crend().
{
     return implementation->begin();
   }
cend()
template<typename PipeAccessor > const_iterator trisycl::pipe_reservation< PipeAccessor >::cend () const inline
Build a constant iterator past the end of the reservation station.
Definition at line 136 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
Referenced by trisycl::pipe_reservation< PipeAccessor >::crbegin().
{
     return implementation->end();
   }
commit()
template<typename PipeAccessor > void trisycl::pipe_reservation< PipeAccessor >::commit () const inline
Force a commit operation.
Normally the commit is implicitly done in the destructor, but sometime it is useful to do it earlier.
Definition at line 112 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
                       {
     return implementation->commit();
   }
crbegin()
template<typename PipeAccessor > const_reverse_iterator trisycl::pipe_reservation< PipeAccessor >::crbegin () const inline
Get a constant reverse iterator on the last element of the reservation station.
Definition at line 156 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::cend().
{
     return std::make_reverse_iterator(cend());
   }
crend()
template<typename PipeAccessor > const_reverse_iterator trisycl::pipe_reservation< PipeAccessor >::crend () const inline
Get a constant reverse iterator on the first element past the end of the reservation station.
Definition at line 163 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::cbegin().
{
     return std::make_reverse_iterator(cbegin());
   }
end()
template<typename PipeAccessor > iterator trisycl::pipe_reservation< PipeAccessor >::end () const inline
Get an iterator past the end of the reservation station.
Definition at line 124 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
Referenced by trisycl::pipe_reservation< PipeAccessor >::rbegin().
{
     return implementation->end();
   }
operator bool()
template<typename PipeAccessor > trisycl::pipe_reservation< PipeAccessor >::operator bool () const inline
Test if the pipe_reservation has been correctly allocated.
Returns
true if the pipe_reservation can be used and committed
Definition at line 90 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
{
     return *implementation;
   }
operator[]()
template<typename PipeAccessor > reference trisycl::pipe_reservation< PipeAccessor >::operator[] (std::size_t index) const inline
Access to a given element of the reservation.
Definition at line 102 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
{
     return (*implementation)[index];
   }
rbegin()
template<typename PipeAccessor > reverse_iterator trisycl::pipe_reservation< PipeAccessor >::rbegin () const inline
Get a reverse iterator on the last element of the reservation station.
Definition at line 142 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::end().
{
     return std::make_reverse_iterator(end());
   }
rend()
template<typename PipeAccessor > reverse_iterator trisycl::pipe_reservation< PipeAccessor >::rend () const inline
Get a reverse iterator on the first element past the end of the reservation station.
Definition at line 149 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::begin().
{
     return std::make_reverse_iterator(begin());
   }
size()
template<typename PipeAccessor > std::size_t trisycl::pipe_reservation< PipeAccessor >::size () const inline
Get the number of reserved element(s)
Definition at line 96 of file pipe_reservation.hpp.
References trisycl::pipe_reservation< PipeAccessor >::implementation.
{
     return implementation->size();
   }
Member Data Documentation
blocking
template<typename PipeAccessor > constexpr bool trisycl::pipe_reservation< PipeAccessor >::blocking static
Initial value:
=
    (accessor_type::target == trisycl::access::target::blocking_pipe)
Definition at line 31 of file pipe_reservation.hpp.
implementation
template<typename PipeAccessor > std::shared_ptr<detail::pipe_reservation<accessor_detail> > trisycl::pipe_reservation< PipeAccessor >::implementation
Point to the underlying implementation that can be shared in the SYCL model with a handler semantics.
Definition at line 52 of file pipe_reservation.hpp.
Referenced by trisycl::pipe_reservation< PipeAccessor >::begin(), trisycl::pipe_reservation< PipeAccessor >::cbegin(), trisycl::pipe_reservation< PipeAccessor >::cend(), trisycl::pipe_reservation< PipeAccessor >::commit(), trisycl::pipe_reservation< PipeAccessor >::end(), trisycl::pipe_reservation< PipeAccessor >::operator bool(), trisycl::pipe_reservation< PipeAccessor >::operator[](), and trisycl::pipe_reservation< PipeAccessor >::size().
trisycl::static_pipe
class trisycl::static_pipe
template<typename T, std::size_t Capacity>
class trisycl::static_pipe< T, Capacity >
A SYCL static-scoped pipe equivalent to an OpenCL program-scoped pipe.
Implement a FIFO-style object that can be used through accessors to send some objects T from the input to the output.
Compared to a normal pipe, a static_pipe takes a constexpr size and is expected to be declared in a compile-unit static context so the compiler can generate everything at compile time.
This is useful to generate a fixed and optimized hardware implementation on FPGA for example, where the interconnection graph can be also inferred at compile time.
It is not directly mapped to the OpenCL program-scoped pipe because in SYCL there is not this concept of separated program. But the SYCL device compiler is expected to generate some OpenCL program(s) with program-scoped pipes when a SYCL static-scoped pipe is used. These details are implementation defined.
Definition at line 49 of file static_pipe.hpp.
Public Types
using value_type = T
The STL-like types.
Public Member Functions
static_pipe ()
Construct a static-scoped pipe able to store up to Capacity T objects.
template<access::mode Mode, access::target Target = access::target::pipe>
accessor< value_type, 1, Mode, Target > get_access (handler &command_group_handler)
Get an accessor to the pipe with the required mode.
template<access::mode Mode, access::target Target = access::target::pipe>
accessor< value_type, 1, Mode, Target > get_access ()
Get an accessor to the pipe with the required mode, outside of a normal kernel, for example in host code.
std::size_t constexpr capacity () const
Return the maximum number of elements that can fit in the pipe.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::pipe< T > >
shared_ptr_implementation (std::shared_ptr< detail::pipe< T > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::pipe< T > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const static_pipe< T, Capacity > &other) const
Equality operator.
bool operator< (const static_pipe< T, Capacity > &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename static_pipe::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::pipe< T > >
std::shared_ptr< detail::pipe< T > > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
implementation_t
template<typename T , std::size_t Capacity> using trisycl::static_pipe< T, Capacity >::implementation_t = typename static_pipe::shared_ptr_implementation private
Definition at line 57 of file static_pipe.hpp.
value_type
template<typename T , std::size_t Capacity> using trisycl::static_pipe< T, Capacity >::value_type = T
The STL-like types.
Definition at line 68 of file static_pipe.hpp.
Constructor & Destructor Documentation
static_pipe()
template<typename T , std::size_t Capacity> trisycl::static_pipe< T, Capacity >::static_pipe () inline
Construct a static-scoped pipe able to store up to Capacity T objects.
Definition at line 72 of file static_pipe.hpp.
References trisycl::access::pipe.
     : implementation_t { new detail::pipe<T> { Capacity } } { }
Member Function Documentation
capacity()
template<typename T , std::size_t Capacity> std::size_t constexpr trisycl::static_pipe< T, Capacity >::capacity () const inline
Return the maximum number of elements that can fit in the pipe.
This is a constexpr since the capacity is in the type.
Definition at line 120 of file static_pipe.hpp.
{
     return Capacity;
     }
get_access() [1/2]
template<typename T , std::size_t Capacity> template<access::mode Mode, access::target Target = access::target::pipe> accessor<value_type, 1, Mode, Target> trisycl::static_pipe< T, Capacity >::get_access (handler & command_group_handler) inline
Get an accessor to the pipe with the required mode.
Parameters
Mode is the requested access mode
Target is the type of pipe access required
[in] command_group_handler is the command group handler in which the kernel is to be executed
Definition at line 88 of file static_pipe.hpp.
References trisycl::access::blocking_pipe, trisycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::pipe< T > >::implementation, and trisycl::access::pipe.
{
     static_assert(Target == access::target::pipe
                   || Target == access::target::blocking_pipe,
                   "get_access(handler) with pipes can only deal with "
                   "access::pipe or access::blocking_pipe");
     return { implementation, command_group_handler };
   }
get_access() [2/2]
template<typename T , std::size_t Capacity> template<access::mode Mode, access::target Target = access::target::pipe> accessor<value_type, 1, Mode, Target> trisycl::static_pipe< T, Capacity >::get_access () inline
Get an accessor to the pipe with the required mode, outside of a normal kernel, for example in host code.
Parameters
Mode is the requested access mode
Target is the type of pipe access required
Definition at line 107 of file static_pipe.hpp.
References trisycl::access::blocking_pipe, trisycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::pipe< T > >::implementation, and trisycl::access::pipe.
                {
     static_assert(Target == access::target::pipe
                   || Target == access::target::blocking_pipe,
                   "get_access(handler) with pipes can only deal with "
                   "access::pipe or access::blocking_pipe");
     return { implementation };
   }
Member Data Documentation
implementation_t
template<typename T , std::size_t Capacity> friend trisycl::static_pipe< T, Capacity >::implementation_t private
Definition at line 63 of file static_pipe.hpp.
Typedef Documentation
buffer_allocator
template<typename T > using trisycl::buffer_allocator = typedef std::allocator<T>
#include <include/triSYCL/allocator.hpp>
The allocator objects give the programmer some control on how the memory is allocated inside SYCL.
The default buffer allocator used by the runtime, when no allocator is defined by the user.
The allocator used for the buffer inside SYCL
Just use the default allocator for now.
Reuse the C++ default allocator.
Definition at line 29 of file allocator.hpp.
image_allocator
template<typename T > using trisycl::image_allocator = typedef std::allocator<T>
#include <include/triSYCL/allocator.hpp>
The allocator used for the image inside SYCL.
Just use the default allocator for now.
Definition at line 37 of file allocator.hpp.
map_allocator
template<typename T > using trisycl::map_allocator = typedef std::allocator<T>
#include <include/triSYCL/allocator.hpp>
The allocator used to map the memory at the same place.
Just use the default allocator for now.
Todo:
: implement and clarify the specification. It looks like it is not really an allocator according the current spec
Definition at line 48 of file allocator.hpp.
Function Documentation
add_buffer_to_task()
static std::shared_ptr<detail::task> trisycl::detail::add_buffer_to_task (handler * command_group_handler, std::shared_ptr< detail::buffer_base > b, bool is_write_mode) inline static
#include <include/triSYCL/buffer/detail/buffer_base.hpp>
Referenced by trisycl::detail::buffer_base::add_to_task().
buffer_add_to_task()
template<typename BufferDetail > static std::shared_ptr<detail::task> trisycl::detail::buffer_add_to_task (BufferDetail buf, handler * command_group_handler, bool is_write_mode) static
#include <include/triSYCL/buffer/detail/buffer.hpp>
Proxy function to avoid some circular type recursion.
Returns
a shared_ptr<task>
Todo:
To remove with some refactoring
Definition at line 429 of file buffer.hpp.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::accessor().
{
     return buf->add_to_task(command_group_handler, is_write_mode);
   }
get_pipe_detail()
template<typename Accessor > static auto& trisycl::get_pipe_detail (Accessor & a) inline static
#include <include/triSYCL/accessor.hpp>
Top-level function to break circular dependencies on the the types to get the pipe implementation.
Definition at line 487 of file accessor.hpp.
Referenced by trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::get_pipe_detail(), trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::get_pipe_detail(), and trisycl::pipe_reservation< PipeAccessor >::pipe_reservation().
{
   return a.get_pipe_detail();
   }
waiter()
template<typename T , int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>> auto trisycl::detail::waiter (detail::buffer< T, Dimensions > * b) inline
#include <include/triSYCL/buffer/detail/buffer_waiter.hpp>
Helper function to create a new buffer_waiter.
Definition at line 77 of file buffer_waiter.hpp.
Referenced by trisycl::buffer< T, Dimensions, Allocator >::buffer().
{
   return new buffer_waiter<T, Dimensions, Allocator> { b };
 }