triSYCL implementation of SYCL: AI Engine CGRA
AI Engine CGRA
Extensions for Xilinx ACAP Versal
Extensions to support explicit AI Engine system-wide programming in C++.
Namespaces
namespace trisycl
The vector type to be used as SYCL vector.
namespace trisycl::vendor
namespace trisycl::vendor::xilinx
namespace trisycl::vendor::xilinx::acap
namespace trisycl::vendor::xilinx::acap::aie
namespace trisycl::vendor::xilinx::acap::aie::detail
namespace trisycl::vendor::xilinx::acap::aie::layout
Classes
class trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >
An AXI stream switch parameterized with some geographic layout.
struct trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >
Implementation of the cascade stream infrastructure between AI Engine tiles.
class trisycl::vendor::xilinx::acap::aie::axi_packet
class trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >
Implement a small DSL to chain DMA & locking operations like allowed by the hardware.
struct trisycl::vendor::xilinx::acap::aie::geography< Layout >
Some geographic information about the AI Engine array.
struct trisycl::vendor::xilinx::acap::aie::layout::full
Describe the layout of a "big" AI Engine array.
struct trisycl::vendor::xilinx::acap::aie::layout::one_pe
Describe the layout of a tiny AI Engine with only 1 tile.
struct trisycl::vendor::xilinx::acap::aie::layout::size< X_size, Y_size >
Fully specify the size of an AI Engine layout.
struct trisycl::vendor::xilinx::acap::aie::layout::small
Describe the layout of a small AI Engine array with only a few PE.
struct trisycl::vendor::xilinx::acap::aie::layout::ve1152
struct trisycl::vendor::xilinx::acap::aie::lock_unit
The lock infrastructure used by AI Engine memory modules and shim tiles.
struct trisycl::vendor::xilinx::acap::aie::memory< AIE, X, Y >
The AI Engine Memory Module infrastructure of a tile.
struct trisycl::vendor::xilinx::acap::aie::memory_base
The AI Engine Memory Module infrastructure of a tile common to all the tiles.
class trisycl::vendor::xilinx::acap::aie::memory_infrastructure
The AI Engine memory infrastructure common to all the tiles.
struct trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >
Define an AI Engine CGRA program with its code and memory per core.
struct trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >
The AI Engine minimal queue.
class trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >
The AI Engine shim tile infrastructure.
struct trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >
The AI Engine tile infrastructure defining the program of a tile.
class trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >
The AI Engine tile infrastructure common to all the tiles.
class trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >
The AI Engine tile infrastructure common to all the tiles.
class trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >
The AI Engine tile infrastructure common to all the tiles.
Detailed Description
Extensions to support explicit AI Engine system-wide programming in C++.
Class Documentation
trisycl::vendor::xilinx::acap::aie::axi_stream_switch
class trisycl::vendor::xilinx::acap::aie::axi_stream_switch
template<typename AXIStreamGeography>
class trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >
An AXI stream switch parameterized with some geographic layout.
Parameters
[in] AxiStreamGeography is the geography class used to instantiate the AXI stream switch.
Definition at line 51 of file axi_stream_switch.hpp.
Public Types
using axi_ss_geo = AXIStreamGeography
using mpl = typename axi_ss_geo::master_port_layout
using spl = typename axi_ss_geo::slave_port_layout
using data_type = std::uint32_t
using axi_ss_geo = AXIStreamGeography
using mpl = typename axi_ss_geo::master_port_layout
using spl = typename axi_ss_geo::slave_port_layout
using data_type = std::uint32_t
Public Member Functions
auto & in_connection (spl sp)
Access the input connection behind an input port.
auto & out_connection (mpl mp)
Access the output connection behind an output port.
void connect (spl sp, mpl mp)
Configure a connection of the shim AXI stream switch.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the input router port of the AXI stream switch.
axi_stream_switch ()
Connect the internals of the AXI stream switch.
void start (int x, int y, ::trisycl::detail::fiber_pool &fiber_executor)
Start the tile infrastructure associated to the AIE device.
int tikz_edge_angle (const std::string_view &port_name, const std::initializer_list< std::tuple< std::string_view, int > > &desc) const
Compute the edge angle for a port name according a list of description associating a port name prefix and an associated angle in degree.
void display_routing_configuration (latex::context &c) const
Display the internal switch connections with routing arrows perpendicular to the borders.
template<typename FG , typename FL , typename... EnumRanges>
auto display_border (const std::string_view &node_attribute, FG &&global_coordinate_function, FL &&local_coordinate_function, EnumRanges &&... enum_ranges) const
Display a border of the AXI stream switch.
template<typename GTC >
void display (latex::context &c, const vec< int, 2 > &core_size, const GTC &get_tikz_coordinate) const
Display the AXI stream switch.
auto & in_connection (spl sp)
Access the input connection behind an input port.
auto & out_connection (mpl mp)
Access the output connection behind an output port.
void connect (spl sp, mpl mp)
Configure a connection of the shim AXI stream switch.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the input router port of the AXI stream switch.
axi_stream_switch ()
Connect the internals of the AXI stream switch.
void start (int x, int y, ::trisycl::detail::fiber_pool &fiber_executor)
Start the tile infrastructure associated to the AIE device.
int tikz_edge_angle (const std::string_view &port_name, const std::initializer_list< std::tuple< std::string_view, int > > &desc) const
Compute the edge angle for a port name according a list of description associating a port name prefix and an associated angle in degree.
void display_routing_configuration (latex::context &c) const
Display the internal switch connections with routing arrows perpendicular to the borders.
template<typename FG , typename FL , typename... EnumRanges>
auto display_border (const std::string_view &node_attribute, FG &&global_coordinate_function, FL &&local_coordinate_function, EnumRanges &&... enum_ranges) const
Display a border of the AXI stream switch.
template<typename GTC >
void display (latex::context &c, const vec< int, 2 > &core_size, const GTC &get_tikz_coordinate) const
Display the AXI stream switch.
Static Public Member Functions
static router_minion * get_as_router_minion (communicator_port *rp)
Get the router_minion behind a communicator_port.
static vec< int, 2 > display_size ()
Compute the size of the graphics representation of the switch.
static router_minion * get_as_router_minion (communicator_port *rp)
Get the router_minion behind a communicator_port.
static vec< int, 2 > display_size ()
Compute the size of the graphics representation of the switch.
Public Attributes
std::array< std::shared_ptr< communicator_port >, axi_ss_geo::nb_slave_port > input_ports
The input ports used to send information to the switch.
std::array< std::shared_ptr< communicator_port >, axi_ss_geo::nb_master_port > output_ports
The input ports used to send information to the switch.
int x_coordinate
Keep the horizontal coordinate for debug purpose.
int y_coordinate
Keep the vertical coordinate for debug purpose.
Static Public Attributes
static auto translate_port
Validate the user port number and translate it to the physical port number.
static constexpr auto stream_latency = 4
Additional Inherited Members
Static Private Member Functions inherited from trisycl::detail::debug< axi_stream_switch< AXIStreamGeography > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Typedef Documentation
axi_ss_geo [1/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::axi_ss_geo = AXIStreamGeography
Definition at line 56 of file axi_stream_switch.hpp.
axi_ss_geo [2/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::axi_ss_geo = AXIStreamGeography
Definition at line 56 of file axi_stream_switch.hpp.
data_type [1/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::data_type = std::uint32_t
Definition at line 334 of file axi_stream_switch.hpp.
data_type [2/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::data_type = std::uint32_t
Definition at line 334 of file axi_stream_switch.hpp.
mpl [1/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::mpl = typename axi_ss_geo::master_port_layout
Definition at line 57 of file axi_stream_switch.hpp.
mpl [2/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::mpl = typename axi_ss_geo::master_port_layout
Definition at line 57 of file axi_stream_switch.hpp.
spl [1/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::spl = typename axi_ss_geo::slave_port_layout
Definition at line 58 of file axi_stream_switch.hpp.
spl [2/2]
template<typename AXIStreamGeography > using trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::spl = typename axi_ss_geo::slave_port_layout
Definition at line 58 of file axi_stream_switch.hpp.
Constructor & Destructor Documentation
axi_stream_switch() [1/2]
template<typename AXIStreamGeography > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::axi_stream_switch () inline
Connect the internals of the AXI stream switch.
Definition at line 412 of file axi_stream_switch.hpp.
                      {
    // \todo DMA
    // \todo CTRL
  }
axi_stream_switch() [2/2]
template<typename AXIStreamGeography > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::axi_stream_switch () inline
Connect the internals of the AXI stream switch.
Definition at line 412 of file axi_stream_switch.hpp.
                      {
    // \todo DMA
    // \todo CTRL
  }
Member Function Documentation
connect() [1/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::connect (spl sp, mpl mp) inline
Configure a connection of the shim AXI stream switch.
Parameters
[in] sp is the input port number
[in] mp is the output port number
Exceptions
trisycl::runtime_error if the port number is invalid
Definition at line 325 of file axi_stream_switch.hpp.
{
    TRISYCL_DUMP_T("connect " << this
                   << " input: " << magic_enum::enum_name(sp)
                   << " to output: " << magic_enum::enum_name(mp));
    get_as_router_minion(in_connection(sp).get())
      ->connect_to(mp, out_connection(mp));
  }
References std::get(), and TRISYCL_DUMP_T.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::connect(), and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::connect().
connect() [2/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::connect (spl sp, mpl mp) inline
Configure a connection of the shim AXI stream switch.
Parameters
[in] sp is the input port number
[in] mp is the output port number
Exceptions
trisycl::runtime_error if the port number is invalid
Definition at line 325 of file axi_stream_switch.hpp.
{
    TRISYCL_DUMP_T("connect " << this
                   << " input: " << magic_enum::enum_name(sp)
                   << " to output: " << magic_enum::enum_name(mp));
    get_as_router_minion(in_connection(sp).get())
      ->connect_to(mp, out_connection(mp));
  }
References std::get(), and TRISYCL_DUMP_T.
display() [1/2]
template<typename AXIStreamGeography > template<typename GTC > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display (latex::context & c, const vec< int, 2 > & core_size, const GTC & get_tikz_coordinate) const inline
Display the AXI stream switch.
Definition at line 567 of file axi_stream_switch.hpp.
{
    const auto [ width, height ] = display_size();
    // Display the network interfaces on the top of the switch
    c.add(display_border
          ("rotate=90,anchor=north west", get_tikz_coordinate,
           [&, height = height] (auto i) {
             return std::tuple
               { core_size.x()
                   + ranges::distance(axi_ss_geo::s_me_range)
                   + ranges::distance(axi_ss_geo::s_dma_range)
                   + ranges::distance(axi_ss_geo::s_tile_ctrl_range)
                   + ranges::distance(axi_ss_geo::s_fifo_range) + i,
                  core_size.y() + height - 1 };
           },
           axi_ss_geo::m_north_range,
           axi_ss_geo::s_north_range));
    // Display the network interfaces on the bottom of the switch
    c.add(display_border("rotate=90,anchor=north east",
                         get_tikz_coordinate,
                         [&] (auto i) {
                           return std::tuple { core_size.x() + i,
                                               core_size.y() };
                         },
                         ranges::views::reverse(axi_ss_geo::s_me_range),
                         axi_ss_geo::s_dma_range,
                         axi_ss_geo::s_tile_ctrl_range,
                         axi_ss_geo::s_fifo_range,
                         axi_ss_geo::s_south_range,
                         axi_ss_geo::m_south_range));
    // Display the network interfaces on the left of the switch
    c.add(display_border("anchor=south east",
                         get_tikz_coordinate,
                         [&] (auto i) {
                           return std::tuple { core_size.x() - 1,
                                               core_size.y() + i + 1 };
                         },
                         ranges::views::reverse(axi_ss_geo::m_me_range),
                         axi_ss_geo::m_dma_range,
                         axi_ss_geo::m_tile_ctrl_range,
                         axi_ss_geo::m_fifo_range,
                         axi_ss_geo::m_west_range,
                         axi_ss_geo::s_west_range));
    // Display the network interfaces on the right of the switch
    c.add(display_border
          ("anchor=south west",
           get_tikz_coordinate,
           [&, width = width] (auto i) {
             return std::tuple
               { core_size.x() + width - 1,
                  core_size.y() + i + 1
                  + ranges::distance(axi_ss_geo::m_me_range)
                  + ranges::distance(axi_ss_geo::m_dma_range)
                  + ranges::distance(axi_ss_geo::m_tile_ctrl_range)
                  + ranges::distance(axi_ss_geo::m_fifo_range) };
           },
           axi_ss_geo::s_east_range,
References c, and i.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display().
display() [2/2]
template<typename AXIStreamGeography > template<typename GTC > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display (latex::context & c, const vec< int, 2 > & core_size, const GTC & get_tikz_coordinate) const inline
Display the AXI stream switch.
Definition at line 567 of file axi_stream_switch.hpp.
{
    const auto [ width, height ] = display_size();
    // Display the network interfaces on the top of the switch
    c.add(display_border
          ("rotate=90,anchor=north west", get_tikz_coordinate,
           [&, height = height] (auto i) {
             return std::tuple
               { core_size.x()
                   + ranges::distance(axi_ss_geo::s_me_range)
                   + ranges::distance(axi_ss_geo::s_dma_range)
                   + ranges::distance(axi_ss_geo::s_tile_ctrl_range)
                   + ranges::distance(axi_ss_geo::s_fifo_range) + i,
                  core_size.y() + height - 1 };
           },
           axi_ss_geo::m_north_range,
           axi_ss_geo::s_north_range));
    // Display the network interfaces on the bottom of the switch
    c.add(display_border("rotate=90,anchor=north east",
                         get_tikz_coordinate,
                         [&] (auto i) {
                           return std::tuple { core_size.x() + i,
                                               core_size.y() };
                         },
                         ranges::views::reverse(axi_ss_geo::s_me_range),
                         axi_ss_geo::s_dma_range,
                         axi_ss_geo::s_tile_ctrl_range,
                         axi_ss_geo::s_fifo_range,
                         axi_ss_geo::s_south_range,
                         axi_ss_geo::m_south_range));
    // Display the network interfaces on the left of the switch
    c.add(display_border("anchor=south east",
                         get_tikz_coordinate,
                         [&] (auto i) {
                           return std::tuple { core_size.x() - 1,
                                               core_size.y() + i + 1 };
                         },
                         ranges::views::reverse(axi_ss_geo::m_me_range),
                         axi_ss_geo::m_dma_range,
                         axi_ss_geo::m_tile_ctrl_range,
                         axi_ss_geo::m_fifo_range,
                         axi_ss_geo::m_west_range,
                         axi_ss_geo::s_west_range));
    // Display the network interfaces on the right of the switch
    c.add(display_border
          ("anchor=south west",
           get_tikz_coordinate,
           [&, width = width] (auto i) {
             return std::tuple
               { core_size.x() + width - 1,
                  core_size.y() + i + 1
                  + ranges::distance(axi_ss_geo::m_me_range)
                  + ranges::distance(axi_ss_geo::m_dma_range)
                  + ranges::distance(axi_ss_geo::m_tile_ctrl_range)
                  + ranges::distance(axi_ss_geo::m_fifo_range) };
           },
           axi_ss_geo::s_east_range,
References c, and i.
display_border() [1/2]
template<typename AXIStreamGeography > template<typename FG , typename FL , typename... EnumRanges> auto trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display_border (const std::string_view & node_attribute, FG && global_coordinate_function, FL && local_coordinate_function, EnumRanges &&... enum_ranges) const inline
Display a border of the AXI stream switch.
Definition at line 520 of file axi_stream_switch.hpp.
{
    std::string out;
    // Index each connection displayed in order
    auto i = 0;
    boost::hana::for_each(boost::hana::make_tuple(enum_ranges...),
      [&] (auto&& r) {
        for (auto p : r) {
          auto [x, y] = local_coordinate_function(i);
          out += (boost::format { R"(
    \coordinate(%3%) at %2%;
    \node[%1%] at %2% {%4%};)" }
            % node_attribute
            % global_coordinate_function(x, y)
            // Make a node name from enum name prefixed with master/slave statu7s
            % latex::context::clean_node(magic_enum::enum_name(p),
                                         is_axi_master(p) ? "M" : "S")
            // Use the enum name as the port name to display
            % magic_enum::enum_name(p)).str();
          ++i;
References i.
display_border() [2/2]
template<typename AXIStreamGeography > template<typename FG , typename FL , typename... EnumRanges> auto trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display_border (const std::string_view & node_attribute, FG && global_coordinate_function, FL && local_coordinate_function, EnumRanges &&... enum_ranges) const inline
Display a border of the AXI stream switch.
Definition at line 520 of file axi_stream_switch.hpp.
{
    std::string out;
    // Index each connection displayed in order
    auto i = 0;
    boost::hana::for_each(boost::hana::make_tuple(enum_ranges...),
      [&] (auto&& r) {
        for (auto p : r) {
          auto [x, y] = local_coordinate_function(i);
          out += (boost::format { R"(
    \coordinate(%3%) at %2%;
    \node[%1%] at %2% {%4%};)" }
            % node_attribute
            % global_coordinate_function(x, y)
            // Make a node name from enum name prefixed with master/slave statu7s
            % latex::context::clean_node(magic_enum::enum_name(p),
                                         is_axi_master(p) ? "M" : "S")
            // Use the enum name as the port name to display
            % magic_enum::enum_name(p)).str();
          ++i;
References i.
display_routing_configuration() [1/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display_routing_configuration (latex::context & c) const inline
Display the internal switch connections with routing arrows perpendicular to the borders.
< To the left
< Downwards
< To the right
< Upwards
< To the left
< Downwards
< To the right
< Upwards
Definition at line 477 of file axi_stream_switch.hpp.
{
    for (const auto& [i, p] :  ranges::views::enumerate(input_ports)) {
      auto input_port = static_cast<spl>(i);
      auto rm = get_as_router_minion(p.get());
      for (auto output_port : rm->get_master_port_dests()) {
        auto input_port_name = magic_enum::enum_name(input_port);
        // Compute the angle of the starting arrow from the input
        auto input_angle = tikz_edge_angle(input_port_name,
                                           { { "east", 180 }, ///< To the left
                                             { "north", -90 }, ///< Downwards
                                             { "west", 0 }, ///< To the right
                                             { "dma", 90 }, ///< Upwards
                                             { "fifo", 90 },
                                             { "me", 90 },
                                             { "tile_ctrl", 90 },
                                             { "south", 90 } });
        auto output_port_name = magic_enum::enum_name(output_port);
        // Compute the angle of the ending arrow to the output
        auto output_angle = tikz_edge_angle(output_port_name,
                                            { { "east", 180 }, ///< To the left
                                              { "north", -90 }, ///< Downwards
                                              { "dma", 0 }, ///< To the right
                                              { "fifo", 0 },
                                              { "me", 0 },
                                              { "tile_ctrl", 0 },
                                              { "west", 0 },
                                              { "south", 90 } }); ///< Upwards
        // Use specific color for core emission or reception
        auto color = input_port_name.starts_with("me") ? "red"
          : output_port_name.starts_with("me") ? "teal"
          : input_port_name.starts_with("dma") ? "magenta"
          : output_port_name.starts_with("dma") ? "violet" : "blue";
        c.add((boost::format { R"(
    \draw[%5%] (node cs:name=S%1%)
       to [out=%2%, in=%4%] (node cs:name=M%3%);)" }
            % c.clean_node(input_port_name) % input_angle
            % c.clean_node(output_port_name) % output_angle
            % color).str());
      }
References c, color, i, and p.
display_routing_configuration() [2/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display_routing_configuration (latex::context & c) const inline
Display the internal switch connections with routing arrows perpendicular to the borders.
< To the left
< Downwards
< To the right
< Upwards
< To the left
< Downwards
< To the right
< Upwards
Definition at line 477 of file axi_stream_switch.hpp.
{
    for (const auto& [i, p] :  ranges::views::enumerate(input_ports)) {
      auto input_port = static_cast<spl>(i);
      auto rm = get_as_router_minion(p.get());
      for (auto output_port : rm->get_master_port_dests()) {
        auto input_port_name = magic_enum::enum_name(input_port);
        // Compute the angle of the starting arrow from the input
        auto input_angle = tikz_edge_angle(input_port_name,
                                           { { "east", 180 }, ///< To the left
                                             { "north", -90 }, ///< Downwards
                                             { "west", 0 }, ///< To the right
                                             { "dma", 90 }, ///< Upwards
                                             { "fifo", 90 },
                                             { "me", 90 },
                                             { "tile_ctrl", 90 },
                                             { "south", 90 } });
        auto output_port_name = magic_enum::enum_name(output_port);
        // Compute the angle of the ending arrow to the output
        auto output_angle = tikz_edge_angle(output_port_name,
                                            { { "east", 180 }, ///< To the left
                                              { "north", -90 }, ///< Downwards
                                              { "dma", 0 }, ///< To the right
                                              { "fifo", 0 },
                                              { "me", 0 },
                                              { "tile_ctrl", 0 },
                                              { "west", 0 },
                                              { "south", 90 } }); ///< Upwards
        // Use specific color for core emission or reception
        auto color = input_port_name.starts_with("me") ? "red"
          : output_port_name.starts_with("me") ? "teal"
          : input_port_name.starts_with("dma") ? "magenta"
          : output_port_name.starts_with("dma") ? "violet" : "blue";
        c.add((boost::format { R"(
    \draw[%5%] (node cs:name=S%1%)
       to [out=%2%, in=%4%] (node cs:name=M%3%);)" }
            % c.clean_node(input_port_name) % input_angle
            % c.clean_node(output_port_name) % output_angle
            % color).str());
      }
References c, color, i, and p.
display_size() [1/2]
template<typename AXIStreamGeography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display_size () inline static
Compute the size of the graphics representation of the switch.
Definition at line 547 of file axi_stream_switch.hpp.
{
    // Combine the lengths of the most packed sides,
    // + 1/+ 2 to keep room for labels on each side
    return { 1 + ranges::distance(axi_ss_geo::s_me_range)
             + ranges::distance(axi_ss_geo::m_dma_range)
             + ranges::distance(axi_ss_geo::m_tile_ctrl_range)
             + ranges::distance(axi_ss_geo::m_fifo_range)
             + ranges::distance(axi_ss_geo::m_south_range)
             + ranges::distance(axi_ss_geo::s_south_range),
             2 + ranges::distance(axi_ss_geo::s_me_range)
             + ranges::distance(axi_ss_geo::s_dma_range)
             + ranges::distance(axi_ss_geo::s_tile_ctrl_range)
display_size() [2/2]
template<typename AXIStreamGeography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display_size () inline static
Compute the size of the graphics representation of the switch.
Definition at line 547 of file axi_stream_switch.hpp.
{
    // Combine the lengths of the most packed sides,
    // + 1/+ 2 to keep room for labels on each side
    return { 1 + ranges::distance(axi_ss_geo::s_me_range)
             + ranges::distance(axi_ss_geo::m_dma_range)
             + ranges::distance(axi_ss_geo::m_tile_ctrl_range)
             + ranges::distance(axi_ss_geo::m_fifo_range)
             + ranges::distance(axi_ss_geo::m_south_range)
             + ranges::distance(axi_ss_geo::s_south_range),
             2 + ranges::distance(axi_ss_geo::s_me_range)
             + ranges::distance(axi_ss_geo::s_dma_range)
             + ranges::distance(axi_ss_geo::s_tile_ctrl_range)
get_as_router_minion() [1/2]
template<typename AXIStreamGeography > static router_minion * trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::get_as_router_minion (communicator_port * rp) inline static
Get the router_minion behind a communicator_port.
Definition at line 227 of file axi_stream_switch.hpp.
{
#ifdef NDEBUG
    // No assert mode
    auto rm = static_cast<router_minion *>(rp);
#else
    // In mode with assertion, check this is really a router_minion
    auto rm = dynamic_cast<router_minion *>(rp);
    if (!rm) {
      throw ::trisycl::runtime_error {
        "This is not a routable switch port" };
    }
#endif
    return rm;
  }
get_as_router_minion() [2/2]
template<typename AXIStreamGeography > static router_minion * trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::get_as_router_minion (communicator_port * rp) inline static
Get the router_minion behind a communicator_port.
Definition at line 227 of file axi_stream_switch.hpp.
{
#ifdef NDEBUG
    // No assert mode
    auto rm = static_cast<router_minion *>(rp);
#else
    // In mode with assertion, check this is really a router_minion
    auto rm = dynamic_cast<router_minion *>(rp);
    if (!rm) {
      throw ::trisycl::runtime_error {
        "This is not a routable switch port" };
    }
#endif
    return rm;
  }
in_connection() [1/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::in_connection (spl sp) inline
Access the input connection behind an input port.
Parameters
[in] p is the input port number
Exceptions
trisycl::runtime_error if the port number is invalid
Definition at line 285 of file axi_stream_switch.hpp.
{
    using u_t = std::underlying_type_t<decltype(sp)>;
    auto port = static_cast<u_t>(sp);
    // \todo replace by std::ssize() in the future
    if (port >=  static_cast<std::ptrdiff_t>(std::size(input_ports)))
      throw ::trisycl::runtime_error {
        (boost::format {
          "in_connection: %1% is not a valid port number between 0 and %2%" }
           % port % (std::size(input_ports) - 1)).str() };
    return input_ports[port];
  }
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out_connection(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out_connection().
in_connection() [2/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::in_connection (spl sp) inline
Access the input connection behind an input port.
Parameters
[in] p is the input port number
Exceptions
trisycl::runtime_error if the port number is invalid
Definition at line 285 of file axi_stream_switch.hpp.
{
    using u_t = std::underlying_type_t<decltype(sp)>;
    auto port = static_cast<u_t>(sp);
    // \todo replace by std::ssize() in the future
    if (port >=  static_cast<std::ptrdiff_t>(std::size(input_ports)))
      throw ::trisycl::runtime_error {
        (boost::format {
          "in_connection: %1% is not a valid port number between 0 and %2%" }
           % port % (std::size(input_ports) - 1)).str() };
    return input_ports[port];
  }
input() [1/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input (spl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the slave_port_layout for the stream
Definition at line 373 of file axi_stream_switch.hpp.
                      {
    // No index validation required because of type safety
    return input_ports[::trisycl::detail::underlying_value(p)];
  }
References p, and trisycl::detail::underlying_value.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::input(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::input().
input() [2/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input (spl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the slave_port_layout for the stream
Definition at line 373 of file axi_stream_switch.hpp.
                      {
    // No index validation required because of type safety
    return input_ports[::trisycl::detail::underlying_value(p)];
  }
References p, and trisycl::detail::underlying_value.
out_connection() [1/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::out_connection (mpl mp) inline
Access the output connection behind an output port.
Parameters
[in] p is the output port number
Exceptions
trisycl::runtime_error if the port number is invalid
Definition at line 304 of file axi_stream_switch.hpp.
{
    using u_t = std::underlying_type_t<decltype(mp)>;
    auto port = static_cast<u_t>(mp);
    // \todo replace by std::ssize() in the future
    if (port >= static_cast<std::ptrdiff_t>(std::size(output_ports)))
      throw ::trisycl::runtime_error {
        (boost::format {
          "out_connection: %1% is not a valid port number between 0 and %2%" }
           % port % (std::size(output_ports) - 1)).str() };
    return output_ports[port];
  }
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in_connection(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in_connection().
out_connection() [2/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::out_connection (mpl mp) inline
Access the output connection behind an output port.
Parameters
[in] p is the output port number
Exceptions
trisycl::runtime_error if the port number is invalid
Definition at line 304 of file axi_stream_switch.hpp.
{
    using u_t = std::underlying_type_t<decltype(mp)>;
    auto port = static_cast<u_t>(mp);
    // \todo replace by std::ssize() in the future
    if (port >= static_cast<std::ptrdiff_t>(std::size(output_ports)))
      throw ::trisycl::runtime_error {
        (boost::format {
          "out_connection: %1% is not a valid port number between 0 and %2%" }
           % port % (std::size(output_ports) - 1)).str() };
    return output_ports[port];
  }
output() [1/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output (mpl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 383 of file axi_stream_switch.hpp.
                       {
    // No index validation required because of type safety
    return output_ports[::trisycl::detail::underlying_value(p)];
  }
References p, and trisycl::detail::underlying_value.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::output(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output().
output() [2/2]
template<typename AXIStreamGeography > auto & trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output (mpl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 383 of file axi_stream_switch.hpp.
                       {
    // No index validation required because of type safety
    return output_ports[::trisycl::detail::underlying_value(p)];
  }
References p, and trisycl::detail::underlying_value.
start() [1/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::start (int x, int y, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the tile infrastructure associated to the AIE device.
Definition at line 420 of file axi_stream_switch.hpp.
{
    x_coordinate = x;
    y_coordinate = y;
    // Add a router worker on all switch input
    for (auto& p : input_ports) {
      auto port_enum =
        magic_enum::enum_cast<spl>(std::distance(input_ports.begin(), &p));
#ifdef TRISYCL_DEBUG
      auto port_name = magic_enum::enum_name(port_enum.value());
#endif
      TRISYCL_DUMP_T("axi_stream_switch " << this
                     << " (" << x_coordinate << ',' << y_coordinate
                     << ") start initialize input: " << port_name);
      // If the port comes from the FIFO, use a FIFO-featured
      // router_minion instead
      if (ranges::find(axi_ss_geo::s_fifo_range, port_enum)
          != std::end(axi_ss_geo::s_fifo_range))
        /* A special AXI switch routing interface which provides a
           FIFO.  Since a router_minion has already some internal FIFO
           behavior, some deeper FIFO behavior can actually be
           implemented with a specific router_minion with a deeper
           FIFO internally, to avoid having 2 active components, the
           FIFO + the router_minion */
        p = std::make_shared<router_minion>(*this,
                                            fiber_executor,
                                            axi_ss_geo::fifo_depth);
      else
        p = std::make_shared<router_minion>(*this, fiber_executor);
    }
    // Since the FIFO behavior is actually implemented with a
    // router_minion with a deeper FIFO internally, the "input" of the
    // "FIFO" can be just directly connected to this specific
    // router_minion
    for (auto [o, i] : ranges::views::zip(axi_ss_geo::m_fifo_range,
                                          axi_ss_geo::s_fifo_range))
      output(o) = input(i);
  }
References i, p, TRISYCL_DUMP_T, x, and trisycl::y.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::start(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure().
start() [2/2]
template<typename AXIStreamGeography > void trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::start (int x, int y, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the tile infrastructure associated to the AIE device.
Definition at line 420 of file axi_stream_switch.hpp.
{
    x_coordinate = x;
    y_coordinate = y;
    // Add a router worker on all switch input
    for (auto& p : input_ports) {
      auto port_enum =
        magic_enum::enum_cast<spl>(std::distance(input_ports.begin(), &p));
#ifdef TRISYCL_DEBUG
      auto port_name = magic_enum::enum_name(port_enum.value());
#endif
      TRISYCL_DUMP_T("axi_stream_switch " << this
                     << " (" << x_coordinate << ',' << y_coordinate
                     << ") start initialize input: " << port_name);
      // If the port comes from the FIFO, use a FIFO-featured
      // router_minion instead
      if (ranges::find(axi_ss_geo::s_fifo_range, port_enum)
          != std::end(axi_ss_geo::s_fifo_range))
        /* A special AXI switch routing interface which provides a
           FIFO.  Since a router_minion has already some internal FIFO
           behavior, some deeper FIFO behavior can actually be
           implemented with a specific router_minion with a deeper
           FIFO internally, to avoid having 2 active components, the
           FIFO + the router_minion */
        p = std::make_shared<router_minion>(*this,
                                            fiber_executor,
                                            axi_ss_geo::fifo_depth);
      else
        p = std::make_shared<router_minion>(*this, fiber_executor);
    }
    // Since the FIFO behavior is actually implemented with a
    // router_minion with a deeper FIFO internally, the "input" of the
    // "FIFO" can be just directly connected to this specific
    // router_minion
    for (auto [o, i] : ranges::views::zip(axi_ss_geo::m_fifo_range,
                                          axi_ss_geo::s_fifo_range))
      output(o) = input(i);
  }
References i, p, TRISYCL_DUMP_T, x, and trisycl::y.
tikz_edge_angle() [1/2]
template<typename AXIStreamGeography > int trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::tikz_edge_angle (const std::string_view & port_name, const std::initializer_list< std::tuple< std::string_view, int > > & desc) const inline
Compute the edge angle for a port name according a list of description associating a port name prefix and an associated angle in degree.
Definition at line 464 of file axi_stream_switch.hpp.
{
    for (auto& [prefix, angle] : desc)
      if (port_name.starts_with(prefix))
        return angle;
    assert(0 && "Unknown port name");
    return 0;
  }
tikz_edge_angle() [2/2]
template<typename AXIStreamGeography > int trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::tikz_edge_angle (const std::string_view & port_name, const std::initializer_list< std::tuple< std::string_view, int > > & desc) const inline
Compute the edge angle for a port name according a list of description associating a port name prefix and an associated angle in degree.
Definition at line 464 of file axi_stream_switch.hpp.
{
    for (auto& [prefix, angle] : desc)
      if (port_name.starts_with(prefix))
        return angle;
    assert(0 && "Unknown port name");
    return 0;
  }
Member Data Documentation
input_ports
template<typename AXIStreamGeography > std::array< std::shared_ptr< communicator_port >, axi_ss_geo::nb_slave_port > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input_ports
The input ports used to send information to the switch.
Use a shared pointer to represent the interconnect between switches in a shortcut way.
Definition at line 352 of file axi_stream_switch.hpp.
output_ports
template<typename AXIStreamGeography > std::array< std::shared_ptr< communicator_port >, axi_ss_geo::nb_master_port > trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output_ports
The input ports used to send information to the switch.
Use a shared pointer to represent the interconnect between switches in a shortcut way.
Definition at line 360 of file axi_stream_switch.hpp.
stream_latency
template<typename AXIStreamGeography > static constexpr auto trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::stream_latency = 4 static constexpr
Definition at line 335 of file axi_stream_switch.hpp.
translate_port
template<typename AXIStreamGeography > static auto trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::translate_port inline static
Initial value:
= [] (int user_port,
                                          auto physical_port_min,
                                          auto physical_port_max,
                                          const auto& error_message) {
    auto port_min = static_cast<int>(physical_port_min);
    auto port_max = static_cast<int>(physical_port_max);
    auto last_user_port = port_max - port_min;
    if (user_port < 0 || user_port > last_user_port)
      throw ::trisycl::runtime_error {
        (boost::format {
          "%1%: %2% is not a valid port number between 0 and %3%" }
           % error_message % user_port % last_user_port).str() };
    return static_cast<decltype(physical_port_min)>(port_min + user_port);
  }
Validate the user port number and translate it to the physical port number.
Parameters
[in] user_port is the logical port number, starting to 0
[in] physical_port_min is the physical lower port number to map to
[in] physical_port_max is the physical higher port number to map to
Exceptions
trisycl::runtime_error if the port number is invalid
Returns
the physical port number in the switch corresponding to the logical port
Todo:
This makes sense only for core tile
Parameters
[in] user_port is the logical port number, starting to 0
[in] physical_port_min is the physical lower port number to map to
[in] physical_port_max is the physical higher port number to map to
Exceptions
trisycl::runtime_error if the port number is invalid
Returns
the physical port number in the switch corresponding to the logical port
Todo:
This makes sense only for core tile
Definition at line 260 of file axi_stream_switch.hpp.
x_coordinate
template<typename AXIStreamGeography > int trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::x_coordinate
Keep the horizontal coordinate for debug purpose.
Definition at line 363 of file axi_stream_switch.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::connect_to(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::read(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::router_minion(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::write().
y_coordinate
template<typename AXIStreamGeography > int trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::y_coordinate
Keep the vertical coordinate for debug purpose.
Definition at line 366 of file axi_stream_switch.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::connect_to(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::read(), trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::router_minion(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::write().
trisycl::vendor::xilinx::acap::aie::cascade_stream
struct trisycl::vendor::xilinx::acap::aie::cascade_stream
template<typename Geography>
struct trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >
Implementation of the cascade stream infrastructure between AI Engine tiles.
Based on Math Engine (ME) Architecture Specification, Revision v2.01
March 2019
3.5.4 Data Movement using Cascade Streams, p. 93
2.14 Device-level Floorplanning Guidelines, 2.14.2 Array Edges, p. 69
4.4 ME Core Interfaces, 4.4.4 Cascade Stream Interface, p. 120 explains there is a FIFO depth of 4
5.9.3.6 Cascade Streams: explains that there are only blocking accesses
Direct stream interface: One cascade stream in, one cascade stream out (384-bits)
Todo:
Remove this global infrastructure and distribute it on the tile_infrastructure itself
Based on Math Engine (ME) Architecture Specification, Revision v2.01
March 2019
3.5.4 Data Movement using Cascade Streams, p. 93
2.14 Device-level Floorplanning Guidelines, 2.14.2 Array Edges, p. 69
4.4 ME Core Interfaces, 4.4.4 Cascade Stream Interface, p. 120 explains there is a FIFO depth of 4
5.9.3.6 Cascade Streams: explains that there are only blocking accesses
Direct stream interface: One cascade stream in, one cascade stream out (384-bits)
Todo:
Remove this global infrastructure and distribute it on the tile_infrastructure itself
Definition at line 46 of file cascade_stream.hpp.
Public Types
using geo = Geography
using geo = Geography
Public Member Functions
template<typename T >
auto get_cascade_stream_in (int x, int y) const
Get a blocking read accessor to the cascade stream input.
template<typename T >
auto get_cascade_stream_out (int x, int y) const
Get a blocking write accessor to the cascade stream output.
template<typename T >
auto get_cascade_stream_in (int x, int y) const
Get a blocking read accessor to the cascade stream input.
template<typename T >
auto get_cascade_stream_out (int x, int y) const
Get a blocking write accessor to the cascade stream output.
Public Attributes
::trisycl::sycl_2_2::static_pipe< int, 4 > cascade_stream_pipes [geo::x_size *geo::y_size+1]
The pipes for the cascade streams, with 1 spare pipe on each side of the PE string.
Member Typedef Documentation
geo [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::geo = Geography
Definition at line 47 of file cascade_stream.hpp.
geo [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::geo = Geography
Definition at line 47 of file cascade_stream.hpp.
Member Function Documentation
get_cascade_stream_in() [1/2]
template<typename Geography > template<typename T > auto trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::get_cascade_stream_in (int x, int y) const inline
Get a blocking read accessor to the cascade stream input.
Parameters
T is the data type used to read from the cascade stream pipe
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 76 of file cascade_stream.hpp.
{
    return cascade_stream_pipes[geo::cascade_linear_id(x, y)]
      .template get_access<access::mode::read,
                           access::target::blocking_pipe>();
  }
References trisycl::access::blocking_pipe, trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::cascade_stream_pipes, trisycl::access::read, x, and trisycl::y.
get_cascade_stream_in() [2/2]
template<typename Geography > template<typename T > auto trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::get_cascade_stream_in (int x, int y) const inline
Get a blocking read accessor to the cascade stream input.
Parameters
T is the data type used to read from the cascade stream pipe
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 76 of file cascade_stream.hpp.
{
    return cascade_stream_pipes[geo::cascade_linear_id(x, y)]
      .template get_access<access::mode::read,
                           access::target::blocking_pipe>();
  }
References trisycl::access::blocking_pipe, trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::cascade_stream_pipes, trisycl::access::read, x, and trisycl::y.
get_cascade_stream_out() [1/2]
template<typename Geography > template<typename T > auto trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::get_cascade_stream_out (int x, int y) const inline
Get a blocking write accessor to the cascade stream output.
Parameters
T is the data type used to write to the cascade stream pipe
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 93 of file cascade_stream.hpp.
{
    // The output is connected to the down-stream neighbour of the cascade
    return cascade_stream_pipes[geo::cascade_linear_id(x, y) + 1]
      .template get_access<access::mode::write,
                           access::target::blocking_pipe>();
  }
References trisycl::access::blocking_pipe, trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::cascade_stream_pipes, trisycl::access::write, x, and trisycl::y.
get_cascade_stream_out() [2/2]
template<typename Geography > template<typename T > auto trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::get_cascade_stream_out (int x, int y) const inline
Get a blocking write accessor to the cascade stream output.
Parameters
T is the data type used to write to the cascade stream pipe
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 93 of file cascade_stream.hpp.
{
    // The output is connected to the down-stream neighbour of the cascade
    return cascade_stream_pipes[geo::cascade_linear_id(x, y) + 1]
      .template get_access<access::mode::write,
                           access::target::blocking_pipe>();
  }
References trisycl::access::blocking_pipe, trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::cascade_stream_pipes, trisycl::access::write, x, and trisycl::y.
Member Data Documentation
cascade_stream_pipes
template<typename Geography > trisycl::sycl_2_2::static_pipe< int, 4 > trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::cascade_stream_pipes
The pipes for the cascade streams, with 1 spare pipe on each side of the PE string.
Todo:
Use a data type with 384 bits
Todo:
Use a data type with 384 bits
Definition at line 54 of file cascade_stream.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::get_cascade_stream_in(), and trisycl::vendor::xilinx::acap::aie::cascade_stream< Geography >::get_cascade_stream_out().
trisycl::vendor::xilinx::acap::aie::axi_packet
class trisycl::vendor::xilinx::acap::aie::axi_packet
Packet moving in AIE network-on-chip (NoC)
Definition at line 31 of file connection.hpp.
Public Types
using value_type = std::uint32_t
Payload data type.
using value_type = std::uint32_t
Payload data type.
Public Member Functions
axi_packet (const value_type &data)
Implicit constructor from a data value.
axi_packet (shutdown_t)
Construct a shutdown request packet from axi_packet::shutdown.
axi_packet ()=default
axi_packet (const value_type &data)
Implicit constructor from a data value.
axi_packet (shutdown_t)
Construct a shutdown request packet from axi_packet::shutdown.
axi_packet ()=default
Public Attributes
value_type data
Network payload.
bool tlast = false
Signal end of packet stream.
bool shutdown_request = false
Signal a router shutdown.
Static Public Attributes
static const shutdown_t shutdown
Marker value used to construct a packet asking for shutdown.
Member Typedef Documentation
value_type [1/2]
using trisycl::vendor::xilinx::acap::aie::axi_packet::value_type = std::uint32_t
Payload data type.
Definition at line 38 of file connection.hpp.
value_type [2/2]
using trisycl::vendor::xilinx::acap::aie::axi_packet::value_type = std::uint32_t
Payload data type.
Definition at line 38 of file connection.hpp.
Constructor & Destructor Documentation
axi_packet() [1/6]
trisycl::vendor::xilinx::acap::aie::axi_packet::axi_packet (const value_type & data) inline
Implicit constructor from a data value.
Definition at line 53 of file connection.hpp.
: data { data } {}
axi_packet() [2/6]
trisycl::vendor::xilinx::acap::aie::axi_packet::axi_packet (shutdown_t) inline
Construct a shutdown request packet from axi_packet::shutdown.
Definition at line 56 of file connection.hpp.
: shutdown_request { true } {}
axi_packet() [3/6]
trisycl::vendor::xilinx::acap::aie::axi_packet::axi_packet () default
axi_packet() [4/6]
trisycl::vendor::xilinx::acap::aie::axi_packet::axi_packet (const value_type & data) inline
Implicit constructor from a data value.
Definition at line 53 of file connection.hpp.
: data { data } {}
axi_packet() [5/6]
trisycl::vendor::xilinx::acap::aie::axi_packet::axi_packet (shutdown_t) inline
Construct a shutdown request packet from axi_packet::shutdown.
Definition at line 56 of file connection.hpp.
: shutdown_request { true } {}
axi_packet() [6/6]
trisycl::vendor::xilinx::acap::aie::axi_packet::axi_packet () default
Member Data Documentation
data
value_type trisycl::vendor::xilinx::acap::aie::axi_packet::data
Network payload.
Definition at line 44 of file connection.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::write(), and trisycl::vendor::xilinx::acap::aie::port_receiver< AXIStreamSwich >::write().
shutdown
static const shutdown_t trisycl::vendor::xilinx::acap::aie::axi_packet::shutdown static
Marker value used to construct a packet asking for shutdown.
Definition at line 41 of file connection.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::router_minion::~router_minion().
shutdown_request
bool trisycl::vendor::xilinx::acap::aie::axi_packet::shutdown_request = false
Signal a router shutdown.
Definition at line 50 of file connection.hpp.
tlast
bool trisycl::vendor::xilinx::acap::aie::axi_packet::tlast = false
Signal end of packet stream.
Definition at line 47 of file connection.hpp.
trisycl::vendor::xilinx::acap::aie::dma_dsl
class trisycl::vendor::xilinx::acap::aie::dma_dsl
template<typename Tile, typename DMA, typename LockRef = bool>
class trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >
Implement a small DSL to chain DMA & locking operations like allowed by the hardware.
Parameters
[in] Tile is the type of tile to keep a reference on it
[in] DMA is the type of the DMA involved in the operation
[in] LockRef is the type of the reference to the lock once a lock() operation is involved. Otherwise just use a bool as a dummy type internally.
Definition at line 46 of file dma.hpp.
Public Member Functions
dma_dsl (Tile &t, DMA &d)
Keep track of operation with only DMA involved.
dma_dsl (Tile &t, DMA &d, LockRef l)
Keep track of operation with DMA and lock involved.
auto lock (int l)
Select a lock for the following operations.
template<typename Cmd >
auto & receive (Cmd &&cmd)
Enqueue a DMA receive command.
template<typename Cmd >
auto & send (Cmd &&cmd)
Enqueue a DMA transfer command.
auto & wait ()
Wait for the transfers to complete.
dma_dsl (Tile &t, DMA &d)
Keep track of operation with only DMA involved.
dma_dsl (Tile &t, DMA &d, LockRef l)
Keep track of operation with DMA and lock involved.
auto lock (int l)
Select a lock for the following operations.
template<typename Cmd >
auto & receive (Cmd &&cmd)
Enqueue a DMA receive command.
template<typename Cmd >
auto & send (Cmd &&cmd)
Enqueue a DMA transfer command.
auto & wait ()
Wait for the transfers to complete.
Private Attributes
Tile & tile
Keep track of the tile involved in the operation chain.
DMA & dma
Keep track of the DMA involved in the operation chain.
LockRef lck
Keep track of the current lock involved in the operation chain if any.
Constructor & Destructor Documentation
dma_dsl() [1/4]
template<typename Tile , typename DMA , typename LockRef = bool> trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::dma_dsl (Tile & t, DMA & d) inline
Keep track of operation with only DMA involved.
Definition at line 59 of file dma.hpp.
      : tile { t }
      , dma { d } {}
dma_dsl() [2/4]
template<typename Tile , typename DMA , typename LockRef = bool> trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::dma_dsl (Tile & t, DMA & d, LockRef l) inline
Keep track of operation with DMA and lock involved.
Definition at line 64 of file dma.hpp.
      : tile { t }
      , dma { d }
      , lck { l } {}
dma_dsl() [3/4]
template<typename Tile , typename DMA , typename LockRef = bool> trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::dma_dsl (Tile & t, DMA & d) inline
Keep track of operation with only DMA involved.
Definition at line 59 of file dma.hpp.
      : tile { t }
      , dma { d } {}
dma_dsl() [4/4]
template<typename Tile , typename DMA , typename LockRef = bool> trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::dma_dsl (Tile & t, DMA & d, LockRef l) inline
Keep track of operation with DMA and lock involved.
Definition at line 64 of file dma.hpp.
      : tile { t }
      , dma { d }
      , lck { l } {}
Member Function Documentation
lock() [1/2]
template<typename Tile , typename DMA , typename LockRef = bool> auto trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::lock (int l) inline
Select a lock for the following operations.
Definition at line 70 of file dma.hpp.
                   {
    auto& lock_ref = tile.mem().lock(l);
    return dma_dsl<Tile, DMA, decltype(lock_ref)> { tile, dma, lock_ref };
  }
References trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::dma, trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), and trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::tile.
lock() [2/2]
template<typename Tile , typename DMA , typename LockRef = bool> auto trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::lock (int l) inline
Select a lock for the following operations.
Definition at line 70 of file dma.hpp.
                   {
    auto& lock_ref = tile.mem().lock(l);
    return dma_dsl<Tile, DMA, decltype(lock_ref)> { tile, dma, lock_ref };
  }
References trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::dma, trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), and trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::tile.
receive() [1/2]
template<typename Tile , typename DMA , typename LockRef = bool> template<typename Cmd > auto & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::receive (Cmd && cmd) inline
Enqueue a DMA receive command.
Definition at line 76 of file dma.hpp.
{
    dma.receive(std::forward<Cmd>(cmd));
    // To be able to chain another DMA operation on it
    return *this;
  }
receive() [2/2]
template<typename Tile , typename DMA , typename LockRef = bool> template<typename Cmd > auto & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::receive (Cmd && cmd) inline
Enqueue a DMA receive command.
Definition at line 76 of file dma.hpp.
{
    dma.receive(std::forward<Cmd>(cmd));
    // To be able to chain another DMA operation on it
    return *this;
  }
send() [1/2]
template<typename Tile , typename DMA , typename LockRef = bool> template<typename Cmd > auto & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::send (Cmd && cmd) inline
Enqueue a DMA transfer command.
Definition at line 83 of file dma.hpp.
{
    dma.send(std::forward<Cmd>(cmd));
    // To be able to chain another DMA operation on it
    return *this;
  }
send() [2/2]
template<typename Tile , typename DMA , typename LockRef = bool> template<typename Cmd > auto & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::send (Cmd && cmd) inline
Enqueue a DMA transfer command.
Definition at line 83 of file dma.hpp.
{
    dma.send(std::forward<Cmd>(cmd));
    // To be able to chain another DMA operation on it
    return *this;
  }
wait() [1/2]
template<typename Tile , typename DMA , typename LockRef = bool> auto & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::wait () inline
Wait for the transfers to complete.
The API assumes that the program is written in such a way that at some point the queue will be empty so there is no continuous DMA command enqueuing for example.
Definition at line 94 of file dma.hpp.
               {
    dma.wait();
    // To be able to chain another DMA operation on it
    return *this;
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::wait().
wait() [2/2]
template<typename Tile , typename DMA , typename LockRef = bool> auto & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::wait () inline
Wait for the transfers to complete.
The API assumes that the program is written in such a way that at some point the queue will be empty so there is no continuous DMA command enqueuing for example.
Definition at line 94 of file dma.hpp.
               {
    dma.wait();
    // To be able to chain another DMA operation on it
    return *this;
  }
References trisycl::vendor::xilinx::acap::aie::dma< AXIStreamSwitch, SpecializedDMA >::wait().
Member Data Documentation
dma
template<typename Tile , typename DMA , typename LockRef = bool> DMA & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::dma private
Keep track of the DMA involved in the operation chain.
Definition at line 51 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::lock().
lck
template<typename Tile , typename DMA , typename LockRef = bool> LockRef trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::lck private
Keep track of the current lock involved in the operation chain if any.
Definition at line 55 of file dma.hpp.
tile
template<typename Tile , typename DMA , typename LockRef = bool> Tile & trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::tile private
Keep track of the tile involved in the operation chain.
Definition at line 48 of file dma.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::lock().
trisycl::vendor::xilinx::acap::aie::geography
struct trisycl::vendor::xilinx::acap::aie::geography
template<typename Layout>
struct trisycl::vendor::xilinx::acap::aie::geography< Layout >
Some geographic information about the AI Engine array.
Parameters
Layout is a class describing the basic layout of the CGRA, setting for example the x & y size
Definition at line 33 of file geography.hpp.
Public Types
using layout = Layout
Keep the layout used for this CGRA.
using layout = Layout
Keep the layout used for this CGRA.
Static Public Member Functions
template<template< int X, int Y > typename Tileable>
static auto generate_tiles ()
Generate a tuple by tiling the Tileable object onto the CGRA geometry.
static auto constexpr linear_id (int x, int y)
Compute the linearized coordinate of a tile.
static auto constexpr linear_x (int linear_id)
Compute the horizontal coordinate of a tile from linear id.
static auto constexpr linear_y (int linear_id)
Compute the vertical coordinate of a tile from a linear id.
static bool constexpr is_x_valid (int x)
Test if an horizontal coordinate is valid.
static void validate_x (int x)
Validate an horizontal coordinate.
static bool constexpr is_y_valid (int y)
Test if a vertical coordinate is valid.
static void validate_y (int y)
Validate a vertical coordinate.
static bool constexpr is_x_y_valid (int x, int y)
Test if horizontal and vertical coordinates are valid.
static void validate_x_y (int x, int y)
Validate the horizontal and vertical coordinates.
static bool constexpr is_west_column (int x)
Test if a tile is in the Western column.
static bool constexpr is_east_column (int x)
Test if a tile is in the Eastern column.
static bool constexpr is_south_row (int y)
Test if a tile is in the Southern row.
static bool constexpr is_north_row (int y)
Test if a tile is in the Northern row.
static bool constexpr is_cascade_start (int x, int y)
Test if a tile owns the start of the cascade_stream.
static bool constexpr is_cascade_end (int x, int y)
Test if a tile owns the end of the cascade_stream.
static auto constexpr cascade_linear_id (int x, int y)
Compute the linearized coordinate of a tile along the cascade stream.
static auto constexpr cascade_linear_x (int linear_id)
Compute the horizontal coordinate of a tile from a cascade linear id.
static auto constexpr cascade_linear_y (int linear_id)
Compute the vertical coordinate of a tile from a cascade linear id.
static bool constexpr is_valid_memory_module_offset (int dx, int dy)
Test if a memory module coordinate offset is plausible.
static bool constexpr is_memory_module (int x, int y, int dx, int dy)
Test if a memory module exists and is connected to a tile.
static auto constexpr memory_module_dx_coordinate (int y, int dx)
Compute the memory module x coordinate delta from its tile.
static auto constexpr memory_module_linear_id (int x, int y, int dx, int dy)
Compute the linear id of a memory module attached to a tile.
template<template< int X, int Y > typename Tileable>
static auto generate_tiles ()
Generate a tuple by tiling the Tileable object onto the CGRA geometry.
static auto constexpr linear_id (int x, int y)
Compute the linearized coordinate of a tile.
static auto constexpr linear_x (int linear_id)
Compute the horizontal coordinate of a tile from linear id.
static auto constexpr linear_y (int linear_id)
Compute the vertical coordinate of a tile from a linear id.
static bool constexpr is_x_valid (int x)
Test if an horizontal coordinate is valid.
static void validate_x (int x)
Validate an horizontal coordinate.
static bool constexpr is_y_valid (int y)
Test if a vertical coordinate is valid.
static void validate_y (int y)
Validate a vertical coordinate.
static bool constexpr is_x_y_valid (int x, int y)
Test if horizontal and vertical coordinates are valid.
static void validate_x_y (int x, int y)
Validate the horizontal and vertical coordinates.
static bool constexpr is_west_column (int x)
Test if a tile is in the Western column.
static bool constexpr is_east_column (int x)
Test if a tile is in the Eastern column.
static bool constexpr is_south_row (int y)
Test if a tile is in the Southern row.
static bool constexpr is_north_row (int y)
Test if a tile is in the Northern row.
static bool constexpr is_cascade_start (int x, int y)
Test if a tile owns the start of the cascade_stream.
static bool constexpr is_cascade_end (int x, int y)
Test if a tile owns the end of the cascade_stream.
static auto constexpr cascade_linear_id (int x, int y)
Compute the linearized coordinate of a tile along the cascade stream.
static auto constexpr cascade_linear_x (int linear_id)
Compute the horizontal coordinate of a tile from a cascade linear id.
static auto constexpr cascade_linear_y (int linear_id)
Compute the vertical coordinate of a tile from a cascade linear id.
static bool constexpr is_valid_memory_module_offset (int dx, int dy)
Test if a memory module coordinate offset is plausible.
static bool constexpr is_memory_module (int x, int y, int dx, int dy)
Test if a memory module exists and is connected to a tile.
static auto constexpr memory_module_dx_coordinate (int y, int dx)
Compute the memory module x coordinate delta from its tile.
static auto constexpr memory_module_linear_id (int x, int y, int dx, int dy)
Compute the linear id of a memory module attached to a tile.
Static Public Attributes
static auto constexpr x_min = 0
Minimum horizontal coordinate.
static auto constexpr y_min = 0
Minimum vertical coordinate.
static auto constexpr x_size = layout::x_max + 1
Number of tile horizontally in the CGRA.
static auto constexpr y_size = layout::y_max + 1
Number of tile vertically in the CGRA.
static auto constexpr size = x_size*y_size
Total number of tiles in the CGRA.
static auto constexpr tile_coordinates
A tuple with the coordinate tuples of all the tiles inside the CGRA geometry.
Member Typedef Documentation
layout [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::geography< Layout >::layout = Layout
Keep the layout used for this CGRA.
Definition at line 35 of file geography.hpp.
layout [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::geography< Layout >::layout = Layout
Keep the layout used for this CGRA.
Definition at line 35 of file geography.hpp.
Member Function Documentation
cascade_linear_id() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_id (int x, int y) inline static constexpr
Compute the linearized coordinate of a tile along the cascade stream.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 256 of file geography.hpp.
{
    return x_size*y + ((y & 1) ? layout::x_max - x : x);
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size, and trisycl::y.
cascade_linear_id() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_id (int x, int y) inline static constexpr
Compute the linearized coordinate of a tile along the cascade stream.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 256 of file geography.hpp.
{
    return x_size*y + ((y & 1) ? layout::x_max - x : x);
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size, and trisycl::y.
cascade_linear_x() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_x (int linear_id) inline static constexpr
Compute the horizontal coordinate of a tile from a cascade linear id.
Parameters
[in] linear_id is a linear id along the cascade stream
Definition at line 266 of file geography.hpp.
{
    auto x = linear_x(linear_id);
    // According to the row parity, symmetrize the x coordinate
    return (cascade_linear_y(linear_id) & 1) ? layout::x_max - x : x;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_y(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_x(), and x.
cascade_linear_x() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_x (int linear_id) inline static constexpr
Compute the horizontal coordinate of a tile from a cascade linear id.
Parameters
[in] linear_id is a linear id along the cascade stream
Definition at line 266 of file geography.hpp.
{
    auto x = linear_x(linear_id);
    // According to the row parity, symmetrize the x coordinate
    return (cascade_linear_y(linear_id) & 1) ? layout::x_max - x : x;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_y(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_x(), and x.
cascade_linear_y() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_y (int linear_id) inline static constexpr
Compute the vertical coordinate of a tile from a cascade linear id.
Parameters
[in] linear_id is a linear id along the cascade stream
Definition at line 278 of file geography.hpp.
{
    // Same as the linear id, actually
    return linear_y(linear_id);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_y().
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_x().
cascade_linear_y() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_y (int linear_id) inline static constexpr
Compute the vertical coordinate of a tile from a cascade linear id.
Parameters
[in] linear_id is a linear id along the cascade stream
Definition at line 278 of file geography.hpp.
{
    // Same as the linear id, actually
    return linear_y(linear_id);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_y().
generate_tiles() [1/2]
template<typename Layout > template<template< int X, int Y > typename Tileable> static auto trisycl::vendor::xilinx::acap::aie::geography< Layout >::generate_tiles () inline static
Generate a tuple by tiling the Tileable object onto the CGRA geometry.
Parameters
Tileable is the type to tile according to coordinate X and Y
Definition at line 69 of file geography.hpp.
{
    return boost::hana::transform(
        tile_coordinates
      , [] (auto coord) {
          return Tileable<boost::hana::at_c<1>(coord),
                          boost::hana::at_c<0>(coord)> {};
        }
                                  );
  }
References coord, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::tile_coordinates.
generate_tiles() [2/2]
template<typename Layout > template<template< int X, int Y > typename Tileable> static auto trisycl::vendor::xilinx::acap::aie::geography< Layout >::generate_tiles () inline static
Generate a tuple by tiling the Tileable object onto the CGRA geometry.
Parameters
Tileable is the type to tile according to coordinate X and Y
Definition at line 69 of file geography.hpp.
{
    return boost::hana::transform(
        tile_coordinates
      , [] (auto coord) {
          return Tileable<boost::hana::at_c<1>(coord),
                          boost::hana::at_c<0>(coord)> {};
        }
                                  );
  }
References coord, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::tile_coordinates.
is_cascade_end() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_cascade_end (int x, int y) inline static constexpr
Test if a tile owns the end of the cascade_stream.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 243 of file geography.hpp.
{
    // The x position depends on the parity of the last line
    return x == ((y & 1) ? x_min : layout::x_max) && y == layout::y_max;
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min, and trisycl::y.
is_cascade_end() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_cascade_end (int x, int y) inline static constexpr
Test if a tile owns the end of the cascade_stream.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 243 of file geography.hpp.
{
    // The x position depends on the parity of the last line
    return x == ((y & 1) ? x_min : layout::x_max) && y == layout::y_max;
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min, and trisycl::y.
is_cascade_start() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_cascade_start (int x, int y) inline static constexpr
Test if a tile owns the start of the cascade_stream.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 232 of file geography.hpp.
{
    return x == x_min && y == y_min;
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min, trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
is_cascade_start() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_cascade_start (int x, int y) inline static constexpr
Test if a tile owns the start of the cascade_stream.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 232 of file geography.hpp.
{
    return x == x_min && y == y_min;
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min, trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
is_east_column() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_east_column (int x) inline static constexpr
Test if a tile is in the Eastern column.
Parameters
[in] x is the horizontal tile coordinate
Definition at line 203 of file geography.hpp.
{
    return x == layout::x_max;
  }
References x.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device().
is_east_column() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_east_column (int x) inline static constexpr
Test if a tile is in the Eastern column.
Parameters
[in] x is the horizontal tile coordinate
Definition at line 203 of file geography.hpp.
{
    return x == layout::x_max;
  }
References x.
is_memory_module() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_memory_module (int x, int y, int dx, int dy) inline static constexpr
Test if a memory module exists and is connected to a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 312 of file geography.hpp.
{
    if (!is_valid_memory_module_offset(dx, dy))
      return false;
    if (y == y_min && dy == -1)
      // No memory module on the South of the first (Southern) line
      return false;
    else if (y == layout::y_max && dy == 1)
      // No memory module on the North of the last (Northern) line
      return false;
    else if (x == x_min && !(y & 1) && (dx == -1))
      // No memory module on the West of the first (Western) column on
      // even lines
      return false;
    else if (x == layout::x_max && (y & 1) && (dx == 1))
      // No memory module on the East of the last (Eastern) column on
      // odd lines
      return false;
    else return true;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_valid_memory_module_offset(), x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min, trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
is_memory_module() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_memory_module (int x, int y, int dx, int dy) inline static constexpr
Test if a memory module exists and is connected to a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 312 of file geography.hpp.
{
    if (!is_valid_memory_module_offset(dx, dy))
      return false;
    if (y == y_min && dy == -1)
      // No memory module on the South of the first (Southern) line
      return false;
    else if (y == layout::y_max && dy == 1)
      // No memory module on the North of the last (Northern) line
      return false;
    else if (x == x_min && !(y & 1) && (dx == -1))
      // No memory module on the West of the first (Western) column on
      // even lines
      return false;
    else if (x == layout::x_max && (y & 1) && (dx == 1))
      // No memory module on the East of the last (Eastern) column on
      // odd lines
      return false;
    else return true;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_valid_memory_module_offset(), x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min, trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
is_north_row() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_north_row (int y) inline static constexpr
Test if a tile is in the Northern row.
Parameters
[in] y is the vertical tile coordinate
Definition at line 221 of file geography.hpp.
{
    return y == layout::y_max;
  }
References trisycl::y.
is_north_row() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_north_row (int y) inline static constexpr
Test if a tile is in the Northern row.
Parameters
[in] y is the vertical tile coordinate
Definition at line 221 of file geography.hpp.
{
    return y == layout::y_max;
  }
References trisycl::y.
is_south_row() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_south_row (int y) inline static constexpr
Test if a tile is in the Southern row.
Parameters
[in] y is the vertical tile coordinate
Definition at line 212 of file geography.hpp.
{
    return y == y_min;
  }
References trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
is_south_row() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_south_row (int y) inline static constexpr
Test if a tile is in the Southern row.
Parameters
[in] y is the vertical tile coordinate
Definition at line 212 of file geography.hpp.
{
    return y == y_min;
  }
References trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
is_valid_memory_module_offset() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_valid_memory_module_offset (int dx, int dy) inline static constexpr
Test if a memory module coordinate offset is plausible.
1 of the displacement is 0 and the other one is -1 or 1
Parameters
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 292 of file geography.hpp.
{
    if (dx == 0)
     // Cannot use std::abs() because it is not constexpr in C++17
      return dy == -1 || dy == 1;
    else if (dy == 0)
      return dx == -1 || dx == 1;
    else return false;
  }
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_memory_module().
is_valid_memory_module_offset() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_valid_memory_module_offset (int dx, int dy) inline static constexpr
Test if a memory module coordinate offset is plausible.
1 of the displacement is 0 and the other one is -1 or 1
Parameters
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 292 of file geography.hpp.
{
    if (dx == 0)
     // Cannot use std::abs() because it is not constexpr in C++17
      return dy == -1 || dy == 1;
    else if (dy == 0)
      return dx == -1 || dx == 1;
    else return false;
  }
is_west_column() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_west_column (int x) inline static constexpr
Test if a tile is in the Western column.
Parameters
[in] x is the horizontal tile coordinate
Definition at line 194 of file geography.hpp.
{
    return x == x_min;
  }
References x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device().
is_west_column() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_west_column (int x) inline static constexpr
Test if a tile is in the Western column.
Parameters
[in] x is the horizontal tile coordinate
Definition at line 194 of file geography.hpp.
{
    return x == x_min;
  }
References x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min.
is_x_valid() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_valid (int x) inline static constexpr
Test if an horizontal coordinate is valid.
Parameters
[in] x is the horizontal tile coordinate
Definition at line 113 of file geography.hpp.
{
    return x_min <= x && x <= layout::x_max;
  }
References x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_y_valid(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x().
is_x_valid() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_valid (int x) inline static constexpr
Test if an horizontal coordinate is valid.
Parameters
[in] x is the horizontal tile coordinate
Definition at line 113 of file geography.hpp.
{
    return x_min <= x && x <= layout::x_max;
  }
References x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min.
is_x_y_valid() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_y_valid (int x, int y) inline static constexpr
Test if horizontal and vertical coordinates are valid.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 169 of file geography.hpp.
{
    return is_x_valid(x) && is_y_valid(y);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_valid(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_y_valid(), x, and trisycl::y.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_neighborhood().
is_x_y_valid() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_y_valid (int x, int y) inline static constexpr
Test if horizontal and vertical coordinates are valid.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 169 of file geography.hpp.
{
    return is_x_valid(x) && is_y_valid(y);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_valid(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_y_valid(), x, and trisycl::y.
is_y_valid() [1/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_y_valid (int y) inline static constexpr
Test if a vertical coordinate is valid.
Parameters
[in] y is the vertical tile coordinate
Definition at line 140 of file geography.hpp.
{
    return y_min <= y && y <= layout::y_max;
  }
References trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_y_valid(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_y().
is_y_valid() [2/2]
template<typename Layout > static bool constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_y_valid (int y) inline static constexpr
Test if a vertical coordinate is valid.
Parameters
[in] y is the vertical tile coordinate
Definition at line 140 of file geography.hpp.
{
    return y_min <= y && y <= layout::y_max;
  }
References trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
linear_id() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id (int x, int y) inline static constexpr
Compute the linearized coordinate of a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 86 of file geography.hpp.
{
    return x + x_size*y;
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size, and trisycl::y.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_x(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_y(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_x(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_y(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_linear_id().
linear_id() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id (int x, int y) inline static constexpr
Compute the linearized coordinate of a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Definition at line 86 of file geography.hpp.
{
    return x + x_size*y;
  }
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size, and trisycl::y.
linear_x() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_x (int linear_id) inline static constexpr
Compute the horizontal coordinate of a tile from linear id.
Parameters
[in] linear_id is a linearized coordinate
Definition at line 95 of file geography.hpp.
{
    return linear_id%x_size;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_x().
linear_x() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_x (int linear_id) inline static constexpr
Compute the horizontal coordinate of a tile from linear id.
Parameters
[in] linear_id is a linearized coordinate
Definition at line 95 of file geography.hpp.
{
    return linear_id%x_size;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size.
linear_y() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_y (int linear_id) inline static constexpr
Compute the vertical coordinate of a tile from a linear id.
Parameters
[in] linear_id is a linearized coordinate
Definition at line 104 of file geography.hpp.
{
    return linear_id/x_size;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_y().
linear_y() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_y (int linear_id) inline static constexpr
Compute the vertical coordinate of a tile from a linear id.
Parameters
[in] linear_id is a linearized coordinate
Definition at line 104 of file geography.hpp.
{
    return linear_id/x_size;
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size.
memory_module_dx_coordinate() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_dx_coordinate (int y, int dx) inline static constexpr
Compute the memory module x coordinate delta from its tile.
Parameters
[in] y is the vertical tile coordinate
[in] dx is the horizontal displacement (-1,0,+1)
Definition at line 339 of file geography.hpp.
{
    // Mimic Figure 2-20 on p. 65
    return (dx - 1)/2 + (y & 1);
  }
References trisycl::y.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_linear_id().
memory_module_dx_coordinate() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_dx_coordinate (int y, int dx) inline static constexpr
Compute the memory module x coordinate delta from its tile.
Parameters
[in] y is the vertical tile coordinate
[in] dx is the horizontal displacement (-1,0,+1)
Definition at line 339 of file geography.hpp.
{
    // Mimic Figure 2-20 on p. 65
    return (dx - 1)/2 + (y & 1);
  }
References trisycl::y.
memory_module_linear_id() [1/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_linear_id (int x, int y, int dx, int dy) inline static constexpr
Compute the linear id of a memory module attached to a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 355 of file geography.hpp.
{
    if (dx == 0)
      return linear_id(x, y + dy);
    else
      // Take into account the horizontal chessboard-like skewing
      return linear_id(x + memory_module_dx_coordinate(y, dx), y);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_dx_coordinate(), x, and trisycl::y.
memory_module_linear_id() [2/2]
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_linear_id (int x, int y, int dx, int dy) inline static constexpr
Compute the linear id of a memory module attached to a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 355 of file geography.hpp.
{
    if (dx == 0)
      return linear_id(x, y + dy);
    else
      // Take into account the horizontal chessboard-like skewing
      return linear_id(x + memory_module_dx_coordinate(y, dx), y);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::memory_module_dx_coordinate(), x, and trisycl::y.
validate_x() [1/2]
template<typename Layout > static void trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x (int x) inline static
Validate an horizontal coordinate.
Do nothing but throwing if the coordinate is not a valid tile coordinate.
Parameters
[in] x is the horizontal tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 127 of file geography.hpp.
{
    if (!is_x_valid(x)) {
      throw ::trisycl::runtime_error {
        (boost::format { "The x coordinate %1% is not between %2% and %3%" }
          % x % x_min % layout::x_max).str() };
    }
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_valid(), x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x_y().
validate_x() [2/2]
template<typename Layout > static void trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x (int x) inline static
Validate an horizontal coordinate.
Do nothing but throwing if the coordinate is not a valid tile coordinate.
Parameters
[in] x is the horizontal tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 127 of file geography.hpp.
{
    if (!is_x_valid(x)) {
      throw ::trisycl::runtime_error {
        (boost::format { "The x coordinate %1% is not between %2% and %3%" }
          % x % x_min % layout::x_max).str() };
    }
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_valid(), x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min.
validate_x_y() [1/2]
template<typename Layout > static void trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x_y (int x, int y) inline static
Validate the horizontal and vertical coordinates.
Do nothing but throwing if the coordinates are not valid tile coordinates.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 184 of file geography.hpp.
{
    validate_x(x);
    validate_y(y);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_y(), x, and trisycl::y.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile().
validate_x_y() [2/2]
template<typename Layout > static void trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x_y (int x, int y) inline static
Validate the horizontal and vertical coordinates.
Do nothing but throwing if the coordinates are not valid tile coordinates.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 184 of file geography.hpp.
{
    validate_x(x);
    validate_y(y);
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_y(), x, and trisycl::y.
validate_y() [1/2]
template<typename Layout > static void trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_y (int y) inline static
Validate a vertical coordinate.
Do nothing but throwing if the coordinate is not a valid tile coordinate.
Parameters
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 154 of file geography.hpp.
{
    if (!is_y_valid(y)) {
      throw ::trisycl::runtime_error {
        (boost::format { "The y coordinate %1% is not between %2% and %3%" }
          % y % y_min % layout::y_max).str() };
    }
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_y_valid(), trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x_y().
validate_y() [2/2]
template<typename Layout > static void trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_y (int y) inline static
Validate a vertical coordinate.
Do nothing but throwing if the coordinate is not a valid tile coordinate.
Parameters
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 154 of file geography.hpp.
{
    if (!is_y_valid(y)) {
      throw ::trisycl::runtime_error {
        (boost::format { "The y coordinate %1% is not between %2% and %3%" }
          % y % y_min % layout::y_max).str() };
    }
  }
References trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_y_valid(), trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min.
Member Data Documentation
size
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::size = x_size*y_size static constexpr
Total number of tiles in the CGRA.
Definition at line 50 of file geography.hpp.
tile_coordinates
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::tile_coordinates static constexpr
Initial value:
= boost::hana::cartesian_product(
    boost::hana::make_tuple(
        boost::hana::range_c<int, y_min, y_size>
      , boost::hana::range_c<int, x_min, x_size>
                            )
                                                                          )
A tuple with the coordinate tuples of all the tiles inside the CGRA geometry.
Definition at line 55 of file geography.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::generate_tiles().
x_min
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_min = 0 static constexpr
Minimum horizontal coordinate.
Definition at line 38 of file geography.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_cascade_end(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_cascade_start(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_memory_module(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_west_column(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_valid(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x().
x_size
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size = layout::x_max + 1 static constexpr
Number of tile horizontally in the CGRA.
Definition at line 44 of file geography.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::cascade_linear_id(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_x_index(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_id(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_x(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::linear_y().
y_min
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_min = 0 static constexpr
Minimum vertical coordinate.
Definition at line 41 of file geography.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_cascade_start(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_memory_module(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_south_row(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_y_valid(), and trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_y().
y_size
template<typename Layout > static auto constexpr trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_size = layout::y_max + 1 static constexpr
Number of tile vertically in the CGRA.
Definition at line 47 of file geography.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), and trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_y_index().
trisycl::vendor::xilinx::acap::aie::layout::full
struct trisycl::vendor::xilinx::acap::aie::layout::full
Describe the layout of a "big" AI Engine array.
Use some constrains from Figure 2-8 "ME Array Address Map Example", p. 44
Definition at line 26 of file full.hpp.
Static Public Member Functions
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
Static Public Attributes
static auto constexpr x_min = 0
static auto constexpr x_max = 5
static auto constexpr y_min = 0
static auto constexpr y_max = 4
Member Function Documentation
is_noc_tile() [1/2]
static bool constexpr trisycl::vendor::xilinx::acap::aie::layout::full::is_noc_tile (int x, int y) inline static constexpr
Definition at line 32 of file full.hpp.
{
    return y == 0 && 2 <= x && x <= 3;
  }
References x, and trisycl::y.
is_noc_tile() [2/2]
static bool constexpr trisycl::vendor::xilinx::acap::aie::layout::full::is_noc_tile (int x, int y) inline static constexpr
Definition at line 32 of file full.hpp.
{
    return y == 0 && 2 <= x && x <= 3;
  }
References x, and trisycl::y.
is_pl_tile() [1/2]
static bool constexpr trisycl::vendor::xilinx::acap::aie::layout::full::is_pl_tile (int x, int y) inline static constexpr
Definition at line 36 of file full.hpp.
{
    return y == 0 && ((0 <= x && x <= 1) || (4 <= x && x <= 5));
  }
References x, and trisycl::y.
is_pl_tile() [2/2]
static bool constexpr trisycl::vendor::xilinx::acap::aie::layout::full::is_pl_tile (int x, int y) inline static constexpr
Definition at line 36 of file full.hpp.
{
    return y == 0 && ((0 <= x && x <= 1) || (4 <= x && x <= 5));
  }
References x, and trisycl::y.
Member Data Documentation
x_max
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::full::x_max = 5 static constexpr
Definition at line 28 of file full.hpp.
x_min
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::full::x_min = 0 static constexpr
Definition at line 27 of file full.hpp.
y_max
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::full::y_max = 4 static constexpr
Definition at line 30 of file full.hpp.
y_min
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::full::y_min = 0 static constexpr
Definition at line 29 of file full.hpp.
trisycl::vendor::xilinx::acap::aie::layout::one_pe
struct trisycl::vendor::xilinx::acap::aie::layout::one_pe
Describe the layout of a tiny AI Engine with only 1 tile.
Definition at line 23 of file one_pe.hpp.
Static Public Attributes
static auto constexpr x_max = 0
static auto constexpr y_max = 0
Static Public Attributes inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static auto constexpr x_min = 0
static auto constexpr x_max = 5
static auto constexpr y_min = 0
static auto constexpr y_max = 4
Additional Inherited Members
Static Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
Member Data Documentation
x_max
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::one_pe::x_max = 0 static constexpr
Definition at line 24 of file one_pe.hpp.
y_max
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::one_pe::y_max = 0 static constexpr
Definition at line 25 of file one_pe.hpp.
trisycl::vendor::xilinx::acap::aie::layout::size
struct trisycl::vendor::xilinx::acap::aie::layout::size
template<int X_size, int Y_size>
struct trisycl::vendor::xilinx::acap::aie::layout::size< X_size, Y_size >
Fully specify the size of an AI Engine layout.
Parameters
X_size is the number of tile horizontally
Y_size is the number of tile vertically
Definition at line 30 of file size.hpp.
Static Public Attributes
static auto constexpr x_max = X_size - 1
Maximum horizontal coordinate.
static auto constexpr y_max = Y_size - 1
Maximum vertical coordinate.
Static Public Attributes inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static auto constexpr x_min = 0
static auto constexpr x_max = 5
static auto constexpr y_min = 0
static auto constexpr y_max = 4
Additional Inherited Members
Static Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
Member Data Documentation
x_max
template<int X_size, int Y_size> static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::size< X_size, Y_size >::x_max = X_size - 1 static constexpr
Maximum horizontal coordinate.
Definition at line 34 of file size.hpp.
y_max
template<int X_size, int Y_size> static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::size< X_size, Y_size >::y_max = Y_size - 1 static constexpr
Maximum vertical coordinate.
Definition at line 37 of file size.hpp.
trisycl::vendor::xilinx::acap::aie::layout::small
struct trisycl::vendor::xilinx::acap::aie::layout::small
Describe the layout of a small AI Engine array with only a few PE.
Definition at line 23 of file small.hpp.
Static Public Attributes
static auto constexpr x_max = 1
static auto constexpr y_max = 2
Static Public Attributes inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static auto constexpr x_min = 0
static auto constexpr x_max = 5
static auto constexpr y_min = 0
static auto constexpr y_max = 4
Additional Inherited Members
Static Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
Member Data Documentation
x_max
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::small::x_max = 1 static constexpr
Definition at line 24 of file small.hpp.
y_max
static auto constexpr trisycl::vendor::xilinx::acap::aie::layout::small::y_max = 2 static constexpr
Definition at line 25 of file small.hpp.
trisycl::vendor::xilinx::acap::aie::layout::ve1152
struct trisycl::vendor::xilinx::acap::aie::layout::ve1152
Describe the layout of a Versal VE1152 device
Definition at line 24 of file versal.hpp.
Additional Inherited Members
Static Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
static bool constexpr is_noc_tile (int x, int y)
static bool constexpr is_pl_tile (int x, int y)
Static Public Attributes inherited from trisycl::vendor::xilinx::acap::aie::layout::size< 17, 3 >
static auto constexpr x_max
Maximum horizontal coordinate.
static auto constexpr y_max
Maximum vertical coordinate.
Static Public Attributes inherited from trisycl::vendor::xilinx::acap::aie::layout::full
static auto constexpr x_min = 0
static auto constexpr x_max = 5
static auto constexpr y_min = 0
static auto constexpr y_max = 4
trisycl::vendor::xilinx::acap::aie::lock_unit
struct trisycl::vendor::xilinx::acap::aie::lock_unit
The lock infrastructure used by AI Engine memory modules and shim tiles.
Based on Math Engine (ME) Architecture Specification, Revision v1.5 June 2018
4.4.6 Lock Interface, p. 115
4.7 Lock Unit, p. 129
Definition at line 37 of file lock.hpp.
Public Types
using lock_id_t = decltype(lock_number)
using lock_id_t = decltype(lock_number)
Public Member Functions
auto & lock (int i)
Get the requested lock.
auto & lock (int i)
Get the requested lock.
Public Attributes
locking_device locks [lock_number]
The locking units of the locking device.
Static Public Attributes
static auto constexpr lock_number = 16
Member Typedef Documentation
lock_id_t [1/2]
using trisycl::vendor::xilinx::acap::aie::lock_unit::lock_id_t = decltype(lock_number)
Definition at line 41 of file lock.hpp.
lock_id_t [2/2]
using trisycl::vendor::xilinx::acap::aie::lock_unit::lock_id_t = decltype(lock_number)
Definition at line 41 of file lock.hpp.
Member Function Documentation
lock() [1/2]
auto & trisycl::vendor::xilinx::acap::aie::lock_unit::lock (int i) inline
Get the requested lock.
Definition at line 99 of file lock.hpp.
                    {
    assert(0 <= i && i < lock_number);
    return locks[i];
  }
References i, lock_number, and locks.
Referenced by trisycl::vendor::xilinx::acap::aie::memory_infrastructure::lock().
lock() [2/2]
auto & trisycl::vendor::xilinx::acap::aie::lock_unit::lock (int i) inline
Get the requested lock.
Definition at line 99 of file lock.hpp.
                    {
    assert(0 <= i && i < lock_number);
    return locks[i];
  }
References i, lock_number, and locks.
Member Data Documentation
lock_number
static auto constexpr trisycl::vendor::xilinx::acap::aie::lock_unit::lock_number = 16 static constexpr
Definition at line 39 of file lock.hpp.
Referenced by lock().
locks
locking_device trisycl::vendor::xilinx::acap::aie::lock_unit::locks
The locking units of the locking device.
Definition at line 96 of file lock.hpp.
Referenced by lock().
trisycl::vendor::xilinx::acap::aie::memory
struct trisycl::vendor::xilinx::acap::aie::memory
template<typename AIE, int X, int Y>
struct trisycl::vendor::xilinx::acap::aie::memory< AIE, X, Y >
The AI Engine Memory Module infrastructure of a tile.
This is the type you need to inherit from to define the content of a CGRA tile memory module.
Parameters
AIE is the type representing the full CGRA with the programs and memory contents
X is the horizontal coordinate of the memory module
Y is the vertical coordinate of the memory module
Definition at line 43 of file memory.hpp.
Static Public Attributes
static auto constexpr x = X
The horizontal tile coordinates in the CGRA grid (starting at 0 and increasing towards East)
static auto constexpr y = Y
The vertical tile coordinates in the CGRA grid (starting at increasing towards North)
Additional Inherited Members
Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::memory_base
auto & lock (int i)
Get an access to the a specific lock.
void set_memory_infrastructure (memory_infrastructure &m)
Store a way to access to hardware infrastructure of the tile.
auto & lock (int i)
Get an access to the a specific lock.
void set_memory_infrastructure (memory_infrastructure &m)
Store a way to access to hardware infrastructure of the tile.
Public Attributes inherited from trisycl::vendor::xilinx::acap::aie::memory_base
std::optional< std::reference_wrapper< memory_infrastructure > > mi
Keep a reference to the memory_infrastructure hardware features.
Member Data Documentation
x
template<typename AIE , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::memory< AIE, X, Y >::x = X static constexpr
The horizontal tile coordinates in the CGRA grid (starting at 0 and increasing towards East)
Definition at line 46 of file memory.hpp.
y
template<typename AIE , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::memory< AIE, X, Y >::y = Y static constexpr
The vertical tile coordinates in the CGRA grid (starting at increasing towards North)
Definition at line 49 of file memory.hpp.
trisycl::vendor::xilinx::acap::aie::memory_base
struct trisycl::vendor::xilinx::acap::aie::memory_base
The AI Engine Memory Module infrastructure of a tile common to all the tiles.
This allows some type erasure while accessing the common memory module infrastructure.
Definition at line 37 of file memory_base.hpp.
Public Member Functions
auto & lock (int i)
Get an access to the a specific lock.
void set_memory_infrastructure (memory_infrastructure &m)
Store a way to access to hardware infrastructure of the tile.
auto & lock (int i)
Get an access to the a specific lock.
void set_memory_infrastructure (memory_infrastructure &m)
Store a way to access to hardware infrastructure of the tile.
Public Attributes
std::optional< std::reference_wrapper< memory_infrastructure > > mi
Keep a reference to the memory_infrastructure hardware features.
Member Function Documentation
lock() [1/2]
auto & trisycl::vendor::xilinx::acap::aie::memory_base::lock (int i) inline
Get an access to the a specific lock.
Definition at line 42 of file memory_base.hpp.
                    {
    // value() will throw if there is some missed initialization
    return mi.value().get().lock(i);
  }
References i, and mi.
lock() [2/2]
auto & trisycl::vendor::xilinx::acap::aie::memory_base::lock (int i) inline
Get an access to the a specific lock.
Definition at line 42 of file memory_base.hpp.
                    {
    // value() will throw if there is some missed initialization
    return mi.value().get().lock(i);
  }
References i, and mi.
set_memory_infrastructure() [1/2]
void trisycl::vendor::xilinx::acap::aie::memory_base::set_memory_infrastructure (memory_infrastructure & m) inline
Store a way to access to hardware infrastructure of the tile.
Definition at line 48 of file memory_base.hpp.
{ mi = m; }
References mi.
set_memory_infrastructure() [2/2]
void trisycl::vendor::xilinx::acap::aie::memory_base::set_memory_infrastructure (memory_infrastructure & m) inline
Store a way to access to hardware infrastructure of the tile.
Definition at line 48 of file memory_base.hpp.
{ mi = m; }
References mi.
Member Data Documentation
mi
std::optional< std::reference_wrapper< memory_infrastructure > > trisycl::vendor::xilinx::acap::aie::memory_base::mi
Keep a reference to the memory_infrastructure hardware features.
Definition at line 39 of file memory_base.hpp.
Referenced by lock(), and set_memory_infrastructure().
trisycl::vendor::xilinx::acap::aie::memory_infrastructure
class trisycl::vendor::xilinx::acap::aie::memory_infrastructure
The AI Engine memory infrastructure common to all the tiles.
This allows some type erasure while accessing the common memory infrastructure.
Parameters
Geography is the geography type representing the full layout of the architecture
Definition at line 33 of file memory_infrastructure.hpp.
Public Member Functions
memory_infrastructure (auto &dev)
Start the memory infrastructure associated to the AIE device tile.
auto & lock (int i)
Get access to a specific lock in this memory module.
memory_infrastructure (auto &dev)
Start the memory infrastructure associated to the AIE device tile.
auto & lock (int i)
Get access to a specific lock in this memory module.
Private Attributes
lock_unit memory_locking_unit
The lock unit of the memory tile.
void * dev
Keep track of the aie::detail::device for hardware resource control in device mode or for debugging purpose for better messages.
Constructor & Destructor Documentation
memory_infrastructure() [1/2]
trisycl::vendor::xilinx::acap::aie::memory_infrastructure::memory_infrastructure (auto & dev) inline
Start the memory infrastructure associated to the AIE device tile.
Parameters
[in] dev is the aie::detail::device used to control hardware when using real hardware and provide some debug information from inside the tile_infrastructure.
Use auto concept here to avoid explicit type causing circular dependency
Definition at line 55 of file memory_infrastructure.hpp.
      : dev { &dev } {}
memory_infrastructure() [2/2]
trisycl::vendor::xilinx::acap::aie::memory_infrastructure::memory_infrastructure (auto & dev) inline
Start the memory infrastructure associated to the AIE device tile.
Parameters
[in] dev is the aie::detail::device used to control hardware when using real hardware and provide some debug information from inside the tile_infrastructure.
Use auto concept here to avoid explicit type causing circular dependency
Definition at line 55 of file memory_infrastructure.hpp.
      : dev { &dev } {}
Member Function Documentation
lock() [1/2]
auto & trisycl::vendor::xilinx::acap::aie::memory_infrastructure::lock (int i) inline
Get access to a specific lock in this memory module.
Definition at line 59 of file memory_infrastructure.hpp.
{ return memory_locking_unit.lock(i); }
References i, trisycl::vendor::xilinx::acap::aie::lock_unit::lock(), and memory_locking_unit.
lock() [2/2]
auto & trisycl::vendor::xilinx::acap::aie::memory_infrastructure::lock (int i) inline
Get access to a specific lock in this memory module.
Definition at line 59 of file memory_infrastructure.hpp.
{ return memory_locking_unit.lock(i); }
References i, trisycl::vendor::xilinx::acap::aie::lock_unit::lock(), and memory_locking_unit.
Member Data Documentation
dev
void * trisycl::vendor::xilinx::acap::aie::memory_infrastructure::dev private
Keep track of the aie::detail::device for hardware resource control in device mode or for debugging purpose for better messages.
Use void* for now to avoid cyclic header dependencies for now instead of the aie::detail::device
Definition at line 43 of file memory_infrastructure.hpp.
memory_locking_unit
lock_unit trisycl::vendor::xilinx::acap::aie::memory_infrastructure::memory_locking_unit private
The lock unit of the memory tile.
Definition at line 35 of file memory_infrastructure.hpp.
Referenced by lock().
trisycl::vendor::xilinx::acap::aie::program
struct trisycl::vendor::xilinx::acap::aie::program
template<typename AIEDevice, template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory>
struct trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >
Define an AI Engine CGRA program with its code and memory per core.
Parameters
AIEDevice is the device description of the machine to instantiate with the physical size
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
Definition at line 54 of file program.hpp.
Public Types
using geo = typename AIEDevice::geo
The geography of the CGRA.
using device = AIEDevice
template<int X, int Y>
using tileable_memory = Memory< program, X, Y >
Type describing all the memory modules of the CGRA.
template<int X, int Y>
using tileable_tile = Tile< program, X, Y >
Type describing the programs of all the cores in the CGRA.
using geo = typename AIEDevice::geo
The geography of the CGRA.
using device = AIEDevice
template<int X, int Y>
using tileable_memory = Memory< program, X, Y >
Type describing all the memory modules of the CGRA.
template<int X, int Y>
using tileable_tile = Tile< program, X, Y >
Type describing the programs of all the cores in the CGRA.
Public Member Functions
memory_base & memory_module (int x, int y)
Access to the common infrastructure part of a memory module.
template<int LinearId>
auto & memory_module ()
Access to a heterogeneous memory module by its linear id.
template<int X, int Y>
auto & memory_module ()
Access to a heterogeneous memory module by its coordinates.
template<typename F >
void for_each_memory_base (F &&f)
Iterate on all the memory module bases of the AIE in an homogeneous way.
template<int LinearId>
auto & tile ()
Access to a heterogeneous tile by linear id.
template<int X, int Y>
auto & tile ()
Access to a heterogeneous tile by its coordinates.
template<typename F >
void for_each_tile_base (F &&f)
Iterate on all the tile bases of the AIE in an homogeneous way.
program (AIEDevice &aie_d)
Create the AIE program with the tiles and memory modules.
template<typename KernelName , typename KernelType >
void kernel_outliner (KernelType k)
Instantiate a kernel in a form that can be outlined by the SYCL device compiler.
void wait ()
Wait for the end of the execution of each tile.
void run ()
Launch the programs of all the tiles of the CGRA in their own executor (CPU thread, fiber...) and wait for their completion.
template<typename Invocable >
void run (Invocable &&f)
Run synchronously an heterogeneous invocable collectively on the device.
auto & cascade ()
Access the cascade connections.
memory_base & memory_module (int x, int y)
Access to the common infrastructure part of a memory module.
template<int LinearId>
auto & memory_module ()
Access to a heterogeneous memory module by its linear id.
template<int X, int Y>
auto & memory_module ()
Access to a heterogeneous memory module by its coordinates.
template<typename F >
void for_each_memory_base (F &&f)
Iterate on all the memory module bases of the AIE in an homogeneous way.
template<int LinearId>
auto & tile ()
Access to a heterogeneous tile by linear id.
template<int X, int Y>
auto & tile ()
Access to a heterogeneous tile by its coordinates.
template<typename F >
void for_each_tile_base (F &&f)
Iterate on all the tile bases of the AIE in an homogeneous way.
program (AIEDevice &aie_d)
Create the AIE program with the tiles and memory modules.
template<typename KernelName , typename KernelType >
void kernel_outliner (KernelType k)
Instantiate a kernel in a form that can be outlined by the SYCL device compiler.
void wait ()
Wait for the end of the execution of each tile.
void run ()
Launch the programs of all the tiles of the CGRA in their own executor (CPU thread, fiber...) and wait for their completion.
template<typename Invocable >
void run (Invocable &&f)
Run synchronously an heterogeneous invocable collectively on the device.
auto & cascade ()
Access the cascade connections.
Public Attributes
AIEDevice aie_d
The device running this program.
decltype(geo::template generate_tiles< tileable_memory >()) memory_modules = geo::template generate_tiles<tileable_memory>()
The tiled memory modules of the CGRA.
memory_base * memory_modules_bases [geo::y_size][geo::x_size]
Keep track of all the tiled memory modules as a type-erased memory_modules_base type to have a simpler access to the basic position-independent memory module features.
decltype(geo::template generate_tiles< tileable_tile >()) tiles
The tiled programs of the CGRA.
tile_base< program > * tile_bases [geo::y_size][geo::x_size]
Keep track of all the tiles as a type-erased tile_base type to have a simpler access to the basic position-independent tile features.
Member Typedef Documentation
device [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::device = AIEDevice
Definition at line 58 of file program.hpp.
device [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::device = AIEDevice
Definition at line 58 of file program.hpp.
geo [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::geo = typename AIEDevice::geo
The geography of the CGRA.
Definition at line 57 of file program.hpp.
geo [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::geo = typename AIEDevice::geo
The geography of the CGRA.
Definition at line 57 of file program.hpp.
tileable_memory [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tileable_memory = Memory<program, X, Y>
Type describing all the memory modules of the CGRA.
Definition at line 65 of file program.hpp.
tileable_memory [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tileable_memory = Memory<program, X, Y>
Type describing all the memory modules of the CGRA.
Definition at line 65 of file program.hpp.
tileable_tile [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tileable_tile = Tile<program, X, Y>
Type describing the programs of all the cores in the CGRA.
Definition at line 81 of file program.hpp.
tileable_tile [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> using trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tileable_tile = Tile<program, X, Y>
Type describing the programs of all the cores in the CGRA.
Definition at line 81 of file program.hpp.
Constructor & Destructor Documentation
program() [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::program (AIEDevice & aie_d) inline
Create the AIE program with the tiles and memory modules.
Definition at line 177 of file program.hpp.
                            : aie_d { aie_d } {
    boost::hana::for_each(tiles, [&] (auto& t) {
        // Inform each tile about its program
        t.set_program(*this);
        // Inform each tile about their tile infrastructure
        t.set_tile_infrastructure(aie_d.tile(t.x, t.y));
        // Keep track of each base tile
        tile_bases[t.y][t.x] = &t;
      });
    // Connect each memory to its infrastructure
    boost::hana::for_each(memory_modules, [&] (auto& m) {
        // Inform each tile about their tile infrastructure
        m.set_memory_infrastructure(aie_d.mem(m.x, m.y));
        // Keep track of each base tile
        memory_modules_bases[m.y][m.x] = &m;
      });
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::aie_d, trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules, trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules_bases, trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile_bases, and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles.
program() [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::program (AIEDevice & aie_d) inline
Create the AIE program with the tiles and memory modules.
Definition at line 177 of file program.hpp.
                            : aie_d { aie_d } {
    boost::hana::for_each(tiles, [&] (auto& t) {
        // Inform each tile about its program
        t.set_program(*this);
        // Inform each tile about their tile infrastructure
        t.set_tile_infrastructure(aie_d.tile(t.x, t.y));
        // Keep track of each base tile
        tile_bases[t.y][t.x] = &t;
      });
    // Connect each memory to its infrastructure
    boost::hana::for_each(memory_modules, [&] (auto& m) {
        // Inform each tile about their tile infrastructure
        m.set_memory_infrastructure(aie_d.mem(m.x, m.y));
        // Keep track of each base tile
        memory_modules_bases[m.y][m.x] = &m;
      });
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::aie_d, trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules, trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules_bases, trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile_bases, and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles.
Member Function Documentation
cascade() [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::cascade () inline
Access the cascade connections.
Definition at line 276 of file program.hpp.
                  {
    return aie_d.cascade();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::aie_d.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::cascade().
cascade() [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::cascade () inline
Access the cascade connections.
Definition at line 276 of file program.hpp.
                  {
    return aie_d.cascade();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::aie_d.
for_each_memory_base() [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename F > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::for_each_memory_base (F && f) inline
Iterate on all the memory module bases of the AIE in an homogeneous way.
Parameters
[in] F is the function to apply on each memory module base
Definition at line 135 of file program.hpp.
{
    for (auto y = 0; y != geo::y_size; ++y)
      for (auto x = 0; x != geo::x_size; ++x)
        f(*memory_modules_bases[y][x]);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules_bases, x, and trisycl::y.
for_each_memory_base() [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename F > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::for_each_memory_base (F && f) inline
Iterate on all the memory module bases of the AIE in an homogeneous way.
Parameters
[in] F is the function to apply on each memory module base
Definition at line 135 of file program.hpp.
{
    for (auto y = 0; y != geo::y_size; ++y)
      for (auto x = 0; x != geo::x_size; ++x)
        f(*memory_modules_bases[y][x]);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules_bases, x, and trisycl::y.
for_each_tile_base() [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename F > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::for_each_tile_base (F && f) inline
Iterate on all the tile bases of the AIE in an homogeneous way.
Parameters
[in] F is the function to apply on each tile base
Definition at line 169 of file program.hpp.
{
    for (auto y = 0; y != geo::y_size; ++y)
      for (auto x = 0; x != geo::x_size; ++x)
        f(*tile_bases[y][x]);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile_bases, x, and trisycl::y.
for_each_tile_base() [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename F > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::for_each_tile_base (F && f) inline
Iterate on all the tile bases of the AIE in an homogeneous way.
Parameters
[in] F is the function to apply on each tile base
Definition at line 169 of file program.hpp.
{
    for (auto y = 0; y != geo::y_size; ++y)
      for (auto x = 0; x != geo::x_size; ++x)
        f(*tile_bases[y][x]);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile_bases, x, and trisycl::y.
kernel_outliner() [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename KernelName , typename KernelType > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::kernel_outliner (KernelType k) inline
Instantiate a kernel in a form that can be outlined by the SYCL device compiler.
Parameters
[in] KernelName k is the kernel name type required by SYCL
[in] k is the kernel functor
Definition at line 207 of file program.hpp.
{
    k();
  }
kernel_outliner() [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename KernelName , typename KernelType > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::kernel_outliner (KernelType k) inline
Instantiate a kernel in a form that can be outlined by the SYCL device compiler.
Parameters
[in] KernelName k is the kernel name type required by SYCL
[in] k is the kernel functor
Definition at line 207 of file program.hpp.
{
    k();
  }
memory_module() [1/6]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int LinearId> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module () inline
Access to a heterogeneous memory module by its linear id.
Parameters
[in] LinearId is the linear id
Definition at line 112 of file program.hpp.
{
    return boost::hana::at_c<LinearId>(memory_modules);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules.
memory_module() [2/6]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module () inline
Access to a heterogeneous memory module by its coordinates.
Parameters
[in] X is the horizontal memory module coordinate
[in] Y is the vertical memory module coordinate
Definition at line 124 of file program.hpp.
{
    return memory_module<geo::linear_id(X, Y)>();
  }
memory_module() [3/6]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int LinearId> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module () inline
Access to a heterogeneous memory module by its linear id.
Parameters
[in] LinearId is the linear id
Definition at line 112 of file program.hpp.
{
    return boost::hana::at_c<LinearId>(memory_modules);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules.
memory_module() [4/6]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module () inline
Access to a heterogeneous memory module by its coordinates.
Parameters
[in] X is the horizontal memory module coordinate
[in] Y is the vertical memory module coordinate
Definition at line 124 of file program.hpp.
{
    return memory_module<geo::linear_id(X, Y)>();
  }
memory_module() [5/6]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> memory_base & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module (int x, int y) inline
Access to the common infrastructure part of a memory module.
Parameters
[in] x is the horizontal memory module coordinate
[in] y is the vertical memory module coordinate
Definition at line 101 of file program.hpp.
{
    geo::validate_x_y(x, y);
    return *memory_modules_bases[y][x];
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules_bases, x, and trisycl::y.
memory_module() [6/6]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> memory_base & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module (int x, int y) inline
Access to the common infrastructure part of a memory module.
Parameters
[in] x is the horizontal memory module coordinate
[in] y is the vertical memory module coordinate
Definition at line 101 of file program.hpp.
{
    geo::validate_x_y(x, y);
    return *memory_modules_bases[y][x];
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules_bases, x, and trisycl::y.
run() [1/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::run () inline
Launch the programs of all the tiles of the CGRA in their own executor (CPU thread, fiber...) and wait for their completion.
This is the main member function to use to launch the execution.
Definition at line 225 of file program.hpp.
             {
    // Start each tile program in its own executor
    boost::hana::for_each(tiles, [&] (auto& t) {
        t.single_task([&] {
            TRISYCL_DUMP_T("Starting AIE tile (" << t.x << ',' << t.y
                           << ") linear id = " << t.linear_id());
            /* Just use a capture by reference in the following
               because there is direct execution here */
            auto kernel = [&] {
                            // If the tile has an operator(), use it
                            if constexpr (requires { t(); })
                              return [&] { t(); };
                            /* Else the kernel should have a run
                               member function and use it. */
                            else
                              return [&] { t.run(); };
            }();
            using kernel_type = decltype(kernel);
            // Use the kernel type as its SYCL name too
            kernel_outliner<kernel_type, kernel_type>(kernel);
            TRISYCL_DUMP_T("Stopping AIE tile (" << t.x << ',' << t.y << ')');
          });
      });
    wait();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles, TRISYCL_DUMP_T, and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::wait().
run() [2/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::run () inline
Launch the programs of all the tiles of the CGRA in their own executor (CPU thread, fiber...) and wait for their completion.
This is the main member function to use to launch the execution.
Definition at line 225 of file program.hpp.
             {
    // Start each tile program in its own executor
    boost::hana::for_each(tiles, [&] (auto& t) {
        t.single_task([&] {
            TRISYCL_DUMP_T("Starting AIE tile (" << t.x << ',' << t.y
                           << ") linear id = " << t.linear_id());
            /* Just use a capture by reference in the following
               because there is direct execution here */
            auto kernel = [&] {
                            // If the tile has an operator(), use it
                            if constexpr (requires { t(); })
                              return [&] { t(); };
                            /* Else the kernel should have a run
                               member function and use it. */
                            else
                              return [&] { t.run(); };
            }();
            using kernel_type = decltype(kernel);
            // Use the kernel type as its SYCL name too
            kernel_outliner<kernel_type, kernel_type>(kernel);
            TRISYCL_DUMP_T("Stopping AIE tile (" << t.x << ',' << t.y << ')');
          });
      });
    wait();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles, TRISYCL_DUMP_T, and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::wait().
run() [3/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::run (Invocable && f) inline
Run synchronously an heterogeneous invocable collectively on the device.
Parameters
f is an invocable taking an heterogeneous tile handler
Todo:
Factorize out the 2 run functions
Each tile gets its own copy of work
Definition at line 258 of file program.hpp.
{
    // Start each tile program in its own executor
    boost::hana::for_each(tiles, [&] (auto& t) {
        t.single_task([&] {
            TRISYCL_DUMP_T("Starting AIE tile (" << t.x << ',' << t.y
                           << ") linear id = " << t.linear_id());
            /// Each tile gets its own copy of work
            auto kernel = [&, work = f] { work(t); };
            using kernel_type = decltype(kernel);
            // Use the kernel type as its SYCL name too
            kernel_outliner<kernel_type, kernel_type>(kernel);
            TRISYCL_DUMP_T("Stopping AIE tile (" << t.x << ',' << t.y << ')');
          });
      });
    wait();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles, TRISYCL_DUMP_T, and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::wait().
run() [4/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::run (Invocable && f) inline
Run synchronously an heterogeneous invocable collectively on the device.
Parameters
f is an invocable taking an heterogeneous tile handler
Todo:
Factorize out the 2 run functions
Each tile gets its own copy of work
Definition at line 258 of file program.hpp.
{
    // Start each tile program in its own executor
    boost::hana::for_each(tiles, [&] (auto& t) {
        t.single_task([&] {
            TRISYCL_DUMP_T("Starting AIE tile (" << t.x << ',' << t.y
                           << ") linear id = " << t.linear_id());
            /// Each tile gets its own copy of work
            auto kernel = [&, work = f] { work(t); };
            using kernel_type = decltype(kernel);
            // Use the kernel type as its SYCL name too
            kernel_outliner<kernel_type, kernel_type>(kernel);
            TRISYCL_DUMP_T("Stopping AIE tile (" << t.x << ',' << t.y << ')');
          });
      });
    wait();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles, TRISYCL_DUMP_T, and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::wait().
tile() [1/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int LinearId> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile () inline
Access to a heterogeneous tile by linear id.
Parameters
[in] LinearId is the linear id
Definition at line 147 of file program.hpp.
               {
    return boost::hana::at_c<LinearId>(tiles);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles.
tile() [2/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile () inline
Access to a heterogeneous tile by its coordinates.
Parameters
[in] X is the horizontal tile coordinate
[in] Y is the vertical tile coordinate
Definition at line 159 of file program.hpp.
               {
    return tile<geo::linear_id(X, Y)>();
  }
tile() [3/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int LinearId> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile () inline
Access to a heterogeneous tile by linear id.
Parameters
[in] LinearId is the linear id
Definition at line 147 of file program.hpp.
               {
    return boost::hana::at_c<LinearId>(tiles);
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles.
tile() [4/4]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> template<int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile () inline
Access to a heterogeneous tile by its coordinates.
Parameters
[in] X is the horizontal tile coordinate
[in] Y is the vertical tile coordinate
Definition at line 159 of file program.hpp.
               {
    return tile<geo::linear_id(X, Y)>();
  }
wait() [1/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::wait () inline
Wait for the end of the execution of each tile.
Definition at line 212 of file program.hpp.
              {
    boost::hana::for_each(tiles, [&] (auto& t) {
        TRISYCL_DUMP_T("Joining AIE tile (" << t.x << ',' << t.y << ")...");
        t.wait();
        TRISYCL_DUMP_T("Joined AIE tile (" << t.x << ',' << t.y << ')');
      });
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles, and TRISYCL_DUMP_T.
Referenced by trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::run().
wait() [2/2]
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::wait () inline
Wait for the end of the execution of each tile.
Definition at line 212 of file program.hpp.
              {
    boost::hana::for_each(tiles, [&] (auto& t) {
        TRISYCL_DUMP_T("Joining AIE tile (" << t.x << ',' << t.y << ")...");
        t.wait();
        TRISYCL_DUMP_T("Joined AIE tile (" << t.x << ',' << t.y << ')');
      });
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles, and TRISYCL_DUMP_T.
Member Data Documentation
aie_d
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> AIEDevice trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::aie_d
The device running this program.
Definition at line 61 of file program.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::cascade(), and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::program().
memory_modules
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> decltype(geo::template generate_tiles< tileable_memory >()) trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules = geo::template generate_tiles<tileable_memory>()
The tiled memory modules of the CGRA.
Unfortunately it is not possible to use auto here... Otherwise it could be just:
static inline auto
Definition at line 72 of file program.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module(), and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::program().
memory_modules_bases
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> memory_base * trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_modules_bases
Keep track of all the tiled memory modules as a type-erased memory_modules_base type to have a simpler access to the basic position-independent memory module features.
Definition at line 77 of file program.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::for_each_memory_base(), trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::memory_module(), and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::program().
tile_bases
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> tile_base< program > * trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile_bases
Keep track of all the tiles as a type-erased tile_base type to have a simpler access to the basic position-independent tile features.
Definition at line 93 of file program.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::for_each_tile_base(), and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::program().
tiles
template<typename AIEDevice , template< typename AIE, int X, int Y > typename Tile = acap::aie::tile, template< typename AIE, int X, int Y > typename Memory = acap::aie::memory> decltype(geo::template generate_tiles< tileable_tile >()) trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tiles
Initial value:
=
    geo::template generate_tiles<tileable_tile>()
The tiled programs of the CGRA.
Unfortunately it is not possible to use auto here... Otherwise it could be just:
static inline auto
Definition at line 87 of file program.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::program(), trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::run(), trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::tile(), and trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::wait().
trisycl::vendor::xilinx::acap::aie::queue
struct trisycl::vendor::xilinx::acap::aie::queue
template<typename AIEDevice>
struct trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >
The AI Engine minimal queue.
Todo:
Make a real queue implementation instead of this mock-up
Parameters
AIEDevice is the AIE device targeted by the queue
Todo:
Make a real queue implementation instead of this mock-up
Parameters
AIEDevice is the AIE device targeted by the queue
Definition at line 30 of file queue.hpp.
Public Types
using device = AIEDevice
using geo = typename device::geo
using layout = typename geo::layout
using device = AIEDevice
using geo = typename device::geo
using layout = typename geo::layout
Public Member Functions
queue (device &d)
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
void run () const
Run synchronously a program execution on this queue.
template<typename Invocable >
void run (Invocable &&f) const
Run synchronously an heterogeneous invocable on this queue.
void wait () const
Wait for all the device tiles on this queue to finish.
template<typename Invocable >
void uniform_run (Invocable &&f) const
Run synchronously a uniform invocable on this queue.
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
auto submit () const
Submit a program execution on this queue.
queue (device &d)
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
void run () const
Run synchronously a program execution on this queue.
template<typename Invocable >
void run (Invocable &&f) const
Run synchronously an heterogeneous invocable on this queue.
void wait () const
Wait for all the device tiles on this queue to finish.
template<typename Invocable >
void uniform_run (Invocable &&f) const
Run synchronously a uniform invocable on this queue.
template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory>
auto submit () const
Submit a program execution on this queue.
Public Attributes
device & aie_d
Member Typedef Documentation
device [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::device = AIEDevice
Definition at line 31 of file queue.hpp.
device [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::device = AIEDevice
Definition at line 31 of file queue.hpp.
geo [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::geo = typename device::geo
Definition at line 32 of file queue.hpp.
geo [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::geo = typename device::geo
Definition at line 32 of file queue.hpp.
layout [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::layout = typename geo::layout
Definition at line 33 of file queue.hpp.
layout [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::layout = typename geo::layout
Definition at line 33 of file queue.hpp.
Constructor & Destructor Documentation
queue() [1/2]
template<typename AIEDevice > trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::queue (device & d) inline
Definition at line 38 of file queue.hpp.
      : aie_d { d } {}
queue() [2/2]
template<typename AIEDevice > trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::queue (device & d) inline
Definition at line 38 of file queue.hpp.
      : aie_d { d } {}
Member Function Documentation
run() [1/4]
template<typename AIEDevice > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::run () const inline
Run synchronously a program execution on this queue.
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
Definition at line 63 of file queue.hpp.
                   {
    program<device, Tile, Memory> { aie_d }.run();
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d.
run() [2/4]
template<typename AIEDevice > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::run () const inline
Run synchronously a program execution on this queue.
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
Definition at line 63 of file queue.hpp.
                   {
    program<device, Tile, Memory> { aie_d }.run();
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d.
run() [3/4]
template<typename AIEDevice > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::run (Invocable && f) const inline
Run synchronously an heterogeneous invocable on this queue.
Parameters
f is an invocable taking an heterogeneous tile handler
Definition at line 71 of file queue.hpp.
{
    program<device> { aie_d }.run(std::forward<Invocable>(f));
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d.
run() [4/4]
template<typename AIEDevice > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::run (Invocable && f) const inline
Run synchronously an heterogeneous invocable on this queue.
Parameters
f is an invocable taking an heterogeneous tile handler
Definition at line 71 of file queue.hpp.
{
    program<device> { aie_d }.run(std::forward<Invocable>(f));
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d.
submit() [1/2]
template<typename AIEDevice > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> auto trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::submit () const inline
Submit a program execution on this queue.
Todo:
SUBMIT
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
\fixme implement a real queue with lifetime support because here it assume the device will last...
Definition at line 106 of file queue.hpp.
                      {
    return queue_waiter { std::async(std::launch::async,
                                     /** \fixme implement a real queue with
                                        lifetime support because here it assume
                                        the device will last... */
                                     [*this] { this->run<Tile, Memory>(); }) };
  }
submit() [2/2]
template<typename AIEDevice > template<template< typename Device, int X, int Y > typename Tile = acap::aie::tile, template< typename Device, int X, int Y > typename Memory = acap::aie::memory> auto trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::submit () const inline
Submit a program execution on this queue.
Todo:
SUBMIT
Parameters
Tile is the description of the program tiles to instantiate. By default each tile will run an empty program.
Memory is the description of the machine memory modules. By default the machine has empty memory modules.
\fixme implement a real queue with lifetime support because here it assume the device will last...
Definition at line 106 of file queue.hpp.
                      {
    return queue_waiter { std::async(std::launch::async,
                                     /** \fixme implement a real queue with
                                        lifetime support because here it assume
                                        the device will last... */
                                     [*this] { this->run<Tile, Memory>(); }) };
  }
uniform_run() [1/2]
template<typename AIEDevice > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::uniform_run (Invocable && f) const inline
Run synchronously a uniform invocable on this queue.
Parameters
f is an invocable taking a uniform tile handler
Definition at line 84 of file queue.hpp.
{
    aie_d.for_each_tile(
        [work = std::forward<Invocable>(f)](auto& t) {
          t.single_task(work);
        });
    wait();
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d, and trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::wait().
uniform_run() [2/2]
template<typename AIEDevice > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::uniform_run (Invocable && f) const inline
Run synchronously a uniform invocable on this queue.
Parameters
f is an invocable taking a uniform tile handler
Definition at line 84 of file queue.hpp.
{
    aie_d.for_each_tile(
        [work = std::forward<Invocable>(f)](auto& t) {
          t.single_task(work);
        });
    wait();
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d, and trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::wait().
wait() [1/2]
template<typename AIEDevice > void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::wait () const inline
Wait for all the device tiles on this queue to finish.
Definition at line 76 of file queue.hpp.
                    {
    aie_d.for_each_tile([](auto& t) { t.wait(); });
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d.
Referenced by trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::uniform_run().
wait() [2/2]
template<typename AIEDevice > void trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::wait () const inline
Wait for all the device tiles on this queue to finish.
Definition at line 76 of file queue.hpp.
                    {
    aie_d.for_each_tile([](auto& t) { t.wait(); });
  }
References trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d.
Member Data Documentation
aie_d
template<typename AIEDevice > device& trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::aie_d
Todo:
Why using a reference since now a device is a shared_ptr?
Todo:
Why using a reference since now a device is a shared_ptr?
Definition at line 36 of file queue.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::run(), trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::uniform_run(), and trisycl::vendor::xilinx::acap::aie::queue< AIEDevice >::wait().
trisycl::vendor::xilinx::acap::aie::shim_tile
class trisycl::vendor::xilinx::acap::aie::shim_tile
template<typename AIEDevice>
class trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >
The AI Engine shim tile infrastructure.
Parameters
AIE is the type representing the full CGRA with the programs and memory contents
Todo:
Assume only AIE Shim PL tiles for now
Parameters
AIE is the type representing the full CGRA with the programs and memory contents
Todo:
Assume only AIE Shim PL tiles for now
Definition at line 32 of file shim_tile.hpp.
Public Member Functions
shim_tile ()
Construct the shim tile infrastructure.
void start (int x, ::trisycl::detail::fiber_pool &fiber_executor)
Start the shim tile infrastructure associated to the AIE device.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the output router port of the AXI stream switch.
auto & bli_in_connection (int port)
Get the BLI input connection from the shim tile.
auto & bli_out_connection (int port)
Get the BLI output connection to the shim tile.
auto & bli_in (int port)
Get the BLI (Boundary Logic Interface) input port from the PL (Programmable Logic in the FPGA) to read data from.
auto & bli_out (int port)
Get the BLI (Boundary Logic Interface) output port to the PL (Programmable Logic in the FPGA) to write data to.
void connect (typename geo::shim_axi_stream_switch::slave_port_layout sp, typename geo::shim_axi_stream_switch::master_port_layout mp)
Configure a connection of the shim tile AXI stream switch.
shim_tile ()
Construct the shim tile infrastructure.
void start (int x, ::trisycl::detail::fiber_pool &fiber_executor)
Start the shim tile infrastructure associated to the AIE device.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the output router port of the AXI stream switch.
auto & bli_in_connection (int port)
Get the BLI input connection from the shim tile.
auto & bli_out_connection (int port)
Get the BLI output connection to the shim tile.
auto & bli_in (int port)
Get the BLI (Boundary Logic Interface) input port from the PL (Programmable Logic in the FPGA) to read data from.
auto & bli_out (int port)
Get the BLI (Boundary Logic Interface) output port to the PL (Programmable Logic in the FPGA) to write data to.
void connect (typename geo::shim_axi_stream_switch::slave_port_layout sp, typename geo::shim_axi_stream_switch::master_port_layout mp)
Configure a connection of the shim tile AXI stream switch.
Static Public Member Functions
static auto translate_input_port (int port)
Map the input BLI id/port to the shim AXI stream switch port.
static auto translate_output_port (int port)
Map the input BLI id/port to the shim AXI stream switch port.
static auto translate_input_port (int port)
Map the input BLI id/port to the shim AXI stream switch port.
static auto translate_output_port (int port)
Map the input BLI id/port to the shim AXI stream switch port.
Private Types
using geo = typename AIEDevice::geo
using axi_ss_geo = typename geo::shim_axi_stream_switch
using mpl = typename axi_ss_geo::master_port_layout
using spl = typename axi_ss_geo::slave_port_layout
using axi_ss_t = axi_stream_switch< axi_ss_geo >
using geo = typename AIEDevice::geo
using axi_ss_geo = typename geo::shim_axi_stream_switch
using mpl = typename axi_ss_geo::master_port_layout
using spl = typename axi_ss_geo::slave_port_layout
using axi_ss_t = axi_stream_switch< axi_ss_geo >
Private Attributes
int x_coordinate
Keep the horizontal coordinate for debug purpose.
int y_coordinate = -1
axi_ss_t axi_ss
The AXI stream switch of the core tile.
std::future< void > future_work
Keep track of the std::thread execution in this tile.
Member Typedef Documentation
axi_ss_geo [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss_geo = typename geo::shim_axi_stream_switch private
Definition at line 34 of file shim_tile.hpp.
axi_ss_geo [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss_geo = typename geo::shim_axi_stream_switch private
Definition at line 34 of file shim_tile.hpp.
axi_ss_t [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss_t = axi_stream_switch<axi_ss_geo> private
Definition at line 37 of file shim_tile.hpp.
axi_ss_t [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss_t = axi_stream_switch<axi_ss_geo> private
Definition at line 37 of file shim_tile.hpp.
geo [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::geo = typename AIEDevice::geo private
Definition at line 33 of file shim_tile.hpp.
geo [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::geo = typename AIEDevice::geo private
Definition at line 33 of file shim_tile.hpp.
mpl [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::mpl = typename axi_ss_geo::master_port_layout private
Definition at line 35 of file shim_tile.hpp.
mpl [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::mpl = typename axi_ss_geo::master_port_layout private
Definition at line 35 of file shim_tile.hpp.
spl [1/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::spl = typename axi_ss_geo::slave_port_layout private
Definition at line 36 of file shim_tile.hpp.
spl [2/2]
template<typename AIEDevice > using trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::spl = typename axi_ss_geo::slave_port_layout private
Definition at line 36 of file shim_tile.hpp.
Constructor & Destructor Documentation
shim_tile() [1/2]
template<typename AIEDevice > trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::shim_tile () inline
Construct the shim tile infrastructure.
Definition at line 63 of file shim_tile.hpp.
              {
    // Connect the core receivers to its AXI stream switch
    for (auto p : axi_ss_geo::m_south_range)
      output(p) = std::make_shared<port_receiver<axi_ss_t>>
        (axi_ss, "BLI_shim_receiver");
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::output(), and p.
shim_tile() [2/2]
template<typename AIEDevice > trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::shim_tile () inline
Construct the shim tile infrastructure.
Definition at line 63 of file shim_tile.hpp.
              {
    // Connect the core receivers to its AXI stream switch
    for (auto p : axi_ss_geo::m_south_range)
      output(p) = std::make_shared<port_receiver<axi_ss_t>>
        (axi_ss, "BLI_shim_receiver");
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::output(), and p.
Member Function Documentation
bli_in() [1/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in (int port) inline
Get the BLI (Boundary Logic Interface) input port from the PL (Programmable Logic in the FPGA) to read data from.
Parameters
[in] port is the BLI id/port to use
Definition at line 155 of file shim_tile.hpp.
{
    return *bli_in_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in_connection().
bli_in() [2/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in (int port) inline
Get the BLI (Boundary Logic Interface) input port from the PL (Programmable Logic in the FPGA) to read data from.
Parameters
[in] port is the BLI id/port to use
Definition at line 155 of file shim_tile.hpp.
{
    return *bli_in_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in_connection().
bli_in_connection() [1/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in_connection (int port) inline
Get the BLI input connection from the shim tile.
Parameters
[in] port is the BLI id/port to use
Definition at line 133 of file shim_tile.hpp.
{
    // The input is actually the output of the switch
    return axi_ss.out_connection(translate_output_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::out_connection(), and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_output_port().
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in().
bli_in_connection() [2/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in_connection (int port) inline
Get the BLI input connection from the shim tile.
Parameters
[in] port is the BLI id/port to use
Definition at line 133 of file shim_tile.hpp.
{
    // The input is actually the output of the switch
    return axi_ss.out_connection(translate_output_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::out_connection(), and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_output_port().
bli_out() [1/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out (int port) inline
Get the BLI (Boundary Logic Interface) output port to the PL (Programmable Logic in the FPGA) to write data to.
Parameters
[in] port is the BLI id/port to use
Definition at line 165 of file shim_tile.hpp.
{
    return *bli_out_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out_connection().
bli_out() [2/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out (int port) inline
Get the BLI (Boundary Logic Interface) output port to the PL (Programmable Logic in the FPGA) to write data to.
Parameters
[in] port is the BLI id/port to use
Definition at line 165 of file shim_tile.hpp.
{
    return *bli_out_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out_connection().
bli_out_connection() [1/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out_connection (int port) inline
Get the BLI output connection to the shim tile.
Parameters
[in] port is the BLI id/port to use
Definition at line 143 of file shim_tile.hpp.
{
    // The output is actually the input of the switch
    return axi_ss.in_connection(translate_input_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::in_connection(), and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_input_port().
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out().
bli_out_connection() [2/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out_connection (int port) inline
Get the BLI output connection to the shim tile.
Parameters
[in] port is the BLI id/port to use
Definition at line 143 of file shim_tile.hpp.
{
    // The output is actually the input of the switch
    return axi_ss.in_connection(translate_input_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::in_connection(), and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_input_port().
connect() [1/2]
template<typename AIEDevice > void trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::connect (typename geo::shim_axi_stream_switch::slave_port_layout sp, typename geo::shim_axi_stream_switch::master_port_layout mp) inline
Configure a connection of the shim tile AXI stream switch.
Definition at line 171 of file shim_tile.hpp.
{
    axi_ss.connect(sp, mp);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::connect().
connect() [2/2]
template<typename AIEDevice > void trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::connect (typename geo::shim_axi_stream_switch::slave_port_layout sp, typename geo::shim_axi_stream_switch::master_port_layout mp) inline
Configure a connection of the shim tile AXI stream switch.
Definition at line 171 of file shim_tile.hpp.
{
    axi_ss.connect(sp, mp);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::connect().
input() [1/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::input (spl p) inline
Get the input router port of the AXI stream switch.
Todo:
Factorize some code between core tile and shim tile
Parameters
p is the slave_port_layout for the stream
Definition at line 92 of file shim_tile.hpp.
                     {
    // No index validation required because of type safety
    return axi_ss.input(p);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input(), and p.
input() [2/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::input (spl p) inline
Get the input router port of the AXI stream switch.
Todo:
Factorize some code between core tile and shim tile
Parameters
p is the slave_port_layout for the stream
Definition at line 92 of file shim_tile.hpp.
                     {
    // No index validation required because of type safety
    return axi_ss.input(p);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input(), and p.
output() [1/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::output (mpl p) inline
Get the output router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 102 of file shim_tile.hpp.
                      {
    // No index validation required because of type safety
    return axi_ss.output(p);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output(), and p.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::shim_tile().
output() [2/2]
template<typename AIEDevice > auto & trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::output (mpl p) inline
Get the output router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 102 of file shim_tile.hpp.
                      {
    // No index validation required because of type safety
    return axi_ss.output(p);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output(), and p.
start() [1/2]
template<typename AIEDevice > void trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::start (int x, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the shim tile infrastructure associated to the AIE device.
Parameters
[in] x is the horizontal coordinate for this tile
[in] fiber_executor is the executor used to run infrastructure details
Definition at line 78 of file shim_tile.hpp.
{
    x_coordinate = x;
#if TRISYCL_XILINX_AIE_TILE_CODE_ON_FIBER
    fe = &fiber_executor;
#endif
    axi_ss.start(x, -1, fiber_executor);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::start(), x, and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::x_coordinate.
start() [2/2]
template<typename AIEDevice > void trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::start (int x, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the shim tile infrastructure associated to the AIE device.
Parameters
[in] x is the horizontal coordinate for this tile
[in] fiber_executor is the executor used to run infrastructure details
Definition at line 78 of file shim_tile.hpp.
{
    x_coordinate = x;
#if TRISYCL_XILINX_AIE_TILE_CODE_ON_FIBER
    fe = &fiber_executor;
#endif
    axi_ss.start(x, -1, fiber_executor);
  }
References trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::start(), x, and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::x_coordinate.
translate_input_port() [1/2]
template<typename AIEDevice > static auto trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_input_port (int port) inline static
Map the input BLI id/port to the shim AXI stream switch port.
Parameters
[in] port is the BLI id/port to use
Definition at line 112 of file shim_tile.hpp.
{
    return axi_ss_t::translate_port(port, spl::south_0, spl::south_last,
                                    "The BLI input port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out_connection().
translate_input_port() [2/2]
template<typename AIEDevice > static auto trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_input_port (int port) inline static
Map the input BLI id/port to the shim AXI stream switch port.
Parameters
[in] port is the BLI id/port to use
Definition at line 112 of file shim_tile.hpp.
{
    return axi_ss_t::translate_port(port, spl::south_0, spl::south_last,
                                    "The BLI input port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
translate_output_port() [1/2]
template<typename AIEDevice > static auto trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_output_port (int port) inline static
Map the input BLI id/port to the shim AXI stream switch port.
Parameters
[in] port is the BLI id/port to use
Definition at line 122 of file shim_tile.hpp.
{
    return axi_ss_t::translate_port(port, mpl::south_0, mpl::south_last,
                                    "The BLI output port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in_connection().
translate_output_port() [2/2]
template<typename AIEDevice > static auto trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::translate_output_port (int port) inline static
Map the input BLI id/port to the shim AXI stream switch port.
Parameters
[in] port is the BLI id/port to use
Definition at line 122 of file shim_tile.hpp.
{
    return axi_ss_t::translate_port(port, mpl::south_0, mpl::south_last,
                                    "The BLI output port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
Member Data Documentation
axi_ss
template<typename AIEDevice > axi_ss_t trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::axi_ss private
The AXI stream switch of the core tile.
Definition at line 47 of file shim_tile.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_in_connection(), trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::bli_out_connection(), trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::connect(), trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::input(), trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::output(), trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::shim_tile(), and trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::start().
future_work
template<typename AIEDevice > std::future< void > trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::future_work private
Keep track of the std::thread execution in this tile.
Definition at line 57 of file shim_tile.hpp.
x_coordinate
template<typename AIEDevice > int trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::x_coordinate private
Keep the horizontal coordinate for debug purpose.
Definition at line 40 of file shim_tile.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::start().
y_coordinate
template<typename AIEDevice > int trisycl::vendor::xilinx::acap::aie::shim_tile< AIEDevice >::y_coordinate = -1 private
Todo:
Remove? Keep the vertical coordinate for debug purpose
Todo:
Remove? Keep the vertical coordinate for debug purpose
Definition at line 44 of file shim_tile.hpp.
trisycl::vendor::xilinx::acap::aie::tile
struct trisycl::vendor::xilinx::acap::aie::tile
template<typename AIE_Program, int X, int Y>
struct trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >
The AI Engine tile infrastructure defining the program of a tile.
This is the type you need to inherit from to define the program of a CGRA tile.
Parameters
AIE_Program is the type representing the full CGRA with the programs and memory contents
X is the horizontal coordinate of the memory module
Y is the vertical coordinate of the memory module
Todo:
(Andrew Gozillon) FYI, until Intel fix the way they handle base classes in the SYCL compiler frontend this tile_base can never have non-default constructed data (on the device side implementation, the host should be fine to have whatever). As the hack I have in place just now only outlines a call to the base classes default constructor, it might be feasible to work around that though by calling a base class "fill" function in the tile constructor or tweaking the way the run function of a tile is outlined so that it outlines it as a copy of the full object rather than components of the object and reconstructing it inside the kernel (although you'll fall into the standard layout trap as you'll be passing a full object to the kernel invocation and it'd take some reworking of the Tile's main generation).
A proper fix for this is probably quite difficult as you'd need to take into account the base classes dependencies among-st other things like the constructor body not being available in the same TU, some discussion here: https://github.com/intel/llvm/issues/488
This is the type you need to inherit from to define the program of a CGRA tile.
Parameters
AIE_Program is the type representing the full CGRA with the programs and memory contents
X is the horizontal coordinate of the memory module
Y is the vertical coordinate of the memory module
Todo:
(Andrew Gozillon) FYI, until Intel fix the way they handle base classes in the SYCL compiler frontend this tile_base can never have non-default constructed data (on the device side implementation, the host should be fine to have whatever). As the hack I have in place just now only outlines a call to the base classes default constructor, it might be feasible to work around that though by calling a base class "fill" function in the tile constructor or tweaking the way the run function of a tile is outlined so that it outlines it as a copy of the full object rather than components of the object and reconstructing it inside the kernel (although you'll fall into the standard layout trap as you'll be passing a full object to the kernel invocation and it'd take some reworking of the Tile's main generation).
A proper fix for this is probably quite difficult as you'd need to take into account the base classes dependencies among-st other things like the constructor body not being available in the same TU, some discussion here: https://github.com/intel/llvm/issues/488
Definition at line 57 of file tile.hpp.
Public Types
using geo = typename AIE_Program::geo
The geography of the CGRA.
using tb = tile_base< AIE_Program >
Shortcut to the tile base class.
using mem_t = typename AIE_Program::template tileable_memory< x, y >
The type of the memory module native to the tile.
using geo = typename AIE_Program::geo
The geography of the CGRA.
using tb = tile_base< AIE_Program >
Shortcut to the tile base class.
using mem_t = typename AIE_Program::template tileable_memory< x, y >
The type of the memory module native to the tile.
Public Member Functions
auto & mem_west ()
Get the memory module on the West if it does exist.
auto & mem_east ()
Get the memory module on the East if it does exist.
auto & mem_south ()
Get the memory module on the South if it does exist.
auto & mem_north ()
Get the memory module on the North if it does exist.
auto & mem ()
The memory module native to the tile.
template<int Dx, int Dy>
auto & mem ()
Get the memory module relative to the tile.
template<typename T >
auto get_cascade_stream_in ()
Get a read accessor to the cascade stream input.
template<typename T >
auto get_cascade_stream_out ()
Get a write accessor to the cascade stream output.
void horizontal_barrier (int lock=14)
An horizontal barrier using a lock.
void vertical_barrier (int lock=15)
A vertical barrier using a lock.
void barrier ()
Full barrier using the 2 locks by default.
auto rx_dma (int port)
Get access on a receiver DMA.
auto tx_dma (int port)
Get access on a transmit DMA.
auto & mem_west ()
Get the memory module on the West if it does exist.
auto & mem_east ()
Get the memory module on the East if it does exist.
auto & mem_south ()
Get the memory module on the South if it does exist.
auto & mem_north ()
Get the memory module on the North if it does exist.
auto & mem ()
The memory module native to the tile.
template<int Dx, int Dy>
auto & mem ()
Get the memory module relative to the tile.
template<typename T >
auto get_cascade_stream_in ()
Get a read accessor to the cascade stream input.
template<typename T >
auto get_cascade_stream_out ()
Get a write accessor to the cascade stream output.
void horizontal_barrier (int lock=14)
An horizontal barrier using a lock.
void vertical_barrier (int lock=15)
A vertical barrier using a lock.
void barrier ()
Full barrier using the 2 locks by default.
auto rx_dma (int port)
Get access on a receiver DMA.
auto tx_dma (int port)
Get access on a transmit DMA.
Public Member Functions inherited from trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >
void run ()
Provide a run member function that does nothing so it is possible to write a minimum AI Engine program that does nothing.
template<typename Work >
void single_task (Work &&f)
Submit a callable on this tile.
void wait ()
Wait for the execution of the callable on this tile.
auto & cascade ()
Access the cascade connections.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
void set_program (AIE_Program &p)
Store a way to access to the program.
void set_tile_infrastructure (tile_infrastructure< geo > t)
Store a way to access to hardware infrastructure of the tile.
void run ()
Provide a run member function that does nothing so it is possible to write a minimum AI Engine program that does nothing.
template<typename Work >
void single_task (Work &&f)
Submit a callable on this tile.
void wait ()
Wait for the execution of the callable on this tile.
auto & cascade ()
Access the cascade connections.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
void set_program (AIE_Program &p)
Store a way to access to the program.
void set_tile_infrastructure (tile_infrastructure< geo > t)
Store a way to access to hardware infrastructure of the tile.
Static Public Member Functions
template<int Dim>
static auto constexpr get_id ()
Return the coordinate of the tile in the given dimension.
static auto constexpr linear_id ()
Return the linearized coordinate of the tile.
static bool constexpr is_west_column ()
Test if the tile is in the Western column.
static bool constexpr is_east_column ()
Test if the tile is in the Eastern column.
static bool constexpr is_south_row ()
Test if the tile is in the Southern row.
static bool constexpr is_north_row ()
Test if the tile is in the Northern row.
static bool constexpr is_west_valid ()
Test if the tile has a Western neighbor.
static bool constexpr is_east_valid ()
Test if the tile has a Eastern neighbor.
static bool constexpr is_south_valid ()
Test if the tile has a Southern neighbor.
static bool constexpr is_south_west_valid ()
Test if the tile has a South West neighbor.
static bool constexpr is_south_east_valid ()
Test if the tile has a South East neighbor.
static bool constexpr is_north_valid ()
Test if the tile has a Northern neighbor.
static bool constexpr is_north_east_valid ()
Test if the tile has a North East neighbor.
static bool constexpr is_north_west_valid ()
Test if the tile has a North West neighbor.
static bool constexpr is_memory_module (int dx, int dy)
Test if a memory module exists and is connected to this tile.
static bool constexpr is_memory_module_west ()
Test if a memory module exists on the West of this tile.
static bool constexpr is_memory_module_east ()
Test if a memory module exists on the East of this tile.
static bool constexpr is_memory_module_south ()
Test if a memory module exists on the South this tile.
static bool constexpr is_memory_module_north ()
Test if a memory module exists on the North this tile.
static auto constexpr memory_module_linear_id (int dx, int dy)
Compute the linear id of a memory module attached to this tile.
static bool constexpr is_cascade_start ()
Test if this tile owns the start of the cascade_stream.
static bool constexpr is_cascade_end ()
Test if this tile owns the end of the cascade_stream.
static auto constexpr cascade_linear_id ()
Compute the linearized coordinate of a tile along the cascade stream.
template<int Dim>
static auto constexpr get_id ()
Return the coordinate of the tile in the given dimension.
static auto constexpr linear_id ()
Return the linearized coordinate of the tile.
static bool constexpr is_west_column ()
Test if the tile is in the Western column.
static bool constexpr is_east_column ()
Test if the tile is in the Eastern column.
static bool constexpr is_south_row ()
Test if the tile is in the Southern row.
static bool constexpr is_north_row ()
Test if the tile is in the Northern row.
static bool constexpr is_west_valid ()
Test if the tile has a Western neighbor.
static bool constexpr is_east_valid ()
Test if the tile has a Eastern neighbor.
static bool constexpr is_south_valid ()
Test if the tile has a Southern neighbor.
static bool constexpr is_south_west_valid ()
Test if the tile has a South West neighbor.
static bool constexpr is_south_east_valid ()
Test if the tile has a South East neighbor.
static bool constexpr is_north_valid ()
Test if the tile has a Northern neighbor.
static bool constexpr is_north_east_valid ()
Test if the tile has a North East neighbor.
static bool constexpr is_north_west_valid ()
Test if the tile has a North West neighbor.
static bool constexpr is_memory_module (int dx, int dy)
Test if a memory module exists and is connected to this tile.
static bool constexpr is_memory_module_west ()
Test if a memory module exists on the West of this tile.
static bool constexpr is_memory_module_east ()
Test if a memory module exists on the East of this tile.
static bool constexpr is_memory_module_south ()
Test if a memory module exists on the South this tile.
static bool constexpr is_memory_module_north ()
Test if a memory module exists on the North this tile.
static auto constexpr memory_module_linear_id (int dx, int dy)
Compute the linear id of a memory module attached to this tile.
static bool constexpr is_cascade_start ()
Test if this tile owns the start of the cascade_stream.
static bool constexpr is_cascade_end ()
Test if this tile owns the end of the cascade_stream.
static auto constexpr cascade_linear_id ()
Compute the linearized coordinate of a tile along the cascade stream.
Static Public Attributes
static auto constexpr x = X
The horizontal tile coordinates in the CGRA grid (starting at 0 and increasing towards the East)
static auto constexpr y = Y
The vertical tile coordinates in the CGRA grid (starting at increasing towards the North)
Additional Inherited Members
Protected Attributes inherited from trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >
AIE_Program * program
Keep a reference to the AIE_Program with the full tile and memory view.
tile_infrastructure< geo > ti
Keep a reference to the tile_infrastructure hardware features.
Member Typedef Documentation
geo [1/2]
template<typename AIE_Program , int X, int Y> using trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::geo = typename AIE_Program::geo
The geography of the CGRA.
Definition at line 66 of file tile.hpp.
geo [2/2]
template<typename AIE_Program , int X, int Y> using trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::geo = typename AIE_Program::geo
The geography of the CGRA.
Definition at line 66 of file tile.hpp.
mem_t [1/2]
template<typename AIE_Program , int X, int Y> using trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_t = typename AIE_Program::template tileable_memory<x, y>
The type of the memory module native to the tile.
Definition at line 298 of file tile.hpp.
mem_t [2/2]
template<typename AIE_Program , int X, int Y> using trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_t = typename AIE_Program::template tileable_memory<x, y>
The type of the memory module native to the tile.
Definition at line 298 of file tile.hpp.
tb [1/2]
template<typename AIE_Program , int X, int Y> using trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::tb = tile_base<AIE_Program>
Shortcut to the tile base class.
Definition at line 69 of file tile.hpp.
tb [2/2]
template<typename AIE_Program , int X, int Y> using trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::tb = tile_base<AIE_Program>
Shortcut to the tile base class.
Definition at line 69 of file tile.hpp.
Member Function Documentation
barrier() [1/2]
template<typename AIE_Program , int X, int Y> void trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::barrier () inline
Full barrier using the 2 locks by default.
Implement a barrier across the full program by using horizontal_barrier() and vertical_barrier().
Definition at line 430 of file tile.hpp.
                 {
    horizontal_barrier();
    vertical_barrier();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier().
barrier() [2/2]
template<typename AIE_Program , int X, int Y> void trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::barrier () inline
Full barrier using the 2 locks by default.
Implement a barrier across the full program by using horizontal_barrier() and vertical_barrier().
Definition at line 430 of file tile.hpp.
                 {
    horizontal_barrier();
    vertical_barrier();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier().
cascade_linear_id() [1/2]
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::cascade_linear_id () inline static constexpr
Compute the linearized coordinate of a tile along the cascade stream.
Definition at line 315 of file tile.hpp.
{
    return geo::cascade_linear_id(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
cascade_linear_id() [2/2]
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::cascade_linear_id () inline static constexpr
Compute the linearized coordinate of a tile along the cascade stream.
Definition at line 315 of file tile.hpp.
{
    return geo::cascade_linear_id(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
get_cascade_stream_in() [1/2]
template<typename AIE_Program , int X, int Y> template<typename T > auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_in () inline
Get a read accessor to the cascade stream input.
Parameters
T is the data type used to read from the cascade stream pipe
Target is the access mode to the pipe. It is blocking by default
Definition at line 329 of file tile.hpp.
{
    static_assert(!is_cascade_start(), "You cannot access to the cascade stream"
                  " input on the tile that starts the stream");
    return tb::cascade().template get_cascade_stream_in<T>(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::cascade(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_start(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
get_cascade_stream_in() [2/2]
template<typename AIE_Program , int X, int Y> template<typename T > auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_in () inline
Get a read accessor to the cascade stream input.
Parameters
T is the data type used to read from the cascade stream pipe
Target is the access mode to the pipe. It is blocking by default
Definition at line 329 of file tile.hpp.
{
    static_assert(!is_cascade_start(), "You cannot access to the cascade stream"
                  " input on the tile that starts the stream");
    return tb::cascade().template get_cascade_stream_in<T>(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::cascade(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_start(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
get_cascade_stream_out() [1/2]
template<typename AIE_Program , int X, int Y> template<typename T > auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_out () inline
Get a write accessor to the cascade stream output.
Parameters
T is the data type used to write to the cascade stream pipe
Target is the access mode to the pipe. It is blocking by default
Definition at line 345 of file tile.hpp.
{
    static_assert(!is_cascade_end(), "You cannot access to the cascade stream"
                  " output on the tile that starts the stream");
    return tb::cascade().template get_cascade_stream_out<T>(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::cascade(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_end(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
get_cascade_stream_out() [2/2]
template<typename AIE_Program , int X, int Y> template<typename T > auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_out () inline
Get a write accessor to the cascade stream output.
Parameters
T is the data type used to write to the cascade stream pipe
Target is the access mode to the pipe. It is blocking by default
Definition at line 345 of file tile.hpp.
{
    static_assert(!is_cascade_end(), "You cannot access to the cascade stream"
                  " output on the tile that starts the stream");
    return tb::cascade().template get_cascade_stream_out<T>(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::cascade(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_end(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
get_id() [1/2]
template<typename AIE_Program , int X, int Y> template<int Dim> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_id () inline static constexpr
Return the coordinate of the tile in the given dimension.
Parameters
Dim is 0 for the horizontal (x) dimension and 1 for the vertical (y) dimension
Definition at line 78 of file tile.hpp.
{
    static_assert(0 <= Dim && Dim <= 1,
                  "The dimension has to be between 0 and 1");
    if constexpr (Dim == 0)
      return x;
    else
      return y;
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
get_id() [2/2]
template<typename AIE_Program , int X, int Y> template<int Dim> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_id () inline static constexpr
Return the coordinate of the tile in the given dimension.
Parameters
Dim is 0 for the horizontal (x) dimension and 1 for the vertical (y) dimension
Definition at line 78 of file tile.hpp.
{
    static_assert(0 <= Dim && Dim <= 1,
                  "The dimension has to be between 0 and 1");
    if constexpr (Dim == 0)
      return x;
    else
      return y;
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
horizontal_barrier() [1/2]
template<typename AIE_Program , int X, int Y> void trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier (int lock = 14) inline
An horizontal barrier using a lock.
Implement a barrier across the tiles a line.
Parameters
[in] lock is the ME lock to use. The lock 14 is used by default
Definition at line 359 of file tile.hpp.
{
    if constexpr (y & 1) {
      // Propagate a token from West to East and back
      if constexpr (!is_west_column()) {
        // Wait for the Western neighbour to be ready
        mem().lock(lock).acquire_with_value(true);
      }
      if constexpr (is_memory_module_east()) {
        mem_east().lock(lock).acquire_with_value(false);
        // Unleash the Eastern neighbour
        mem_east().lock(lock).release_with_value(true);
        // Wait for the Eastern neighbour to acknowledge
        mem_east().lock(lock).acquire_with_value(false);
       }
      if constexpr (!is_west_column()) {
        // Acknowledge to the Western neighbour
        mem().lock(lock).release_with_value(false);
      }
    } else {
      // Propagate a token from East to West and back
      if constexpr (!is_east_column()) {
        // Wait for the Eastern neighbour to be ready
        mem().lock(lock).acquire_with_value(true);
      }
      if constexpr (is_memory_module_west()) {
        mem_west().lock(lock).acquire_with_value(false);
        // Unleash the Western neighbour
        mem_west().lock(lock).release_with_value(true);
        // Wait for the Western neighbour to acknowledge
        mem_west().lock(lock).acquire_with_value(false);
       }
      if constexpr (!is_east_column()) {
        // Acknowledge to the Eastern neighbour
        mem().lock(lock).release_with_value(false);
      }
    }
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_column(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_west(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_column(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::barrier().
horizontal_barrier() [2/2]
template<typename AIE_Program , int X, int Y> void trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier (int lock = 14) inline
An horizontal barrier using a lock.
Implement a barrier across the tiles a line.
Parameters
[in] lock is the ME lock to use. The lock 14 is used by default
Definition at line 359 of file tile.hpp.
{
    if constexpr (y & 1) {
      // Propagate a token from West to East and back
      if constexpr (!is_west_column()) {
        // Wait for the Western neighbour to be ready
        mem().lock(lock).acquire_with_value(true);
      }
      if constexpr (is_memory_module_east()) {
        mem_east().lock(lock).acquire_with_value(false);
        // Unleash the Eastern neighbour
        mem_east().lock(lock).release_with_value(true);
        // Wait for the Eastern neighbour to acknowledge
        mem_east().lock(lock).acquire_with_value(false);
       }
      if constexpr (!is_west_column()) {
        // Acknowledge to the Western neighbour
        mem().lock(lock).release_with_value(false);
      }
    } else {
      // Propagate a token from East to West and back
      if constexpr (!is_east_column()) {
        // Wait for the Eastern neighbour to be ready
        mem().lock(lock).acquire_with_value(true);
      }
      if constexpr (is_memory_module_west()) {
        mem_west().lock(lock).acquire_with_value(false);
        // Unleash the Western neighbour
        mem_west().lock(lock).release_with_value(true);
        // Wait for the Western neighbour to acknowledge
        mem_west().lock(lock).acquire_with_value(false);
       }
      if constexpr (!is_east_column()) {
        // Acknowledge to the Eastern neighbour
        mem().lock(lock).release_with_value(false);
      }
    }
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_column(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_west(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_column(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_cascade_end() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_end () inline static constexpr
Test if this tile owns the end of the cascade_stream.
Definition at line 308 of file tile.hpp.
{
    return geo::is_cascade_end(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_out().
is_cascade_end() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_end () inline static constexpr
Test if this tile owns the end of the cascade_stream.
Definition at line 308 of file tile.hpp.
{
    return geo::is_cascade_end(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_cascade_start() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_start () inline static constexpr
Test if this tile owns the start of the cascade_stream.
Definition at line 302 of file tile.hpp.
{
    return geo::is_cascade_start(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_in().
is_cascade_start() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_start () inline static constexpr
Test if this tile owns the start of the cascade_stream.
Definition at line 302 of file tile.hpp.
{
    return geo::is_cascade_start(x, y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_east_column() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_column () inline static constexpr
Test if the tile is in the Eastern column.
Definition at line 110 of file tile.hpp.
{
    return geo::is_east_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier().
is_east_column() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_column () inline static constexpr
Test if the tile is in the Eastern column.
Definition at line 110 of file tile.hpp.
{
    return geo::is_east_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
is_east_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_valid () inline static constexpr
Test if the tile has a Eastern neighbor.
Definition at line 134 of file tile.hpp.
{
    return !geo::is_east_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_east_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_east_valid().
is_east_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_valid () inline static constexpr
Test if the tile has a Eastern neighbor.
Definition at line 134 of file tile.hpp.
{
    return !geo::is_east_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
is_memory_module() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module (int dx, int dy) inline static constexpr
Test if a memory module exists and is connected to this tile.
Parameters
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 181 of file tile.hpp.
{
    return geo::is_memory_module(x, y, dx, dy);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_north(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_south(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_west().
is_memory_module() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module (int dx, int dy) inline static constexpr
Test if a memory module exists and is connected to this tile.
Parameters
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 181 of file tile.hpp.
{
    return geo::is_memory_module(x, y, dx, dy);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_memory_module_east() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_east () inline static constexpr
Test if a memory module exists on the East of this tile.
Definition at line 193 of file tile.hpp.
{
    return is_memory_module(1, 0);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east().
is_memory_module_east() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_east () inline static constexpr
Test if a memory module exists on the East of this tile.
Definition at line 193 of file tile.hpp.
{
    return is_memory_module(1, 0);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
is_memory_module_north() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_north () inline static constexpr
Test if a memory module exists on the North this tile.
Definition at line 205 of file tile.hpp.
{
    return is_memory_module(0, 1);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier().
is_memory_module_north() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_north () inline static constexpr
Test if a memory module exists on the North this tile.
Definition at line 205 of file tile.hpp.
{
    return is_memory_module(0, 1);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
is_memory_module_south() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_south () inline static constexpr
Test if a memory module exists on the South this tile.
Definition at line 199 of file tile.hpp.
{
    return is_memory_module(0, -1);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_south().
is_memory_module_south() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_south () inline static constexpr
Test if a memory module exists on the South this tile.
Definition at line 199 of file tile.hpp.
{
    return is_memory_module(0, -1);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
is_memory_module_west() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_west () inline static constexpr
Test if a memory module exists on the West of this tile.
Definition at line 187 of file tile.hpp.
{
    return is_memory_module(-1, 0);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west().
is_memory_module_west() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_west () inline static constexpr
Test if a memory module exists on the West of this tile.
Definition at line 187 of file tile.hpp.
{
    return is_memory_module(-1, 0);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module().
is_north_east_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_east_valid () inline static constexpr
Test if the tile has a North East neighbor.
Definition at line 164 of file tile.hpp.
{
    return is_north_valid() && is_east_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_valid().
is_north_east_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_east_valid () inline static constexpr
Test if the tile has a North East neighbor.
Definition at line 164 of file tile.hpp.
{
    return is_north_valid() && is_east_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_valid().
is_north_row() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_row () inline static constexpr
Test if the tile is in the Northern row.
Definition at line 122 of file tile.hpp.
{
    return geo::is_north_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_north_row() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_row () inline static constexpr
Test if the tile is in the Northern row.
Definition at line 122 of file tile.hpp.
{
    return geo::is_north_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_north_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_valid () inline static constexpr
Test if the tile has a Northern neighbor.
Definition at line 158 of file tile.hpp.
{
    return !geo::is_north_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_east_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_west_valid().
is_north_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_valid () inline static constexpr
Test if the tile has a Northern neighbor.
Definition at line 158 of file tile.hpp.
{
    return !geo::is_north_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_north_west_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_west_valid () inline static constexpr
Test if the tile has a North West neighbor.
Definition at line 170 of file tile.hpp.
{
    return is_north_valid() && is_west_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_valid().
is_north_west_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_west_valid () inline static constexpr
Test if the tile has a North West neighbor.
Definition at line 170 of file tile.hpp.
{
    return is_north_valid() && is_west_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_valid().
is_south_east_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_east_valid () inline static constexpr
Test if the tile has a South East neighbor.
Definition at line 152 of file tile.hpp.
{
    return is_south_valid() && is_east_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_valid().
is_south_east_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_east_valid () inline static constexpr
Test if the tile has a South East neighbor.
Definition at line 152 of file tile.hpp.
{
    return is_south_valid() && is_east_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_valid().
is_south_row() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_row () inline static constexpr
Test if the tile is in the Southern row.
Definition at line 116 of file tile.hpp.
{
    return geo::is_south_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier().
is_south_row() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_row () inline static constexpr
Test if the tile is in the Southern row.
Definition at line 116 of file tile.hpp.
{
    return geo::is_south_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_south_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_valid () inline static constexpr
Test if the tile has a Southern neighbor.
Definition at line 140 of file tile.hpp.
{
    return !geo::is_south_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_east_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_west_valid().
is_south_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_valid () inline static constexpr
Test if the tile has a Southern neighbor.
Definition at line 140 of file tile.hpp.
{
    return !geo::is_south_row(y);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
is_south_west_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_west_valid () inline static constexpr
Test if the tile has a South West neighbor.
Definition at line 146 of file tile.hpp.
{
    return is_south_valid() && is_west_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_valid().
is_south_west_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_west_valid () inline static constexpr
Test if the tile has a South West neighbor.
Definition at line 146 of file tile.hpp.
{
    return is_south_valid() && is_west_valid();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_valid().
is_west_column() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_column () inline static constexpr
Test if the tile is in the Western column.
Todo:
Need something more modern than Boost.Operator to implement trisycl::id
Look for example at https://github.com/taocpp/operators/issues/9 static auto constexpr get_id() { return trisycl::id<2> { x, y }; }
Definition at line 104 of file tile.hpp.
{
    return geo::is_west_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier().
is_west_column() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_column () inline static constexpr
Test if the tile is in the Western column.
Todo:
Need something more modern than Boost.Operator to implement trisycl::id
Look for example at https://github.com/taocpp/operators/issues/9 static auto constexpr get_id() { return trisycl::id<2> { x, y }; }
Definition at line 104 of file tile.hpp.
{
    return geo::is_west_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
is_west_valid() [1/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_valid () inline static constexpr
Test if the tile has a Western neighbor.
Definition at line 128 of file tile.hpp.
{
    return !geo::is_west_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_west_valid(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_west_valid().
is_west_valid() [2/2]
template<typename AIE_Program , int X, int Y> static bool constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_valid () inline static constexpr
Test if the tile has a Western neighbor.
Definition at line 128 of file tile.hpp.
{
    return !geo::is_west_column(x);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x.
linear_id() [1/2]
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::linear_id () inline static constexpr
Return the linearized coordinate of the tile.
Definition at line 89 of file tile.hpp.
{
    return geo::linear_id(x, y);
  }
References trisycl::detail::linear_id(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
linear_id() [2/2]
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::linear_id () inline static constexpr
Return the linearized coordinate of the tile.
Definition at line 89 of file tile.hpp.
{
    return geo::linear_id(x, y);
  }
References trisycl::detail::linear_id(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
mem() [1/4]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem () inline
The memory module native to the tile.
Definition at line 260 of file tile.hpp.
              {
    if constexpr (y & 1)
      return mem_west();
    else
      return mem_east();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), trisycl::vendor::xilinx::acap::aie::dma_dsl< Tile, DMA, LockRef >::lock(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier().
mem() [2/4]
template<typename AIE_Program , int X, int Y> template<int Dx, int Dy> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem () inline
Get the memory module relative to the tile.
Parameters
[in] Dx is the horizontal offset relative to the current core tile
[in] Dy is the vertical offset relative to the current core tile
Returns
the memory tile object
Note that since a core tile has a 4-neighbor connectivity, at least one of the offset needs to be 0 and the other to be either 1 or -1.
Definition at line 281 of file tile.hpp.
              {
    static_assert(geo::is_valid_memory_module_offset(Dx, Dy),
                  "Note that since a core tile has a 4-neighbor connectivity,"
                  " one of the offset needs to be 0 and the other to be either"
                  " 1 or -1");
    if constexpr (Dx == -1)
      return mem_west();
    else if constexpr (Dx == 1)
      return mem_east();
    else if constexpr (Dy == -1)
      return mem_south();
    else
      return mem_north();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_south(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west().
mem() [3/4]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem () inline
The memory module native to the tile.
Definition at line 260 of file tile.hpp.
              {
    if constexpr (y & 1)
      return mem_west();
    else
      return mem_east();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
mem() [4/4]
template<typename AIE_Program , int X, int Y> template<int Dx, int Dy> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem () inline
Get the memory module relative to the tile.
Parameters
[in] Dx is the horizontal offset relative to the current core tile
[in] Dy is the vertical offset relative to the current core tile
Returns
the memory tile object
Note that since a core tile has a 4-neighbor connectivity, at least one of the offset needs to be 0 and the other to be either 1 or -1.
Definition at line 281 of file tile.hpp.
              {
    static_assert(geo::is_valid_memory_module_offset(Dx, Dy),
                  "Note that since a core tile has a 4-neighbor connectivity,"
                  " one of the offset needs to be 0 and the other to be either"
                  " 1 or -1");
    if constexpr (Dx == -1)
      return mem_west();
    else if constexpr (Dx == 1)
      return mem_east();
    else if constexpr (Dy == -1)
      return mem_south();
    else
      return mem_north();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_south(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west().
mem_east() [1/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east () inline
Get the memory module on the East if it does exist.
Definition at line 232 of file tile.hpp.
                   {
    static_assert(is_memory_module_east(), "There is no memory module"
                  " on the East of this tile in the Eastern column and"
                  " on an odd row");
    return tb::program->template
      memory_module<memory_module_linear_id(1, 0)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_east(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem().
mem_east() [2/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east () inline
Get the memory module on the East if it does exist.
Definition at line 232 of file tile.hpp.
                   {
    static_assert(is_memory_module_east(), "There is no memory module"
                  " on the East of this tile in the Eastern column and"
                  " on an odd row");
    return tb::program->template
      memory_module<memory_module_linear_id(1, 0)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_east(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
mem_north() [1/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north () inline
Get the memory module on the North if it does exist.
Definition at line 251 of file tile.hpp.
                    {
    static_assert(is_memory_module_north(), "There is no memory module"
                  " above the Northern tile row");
    return tb::program->template
      memory_module<memory_module_linear_id(0, 1)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_north(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier().
mem_north() [2/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north () inline
Get the memory module on the North if it does exist.
Definition at line 251 of file tile.hpp.
                    {
    static_assert(is_memory_module_north(), "There is no memory module"
                  " above the Northern tile row");
    return tb::program->template
      memory_module<memory_module_linear_id(0, 1)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_north(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
mem_south() [1/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_south () inline
Get the memory module on the South if it does exist.
Definition at line 242 of file tile.hpp.
                    {
    static_assert(is_memory_module_south(), "There is no memory module"
                  " below the Southern tile row");
    return tb::program->template
      memory_module<memory_module_linear_id(0, -1)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_south(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem().
mem_south() [2/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_south () inline
Get the memory module on the South if it does exist.
Definition at line 242 of file tile.hpp.
                    {
    static_assert(is_memory_module_south(), "There is no memory module"
                  " below the Southern tile row");
    return tb::program->template
      memory_module<memory_module_linear_id(0, -1)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_south(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
mem_west() [1/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west () inline
Get the memory module on the West if it does exist.
Definition at line 222 of file tile.hpp.
                    {
     static_assert(is_memory_module_west(), "There is no memory module"
                   " on the West of this tile in the Western column and"
                   " on an even row");
     return tb::program->template
       memory_module<memory_module_linear_id(-1, 0)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_west(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem().
mem_west() [2/2]
template<typename AIE_Program , int X, int Y> auto & trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west () inline
Get the memory module on the West if it does exist.
Definition at line 222 of file tile.hpp.
                    {
     static_assert(is_memory_module_west(), "There is no memory module"
                   " on the West of this tile in the Western column and"
                   " on an even row");
     return tb::program->template
       memory_module<memory_module_linear_id(-1, 0)>();
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_west(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program.
memory_module_linear_id() [1/2]
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id (int dx, int dy) inline static constexpr
Compute the linear id of a memory module attached to this tile.
Parameters
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 216 of file tile.hpp.
{
    return geo:: memory_module_linear_id(x, y, dx, dy);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_south(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west().
memory_module_linear_id() [2/2]
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id (int dx, int dy) inline static constexpr
Compute the linear id of a memory module attached to this tile.
Parameters
[in] dx is the horizontal displacement (-1,0,+1)
[in] dy is the vertical displacement (-1,0,+1)
Definition at line 216 of file tile.hpp.
{
    return geo:: memory_module_linear_id(x, y, dx, dy);
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x, and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y.
rx_dma() [1/2]
template<typename AIE_Program , int X, int Y> auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::rx_dma (int port) inline
Get access on a receiver DMA.
Parameters
[in] port specifies which DMA to access, starting at 0
Definition at line 439 of file tile.hpp.
{
    return dma_dsl { *this, this->ti.rx_dma(port) };
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::rx_dma(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
rx_dma() [2/2]
template<typename AIE_Program , int X, int Y> auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::rx_dma (int port) inline
Get access on a receiver DMA.
Parameters
[in] port specifies which DMA to access, starting at 0
Definition at line 439 of file tile.hpp.
{
    return dma_dsl { *this, this->ti.rx_dma(port) };
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::rx_dma(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
tx_dma() [1/2]
template<typename AIE_Program , int X, int Y> auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::tx_dma (int port) inline
Get access on a transmit DMA.
Parameters
[in] port specifies which DMA to access, starting at 0
Definition at line 447 of file tile.hpp.
{
    return dma_dsl { *this, this->ti.tx_dma(port) };
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti, and trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tx_dma().
tx_dma() [2/2]
template<typename AIE_Program , int X, int Y> auto trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::tx_dma (int port) inline
Get access on a transmit DMA.
Parameters
[in] port specifies which DMA to access, starting at 0
Definition at line 447 of file tile.hpp.
{
    return dma_dsl { *this, this->ti.tx_dma(port) };
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti, and trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tx_dma().
vertical_barrier() [1/2]
template<typename AIE_Program , int X, int Y> void trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier (int lock = 15) inline
A vertical barrier using a lock.
Implement a barrier across the tiles a line.
Parameters
[in] lock is the ME lock to use. The lock 15 is used by default
Definition at line 405 of file tile.hpp.
{
    // Propagate a token from South to North and back
    if constexpr (!is_south_row()) {
      // Wait for the Southern neighbour to be ready
      mem().lock(lock).acquire_with_value(true);
    }
    if constexpr (is_memory_module_north()) {
      mem_north().lock(lock).acquire_with_value(false);
      // Unleash the Northern neighbour
      mem_north().lock(lock).release_with_value(true);
      // Wait for the Northern neighbour to acknowledge
      mem_north().lock(lock).acquire_with_value(false);
    }
    if constexpr (!is_south_row()) {
      // Acknowledge to the Southern neighbour
      mem().lock(lock).release_with_value(false);
    }
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_north(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_row(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north().
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::barrier().
vertical_barrier() [2/2]
template<typename AIE_Program , int X, int Y> void trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::vertical_barrier (int lock = 15) inline
A vertical barrier using a lock.
Implement a barrier across the tiles a line.
Parameters
[in] lock is the ME lock to use. The lock 15 is used by default
Definition at line 405 of file tile.hpp.
{
    // Propagate a token from South to North and back
    if constexpr (!is_south_row()) {
      // Wait for the Southern neighbour to be ready
      mem().lock(lock).acquire_with_value(true);
    }
    if constexpr (is_memory_module_north()) {
      mem_north().lock(lock).acquire_with_value(false);
      // Unleash the Northern neighbour
      mem_north().lock(lock).release_with_value(true);
      // Wait for the Northern neighbour to acknowledge
      mem_north().lock(lock).acquire_with_value(false);
    }
    if constexpr (!is_south_row()) {
      // Acknowledge to the Southern neighbour
      mem().lock(lock).release_with_value(false);
    }
  }
References trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module_north(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_row(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north().
Member Data Documentation
x
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::x = X static constexpr
The horizontal tile coordinates in the CGRA grid (starting at 0 and increasing towards the East)
Definition at line 60 of file tile.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::cascade_linear_id(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_in(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_out(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_id(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_end(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_start(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_column(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_east_valid(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_column(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_west_valid(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::linear_id(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id().
y
template<typename AIE_Program , int X, int Y> static auto constexpr trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::y = Y static constexpr
The vertical tile coordinates in the CGRA grid (starting at increasing towards the North)
Definition at line 63 of file tile.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::cascade_linear_id(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_in(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_out(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_id(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::horizontal_barrier(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_end(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_cascade_start(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_memory_module(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_row(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_north_valid(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_row(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::is_south_valid(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::linear_id(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::memory_module_linear_id().
trisycl::vendor::xilinx::acap::aie::tile_base
class trisycl::vendor::xilinx::acap::aie::tile_base
template<typename AIE_Program>
class trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >
The AI Engine tile infrastructure common to all the tiles.
This allows some type erasure while accessing the common tile infrastructure.
Parameters
AIE_Program is the type representing the full CGRA program with the tile programs and memory contents
Definition at line 32 of file tile_base.hpp.
Public Member Functions
void run ()
Provide a run member function that does nothing so it is possible to write a minimum AI Engine program that does nothing.
template<typename Work >
void single_task (Work &&f)
Submit a callable on this tile.
void wait ()
Wait for the execution of the callable on this tile.
auto & cascade ()
Access the cascade connections.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
void set_program (AIE_Program &p)
Store a way to access to the program.
void set_tile_infrastructure (tile_infrastructure< geo > t)
Store a way to access to hardware infrastructure of the tile.
void run ()
Provide a run member function that does nothing so it is possible to write a minimum AI Engine program that does nothing.
template<typename Work >
void single_task (Work &&f)
Submit a callable on this tile.
void wait ()
Wait for the execution of the callable on this tile.
auto & cascade ()
Access the cascade connections.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
void set_program (AIE_Program &p)
Store a way to access to the program.
void set_tile_infrastructure (tile_infrastructure< geo > t)
Store a way to access to hardware infrastructure of the tile.
Protected Attributes
AIE_Program * program
Keep a reference to the AIE_Program with the full tile and memory view.
tile_infrastructure< geo > ti
Keep a reference to the tile_infrastructure hardware features.
Private Types
using geo = typename AIE_Program::device::geo
using geo = typename AIE_Program::device::geo
Member Typedef Documentation
geo [1/2]
template<typename AIE_Program > using trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::geo = typename AIE_Program::device::geo private
Definition at line 34 of file tile_base.hpp.
geo [2/2]
template<typename AIE_Program > using trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::geo = typename AIE_Program::device::geo private
Definition at line 34 of file tile_base.hpp.
Member Function Documentation
cascade() [1/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::cascade () inline
Access the cascade connections.
Definition at line 72 of file tile_base.hpp.
                  {
    // \todo the cascade should be part of the tile infrastructure instead
    return program->cascade();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::cascade().
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_in(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::get_cascade_stream_out().
cascade() [2/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::cascade () inline
Access the cascade connections.
Definition at line 72 of file tile_base.hpp.
                  {
    // \todo the cascade should be part of the tile infrastructure instead
    return program->cascade();
  }
References trisycl::vendor::xilinx::acap::aie::program< AIEDevice, Tile, Memory >::cascade().
in() [1/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in (int port) inline
Get the user input port from the AXI stream switch.
Definition at line 97 of file tile_base.hpp.
                     {
    return ti.in(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
in() [2/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in (int port) inline
Get the user input port from the AXI stream switch.
Definition at line 97 of file tile_base.hpp.
                     {
    return ti.in(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
in_connection() [1/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in_connection (int port) inline
Get the user input connection from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 82 of file tile_base.hpp.
{
    return ti.in_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in_connection(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
in_connection() [2/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in_connection (int port) inline
Get the user input connection from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 82 of file tile_base.hpp.
{
    return ti.in_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in_connection(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
out() [1/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out (int port) inline
Get the user output port to the AXI stream switch.
Definition at line 103 of file tile_base.hpp.
                      {
    return ti.out(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
out() [2/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out (int port) inline
Get the user output port to the AXI stream switch.
Definition at line 103 of file tile_base.hpp.
                      {
    return ti.out(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
out_connection() [1/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out_connection (int port) inline
Get the user output connection to the AXI stream switch.
Parameters
[in] port is port to use
Definition at line 91 of file tile_base.hpp.
{
    return ti.out_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out_connection(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
out_connection() [2/2]
template<typename AIE_Program > auto & trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out_connection (int port) inline
Get the user output connection to the AXI stream switch.
Parameters
[in] port is port to use
Definition at line 91 of file tile_base.hpp.
{
    return ti.out_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out_connection(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
run() [1/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::run () inline
Provide a run member function that does nothing so it is possible to write a minimum AI Engine program that does nothing.
Note that even if this function is not virtual, in the common case a programmer implements it to specify the program executed by a tile
Definition at line 54 of file tile_base.hpp.
             {
  }
run() [2/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::run () inline
Provide a run member function that does nothing so it is possible to write a minimum AI Engine program that does nothing.
Note that even if this function is not virtual, in the common case a programmer implements it to specify the program executed by a tile
Definition at line 54 of file tile_base.hpp.
             {
  }
set_program() [1/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::set_program (AIE_Program & p) inline
Store a way to access to the program.
Definition at line 109 of file tile_base.hpp.
{
    program = &p;
  }
References p.
set_program() [2/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::set_program (AIE_Program & p) inline
Store a way to access to the program.
Definition at line 109 of file tile_base.hpp.
{
    program = &p;
  }
References p.
set_tile_infrastructure() [1/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::set_tile_infrastructure (tile_infrastructure< geo > t) inline
Store a way to access to hardware infrastructure of the tile.
Definition at line 115 of file tile_base.hpp.
{
    ti = t;
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
set_tile_infrastructure() [2/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::set_tile_infrastructure (tile_infrastructure< geo > t) inline
Store a way to access to hardware infrastructure of the tile.
Definition at line 115 of file tile_base.hpp.
{
    ti = t;
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
single_task() [1/2]
template<typename AIE_Program > template<typename Work > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::single_task (Work && f) inline
Submit a callable on this tile.
Definition at line 60 of file tile_base.hpp.
{
    ti.single_task(std::forward<Work>(f));
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::single_task(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
single_task() [2/2]
template<typename AIE_Program > template<typename Work > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::single_task (Work && f) inline
Submit a callable on this tile.
Definition at line 60 of file tile_base.hpp.
{
    ti.single_task(std::forward<Work>(f));
  }
References trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::single_task(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti.
wait() [1/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::wait () inline
Wait for the execution of the callable on this tile.
Definition at line 66 of file tile_base.hpp.
              {
    ti.wait();
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti, and trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::wait().
wait() [2/2]
template<typename AIE_Program > void trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::wait () inline
Wait for the execution of the callable on this tile.
Definition at line 66 of file tile_base.hpp.
              {
    ti.wait();
  }
References trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti, and trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::wait().
Member Data Documentation
program
template<typename AIE_Program > AIE_Program * trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::program protected
Keep a reference to the AIE_Program with the full tile and memory view.
Todo:
can probably be removed
Todo:
can probably be removed
Definition at line 40 of file tile_base.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_east(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_north(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_south(), and trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::mem_west().
ti
template<typename AIE_Program > tile_infrastructure< geo > trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::ti protected
Keep a reference to the tile_infrastructure hardware features.
Definition at line 43 of file tile_base.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in(), trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in_connection(), trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out(), trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out_connection(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::rx_dma(), trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::set_tile_infrastructure(), trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::single_task(), trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::tx_dma(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::wait().
trisycl::vendor::xilinx::acap::aie::tile_infrastructure
class trisycl::vendor::xilinx::acap::aie::tile_infrastructure
template<typename Geography>
class trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >
The AI Engine tile infrastructure common to all the tiles.
This allows some type erasure while accessing the common tile infrastructure.
Parameters
Geography is the geography type representing the full layout of the architecture
Definition at line 42 of file tile_infrastructure.hpp.
Public Types
using facade_t = facade::device< tile_infrastructure< Geography >, dti >
The faade used to implement part of the user-facing type.
using geo = Geography
using axi_ss_geo = typename dti::axi_ss_geo
using mpl = typename dti::mpl
using spl = typename dti::spl
using axi_ss_t = typename dti::axi_ss_t
using facade_t = facade::device< tile_infrastructure< Geography >, dti >
The faade used to implement part of the user-facing type.
using geo = Geography
using axi_ss_geo = typename dti::axi_ss_geo
using mpl = typename dti::mpl
using spl = typename dti::spl
using axi_ss_t = typename dti::axi_ss_t
Public Types inherited from trisycl::facade::device< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >
using implementation_t = detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >
The type encapsulating the implementation.
using detail_t = detail::tile_infrastructure< Geography >
The real detail type doing the work behind the scene.
Public Member Functions
tile_infrastructure (int x, int y, auto &dev, ::trisycl::detail::fiber_pool &fiber_executor)
Start the tile infrastructure associated to the AIE device.
tile_infrastructure ()=default
int x ()
Get the horizontal coordinate.
int y ()
Get the vertical coordinate.
auto & mem ()
Access to the common infrastructure part of a tile memory.
template<typename Invocable >
void submit (Invocable &&f) const
Submit a command group to the tile.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
auto & rx_dma (int id)
Get access to a receiver DMA.
auto & tx_dma (int id)
Get access to a transmit DMA.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the output router port of the AXI stream switch.
template<typename Work >
auto & single_task (Work &&f)
Launch a callable on this tile.
auto & wait ()
Wait for the execution of the callable on this tile.
auto & connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp)
Configure a connection of the core tile AXI stream switch.
void display (latex::context &c) const
Display the tile to a LaTeX context.
tile_infrastructure (int x, int y, auto &dev, ::trisycl::detail::fiber_pool &fiber_executor)
Start the tile infrastructure associated to the AIE device.
tile_infrastructure ()=default
int x ()
Get the horizontal coordinate.
int y ()
Get the vertical coordinate.
auto & mem ()
Access to the common infrastructure part of a tile memory.
template<typename Invocable >
void submit (Invocable &&f) const
Submit a command group to the tile.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
auto & rx_dma (int id)
Get access to a receiver DMA.
auto & tx_dma (int id)
Get access to a transmit DMA.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the output router port of the AXI stream switch.
template<typename Work >
auto & single_task (Work &&f)
Launch a callable on this tile.
auto & wait ()
Wait for the execution of the callable on this tile.
auto & connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp)
Configure a connection of the core tile AXI stream switch.
void display (latex::context &c) const
Display the tile to a LaTeX context.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >
shared_ptr_implementation (std::shared_ptr< detail::tile_infrastructure< Geography > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::tile_infrastructure< Geography > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Static Public Member Functions
static constexpr int x_size ()
Get the horizontal number of tiles.
static constexpr int y_size ()
Get the vertical number of tiles.
static vec< int, 2 > display_size ()
Compute the size of the graphics representation of the tile.
static constexpr int x_size ()
Get the horizontal number of tiles.
static constexpr int y_size ()
Get the vertical number of tiles.
static vec< int, 2 > display_size ()
Compute the size of the graphics representation of the tile.
Private Types
using dti = detail::tile_infrastructure< Geography >
The type encapsulating the implementation.
using dti = detail::tile_infrastructure< Geography >
The type encapsulating the implementation.
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >
std::shared_ptr< detail::tile_infrastructure< Geography > > implementation
The implementation forward everything to this... implementation.
Member Typedef Documentation
axi_ss_geo [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::axi_ss_geo = typename dti::axi_ss_geo
Definition at line 53 of file tile_infrastructure.hpp.
axi_ss_geo [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::axi_ss_geo = typename dti::axi_ss_geo
Definition at line 53 of file tile_infrastructure.hpp.
axi_ss_t [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::axi_ss_t = typename dti::axi_ss_t
Definition at line 56 of file tile_infrastructure.hpp.
axi_ss_t [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::axi_ss_t = typename dti::axi_ss_t
Definition at line 56 of file tile_infrastructure.hpp.
dti [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::dti = detail::tile_infrastructure<Geography> private
The type encapsulating the implementation.
Definition at line 46 of file tile_infrastructure.hpp.
dti [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::dti = detail::tile_infrastructure<Geography> private
The type encapsulating the implementation.
Definition at line 46 of file tile_infrastructure.hpp.
facade_t [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::facade_t = facade::device<tile_infrastructure<Geography>, dti>
The faade used to implement part of the user-facing type.
Definition at line 50 of file tile_infrastructure.hpp.
facade_t [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::facade_t = facade::device<tile_infrastructure<Geography>, dti>
The faade used to implement part of the user-facing type.
Definition at line 50 of file tile_infrastructure.hpp.
geo [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::geo = Geography
Definition at line 52 of file tile_infrastructure.hpp.
geo [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::geo = Geography
Definition at line 52 of file tile_infrastructure.hpp.
mpl [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::mpl = typename dti::mpl
Definition at line 54 of file tile_infrastructure.hpp.
mpl [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::mpl = typename dti::mpl
Definition at line 54 of file tile_infrastructure.hpp.
spl [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::spl = typename dti::spl
Definition at line 55 of file tile_infrastructure.hpp.
spl [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::spl = typename dti::spl
Definition at line 55 of file tile_infrastructure.hpp.
Constructor & Destructor Documentation
tile_infrastructure() [1/4]
template<typename Geography > trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tile_infrastructure (int x, int y, auto & dev, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the tile infrastructure associated to the AIE device.
Parameters
[in] x is the horizontal coordinate for this tile
[in] y is the vertical coordinate for this tile
[in] dev is the aie::detail::device used to control hardware when using real hardware and provide some debug information from inside the tile_infrastructure. Use auto concept here to avoid explicit type causing circular dependency
[in] fiber_executor is the executor used to run infrastructure details
Definition at line 75 of file tile_infrastructure.hpp.
      : facade_t { std::make_shared<dti>(x, y, dev, fiber_executor) } {}
tile_infrastructure() [2/4]
template<typename Geography > trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tile_infrastructure () default
tile_infrastructure() [3/4]
template<typename Geography > trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tile_infrastructure (int x, int y, auto & dev, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the tile infrastructure associated to the AIE device.
Parameters
[in] x is the horizontal coordinate for this tile
[in] y is the vertical coordinate for this tile
[in] dev is the aie::detail::device used to control hardware when using real hardware and provide some debug information from inside the tile_infrastructure. Use auto concept here to avoid explicit type causing circular dependency
[in] fiber_executor is the executor used to run infrastructure details
Definition at line 75 of file tile_infrastructure.hpp.
      : facade_t { std::make_shared<dti>(x, y, dev, fiber_executor) } {}
tile_infrastructure() [4/4]
template<typename Geography > trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tile_infrastructure () default
Member Function Documentation
connect() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp) inline
Configure a connection of the core tile AXI stream switch.
Definition at line 198 of file tile_infrastructure.hpp.
{
    implementation->connect(sp, mp);
    // To allow chaining commands
    return *this;
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
connect() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp) inline
Configure a connection of the core tile AXI stream switch.
Definition at line 198 of file tile_infrastructure.hpp.
{
    implementation->connect(sp, mp);
    // To allow chaining commands
    return *this;
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
display() [1/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::display (latex::context & c) const inline
Display the tile to a LaTeX context.
Definition at line 209 of file tile_infrastructure.hpp.
{ implementation->display(c); }
References c, and trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
display() [2/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::display (latex::context & c) const inline
Display the tile to a LaTeX context.
Definition at line 209 of file tile_infrastructure.hpp.
{ implementation->display(c); }
References c, and trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
display_size() [1/2]
template<typename Geography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::display_size () inline static
Compute the size of the graphics representation of the tile.
Definition at line 206 of file tile_infrastructure.hpp.
{ return dti::display_size(); }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_size().
display_size() [2/2]
template<typename Geography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::display_size () inline static
Compute the size of the graphics representation of the tile.
Definition at line 206 of file tile_infrastructure.hpp.
{ return dti::display_size(); }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_size().
in() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in (int port) inline
Get the user input port from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 135 of file tile_infrastructure.hpp.
{ return implementation->in(port); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in().
in() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in (int port) inline
Get the user input port from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 135 of file tile_infrastructure.hpp.
{ return implementation->in(port); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
in_connection() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in_connection (int port) inline
Get the user input connection from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 121 of file tile_infrastructure.hpp.
{ return implementation->in_connection(port); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::in_connection().
in_connection() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::in_connection (int port) inline
Get the user input connection from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 121 of file tile_infrastructure.hpp.
{ return implementation->in_connection(port); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
input() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::input (spl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the slave_port_layout for the stream
Definition at line 157 of file tile_infrastructure.hpp.
{ return implementation->input(p); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation, and p.
input() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::input (spl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the slave_port_layout for the stream
Definition at line 157 of file tile_infrastructure.hpp.
{ return implementation->input(p); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation, and p.
mem() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::mem () inline
Access to the common infrastructure part of a tile memory.
Definition at line 96 of file tile_infrastructure.hpp.
              {
    return implementation->mem();
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
mem() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::mem () inline
Access to the common infrastructure part of a tile memory.
Definition at line 96 of file tile_infrastructure.hpp.
              {
    return implementation->mem();
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
out() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out (int port) inline
Get the user output port to the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 141 of file tile_infrastructure.hpp.
{ return implementation->out(port); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out().
out() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out (int port) inline
Get the user output port to the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 141 of file tile_infrastructure.hpp.
{ return implementation->out(port); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
out_connection() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out_connection (int port) inline
Get the user output connection to the AXI stream switch.
Parameters
[in] port is port to use
Definition at line 127 of file tile_infrastructure.hpp.
{
    return implementation->out_connection(port);
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::out_connection().
out_connection() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::out_connection (int port) inline
Get the user output connection to the AXI stream switch.
Parameters
[in] port is port to use
Definition at line 127 of file tile_infrastructure.hpp.
{
    return implementation->out_connection(port);
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
output() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::output (mpl p) inline
Get the output router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 163 of file tile_infrastructure.hpp.
{ return implementation->output(p); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation, and p.
output() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::output (mpl p) inline
Get the output router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 163 of file tile_infrastructure.hpp.
{ return implementation->output(p); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation, and p.
rx_dma() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::rx_dma (int id) inline
Get access to a receiver DMA.
Parameters
[in] id specifies which DMA to access
Definition at line 146 of file tile_infrastructure.hpp.
{ return implementation->rx_dma(id); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::rx_dma().
rx_dma() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::rx_dma (int id) inline
Get access to a receiver DMA.
Parameters
[in] id specifies which DMA to access
Definition at line 146 of file tile_infrastructure.hpp.
{ return implementation->rx_dma(id); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
single_task() [1/2]
template<typename Geography > template<typename Work > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::single_task (Work && f) inline
Launch a callable on this tile.
Recycle the tile_infrastructure shared_ptr as a fake tile handle which is copyable.
Todo:
In a device implementation we should have a real tile_handler type making sense on the device instead of just *this
Definition at line 166 of file tile_infrastructure.hpp.
{
    /* Add an immediate lambda call to avoid a warning about capturing
       this when non using it */
    auto kernel = [&] {
      if constexpr (requires { f(); })
        /* If the invocable is not interested by the handler, do not
           provide it. Use a copy of the callable to make the
           separation from host to device memory very clear. */
        return [work = f] () mutable { return work(); };
      else
        /** Recycle the tile_infrastructure shared_ptr as a fake tile
            handle which is copyable.
            \todo In a device implementation we should have a real
            tile_handler type making sense on the device instead of
            just *this */
        return [this, work = f] () mutable { return work(*this); };
    }();
    implementation->single_task(kernel);
    // To allow chaining commands
    return *this;
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::cgh_t::single_task(), and trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::single_task().
single_task() [2/2]
template<typename Geography > template<typename Work > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::single_task (Work && f) inline
Launch a callable on this tile.
Recycle the tile_infrastructure shared_ptr as a fake tile handle which is copyable.
Todo:
In a device implementation we should have a real tile_handler type making sense on the device instead of just *this
Definition at line 166 of file tile_infrastructure.hpp.
{
    /* Add an immediate lambda call to avoid a warning about capturing
       this when non using it */
    auto kernel = [&] {
      if constexpr (requires { f(); })
        /* If the invocable is not interested by the handler, do not
           provide it. Use a copy of the callable to make the
           separation from host to device memory very clear. */
        return [work = f] () mutable { return work(); };
      else
        /** Recycle the tile_infrastructure shared_ptr as a fake tile
            handle which is copyable.
            \todo In a device implementation we should have a real
            tile_handler type making sense on the device instead of
            just *this */
        return [this, work = f] () mutable { return work(*this); };
    }();
    implementation->single_task(kernel);
    // To allow chaining commands
    return *this;
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
submit() [1/2]
template<typename Geography > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::submit (Invocable && f) const inline
Submit a command group to the tile.
Definition at line 112 of file tile_infrastructure.hpp.
{
    cgh_t cgh { *this };
    std::forward<Invocable>(f)(cgh);
  }
submit() [2/2]
template<typename Geography > template<typename Invocable > void trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::submit (Invocable && f) const inline
Submit a command group to the tile.
Definition at line 112 of file tile_infrastructure.hpp.
{
    cgh_t cgh { *this };
    std::forward<Invocable>(f)(cgh);
  }
tx_dma() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tx_dma (int id) inline
Get access to a transmit DMA.
Parameters
[in] id specifies which DMA to access
Definition at line 151 of file tile_infrastructure.hpp.
{ return implementation->tx_dma(id); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile< AIE_Program, X, Y >::tx_dma().
tx_dma() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::tx_dma (int id) inline
Get access to a transmit DMA.
Parameters
[in] id specifies which DMA to access
Definition at line 151 of file tile_infrastructure.hpp.
{ return implementation->tx_dma(id); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
wait() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::wait () inline
Wait for the execution of the callable on this tile.
Definition at line 191 of file tile_infrastructure.hpp.
               {
    implementation->wait();
    // To allow chaining commands
    return *this;
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
Referenced by trisycl::vendor::xilinx::acap::aie::tile_base< AIE_Program >::wait().
wait() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::wait () inline
Wait for the execution of the callable on this tile.
Definition at line 191 of file tile_infrastructure.hpp.
               {
    implementation->wait();
    // To allow chaining commands
    return *this;
  }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
x() [1/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::x () inline
Get the horizontal coordinate.
Definition at line 84 of file tile_infrastructure.hpp.
{ return implementation->x(); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
x() [2/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::x () inline
Get the horizontal coordinate.
Definition at line 84 of file tile_infrastructure.hpp.
{ return implementation->x(); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
x_size() [1/2]
template<typename Geography > static constexpr int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::x_size () inline static constexpr
Get the horizontal number of tiles.
Definition at line 90 of file tile_infrastructure.hpp.
{ return geo::x_size; }
x_size() [2/2]
template<typename Geography > static constexpr int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::x_size () inline static constexpr
Get the horizontal number of tiles.
Definition at line 90 of file tile_infrastructure.hpp.
{ return geo::x_size; }
y() [1/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::y () inline
Get the vertical coordinate.
Definition at line 87 of file tile_infrastructure.hpp.
{ return implementation->y(); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
y() [2/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::y () inline
Get the vertical coordinate.
Definition at line 87 of file tile_infrastructure.hpp.
{ return implementation->y(); }
References trisycl::detail::shared_ptr_implementation< tile_infrastructure< Geography >, detail::tile_infrastructure< Geography > >::implementation.
y_size() [1/2]
template<typename Geography > static constexpr int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::y_size () inline static constexpr
Get the vertical number of tiles.
Definition at line 93 of file tile_infrastructure.hpp.
{ return geo::y_size; }
y_size() [2/2]
template<typename Geography > static constexpr int trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::y_size () inline static constexpr
Get the vertical number of tiles.
Definition at line 93 of file tile_infrastructure.hpp.
{ return geo::y_size; }
trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure
class trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure
template<typename Geography>
class trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >
The AI Engine tile infrastructure common to all the tiles.
This allows some type erasure while accessing the common tile infrastructure.
Parameters
AIE is the type representing the full CGRA with the programs and memory contents
Definition at line 51 of file tile_infrastructure.hpp.
Public Types
using geo = Geography
using axi_ss_geo = typename geo::core_axi_stream_switch
using mpl = typename axi_ss_geo::master_port_layout
using spl = typename axi_ss_geo::slave_port_layout
using axi_ss_t = axi_stream_switch< axi_ss_geo >
using geo = Geography
using axi_ss_geo = typename geo::core_axi_stream_switch
using mpl = typename axi_ss_geo::master_port_layout
using spl = typename axi_ss_geo::slave_port_layout
using axi_ss_t = axi_stream_switch< axi_ss_geo >
Public Member Functions
tile_infrastructure (int x, int y, auto &dev, ::trisycl::detail::fiber_pool &fiber_executor)
Start the tile infrastructure associated to the AIE device tile.
int x ()
Get the horizontal coordinate.
int y ()
Get the vertical coordinate.
auto & mem ()
Access to the common infrastructure part of a tile memory.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
auto & rx_dma (int id)
Get access to a receiver DMA.
auto & tx_dma (int id)
Get access to a transmit DMA.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the output router port of the AXI stream switch.
template<typename Work >
void single_task (Work &&f)
Launch an invocable on this tile.
void wait ()
Wait for the execution of the callable on this tile.
void connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp)
Configure a connection of the core tile AXI stream switch.
void display (latex::context &c) const
Display the tile to a LaTeX context.
tile_infrastructure (int x, int y, auto &dev, ::trisycl::detail::fiber_pool &fiber_executor)
Start the tile infrastructure associated to the AIE device tile.
int x ()
Get the horizontal coordinate.
int y ()
Get the vertical coordinate.
auto & mem ()
Access to the common infrastructure part of a tile memory.
auto & in_connection (int port)
Get the user input connection from the AXI stream switch.
auto & out_connection (int port)
Get the user output connection to the AXI stream switch.
auto & in (int port)
Get the user input port from the AXI stream switch.
auto & out (int port)
Get the user output port to the AXI stream switch.
auto & rx_dma (int id)
Get access to a receiver DMA.
auto & tx_dma (int id)
Get access to a transmit DMA.
auto & input (spl p)
Get the input router port of the AXI stream switch.
auto & output (mpl p)
Get the output router port of the AXI stream switch.
template<typename Work >
void single_task (Work &&f)
Launch an invocable on this tile.
void wait ()
Wait for the execution of the callable on this tile.
void connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp)
Configure a connection of the core tile AXI stream switch.
void display (latex::context &c) const
Display the tile to a LaTeX context.
Static Public Member Functions
static vec< int, 2 > display_core_size ()
Compute the size of the graphics representation of the processor.
static vec< int, 2 > display_size ()
Compute the size of the graphics representation of the tile.
static vec< int, 2 > display_core_size ()
Compute the size of the graphics representation of the processor.
static vec< int, 2 > display_size ()
Compute the size of the graphics representation of the tile.
Static Private Member Functions
static auto translate_input_port (int port)
Map the user input port number to the AXI stream switch port.
static auto translate_output_port (int port)
Map the user output port number to the AXI stream switch port.
static auto translate_input_port (int port)
Map the user input port number to the AXI stream switch port.
static auto translate_output_port (int port)
Map the user output port number to the AXI stream switch port.
Private Attributes
int x_coordinate
Keep the horizontal coordinate.
int y_coordinate
Keep the vertical coordinate.
void * dev
Keep track of the aie::detail::device for hardware resource control in device mode or for debugging purpose for better messages.
axi_ss_t axi_ss
The AXI stream switch of the core tile.
aie::memory_infrastructure mi
Keep track of all the infrastructure tile memories of this device.
std::array< std::optional< sending_dma< axi_ss_t > >, axi_ss_geo::s_dma_size > tx_dmas
Sending DMAs.
std::future< void > future_work
Keep track of the std::thread execution in this tile.
Member Typedef Documentation
axi_ss_geo [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss_geo = typename geo::core_axi_stream_switch
Definition at line 55 of file tile_infrastructure.hpp.
axi_ss_geo [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss_geo = typename geo::core_axi_stream_switch
Definition at line 55 of file tile_infrastructure.hpp.
axi_ss_t [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss_t = axi_stream_switch<axi_ss_geo>
Definition at line 58 of file tile_infrastructure.hpp.
axi_ss_t [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss_t = axi_stream_switch<axi_ss_geo>
Definition at line 58 of file tile_infrastructure.hpp.
geo [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::geo = Geography
Definition at line 54 of file tile_infrastructure.hpp.
geo [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::geo = Geography
Definition at line 54 of file tile_infrastructure.hpp.
mpl [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mpl = typename axi_ss_geo::master_port_layout
Definition at line 56 of file tile_infrastructure.hpp.
mpl [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mpl = typename axi_ss_geo::master_port_layout
Definition at line 56 of file tile_infrastructure.hpp.
spl [1/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::spl = typename axi_ss_geo::slave_port_layout
Definition at line 57 of file tile_infrastructure.hpp.
spl [2/2]
template<typename Geography > using trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::spl = typename axi_ss_geo::slave_port_layout
Definition at line 57 of file tile_infrastructure.hpp.
Constructor & Destructor Documentation
tile_infrastructure() [1/2]
template<typename Geography > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure (int x, int y, auto & dev, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the tile infrastructure associated to the AIE device tile.
Parameters
[in] x is the horizontal coordinate for this tile
[in] y is the vertical coordinate for this tile
[in] dev is the aie::detail::device used to control hardware when using real hardware and provide some debug information from inside the tile_infrastructure. Use auto concept here to avoid explicit type causing circular dependency
[in] fiber_executor is the executor used to run infrastructure details
Definition at line 132 of file tile_infrastructure.hpp.
      : x_coordinate { x }
      , y_coordinate { y }
      , dev { &dev }
      , mi { dev }
#if TRISYCL_XILINX_AIE_TILE_CODE_ON_FIBER
      , fe { &fiber_executor }
#endif
  {
    // Connect the core receivers to its AXI stream switch
    for (auto p : views::enum_type(mpl::me_0, mpl::me_last))
      output(p) =
          std::make_shared<port_receiver<axi_ss_t>>(axi_ss, "core_receiver");
    axi_ss.start(x, y, fiber_executor);
    /* Create the core tile receiver DMAs and make them directly the
       switch output ports */
    for (auto p : axi_ss_geo::m_dma_range)
      output(p) =
          std::make_shared<receiving_dma<axi_ss_t>>(axi_ss, fiber_executor);
    /* Create the core tile sender DMAs and connect them internally to
       their switch input ports */
    for (const auto& [d, p] :
         ranges::views::zip(tx_dmas, axi_ss_geo::s_dma_range))
      d.emplace(fiber_executor, input(p));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::views::enum_type, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::input(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output(), p, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::start(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dmas, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y().
tile_infrastructure() [2/2]
template<typename Geography > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure (int x, int y, auto & dev, ::trisycl::detail::fiber_pool & fiber_executor) inline
Start the tile infrastructure associated to the AIE device tile.
Parameters
[in] x is the horizontal coordinate for this tile
[in] y is the vertical coordinate for this tile
[in] dev is the aie::detail::device used to control hardware when using real hardware and provide some debug information from inside the tile_infrastructure. Use auto concept here to avoid explicit type causing circular dependency
[in] fiber_executor is the executor used to run infrastructure details
Definition at line 132 of file tile_infrastructure.hpp.
      : x_coordinate { x }
      , y_coordinate { y }
      , dev { &dev }
      , mi { dev }
#if TRISYCL_XILINX_AIE_TILE_CODE_ON_FIBER
      , fe { &fiber_executor }
#endif
  {
    // Connect the core receivers to its AXI stream switch
    for (auto p : views::enum_type(mpl::me_0, mpl::me_last))
      output(p) =
          std::make_shared<port_receiver<axi_ss_t>>(axi_ss, "core_receiver");
    axi_ss.start(x, y, fiber_executor);
    /* Create the core tile receiver DMAs and make them directly the
       switch output ports */
    for (auto p : axi_ss_geo::m_dma_range)
      output(p) =
          std::make_shared<receiving_dma<axi_ss_t>>(axi_ss, fiber_executor);
    /* Create the core tile sender DMAs and connect them internally to
       their switch input ports */
    for (const auto& [d, p] :
         ranges::views::zip(tx_dmas, axi_ss_geo::s_dma_range))
      d.emplace(fiber_executor, input(p));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::views::enum_type, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::input(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output(), p, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::start(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dmas, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y().
Member Function Documentation
connect() [1/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp) inline
Configure a connection of the core tile AXI stream switch.
Definition at line 262 of file tile_infrastructure.hpp.
{
    axi_ss.connect(sp, mp);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::connect().
connect() [2/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::connect (typename geo::core_axi_stream_switch::slave_port_layout sp, typename geo::core_axi_stream_switch::master_port_layout mp) inline
Configure a connection of the core tile AXI stream switch.
Definition at line 262 of file tile_infrastructure.hpp.
{
    axi_ss.connect(sp, mp);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::connect().
display() [1/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display (latex::context & c) const inline
Display the tile to a LaTeX context.
Definition at line 281 of file tile_infrastructure.hpp.
{
    auto get_tikz_coordinate = [&](auto x, auto y) {
      auto const [x_size, y_size] = display_size();
      return (boost::format { "(%1%,%2%)" }
              // Scale real LaTeX coordinate to fit
              % c.scale(x_coordinate * x_size + x) %
              c.scale(y_coordinate * y_size + y))
          .str();
    };
    c.add((boost::format { "  \\begin{scope}[name prefix = TileX%1%Y%2%]" } %
           x_coordinate % y_coordinate)
              .str());
    axi_ss.display(c, display_core_size(), get_tikz_coordinate);
    // Connect the core receivers to its AXI stream switch
    for (auto [i, p] : axi_ss_geo::m_me_range | ranges::views::enumerate) {
      c.add(
          (boost::format { R"(
    \coordinate(CoreIn%1%) at %2%;
    \node[rotate=90,anchor=east](CoreIn%1%Label) at %2% {in(%1%)};
    \draw (node cs:name=MMe%1%)
       -| (node cs:name=CoreIn%1%);)" } %
           i %
           get_tikz_coordinate(i, ranges::distance(axi_ss_geo::m_me_range) + 1))
              .str());
    };
    // Connect the core senders to its AXI stream switch
    for (auto [i, p] : axi_ss_geo::s_me_range | ranges::views::enumerate) {
      c.add(
          (boost::format { R"(
    \coordinate(CoreOut%1%) at %2%;
    \node[anchor=east](CoreOut%1%Label) at %2%  {out(%1%)};
    \draw (node cs:name=CoreOut%1%)
       -| (node cs:name=SMe%1%);)" } %
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, c, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_core_size(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_size(), i, p, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
display() [2/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display (latex::context & c) const inline
Display the tile to a LaTeX context.
Definition at line 281 of file tile_infrastructure.hpp.
{
    auto get_tikz_coordinate = [&](auto x, auto y) {
      auto const [x_size, y_size] = display_size();
      return (boost::format { "(%1%,%2%)" }
              // Scale real LaTeX coordinate to fit
              % c.scale(x_coordinate * x_size + x) %
              c.scale(y_coordinate * y_size + y))
          .str();
    };
    c.add((boost::format { "  \\begin{scope}[name prefix = TileX%1%Y%2%]" } %
           x_coordinate % y_coordinate)
              .str());
    axi_ss.display(c, display_core_size(), get_tikz_coordinate);
    // Connect the core receivers to its AXI stream switch
    for (auto [i, p] : axi_ss_geo::m_me_range | ranges::views::enumerate) {
      c.add(
          (boost::format { R"(
    \coordinate(CoreIn%1%) at %2%;
    \node[rotate=90,anchor=east](CoreIn%1%Label) at %2% {in(%1%)};
    \draw (node cs:name=MMe%1%)
       -| (node cs:name=CoreIn%1%);)" } %
           i %
           get_tikz_coordinate(i, ranges::distance(axi_ss_geo::m_me_range) + 1))
              .str());
    };
    // Connect the core senders to its AXI stream switch
    for (auto [i, p] : axi_ss_geo::s_me_range | ranges::views::enumerate) {
      c.add(
          (boost::format { R"(
    \coordinate(CoreOut%1%) at %2%;
    \node[anchor=east](CoreOut%1%Label) at %2%  {out(%1%)};
    \draw (node cs:name=CoreOut%1%)
       -| (node cs:name=SMe%1%);)" } %
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, c, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::display(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_core_size(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_size(), i, p, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
display_core_size() [1/2]
template<typename Geography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_core_size () inline static
Compute the size of the graphics representation of the processor.
Definition at line 268 of file tile_infrastructure.hpp.
{
    // This is the minimum rectangle fitting all the processor outputs & inputs
    return { 1 + ranges::distance(axi_ss_geo::m_me_range),
             1 + ranges::distance(axi_ss_geo::s_me_range) };
  }
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_size().
display_core_size() [2/2]
template<typename Geography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_core_size () inline static
Compute the size of the graphics representation of the processor.
Definition at line 268 of file tile_infrastructure.hpp.
{
    // This is the minimum rectangle fitting all the processor outputs & inputs
    return { 1 + ranges::distance(axi_ss_geo::m_me_range),
             1 + ranges::distance(axi_ss_geo::s_me_range) };
  }
display_size() [1/2]
template<typename Geography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_size () inline static
Compute the size of the graphics representation of the tile.
Definition at line 275 of file tile_infrastructure.hpp.
{
    // Just the sum of the size of its content
    return display_core_size() + axi_ss_t::display_size();
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_core_size(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::display_size().
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display(), and trisycl::vendor::xilinx::acap::aie::tile_infrastructure< Geography >::display_size().
display_size() [2/2]
template<typename Geography > static vec< int, 2 > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_size () inline static
Compute the size of the graphics representation of the tile.
Definition at line 275 of file tile_infrastructure.hpp.
{
    // Just the sum of the size of its content
    return display_core_size() + axi_ss_t::display_size();
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display_core_size(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::display_size().
in() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in (int port) inline
Get the user input port from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 194 of file tile_infrastructure.hpp.
                     {
    TRISYCL_DUMP_T("in(" << port << ") on tile(" << x_coordinate << ','
                         << y_coordinate << ')');
    return *in_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in_connection(), TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
in() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in (int port) inline
Get the user input port from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 194 of file tile_infrastructure.hpp.
                     {
    TRISYCL_DUMP_T("in(" << port << ") on tile(" << x_coordinate << ','
                         << y_coordinate << ')');
    return *in_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in_connection(), TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
in_connection() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in_connection (int port) inline
Get the user input connection from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 174 of file tile_infrastructure.hpp.
{
    /* The input port for the core is actually the corresponding
       output on the switch */
    return axi_ss.out_connection(translate_output_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::out_connection(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_output_port().
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in().
in_connection() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in_connection (int port) inline
Get the user input connection from the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 174 of file tile_infrastructure.hpp.
{
    /* The input port for the core is actually the corresponding
       output on the switch */
    return axi_ss.out_connection(translate_output_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::out_connection(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_output_port().
input() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::input (spl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the slave_port_layout for the stream
Definition at line 230 of file tile_infrastructure.hpp.
                     {
    // No index validation required because of type safety
    return axi_ss.input(p);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input(), and p.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure().
input() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::input (spl p) inline
Get the input router port of the AXI stream switch.
Parameters
p is the slave_port_layout for the stream
Definition at line 230 of file tile_infrastructure.hpp.
                     {
    // No index validation required because of type safety
    return axi_ss.input(p);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input(), and p.
mem() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mem () inline
Access to the common infrastructure part of a tile memory.
Definition at line 166 of file tile_infrastructure.hpp.
              {
    return mi;
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mi.
mem() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mem () inline
Access to the common infrastructure part of a tile memory.
Definition at line 166 of file tile_infrastructure.hpp.
              {
    return mi;
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mi.
out() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out (int port) inline
Get the user output port to the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 204 of file tile_infrastructure.hpp.
                      {
    TRISYCL_DUMP_T("out(" << port << ") on tile(" << x_coordinate << ','
                          << y_coordinate << ')');
    return *out_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out_connection(), TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
out() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out (int port) inline
Get the user output port to the AXI stream switch.
Parameters
[in] port is the port to use
Definition at line 204 of file tile_infrastructure.hpp.
                      {
    TRISYCL_DUMP_T("out(" << port << ") on tile(" << x_coordinate << ','
                          << y_coordinate << ')');
    return *out_connection(port);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out_connection(), TRISYCL_DUMP_T, trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate, and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
out_connection() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out_connection (int port) inline
Get the user output connection to the AXI stream switch.
Parameters
[in] port is port to use
Definition at line 184 of file tile_infrastructure.hpp.
{
    /* The output port for the core is actually the corresponding
       input on the switch */
    return axi_ss.in_connection(translate_input_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::in_connection(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_input_port().
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out().
out_connection() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out_connection (int port) inline
Get the user output connection to the AXI stream switch.
Parameters
[in] port is port to use
Definition at line 184 of file tile_infrastructure.hpp.
{
    /* The output port for the core is actually the corresponding
       input on the switch */
    return axi_ss.in_connection(translate_input_port(port));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::in_connection(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_input_port().
output() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output (mpl p) inline
Get the output router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 239 of file tile_infrastructure.hpp.
                      {
    // No index validation required because of type safety
    return axi_ss.output(p);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output(), and p.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::rx_dma(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure().
output() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output (mpl p) inline
Get the output router port of the AXI stream switch.
Parameters
p is the master_port_layout for the stream
Definition at line 239 of file tile_infrastructure.hpp.
                      {
    // No index validation required because of type safety
    return axi_ss.output(p);
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss, trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output(), and p.
rx_dma() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::rx_dma (int id) inline
Get access to a receiver DMA.
Parameters
[in] id specifies which DMA to access
The output of the switch is actually a receiving DMA, so we can view it as a DMA
Definition at line 213 of file tile_infrastructure.hpp.
                       {
    /** The output of the switch is actually a receiving DMA, so we
        can view it as a DMA */
    return static_cast<receiving_dma<axi_ss_t>&>(*output(
        axi_ss_t::translate_port(id, mpl::dma_0, mpl::dma_last,
                                 "The receiver DMA port is out of range")));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
rx_dma() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::rx_dma (int id) inline
Get access to a receiver DMA.
Parameters
[in] id specifies which DMA to access
The output of the switch is actually a receiving DMA, so we can view it as a DMA
Definition at line 213 of file tile_infrastructure.hpp.
                       {
    /** The output of the switch is actually a receiving DMA, so we
        can view it as a DMA */
    return static_cast<receiving_dma<axi_ss_t>&>(*output(
        axi_ss_t::translate_port(id, mpl::dma_0, mpl::dma_last,
                                 "The receiver DMA port is out of range")));
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
single_task() [1/2]
template<typename Geography > template<typename Work > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::single_task (Work && f) inline
Launch an invocable on this tile.
Definition at line 245 of file tile_infrastructure.hpp.
{
    if (future_work.valid())
      throw std::logic_error("Something is already running on this tile!");
    // Launch the tile program immediately on a new executor engine
#if TRISYCL_XILINX_AIE_TILE_CODE_ON_FIBER
    future_work = fe->submit(std::forward<Work>(f));
#else
    future_work = std::async(std::launch::async, std::forward<Work>(f));
#endif
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::future_work, and trisycl::detail::fiber_pool::submit().
single_task() [2/2]
template<typename Geography > template<typename Work > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::single_task (Work && f) inline
Launch an invocable on this tile.
Definition at line 245 of file tile_infrastructure.hpp.
{
    if (future_work.valid())
      throw std::logic_error("Something is already running on this tile!");
    // Launch the tile program immediately on a new executor engine
#if TRISYCL_XILINX_AIE_TILE_CODE_ON_FIBER
    future_work = fe->submit(std::forward<Work>(f));
#else
    future_work = std::async(std::launch::async, std::forward<Work>(f));
#endif
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::future_work, and trisycl::detail::fiber_pool::submit().
translate_input_port() [1/2]
template<typename Geography > static auto trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_input_port (int port) inline static private
Map the user input port number to the AXI stream switch port.
Parameters
[in] port is the user port to use
Definition at line 103 of file tile_infrastructure.hpp.
{
    return axi_ss_t::translate_port(port, spl::me_0, spl::me_last,
                                    "The core input port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out_connection().
translate_input_port() [2/2]
template<typename Geography > static auto trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_input_port (int port) inline static private
Map the user input port number to the AXI stream switch port.
Parameters
[in] port is the user port to use
Definition at line 103 of file tile_infrastructure.hpp.
{
    return axi_ss_t::translate_port(port, spl::me_0, spl::me_last,
                                    "The core input port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
translate_output_port() [1/2]
template<typename Geography > static auto trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_output_port (int port) inline static private
Map the user output port number to the AXI stream switch port.
Parameters
[in] port is the user port to use
Definition at line 112 of file tile_infrastructure.hpp.
{
    return axi_ss_t::translate_port(port, mpl::me_0, mpl::me_last,
                                    "The core output port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in_connection().
translate_output_port() [2/2]
template<typename Geography > static auto trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::translate_output_port (int port) inline static private
Map the user output port number to the AXI stream switch port.
Parameters
[in] port is the user port to use
Definition at line 112 of file tile_infrastructure.hpp.
{
    return axi_ss_t::translate_port(port, mpl::me_0, mpl::me_last,
                                    "The core output port is out of range");
  }
References trisycl::vendor::xilinx::acap::aie::axi_stream_switch< axi_ss_geo >::translate_port.
tx_dma() [1/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dma (int id) inline
Get access to a transmit DMA.
Parameters
[in] id specifies which DMA to access
Definition at line 224 of file tile_infrastructure.hpp.
{ return *tx_dmas.at(id); }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dmas.
tx_dma() [2/2]
template<typename Geography > auto & trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dma (int id) inline
Get access to a transmit DMA.
Parameters
[in] id specifies which DMA to access
Definition at line 224 of file tile_infrastructure.hpp.
{ return *tx_dmas.at(id); }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dmas.
wait() [1/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::wait () inline
Wait for the execution of the callable on this tile.
Definition at line 257 of file tile_infrastructure.hpp.
              { if (future_work.valid())
      future_work.get();
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::future_work.
wait() [2/2]
template<typename Geography > void trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::wait () inline
Wait for the execution of the callable on this tile.
Definition at line 257 of file tile_infrastructure.hpp.
              { if (future_work.valid())
      future_work.get();
  }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::future_work.
x() [1/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x () inline
Get the horizontal coordinate.
Definition at line 160 of file tile_infrastructure.hpp.
{ return x_coordinate; }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure().
x() [2/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x () inline
Get the horizontal coordinate.
Definition at line 160 of file tile_infrastructure.hpp.
{ return x_coordinate; }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate.
y() [1/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y () inline
Get the vertical coordinate.
Definition at line 163 of file tile_infrastructure.hpp.
{ return y_coordinate; }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure().
y() [2/2]
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y () inline
Get the vertical coordinate.
Definition at line 163 of file tile_infrastructure.hpp.
{ return y_coordinate; }
References trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate.
Member Data Documentation
axi_ss
template<typename Geography > axi_ss_t trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::axi_ss private
The AXI stream switch of the core tile.
Definition at line 76 of file tile_infrastructure.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::connect(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in_connection(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::input(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out_connection(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::output(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure().
dev
template<typename Geography > void * trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::dev private
Keep track of the aie::detail::device for hardware resource control in device mode or for debugging purpose for better messages.
Use void* for now to avoid cyclic header dependencies for now instead of the aie::detail::device
Definition at line 73 of file tile_infrastructure.hpp.
future_work
template<typename Geography > std::future< void > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::future_work private
Keep track of the std::thread execution in this tile.
Definition at line 96 of file tile_infrastructure.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::single_task(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::wait().
mi
template<typename Geography > aie::memory_infrastructure trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mi private
Keep track of all the infrastructure tile memories of this device.
Definition at line 80 of file tile_infrastructure.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::mem().
tx_dmas
template<typename Geography > std::array< std::optional< sending_dma< axi_ss_t > >, axi_ss_geo::s_dma_size > trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dmas private
Sending DMAs.
Use std::optional to postpone initialization
Definition at line 86 of file tile_infrastructure.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tile_infrastructure(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::tx_dma().
x_coordinate
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x_coordinate private
Keep the horizontal coordinate.
Definition at line 62 of file tile_infrastructure.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::x().
y_coordinate
template<typename Geography > int trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y_coordinate private
Keep the vertical coordinate.
Definition at line 65 of file tile_infrastructure.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::display(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::in(), trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::out(), and trisycl::vendor::xilinx::acap::aie::detail::tile_infrastructure< Geography >::y().