triSYCL implementation of OpenCL SYCL: Some helpers for the implementation
Some helpers for the implementation
Classes
struct cl::sycl::detail::container_element_aspect< T >
A mix-in to add some container element aspects.
struct cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >
Define a multi-dimensional index, used for example to locate a work item or a buffer element.
struct cl::sycl::detail::small_array_123< BasicType, FinalType, Dims >
A small array of 1, 2 or 3 elements with the implicit constructors.
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >
Use some specializations so that some function overloads can be determined according to some implicit constructors and to have an implicit conversion from/to BasicType (such as an int typically) if Dimensions = 1.
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >
Macros
#define TRISYCL_BOOST_OPERATOR_VECTOR_OP(op)
Helper macro to declare a vector operation with the given side-effect operator.
#define TRISYCL_LOGICAL_OPERATOR_VECTOR_OP(op)
Functions
template<typename Range , typename Id >
size_t constexpr cl::sycl::detail::linear_id (Range range, Id id, Id offset={})
Compute a linearized array access used in the OpenCL 2 world.
void cl::sycl::detail::unimplemented ()
Display an "unimplemented" message.
Detailed Description
Class Documentation
cl::sycl::detail::container_element_aspect
struct cl::sycl::detail::container_element_aspect
template<typename T>
struct cl::sycl::detail::container_element_aspect< T >
A mix-in to add some container element aspects.
Definition at line 23 of file container_element_aspect.hpp.
Public Types
using value_type = T
using pointer = value_type *
using const_pointer = const value_type *
using reference = value_type &
using const_reference = const value_type &
Member Typedef Documentation
const_pointer
template<typename T> using cl::sycl::detail::container_element_aspect< T >::const_pointer = const value_type*
Definition at line 27 of file container_element_aspect.hpp.
const_reference
template<typename T> using cl::sycl::detail::container_element_aspect< T >::const_reference = const value_type&
Definition at line 29 of file container_element_aspect.hpp.
pointer
template<typename T> using cl::sycl::detail::container_element_aspect< T >::pointer = value_type*
Definition at line 26 of file container_element_aspect.hpp.
reference
template<typename T> using cl::sycl::detail::container_element_aspect< T >::reference = value_type&
Definition at line 28 of file container_element_aspect.hpp.
value_type
template<typename T> using cl::sycl::detail::container_element_aspect< T >::value_type = T
Definition at line 25 of file container_element_aspect.hpp.
cl::sycl::detail::small_array
struct cl::sycl::detail::small_array
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false>
struct cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >
Define a multi-dimensional index, used for example to locate a work item or a buffer element.
Unfortunately, even if std::array is an aggregate class allowing native list initialization, it is no longer an aggregate if we derive from an aggregate. Thus we have to redeclare the constructors.
Parameters
BasicType is the type element, such as int
Dims is the dimension number, typically between 1 and 3
FinalType is the final type, such as range<> or id<>, so that boost::operator can return the right type
EnableArgsConstructor adds a constructors from Dims variadic elements when true. It is false by default.
std::array<> provides the collection concept, with .size(), == and != too.
Definition at line 74 of file small_array.hpp.
Public Types
using element_type = BasicType
Public Member Functions
template<typename SourceType >
small_array (const SourceType src[Dims])
A constructor from another array.
BasicType & x ()
An accessor to the first variable of a small array.
BasicType & y ()
An accessor to the second variable of a small array.
BasicType & z ()
An accessor to the third variable of a small array.
template<typename SourceBasicType , typename SourceFinalType , bool SourceEnableArgsConstructor>
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
template<typename... Types, bool Depend = true, typename = typename std::enable_if_t<EnableArgsConstructor && Depend>>
small_array (const Types &... args)
Initialize the array from a list of elements.
template<typename SourceBasicType >
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
auto get (std::size_t index) const
Return the element of the array.
operator FinalType ()
Add + like operations on the id<> and others.
Public Member Functions inherited from cl::sycl::detail::display_vector< FinalType >
void display () const
To debug and test.
Static Public Attributes
static const auto dimensionality = Dims
static const size_t dimension = Dims
Member Typedef Documentation
element_type
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> using cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::element_type = BasicType
Definition at line 94 of file small_array.hpp.
Constructor & Destructor Documentation
small_array() [1/5]
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> template<typename SourceType > cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::small_array (const SourceType src[Dims]) inline
A constructor from another array.
Make it explicit to avoid spurious range<> constructions from int * for example
Definition at line 103 of file small_array.hpp.
{
     // (*this)[0] is the first element of the underlying array
     std::copy_n(src, Dims, &(*this)[0]);
   }
small_array() [2/5]
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> template<typename SourceBasicType , typename SourceFinalType , bool SourceEnableArgsConstructor> cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > & src) inline
A constructor from another small_array of the same size.
Definition at line 137 of file small_array.hpp.
{
     std::copy_n(&src[0], Dims, &(*this)[0]);
   }
small_array() [3/5]
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> template<typename... Types, bool Depend = true, typename = typename std::enable_if_t<EnableArgsConstructor && Depend>> cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::small_array (const Types &... args) inline
Initialize the array from a list of elements.
Strangely, even when using the array constructors, the initialization of the aggregate is not available. So recreate an equivalent here.
Since there are inherited types that defines some constructors with some conflicts, make it optional here, according to EnableArgsConstructor template parameter.
Definition at line 160 of file small_array.hpp.
     : std::array<BasicType, Dims> {
     // Allow a loss of precision in initialization with the static_cast
     { static_cast<BasicType>(args)... }
   }
small_array() [4/5]
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> template<typename SourceBasicType > cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::small_array (const std::array< SourceBasicType, Dims > & src) inline
Construct a small_array from a std::array.
Definition at line 174 of file small_array.hpp.
   : std::array<BasicType, Dims>(src) {}
small_array() [5/5]
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::small_array () default
Keep the synthesized constructors.
Referenced by cl::sycl::detail::small_array< BasicType, FinalType, 3 >::small_array().
Member Function Documentation
get()
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> auto cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::get (std::size_t index) const inline
Return the element of the array.
Definition at line 185 of file small_array.hpp.
{
     return (*this)[index];
   }
operator FinalType()
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::operator FinalType () inline
Add + like operations on the id<> and others.
Add - like operations on the id<> and others Add * like operations on the id<> and others Add / like operations on the id<> and others Add % like operations on the id<> and others Add << like operations on the id<> and others Add >> like operations on the id<> and others Add & like operations on the id<> and others Add ^ like operations on the id<> and others Add | like operations on the id<> and others Since the boost::operator work on the small_array, add an implicit conversion to produce the expected type
Definition at line 228 of file small_array.hpp.
{
     return *static_cast<FinalType *>(this);
   }
x()
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> BasicType& cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::x () inline
An accessor to the first variable of a small array.
Definition at line 111 of file small_array.hpp.
Referenced by cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >::small_array_123(), cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >::small_array_123(), and cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123().
                 {
     static_assert(Dims >= 1, "can't access to small_array[0] if Dims < 1");
     return (*this)[0];
   }
y()
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> BasicType& cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::y () inline
An accessor to the second variable of a small array.
Definition at line 119 of file small_array.hpp.
Referenced by cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >::small_array_123(), and cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123().
                 {
     static_assert(Dims >= 2, "can't access to small_array[1] if Dims < 2");
     return (*this)[1];
   }
z()
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> BasicType& cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::z () inline
An accessor to the third variable of a small array.
Definition at line 127 of file small_array.hpp.
Referenced by cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123().
                 {
     static_assert(Dims >= 3, "can't access to small_array[2] if Dims < 3");
     return (*this)[2];
   }
Member Data Documentation
dimension
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> const size_t cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::dimension = Dims static
Definition at line 93 of file small_array.hpp.
dimensionality
template<typename BasicType, typename FinalType, std::size_t Dims, bool EnableArgsConstructor = false> const auto cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::dimensionality = Dims static
Todo:
add this Boost::multi_array or STL concept to the specification?
Definition at line 89 of file small_array.hpp.
cl::sycl::detail::small_array_123
struct cl::sycl::detail::small_array_123
template<typename BasicType, typename FinalType, std::size_t Dims>
struct cl::sycl::detail::small_array_123< BasicType, FinalType, Dims >
A small array of 1, 2 or 3 elements with the implicit constructors.
Definition at line 237 of file small_array.hpp.
Additional Inherited Members
Public Types inherited from cl::sycl::detail::small_array< BasicType, FinalType, Dims >
using element_type = BasicType
Public Member Functions inherited from cl::sycl::detail::small_array< BasicType, FinalType, Dims >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
BasicType & x ()
An accessor to the first variable of a small array.
BasicType & y ()
An accessor to the second variable of a small array.
BasicType & z ()
An accessor to the third variable of a small array.
auto get (std::size_t index) const
Return the element of the array.
operator FinalType ()
Add + like operations on the id<> and others.
Public Member Functions inherited from cl::sycl::detail::display_vector< FinalType >
void display () const
To debug and test.
Static Public Attributes inherited from cl::sycl::detail::small_array< BasicType, FinalType, Dims >
static const auto dimensionality
static const size_t dimension
cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >
template<typename BasicType, typename FinalType>
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >
Use some specializations so that some function overloads can be determined according to some implicit constructors and to have an implicit conversion from/to BasicType (such as an int typically) if Dimensions = 1.
Definition at line 249 of file small_array.hpp.
Public Member Functions
small_array_123 (BasicType x)
A 1-D constructor to have implicit conversion from from 1 integer and automatic inference of the dimensionality.
small_array_123 ()=default
Keep other constructors.
operator BasicType () const
Conversion so that an for example an id<1> can basically be used like an integer.
Public Member Functions inherited from cl::sycl::detail::small_array< BasicType, FinalType, 1 >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
BasicType & x ()
An accessor to the first variable of a small array.
BasicType & y ()
An accessor to the second variable of a small array.
BasicType & z ()
An accessor to the third variable of a small array.
auto get (std::size_t index) const
Return the element of the array.
operator FinalType ()
Add + like operations on the id<> and others.
Public Member Functions inherited from cl::sycl::detail::display_vector< FinalType >
void display () const
To debug and test.
Additional Inherited Members
Public Types inherited from cl::sycl::detail::small_array< BasicType, FinalType, 1 >
using element_type = BasicType
Static Public Attributes inherited from cl::sycl::detail::small_array< BasicType, FinalType, 1 >
static const auto dimensionality
static const size_t dimension
Constructor & Destructor Documentation
small_array_123() [1/2]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >::small_array_123 (BasicType x) inline
A 1-D constructor to have implicit conversion from from 1 integer and automatic inference of the dimensionality.
Definition at line 253 of file small_array.hpp.
References cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::x().
{
     (*this)[0] = x;
   }
small_array_123() [2/2]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >::small_array_123 () default
Keep other constructors.
Member Function Documentation
operator BasicType()
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 1 >::operator BasicType () const inline
Conversion so that an for example an id<1> can basically be used like an integer.
Definition at line 265 of file small_array.hpp.
{
     return (*this)[0];
   }
cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >
template<typename BasicType, typename FinalType>
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >
Definition at line 272 of file small_array.hpp.
Public Member Functions
small_array_123 (BasicType x, BasicType y)
A 2-D constructor to have implicit conversion from from 2 integers and automatic inference of the dimensionality.
small_array_123 (BasicType e)
Broadcasting constructor initializing all the elements with the same value.
small_array_123 ()=default
Keep other constructors.
Public Member Functions inherited from cl::sycl::detail::small_array< BasicType, FinalType, 2 >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
BasicType & x ()
An accessor to the first variable of a small array.
BasicType & y ()
An accessor to the second variable of a small array.
BasicType & z ()
An accessor to the third variable of a small array.
auto get (std::size_t index) const
Return the element of the array.
operator FinalType ()
Add + like operations on the id<> and others.
Public Member Functions inherited from cl::sycl::detail::display_vector< FinalType >
void display () const
To debug and test.
Additional Inherited Members
Public Types inherited from cl::sycl::detail::small_array< BasicType, FinalType, 2 >
using element_type = BasicType
Static Public Attributes inherited from cl::sycl::detail::small_array< BasicType, FinalType, 2 >
static const auto dimensionality
static const size_t dimension
Constructor & Destructor Documentation
small_array_123() [1/3]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >::small_array_123 (BasicType x, BasicType y) inline
A 2-D constructor to have implicit conversion from from 2 integers and automatic inference of the dimensionality.
Definition at line 276 of file small_array.hpp.
References cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::x(), and cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::y().
{
     (*this)[0] = x;
     (*this)[1] = y;
   }
small_array_123() [2/3]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >::small_array_123 (BasicType e) inline explicit
Broadcasting constructor initializing all the elements with the same value.
Todo:
Add to the specification of the range, id...
Definition at line 287 of file small_array.hpp.
 : small_array_123 { e, e } { }
small_array_123() [3/3]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 2 >::small_array_123 () default
Keep other constructors.
cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >
template<typename BasicType, typename FinalType>
struct cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >
Definition at line 298 of file small_array.hpp.
Public Member Functions
small_array_123 (BasicType x, BasicType y, BasicType z)
A 3-D constructor to have implicit conversion from from 3 integers and automatic inference of the dimensionality.
small_array_123 (BasicType e)
Broadcasting constructor initializing all the elements with the same value.
small_array_123 ()=default
Keep other constructors.
Public Member Functions inherited from cl::sycl::detail::small_array< BasicType, FinalType, 3 >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
BasicType & x ()
An accessor to the first variable of a small array.
BasicType & y ()
An accessor to the second variable of a small array.
BasicType & z ()
An accessor to the third variable of a small array.
auto get (std::size_t index) const
Return the element of the array.
operator FinalType ()
Add + like operations on the id<> and others.
Public Member Functions inherited from cl::sycl::detail::display_vector< FinalType >
void display () const
To debug and test.
Additional Inherited Members
Public Types inherited from cl::sycl::detail::small_array< BasicType, FinalType, 3 >
using element_type = BasicType
Static Public Attributes inherited from cl::sycl::detail::small_array< BasicType, FinalType, 3 >
static const auto dimensionality
static const size_t dimension
Constructor & Destructor Documentation
small_array_123() [1/3]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123 (BasicType x, BasicType y, BasicType z) inline
A 3-D constructor to have implicit conversion from from 3 integers and automatic inference of the dimensionality.
Definition at line 302 of file small_array.hpp.
References cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::x(), cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::y(), and cl::sycl::detail::small_array< BasicType, FinalType, Dims, EnableArgsConstructor >::z().
{
     (*this)[0] = x;
     (*this)[1] = y;
     (*this)[2] = z;
   }
small_array_123() [2/3]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123 (BasicType e) inline explicit
Broadcasting constructor initializing all the elements with the same value.
Todo:
Add to the specification of the range, id...
Definition at line 314 of file small_array.hpp.
 : small_array_123 { e, e, e } { }
small_array_123() [3/3]
template<typename BasicType , typename FinalType > cl::sycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123 () default
Keep other constructors.
Macro Definition Documentation
TRISYCL_BOOST_OPERATOR_VECTOR_OP
#define TRISYCL_BOOST_OPERATOR_VECTOR_OP (op)
#include <include/CL/sycl/detail/small_array.hpp>
Value:
FinalType operator op(const FinalType &rhs) {         \
    for (std::size_t i = 0; i != Dims; ++i)             \
      (*this)[i] op rhs[i];                             \
    return *this;                                       \
  }
Helper macro to declare a vector operation with the given side-effect operator.
Definition at line 33 of file small_array.hpp.
Referenced by cl::sycl::detail::small_array< BasicType, FinalType, 3 >::get().
TRISYCL_LOGICAL_OPERATOR_VECTOR_OP
#define TRISYCL_LOGICAL_OPERATOR_VECTOR_OP (op)
#include <include/CL/sycl/detail/small_array.hpp>
Value:
FinalType operator op(const FinalType &rhs) {         \
    FinalType res;                                      \
    for (std::size_t i = 0; i != Dims; ++i)             \
      res[i] = (*this)[i] op rhs[i];                    \
    return res;                                         \
  }
Definition at line 41 of file small_array.hpp.
Referenced by cl::sycl::detail::small_array< BasicType, FinalType, 3 >::get().
Function Documentation
linear_id()
template<typename Range , typename Id > size_t constexpr cl::sycl::detail::linear_id (Range range, Id id, Id offset = {}) inline
#include <include/CL/sycl/detail/linear_id.hpp>
Compute a linearized array access used in the OpenCL 2 world.
Typically for the get_global_linear_id() and get_local_linear_id() functions.
Definition at line 28 of file linear_id.hpp.
Referenced by cl::sycl::nd_item< Dimensions >::get_global_linear_id(), cl::sycl::nd_item< Dimensions >::get_group_linear_id(), cl::sycl::group< Dimensions >::get_linear(), cl::sycl::item< Dimensions >::get_linear_id(), and cl::sycl::nd_item< Dimensions >::get_local_linear_id().
                                                                   {}) {
   auto dims = std::distance(std::begin(range), std::end(range));
   size_t linear_id = 0;
   /* A good compiler should unroll this and do partial evaluation to
      remove the first multiplication by 0 of this Horner evaluation and
      remove the 0 offset evaluation */
     for (int i = dims - 1; i >= 0; --i)
       linear_id = linear_id*range[i] + id[i] - offset[i];
     return linear_id;
   }
unimplemented()
void cl::sycl::detail::unimplemented () inline
#include <include/CL/sycl/detail/unimplemented.hpp>
Display an "unimplemented" message.
Can be changed to call assert(0) or whatever.
Definition at line 25 of file unimplemented.hpp.
Referenced by cl::sycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor(), cl::sycl::nd_item< Dimensions >::barrier(), cl::sycl::buffer< T, Dimensions, Allocator >::buffer(), cl::sycl::context::context(), cl::sycl::kernel::get(), cl::sycl::detail::opencl_kernel::get_boost_compute(), cl::sycl::detail::opencl_context::get_devices(), cl::sycl::context::get_devices(), cl::sycl::context::get_info(), cl::sycl::queue::get_info(), cl::sycl::detail::host_context::get_platform(), cl::sycl::detail::opencl_device::get_platform(), cl::sycl::detail::host_device::get_platform(), cl::sycl::detail::opencl_context::get_platform(), cl::sycl::detail::host_platform::has_extension(), cl::sycl::detail::opencl_device::has_extension(), cl::sycl::detail::host_device::has_extension(), cl::sycl::detail::opencl_context::is_host(), cl::sycl::platform::platform(), cl::sycl::queue::queue(), cl::sycl::queue::submit(), cl::sycl::queue::throw_asynchronous(), and cl::sycl::queue::wait_and_throw().
{
 #ifndef NDEBUG
   std::cerr << "Error: using a non implemented feature!!!" << std::endl
             << "Please contribute to the open source implementation. :-)"
             << std::endl;
 #endif
 }