triSYCL implementation of SYCL: Xilinx vendor extensions
Xilinx vendor extensions
Namespaces
namespace trisycl
The vector type to be used as SYCL vector.
namespace trisycl::vendor
namespace trisycl::vendor::xilinx
namespace trisycl::vendor::xilinx::partition
Kind of array partition.
Classes
struct trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >
Define an array class with partition feature.
Macros
#define _ssdm_op_SpecDataflowPipeline(...) do { } while (0)
#define _ssdm_op_SpecPipeline(...) do { } while (0)
#define _ssdm_SpecArrayPartition(...) do { } while (0)
#define _ssdm_op_SpecDataflowPipeline(...) do { } while (0)
#define _ssdm_op_SpecPipeline(...) do { } while (0)
#define _ssdm_SpecArrayPartition(...) do { } while (0)
Detailed Description
Class Documentation
trisycl::vendor::xilinx::partition_array
struct trisycl::vendor::xilinx::partition_array
template<typename ValueType, std::size_t Size, typename PartitionType = partition::none>
struct trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >
Define an array class with partition feature.
Since on FPGA, users can customize the memory architecture in the system and within the CU. Array partition help us to partition single array to multiple memories that can be accessed simultaneously getting higher memory bandwidth.
Parameters
ValueType is the type of element.
Size is the size of the array.
PartitionType is the array partition type: cyclic, block, and complete. The default type is none.
Todo:
Deal with multi-dimension array.
Since on FPGA, users can customize the memory architecture in the system and within the CU. Array partition help us to partition single array to multiple memories that can be accessed simultaneously getting higher memory bandwidth.
Parameters
ValueType is the type of element.
Size is the size of the array.
PartitionType is the array partition type: cyclic, block, and complete. The default type is none.
Todo:
Deal with multi-dimension array.
Definition at line 154 of file partition_array.hpp.
Public Types
using element_type = ValueType
Type of array elements.
using element_type = ValueType
Type of array elements.
Public Member Functions
auto begin ()
Provide iterator.
const auto begin () const
auto end ()
const auto end () const
constexpr auto size () const noexcept
Evaluate size.
partition_array ()
Construct an array.
template<typename SomeContainer >
partition_array (const SomeContainer &src)
A constructor from some container.
template<typename SourceBasicType , typename = std::enable_if_t<std::is_convertible<SourceBasicType, ValueType>::value>>
constexpr partition_array (std::initializer_list< SourceBasicType > l)
Construct an array from initializer_list.
constexpr ValueType & operator[] (std::size_t i)
Provide a subscript operator.
constexpr const ValueType & operator[] (std::size_t i) const
constexpr auto get_partition_type () const
Return the partition type of the array.
auto begin ()
Provide iterator.
const auto begin () const
auto end ()
const auto end () const
constexpr auto size () const noexcept
Evaluate size.
partition_array ()
Construct an array.
template<typename SomeContainer >
partition_array (const SomeContainer &src)
A constructor from some container.
template<typename SourceBasicType , typename = std::enable_if_t<std::is_convertible<SourceBasicType, ValueType>::value>>
constexpr partition_array (std::initializer_list< SourceBasicType > l)
Construct an array from initializer_list.
constexpr ValueType & operator[] (std::size_t i)
Provide a subscript operator.
constexpr const ValueType & operator[] (std::size_t i) const
constexpr auto get_partition_type () const
Return the partition type of the array.
Public Attributes
ValueType elems [Size]
Store the array elements.
Static Public Attributes
static constexpr auto array_size = Size
The number of elements of the 1-D array.
static constexpr auto partition_type = PartitionType::partition_type
The kind of partitioning.
Member Typedef Documentation
element_type [1/2]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> using trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::element_type = ValueType
Type of array elements.
Definition at line 166 of file partition_array.hpp.
element_type [2/2]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> using trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::element_type = ValueType
Type of array elements.
Definition at line 166 of file partition_array.hpp.
Constructor & Destructor Documentation
partition_array() [1/6]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array () inline
Construct an array.
Definition at line 183 of file partition_array.hpp.
                    {
    // Add the intrinsic according expressing to the target compiler the
    // partitioning to use
    if constexpr (partition_type == partition::type::cyclic)
      _ssdm_SpecArrayPartition(&(*this)[0], PartitionType::partition_dim,
                               "CYCLIC", PartitionType::physical_mem_num, "");
    if constexpr (partition_type == partition::type::block)
      _ssdm_SpecArrayPartition(&(*this)[0], PartitionType::partition_dim,
                               "BLOCK", PartitionType::ele_in_each_physical_mem,
                               "");
    if constexpr (partition_type == partition::type::complete)
      _ssdm_SpecArrayPartition(&(*this)[0], PartitionType::partition_dim,
                               "COMPLETE", 0, "");
  }
References _ssdm_SpecArrayPartition, trisycl::vendor::xilinx::partition::block, trisycl::vendor::xilinx::partition::complete, trisycl::vendor::xilinx::partition::cyclic, and trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_type.
partition_array() [2/6]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> template<typename SomeContainer > trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array (const SomeContainer & src) inline
A constructor from some container.
Todo:
Find a way to specialize this with a safer implementation when the size of src is at least constexpr
Definition at line 201 of file partition_array.hpp.
    : partition_array { } {
    /// \todo Find a way to specialize this with a safer
    /// implementation when the size of src is at least constexpr
    std::copy_n(std::begin(src), Size, begin());
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin(), and src.
partition_array() [3/6]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> template<typename SourceBasicType , typename = std::enable_if_t<std::is_convertible<SourceBasicType, ValueType>::value>> constexpr trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array (std::initializer_list< SourceBasicType > l) inline constexpr
Construct an array from initializer_list.
Todo:
Find a way to specialize this with a safer implementation when the size of src is at least constexpr This does not work... static_assert(l.size() == Size);
Definition at line 216 of file partition_array.hpp.
    : partition_array { } {
    /// \todo Find a way to specialize this with a safer
    /// implementation when the size of src is at least constexpr
    /// This does not work...
    /// static_assert(l.size() == Size);
    std::copy_n(std::begin(l), Size, begin());
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin().
partition_array() [4/6]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array () inline
Construct an array.
Definition at line 183 of file partition_array.hpp.
                    {
    // Add the intrinsic according expressing to the target compiler the
    // partitioning to use
    if constexpr (partition_type == partition::type::cyclic)
      _ssdm_SpecArrayPartition(&(*this)[0], PartitionType::partition_dim,
                               "CYCLIC", PartitionType::physical_mem_num, "");
    if constexpr (partition_type == partition::type::block)
      _ssdm_SpecArrayPartition(&(*this)[0], PartitionType::partition_dim,
                               "BLOCK", PartitionType::ele_in_each_physical_mem,
                               "");
    if constexpr (partition_type == partition::type::complete)
      _ssdm_SpecArrayPartition(&(*this)[0], PartitionType::partition_dim,
                               "COMPLETE", 0, "");
  }
References _ssdm_SpecArrayPartition, trisycl::vendor::xilinx::partition::block, trisycl::vendor::xilinx::partition::complete, trisycl::vendor::xilinx::partition::cyclic, and trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_type.
partition_array() [5/6]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> template<typename SomeContainer > trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array (const SomeContainer & src) inline
A constructor from some container.
Todo:
Find a way to specialize this with a safer implementation when the size of src is at least constexpr
Definition at line 201 of file partition_array.hpp.
    : partition_array { } {
    /// \todo Find a way to specialize this with a safer
    /// implementation when the size of src is at least constexpr
    std::copy_n(std::begin(src), Size, begin());
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin(), and src.
partition_array() [6/6]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> template<typename SourceBasicType , typename = std::enable_if_t<std::is_convertible<SourceBasicType, ValueType>::value>> constexpr trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array (std::initializer_list< SourceBasicType > l) inline constexpr
Construct an array from initializer_list.
Todo:
Find a way to specialize this with a safer implementation when the size of src is at least constexpr This does not work... static_assert(l.size() == Size);
Definition at line 216 of file partition_array.hpp.
    : partition_array { } {
    /// \todo Find a way to specialize this with a safer
    /// implementation when the size of src is at least constexpr
    /// This does not work...
    /// static_assert(l.size() == Size);
    std::copy_n(std::begin(l), Size, begin());
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin().
Member Function Documentation
begin() [1/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin () inline
Provide iterator.
Definition at line 170 of file partition_array.hpp.
{ return elems; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
Referenced by trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array().
begin() [2/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin () inline
Provide iterator.
Definition at line 170 of file partition_array.hpp.
{ return elems; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
begin() [3/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> const auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin () const inline
Definition at line 171 of file partition_array.hpp.
{ return elems; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
begin() [4/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> const auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin () const inline
Definition at line 171 of file partition_array.hpp.
{ return elems; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
end() [1/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::end () inline
Definition at line 172 of file partition_array.hpp.
{ return elems+Size; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
end() [2/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::end () inline
Definition at line 172 of file partition_array.hpp.
{ return elems+Size; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
end() [3/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> const auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::end () const inline
Definition at line 173 of file partition_array.hpp.
{ return elems+Size; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
end() [4/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> const auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::end () const inline
Definition at line 173 of file partition_array.hpp.
{ return elems+Size; }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems.
get_partition_type() [1/2]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::get_partition_type () const inline constexpr
Return the partition type of the array.
Definition at line 238 of file partition_array.hpp.
{
    return partition_type;
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_type.
get_partition_type() [2/2]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::get_partition_type () const inline constexpr
Return the partition type of the array.
Definition at line 238 of file partition_array.hpp.
{
    return partition_type;
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_type.
operator[]() [1/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr ValueType & trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::operator[] (std::size_t i) inline constexpr
Provide a subscript operator.
Definition at line 227 of file partition_array.hpp.
{
    return elems[i];
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems, and i.
operator[]() [2/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr ValueType & trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::operator[] (std::size_t i) inline constexpr
Provide a subscript operator.
Definition at line 227 of file partition_array.hpp.
{
    return elems[i];
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems, and i.
operator[]() [3/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr const ValueType & trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::operator[] (std::size_t i) const inline constexpr
Definition at line 232 of file partition_array.hpp.
{
    return elems[i];
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems, and i.
operator[]() [4/4]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr const ValueType & trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::operator[] (std::size_t i) const inline constexpr
Definition at line 232 of file partition_array.hpp.
{
    return elems[i];
  }
References trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems, and i.
size() [1/2]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::size () const inline constexpr noexcept
Evaluate size.
Definition at line 177 of file partition_array.hpp.
{
    return Size;
  }
size() [2/2]
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> constexpr auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::size () const inline constexpr noexcept
Evaluate size.
Definition at line 177 of file partition_array.hpp.
{
    return Size;
  }
Member Data Documentation
array_size
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> static constexpr auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::array_size = Size static constexpr
The number of elements of the 1-D array.
Definition at line 162 of file partition_array.hpp.
elems
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> ValueType trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::elems
Store the array elements.
Note that it means default initialization for partition_array elements, which is lazily convenient for heterogeneous computing
Definition at line 160 of file partition_array.hpp.
Referenced by trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::begin(), trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::end(), and trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::operator[]().
partition_type
template<typename ValueType , std::size_t Size, typename PartitionType = partition::none> static constexpr auto trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_type = PartitionType::partition_type static constexpr
The kind of partitioning.
Definition at line 164 of file partition_array.hpp.
Referenced by trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::get_partition_type(), and trisycl::vendor::xilinx::partition_array< ValueType, Size, PartitionType >::partition_array().
Macro Definition Documentation
_ssdm_op_SpecDataflowPipeline [1/2]
#define _ssdm_op_SpecDataflowPipeline (...) do { } while (0)
#include <include/sycl/vendor/Xilinx/fpga/ssdm_inst.hpp>
Definition at line 29 of file ssdm_inst.hpp.
_ssdm_op_SpecDataflowPipeline [2/2]
#define _ssdm_op_SpecDataflowPipeline (...) do { } while (0)
#include <include/triSYCL/vendor/Xilinx/fpga/ssdm_inst.hpp>
Definition at line 29 of file ssdm_inst.hpp.
_ssdm_op_SpecPipeline [1/2]
#define _ssdm_op_SpecPipeline (...) do { } while (0)
#include <include/sycl/vendor/Xilinx/fpga/ssdm_inst.hpp>
Definition at line 30 of file ssdm_inst.hpp.
_ssdm_op_SpecPipeline [2/2]
#define _ssdm_op_SpecPipeline (...) do { } while (0)
#include <include/triSYCL/vendor/Xilinx/fpga/ssdm_inst.hpp>
Definition at line 30 of file ssdm_inst.hpp.
_ssdm_SpecArrayPartition [1/2]
#define _ssdm_SpecArrayPartition (...) do { } while (0)
#include <include/sycl/vendor/Xilinx/fpga/ssdm_inst.hpp>
Definition at line 31 of file ssdm_inst.hpp.
_ssdm_SpecArrayPartition [2/2]
#define _ssdm_SpecArrayPartition (...) do { } while (0)
#include <include/triSYCL/vendor/Xilinx/fpga/ssdm_inst.hpp>
Definition at line 31 of file ssdm_inst.hpp.