triSYCL implementation of SYCL: Expressing parallelism through kernels
Expressing parallelism through kernels
Namespaces
trisycl::detail
Classes
struct trisycl::group< Dimensions >
A group index used in a parallel_for_workitem to specify a work_group.
struct trisycl::h_item< Dimensions >
h_item<int dimensions> identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range<int dimensions> passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call if no range is passed to the parallel_for_work_item call.
class trisycl::id< Dimensions >
Define a multi-dimensional index, used for example to locate a work item.
class trisycl::item< Dimensions, with_offset >
A SYCL item stores information on a work-item with some more context such as the definition range and offset.
struct trisycl::nd_item< Dimensions >
A SYCL nd_item stores information on a work-item within a work-group, with some more context such as the definition ranges.
struct trisycl::nd_range< Dimensions >
A ND-range, made by a global and local range, to specify work-group and work-item organization.
struct trisycl::detail::parallel_for_iterate< level, Range, ParallelForFunctor, Id >
A recursive multi-dimensional iterator that ends up calling f.
struct trisycl::detail::parallel_for_iterate< 0, Range, ParallelForFunctor, Id >
Stop the recursion when level reaches 0 by simply calling the kernel functor with the constructed id.
class trisycl::range< Dimensions >
A SYCL range defines a multi-dimensional index range that can be used to define launch parallel computation extent or buffer sizes.
Functions
auto trisycl::make_id (id< 1 > i)
Implement a make_id to construct an id<> of the right dimension with implicit conversion from an initializer list for example.
auto trisycl::make_id (id< 2 > i)
auto trisycl::make_id (id< 3 > i)
template<typename... BasicType>
auto trisycl::make_id (BasicType... Args)
Construct an id<> from a function call with arguments, like make_id(1, 2, 3)
template<int Dimensions = 1, typename ParallelForFunctor , typename Id >
void trisycl::detail::parallel_for (range< Dimensions > r, ParallelForFunctor f, Id)
Implementation of a data parallel computation with parallelism specified at launch time by a range<>.
template<int Dimensions = 1, typename ParallelForFunctor >
void trisycl::detail::parallel_for (range< Dimensions > r, ParallelForFunctor f, item< Dimensions >)
Implementation of a data parallel computation with parallelism specified at launch time by a range<>.
template<typename F , typename R , typename A >
auto trisycl::detail::capture_arg_v (R(F::*)(A))
template<int Dimensions = 1, typename ParallelForFunctor >
void trisycl::detail::parallel_for (range< Dimensions > r, ParallelForFunctor f)
Calls the appropriate ternary parallel_for overload based on the index type of the kernel function object f.
template<int Dimensions = 1, typename ParallelForFunctor >
void trisycl::detail::parallel_for_global_offset (range< Dimensions > global_size, id< Dimensions > offset, ParallelForFunctor f)
Implementation of parallel_for with a range<> and an offset.
template<int Dimensions = 1, typename ParallelForFunctor >
void trisycl::detail::parallel_for_workgroup (nd_range< Dimensions > r, ParallelForFunctor f)
Implement the loop on the work-groups.
template<int Dimensions, typename T_Item , typename ParallelForFunctor >
void trisycl::detail::parallel_for_workitem (const group< Dimensions > &g, ParallelForFunctor f)
Implement the loop on the work-items inside a work-group.
template<int Dimensions = 1, typename ParallelForFunctor >
void trisycl::detail::parallel_for (nd_range< Dimensions > r, ParallelForFunctor f)
Implement a variation of parallel_for to take into account a nd_range<>
template<int Dimensions = 1, typename ParallelForFunctor >
void trisycl::detail::parallel_for_workitem_in_group (const group< Dimensions > &g, ParallelForFunctor f)
Implement the loop on the work-items inside a work-group.
static auto trisycl::detail::to_tbb_range (const range< 1 > &r)
static auto trisycl::detail::to_tbb_range (const range< 2 > &r)
static auto trisycl::detail::to_tbb_range (const range< 3 > &r)
static auto trisycl::detail::to_sycl_id (const tbb::blocked_range< size_t > &in)
static auto trisycl::detail::to_sycl_id (const tbb::blocked_range2d< size_t > &in)
static auto trisycl::detail::to_sycl_id (const tbb::blocked_range3d< size_t > &in)
template<typename Range , typename ParallelForFunctor >
void trisycl::detail::parallel_for_iterate (Range r, ParallelForFunctor &f)
auto trisycl::make_range (range< 1 > r)
Implement a make_range to construct a range<> of the right dimension with implicit conversion from an initializer list for example.
auto trisycl::make_range (range< 2 > r)
auto trisycl::make_range (range< 3 > r)
template<typename... BasicType>
auto trisycl::make_range (BasicType... Args)
Construct a range<> from a function call with arguments, like make_range(1, 2, 3)
Detailed Description
Class Documentation
trisycl::group
struct trisycl::group
template<int Dimensions>
struct trisycl::group< Dimensions >
A group index used in a parallel_for_workitem to specify a work_group.
Definition at line 24 of file group.hpp.
Public Member Functions
group (const nd_range< Dimensions > &ndr)
Create a group from an nd_range<> with a 0 id<>
group (const id< Dimensions > &i, const nd_range< Dimensions > &ndr)
Create a group from an id and a nd_range<>
group ()=default
To be able to copy and assign group, use default constructors too.
id< Dimensions > get_id () const
Return an id representing the index of the group within the nd_range for every dimension.
size_t get_id (int dimension) const
Return the index of the group in the given dimension.
auto & operator[] (int dimension)
Return the index of the group in the given dimension within the nd_range<>
range< Dimensions > get_group_range () const
Return a range<> representing the dimensions of the current group.
size_t get_group_range (int dimension) const
Return element dimension from the con stituent group range.
range< Dimensions > get_global_range () const
Get the local range for this work_group.
size_t get_global_range (int dimension) const
Return element dimension from the constituent global range.
range< Dimensions > get_local_range () const
Get the local range for this work_group.
size_t get_local_range (int dimension) const
Return element dimension from the constituent local range.
id< Dimensions > get_offset () const
Get the offset of the NDRange.
size_t get_offset (int dimension) const
Get the offset of the NDRange.
nd_range< Dimensions > get_nd_range () const
size_t get_linear_id () const
Get a linearized version of the group ID.
void parallel_for_work_item (std::function< void(h_item< dimensionality >)> f) const
Loop on the work-items inside a work-group.
bool operator== (const group &groupB) const
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Attributes
id< Dimensions > group_id
The coordinate of the group item.
nd_range< Dimensions > ndr
Keep a reference on the nd_range to serve potential query on it.
Constructor & Destructor Documentation
group() [1/3]
template<int Dimensions> trisycl::group< Dimensions >::group (const nd_range< Dimensions > & ndr) inline
Create a group from an nd_range<> with a 0 id<>
Todo:
This should be private since it is only used by the triSYCL implementation
Definition at line 61 of file group.hpp.
 : ndr { ndr } {}
group() [2/3]
template<int Dimensions> trisycl::group< Dimensions >::group (const id< Dimensions > & i, const nd_range< Dimensions > & ndr) inline
Create a group from an id and a nd_range<>
Todo:
This should be private somehow, but it is used by the validation infrastructure
Definition at line 69 of file group.hpp.
                                                                    :
     group_id { i }, ndr { ndr } {}
group() [3/3]
template<int Dimensions> trisycl::group< Dimensions >::group () default
To be able to copy and assign group, use default constructors too.
Todo:
Make most of them protected, reserved to implementation
Member Function Documentation
get_global_range() [1/2]
template<int Dimensions> range<Dimensions> trisycl::group< Dimensions >::get_global_range () const inline
Get the local range for this work_group.
Definition at line 122 of file group.hpp.
{
     return get_nd_range().get_global_range();
   }
get_global_range() [2/2]
template<int Dimensions> size_t trisycl::group< Dimensions >::get_global_range (int dimension) const inline
Return element dimension from the constituent global range.
Definition at line 128 of file group.hpp.
{
     return get_global_range()[dimension];
   }
get_group_range() [1/2]
template<int Dimensions> range<Dimensions> trisycl::group< Dimensions >::get_group_range () const inline
Return a range<> representing the dimensions of the current group.
This local range may have been provided by the programmer, or chosen by the runtime.
Todo:
Fix this comment and the specification
Definition at line 110 of file group.hpp.
{
     return get_nd_range().get_group_range();
   }
get_group_range() [2/2]
template<int Dimensions> size_t trisycl::group< Dimensions >::get_group_range (int dimension) const inline
Return element dimension from the con stituent group range.
Definition at line 116 of file group.hpp.
{
     return get_group_range()[dimension];
   }
get_id() [1/2]
template<int Dimensions> id<Dimensions> trisycl::group< Dimensions >::get_id () const inline
Return an id representing the index of the group within the nd_range for every dimension.
Definition at line 83 of file group.hpp.
Referenced by trisycl::detail::parallel_for_iterate(), and trisycl::detail::parallel_for_workitem().
 { return group_id; }
get_id() [2/2]
template<int Dimensions> size_t trisycl::group< Dimensions >::get_id (int dimension) const inline
Return the index of the group in the given dimension.
Definition at line 87 of file group.hpp.
References trisycl::group< Dimensions >::get_id().
Referenced by trisycl::group< Dimensions >::get_id().
 { return get_id()[dimension]; }
get_linear_id()
template<int Dimensions> size_t trisycl::group< Dimensions >::get_linear_id () const inline
Get a linearized version of the group ID.
Definition at line 172 of file group.hpp.
References trisycl::detail::linear_id().
{
     return detail::linear_id(get_group_range(), get_id());
   }
get_local_range() [1/2]
template<int Dimensions> range<Dimensions> trisycl::group< Dimensions >::get_local_range () const inline
Get the local range for this work_group.
Todo:
Add to the specification
Definition at line 137 of file group.hpp.
Referenced by trisycl::detail::parallel_for_iterate(), and trisycl::detail::parallel_for_workitem().
{
     return get_nd_range().get_local_range();
   }
get_local_range() [2/2]
template<int Dimensions> size_t trisycl::group< Dimensions >::get_local_range (int dimension) const inline
Return element dimension from the constituent local range.
Todo:
Add to the specification
Definition at line 146 of file group.hpp.
{
     return get_local_range()[dimension];
   }
get_nd_range()
template<int Dimensions> nd_range<Dimensions> trisycl::group< Dimensions >::get_nd_range () const inline
Todo:
Also provide this access to the current nd_range
Definition at line 166 of file group.hpp.
Referenced by trisycl::detail::parallel_for_iterate(), and trisycl::detail::parallel_for_workitem().
 { return ndr; }
get_offset() [1/2]
template<int Dimensions> id<Dimensions> trisycl::group< Dimensions >::get_offset () const inline
Get the offset of the NDRange.
Todo:
Add to the specification
Definition at line 155 of file group.hpp.
 { return get_nd_range().get_offset(); }
get_offset() [2/2]
template<int Dimensions> size_t trisycl::group< Dimensions >::get_offset (int dimension) const inline
Get the offset of the NDRange.
Todo:
Add to the specification
Definition at line 162 of file group.hpp.
References trisycl::group< Dimensions >::get_offset().
Referenced by trisycl::group< Dimensions >::get_offset().
 { return get_offset()[dimension]; }
operator==()
template<int Dimensions> bool trisycl::group< Dimensions >::operator== (const group< Dimensions > & groupB) const inline
Definition at line 186 of file group.hpp.
References trisycl::group< Dimensions >::group_id, and trisycl::group< Dimensions >::ndr.
{
     return (group_id == groupB.group_id &&
         ndr == groupB.ndr);
   }
operator[]()
template<int Dimensions> auto& trisycl::group< Dimensions >::operator[] (int dimension) inline
Return the index of the group in the given dimension within the nd_range<>
Todo:
In this implementation it is not const because the group<> is written in the parallel_for iterators. To fix according to the specification
Definition at line 97 of file group.hpp.
{
     return group_id[dimension];
   }
parallel_for_work_item()
template<int Dimensions> void trisycl::group< Dimensions >::parallel_for_work_item (std::function< void(h_item< dimensionality >)> f) const inline
Loop on the work-items inside a work-group.
Definition at line 179 of file group.hpp.
References trisycl::detail::parallel_for_workitem_in_group().
           {
     detail::parallel_for_workitem_in_group(*this, f);
   }
Member Data Documentation
dimensionality
template<int Dimensions> constexpr auto trisycl::group< Dimensions >::dimensionality = Dimensions static
Todo:
add this Boost::multi_array or STL concept to the specification?
Definition at line 44 of file group.hpp.
group_id
template<int Dimensions> id<Dimensions> trisycl::group< Dimensions >::group_id private
The coordinate of the group item.
Definition at line 49 of file group.hpp.
Referenced by trisycl::group< Dimensions >::operator==().
ndr
template<int Dimensions> nd_range<Dimensions> trisycl::group< Dimensions >::ndr private
Keep a reference on the nd_range to serve potential query on it.
Definition at line 52 of file group.hpp.
Referenced by trisycl::group< Dimensions >::operator==().
trisycl::h_item
struct trisycl::h_item
template<int Dimensions = 1>
struct trisycl::h_item< Dimensions >
h_item<int dimensions> identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range<int dimensions> passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call if no range is passed to the parallel_for_work_item call.
It encapsulates enough information to identify the work-items local and global items according to the information given to parallel_for_work_group (physical ids) as well as the work-items logical local items in the flexible range. All returned items objects are offset-less. Instances of the h_item<int dimensions> class are not user-constructible and are passed by the runtime to each instance of the function object.
Definition at line 42 of file h_item.hpp.
Public Member Functions
h_item (nd_range< Dimensions > ndr)
Create an empty nd_item<> from an nd_range<>
h_item (id< Dimensions > global_index, nd_range< Dimensions > ndr)
Create a full nd_item.
h_item ()=default
To be able to copy and assign nd_item, use default constructors too.
id< Dimensions > get_global_id () const
Return the constituent global id representing the work-item's position in the global iteration space.
size_t get_global_id (int dimension) const
Return the constituent element of the global id representing the work-item's position in the global iteration space in the given dimension.
size_t get_global_linear_id () const
Return the flattened id of the current work-item after subtracting the offset.
id< Dimensions > get_local_id () const
Return the constituent local id representing the work-item's position within the current work-group.
size_t get_local_id (int dimension) const
Return the constituent element of the local id representing the work-item's position within the current work-group in the given dimension.
size_t get_local_linear_id () const
Return the flattened id of the current work-item within the current work-group.
id< Dimensions > get_group () const
Return the constituent group group representing the work-group's position within the overall nd_range.
size_t get_group (int dimension) const
Return the constituent element of the group id representing the work-group's position within the overall nd_range in the given dimension.
size_t get_group_linear_id () const
Return the flattened id of the current work-group.
id< Dimensions > get_group_range () const
Return the number of groups in the nd_range.
size_t get_group_range (int dimension) const
Return the number of groups for dimension in the nd_range.
range< Dimensions > get_global_range () const
Return a range<> representing the dimensions of the nd_range<>
range< Dimensions > get_local_range () const
Return a range<> representing the dimensions of the current work-group.
id< Dimensions > get_offset () const
Return an id<> representing the n-dimensional offset provided to the constructor of the nd_range<> and that is added by the runtime to the global-ID of each work-item.
nd_range< Dimensions > get_nd_range () const
Return the nd_range<> of the current execution.
item< Dimensions > get_item () const
Allows projection down to an item.
void barrier (access::fence_space flag=access::fence_space::global_and_local) const
Execute a barrier with memory ordering on the local address space, global address space or both based on the value of flag.
void set_local (id< Dimensions > Index)
void set_global (id< Dimensions > Index)
bool operator== (const h_item< Dimensions > &itemB) const
comparison operators
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Attributes
id< Dimensions > global_index
id< Dimensions > local_index
nd_range< Dimensions > ND_range
Constructor & Destructor Documentation
h_item() [1/3]
template<int Dimensions = 1> trisycl::h_item< Dimensions >::h_item (nd_range< Dimensions > ndr) inline
Create an empty nd_item<> from an nd_range<>
Todo:
This is for the triSYCL implementation which is expected to call set_global() and set_local() later. This should be hidden to the user.
Definition at line 63 of file h_item.hpp.
 : ND_range { ndr } {}
h_item() [2/3]
template<int Dimensions = 1> trisycl::h_item< Dimensions >::h_item (id< Dimensions > global_index, nd_range< Dimensions > ndr) inline
Create a full nd_item.
Todo:
This is for validation purpose. Hide this to the programmer somehow
Definition at line 71 of file h_item.hpp.
References trisycl::h_item< Dimensions >::h_item().
                                     :
     global_index { global_index },
     // Compute the local index using the offset and the group size
     local_index
       { (global_index - ndr.get_offset())%id<Dimensions> { ndr.get_local() } },
     ND_range { ndr }
   {}
h_item() [3/3]
template<int Dimensions = 1> trisycl::h_item< Dimensions >::h_item () default
To be able to copy and assign nd_item, use default constructors too.
Todo:
Make most of them protected, reserved to implementation
Referenced by trisycl::h_item< Dimensions >::h_item().
Member Function Documentation
barrier()
template<int Dimensions = 1> void trisycl::h_item< Dimensions >::barrier (access::fence_space flag = access::fence_space::global_and_local) const inline
Execute a barrier with memory ordering on the local address space, global address space or both based on the value of flag.
The current work-item will wait at the barrier until all work-items in the current work-group have reached the barrier.
In addition, the barrier performs a fence operation ensuring that all memory accesses in the specified address space issued before the barrier complete before those issued after the barrier
Definition at line 210 of file h_item.hpp.
References TRISYCL_UNIMPL.
{
 #if defined(_OPENMP) && !defined(TRISYCL_NO_BARRIER)
     /* Use OpenMP barrier in the implementation with 1 OpenMP thread per
        work-item of the work-group */
 #pragma omp barrier
 #else
     // \todo To be implemented efficiently otherwise
     TRISYCL_UNIMPL;
 #endif
   }
get_global_id() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::h_item< Dimensions >::get_global_id () const inline
Return the constituent global id representing the work-item's position in the global iteration space.
Definition at line 91 of file h_item.hpp.
References trisycl::h_item< Dimensions >::global_index.
Referenced by trisycl::h_item< Dimensions >::get_global_id(), trisycl::h_item< Dimensions >::get_global_linear_id(), trisycl::h_item< Dimensions >::get_group(), and trisycl::h_item< Dimensions >::get_item().
 { return global_index; }
get_global_id() [2/2]
template<int Dimensions = 1> size_t trisycl::h_item< Dimensions >::get_global_id (int dimension) const inline
Return the constituent element of the global id representing the work-item's position in the global iteration space in the given dimension.
Definition at line 98 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_global_id().
{
     return get_global_id()[dimension];
   }
get_global_linear_id()
template<int Dimensions = 1> size_t trisycl::h_item< Dimensions >::get_global_linear_id () const inline
Return the flattened id of the current work-item after subtracting the offset.
Definition at line 106 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_global_id(), trisycl::h_item< Dimensions >::get_global_range(), trisycl::h_item< Dimensions >::get_offset(), and trisycl::detail::linear_id().
{
     return detail::linear_id(get_global_range(), get_global_id(), get_offset());
   }
get_global_range()
template<int Dimensions = 1> range<Dimensions> trisycl::h_item< Dimensions >::get_global_range () const inline
Return a range<> representing the dimensions of the nd_range<>
Definition at line 169 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_nd_range().
Referenced by trisycl::h_item< Dimensions >::get_global_linear_id(), and trisycl::h_item< Dimensions >::get_item().
{
     return get_nd_range().get_global_range();
   }
get_group() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::h_item< Dimensions >::get_group () const inline
Return the constituent group group representing the work-group's position within the overall nd_range.
Definition at line 135 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_global_id(), and trisycl::h_item< Dimensions >::get_local_range().
Referenced by trisycl::h_item< Dimensions >::get_group(), and trisycl::h_item< Dimensions >::get_group_linear_id().
{
     /* Convert get_local_range() to an id<> to remove ambiguity into using
        implicit conversion either from range<> to id<> or the opposite */
     return get_global_id()/id<Dimensions> { get_local_range() };
   }
get_group() [2/2]
template<int Dimensions = 1> size_t trisycl::h_item< Dimensions >::get_group (int dimension) const inline
Return the constituent element of the group id representing the work-group's position within the overall nd_range in the given dimension.
Definition at line 146 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_group().
{
     return get_group()[dimension];
   }
get_group_linear_id()
template<int Dimensions = 1> size_t trisycl::h_item< Dimensions >::get_group_linear_id () const inline
Return the flattened id of the current work-group.
Definition at line 152 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_group(), trisycl::h_item< Dimensions >::get_group_range(), and trisycl::detail::linear_id().
{
     return detail::linear_id(get_group_range(), get_group());
   }
get_group_range() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::h_item< Dimensions >::get_group_range () const inline
Return the number of groups in the nd_range.
Definition at line 158 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_nd_range().
Referenced by trisycl::h_item< Dimensions >::get_group_linear_id(), and trisycl::h_item< Dimensions >::get_group_range().
{
     return get_nd_range().get_group_range();
   }
get_group_range() [2/2]
template<int Dimensions = 1> size_t trisycl::h_item< Dimensions >::get_group_range (int dimension) const inline
Return the number of groups for dimension in the nd_range.
Definition at line 163 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_group_range().
{
      return get_group_range()[dimension];
   }
get_item()
template<int Dimensions = 1> item<Dimensions> trisycl::h_item< Dimensions >::get_item () const inline
Allows projection down to an item.
Todo:
Add to the specification
Definition at line 195 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_global_id(), trisycl::h_item< Dimensions >::get_global_range(), and trisycl::h_item< Dimensions >::get_offset().
{
     return { get_global_range(), get_global_id(), get_offset() };
   }
get_local_id() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::h_item< Dimensions >::get_local_id () const inline
Return the constituent local id representing the work-item's position within the current work-group.
Definition at line 114 of file h_item.hpp.
References trisycl::h_item< Dimensions >::local_index.
Referenced by trisycl::h_item< Dimensions >::get_local_linear_id().
 { return local_index; }
get_local_id() [2/2]
template<int Dimensions = 1> size_t trisycl::h_item< Dimensions >::get_local_id (int dimension) const inline
Return the constituent element of the local id representing the work-item's position within the current work-group in the given dimension.
Definition at line 121 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_local_id().
Referenced by trisycl::h_item< Dimensions >::get_local_id().
 { return get_local_id()[dimension]; }
get_local_linear_id()
template<int Dimensions = 1> size_t trisycl::h_item< Dimensions >::get_local_linear_id () const inline
Return the flattened id of the current work-item within the current work-group.
Definition at line 127 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_local_id(), trisycl::h_item< Dimensions >::get_local_range(), and trisycl::detail::linear_id().
{
     return detail::linear_id(get_local_range(), get_local_id());
   }
get_local_range()
template<int Dimensions = 1> range<Dimensions> trisycl::h_item< Dimensions >::get_local_range () const inline
Return a range<> representing the dimensions of the current work-group.
Definition at line 175 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_nd_range().
Referenced by trisycl::h_item< Dimensions >::get_group(), and trisycl::h_item< Dimensions >::get_local_linear_id().
{
     return get_nd_range().get_local_range();
   }
get_nd_range()
template<int Dimensions = 1> nd_range<Dimensions> trisycl::h_item< Dimensions >::get_nd_range () const inline
Return the nd_range<> of the current execution.
Definition at line 188 of file h_item.hpp.
References trisycl::h_item< Dimensions >::ND_range.
Referenced by trisycl::h_item< Dimensions >::get_global_range(), trisycl::h_item< Dimensions >::get_group_range(), trisycl::h_item< Dimensions >::get_local_range(), and trisycl::h_item< Dimensions >::get_offset().
 { return ND_range; }
get_offset()
template<int Dimensions = 1> id<Dimensions> trisycl::h_item< Dimensions >::get_offset () const inline
Return an id<> representing the n-dimensional offset provided to the constructor of the nd_range<> and that is added by the runtime to the global-ID of each work-item.
Definition at line 184 of file h_item.hpp.
References trisycl::h_item< Dimensions >::get_nd_range().
Referenced by trisycl::h_item< Dimensions >::get_global_linear_id(), and trisycl::h_item< Dimensions >::get_item().
 { return get_nd_range().get_offset(); }
operator==()
template<int Dimensions = 1> bool trisycl::h_item< Dimensions >::operator== (const h_item< Dimensions > & itemB) const inline
comparison operators
Definition at line 231 of file h_item.hpp.
References trisycl::h_item< Dimensions >::global_index, and trisycl::h_item< Dimensions >::ND_range.
{
     return (ND_range == itemB.ND_range &&
             global_index == itemB.global_index);
   }
set_global()
template<int Dimensions = 1> void trisycl::h_item< Dimensions >::set_global (id< Dimensions > Index) inline
Definition at line 228 of file h_item.hpp.
 { global_index = Index; }
set_local()
template<int Dimensions = 1> void trisycl::h_item< Dimensions >::set_local (id< Dimensions > Index) inline
Definition at line 224 of file h_item.hpp.
 { local_index = Index; }
Member Data Documentation
dimensionality
template<int Dimensions = 1> constexpr auto trisycl::h_item< Dimensions >::dimensionality = Dimensions static
Todo:
add this Boost::multi_array or STL concept to the specification?
Definition at line 45 of file h_item.hpp.
global_index
template<int Dimensions = 1> id<Dimensions> trisycl::h_item< Dimensions >::global_index private
Definition at line 49 of file h_item.hpp.
Referenced by trisycl::h_item< Dimensions >::get_global_id(), and trisycl::h_item< Dimensions >::operator==().
local_index
template<int Dimensions = 1> id<Dimensions> trisycl::h_item< Dimensions >::local_index private
Definition at line 52 of file h_item.hpp.
Referenced by trisycl::h_item< Dimensions >::get_local_id().
ND_range
template<int Dimensions = 1> nd_range<Dimensions> trisycl::h_item< Dimensions >::ND_range private
Definition at line 53 of file h_item.hpp.
Referenced by trisycl::h_item< Dimensions >::get_nd_range(), and trisycl::h_item< Dimensions >::operator==().
trisycl::id
class trisycl::id
template<int Dimensions = 1>
class trisycl::id< Dimensions >
Define a multi-dimensional index, used for example to locate a work item.
Definition at line 30 of file id.hpp.
Public Member Functions
id (const range< Dimensions > &range_size)
Construct an id from the dimensions of a range.
Public Member Functions inherited from trisycl::detail::small_array< std::size_t, id< Dimensions >, Dims >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
auto get (std::size_t index) const
Return the element of the array.
operator id< Dimensions > ()
Add + like operations on the id<> and others.
Public Member Functions inherited from trisycl::detail::display_vector< id< Dimensions > >
void display () const
To debug and test.
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Static Public Attributes inherited from trisycl::detail::small_array< std::size_t, id< Dimensions >, Dims >
static const auto dimensionality
static const size_t dimension
Additional Inherited Members
Public Types inherited from trisycl::detail::small_array< std::size_t, id< Dimensions >, Dims >
using element_type = std::size_t
Constructor & Destructor Documentation
id()
template<int Dimensions = 1> trisycl::id< Dimensions >::id (const range< Dimensions > & range_size) inline
Construct an id from the dimensions of a range.
Use the fact we have a constructor of a small_array from a another kind of small_array
Definition at line 47 of file id.hpp.
Referenced by trisycl::id< dimensionality >::id().
     : detail::small_array_123<std::size_t, id<Dimensions>, Dimensions>
       { range_size }
Member Data Documentation
dimensionality
template<int Dimensions = 1> constexpr auto trisycl::id< Dimensions >::dimensionality = Dimensions static
Todo:
add this Boost::multi_array or STL concept to the specification?
Definition at line 38 of file id.hpp.
trisycl::item
class trisycl::item
template<int Dimensions = 1, bool with_offset = true>
class trisycl::item< Dimensions, with_offset >
A SYCL item stores information on a work-item with some more context such as the definition range and offset.
Definition at line 20 of file id.hpp.
Public Member Functions
item (range< Dimensions > global_size, id< Dimensions > global_index, id< Dimensions > offset={})
Create an item from a local size and an optional offset.
item ()=default
To be able to copy and assign item, use default constructors too.
id< Dimensions > get_id () const
Return the constituent local or global id<> representing the work-item's position in the iteration space.
size_t get_id (int dimension) const
Return the requested dimension of the constituent id<> representing the work-item's position in the iteration space.
auto & operator[] (int dimension)
Return the constituent id<> l-value representing the work-item's position in the iteration space in the given dimension.
range< Dimensions > get_range () const
Returns a range<> representing the dimensions of the range of possible values of the item.
size_t get_range (int dimension) const
Return the same value as get_range().get(dimension)
id< Dimensions > get_offset () const
Returns an id<> representing the n-dimensional offset provided to the parallel_for and that is added by the runtime to the global-ID of each work-item, if this item represents a global range.
size_t get_linear_id () const
Return the linearized ID in the item's range.
void set (id< Dimensions > Index)
For the implementation, need to set the global index.
operator item< Dimensions, true > () const
Returns an item with same dimensions but offset set to 0.
void display () const
Display the value for debugging and validation purpose.
bool operator== (const item< Dimensions > &itemB) const
Comparison operators for item.
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Attributes
range< Dimensions > global_range
id< Dimensions > global_index
id< Dimensions > offset
Constructor & Destructor Documentation
item() [1/2]
template<int Dimensions = 1, bool with_offset = true> trisycl::item< Dimensions, with_offset >::item (range< Dimensions > global_size, id< Dimensions > global_index, id< Dimensions > offset = {}) inline
Create an item from a local size and an optional offset.
This constructor is used by the triSYCL implementation and the non-regression testing.
Definition at line 49 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::item().
                                {}) :
     global_range { global_size },
     global_index { global_index },
     offset { offset }
   {}
item() [2/2]
template<int Dimensions = 1, bool with_offset = true> trisycl::item< Dimensions, with_offset >::item () default
To be able to copy and assign item, use default constructors too.
Todo:
Make most of them protected, reserved to implementation
Referenced by trisycl::item< Dimensions, with_offset >::item().
Member Function Documentation
display()
template<int Dimensions = 1, bool with_offset = true> void trisycl::item< Dimensions, with_offset >::display () const inline
Display the value for debugging and validation purpose.
Definition at line 126 of file item.hpp.
References trisycl::detail::display_vector< range< Dimensions > >::display(), and trisycl::detail::display_vector< id< Dimensions > >::display().
{
     global_range.display();
     global_index.display();
     offset.display();
   }
get_id() [1/2]
template<int Dimensions = 1, bool with_offset = true> id<Dimensions> trisycl::item< Dimensions, with_offset >::get_id () const inline
Return the constituent local or global id<> representing the work-item's position in the iteration space.
Definition at line 68 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::global_index.
Referenced by trisycl::item< Dimensions, with_offset >::get_linear_id(), trisycl::id< dimensionality >::id(), trisycl::item< Dimensions, with_offset >::operator item< Dimensions, true >(), and trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[]().
 { return global_index; }
get_id() [2/2]
template<int Dimensions = 1, bool with_offset = true> size_t trisycl::item< Dimensions, with_offset >::get_id (int dimension) const inline
Return the requested dimension of the constituent id<> representing the work-item's position in the iteration space.
Definition at line 74 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::get_id().
Referenced by trisycl::item< Dimensions, with_offset >::get_id().
 { return get_id()[dimension]; }
get_linear_id()
template<int Dimensions = 1, bool with_offset = true> size_t trisycl::item< Dimensions, with_offset >::get_linear_id () const inline
Return the linearized ID in the item's range.
Computed as the flatted ID after the offset is subtracted.
Definition at line 108 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::get_id(), trisycl::item< Dimensions, with_offset >::get_offset(), trisycl::item< Dimensions, with_offset >::get_range(), and trisycl::detail::linear_id().
{
     return detail::linear_id(get_range(), get_id(), get_offset());
   }
get_offset()
template<int Dimensions = 1, bool with_offset = true> id<Dimensions> trisycl::item< Dimensions, with_offset >::get_offset () const inline
Returns an id<> representing the n-dimensional offset provided to the parallel_for and that is added by the runtime to the global-ID of each work-item, if this item represents a global range.
For an item representing a local range of where no offset was passed this will always return an id of all 0 values.
Definition at line 98 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::offset.
Referenced by trisycl::item< Dimensions, with_offset >::get_linear_id().
{
     static_assert(with_offset == true, "get_offset only callable with has_offset = true");
     return offset;
   }
get_range() [1/2]
template<int Dimensions = 1, bool with_offset = true> range<Dimensions> trisycl::item< Dimensions, with_offset >::get_range () const inline
Returns a range<> representing the dimensions of the range of possible values of the item.
Definition at line 86 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::global_range.
Referenced by trisycl::item< Dimensions, with_offset >::get_linear_id(), and trisycl::item< Dimensions, with_offset >::operator item< Dimensions, true >().
 { return global_range; }
get_range() [2/2]
template<int Dimensions = 1, bool with_offset = true> size_t trisycl::item< Dimensions, with_offset >::get_range (int dimension) const inline
Return the same value as get_range().get(dimension)
Definition at line 89 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::get_range().
Referenced by trisycl::item< Dimensions, with_offset >::get_range().
 { return get_range().get(dimension); }
operator item< Dimensions, true >()
template<int Dimensions = 1, bool with_offset = true> trisycl::item< Dimensions, with_offset >::operator item< Dimensions, true > () const inline
Returns an item with same dimensions but offset set to 0.
Definition at line 120 of file item.hpp.
References trisycl::item< Dimensions, with_offset >::get_id(), and trisycl::item< Dimensions, with_offset >::get_range().
{
     static_assert(with_offset == false, "get_offset only callable with has_offset = true");
     return { this->get_range(), this->get_id(), 0 };
   }
operator==()
template<int Dimensions = 1, bool with_offset = true> bool trisycl::item< Dimensions, with_offset >::operator== (const item< Dimensions > & itemB) const inline
Comparison operators for item.
Definition at line 133 of file item.hpp.
{
     return (global_range == itemB.global_range &&
             global_index == itemB.global_index &&
             offset == itemB.offset);
   }
operator[]()
template<int Dimensions = 1, bool with_offset = true> auto& trisycl::item< Dimensions, with_offset >::operator[] (int dimension) inline
Return the constituent id<> l-value representing the work-item's position in the iteration space in the given dimension.
Definition at line 80 of file item.hpp.
 { return global_index[dimension]; }
set()
template<int Dimensions = 1, bool with_offset = true> void trisycl::item< Dimensions, with_offset >::set (id< Dimensions > Index) inline
For the implementation, need to set the global index.
Todo:
Move to private and add friends
Definition at line 117 of file item.hpp.
 { global_index = Index; }
Member Data Documentation
dimensionality
template<int Dimensions = 1, bool with_offset = true> constexpr auto trisycl::item< Dimensions, with_offset >::dimensionality = Dimensions static
Todo:
add this Boost::multi_array or STL concept to the specification?
Definition at line 34 of file item.hpp.
global_index
template<int Dimensions = 1, bool with_offset = true> id<Dimensions> trisycl::item< Dimensions, with_offset >::global_index private
Definition at line 39 of file item.hpp.
Referenced by trisycl::item< Dimensions, with_offset >::get_id().
global_range
template<int Dimensions = 1, bool with_offset = true> range<Dimensions> trisycl::item< Dimensions, with_offset >::global_range private
Definition at line 38 of file item.hpp.
Referenced by trisycl::item< Dimensions, with_offset >::get_range().
offset
template<int Dimensions = 1, bool with_offset = true> id<Dimensions> trisycl::item< Dimensions, with_offset >::offset private
Definition at line 40 of file item.hpp.
Referenced by trisycl::item< Dimensions, with_offset >::get_offset().
trisycl::nd_item
struct trisycl::nd_item
template<int Dimensions = 1>
struct trisycl::nd_item< Dimensions >
A SYCL nd_item stores information on a work-item within a work-group, with some more context such as the definition ranges.
Definition at line 31 of file nd_item.hpp.
Public Member Functions
nd_item (nd_range< Dimensions > ndr)
Create an empty nd_item<> from an nd_range<>
nd_item (id< Dimensions > global_index, nd_range< Dimensions > ndr)
Create a full nd_item.
nd_item ()=default
To be able to copy and assign nd_item, use default constructors too.
id< Dimensions > get_global_id () const
Return the constituent global id representing the work-item's position in the global iteration space.
size_t get_global_id (int dimension) const
Return the constituent element of the global id representing the work-item's position in the global iteration space in the given dimension.
size_t get_global_linear_id () const
Return the flattened id of the current work-item after subtracting the offset.
id< Dimensions > get_local_id () const
Return the constituent local id representing the work-item's position within the current work-group.
size_t get_local_id (int dimension) const
Return the constituent element of the local id representing the work-item's position within the current work-group in the given dimension.
size_t get_local_linear_id () const
Return the flattened id of the current work-item within the current work-group.
id< Dimensions > get_group () const
Return the constituent group representing the work-group's position within the overall nd_range.
size_t get_group (int dimension) const
Return the constituent element of the group id representing the work-group;s position within the overall nd_range in the given dimension.
size_t get_group_linear_id () const
Return the flattened id of the current work-group.
id< Dimensions > get_group_range () const
Return the number of groups in the nd_range.
size_t get_group_range (int dimension) const
Return the number of groups for dimension in the nd_range.
range< Dimensions > get_global_range () const
Return a range<> representing the dimensions of the nd_range<>
range< Dimensions > get_local_range () const
Return a range<> representing the dimensions of the current work-group.
id< Dimensions > get_offset () const
Return an id<> representing the n-dimensional offset provided to the constructor of the nd_range<> and that is added by the runtime to the global-ID of each work-item.
nd_range< Dimensions > get_nd_range () const
Return the nd_range<> of the current execution.
item< Dimensions > get_item () const
Allows projection down to an item.
void barrier (access::fence_space flag=access::fence_space::global_and_local) const
Execute a barrier with memory ordering on the local address space, global address space or both based on the value of flag.
void set_local (id< Dimensions > Index)
void set_global (id< Dimensions > Index)
bool operator== (const nd_item< Dimensions > &nd_itemB) const
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Attributes
id< Dimensions > global_index
id< Dimensions > local_index
nd_range< Dimensions > ND_range
Constructor & Destructor Documentation
nd_item() [1/3]
template<int Dimensions = 1> trisycl::nd_item< Dimensions >::nd_item (nd_range< Dimensions > ndr) inline
Create an empty nd_item<> from an nd_range<>
Todo:
This is for the triSYCL implementation which is expected to call set_global() and set_local() later. This should be hidden to the user.
Definition at line 52 of file nd_item.hpp.
 : ND_range { ndr } {}
nd_item() [2/3]
template<int Dimensions = 1> trisycl::nd_item< Dimensions >::nd_item (id< Dimensions > global_index, nd_range< Dimensions > ndr) inline
Create a full nd_item.
Todo:
This is for validation purpose. Hide this to the programmer somehow
Definition at line 60 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::nd_item().
                                     :
     global_index { global_index },
     // Compute the local index using the offset and the group size
     local_index { (global_index - ndr.get_offset())%id<Dimensions> {
         ndr.get_local_range() } },
     ND_range { ndr }
   {}
nd_item() [3/3]
template<int Dimensions = 1> trisycl::nd_item< Dimensions >::nd_item () default
To be able to copy and assign nd_item, use default constructors too.
Todo:
Make most of them protected, reserved to implementation
Referenced by trisycl::nd_item< Dimensions >::nd_item().
Member Function Documentation
barrier()
template<int Dimensions = 1> void trisycl::nd_item< Dimensions >::barrier (access::fence_space flag = access::fence_space::global_and_local) const inline
Execute a barrier with memory ordering on the local address space, global address space or both based on the value of flag.
The current work-item will wait at the barrier until all work-items in the current work-group have reached the barrier.
In addition, the barrier performs a fence operation ensuring that all memory accesses in the specified address space issued before the barrier complete before those issued after the barrier
Definition at line 203 of file nd_item.hpp.
References TRISYCL_UNIMPL.
{
 #if defined(_OPENMP) && !defined(TRISYCL_NO_BARRIER)
     /* Use OpenMP barrier in the implementation with 1 OpenMP thread per
        work-item of the work-group */
 #pragma omp barrier
 #else
     // \todo To be implemented efficiently otherwise
     TRISYCL_UNIMPL;
 #endif
   }
get_global_id() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::nd_item< Dimensions >::get_global_id () const inline
Return the constituent global id representing the work-item's position in the global iteration space.
Definition at line 80 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::global_index.
Referenced by trisycl::nd_item< Dimensions >::get_global_id(), trisycl::nd_item< Dimensions >::get_global_linear_id(), trisycl::nd_item< Dimensions >::get_group(), trisycl::nd_item< Dimensions >::get_item(), and trisycl::accessor< DataType, Dimensions, AccessMode, Target >::operator[]().
 { return global_index; }
get_global_id() [2/2]
template<int Dimensions = 1> size_t trisycl::nd_item< Dimensions >::get_global_id (int dimension) const inline
Return the constituent element of the global id representing the work-item's position in the global iteration space in the given dimension.
Definition at line 87 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_global_id().
{
     return get_global_id()[dimension];
   }
get_global_linear_id()
template<int Dimensions = 1> size_t trisycl::nd_item< Dimensions >::get_global_linear_id () const inline
Return the flattened id of the current work-item after subtracting the offset.
Definition at line 95 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_global_id(), trisycl::nd_item< Dimensions >::get_global_range(), trisycl::nd_item< Dimensions >::get_offset(), and trisycl::detail::linear_id().
{
     return detail::linear_id(get_global_range(),
                              get_global_id(),
                              get_offset());
   }
get_global_range()
template<int Dimensions = 1> range<Dimensions> trisycl::nd_item< Dimensions >::get_global_range () const inline
Return a range<> representing the dimensions of the nd_range<>
Definition at line 162 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_nd_range().
Referenced by trisycl::nd_item< Dimensions >::get_global_linear_id(), and trisycl::nd_item< Dimensions >::get_item().
{
     return get_nd_range().get_global_range();
   }
get_group() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::nd_item< Dimensions >::get_group () const inline
Return the constituent group representing the work-group's position within the overall nd_range.
Definition at line 128 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_global_id(), and trisycl::nd_item< Dimensions >::get_local_range().
Referenced by trisycl::nd_item< Dimensions >::get_group(), and trisycl::nd_item< Dimensions >::get_group_linear_id().
{
     /* Convert get_local_range() to an id<> to remove ambiguity into using
        implicit conversion either from range<> to id<> or the opposite */
     return get_global_id()/id<Dimensions> { get_local_range() };
   }
get_group() [2/2]
template<int Dimensions = 1> size_t trisycl::nd_item< Dimensions >::get_group (int dimension) const inline
Return the constituent element of the group id representing the work-group;s position within the overall nd_range in the given dimension.
Definition at line 139 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_group().
{
     return get_group()[dimension];
   }
get_group_linear_id()
template<int Dimensions = 1> size_t trisycl::nd_item< Dimensions >::get_group_linear_id () const inline
Return the flattened id of the current work-group.
Definition at line 145 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_group(), trisycl::nd_item< Dimensions >::get_group_range(), and trisycl::detail::linear_id().
{
     return detail::linear_id(get_group_range(), get_group());
   }
get_group_range() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::nd_item< Dimensions >::get_group_range () const inline
Return the number of groups in the nd_range.
Definition at line 151 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_nd_range().
Referenced by trisycl::nd_item< Dimensions >::get_group_linear_id(), and trisycl::nd_item< Dimensions >::get_group_range().
{
     return get_nd_range().get_group_range();
   }
get_group_range() [2/2]
template<int Dimensions = 1> size_t trisycl::nd_item< Dimensions >::get_group_range (int dimension) const inline
Return the number of groups for dimension in the nd_range.
Definition at line 156 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_group_range().
{
      return get_group_range()[dimension];
   }
get_item()
template<int Dimensions = 1> item<Dimensions> trisycl::nd_item< Dimensions >::get_item () const inline
Allows projection down to an item.
Todo:
Add to the specification
Definition at line 188 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_global_id(), trisycl::nd_item< Dimensions >::get_global_range(), and trisycl::nd_item< Dimensions >::get_offset().
{
     return { get_global_range(), get_global_id(), get_offset() };
   }
get_local_id() [1/2]
template<int Dimensions = 1> id<Dimensions> trisycl::nd_item< Dimensions >::get_local_id () const inline
Return the constituent local id representing the work-item's position within the current work-group.
Definition at line 105 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::local_index.
Referenced by trisycl::nd_item< Dimensions >::get_local_id(), and trisycl::nd_item< Dimensions >::get_local_linear_id().
 { return local_index; }
get_local_id() [2/2]
template<int Dimensions = 1> size_t trisycl::nd_item< Dimensions >::get_local_id (int dimension) const inline
Return the constituent element of the local id representing the work-item's position within the current work-group in the given dimension.
Definition at line 112 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_local_id().
{
     return get_local_id()[dimension];
   }
get_local_linear_id()
template<int Dimensions = 1> size_t trisycl::nd_item< Dimensions >::get_local_linear_id () const inline
Return the flattened id of the current work-item within the current work-group.
Definition at line 120 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_local_id(), trisycl::nd_item< Dimensions >::get_local_range(), and trisycl::detail::linear_id().
{
     return detail::linear_id(get_local_range(), get_local_id());
   }
get_local_range()
template<int Dimensions = 1> range<Dimensions> trisycl::nd_item< Dimensions >::get_local_range () const inline
Return a range<> representing the dimensions of the current work-group.
Definition at line 168 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_nd_range().
Referenced by trisycl::nd_item< Dimensions >::get_group(), and trisycl::nd_item< Dimensions >::get_local_linear_id().
{
     return get_nd_range().get_local_range();
   }
get_nd_range()
template<int Dimensions = 1> nd_range<Dimensions> trisycl::nd_item< Dimensions >::get_nd_range () const inline
Return the nd_range<> of the current execution.
Definition at line 181 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::ND_range.
Referenced by trisycl::nd_item< Dimensions >::get_global_range(), trisycl::nd_item< Dimensions >::get_group_range(), trisycl::nd_item< Dimensions >::get_local_range(), and trisycl::nd_item< Dimensions >::get_offset().
 { return ND_range; }
get_offset()
template<int Dimensions = 1> id<Dimensions> trisycl::nd_item< Dimensions >::get_offset () const inline
Return an id<> representing the n-dimensional offset provided to the constructor of the nd_range<> and that is added by the runtime to the global-ID of each work-item.
Definition at line 177 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::get_nd_range().
Referenced by trisycl::nd_item< Dimensions >::get_global_linear_id(), and trisycl::nd_item< Dimensions >::get_item().
 { return get_nd_range().get_offset(); }
operator==()
template<int Dimensions = 1> bool trisycl::nd_item< Dimensions >::operator== (const nd_item< Dimensions > & nd_itemB) const inline
Definition at line 224 of file nd_item.hpp.
References trisycl::nd_item< Dimensions >::global_index, and trisycl::nd_item< Dimensions >::ND_range.
{
     return (ND_range == nd_itemB.ND_range &&
         global_index == nd_itemB.global_index);
   }
set_global()
template<int Dimensions = 1> void trisycl::nd_item< Dimensions >::set_global (id< Dimensions > Index) inline
Definition at line 221 of file nd_item.hpp.
 { global_index = Index; }
set_local()
template<int Dimensions = 1> void trisycl::nd_item< Dimensions >::set_local (id< Dimensions > Index) inline
Definition at line 217 of file nd_item.hpp.
 { local_index = Index; }
Member Data Documentation
dimensionality
template<int Dimensions = 1> constexpr auto trisycl::nd_item< Dimensions >::dimensionality = Dimensions static
Todo:
add this Boost::multi_array or STL concept to the specification?
Definition at line 34 of file nd_item.hpp.
global_index
template<int Dimensions = 1> id<Dimensions> trisycl::nd_item< Dimensions >::global_index private
Definition at line 38 of file nd_item.hpp.
Referenced by trisycl::nd_item< Dimensions >::get_global_id(), and trisycl::nd_item< Dimensions >::operator==().
local_index
template<int Dimensions = 1> id<Dimensions> trisycl::nd_item< Dimensions >::local_index private
Definition at line 41 of file nd_item.hpp.
Referenced by trisycl::nd_item< Dimensions >::get_local_id().
ND_range
template<int Dimensions = 1> nd_range<Dimensions> trisycl::nd_item< Dimensions >::ND_range private
Definition at line 42 of file nd_item.hpp.
Referenced by trisycl::nd_item< Dimensions >::get_nd_range(), and trisycl::nd_item< Dimensions >::operator==().
trisycl::nd_range
struct trisycl::nd_range
template<int Dimensions = 1>
struct trisycl::nd_range< Dimensions >
A ND-range, made by a global and local range, to specify work-group and work-item organization.
The local offset is used to translate the iteration space origin if needed.
Todo:
add copy constructors in the specification
Definition at line 32 of file nd_range.hpp.
Public Member Functions
nd_range (range< Dimensions > global_size, range< Dimensions > local_size, id< Dimensions > offset={})
Construct a ND-range with all the details available in OpenCL.
range< Dimensions > get_global_range () const
Get the global iteration space range.
range< Dimensions > get_local_range () const
Get the local part of the iteration space range.
auto get_group_range () const
Get the range of work-groups needed to run this ND-range.
id< Dimensions > get_offset () const
void display () const
Display the value for debugging and validation purpose.
bool operator== (const nd_range &nd_rangeB) const
Comparison operators for nd_range.
Static Public Attributes
static constexpr auto dimensionality = Dimensions
Private Attributes
range< dimensionality > global_range
range< dimensionality > local_range
id< dimensionality > offset
Constructor & Destructor Documentation
nd_range()
template<int Dimensions = 1> trisycl::nd_range< Dimensions >::nd_range (range< Dimensions > global_size, range< Dimensions > local_size, id< Dimensions > offset = {}) inline
Construct a ND-range with all the details available in OpenCL.
By default use a zero offset, that is iterations start at 0
Definition at line 49 of file nd_range.hpp.
                                    {}) :
     global_range { global_size }, local_range { local_size }, offset { offset }
   { }
Member Function Documentation
display()
template<int Dimensions = 1> void trisycl::nd_range< Dimensions >::display () const inline
Display the value for debugging and validation purpose.
Definition at line 79 of file nd_range.hpp.
References trisycl::detail::display_vector< T >::display().
{
     global_range.display();
     local_range.display();
     offset.display();
   }
get_global_range()
template<int Dimensions = 1> range<Dimensions> trisycl::nd_range< Dimensions >::get_global_range () const inline
Get the global iteration space range.
Definition at line 57 of file nd_range.hpp.
References trisycl::nd_range< Dimensions >::global_range.
 { return global_range; }
get_group_range()
template<int Dimensions = 1> auto trisycl::nd_range< Dimensions >::get_group_range () const inline
Get the range of work-groups needed to run this ND-range.
Definition at line 65 of file nd_range.hpp.
Referenced by trisycl::detail::parallel_for(), trisycl::detail::parallel_for_iterate(), and trisycl::detail::parallel_for_workgroup().
{
     /* This is basically global_range/local_range, round up to the
        next integer, in case the global range is not a multiple of the
        local range. Note this is a motivating example to build a range
        from a scalar with a broadcasting constructor. */
     return (global_range + local_range - range<Dimensions>{ 1 })/local_range;
   }
get_local_range()
template<int Dimensions = 1> range<Dimensions> trisycl::nd_range< Dimensions >::get_local_range () const inline
Get the local part of the iteration space range.
Definition at line 61 of file nd_range.hpp.
References trisycl::nd_range< Dimensions >::local_range.
Referenced by trisycl::detail::parallel_for().
 { return local_range; }
get_offset()
template<int Dimensions = 1> id<Dimensions> trisycl::nd_range< Dimensions >::get_offset () const inline
Todo:
get_offset() is lacking in the specification
Definition at line 75 of file nd_range.hpp.
References trisycl::nd_range< Dimensions >::offset.
 { return offset; }
operator==()
template<int Dimensions = 1> bool trisycl::nd_range< Dimensions >::operator== (const nd_range< Dimensions > & nd_rangeB) const inline
Comparison operators for nd_range.
Definition at line 86 of file nd_range.hpp.
References trisycl::nd_range< Dimensions >::global_range, and trisycl::nd_range< Dimensions >::offset.
{
     return (global_range == nd_rangeB.global_range &&
         offset == nd_rangeB.offset);
   }
Member Data Documentation
dimensionality
template<int Dimensions = 1> constexpr auto trisycl::nd_range< Dimensions >::dimensionality = Dimensions static
Todo:
add this Boost::multi_array or STL concept to the specification?
Definition at line 35 of file nd_range.hpp.
global_range
template<int Dimensions = 1> range<dimensionality> trisycl::nd_range< Dimensions >::global_range private
Definition at line 39 of file nd_range.hpp.
Referenced by trisycl::nd_range< Dimensions >::get_global_range(), and trisycl::nd_range< Dimensions >::operator==().
local_range
template<int Dimensions = 1> range<dimensionality> trisycl::nd_range< Dimensions >::local_range private
Definition at line 40 of file nd_range.hpp.
Referenced by trisycl::nd_range< Dimensions >::get_local_range().
offset
template<int Dimensions = 1> id<dimensionality> trisycl::nd_range< Dimensions >::offset private
Definition at line 41 of file nd_range.hpp.
Referenced by trisycl::nd_range< Dimensions >::get_offset(), and trisycl::nd_range< Dimensions >::operator==().
trisycl::detail::parallel_for_iterate
struct trisycl::detail::parallel_for_iterate
template<std::size_t level, typename Range, typename ParallelForFunctor, typename Id>
struct trisycl::detail::parallel_for_iterate< level, Range, ParallelForFunctor, Id >
A recursive multi-dimensional iterator that ends up calling f.
The iteration order may be changed later.
Since partial specialization of function template is not possible in C++14, use a class template instead with everything in the constructor.
Definition at line 55 of file parallelism.hpp.
Public Member Functions
parallel_for_iterate (Range r, ParallelForFunctor &f, Id &index)
Constructor & Destructor Documentation
parallel_for_iterate()
template<std::size_t level, typename Range , typename ParallelForFunctor , typename Id > trisycl::detail::parallel_for_iterate< level, Range, ParallelForFunctor, Id >::parallel_for_iterate (Range r, ParallelForFunctor & f, Id & index) inline
Definition at line 56 of file parallelism.hpp.
{
     for (boost::multi_array_types::index _sycl_index = 0,
            _sycl_end = r[Range::dimensionality - level];
          _sycl_index < _sycl_end;
          _sycl_index++) {
       // Set the current value of the index for this dimension
       index[Range::dimensionality - level] = _sycl_index;
       // Iterate further on lower dimensions
       parallel_for_iterate<level - 1,
                            Range,
                            ParallelForFunctor,
                            Id> { r, f, index };
     }
   }
trisycl::detail::parallel_for_iterate< 0, Range, ParallelForFunctor, Id >
struct trisycl::detail::parallel_for_iterate< 0, Range, ParallelForFunctor, Id >
template<typename Range, typename ParallelForFunctor, typename Id>
struct trisycl::detail::parallel_for_iterate< 0, Range, ParallelForFunctor, Id >
Stop the recursion when level reaches 0 by simply calling the kernel functor with the constructed id.
Definition at line 118 of file parallelism.hpp.
Public Member Functions
parallel_for_iterate (Range r, ParallelForFunctor &f, Id &index)
Constructor & Destructor Documentation
parallel_for_iterate()
template<typename Range , typename ParallelForFunctor , typename Id > trisycl::detail::parallel_for_iterate< 0, Range, ParallelForFunctor, Id >::parallel_for_iterate (Range r, ParallelForFunctor & f, Id & index) inline
Definition at line 119 of file parallelism.hpp.
{
     f(index);
   }
trisycl::range
class trisycl::range
template<int Dimensions = 1>
class trisycl::range< Dimensions >
A SYCL range defines a multi-dimensional index range that can be used to define launch parallel computation extent or buffer sizes.
Todo:
use std::size_t Dimensions instead of int Dimensions in the specification?
Todo:
add to the specification this default parameter value?
Todo:
add to the specification some way to specify an offset?
Definition at line 33 of file range.hpp.
Public Member Functions
size_t size () const
Return the number of elements in the range.
Public Member Functions inherited from trisycl::detail::small_array< std::size_t, range< Dimensions >, Dims >
small_array (const SourceType src[Dims])
A constructor from another array.
small_array (const small_array< SourceBasicType, SourceFinalType, Dims, SourceEnableArgsConstructor > &src)
A constructor from another small_array of the same size.
small_array (const Types &... args)
Initialize the array from a list of elements.
small_array (const std::array< SourceBasicType, Dims > &src)
Construct a small_array from a std::array.
small_array ()=default
Keep the synthesized constructors.
auto get (std::size_t index) const
Return the element of the array.
operator range< Dimensions > ()
Add + like operations on the id<> and others.
Public Member Functions inherited from trisycl::detail::display_vector< range< Dimensions > >
void display () const
To debug and test.
Additional Inherited Members
Public Types inherited from trisycl::detail::small_array< std::size_t, range< Dimensions >, Dims >
using element_type = std::size_t
Static Public Attributes inherited from trisycl::detail::small_array< std::size_t, range< Dimensions >, Dims >
static const auto dimensionality
static const size_t dimension
Member Function Documentation
size()
template<int Dimensions = 1> size_t trisycl::range< Dimensions >::size () const inline
Return the number of elements in the range.
Definition at line 48 of file range.hpp.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, access::target::local >::allocate_accessor(), trisycl::detail::buffer< T, Dimensions >::allocate_buffer(), and trisycl::detail::parallel_for_workitem().
                       {
     // Return the product of the sizes in each dimension
     return std::accumulate(this->cbegin(),
                            this->cend(),
                            1,
                            std::multiplies<size_t> {});
   }
Function Documentation
capture_arg_v()
template<typename F , typename R , typename A > auto trisycl::detail::capture_arg_v (R(F::*)(A))
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Definition at line 200 of file parallelism.hpp.
Referenced by trisycl::detail::parallel_for().
 { return A{}; }
make_id() [1/4]
auto trisycl::make_id (id< 1 > i) inline
#include <include/triSYCL/id.hpp>
Implement a make_id to construct an id<> of the right dimension with implicit conversion from an initializer list for example.
Cannot use a template on the number of dimensions because the implicit conversion would not be tried.
Definition at line 73 of file id.hpp.
References i.
Referenced by trisycl::detail::to_sycl_id().
 { return i; }
make_id() [2/4]
auto trisycl::make_id (id< 2 > i) inline
#include <include/triSYCL/id.hpp>
Definition at line 74 of file id.hpp.
References i.
 { return i; }
make_id() [3/4]
auto trisycl::make_id (id< 3 > i) inline
#include <include/triSYCL/id.hpp>
Definition at line 75 of file id.hpp.
References i.
 { return i; }
make_id() [4/4]
template<typename... BasicType> auto trisycl::make_id (BasicType... Args)
#include <include/triSYCL/id.hpp>
Construct an id<> from a function call with arguments, like make_id(1, 2, 3)
Definition at line 81 of file id.hpp.
{
   // Call constructor directly to allow narrowing
   return id<sizeof...(Args)>(Args...);
 }
make_range() [1/4]
auto trisycl::make_range (range< 1 > r) inline
#include <include/triSYCL/range.hpp>
Implement a make_range to construct a range<> of the right dimension with implicit conversion from an initializer list for example.
Cannot use a template on the number of dimensions because the implicit conversion would not be tried.
Definition at line 64 of file range.hpp.
 { return r; }
make_range() [2/4]
auto trisycl::make_range (range< 2 > r) inline
#include <include/triSYCL/range.hpp>
Definition at line 65 of file range.hpp.
 { return r; }
make_range() [3/4]
auto trisycl::make_range (range< 3 > r) inline
#include <include/triSYCL/range.hpp>
Definition at line 66 of file range.hpp.
 { return r; }
make_range() [4/4]
template<typename... BasicType> auto trisycl::make_range (BasicType... Args)
#include <include/triSYCL/range.hpp>
Construct a range<> from a function call with arguments, like make_range(1, 2, 3)
Definition at line 73 of file range.hpp.
{
   // Call constructor directly to allow narrowing
   return range<sizeof...(Args)>(Args...);
 }
parallel_for() [1/4]
template<int Dimensions = 1, typename ParallelForFunctor , typename Id > void trisycl::detail::parallel_for (range< Dimensions > r, ParallelForFunctor f, Id)
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Implementation of a data parallel computation with parallelism specified at launch time by a range<>.
Kernel index is id or int.
This implementation use OpenMP 3 if compiled with the right flag.
Kernel index is id or int.
Definition at line 131 of file parallelism.hpp.
Referenced by trisycl::detail::parallel_for(), trisycl::handler::parallel_for(), trisycl::detail::parallel_for_global_offset(), and trisycl::detail::parallel_for_iterate().
                       {
 #ifdef _OPENMP
   // Use OpenMP for the top loop level
   parallel_OpenMP_for_iterate<Dimensions,
                               range<Dimensions>,
                               ParallelForFunctor,
                               id<Dimensions>> { r, f };
 #else
   // In a sequential execution there is only one index processed at a time
   id<Dimensions> index;
   parallel_for_iterate<Dimensions,
                        range<Dimensions>,
                        ParallelForFunctor,
                        id<Dimensions>> { r, f, index };
 #endif
 }
parallel_for() [2/4]
template<int Dimensions = 1, typename ParallelForFunctor > void trisycl::detail::parallel_for (range< Dimensions > r, ParallelForFunctor f, item< Dimensions >)
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Implementation of a data parallel computation with parallelism specified at launch time by a range<>.
Kernel index is item.
This implementation use OpenMP 3 if compiled with the right flag.
Kernel index is item.
Definition at line 157 of file parallelism.hpp.
{
   auto reconstruct_item = [&] (id<Dimensions> l) {
     // Reconstruct the global item
     item<Dimensions> index { r, l };
     // Call the user kernel with the item<> instead of the id<>
     f(index);
   };
 #ifdef _OPENMP
   // Use OpenMP for the top loop level
   parallel_OpenMP_for_iterate<Dimensions,
                               range<Dimensions>,
                               decltype(reconstruct_item),
                               id<Dimensions>> { r, reconstruct_item };
 #else
   // In a sequential execution there is only one index processed at a time
   id<Dimensions> index;
   parallel_for_iterate<Dimensions,
                        range<Dimensions>,
                        decltype(reconstruct_item),
                        id<Dimensions>> { r, reconstruct_item, index };
 #endif
 }
parallel_for() [3/4]
template<int Dimensions = 1, typename ParallelForFunctor > void trisycl::detail::parallel_for (range< Dimensions > r, ParallelForFunctor f)
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Calls the appropriate ternary parallel_for overload based on the index type of the kernel function object f.
capture_arg_v generates a value from the type of the passed in kernels (lambdas) argument (item or id in this case) and passes it onwards to parallel_for so that it's aware which index class it's supposed to generate data for.
We erase the type then retrieve it again so that we can avoid redefining the parallel_for interface in handler.hpp for item and id as the parallel_for in the SYCL 1.2.1 spec that accepts a range can be overloaded for both.
Definition at line 220 of file parallelism.hpp.
References trisycl::detail::capture_arg_v(), and trisycl::detail::parallel_for().
{
   parallel_for(r,f, capture_arg_v(&ParallelForFunctor::operator()));
 }
parallel_for() [4/4]
template<int Dimensions = 1, typename ParallelForFunctor > void trisycl::detail::parallel_for (nd_range< Dimensions > r, ParallelForFunctor f)
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Implement a variation of parallel_for to take into account a nd_range<>
Todo:
Add an OpenMP implementation
Todo:
Deal with incomplete work-groups
Todo:
Implement with parallel_for_workgroup()/parallel_for_workitem()
Definition at line 390 of file parallelism.hpp.
References trisycl::nd_range< Dimensions >::get_group_range(), trisycl::nd_range< Dimensions >::get_local_range(), and trisycl::detail::parallel_for_workitem().
{
   // To iterate on the work-group
   id<Dimensions> group;
   range<Dimensions> group_range = r.get_group_range();
 #ifdef _OPENMP
   auto iterate_in_work_group = [&] (id<Dimensions> g) {
     //group.display();
     // Then iterate on the local work-groups
     trisycl::group<Dimensions> wg {g, r};
     parallel_for_workitem<Dimensions,
                           nd_item<Dimensions>,
                           decltype(f)>(wg, f);
   };
 #else
   // In a sequential execution there is only one index processed at a time
   nd_item<Dimensions> index { r };
   // To iterate on the local work-item
   id<Dimensions> local;
   range<Dimensions> local_range = r.get_local_range();
   // Reconstruct the item from its group and local id
   auto reconstruct_item = [&] (id<Dimensions> l) {
     //local.display();
     // Reconstruct the global item
     index.set_local(local);
     // Upgrade local_range to an id<> so that we can * with the group (an id<>)
     index.set_global(local + id<Dimensions>(local_range)*group);
     // Call the user kernel at last
     f(index);
   };
   /* To recycle the parallel_for on range<>, wrap the ParallelForFunctor f
      into another functor that iterates inside the work-group and then
      calls f */
   auto iterate_in_work_group = [&] (id<Dimensions> g) {
     //group.display();
     // Then iterate on the local work-groups
     parallel_for_iterate<Dimensions,
                          range<Dimensions>,
                          decltype(reconstruct_item),
                          id<Dimensions>> { local_range,
                                            reconstruct_item,
                                            local };
   };
 #endif
   // First iterate on all the work-groups
   parallel_for_iterate<Dimensions,
                        range<Dimensions>,
                        decltype(iterate_in_work_group),
                        id<Dimensions>> { group_range,
                                          iterate_in_work_group,
                                          group };
 }
parallel_for_global_offset()
template<int Dimensions = 1, typename ParallelForFunctor > void trisycl::detail::parallel_for_global_offset (range< Dimensions > global_size, id< Dimensions > offset, ParallelForFunctor f)
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Implementation of parallel_for with a range<> and an offset.
Definition at line 234 of file parallelism.hpp.
References offset, and trisycl::detail::parallel_for().
Referenced by trisycl::detail::parallel_for_iterate().
{
   // Reconstruct the item from its id<> and its offset
   auto reconstruct_item = [&] (id<Dimensions> l) {
     // Reconstruct the global item
     item<Dimensions> index { global_size, l + offset, offset };
     // Call the user kernel with the item<> instead of the id<>
     f(index);
   };
   // First iterate on all the work-groups
   parallel_for(global_size, reconstruct_item);
 }
parallel_for_iterate()
template<typename Range , typename ParallelForFunctor > void trisycl::detail::parallel_for_iterate (Range r, ParallelForFunctor & f)
#include <include/triSYCL/parallelism/detail/parallelism_tbb.hpp>
Definition at line 70 of file parallelism_tbb.hpp.
References trisycl::nd_range< Dimensions >::get_group_range(), trisycl::group< Dimensions >::get_id(), trisycl::group< Dimensions >::get_local_range(), trisycl::group< Dimensions >::get_nd_range(), offset, trisycl::detail::parallel_for(), trisycl::detail::parallel_for_global_offset(), trisycl::detail::parallel_for_workgroup(), trisycl::detail::parallel_for_workitem(), trisycl::detail::parallel_for_workitem_in_group(), trisycl::detail::to_sycl_id(), and trisycl::detail::to_tbb_range().
 {
   tbb::parallel_for(to_tbb_range(r),
                     [&](auto idx) { f(to_sycl_id(idx)); },
                     tbb::simple_partitioner{});
 }
parallel_for_workgroup()
template<int Dimensions = 1, typename ParallelForFunctor > void trisycl::detail::parallel_for_workgroup (nd_range< Dimensions > r, ParallelForFunctor f)
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Implement the loop on the work-groups.
Definition at line 252 of file parallelism.hpp.
References trisycl::nd_range< Dimensions >::get_group_range().
Referenced by trisycl::detail::parallel_for_iterate(), and trisycl::handler::parallel_for_work_group().
{
   // In a sequential execution there is only one index processed at a time
   group<Dimensions> g { r };
   // First iterate on all the work-groups
   parallel_for_iterate<Dimensions,
                        range<Dimensions>,
                        ParallelForFunctor,
                        group<Dimensions>> {
     r.get_group_range(),
     f,
     g };
 }
parallel_for_workitem()
template<int Dimensions, typename T_Item , typename ParallelForFunctor > void trisycl::detail::parallel_for_workitem (const group< Dimensions > & g, ParallelForFunctor f)
#include <include/triSYCL/parallelism/detail/parallelism.hpp>
Implement the loop on the work-items inside a work-group.
Todo:
Better type the functor
Definition at line 273 of file parallelism.hpp.
References trisycl::detail::small_array< std::size_t, range< Dimensions >, Dims >::get(), trisycl::group< Dimensions >::get_id(), trisycl::group< Dimensions >::get_local_range(), trisycl::group< Dimensions >::get_nd_range(), i, and trisycl::range< Dimensions >::size().
Referenced by trisycl::detail::parallel_for(), trisycl::detail::parallel_for_iterate(), and trisycl::detail::parallel_for_workitem_in_group().
{
 #if defined(_OPENMP) && (!defined(TRISYCL_NO_BARRIER) && !defined(_MSC_VER))
   /* To implement barriers with OpenMP, one thread is created for each
      work-item in the group and thus an OpenMP barrier has the same effect
      of an OpenCL barrier executed by the work-items in a workgroup
      The issue is that the parallel_for_workitem() execution is slow even
      when nd_item::barrier() is not used
   */
   range<Dimensions> l_r = g.get_nd_range().get_local_range();
   id<Dimensions> id_l_r { l_r };
   auto tot = l_r.size();
   if constexpr (Dimensions == 1) {
   #pragma omp parallel for collapse(1) schedule(static) num_threads(tot)
     for (size_t i = 0; i < l_r.get(0); ++i) {
       T_Item index{g.get_nd_range()};
       index.set_local(i);
       index.set_global(index.get_local_id() + id_l_r * g.get_id());
       f(index);
     }
   } else if constexpr (Dimensions == 2) {
   #pragma omp parallel for collapse(2) schedule(static) num_threads(tot)
     for (size_t i = 0; i < l_r.get(0); ++i) {
       for (size_t j = 0; j < l_r.get(1); ++j) {
         T_Item index{g.get_nd_range()};
         index.set_local({i,j});
         index.set_global(index.get_local_id() + id_l_r * g.get_id());
         f(index);
       }
     }
   } else if constexpr (Dimensions == 3) {
   #pragma omp parallel for collapse(3) schedule(static) num_threads(tot)
     for (size_t i = 0; i < l_r.get(0); ++i)
       for (size_t j = 0; j < l_r.get(1); ++j)
         for (size_t k = 0; k < l_r.get(2); ++k) {
           T_Item index{g.get_nd_range()};
           index.set_local({i,j,k});
           index.set_global(index.get_local_id() + id_l_r * g.get_id());
           f(index);
         }
   }
 #elif defined(_OPENMP) && (defined(TRISYCL_NO_BARRIER) && !defined(_MSC_VER))
   range<Dimensions> l_r = g.get_nd_range().get_local_range();
   id<Dimensions> id_l_r { l_r };
   if constexpr (Dimensions == 1) {
   #pragma omp parallel for simd collapse(1)
     for (size_t i = 0; i < l_r.get(0); ++i) {
       T_Item index{g.get_nd_range()};
       index.set_local(i);
       index.set_global(index.get_local_id() + id_l_r * g.get_id());
       f(index);
     }
   } else if constexpr (Dimensions == 2) {
   #pragma omp parallel for simd collapse(2)
     for (size_t i = 0; i < l_r.get(0); ++i) {
       for (size_t j = 0; j < l_r.get(1); ++j) {
         T_Item index{g.get_nd_range()};
         index.set_local({i,j});
         index.set_global(index.get_local_id() + id_l_r * g.get_id());
         f(index);
       }
     }
   } else if constexpr (Dimensions == 3) {
     #pragma omp parallel for simd collapse(3)
     for (size_t i = 0; i < l_r.get(0); ++i)
       for (size_t j = 0; j < l_r.get(1); ++j)
         for (size_t k = 0; k < l_r.get(2); ++k) {
           T_Item index{g.get_nd_range()};
           index.set_local({i,j,k});
           index.set_global(index.get_local_id() + id_l_r * g.get_id());
           f(index);
         }
   }
 #else
   // In a sequential execution there is only one index processed at a time
   T_Item index { g.get_nd_range() };
   // To iterate on the local work-item
   id<Dimensions> local;
   // Reconstruct the item from its group and local id
   auto reconstruct_item = [&] (id<Dimensions> l) {
     //local.display();
     //l.display();
     // Reconstruct the global item
     index.set_local(local);
     // \todo Some strength reduction here
     index.set_global(local + id<Dimensions>(g.get_local_range())*g.get_id());
     // Call the user kernel at last
     f(index);
   };
   // Then iterate on all the work-items of the work-group
   parallel_for_iterate<Dimensions,
                        range<Dimensions>,
                        decltype(reconstruct_item),
                        id<Dimensions>> {
     g.get_local_range(),
     reconstruct_item,
     local };
 #endif
 }
parallel_for_workitem_in_group()
template<int Dimensions = 1, typename ParallelForFunctor > void trisycl::detail::parallel_for_workitem_in_group (const group< Dimensions > & g, ParallelForFunctor f)
#include <include/triSYCL/group.hpp>
Implement the loop on the work-items inside a work-group.
Definition at line 457 of file parallelism.hpp.
References trisycl::detail::parallel_for_workitem().
Referenced by trisycl::detail::parallel_for_iterate(), and trisycl::group< Dimensions >::parallel_for_work_item().
{
   parallel_for_workitem<Dimensions,
                         h_item<Dimensions>,
                         ParallelForFunctor>(g, f);
 }
to_sycl_id() [1/3]
static auto trisycl::detail::to_sycl_id (const tbb::blocked_range< size_t > & in) inline static
#include <include/triSYCL/parallelism/detail/parallelism_tbb.hpp>
Definition at line 49 of file parallelism_tbb.hpp.
References trisycl::make_id().
Referenced by trisycl::detail::parallel_for_iterate().
 {
   return make_id(in.begin());
 }
to_sycl_id() [2/3]
static auto trisycl::detail::to_sycl_id (const tbb::blocked_range2d< size_t > & in) inline static
#include <include/triSYCL/parallelism/detail/parallelism_tbb.hpp>
Definition at line 54 of file parallelism_tbb.hpp.
References trisycl::make_id().
 {
   const auto cols = in.cols().begin();
   const auto rows = in.rows().begin();
   return make_id(rows, cols);
 }
to_sycl_id() [3/3]
static auto trisycl::detail::to_sycl_id (const tbb::blocked_range3d< size_t > & in) inline static
#include <include/triSYCL/parallelism/detail/parallelism_tbb.hpp>
Definition at line 61 of file parallelism_tbb.hpp.
References trisycl::make_id().
 {
   const auto pages = in.pages().begin();
   const auto cols = in.cols().begin();
   const auto rows = in.rows().begin();
   return make_id(rows, cols, pages);
 }
to_tbb_range() [1/3]
static auto trisycl::detail::to_tbb_range (const range< 1 > & r) inline static
#include <include/triSYCL/parallelism/detail/parallelism_tbb.hpp>
Definition at line 34 of file parallelism_tbb.hpp.
Referenced by trisycl::detail::parallel_for_iterate().
 {
   return tbb::blocked_range<size_t>(0, r[0]);
 }
to_tbb_range() [2/3]
static auto trisycl::detail::to_tbb_range (const range< 2 > & r) inline static
#include <include/triSYCL/parallelism/detail/parallelism_tbb.hpp>
Definition at line 39 of file parallelism_tbb.hpp.
 {
   return tbb::blocked_range2d<size_t>(0, r[0], 0, r[1]);
 }
to_tbb_range() [3/3]
static auto trisycl::detail::to_tbb_range (const range< 3 > & r) inline static
#include <include/triSYCL/parallelism/detail/parallelism_tbb.hpp>
Definition at line 44 of file parallelism_tbb.hpp.
 {
   return tbb::blocked_range3d<size_t>(0, r[0], 0, r[1], 0, r[2]);
 }