triSYCL implementation of SYCL: Opencl_spir_helpers
Opencl_spir_helpers
Namespaces
namespace trisycl
The vector type to be used as SYCL vector.
namespace trisycl::detail
Some global triSYCL configuration.
namespace trisycl::detail::spir
Functions
template<typename T , typename F >
auto trisycl::detail::spir::make_array_with_func (F unary_func)
template<int Dimensions>
nd_range< Dimensions > trisycl::detail::spir::make_spir_nd_range ()
template<int Dimensions>
h_item< Dimensions > trisycl::detail::spir::make_spir_h_item ()
template<int Dimensions, typename Index_T >
auto trisycl::detail::spir::create_parallel_for_arg (Index_T index_or_range)
Detailed Description
Function Documentation
create_parallel_for_arg()
template<int Dimensions, typename Index_T > auto trisycl::detail::spir::create_parallel_for_arg (Index_T index_or_range)
#include <include/triSYCL/detail/SPIR/opencl_spir_helpers.hpp>
Definition at line 73 of file opencl_spir_helpers.hpp.
{
  if constexpr (std::is_same_v<Index_T, id<Dimensions>>) {
    index_or_range = make_array_with_func<Index_T>(get_global_id);
  } else if constexpr (std::is_same_v<Index_T, item<Dimensions>>) {
    // Item's do not contain local information in parallel_for
    index_or_range = Index_T {
      make_array_with_func<range<Dimensions>>(get_global_size),
      make_array_with_func<id<Dimensions>>(get_global_id),
      make_array_with_func<id<Dimensions>>(get_global_offset)
    };
  } else {
    static_assert(std::is_same_v<Index_T, item<Dimensions>> ||
                  std::is_same_v<Index_T, id<Dimensions>>,
                  "undefined Index_T passed to create_parallel_for_arg");
  }
  return index_or_range;
}
References trisycl::detail::spir::make_array_with_func().
make_array_with_func()
template<typename T , typename F > auto trisycl::detail::spir::make_array_with_func (F unary_func)
#include <include/triSYCL/detail/SPIR/opencl_spir_helpers.hpp>
Definition at line 37 of file opencl_spir_helpers.hpp.
{
  T id_or_range {};
  for (size_t i = 0; i < id_or_range.dimensionality; ++i)
    id_or_range[i] = unary_func(i);
  return id_or_range;
}
References i.
Referenced by trisycl::detail::spir::create_parallel_for_arg(), and trisycl::detail::spir::make_spir_nd_range().
make_spir_h_item()
template<int Dimensions> h_item< Dimensions > trisycl::detail::spir::make_spir_h_item ()
#include <include/triSYCL/detail/SPIR/opencl_spir_helpers.hpp>
Definition at line 59 of file opencl_spir_helpers.hpp.
{
  return h_item<Dimensions> {
    make_array_with_func<id<Dimensions>>(get_global_offset),
    make_spir_nd_range<Dimensions>()
  };
}
make_spir_nd_range()
template<int Dimensions> nd_range< Dimensions > trisycl::detail::spir::make_spir_nd_range ()
#include <include/triSYCL/detail/SPIR/opencl_spir_helpers.hpp>
Definition at line 47 of file opencl_spir_helpers.hpp.
{
  return nd_range<Dimensions> {
    make_array_with_func<range<Dimensions>>(get_global_size),
    make_array_with_func<range<Dimensions>>(get_local_size),
    make_array_with_func<id<Dimensions>>(get_global_offset)
  };
}
References trisycl::detail::spir::make_array_with_func().