triSYCL implementation of SYCL: Data access and storage in old version of SYCL
Data access and storage in old version of SYCL
Classes
class trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
class trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
class trisycl::host_accessor< DataType, Dimensions, AccessMode >
SYCL 2020 host_accessor.
class trisycl::sycl_2_2::pipe< T >
A SYCL pipe.
struct trisycl::detail::sycl_2_2::reserve_id< T >
A private description of a reservation station.
class trisycl::detail::sycl_2_2::pipe< T >
Implement a pipe object.
class trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >
The accessor abstracts the way pipe data are accessed inside a kernel.
struct trisycl::sycl_2_2::pipe_reservation< PipeAccessor >
The pipe reservation station allows to reserve an array-like view inside the pipe for ordered race-free access from various work-items for example.
class trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >
The implementation of the pipe reservation station.
class trisycl::sycl_2_2::static_pipe< T, Capacity >
A SYCL static-scoped pipe equivalent to an OpenCL program-scoped pipe.
Functions
template<typename Accessor >
static auto & trisycl::get_pipe_detail (Accessor &a)
Top-level function to break circular dependencies on the the types to get the pipe implementation.
Detailed Description
Class Documentation
trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
class trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
template<typename DataType, access::mode AccessMode>
class trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
This is a proposal for the now abandoned SYCL 2.2 provisional specification. This is still here for historical reasons.
A specialization for an non-blocking pipe
Definition at line 402 of file accessor.hpp.
Public Types
using accessor_detail = detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::pipe >
Public Types inherited from trisycl::detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::pipe >
using value_type = DataType
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
Public Member Functions
accessor (sycl_2_2::pipe< DataType > &p, handler &command_group_handler)
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
sycl_2_2::pipe_reservation< accessor > reserve (std::size_t size) const
Make a reservation inside the pipe.
auto & get_pipe_detail ()
Get the underlying pipe implementation.
Public Member Functions inherited from trisycl::detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::pipe >
pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< DataType > > &p)
Construct a pipe accessor from an existing pipe.
pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< DataType > > &p, handler &command_group_handler)
Construct a pipe accessor from an existing pipe.
pipe_accessor ()=default
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size () const
Get the current number of elements in the pipe.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
operator bool () const
In an explicit bool context, the accessor gives the success status of the last access.
const pipe_accessor & write (const value_type &value) const
Try to write a value to the pipe.
const pipe_accessor & operator<< (const value_type &value) const
Some syntactic sugar to use.
const pipe_accessor & read (value_type &value) const
Try to read a value from the pipe.
value_type read () const
Read a value from a blocking pipe.
const pipe_accessor & operator>> (value_type &value) const
Some syntactic sugar to use.
detail::sycl_2_2::pipe_reservation< pipe_accessor > reserve (std::size_t size) const
void set_debug (bool enable) const
Set debug mode.
auto & get_pipe_detail ()
~pipe_accessor ()
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::debug< detail::sycl_2_2::pipe_accessor< DataType, AccessMode, Target > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Static Public Attributes inherited from trisycl::detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::pipe >
static constexpr auto rank
static constexpr auto mode
static constexpr auto target
static constexpr bool blocking
Member Typedef Documentation
accessor_detail
template<typename DataType , access::mode AccessMode> using trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::accessor_detail = detail::sycl_2_2::pipe_accessor<DataType, AccessMode, access::target::pipe>
Definition at line 408 of file accessor.hpp.
Constructor & Destructor Documentation
accessor()
template<typename DataType , access::mode AccessMode> trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::accessor (sycl_2_2::pipe< DataType > & p, handler & command_group_handler) inline
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
access_target defines the form of access being obtained.
Definition at line 418 of file accessor.hpp.
    : accessor_detail { p.implementation, command_group_handler } { }
Member Function Documentation
get_pipe_detail()
template<typename DataType , access::mode AccessMode> auto & trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::get_pipe_detail () inline
Get the underlying pipe implementation.
Definition at line 428 of file accessor.hpp.
{
    return accessor_detail::get_pipe_detail();
  }
References trisycl::get_pipe_detail().
reserve()
template<typename DataType , access::mode AccessMode> sycl_2_2::pipe_reservation< accessor > trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::reserve (std::size_t size) const inline
Make a reservation inside the pipe.
Definition at line 422 of file accessor.hpp.
{
    return accessor_detail::reserve(size);
  }
trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
class trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
template<typename DataType, access::mode AccessMode>
class trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
This is a proposal for the now abandoned SYCL 2.2 provisional specification. This is still here for historical reasons.
A specialization for a blocking pipe
Definition at line 445 of file accessor.hpp.
Public Types
using accessor_detail = detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
Public Types inherited from trisycl::detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
using value_type = DataType
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
Public Member Functions
accessor (sycl_2_2::pipe< DataType > &p, handler &command_group_handler)
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
accessor (sycl_2_2::pipe< DataType > &p)
Construct a pipe accessor from a pipe outside of a normal kernel, for example in host code.
sycl_2_2::pipe_reservation< accessor > reserve (std::size_t size) const
Make a reservation inside the pipe.
auto & get_pipe_detail ()
Get the underlying pipe implementation.
Public Member Functions inherited from trisycl::detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< DataType > > &p)
Construct a pipe accessor from an existing pipe.
pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< DataType > > &p, handler &command_group_handler)
Construct a pipe accessor from an existing pipe.
pipe_accessor ()=default
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size () const
Get the current number of elements in the pipe.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
operator bool () const
In an explicit bool context, the accessor gives the success status of the last access.
const pipe_accessor & write (const value_type &value) const
Try to write a value to the pipe.
const pipe_accessor & operator<< (const value_type &value) const
Some syntactic sugar to use.
const pipe_accessor & read (value_type &value) const
Try to read a value from the pipe.
value_type read () const
Read a value from a blocking pipe.
const pipe_accessor & operator>> (value_type &value) const
Some syntactic sugar to use.
detail::sycl_2_2::pipe_reservation< pipe_accessor > reserve (std::size_t size) const
void set_debug (bool enable) const
Set debug mode.
auto & get_pipe_detail ()
~pipe_accessor ()
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::debug< detail::sycl_2_2::pipe_accessor< DataType, AccessMode, Target > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Static Public Attributes inherited from trisycl::detail::sycl_2_2::pipe_accessor< DataType, AccessMode, access::target::blocking_pipe >
static constexpr auto rank
static constexpr auto mode
static constexpr auto target
static constexpr bool blocking
Member Typedef Documentation
accessor_detail
template<typename DataType , access::mode AccessMode> using trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::accessor_detail = detail::sycl_2_2::pipe_accessor<DataType, AccessMode, access::target::blocking_pipe>
Definition at line 451 of file accessor.hpp.
Constructor & Destructor Documentation
accessor() [1/2]
template<typename DataType , access::mode AccessMode> trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::accessor (sycl_2_2::pipe< DataType > & p, handler & command_group_handler) inline
Construct a pipe accessor from a pipe using a command group handler object from the command group scope.
access_target defines the form of access being obtained.
Definition at line 463 of file accessor.hpp.
    : accessor_detail { p.implementation, command_group_handler } { }
accessor() [2/2]
template<typename DataType , access::mode AccessMode> trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::accessor (sycl_2_2::pipe< DataType > & p) inline
Construct a pipe accessor from a pipe outside of a normal kernel, for example in host code.
Definition at line 470 of file accessor.hpp.
    : accessor_detail { p.implementation } { }
Member Function Documentation
get_pipe_detail()
template<typename DataType , access::mode AccessMode> auto & trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::get_pipe_detail () inline
Get the underlying pipe implementation.
Definition at line 481 of file accessor.hpp.
{
    return accessor_detail::get_pipe_detail();
  }
References trisycl::get_pipe_detail().
reserve()
template<typename DataType , access::mode AccessMode> sycl_2_2::pipe_reservation< accessor > trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::reserve (std::size_t size) const inline
Make a reservation inside the pipe.
Definition at line 475 of file accessor.hpp.
{
    return accessor_detail::reserve(size);
  }
trisycl::host_accessor
class trisycl::host_accessor
template<typename DataType, int Dimensions, access::mode AccessMode = access::mode::read_write>
class trisycl::host_accessor< DataType, Dimensions, AccessMode >
SYCL 2020 host_accessor.
Parameters
[in] DataType is the value type of the elements
[in] Dimensions is the rank of the accessor
[in] AccessMode precises whether the access is done in read or write mode. By default this is read+write
Definition at line 499 of file accessor.hpp.
Public Member Functions
template<typename Allocator >
host_accessor (buffer< DataType, Dimensions, Allocator > &target_buffer)
Create an accessor to a buffer to access from the host.
template<typename Allocator >
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer, handler &command_group_handler)
Construct a buffer accessor from a buffer using a command group handler object from the command group scope.
template<typename Allocator >
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer)
Construct a buffer accessor from a buffer.
template<typename Allocator >
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer, handler &command_group_handler, const range< Dimensions > &offset, const range< Dimensions > &range)
Construct a buffer accessor from a buffer given a specific range for access permissions and an offset that provides the starting point for the access range using a command group handler object from the command group scope.
accessor (const range< Dimensions > &allocation_size, handler &command_group_handler)
Construct an accessor of dimension Dimensions with elements of type DataType using the passed range to specify the size in each dimension.
Public Member Functions inherited from trisycl::accessor< DataType, Dimensions, access::mode::read_write, access::target::host_buffer >
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer, handler &command_group_handler)
Construct a buffer accessor from a buffer using a command group handler object from the command group scope.
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer)
Construct a buffer accessor from a buffer.
accessor (buffer< DataType, Dimensions, Allocator > &target_buffer, handler &command_group_handler, const range< Dimensions > &offset, const range< Dimensions > &range)
Construct a buffer accessor from a buffer given a specific range for access permissions and an offset that provides the starting point for the access range using a command group handler object from the command group scope.
accessor (const range< Dimensions > &allocation_size, handler &command_group_handler)
Construct an accessor of dimension Dimensions with elements of type DataType using the passed range to specify the size in each dimension.
auto get_range () const
Return a range object representing the size of the buffer in terms of number of elements in each dimension as passed to the constructor.
auto get_count () const
Returns the total number of elements behind the accessor.
auto get_size () const
Returns the size of the underlying buffer storage in bytes.
decltype(auto) operator[] (T... indices)
Use the accessor with integers la [i1][i2][i3] or C++23 [i1, i2,...].
decltype(auto) operator[] (T... indices) const
Use the accessor with integers la [i1][i2][i3] or C++23 [i1, i2,...].
auto & operator[] (const id< dimensionality > &index)
To use the accessor with [id<>].
auto & operator[] (const id< dimensionality > &index) const
To use the accessor with [id<>].
auto & operator[] (const item< dimensionality > &index)
To use an accessor with [item<>].
auto & operator[] (const item< dimensionality > &index) const
To use an accessor with [item<>].
auto & operator[] (const nd_item< dimensionality > &index)
To use an accessor with an [nd_item<>].
auto & operator[] (const nd_item< dimensionality > &index) const
To use an accessor with an [nd_item<>].
accessor_detail::reference operator* ()
Get the first element of the accessor.
accessor_detail::reference operator* () const
Get the first element of the accessor.
auto get_pointer () const
Get the pointer to the start of the data.
accessor_detail::iterator begin () const
Forward all the iterator functions to the implementation.
accessor_detail::iterator end () const
accessor_detail::const_iterator cbegin () const
accessor_detail::const_iterator cend () const
accessor_detail::reverse_iterator rbegin () const
accessor_detail::reverse_iterator rend () const
accessor_detail::const_reverse_iterator crbegin () const
accessor_detail::const_reverse_iterator crend () const
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >
shared_ptr_implementation (std::shared_ptr< detail::accessor< DataType, Dimensions, AccessMode, Target > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::accessor< DataType, Dimensions, AccessMode, Target > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using base = accessor< DataType, Dimensions, AccessMode, access::target::host_buffer >
Additional Inherited Members
Public Types inherited from trisycl::detail::container_element_aspect< DataType >
using value_type = DataType
using pointer = value_type *
using const_pointer = const value_type *
using reference = value_type &
using const_reference = const value_type &
Static Public Member Functions inherited from trisycl::accessor< DataType, Dimensions, access::mode::read_write, access::target::host_buffer >
static auto constexpr access_mode ()
Introspect the access_mode.
static auto constexpr target ()
Introspect the target.
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< accessor< DataType, Dimensions, AccessMode, Target >, detail::accessor< DataType, Dimensions, AccessMode, Target > >
std::shared_ptr< detail::accessor< DataType, Dimensions, AccessMode, Target > > implementation
The implementation forward everything to this... implementation.
Static Public Attributes inherited from trisycl::accessor< DataType, Dimensions, access::mode::read_write, access::target::host_buffer >
static constexpr auto dimensionality
Member Typedef Documentation
base
template<typename DataType , int Dimensions, access::mode AccessMode = access::mode::read_write> using trisycl::host_accessor< DataType, Dimensions, AccessMode >::base = accessor<DataType, Dimensions, AccessMode, access::target::host_buffer> private
Definition at line 503 of file accessor.hpp.
Constructor & Destructor Documentation
host_accessor()
template<typename DataType , int Dimensions, access::mode AccessMode = access::mode::read_write> template<typename Allocator > trisycl::host_accessor< DataType, Dimensions, AccessMode >::host_accessor (buffer< DataType, Dimensions, Allocator > & target_buffer) inline
Create an accessor to a buffer to access from the host.
Definition at line 512 of file accessor.hpp.
    : base { target_buffer } {}
Member Function Documentation
accessor() [1/4]
template<typename DataType , int Dimensions, access::mode AccessMode = access::mode::read_write> template<typename Allocator > trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (buffer< DataType, Dimensions, Allocator > & target_buffer) inline
Construct a buffer accessor from a buffer.
Constructor only available for host_buffer target.
access_target defines the form of access being obtained.
Definition at line 125 of file accessor.hpp.
    : implementation_t {
    new detail::accessor<DataType, Dimensions, AccessMode, Target> {
      target_buffer.implementation->implementation }
  } {
    static_assert(Target == access::target::host_buffer,
                  "without a handler, access target should be host_buffer");
  }
accessor() [2/4]
template<typename DataType , int Dimensions, access::mode AccessMode = access::mode::read_write> template<typename Allocator > trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (buffer< DataType, Dimensions, Allocator > & target_buffer, handler & command_group_handler) inline
Construct a buffer accessor from a buffer using a command group handler object from the command group scope.
Constructor only available for global_buffer or constant_buffer target.
access_target defines the form of access being obtained.
Todo:
Add template allocator type in all the accessor constructors in the specification or just use a more opaque Buffer type?
Todo:
fix specification where access mode should be target instead
Definition at line 104 of file accessor.hpp.
                                           : implementation_t {
    new detail::accessor<DataType, Dimensions, AccessMode, Target> {
      target_buffer.implementation->implementation, command_group_handler }
  } {
    static_assert(Target == access::target::global_buffer
                  || Target == access::target::constant_buffer,
                  "access target should be global_buffer or constant_buffer "
                  "when a handler is used");
    // Now the implementation is created, register it
    implementation->register_accessor();
  }
accessor() [3/4]
template<typename DataType , int Dimensions, access::mode AccessMode = access::mode::read_write> template<typename Allocator > trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (buffer< DataType, Dimensions, Allocator > & target_buffer, handler & command_group_handler, const range< Dimensions > & offset, const range< Dimensions > & range) inline
Construct a buffer accessor from a buffer given a specific range for access permissions and an offset that provides the starting point for the access range using a command group handler object from the command group scope.
This accessor limits the processing of the buffer to the [offset, offset+range[ for every dimension. Any other parts of the buffer will be unaffected.
Constructor only available for access modes global_buffer, and constant_buffer (see Table "Buffer accessor constructors"). access_target defines the form of access being obtained.
This accessor is recommended for discard-write and discard read write access modes, when the unaffected parts of the processing should be retained.
Definition at line 153 of file accessor.hpp.
{
    TRISYCL_UNIMPL;
  }
accessor() [4/4]
template<typename DataType , int Dimensions, access::mode AccessMode = access::mode::read_write> trisycl::accessor< DataType, Dimensions, AccessMode, Target >::accessor (const range< Dimensions > & allocation_size, handler & command_group_handler) inline
Construct an accessor of dimension Dimensions with elements of type DataType using the passed range to specify the size in each dimension.
It needs as a parameter a command group handler object from the command group scope. Constructor only available if AccessMode is local, see Table 3.25.
Definition at line 169 of file accessor.hpp.
    : implementation_t { new detail::accessor<DataType,
                                              Dimensions,
                                              AccessMode,
                                              access::target::local> {
      allocation_size, command_group_handler
        }
  }
  {
    static_assert(Target == access::target::local,
                  "This accessor constructor requires "
                  "access target be local");
  }
trisycl::sycl_2_2::pipe
class trisycl::sycl_2_2::pipe
template<typename T>
class trisycl::sycl_2_2::pipe< T >
A SYCL pipe.
This is a proposal for the now abandoned SYCL 2.2 provisional specification. This is still here for historical reasons.
Implement a FIFO-style object that can be used through accessors to send some objects T from the input to the output
Definition at line 38 of file pipe.hpp.
Public Types
using value_type = T
The STL-like types.
Public Member Functions
pipe (std::size_t capacity)
Construct a pipe able to store up to capacity T objects.
template<access::mode Mode, access::target Target = access::target::pipe>
accessor< value_type, 1, Mode, Target > get_access (handler &command_group_handler)
Get an accessor to the pipe with the required mode.
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< pipe< T >, detail::sycl_2_2::pipe< T > >
shared_ptr_implementation (std::shared_ptr< detail::sycl_2_2::pipe< T > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::sycl_2_2::pipe< T > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename pipe::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< pipe< T >, detail::sycl_2_2::pipe< T > >
std::shared_ptr< detail::sycl_2_2::pipe< T > > implementation
The implementation forward everything to this... implementation.
Static Private Member Functions inherited from trisycl::detail::debug< pipe< T > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Typedef Documentation
implementation_t
template<typename T > using trisycl::sycl_2_2::pipe< T >::implementation_t = typename pipe::shared_ptr_implementation private
Definition at line 46 of file pipe.hpp.
value_type
template<typename T > using trisycl::sycl_2_2::pipe< T >::value_type = T
The STL-like types.
Definition at line 59 of file pipe.hpp.
Constructor & Destructor Documentation
pipe()
template<typename T > trisycl::sycl_2_2::pipe< T >::pipe (std::size_t capacity) inline
Construct a pipe able to store up to capacity T objects.
Definition at line 63 of file pipe.hpp.
    : implementation_t { new detail::sycl_2_2::pipe<T> { capacity } } { }
References trisycl::sycl_2_2::pipe< T >::capacity().
Member Function Documentation
capacity()
template<typename T > std::size_t trisycl::sycl_2_2::pipe< T >::capacity () const inline
Return the maximum number of elements that can fit in the pipe.
Definition at line 89 of file pipe.hpp.
{
    return implementation->capacity();
    }
Referenced by trisycl::sycl_2_2::pipe< T >::pipe().
get_access()
template<typename T > template<access::mode Mode, access::target Target = access::target::pipe> accessor< value_type, 1, Mode, Target > trisycl::sycl_2_2::pipe< T >::get_access (handler & command_group_handler) inline
Get an accessor to the pipe with the required mode.
Parameters
Mode is the requested access mode
Target is the type of pipe access required
[in] command_group_handler is the command group handler in which the kernel is to be executed
Definition at line 79 of file pipe.hpp.
{
    static_assert(Target == access::target::pipe
                  || Target == access::target::blocking_pipe,
                  "get_access(handler) with pipes can only deal with "
                  "access::pipe or access::blocking_pipe");
    return { implementation, command_group_handler };
  }
References trisycl::access::blocking_pipe, and trisycl::access::pipe.
Member Data Documentation
implementation_t
template<typename T > friend trisycl::sycl_2_2::pipe< T >::implementation_t private
Definition at line 49 of file pipe.hpp.
trisycl::detail::sycl_2_2::reserve_id
struct trisycl::detail::sycl_2_2::reserve_id
template<typename T>
struct trisycl::detail::sycl_2_2::reserve_id< T >
A private description of a reservation station.
Definition at line 41 of file pipe.hpp.
Public Member Functions
reserve_id (typename boost::circular_buffer< T >::iterator start, std::size_t size)
Track a reservation not committed yet.
Public Attributes
boost::circular_buffer< T >::iterator start
Start of the reservation in the pipe storage.
std::size_t size
Number of elements in the reservation.
bool ready = false
Constructor & Destructor Documentation
reserve_id()
template<typename T > trisycl::detail::sycl_2_2::reserve_id< T >::reserve_id (typename boost::circular_buffer< T >::iterator start, std::size_t size) inline
Track a reservation not committed yet.
Parameters
[in] start point to the start of the reservation in the pipe storage
[in] size is the number of elements in the reservation
Definition at line 59 of file pipe.hpp.
                             : start { start }, size { size } {}
Member Data Documentation
ready
template<typename T > bool trisycl::detail::sycl_2_2::reserve_id< T >::ready = false
Definition at line 50 of file pipe.hpp.
size
template<typename T > std::size_t trisycl::detail::sycl_2_2::reserve_id< T >::size
Number of elements in the reservation.
Definition at line 46 of file pipe.hpp.
start
template<typename T > boost::circular_buffer<T>::iterator trisycl::detail::sycl_2_2::reserve_id< T >::start
Start of the reservation in the pipe storage.
Definition at line 43 of file pipe.hpp.
trisycl::detail::sycl_2_2::pipe
class trisycl::detail::sycl_2_2::pipe
template<typename T>
class trisycl::detail::sycl_2_2::pipe< T >
Implement a pipe object.
Use some mutable members so that the pipe object can be changed even when the accessors are captured in a lambda.
Definition at line 71 of file pipe.hpp.
Public Types
using value_type = T
using implementation_t = boost::circular_buffer< value_type >
Implement the pipe with a circular buffer.
using rid_iterator = typename decltype(w_rid_q)::iterator
Public Member Functions
pipe (std::size_t capacity)
Create a pipe as a circular buffer of the required capacity.
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size_with_lock () const
The size() method used outside needs to lock the datastructure.
bool empty_with_lock () const
The empty() method used outside needs to lock the datastructure.
bool full_with_lock () const
bool write (const T &value, bool blocking=false)
Try to write a value to the pipe.
bool read (T &value, bool blocking=false)
Try to read a value from the pipe.
std::size_t reserved_for_reading () const
Compute the amount of elements blocked by read reservations, not yet committed.
std::size_t reserved_for_writing () const
Compute the amount of elements blocked by write reservations, not yet committed.
bool reserve_read (std::size_t s, rid_iterator &rid, bool blocking=false)
Reserve some part of the pipe for reading.
bool reserve_write (std::size_t s, rid_iterator &rid, bool blocking=false)
Reserve some part of the pipe for writing.
void move_read_reservation_forward ()
Process the read reservations that are ready to be released in the reservation queue.
void move_write_reservation_forward ()
Process the write reservations that are ready to be released in the reservation queue.
Public Attributes
bool used_for_reading = false
True when the pipe is currently used for reading.
bool used_for_writing = false
True when the pipe is currently used for writing.
Private Member Functions
std::size_t size () const
Get the current number of elements in the pipe that can be read.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
Private Attributes
boost::circular_buffer< value_type > cb
The circular buffer to store the elements.
std::mutex cb_mutex
To protect the access to the circular buffer.
std::deque< reserve_id< value_type > > w_rid_q
The queue of pending write reservations.
std::deque< reserve_id< value_type > > r_rid_q
The queue of pending read reservations.
std::size_t read_reserved_frozen
Track the number of frozen elements related to read reservations.
std::condition_variable read_done
To signal that a read has been successful.
std::condition_variable write_done
To signal that a write has been successful.
bool debug_mode = false
To control the debug mode, disabled by default.
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::debug< pipe< T > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Typedef Documentation
implementation_t
template<typename T > using trisycl::detail::sycl_2_2::pipe< T >::implementation_t = boost::circular_buffer<value_type>
Implement the pipe with a circular buffer.
Definition at line 78 of file pipe.hpp.
rid_iterator
template<typename T > using trisycl::detail::sycl_2_2::pipe< T >::rid_iterator = typename decltype(w_rid_q)::iterator
Definition at line 96 of file pipe.hpp.
value_type
template<typename T > using trisycl::detail::sycl_2_2::pipe< T >::value_type = T
Definition at line 75 of file pipe.hpp.
Constructor & Destructor Documentation
pipe()
template<typename T > trisycl::detail::sycl_2_2::pipe< T >::pipe (std::size_t capacity) inline
Create a pipe as a circular buffer of the required capacity.
Definition at line 127 of file pipe.hpp.
: cb { capacity }, read_reserved_frozen { 0 } { }
Member Function Documentation
capacity()
template<typename T > std::size_t trisycl::detail::sycl_2_2::pipe< T >::capacity () const inline
Return the maximum number of elements that can fit in the pipe.
Definition at line 132 of file pipe.hpp.
{
    // No lock required since it is fixed and set at construction time
    return cb.capacity();
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::reserve_write().
empty()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::empty () const inline private
Test if the pipe is empty.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the write side (for example on FPGA).
Definition at line 167 of file pipe.hpp.
                     {
    TRISYCL_DUMP_T("empty() cb.size() = " << cb.size()
                   << " size() = " << size());
    // It is empty when the size is zero, taking into account reservations
    return size() ==  0;
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb, trisycl::detail::sycl_2_2::pipe< T >::size(), and TRISYCL_DUMP_T.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::empty_with_lock(), and trisycl::detail::sycl_2_2::pipe< T >::read().
empty_with_lock()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::empty_with_lock () const inline
The empty() method used outside needs to lock the datastructure.
Definition at line 198 of file pipe.hpp.
{
    std::lock_guard<std::mutex> lg { cb_mutex };
    return empty();
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, and trisycl::detail::sycl_2_2::pipe< T >::empty().
full()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::full () const inline private
Test if the pipe is full.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the read side (for example on FPGA).
Definition at line 183 of file pipe.hpp.
                    {
    return cb.full();
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::full_with_lock(), and trisycl::detail::sycl_2_2::pipe< T >::write().
full_with_lock()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::full_with_lock () const inline
Definition at line 205 of file pipe.hpp.
{
    std::lock_guard<std::mutex> lg { cb_mutex };
    return full();
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, and trisycl::detail::sycl_2_2::pipe< T >::full().
move_read_reservation_forward()
template<typename T > void trisycl::detail::sycl_2_2::pipe< T >::move_read_reservation_forward () inline
Process the read reservations that are ready to be released in the reservation queue.
Definition at line 432 of file pipe.hpp.
{
    // Lock the pipe to avoid nuisance
    std::unique_lock<std::mutex> lock { cb_mutex };
    for (;;) {
      if (r_rid_q.empty())
        // No pending reservation, so nothing to do
        break;
      if (!r_rid_q.front().ready)
        /* If the first reservation is not ready to be released, stop
           because it is blocking all the following in the queue
           anyway */
        break;
      // Remove the reservation to be released from the queue
      r_rid_q.pop_front();
      std::size_t n_to_pop;
      if (r_rid_q.empty())
        // If it was the last one, remove all the reservation
        n_to_pop = read_reserved_frozen;
      else
        // Else remove everything up to the next reservation
        n_to_pop =  r_rid_q.front().start - cb.begin();
      // No longer take into account these reserved slots
      read_reserved_frozen -= n_to_pop;
      // Release the elements from the FIFO
      while (n_to_pop--)
        cb.pop_front();
      // Notify the clients waiting for some room to write in the pipe
      read_done.notify_all();
      /* ...and process the next reservation to see if it is ready to
         be released too */
    }
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb, trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, trisycl::detail::sycl_2_2::pipe< T >::r_rid_q, trisycl::detail::sycl_2_2::pipe< T >::read_done, and trisycl::detail::sycl_2_2::pipe< T >::read_reserved_frozen.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit().
move_write_reservation_forward()
template<typename T > void trisycl::detail::sycl_2_2::pipe< T >::move_write_reservation_forward () inline
Process the write reservations that are ready to be released in the reservation queue.
Definition at line 470 of file pipe.hpp.
{
    // Lock the pipe to avoid nuisance
    std::lock_guard<std::mutex> lg { cb_mutex };
    for (;;) {
      if (w_rid_q.empty())
        // No pending reservation, so nothing to do
        break;
      // Get the first reservation
      const auto &rid = w_rid_q.front();
      if (!rid.ready)
        /* If the reservation is not ready to be released, stop
           because it is blocking all the following in the queue
           anyway */
        break;
      // Remove the reservation to be released from the queue
      w_rid_q.pop_front();
      // Notify the clients waiting to read something from the pipe
      write_done.notify_all();
      /* ...and process the next reservation to see if it is ready to
         be released too */
    }
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, trisycl::detail::sycl_2_2::pipe< T >::w_rid_q, and trisycl::detail::sycl_2_2::pipe< T >::write_done.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit().
read()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::read (T & value, bool blocking = false) inline
Try to read a value from the pipe.
Parameters
[out] value is the reference to where to store what is read
[in] blocking specify if the call wait for the operation to succeed
Returns
true on success
If there is a pending reservation, read the next element to be read and update the number of reserved elements
Definition at line 262 of file pipe.hpp.
{
    // Lock the pipe to avoid being disturbed
    std::unique_lock<std::mutex> ul { cb_mutex };
    TRISYCL_DUMP_T("Read pipe empty = " << empty());
    if (blocking)
      /* If in blocking mode, wait for the not empty condition, that
         may be changed when a write is done */
      write_done.wait(ul, [&] { return !empty(); });
    else if (empty())
      return false;
    TRISYCL_DUMP_T("Read pipe front = " << cb.front()
                   << " back = " << cb.back()
                   << " reserved_for_reading() = " << reserved_for_reading());
    if (read_reserved_frozen)
      /** If there is a pending reservation, read the next element to
          be read and update the number of reserved elements */
      value = cb.begin()[read_reserved_frozen++];
    else {
      /* There is no pending read reservation, so pop the read value
         from the pipe */
      value = cb.front();
      cb.pop_front();
    }
    TRISYCL_DUMP_T("Read pipe value = " << value);
    // Micro-optimization: unlock before the notification
    // https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all
    ul.unlock();
    // Notify the clients waiting for some room to write in the pipe
    read_done.notify_all();
    return true;
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb, trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, trisycl::detail::sycl_2_2::pipe< T >::empty(), trisycl::detail::sycl_2_2::pipe< T >::read_done, trisycl::detail::sycl_2_2::pipe< T >::read_reserved_frozen, trisycl::detail::sycl_2_2::pipe< T >::reserved_for_reading(), TRISYCL_DUMP_T, and trisycl::detail::sycl_2_2::pipe< T >::write_done.
reserve_read()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::reserve_read (std::size_t s, rid_iterator & rid, bool blocking = false) inline
Reserve some part of the pipe for reading.
Parameters
[in] s is the number of element to reserve
[out] rid is an iterator to a description of the reservation that has been done if successful
[in] blocking specify if the call wait for the operation to succeed
Returns
true if the reservation was successful
Definition at line 342 of file pipe.hpp.
{
    // Lock the pipe to avoid being disturbed
    std::unique_lock<std::mutex> ul { cb_mutex };
    TRISYCL_DUMP_T("Before read reservation cb.size() = " << cb.size()
                   << " size() = " << size());
    if (s == 0)
      // Empty reservation requested, so nothing to do
      return false;
    if (blocking)
      /* If in blocking mode, wait for enough elements to read in the
         pipe for the reservation. This condition can change when a
         write is done */
      write_done.wait(ul, [&] { return s <= size(); });
    else if (s > size())
      // Not enough elements to read in the pipe for the reservation
      return false;
    // Compute the location of the first element of the reservation
    auto first = cb.begin() + read_reserved_frozen;
    // Increment the number of frozen elements
    read_reserved_frozen += s;
    /* Add a description of the reservation at the end of the
       reservation queue */
    r_rid_q.emplace_back(first, s);
    // Return the iterator to the last reservation descriptor
    rid = r_rid_q.end() - 1;
    TRISYCL_DUMP_T("After reservation cb.size() = " << cb.size()
                   << " size() = " << size());
    return true;
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb, trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, trisycl::detail::sycl_2_2::pipe< T >::r_rid_q, trisycl::detail::sycl_2_2::pipe< T >::read_reserved_frozen, trisycl::detail::sycl_2_2::pipe< T >::size(), TRISYCL_DUMP_T, and trisycl::detail::sycl_2_2::pipe< T >::write_done.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation().
reserve_write()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::reserve_write (std::size_t s, rid_iterator & rid, bool blocking = false) inline
Reserve some part of the pipe for writing.
Parameters
[in] s is the number of element to reserve
[out] rid is an iterator to a description of the reservation that has been done if successful
[in] blocking specify if the call wait for the operation to succeed
Returns
true if the reservation was successful
Definition at line 390 of file pipe.hpp.
{
    // Lock the pipe to avoid being disturbed
    std::unique_lock<std::mutex> ul { cb_mutex };
    TRISYCL_DUMP_T("Before write reservation cb.size() = " << cb.size()
                   << " size() = " << size());
    if (s == 0)
      // Empty reservation requested, so nothing to do
      return false;
    if (blocking)
      /* If in blocking mode, wait for enough room in the pipe, that
         may be changed when a read is done. Do not use a difference
         here because it is only about unsigned values */
      read_done.wait(ul, [&] { return cb.size() + s <= capacity(); });
    else if (cb.size() + s > capacity())
      // Not enough room in the pipe for the reservation
      return false;
    /* If there is enough room in the pipe, just create default values
         in it to do the reservation */
    for (std::size_t i = 0; i != s; ++i)
      cb.push_back();
    /* Compute the location of the first element a posteriori since it
         may not exist a priori if cb was empty before */
    auto first = cb.end() - s;
    /* Add a description of the reservation at the end of the
       reservation queue */
    w_rid_q.emplace_back(first, s);
    // Return the iterator to the last reservation descriptor
    rid = w_rid_q.end() - 1;
    TRISYCL_DUMP_T("After reservation cb.size() = " << cb.size()
                   << " size() = " << size());
    return true;
  }
References trisycl::detail::sycl_2_2::pipe< T >::capacity(), trisycl::detail::sycl_2_2::pipe< T >::cb, trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, i, trisycl::detail::sycl_2_2::pipe< T >::read_done, trisycl::detail::sycl_2_2::pipe< T >::size(), TRISYCL_DUMP_T, and trisycl::detail::sycl_2_2::pipe< T >::w_rid_q.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation().
reserved_for_reading()
template<typename T > std::size_t trisycl::detail::sycl_2_2::pipe< T >::reserved_for_reading () const inline
Compute the amount of elements blocked by read reservations, not yet committed.
This includes some normal reads to pipes between/after un-committed reservations
This function assumes that the data structure is locked
Definition at line 306 of file pipe.hpp.
{
    return read_reserved_frozen;
  }
References trisycl::detail::sycl_2_2::pipe< T >::read_reserved_frozen.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::read(), trisycl::detail::sycl_2_2::pipe< T >::size(), and trisycl::detail::sycl_2_2::pipe< T >::write().
reserved_for_writing()
template<typename T > std::size_t trisycl::detail::sycl_2_2::pipe< T >::reserved_for_writing () const inline
Compute the amount of elements blocked by write reservations, not yet committed.
This includes some normal writes to pipes between/after un-committed reservations
This function assumes that the data structure is locked
Definition at line 319 of file pipe.hpp.
{
    if (w_rid_q.empty())
      // No on-going reservation
      return 0;
    else
      /* The reserved size is from the first element of the first
         on-going reservation up to the end of the pipe content */
      return cb.end() - w_rid_q.front().start;
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb, and trisycl::detail::sycl_2_2::pipe< T >::w_rid_q.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::size(), and trisycl::detail::sycl_2_2::pipe< T >::write().
size()
template<typename T > std::size_t trisycl::detail::sycl_2_2::pipe< T >::size () const inline private
Get the current number of elements in the pipe that can be read.
This is obviously a volatile value which is constrained by the theory of restricted relativity.
Note that on some devices it may be costly to implement (for example on FPGA).
Definition at line 147 of file pipe.hpp.
{
    TRISYCL_DUMP_T("size() cb.size() = " << cb.size()
                   << " cb.end() = " << (void *)&*cb.end()
                   << " reserved_for_reading() = " << reserved_for_reading()
                   << " reserved_for_writing() = " << reserved_for_writing());
    /* The actual number of available elements depends from the
       elements blocked by some reservations.
       This prevents a consumer to read into reserved area. */
    return cb.size() - reserved_for_reading() - reserved_for_writing();
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb, trisycl::detail::sycl_2_2::pipe< T >::reserved_for_reading(), trisycl::detail::sycl_2_2::pipe< T >::reserved_for_writing(), and TRISYCL_DUMP_T.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::empty(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::end(), trisycl::detail::sycl_2_2::pipe< T >::reserve_read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_write(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::size(), and trisycl::detail::sycl_2_2::pipe< T >::size_with_lock().
size_with_lock()
template<typename T > std::size_t trisycl::detail::sycl_2_2::pipe< T >::size_with_lock () const inline
The size() method used outside needs to lock the datastructure.
Definition at line 191 of file pipe.hpp.
{
    std::lock_guard<std::mutex> lg { cb_mutex };
    return size();
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, and trisycl::detail::sycl_2_2::pipe< T >::size().
write()
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::write (const T & value, bool blocking = false) inline
Try to write a value to the pipe.
Parameters
[in] value is what we want to write
[in] blocking specify if the call wait for the operation to succeed
Returns
true on success
Todo:
provide a && version
Definition at line 222 of file pipe.hpp.
{
    // Lock the pipe to avoid being disturbed
    std::unique_lock<std::mutex> ul { cb_mutex };
    TRISYCL_DUMP_T("Write pipe full = " << full()
                   << " value = " << value);
    if (blocking)
      /* If in blocking mode, wait for the not full condition, that
         may be changed when a read is done */
      read_done.wait(ul, [&] { return !full(); });
    else if (full())
      return false;
    cb.push_back(value);
    TRISYCL_DUMP_T("Write pipe front = " << cb.front()
                   << " back = " << cb.back()
                   << " cb.begin() = " << (void *)&*cb.begin()
                   << " cb.size() = " << cb.size()
                   << " cb.end() = " << (void *)&*cb.end()
                   << " reserved_for_reading() = " << reserved_for_reading()
                   << " reserved_for_writing() = " << reserved_for_writing());
    // Micro-optimization: unlock before the notification
    // https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all
    ul.unlock();
    // Notify the clients waiting to read something from the pipe
    write_done.notify_all();
    return true;
  }
References trisycl::detail::sycl_2_2::pipe< T >::cb, trisycl::detail::sycl_2_2::pipe< T >::cb_mutex, trisycl::detail::sycl_2_2::pipe< T >::full(), trisycl::detail::sycl_2_2::pipe< T >::read_done, trisycl::detail::sycl_2_2::pipe< T >::reserved_for_reading(), trisycl::detail::sycl_2_2::pipe< T >::reserved_for_writing(), TRISYCL_DUMP_T, and trisycl::detail::sycl_2_2::pipe< T >::write_done.
Member Data Documentation
cb
template<typename T > boost::circular_buffer<value_type> trisycl::detail::sycl_2_2::pipe< T >::cb private
The circular buffer to store the elements.
Definition at line 83 of file pipe.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::capacity(), trisycl::detail::sycl_2_2::pipe< T >::empty(), trisycl::detail::sycl_2_2::pipe< T >::full(), trisycl::detail::sycl_2_2::pipe< T >::move_read_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_write(), trisycl::detail::sycl_2_2::pipe< T >::reserved_for_writing(), trisycl::detail::sycl_2_2::pipe< T >::size(), and trisycl::detail::sycl_2_2::pipe< T >::write().
cb_mutex
template<typename T > std::mutex trisycl::detail::sycl_2_2::pipe< T >::cb_mutex mutable private
To protect the access to the circular buffer.
In case the object is capture in a lambda per copy, make it mutable.
Definition at line 89 of file pipe.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::empty_with_lock(), trisycl::detail::sycl_2_2::pipe< T >::full_with_lock(), trisycl::detail::sycl_2_2::pipe< T >::move_read_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::move_write_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_write(), trisycl::detail::sycl_2_2::pipe< T >::size_with_lock(), and trisycl::detail::sycl_2_2::pipe< T >::write().
debug_mode
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::debug_mode = false private
To control the debug mode, disabled by default.
Definition at line 116 of file pipe.hpp.
r_rid_q
template<typename T > std::deque<reserve_id<value_type> > trisycl::detail::sycl_2_2::pipe< T >::r_rid_q private
The queue of pending read reservations.
Definition at line 104 of file pipe.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::move_read_reservation_forward(), and trisycl::detail::sycl_2_2::pipe< T >::reserve_read().
read_done
template<typename T > std::condition_variable trisycl::detail::sycl_2_2::pipe< T >::read_done private
To signal that a read has been successful.
Definition at line 110 of file pipe.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::move_read_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_write(), and trisycl::detail::sycl_2_2::pipe< T >::write().
read_reserved_frozen
template<typename T > std::size_t trisycl::detail::sycl_2_2::pipe< T >::read_reserved_frozen private
Track the number of frozen elements related to read reservations.
Definition at line 107 of file pipe.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::move_read_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_read(), and trisycl::detail::sycl_2_2::pipe< T >::reserved_for_reading().
used_for_reading
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::used_for_reading = false
True when the pipe is currently used for reading.
Definition at line 121 of file pipe.hpp.
used_for_writing
template<typename T > bool trisycl::detail::sycl_2_2::pipe< T >::used_for_writing = false
True when the pipe is currently used for writing.
Definition at line 124 of file pipe.hpp.
w_rid_q
template<typename T > std::deque<reserve_id<value_type> > trisycl::detail::sycl_2_2::pipe< T >::w_rid_q private
The queue of pending write reservations.
Definition at line 92 of file pipe.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::move_write_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::reserve_write(), and trisycl::detail::sycl_2_2::pipe< T >::reserved_for_writing().
write_done
template<typename T > std::condition_variable trisycl::detail::sycl_2_2::pipe< T >::write_done private
To signal that a write has been successful.
Definition at line 113 of file pipe.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe< T >::move_write_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_read(), and trisycl::detail::sycl_2_2::pipe< T >::write().
trisycl::detail::sycl_2_2::pipe_accessor
class trisycl::detail::sycl_2_2::pipe_accessor
template<typename T, access::mode AccessMode, access::target Target>
class trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >
The accessor abstracts the way pipe data are accessed inside a kernel.
Definition at line 49 of file pipe_accessor.hpp.
Public Types
using value_type = T
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
Public Member Functions
pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< T > > &p)
Construct a pipe accessor from an existing pipe.
pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< T > > &p, handler &command_group_handler)
Construct a pipe accessor from an existing pipe.
pipe_accessor ()=default
std::size_t capacity () const
Return the maximum number of elements that can fit in the pipe.
std::size_t size () const
Get the current number of elements in the pipe.
bool empty () const
Test if the pipe is empty.
bool full () const
Test if the pipe is full.
operator bool () const
In an explicit bool context, the accessor gives the success status of the last access.
const pipe_accessor & write (const value_type &value) const
Try to write a value to the pipe.
const pipe_accessor & operator<< (const value_type &value) const
Some syntactic sugar to use.
const pipe_accessor & read (value_type &value) const
Try to read a value from the pipe.
value_type read () const
Read a value from a blocking pipe.
const pipe_accessor & operator>> (value_type &value) const
Some syntactic sugar to use.
detail::sycl_2_2::pipe_reservation< pipe_accessor > reserve (std::size_t size) const
void set_debug (bool enable) const
Set debug mode.
auto & get_pipe_detail ()
~pipe_accessor ()
Static Public Attributes
static constexpr auto rank = 1
static constexpr auto mode = AccessMode
static constexpr auto target = Target
static constexpr bool blocking
Private Attributes
std::shared_ptr< detail::sycl_2_2::pipe< T > > implementation
The real pipe implementation behind the hood.
bool ok = false
Store the success status of last pipe operation.
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::debug< detail::sycl_2_2::pipe_accessor< T, AccessMode, Target > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Typedef Documentation
const_reference
template<typename T , access::mode AccessMode, access::target Target> using trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::const_reference = const value_type&
Definition at line 64 of file pipe_accessor.hpp.
reference
template<typename T , access::mode AccessMode, access::target Target> using trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::reference = value_type&
Definition at line 63 of file pipe_accessor.hpp.
value_type
template<typename T , access::mode AccessMode, access::target Target> using trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::value_type = T
The STL-like types.
Definition at line 62 of file pipe_accessor.hpp.
Constructor & Destructor Documentation
pipe_accessor() [1/3]
template<typename T , access::mode AccessMode, access::target Target> trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< T > > & p) inline
Construct a pipe accessor from an existing pipe.
Todo:
Use pipe_exception instead
Definition at line 88 of file pipe_accessor.hpp.
    : implementation { p } {
    //    TRISYCL_DUMP_T("Create a kernel pipe accessor write = "
    //                 << is_write_access());
    // Verify that the pipe is not already used in the requested mode
    if (mode == access::mode::write)
      if (implementation->used_for_writing)
        /// \todo Use pipe_exception instead
        throw std::logic_error { "The pipe is already used for writing." };
      else
        implementation->used_for_writing = true;
    else
      if (implementation->used_for_reading)
        throw std::logic_error { "The pipe is already used for reading." };
      else
        implementation->used_for_reading = true;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode, and trisycl::access::write.
pipe_accessor() [2/3]
template<typename T , access::mode AccessMode, access::target Target> trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::pipe_accessor (const std::shared_ptr< detail::sycl_2_2::pipe< T > > & p, handler & command_group_handler) inline
Construct a pipe accessor from an existing pipe.
For now the handler is not used.
Definition at line 111 of file pipe_accessor.hpp.
    : pipe_accessor(p) {}
pipe_accessor() [3/3]
template<typename T , access::mode AccessMode, access::target Target> trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::pipe_accessor () default
~pipe_accessor()
template<typename T , access::mode AccessMode, access::target Target> trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::~pipe_accessor () inline
Free the pipe for a future usage for the current mode
Definition at line 286 of file pipe_accessor.hpp.
                   {
    /// Free the pipe for a future usage for the current mode
    if (mode == access::mode::write)
      implementation->used_for_writing = false;
    else
      implementation->used_for_reading = false;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode, and trisycl::access::write.
Member Function Documentation
capacity()
template<typename T , access::mode AccessMode, access::target Target> std::size_t trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::capacity () const inline
Return the maximum number of elements that can fit in the pipe.
Definition at line 120 of file pipe_accessor.hpp.
{
    return implementation->capacity();
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation.
empty()
template<typename T , access::mode AccessMode, access::target Target> bool trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::empty () const inline
Test if the pipe is empty.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the write side (for example on FPGA).
Definition at line 145 of file pipe_accessor.hpp.
                     {
    return implementation->empty_with_lock();
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation.
full()
template<typename T , access::mode AccessMode, access::target Target> bool trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::full () const inline
Test if the pipe is full.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement on the read side (for example on FPGA).
Definition at line 158 of file pipe_accessor.hpp.
                    {
    return implementation->full_with_lock();
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation.
get_pipe_detail()
template<typename T , access::mode AccessMode, access::target Target> auto & trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::get_pipe_detail () inline
Definition at line 281 of file pipe_accessor.hpp.
{
    return implementation;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation.
operator bool()
template<typename T , access::mode AccessMode, access::target Target> trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator bool () const inline explicit
In an explicit bool context, the accessor gives the success status of the last access.
It is not impacted by reservation success.
The explicitness is related to avoid
 some_pipe <<
some_value
to be interpreted as
 some_bool <<
some_value
when the type of
some_value
is not the same type as the pipe type.
Returns
true on success of the previous read or write operation
Definition at line 175 of file pipe_accessor.hpp.
{
    return ok;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::ok.
operator<<()
template<typename T , access::mode AccessMode, access::target Target> const pipe_accessor & trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator<< (const value_type & value) const inline
Some syntactic sugar to use.
a << v
instead of
a.write(v)
Definition at line 205 of file pipe_accessor.hpp.
{
    static_assert(mode == access::mode::write,
                  "'<<' operator on a pipe accessor is only possible"
                  " with write access mode");
    // Return a reference to *this so we can apply a sequence of >>
    return write(value);
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode, trisycl::access::write, and trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::write().
operator>>()
template<typename T , access::mode AccessMode, access::target Target> const pipe_accessor & trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator>> (value_type & value) const inline
Some syntactic sugar to use.
a >> v
instead of
a.read(v)
Definition at line 260 of file pipe_accessor.hpp.
{
    static_assert(mode == access::mode::read,
                  "'>>' operator on a pipe accessor is only possible"
                  " with read access mode");
    // Return a reference to *this so we can apply a sequence of >>
    return read(value);
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode, trisycl::access::read, and trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::read().
read() [1/2]
template<typename T , access::mode AccessMode, access::target Target> value_type trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::read () const inline
Read a value from a blocking pipe.
Returns
the read value directly, since it cannot fail on blocking pipe
This function is const so it can work when the accessor is passed by copy in the [=] kernel lambda, which is not mutable by default
Definition at line 245 of file pipe_accessor.hpp.
{
    static_assert(mode == access::mode::read,
                  "'.read()' method on a pipe accessor is only possible"
                  " with read access mode");
    static_assert(blocking,
                  "'.read()' method on a pipe accessor is only possible"
                  " with a blocking pipe");
    value_type value;
    implementation->read(value, blocking);
    return value;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::blocking, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode, and trisycl::access::read.
Referenced by trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator>>().
read() [2/2]
template<typename T , access::mode AccessMode, access::target Target> const pipe_accessor & trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::read (value_type & value) const inline
Try to read a value from the pipe.
Parameters
[out] value is the reference to where to store what is read
Returns
this
so we can apply a sequence of read for example (but do not do this on a non blocking pipe...)
This function is const so it can work when the accessor is passed by copy in the [=] kernel lambda, which is not mutable by default
Definition at line 226 of file pipe_accessor.hpp.
{
    static_assert(mode == access::mode::read,
                  "'.read(value_type &value)' method on a pipe accessor"
                  " is only possible with read access mode");
    ok = implementation->read(value, blocking);
    // Return a reference to *this so we can apply a sequence of read
    return *this;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::blocking, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::ok, and trisycl::access::read.
reserve()
template<typename T , access::mode AccessMode, access::target Target> detail::sycl_2_2::pipe_reservation< pipe_accessor > trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::reserve (std::size_t size) const inline
Definition at line 270 of file pipe_accessor.hpp.
{
    return { *implementation, size };
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation, and trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::size().
set_debug()
template<typename T , access::mode AccessMode, access::target Target> void trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::set_debug (bool enable) const inline
Set debug mode.
Definition at line 276 of file pipe_accessor.hpp.
{
    implementation->debug_mode = enable;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation.
size()
template<typename T , access::mode AccessMode, access::target Target> std::size_t trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::size () const inline
Get the current number of elements in the pipe.
This is obviously a volatile value which is constrained by restricted relativity.
Note that on some devices it may be costly to implement (for example on FPGA).
Definition at line 132 of file pipe_accessor.hpp.
{
    return implementation->size_with_lock();
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation.
Referenced by trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::reserve().
write()
template<typename T , access::mode AccessMode, access::target Target> const pipe_accessor & trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::write (const value_type & value) const inline
Try to write a value to the pipe.
Parameters
[in] value is what we want to write
Returns
this so we can apply a sequence of write for example (but do not do this on a non blocking pipe...)
Todo:
provide a && version
This function is const so it can work when the accessor is passed by copy in the [=] kernel lambda, which is not mutable by default
Definition at line 193 of file pipe_accessor.hpp.
{
    static_assert(mode == access::mode::write,
                  "'.write(const value_type &value)' method on a pipe accessor"
                  " is only possible with write access mode");
    ok = implementation->write(value, blocking);
    // Return a reference to *this so we can apply a sequence of write
    return *this;
  }
References trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::blocking, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode, trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::ok, and trisycl::access::write.
Referenced by trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator<<().
Member Data Documentation
blocking
template<typename T , access::mode AccessMode, access::target Target> constexpr bool trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::blocking static constexpr
Initial value:
=
    (target == trisycl::access::target::blocking_pipe)
Definition at line 58 of file pipe_accessor.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::read(), and trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::write().
implementation
template<typename T , access::mode AccessMode, access::target Target> std::shared_ptr<detail::sycl_2_2::pipe<T> > trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::implementation private
The real pipe implementation behind the hood.
Definition at line 69 of file pipe_accessor.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::capacity(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::empty(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::full(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::get_pipe_detail(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::pipe_accessor(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::read(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::reserve(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::set_debug(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::size(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::write(), and trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::~pipe_accessor().
mode
template<typename T , access::mode AccessMode, access::target Target> constexpr auto trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::mode = AccessMode static constexpr
Definition at line 55 of file pipe_accessor.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator<<(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator>>(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::pipe_accessor(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::read(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::write(), and trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::~pipe_accessor().
ok
template<typename T , access::mode AccessMode, access::target Target> bool trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::ok = false mutable private
Store the success status of last pipe operation.
It is not impacted by reservation success.
It does exist even if the pipe accessor is not evaluated in a boolean context for, but a use-def analysis can optimise it out in that case and not use some storage
Use a mutable state here so that it can work with a [=] lambda capture without having to declare the whole lambda as mutable
Definition at line 82 of file pipe_accessor.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::operator bool(), trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::read(), and trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::write().
rank
template<typename T , access::mode AccessMode, access::target Target> constexpr auto trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::rank = 1 static constexpr
Definition at line 54 of file pipe_accessor.hpp.
target
template<typename T , access::mode AccessMode, access::target Target> constexpr auto trisycl::detail::sycl_2_2::pipe_accessor< T, AccessMode, Target >::target = Target static constexpr
Definition at line 56 of file pipe_accessor.hpp.
trisycl::sycl_2_2::pipe_reservation
struct trisycl::sycl_2_2::pipe_reservation
template<typename PipeAccessor>
struct trisycl::sycl_2_2::pipe_reservation< PipeAccessor >
The pipe reservation station allows to reserve an array-like view inside the pipe for ordered race-free access from various work-items for example.
Definition at line 32 of file pipe_reservation.hpp.
Public Types
using accessor_type = PipeAccessor
using accessor_detail = typename accessor_type::accessor_detail
using value_type = typename accessor_type::value_type
The STL-like types.
using reference = value_type &
using const_reference = const value_type &
using pointer = value_type *
using const_pointer = const value_type *
using size_type = std::size_t
using difference_type = ptrdiff_t
using iterator = typename detail::sycl_2_2::pipe_reservation< accessor_detail >::iterator
using const_iterator = typename detail::sycl_2_2::pipe_reservation< accessor_detail >::const_iterator
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
pipe_reservation ()=default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or a r-value (for std::move() for example).
pipe_reservation (accessor_type &accessor, std::size_t s)
Create a pipe_reservation for an accessor and a number of elements.
pipe_reservation (detail::sycl_2_2::pipe_reservation< accessor_detail > &&pr)
Create a pipe_reservation from the implementation detail.
operator bool () const
Test if the pipe_reservation has been correctly allocated.
std::size_t size () const
Get the number of reserved element(s)
reference operator[] (std::size_t index) const
Access to a given element of the reservation.
void commit () const
Force a commit operation.
iterator begin () const
Get an iterator on the first element of the reservation station.
iterator end () const
Get an iterator past the end of the reservation station.
const_iterator cbegin () const
Build a constant iterator on the first element of the reservation station.
const_iterator cend () const
Build a constant iterator past the end of the reservation station.
reverse_iterator rbegin () const
Get a reverse iterator on the last element of the reservation station.
reverse_iterator rend () const
Get a reverse iterator on the first element past the end of the reservation station.
const_reverse_iterator crbegin () const
Get a constant reverse iterator on the last element of the reservation station.
const_reverse_iterator crend () const
Get a constant reverse iterator on the first element past the end of the reservation station.
Public Attributes
std::shared_ptr< detail::sycl_2_2::pipe_reservation< accessor_detail > > implementation
Point to the underlying implementation that can be shared in the SYCL model with a handler semantics.
Static Public Attributes
static constexpr bool blocking
Member Typedef Documentation
accessor_detail
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::accessor_detail = typename accessor_type::accessor_detail
Definition at line 36 of file pipe_reservation.hpp.
accessor_type
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::accessor_type = PipeAccessor
Definition at line 33 of file pipe_reservation.hpp.
const_iterator
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::const_iterator = typename detail::sycl_2_2::pipe_reservation<accessor_detail>::const_iterator
Definition at line 47 of file pipe_reservation.hpp.
const_pointer
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::const_pointer = const value_type*
Definition at line 42 of file pipe_reservation.hpp.
const_reference
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::const_reference = const value_type&
Definition at line 40 of file pipe_reservation.hpp.
const_reverse_iterator
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 50 of file pipe_reservation.hpp.
difference_type
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::difference_type = ptrdiff_t
Definition at line 44 of file pipe_reservation.hpp.
iterator
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::iterator = typename detail::sycl_2_2::pipe_reservation<accessor_detail>::iterator
Definition at line 45 of file pipe_reservation.hpp.
pointer
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::pointer = value_type*
Definition at line 41 of file pipe_reservation.hpp.
reference
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::reference = value_type&
Definition at line 39 of file pipe_reservation.hpp.
reverse_iterator
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 49 of file pipe_reservation.hpp.
size_type
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::size_type = std::size_t
Definition at line 43 of file pipe_reservation.hpp.
value_type
template<typename PipeAccessor > using trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::value_type = typename accessor_type::value_type
The STL-like types.
Definition at line 38 of file pipe_reservation.hpp.
Constructor & Destructor Documentation
pipe_reservation() [1/3]
template<typename PipeAccessor > trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation () default
Use default constructors so that we can create a new buffer copy from another one, with either a l-value or a r-value (for std::move() for example).
Since we just copy the shared_ptr<> above, this is where/how the sharing magic is happening with reference counting in this case.
pipe_reservation() [2/3]
template<typename PipeAccessor > trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation (accessor_type & accessor, std::size_t s) inline
Create a pipe_reservation for an accessor and a number of elements.
Definition at line 68 of file pipe_reservation.hpp.
    : implementation {
    new detail::sycl_2_2::pipe_reservation<accessor_detail> {
      get_pipe_detail(accessor), s }
  } {}
References trisycl::get_pipe_detail().
pipe_reservation() [3/3]
template<typename PipeAccessor > trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation (detail::sycl_2_2::pipe_reservation< accessor_detail > && pr) inline
Create a pipe_reservation from the implementation detail.
This is an internal constructor to allow reserve() on the implementation to lift a full-fledged object through accessor::reserve().
Todo:
Make it private and add required friends
Definition at line 83 of file pipe_reservation.hpp.
    : implementation {
    new detail::sycl_2_2::pipe_reservation<accessor_detail> { std::move(pr) } }
  {}
Member Function Documentation
begin()
template<typename PipeAccessor > iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::begin () const inline
Get an iterator on the first element of the reservation station.
Definition at line 121 of file pipe_reservation.hpp.
{
    return implementation->begin();
  }
cbegin()
template<typename PipeAccessor > const_iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::cbegin () const inline
Build a constant iterator on the first element of the reservation station.
Definition at line 133 of file pipe_reservation.hpp.
{
    return implementation->begin();
  }
cend()
template<typename PipeAccessor > const_iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::cend () const inline
Build a constant iterator past the end of the reservation station.
Definition at line 139 of file pipe_reservation.hpp.
{
    return implementation->end();
  }
commit()
template<typename PipeAccessor > void trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::commit () const inline
Force a commit operation.
Normally the commit is implicitly done in the destructor, but sometime it is useful to do it earlier.
Definition at line 115 of file pipe_reservation.hpp.
                      {
    return implementation->commit();
  }
crbegin()
template<typename PipeAccessor > const_reverse_iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::crbegin () const inline
Get a constant reverse iterator on the last element of the reservation station.
Definition at line 159 of file pipe_reservation.hpp.
{
    return std::make_reverse_iterator(cend());
  }
crend()
template<typename PipeAccessor > const_reverse_iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::crend () const inline
Get a constant reverse iterator on the first element past the end of the reservation station.
Definition at line 166 of file pipe_reservation.hpp.
{
    return std::make_reverse_iterator(cbegin());
  }
end()
template<typename PipeAccessor > iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::end () const inline
Get an iterator past the end of the reservation station.
Definition at line 127 of file pipe_reservation.hpp.
                       {
    return implementation->end();
  }
operator bool()
template<typename PipeAccessor > trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::operator bool () const inline
Test if the pipe_reservation has been correctly allocated.
Returns
true if the pipe_reservation can be used and committed
Definition at line 93 of file pipe_reservation.hpp.
{
    return *implementation;
  }
operator[]()
template<typename PipeAccessor > reference trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::operator[] (std::size_t index) const inline
Access to a given element of the reservation.
Definition at line 105 of file pipe_reservation.hpp.
{
    return (*implementation)[index];
  }
rbegin()
template<typename PipeAccessor > reverse_iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::rbegin () const inline
Get a reverse iterator on the last element of the reservation station.
Definition at line 145 of file pipe_reservation.hpp.
{
    return std::make_reverse_iterator(end());
  }
rend()
template<typename PipeAccessor > reverse_iterator trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::rend () const inline
Get a reverse iterator on the first element past the end of the reservation station.
Definition at line 152 of file pipe_reservation.hpp.
{
    return std::make_reverse_iterator(begin());
  }
size()
template<typename PipeAccessor > std::size_t trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::size () const inline
Get the number of reserved element(s)
Definition at line 99 of file pipe_reservation.hpp.
{
    return implementation->size();
  }
Member Data Documentation
blocking
template<typename PipeAccessor > constexpr bool trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::blocking static constexpr
Initial value:
=
    (accessor_type::target == trisycl::access::target::blocking_pipe)
Definition at line 34 of file pipe_reservation.hpp.
implementation
template<typename PipeAccessor > std::shared_ptr<detail::sycl_2_2::pipe_reservation<accessor_detail> > trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::implementation
Point to the underlying implementation that can be shared in the SYCL model with a handler semantics.
Definition at line 55 of file pipe_reservation.hpp.
trisycl::detail::sycl_2_2::pipe_reservation
class trisycl::detail::sycl_2_2::pipe_reservation
template<typename PipeAccessor>
class trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >
The implementation of the pipe reservation station.
Definition at line 36 of file pipe_reservation.hpp.
Public Types
using iterator = typename detail::sycl_2_2::pipe< value_type >::implementation_t::iterator
using const_iterator = typename detail::sycl_2_2::pipe< value_type >::implementation_t::const_iterator
Public Member Functions
void assume_validity ()
Test that the reservation is in a usable state.
pipe_reservation (detail::sycl_2_2::pipe< value_type > &p, std::size_t s)
Create a pipe reservation station that reserves the pipe itself.
pipe_reservation (const pipe_reservation &)=delete
No copy constructor with some spurious commit in the destructor of the original object.
pipe_reservation (pipe_reservation &&orig)
Only a move constructor is required to move it into the shared_ptr.
pipe_reservation ()=default
Keep the default constructors too.
operator bool ()
Test if the reservation succeeded and thus if the reservation can be committed.
iterator begin ()
Start of the reservation area.
iterator end ()
Past the end of the reservation area.
std::size_t size ()
Get the number of elements in the reservation station.
reference operator[] (std::size_t index)
Access to an element of the reservation.
void commit ()
Commit the reservation station.
~pipe_reservation ()
An implicit commit is made in the destructor.
Public Attributes
bool ok = false
True if the reservation was successful and still uncommitted.
detail::sycl_2_2::pipe< value_type >::rid_iterator rid
Point into the reservation buffer. Only valid if ok is true.
detail::sycl_2_2::pipe< value_type > & p
Keep a reference on the pipe to access to the data and methods.
Static Public Attributes
static constexpr access::mode mode = accessor_type::mode
static constexpr access::target target = accessor_type::target
Private Types
using accessor_type = PipeAccessor
using value_type = typename accessor_type::value_type
using reference = typename accessor_type::reference
Static Private Attributes
static constexpr bool blocking
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::debug< detail::sycl_2_2::pipe_reservation< PipeAccessor > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Typedef Documentation
accessor_type
template<typename PipeAccessor > using trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::accessor_type = PipeAccessor private
Definition at line 38 of file pipe_reservation.hpp.
const_iterator
template<typename PipeAccessor > using trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::const_iterator = typename detail::sycl_2_2::pipe<value_type>::implementation_t::const_iterator
Definition at line 48 of file pipe_reservation.hpp.
iterator
template<typename PipeAccessor > using trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::iterator = typename detail::sycl_2_2::pipe<value_type>::implementation_t::iterator
Definition at line 46 of file pipe_reservation.hpp.
reference
template<typename PipeAccessor > using trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::reference = typename accessor_type::reference private
Definition at line 42 of file pipe_reservation.hpp.
value_type
template<typename PipeAccessor > using trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::value_type = typename accessor_type::value_type private
Definition at line 41 of file pipe_reservation.hpp.
Constructor & Destructor Documentation
pipe_reservation() [1/4]
template<typename PipeAccessor > trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation (detail::sycl_2_2::pipe< value_type > & p, std::size_t s) inline
Create a pipe reservation station that reserves the pipe itself.
Definition at line 81 of file pipe_reservation.hpp.
    : p { p } {
    static_assert(mode == access::mode::write
                  || mode == access::mode::read,
                  "A pipe can only be accesed in read or write mode,"
                  " exclusively");
    /* Since this test is constexpr and dependent of a template
       parameter, it should be equivalent to a specialization of the
       method but in a clearer way */
    if (mode == access::mode::write)
      ok = p.reserve_write(s, rid, blocking);
    else
      ok = p.reserve_read(s, rid, blocking);
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::blocking, trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::mode, trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::ok, trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::p, trisycl::access::read, trisycl::detail::sycl_2_2::pipe< T >::reserve_read(), trisycl::detail::sycl_2_2::pipe< T >::reserve_write(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::rid, and trisycl::access::write.
pipe_reservation() [2/4]
template<typename PipeAccessor > trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation (const pipe_reservation< PipeAccessor > &) delete
No copy constructor with some spurious commit in the destructor of the original object.
pipe_reservation() [3/4]
template<typename PipeAccessor > trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation (pipe_reservation< PipeAccessor > && orig) inline
Only a move constructor is required to move it into the shared_ptr.
Definition at line 106 of file pipe_reservation.hpp.
                                            :
    ok {orig.ok },
    rid {orig.rid },
    p { orig.p } {
      /* Even when an object is moved, the destructor of the old
         object is eventually called, so leave the old object in a
         destructable state but without any commit capability */
      orig.ok = false;
    }
pipe_reservation() [4/4]
template<typename PipeAccessor > trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation () default
Keep the default constructors too.
Otherwise there is no move semantics and the copy is made by creating a new reservation and destructing the old one with a spurious commit in the meantime...
~pipe_reservation()
template<typename PipeAccessor > trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::~pipe_reservation () inline
An implicit commit is made in the destructor.
Definition at line 190 of file pipe_reservation.hpp.
                      {
    commit();
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit().
Member Function Documentation
assume_validity()
template<typename PipeAccessor > void trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::assume_validity () inline
Test that the reservation is in a usable state.
Todo:
Throw exception instead
Definition at line 74 of file pipe_reservation.hpp.
{
    assert(ok);
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::ok.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::begin(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::end(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::operator[](), and trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::size().
begin()
template<typename PipeAccessor > iterator trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::begin () inline
Start of the reservation area.
Definition at line 139 of file pipe_reservation.hpp.
                   {
    assume_validity();
    return rid->start;
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::assume_validity(), and trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::rid.
commit()
template<typename PipeAccessor > void trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit () inline
Commit the reservation station.
Todo:
Add to the specification that for simplicity a reservation can be commited several times but only the first one is taken into account
Definition at line 175 of file pipe_reservation.hpp.
                {
    if (ok) {
      // If the reservation is in a committable state, commit
      TRISYCL_DUMP_T("Commit");
      rid->ready = true;
      if (mode == access::mode::write)
        p.move_write_reservation_forward();
      else
        p.move_read_reservation_forward();
      ok = false;
    }
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::mode, trisycl::detail::sycl_2_2::pipe< T >::move_read_reservation_forward(), trisycl::detail::sycl_2_2::pipe< T >::move_write_reservation_forward(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::ok, trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::p, trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::rid, TRISYCL_DUMP_T, and trisycl::access::write.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::~pipe_reservation().
end()
template<typename PipeAccessor > iterator trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::end () inline
Past the end of the reservation area.
Definition at line 146 of file pipe_reservation.hpp.
                 {
    assume_validity();
    return rid->start + rid->size;
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::assume_validity(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::rid, and trisycl::detail::sycl_2_2::pipe< T >::size().
operator bool()
template<typename PipeAccessor > trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::operator bool () inline
Test if the reservation succeeded and thus if the reservation can be committed.
Note that it is up to the user to ensure that all the reservation elements have been initialized correctly in the case of a write for example
Definition at line 133 of file pipe_reservation.hpp.
                  {
    return ok;
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::ok.
operator[]()
template<typename PipeAccessor > reference trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::operator[] (std::size_t index) inline
Access to an element of the reservation.
Definition at line 160 of file pipe_reservation.hpp.
{
    assume_validity();
    TRISYCL_DUMP_T("[] index = " << index
                   << " Reservation write address = " << &(rid->start[index]));
    return rid->start[index];
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::assume_validity(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::rid, and TRISYCL_DUMP_T.
size()
template<typename PipeAccessor > std::size_t trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::size () inline
Get the number of elements in the reservation station.
Definition at line 153 of file pipe_reservation.hpp.
                   {
    assume_validity();
    return rid->size;
  }
References trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::assume_validity(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::rid, and trisycl::detail::sycl_2_2::pipe< T >::size().
Member Data Documentation
blocking
template<typename PipeAccessor > constexpr bool trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::blocking static constexpr private
Initial value:
=
    (accessor_type::target == trisycl::access::target::blocking_pipe)
Definition at line 39 of file pipe_reservation.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation().
mode
template<typename PipeAccessor > constexpr access::mode trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::mode = accessor_type::mode static constexpr
Definition at line 52 of file pipe_reservation.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit(), and trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation().
ok
template<typename PipeAccessor > bool trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::ok = false
True if the reservation was successful and still uncommitted.
B default a pipe_reservation is not reserved and cannot be committed
Definition at line 58 of file pipe_reservation.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::assume_validity(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::operator bool(), and trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation().
p
template<typename PipeAccessor > detail::sycl_2_2::pipe<value_type>& trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::p
Keep a reference on the pipe to access to the data and methods.
Note that with inlining and CSE it should not use more register when compiler optimization is in use.
Definition at line 67 of file pipe_reservation.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit(), and trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation().
rid
template<typename PipeAccessor > detail::sycl_2_2::pipe<value_type>::rid_iterator trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::rid
Point into the reservation buffer. Only valid if ok is true.
Definition at line 61 of file pipe_reservation.hpp.
Referenced by trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::begin(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::commit(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::end(), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::operator[](), trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation(), and trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::size().
target
template<typename PipeAccessor > constexpr access::target trisycl::detail::sycl_2_2::pipe_reservation< PipeAccessor >::target = accessor_type::target static constexpr
Definition at line 53 of file pipe_reservation.hpp.
trisycl::sycl_2_2::static_pipe
class trisycl::sycl_2_2::static_pipe
template<typename T, std::size_t Capacity>
class trisycl::sycl_2_2::static_pipe< T, Capacity >
A SYCL static-scoped pipe equivalent to an OpenCL program-scoped pipe.
Implement a FIFO-style object that can be used through accessors to send some objects T from the input to the output.
Compared to a normal pipe, a static_pipe takes a constexpr size and is expected to be declared in a compile-unit static context so the compiler can generate everything at compile time.
This is useful to generate a fixed and optimized hardware implementation on FPGA for example, where the interconnection graph can be also inferred at compile time.
It is not directly mapped to the OpenCL program-scoped pipe because in SYCL there is not this concept of separated program. But the SYCL device compiler is expected to generate some OpenCL program(s) with program-scoped pipes when a SYCL static-scoped pipe is used. These details are implementation defined.
Definition at line 52 of file static_pipe.hpp.
Public Types
using value_type = T
The STL-like types.
Public Member Functions
static_pipe ()
Construct a static-scoped pipe able to store up to Capacity T objects.
template<access::mode Mode, access::target Target = access::target::pipe>
accessor< value_type, 1, Mode, Target > get_access (handler &command_group_handler) const
Get an accessor to the pipe with the required mode.
template<access::mode Mode, access::target Target = access::target::pipe>
accessor< value_type, 1, Mode, Target > get_access () const
Get an accessor to the pipe with the required mode, outside of a normal kernel, for example in host code.
std::size_t constexpr capacity () const
Return the maximum number of elements that can fit in the pipe.
Public Member Functions inherited from trisycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::sycl_2_2::pipe< T > >
shared_ptr_implementation (std::shared_ptr< detail::sycl_2_2::pipe< T > > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (detail::sycl_2_2::pipe< T > *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Private Types
using implementation_t = typename static_pipe::shared_ptr_implementation
Private Attributes
friend implementation_t
Additional Inherited Members
Public Attributes inherited from trisycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::sycl_2_2::pipe< T > >
std::shared_ptr< detail::sycl_2_2::pipe< T > > implementation
The implementation forward everything to this... implementation.
Static Private Member Functions inherited from trisycl::detail::debug< static_pipe< T, Capacity > >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Member Typedef Documentation
implementation_t
template<typename T , std::size_t Capacity> using trisycl::sycl_2_2::static_pipe< T, Capacity >::implementation_t = typename static_pipe::shared_ptr_implementation private
Definition at line 60 of file static_pipe.hpp.
value_type
template<typename T , std::size_t Capacity> using trisycl::sycl_2_2::static_pipe< T, Capacity >::value_type = T
The STL-like types.
Definition at line 71 of file static_pipe.hpp.
Constructor & Destructor Documentation
static_pipe()
template<typename T , std::size_t Capacity> trisycl::sycl_2_2::static_pipe< T, Capacity >::static_pipe () inline
Construct a static-scoped pipe able to store up to Capacity T objects.
Definition at line 75 of file static_pipe.hpp.
    : implementation_t { new detail::sycl_2_2::pipe<T> { Capacity } } { }
Member Function Documentation
capacity()
template<typename T , std::size_t Capacity> std::size_t constexpr trisycl::sycl_2_2::static_pipe< T, Capacity >::capacity () const inline constexpr
Return the maximum number of elements that can fit in the pipe.
This is a constexpr since the capacity is in the type.
Definition at line 123 of file static_pipe.hpp.
{
    return Capacity;
    }
get_access() [1/2]
template<typename T , std::size_t Capacity> template<access::mode Mode, access::target Target = access::target::pipe> accessor< value_type, 1, Mode, Target > trisycl::sycl_2_2::static_pipe< T, Capacity >::get_access () const inline
Get an accessor to the pipe with the required mode, outside of a normal kernel, for example in host code.
Parameters
Mode is the requested access mode
Target is the type of pipe access required
Definition at line 110 of file static_pipe.hpp.
                     {
    static_assert(Target == access::target::pipe
                  || Target == access::target::blocking_pipe,
                  "get_access(handler) with pipes can only deal with "
                  "access::pipe or access::blocking_pipe");
    return { implementation };
  }
References trisycl::access::blocking_pipe, and trisycl::access::pipe.
get_access() [2/2]
template<typename T , std::size_t Capacity> template<access::mode Mode, access::target Target = access::target::pipe> accessor< value_type, 1, Mode, Target > trisycl::sycl_2_2::static_pipe< T, Capacity >::get_access (handler & command_group_handler) const inline
Get an accessor to the pipe with the required mode.
Parameters
Mode is the requested access mode
Target is the type of pipe access required
[in] command_group_handler is the command group handler in which the kernel is to be executed
Definition at line 91 of file static_pipe.hpp.
{
    static_assert(Target == access::target::pipe
                  || Target == access::target::blocking_pipe,
                  "get_access(handler) with pipes can only deal with "
                  "access::pipe or access::blocking_pipe");
    return { implementation, command_group_handler };
  }
References trisycl::access::blocking_pipe, and trisycl::access::pipe.
Member Data Documentation
implementation_t
template<typename T , std::size_t Capacity> friend trisycl::sycl_2_2::static_pipe< T, Capacity >::implementation_t private
Definition at line 66 of file static_pipe.hpp.
Function Documentation
get_pipe_detail()
template<typename Accessor > static auto & trisycl::get_pipe_detail (Accessor & a) inline static
#include <include/triSYCL/accessor.hpp>
Top-level function to break circular dependencies on the the types to get the pipe implementation.
Definition at line 519 of file accessor.hpp.
{
  return a.get_pipe_detail();
}
References a.
Referenced by trisycl::accessor< DataType, 1, AccessMode, access::target::pipe >::get_pipe_detail(), trisycl::accessor< DataType, 1, AccessMode, access::target::blocking_pipe >::get_pipe_detail(), and trisycl::sycl_2_2::pipe_reservation< PipeAccessor >::pipe_reservation().