triSYCL implementation of SYCL: trisycl::detail Namespace Reference
trisycl::detail Namespace Reference
Manage default configuration and types | Opencl_spir_helpers | Platforms, contexts, accessors and queues | Expressing parallelism through kernels
Some global triSYCL configuration.
Namespaces
namespace spir
namespace sycl_2_2
Classes
class accessor
The buffer accessor abstracts the way buffer data are accessed inside a kernel in a multidimensional variable length array way.
class accessor< T, Dimensions, Mode, access::target::local >
The local accessor specialization abstracts the way local memory is allocated to a kernel to be shared between work-items of the same work-group.
class accessor_base
The buffer accessor base is here mainly to be accessed from the task without dependency on the buffer data types.
struct address_space_array
Implementation of an array variable with an OpenCL address space.
struct address_space_base
Implementation of the base infrastructure to wrap something in an OpenCL address space.
struct address_space_fundamental
Implementation of a fundamental type with an OpenCL address space.
struct address_space_object
Implementation of an object type with an OpenCL address space.
struct address_space_ptr
Implementation for an OpenCL address space pointer.
struct address_space_variable
Implementation of a variable with an OpenCL address space.
class alignment
class alignment<::trisycl::vec< DataType, NumElements > >
struct bool_pack
class buffer
A SYCL buffer is a multidimensional variable length array (à la C99 VLA or even Fortran before) that is used to store data to work on.
struct buffer_base
Factorize some template independent buffer aspects in a base class.
class buffer_waiter
A helper class to wait for the final buffer destruction if the conditions for blocking are met.
class cache
A simple thread safe cache mechanism to cache std::shared_ptr of values indexed by keys.
struct container_element_aspect
A mix-in to add some container element aspects.
class context
struct debug
Class used to trace the construction, copy-construction, move-construction and destruction of classes that inherit from it.
class device
An abstract class representing various models of SYCL devices.
struct display_vector
Class used to display a vector-like type of classes that inherit from it.
struct event
struct expand_to_vector
Allows optional expansion of a 1-element tuple to a V::dimension tuple to replicate scalar values in vector initialization.
struct expand_to_vector< V, Tuple, true >
Specialization in the case we ask for expansion.
class fiber_pool
class host_context
SYCL host context.
class host_device
SYCL host device.
class host_event
class host_platform
SYCL host platform.
class host_queue
Some implementation details about the SYCL queue.
struct is_range
A type trait to check if a type it a sycl::range or not.
struct is_range< range< Dimensions > >
Return true if template instantiating match a sycl::range.
class kernel
Abstract SYCL kernel.
struct ocl_type
Generate a type with some real OpenCL 2 attribute if we are on an OpenCL device.
struct ocl_type< T, access::address_space::constant_space >
Add an attribute for __constant address space.
struct ocl_type< T, access::address_space::global_space >
Add an attribute for __global address space.
struct ocl_type< T, access::address_space::local_space >
Add an attribute for __local address space.
struct ocl_type< T, access::address_space::private_space >
Add an attribute for __private address space.
class opencl_context
SYCL OpenCL context.
class opencl_device
SYCL OpenCL device.
class opencl_event
class opencl_kernel
An abstraction of the OpenCL kernel.
class opencl_platform
SYCL OpenCL platform.
class opencl_queue
Some implementation details about the SYCL queue.
struct overloaded
Helper type for the visitor to do pattern matching on invocables https://en.cppreference.com/w/cpp/utility/variant/visit.
struct parallel_for_iterate
A recursive multi-dimensional iterator that ends up calling f.
struct parallel_for_iterate< 0, Range, ParallelForFunctor, Id >
Stop the recursion when level reaches 0 by simply calling the kernel functor with the constructed id.
class platform
An abstract class representing various models of SYCL platforms.
class pooled_shared_work
class pooled_work_stealing
class program
class property
struct queue
Some implementation details about the SYCL queue.
struct shared_ptr_implementation
Provide an implementation as shared_ptr with total ordering and hashing to be used with algorithms and in (un)ordered containers.
struct singleton
Provide a singleton factory.
struct small_array
Define a multi-dimensional index, used for example to locate a work item or a buffer element.
struct small_array_sycl
A small array to implement SYCL objects like id, range, item... with 1, 2 or 3 elements (or even more if detail::allow_any_dimension is true), with the implicit constructors.
struct small_array_tag
Tag to define simply inheritance from small_array.
struct task
The abstraction to represent SYCL tasks executing inside command_group.
class vec
forward declaration to use in the detail class
Concepts
concept is_small_array
Concept describing a class inheriting from small_array.
Typedefs
template<typename T , access::address_space AS>
using addr_space = typename std::conditional< std::is_pointer< T >::value, address_space_ptr< T, AS >, typename std::conditional< std::is_class< T >::value, address_space_object< T, AS >, typename std::conditional< std::is_array< T >::value, address_space_array< T, AS >, address_space_fundamental< T, AS > >::type >::type >::type
Dispatch the address space implementation according to the requested type.
template<bool... v>
using all_true = std::is_same< bool_pack< true, v... >, bool_pack< v..., true > >
template<typename DataType , int numElements>
using __swizzled_base_vec__ = vec< DataType, numElements >
Functions
template<typename BufferDetail >
static std::shared_ptr< detail::task > buffer_add_to_task (BufferDetail buf, handler *command_group_handler, bool is_write_mode)
Proxy function to avoid some circular type recursion.
static std::shared_ptr< detail::task > add_buffer_to_task (handler *command_group_handler, std::shared_ptr< detail::buffer_base > b, bool is_write_mode)
template<typename T , int Dimensions = 1, typename Allocator = buffer_allocator<std::remove_const_t<T>>>
auto waiter (detail::buffer< T, Dimensions > *b)
Helper function to create a new buffer_waiter.
template<typename V , typename Tuple , std::size_t... Is>
std::array< typename V::element_type, V::dimension > tuple_to_array_iterate (Tuple t, std::index_sequence< Is... >)
Helper to construct an array from initializer elements provided as a tuple.
template<typename V , typename Tuple >
auto tuple_to_array (Tuple t)
Construct an array from initializer elements provided as a tuple.
template<typename V , typename Tuple >
auto expand (Tuple t)
Create the array data of V from a tuple of initializer.
template<typename KernelName , typename Functor >
auto trace_kernel (Functor f)
Wrap a kernel functor in some tracing messages to have start/stop information when TRISYCL_TRACE_KERNEL macro is defined.
template<typename KernelName , typename Functor >
void instantiate_kernel (Functor f) noexcept
Instantiate the kernel code.
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX set_kernel_task_marker (detail::task &) noexcept
Set the task to be used to launch the kernel.
template<typename KernelName , typename Kernel >
void launch_device_kernel (detail::task &t, Kernel k) noexcept
Gather in a single function what is necessary for the device compiler to outline the kernel or to set up the kernel and serialize the arguments.
template<typename Range , typename Id >
size_t constexpr linear_id (Range range, Id id, Id offset={})
Compute a linearized array access used in the OpenCL 2 world.
auto & assign_from_tuple (auto &dest, auto &&tuple)
Assign arguments from a tuple.
template<class... Ts>
overloaded (Ts...) -> overloaded< Ts... >
void unimplemented (const char *func, const char *file, int line)
Display an "unimplemented" message.
template<int Dimensions = 1, typename ParallelForFunctor >
void parallel_for_workitem_in_group (const group< Dimensions > &g, ParallelForFunctor f)
Implement the loop on the work-items inside a work-group.
static std::shared_ptr< detail::task > add_buffer_to_task (handler *command_group_handler, std::shared_ptr< detail::buffer_base > b, bool is_write_mode)
Register a buffer as used by a task.
template<int Dimensions = 1, typename ParallelForFunctor , typename Id >
void parallel_for (range< Dimensions > r, ParallelForFunctor f, Id)
Implementation of a data parallel computation with parallelism specified at launch time by a range<>.
template<int Dimensions = 1, typename ParallelForFunctor >
void parallel_for (range< Dimensions > r, ParallelForFunctor f, item< Dimensions >)
Implementation of a data parallel computation with parallelism specified at launch time by a range<>.
template<typename F , typename R , typename A >
auto capture_arg_v (R(F::*)(A))
template<int Dimensions = 1, typename ParallelForFunctor >
void parallel_for (range< Dimensions > r, ParallelForFunctor f)
Calls the appropriate ternary parallel_for overload based on the index type of the kernel function object f.
template<int Dimensions = 1, typename ParallelForFunctor >
void parallel_for_global_offset (range< Dimensions > global_size, id< Dimensions > offset, ParallelForFunctor f)
Implementation of parallel_for with a range<> and an offset.
template<int Dimensions = 1, typename ParallelForFunctor >
void parallel_for_workgroup (nd_range< Dimensions > r, ParallelForFunctor f)
Implement the loop on the work-groups.
template<int Dimensions, typename T_Item , typename ParallelForFunctor >
void parallel_for_workitem (const group< Dimensions > &g, ParallelForFunctor f)
Implement the loop on the work-items inside a work-group.
template<int Dimensions = 1, typename ParallelForFunctor >
void parallel_for (nd_range< Dimensions > r, ParallelForFunctor f)
Implement a variation of parallel_for to take into account a nd_range<>
static auto to_tbb_range (const range< 1 > &r)
static auto to_tbb_range (const range< 2 > &r)
static auto to_tbb_range (const range< 3 > &r)
static auto to_sycl_id (const tbb::blocked_range< size_t > &in)
static auto to_sycl_id (const tbb::blocked_range2d< size_t > &in)
static auto to_sycl_id (const tbb::blocked_range3d< size_t > &in)
template<typename Range , typename ParallelForFunctor >
void parallel_for_iterate (Range r, ParallelForFunctor &f)
auto rangeify (auto r)
Make an explicit range<1> when an integral is provided or pass the value unchanged.
Variables
TRISYCL_WEAK_ATTRIB_PREFIX detail::cache< cl_context, detail::opencl_context > opencl_context::cache TRISYCL_WEAK_ATTRIB_SUFFIX
template<typename T >
constexpr auto alignment_v = alignment<T>::value
auto constexpr underlying_value
Get the enum value as an integral value of the underlying integer type.
auto constexpr enum_distance
Get the distance between 2 enum underlying values.
auto constexpr enum_count
Count the number of enums between 2 enum boundaries, including the boundaries.
constexpr bool allow_any_dimension
Map TRISYCL_ALLOW_ANY_DIMENSION to a constexpr variable.
constexpr bool use_native_work_item
Map TRISYCL_USE_OPENCL_ND_RANGE to a constexpr variable.
auto prevent_arguments_from_optimization
Avoid the interprocedural optimization to remove these arguments in the kernel instantiation by relying on some dummy static variables.
template<typename T >
constexpr auto is_range_v = is_range<T>::value
A variable to check if a type is a sycl::range or not.
Detailed Description
Some global triSYCL configuration.
Typedef Documentation
__swizzled_base_vec__
template<typename DataType , int numElements> using trisycl::detail::__swizzled_base_vec__ = typedef vec<DataType, numElements>
Definition at line 37 of file vec.hpp.
all_true
template<bool... v> using trisycl::detail::all_true = typedef std::is_same<bool_pack<true, v...>, bool_pack<v..., true> >
Definition at line 16 of file all_true.hpp.
Function Documentation
add_buffer_to_task()
static std::shared_ptr< detail::task > trisycl::detail::add_buffer_to_task (handler * command_group_handler, std::shared_ptr< detail::buffer_base > b, bool is_write_mode) static
Register a buffer as used by a task.
This is a proxy function to avoid complicated type recursion.
Definition at line 532 of file handler.hpp.
{
  command_group_handler->task->add_buffer(b, is_write_mode);
  return command_group_handler->task;
}
References b, and trisycl::handler::task.
assign_from_tuple()
auto & trisycl::detail::assign_from_tuple (auto & dest, auto && tuple)
Assign arguments from a tuple.
Definition at line 14 of file metaprogramming.hpp.
{
  auto expanded_assign = [&](auto&&... elems) mutable {
    // Assign from each tuple element expanded
    dest = { std::forward<decltype(elems)>(elems)... };
  };
  std::apply(expanded_assign, std::forward<decltype(tuple)>(tuple));
  // So we can use the result of the assignment expression if needed
  return dest;
}
instantiate_kernel()
template<typename KernelName , typename Functor > void trisycl::detail::instantiate_kernel (Functor f) noexcept
Instantiate the kernel code.
To have a clear view of what a kernel is at the LLVM IR level even when a lot of optimizations are done (-O3), call the kernel from this function marked as noinline, otherwise the kernel code is inlined directly where it is used.
Actually some optimizations/code restructuring might duplicate the call to instantiate_kernel but the noduplicate attribute seems incompatible with noinline in Clang/LLVM 3.9.1, because the inlining happen when both attributes are used...
Definition at line 51 of file instantiate_kernel.hpp.
{
  /* The outlining compiler is expected to do some massage here or
     around and to insert some calls to \c serialize_arg and so on */
  f();
}
launch_device_kernel()
template<typename KernelName , typename Kernel > void trisycl::detail::launch_device_kernel (detail::task & t, Kernel k) noexcept
Gather in a single function what is necessary for the device compiler to outline the kernel or to set up the kernel and serialize the arguments.
The noinline attribute is used to force this to appear as a real function the device compiler can massage.
Setup the task to be used to launch the kernel.
This is used by the outlining compiler.
Definition at line 91 of file instantiate_kernel.hpp.
{
  /** Setup the task to be used to launch the kernel.
      This is used by the outlining compiler. */
  detail::set_kernel_task_marker(t);
  /* A simplified version for the device just to be able to extract
     the kernel itself.
     It is not a real outlining but a good approximation to be
     massaged by a compiler later.
     Put the iteration space loops in the kernels for now, which makes
     sense for CPU emulation or FPGA pipelined execution.
  */
  instantiate_kernel<KernelName>(k);
}
References set_kernel_task_marker().
rangeify()
auto trisycl::detail::rangeify (auto r)
Make an explicit range<1> when an integral is provided or pass the value unchanged.
Definition at line 75 of file range.hpp.
{
      if constexpr (std::integral<decltype(r)>)
        return range { r };
      else
        return r;
    };
Referenced by trisycl::handler::parallel_for().
set_kernel_task_marker()
TRISYCL_WEAK_ATTRIB_PREFIX void TRISYCL_WEAK_ATTRIB_SUFFIX trisycl::detail::set_kernel_task_marker (detail::task &) noexcept
Set the task to be used to launch the kernel.
This is actually a dummy function so that the device compiler can just grab the task for passing it to the argument serialization functions from the device runtime.
It is better to use a weak linkage than having this function with extern linkage:
if the device compiler is used the function is kept by the compiler because full link and LTO is not applied before the device compiler passes are applied. So there is no partial evaluation in the compiler according to what is returned by this function;
if the device compiler is not used, the code still links and can be compiled.
Definition at line 77 of file instantiate_kernel.hpp.
{
}
Referenced by launch_device_kernel().
Variable Documentation
alignment_v
template<typename T > constexpr auto trisycl::detail::alignment_v = alignment<T>::value constexpr
Definition at line 42 of file alignment_helper.hpp.
allow_any_dimension
constexpr bool trisycl::detail::allow_any_dimension constexpr
Initial value:
=
    false
Map TRISYCL_ALLOW_ANY_DIMENSION to a constexpr variable.
Definition at line 33 of file global_config.hpp.
enum_count
auto constexpr trisycl::detail::enum_count constexpr
Initial value:
= [] (auto enum_start, auto enum_end) {
  return 1 + enum_distance(enum_start, enum_end);
}
Count the number of enums between 2 enum boundaries, including the boundaries.
Definition at line 37 of file enum.hpp.
enum_distance
auto constexpr trisycl::detail::enum_distance constexpr
Initial value:
= [] (auto enum_start, auto enum_end) {
  static_assert(std::is_same_v<decltype(enum_start), decltype(enum_end)>,
                "enum_start and auto enum_end should have the same type");
  return underlying_value(enum_end) - underlying_value(enum_start);
}
Get the distance between 2 enum underlying values.
Definition at line 28 of file enum.hpp.
is_range_v
template<typename T > constexpr auto trisycl::detail::is_range_v = is_range<T>::value constexpr
A variable to check if a type is a sycl::range or not.
Definition at line 90 of file range.hpp.
prevent_arguments_from_optimization
auto trisycl::detail::prevent_arguments_from_optimization inline
Initial value:
= [] (auto & ...args) {
  [[gnu::used]] static auto keep = std::make_tuple(& args...);
}
Avoid the interprocedural optimization to remove these arguments in the kernel instantiation by relying on some dummy static variables.
Using [[gnu::used]] does not work on arguments but only on static variable, so use this function.
Definition at line 28 of file instantiate_kernel.hpp.
underlying_value
auto constexpr trisycl::detail::underlying_value constexpr
Initial value:
= [] (auto e) {
  using value_t = std::underlying_type_t<decltype(e)>;
  return static_cast<value_t>(e);
}
Get the enum value as an integral value of the underlying integer type.
Definition at line 21 of file enum.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::input(), and trisycl::vendor::xilinx::acap::aie::axi_stream_switch< AXIStreamGeography >::output().
use_native_work_item
constexpr bool trisycl::detail::use_native_work_item constexpr
Initial value:
=
    false
Map TRISYCL_USE_OPENCL_ND_RANGE to a constexpr variable.
Definition at line 48 of file global_config.hpp.
Referenced by trisycl::handler::parallel_for().