triSYCL implementation of SYCL: trisycl Namespace Reference
trisycl Namespace Reference
Manage default configuration and types | Vector types in SYCL
The vector type to be used as SYCL vector.
Namespaces
access
Describe the type of access by kernels.
detail
drt
extension
info
native
property
trisycl
vendor
Classes
class accessor
The accessor abstracts the way buffer or pipe data are accessed inside a kernel in a multidimensional variable length array way.
class accessor< DataType, 1, AccessMode, access::target::blocking_pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
class accessor< DataType, 1, AccessMode, access::target::pipe >
The pipe accessor abstracts the way pipe data are accessed inside a kernel.
class accessor_error
Error regarding the trisycl::accessor objects defined.
struct async_exception
An error stored in an exception_list for asynchronous errors.
class buffer
A SYCL buffer is a multidimensional variable length array (à la C99 VLA or even Fortran before) that is used to store data to work on.
class cl_exception
Returns the OpenCL error code encapsulated in the exception.
class compile_program_error
Error while compiling the SYCL kernel to a SYCL device.
class context
SYCL context.
class device
SYCL device.
class device_error
The SYCL device will trigger this exception on error.
class device_selector
The SYCL heuristics to select a device.
class device_type_selector
A device selector by device_type.
class device_typename_selector
Select a device by template device_type parameter.
struct elem
Series of values to specify named swizzle indexes Used when calling the swizzle member function template.
struct error_handler
User supplied error handler to call a user-provided function when an error happens from a SYCL object that was constructed with this error handler.
class event
SYCL event.
class event_error
Error regarding associated trisycl::event objects.
class exception
Encapsulate a SYCL error information.
struct exception_list
Exception list to store several exceptions.
class feature_not_supported
Exception thrown when an optional feature or extension is used in a kernel but its not available on the device the SYCL kernel is being enqueued on.
struct group
A group index used in a parallel_for_workitem to specify a work_group.
struct h_item
h_item<int dimensions> identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range<int dimensions> passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call if no range is passed to the parallel_for_work_item call.
class half
class handler
Command group handler class.
class id
Define a multi-dimensional index, used for example to locate a work item.
struct image
class invalid_object_error
Error regarding any memory objects being used inside the kernel.
class invalid_parameter_error
Error regarding parameters to the SYCL kernel, it may apply to any captured parameters to the kernel lambda.
struct is_wrapper
class item
A SYCL item stores information on a work-item with some more context such as the definition range and offset.
class kernel
SYCL kernel.
class kernel_error
Error that occurred before or while enqueuing the SYCL kernel.
class link_program_error
Error while linking the SYCL kernel to a SYCL device.
class memory_allocation_error
Error on memory allocation on the SYCL device for a SYCL kernel.
struct nd_item
A SYCL nd_item stores information on a work-item within a work-group, with some more context such as the definition ranges.
struct nd_range
A ND-range, made by a global and local range, to specify work-group and work-item organization.
class nd_range_error
Error regarding the trisycl::nd_range specified for the SYCL kernel.
class non_cl_error
Exception for an OpenCL operation requested in a non OpenCL area.
class pipe
A SYCL pipe.
class pipe_error
A failing pipe error will trigger this exception on error.
struct pipe_reservation
The pipe reservation station allows to reserve an array-like view inside the pipe for ordered race-free access from various work-items for example.
class platform
Abstract the OpenCL platform.
class platform_error
The SYCL platform will trigger this exception on error.
class profiling_error
The SYCL runtime will trigger this error if there is an error when profiling info is enabled.
class program
SYCL program.
class property_list
SYCL property list.
class queue
SYCL queue, similar to the OpenCL queue concept.
class range
A SYCL range defines a multi-dimensional index range that can be used to define launch parallel computation extent or buffer sizes.
class runtime_error
class static_pipe
A SYCL static-scoped pipe equivalent to an OpenCL program-scoped pipe.
class vec
forward decl to use in the detail class
class vec< DataType, 1 >
class vec< DataType, 16 >
class vec< DataType, 2 >
class vec< DataType, 3 >
class vec< DataType, 4 >
class vec< DataType, 8 >
Typedefs
template<typename T >
using constant = detail::addr_space< T, access::address_space::constant_space >
Declare a variable to be in the OpenCL constant address space.
template<typename T >
using constant_ptr = constant< T * >
Declare a variable to be in the OpenCL constant address space.
template<typename T >
using generic = detail::addr_space< T, access::address_space::generic_space >
Declare a variable to be in the OpenCL 2 generic address space.
template<typename T >
using global = detail::addr_space< T, access::address_space::global_space >
Declare a variable to be in the OpenCL global address space.
template<typename T >
using global_ptr = global< T * >
Declare a variable to be in the OpenCL global address space.
template<typename T >
using local = detail::addr_space< T, access::address_space::local_space >
Declare a variable to be in the OpenCL local address space.
template<typename T >
using local_ptr = local< T * >
Declare a variable to be in the OpenCL local address space.
template<typename T >
using priv = detail::addr_space< T, access::address_space::private_space >
Declare a variable to be in the OpenCL private address space.
template<typename T >
using private_ptr = priv< T * >
Declare a variable to be in the OpenCL private address space.
template<typename Pointer , access::address_space AS>
using multi_ptr = detail::address_space_ptr< Pointer, AS >
A pointer that can be statically associated to any address-space.
template<typename T >
using buffer_allocator = std::allocator< T >
The allocator objects give the programmer some control on how the memory is allocated inside SYCL.
template<typename T >
using image_allocator = std::allocator< T >
The allocator used for the image inside SYCL.
template<typename T >
using map_allocator = std::allocator< T >
The allocator used to map the memory at the same place.
template<class T , class Alloc = std::allocator<T>>
using vector_class = std::vector< T, Alloc >
using string_class = std::string
template<class R , class... ArgTypes>
using function_class = std::function< R(ArgTypes...)>
using mutex_class = std::mutex
template<class T , class D = std::default_delete<T>>
using unique_ptr_class = std::unique_ptr< T[], D >
template<class T >
using shared_ptr_class = std::shared_ptr< T >
template<class T >
using weak_ptr_class = std::weak_ptr< T >
template<class T >
using hash_class = std::hash< T >
using exception_ptr_class = std::exception_ptr
using default_selector = device_typename_selector< info::device_type::automatic >
Devices selected by heuristics of the system.
using gpu_selector = device_typename_selector< info::device_type::gpu >
Select devices according to device type info::device::device_type::gpu from all the available OpenCL devices.
using cpu_selector = device_typename_selector< info::device_type::cpu >
Select devices according to device type info::device::device_type::cpu from all the available devices and heuristics.
using host_selector = device_typename_selector< info::device_type::host >
Selects the SYCL host CPU device that does not require an OpenCL runtime.
using exception_ptr = std::exception_ptr
A shared pointer to an exception as in C++ specification.
using async_handler = function_class< void, exception_list >
template<typename DataType , int numElements>
using __swizzled_vec__ = vec< DataType, numElements >
Enumerations
enum program_state { program_state::none, program_state::compiled, program_state::linked }
enum rounding_mode {
rounding_mode::automatic, rounding_mode::rte, rounding_mode::rtz, rounding_mode::rtp,
rounding_mode::rtn
}
Rounding mode for vector conversions.
Functions
template<typename Accessor >
static auto & get_pipe_detail (Accessor &a)
Top-level function to break circular dependencies on the the types to get the pipe implementation.
template<typename T , access::address_space AS>
multi_ptr< T, AS > make_ptr (multi_ptr< T, AS > pointer)
Construct a trisycl::multi_ptr<> with the right type.
template<typename T , access::address_space AS>
multi_ptr< T, AS > make_ptr (T *pointer)
Construct a trisycl::multi_ptr<> with the right type.
template<>
auto context::get_info< info::context::reference_count > () const
template<>
auto context::get_info< info::context::platform > () const
template<>
auto context::get_info< info::context::devices > () const
template<>
auto event::get_info< info::event::command_execution_status > () const
template<>
auto event::get_info< info::event::reference_count > () const
template<>
auto event::get_profiling_info< info::event_profiling::command_submit > () const
template<>
auto event::get_profiling_info< info::event_profiling::command_start > () const
template<>
auto event::get_profiling_info< info::event_profiling::command_end > () const
auto make_id (id< 1 > i)
Implement a make_id to construct an id<> of the right dimension with implicit conversion from an initializer list for example.
auto make_id (id< 2 > i)
auto make_id (id< 3 > i)
template<typename... BasicType>
auto make_id (BasicType... Args)
Construct an id<> from a function call with arguments, like make_id(1, 2, 3)
TRISYCL_MATH_WRAP (abs) TRISYCL_MATH_WRAP(atan) TRISYCL_MATH_WRAP3ss(clamp) TRISYCL_MATH_WRAP2s(fmax) TRISYCL_MATH_WRAP2s(fmin) TRISYCL_MATH_WRAP2s(frexp) template< typename T > T max(T x
template<typename T >
T min (T x, T y, T z)
TRISYCL_MATH_WRAP2s (modf) TRISYCL_MATH_WRAP3s(remquo) TRISYCL_MATH_WRAP2(rotate) template< typename T
int size auto cross (vec< T, size > x, vec< T, size > y)
template<typename T , int size>
auto length (vec< T, size > x)
template<typename T , int size>
auto dot (vec< T, size > x, vec< T, size > y)
template<typename T , int size>
auto clamp (vec< T, size > x, T minval, T maxval)
template<typename T , int size>
auto normalize (vec< T, size > x)
template<typename T , int size>
auto floor (vec< T, size > x)
template<typename T , int size>
auto fmin (vec< T, size > x, vec< T, size > y)
template<typename T , int size>
auto fmax (vec< T, size > x, vec< T, size > y)
template<typename T , int size>
auto max (vec< T, size > x, vec< T, size > y)
template<typename T , int size>
auto min (vec< T, size > x, vec< T, size > y)
template<>
auto platform::get_info< info::platform::extensions > () const
template<>
auto queue::get_info< info::queue::device > () const
template<>
auto queue::get_info< info::queue::context > () const
template<>
auto queue::get_info< info::queue::reference_count > () const
auto make_range (range< 1 > r)
Implement a make_range to construct a range<> of the right dimension with implicit conversion from an initializer list for example.
auto make_range (range< 2 > r)
auto make_range (range< 3 > r)
template<typename... BasicType>
auto make_range (BasicType... Args)
Construct a range<> from a function call with arguments, like make_range(1, 2, 3)
Variables
T y
T T z
Detailed Description
The vector type to be used as SYCL vector.
Small OpenCL vector class.
The exception pointer type to be used as SYCL exception pointer.
The hash type to be used as SYCL hash.
The weak pointer type to be used as SYCL weak pointer.
The shared pointer type to be used as SYCL shared pointer.
The unique pointer type to be used as SYCL unique pointer.
The mutex type to be used as SYCL mutex.
The functional type to be used as SYCL function.
The string type to be used as SYCL string.
Typedef Documentation
exception_ptr_class
using trisycl::exception_ptr_class = typedef std::exception_ptr
Definition at line 126 of file default_classes.hpp.
function_class
template<class R , class... ArgTypes> using trisycl::function_class = typedef std::function<R(ArgTypes...)>
Definition at line 50 of file default_classes.hpp.
hash_class
template<class T > using trisycl::hash_class = typedef std::hash<T>
Definition at line 114 of file default_classes.hpp.
mutex_class
using trisycl::mutex_class = typedef std::mutex
Definition at line 62 of file default_classes.hpp.
shared_ptr_class
template<class T > using trisycl::shared_ptr_class = typedef std::shared_ptr<T>
Definition at line 88 of file default_classes.hpp.
string_class
using trisycl::string_class = typedef std::string
Definition at line 37 of file default_classes.hpp.
unique_ptr_class
template<class T , class D = std::default_delete<T>> using trisycl::unique_ptr_class = typedef std::unique_ptr<T[], D>
Definition at line 75 of file default_classes.hpp.
vector_class
template<class T , class Alloc = std::allocator<T>> using trisycl::vector_class = typedef std::vector<T, Alloc>
Definition at line 25 of file default_classes.hpp.
weak_ptr_class
template<class T > using trisycl::weak_ptr_class = typedef std::weak_ptr<T>
Definition at line 101 of file default_classes.hpp.
Enumeration Type Documentation
program_state
enum trisycl::program_state strong
Enumerator
none
compiled
linked
Definition at line 24 of file program.hpp.
{
   none,
   compiled,
   linked
 };
Function Documentation
clamp()
template<typename T , int size> auto trisycl::clamp (vec< T, size > x, T minval, T maxval)
Definition at line 210 of file math.hpp.
{
   return x.map([=](auto e) {
     return clamp(e, minval, maxval);
   });
 }
cross()
int size auto trisycl::cross (vec< T, size > x, vec< T, size > y)
Definition at line 179 of file math.hpp.
{
   static_assert((size == 4 || size == 3),
                 "vec type should be 3 or 4 dimensions");
   if constexpr (size > 3) {
     return vec<T, size> {
             (x[1] * y[2]) - (x[2] * y[1]),
             (x[2] * y[0]) - (x[0] * y[2]),
             (x[0] * y[1]) - (x[1] * y[0]),
             0.0};
   } else {
     return vec<T, size> {
             (x[1] * y[2]) - (x[2] * y[1]),
             (x[2] * y[0]) - (x[0] * y[2]),
             (x[0] * y[1]) - (x[1] * y[0])};
   }
 }
dot()
template<typename T , int size> auto trisycl::dot (vec< T, size > x, vec< T, size > y)
Definition at line 205 of file math.hpp.
{
   return std::inner_product(x.begin(), x.end(), y.begin(), T{0});
 }
event::get_info< info::event::command_execution_status >()
template<> auto trisycl::event::get_info< info::event::command_execution_status > () const inline
Definition at line 100 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
{
   return implementation->get_command_execution_status();
 }
event::get_info< info::event::reference_count >()
template<> auto trisycl::event::get_info< info::event::reference_count > () const inline
Definition at line 105 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
{
   return implementation->get_reference_count();
 }
event::get_profiling_info< info::event_profiling::command_end >()
template<> auto trisycl::event::get_profiling_info< info::event_profiling::command_end > () const inline
Definition at line 120 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
{
   return implementation->get_profiling_info(info::event_profiling::command_end);
 }
event::get_profiling_info< info::event_profiling::command_start >()
template<> auto trisycl::event::get_profiling_info< info::event_profiling::command_start > () const inline
Definition at line 115 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
{
   return implementation->get_profiling_info(info::event_profiling::command_start);
 }
event::get_profiling_info< info::event_profiling::command_submit >()
template<> auto trisycl::event::get_profiling_info< info::event_profiling::command_submit > () const inline
Definition at line 110 of file event.hpp.
References trisycl::detail::shared_ptr_implementation< event, detail::event >::implementation.
{
   return implementation->get_profiling_info(info::event_profiling::command_submit);
 }
floor()
template<typename T , int size> auto trisycl::floor (vec< T, size > x)
Definition at line 225 of file math.hpp.
{
   return x.map(floor<T>);
 }
fmax()
template<typename T , int size> auto trisycl::fmax (vec< T, size > x, vec< T, size > y)
Definition at line 248 of file math.hpp.
Referenced by max().
{
   return x.zip(y, fmax<T,T>);
 }
fmin()
template<typename T , int size> auto trisycl::fmin (vec< T, size > x, vec< T, size > y)
Definition at line 238 of file math.hpp.
Referenced by min().
{
   return x.zip(y, fmin<T,T>);
 }
length()
template<typename T , int size> auto trisycl::length (vec< T, size > x)
Definition at line 198 of file math.hpp.
References x.
Referenced by normalize().
{
   auto temp = x * x;
   return sqrt(std::accumulate(temp.begin(), temp.end(), T{0}));
 }
max()
template<typename T , int size> auto trisycl::max (vec< T, size > x, vec< T, size > y)
Definition at line 262 of file math.hpp.
References fmax().
Referenced by trisycl::device::device().
{
   return fmax(x,y);
 }
min() [1/2]
template<typename T > T trisycl::min (T x, T y, T z)
Definition at line 125 of file math.hpp.
References min(), TRISYCL_MATH_WRAP(), TRISYCL_MATH_WRAP2, TRISYCL_MATH_WRAP2s(), and TRISYCL_MATH_WRAP3s.
                      {
   return std::min(x, std::min(y, z));
 }
min() [2/2]
template<typename T , int size> auto trisycl::min (vec< T, size > x, vec< T, size > y)
Definition at line 268 of file math.hpp.
References fmin().
Referenced by min().
{
   return fmin(x,y);
 }
normalize()
template<typename T , int size> auto trisycl::normalize (vec< T, size > x)
Definition at line 218 of file math.hpp.
References length().
{
   return x / length(x);
 }
TRISYCL_MATH_WRAP()
trisycl::TRISYCL_MATH_WRAP (abs)
Referenced by min().
TRISYCL_MATH_WRAP2s()
trisycl::TRISYCL_MATH_WRAP2s (modf)
Referenced by min().
Variable Documentation
y
T trisycl::y
Definition at line 112 of file math.hpp.
Referenced by trisycl::detail::vec< DataType, 8 >::apply_binary_functor(), trisycl::detail::small_array_123< BasicType, FinalType, 2 >::small_array_123(), and trisycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123().
z
T T trisycl::z
Initial value:
{
  return std::max(x, std::max(y, z))
Definition at line 112 of file math.hpp.
Referenced by trisycl::detail::small_array_123< BasicType, FinalType, 3 >::small_array_123().