triSYCL implementation of SYCL: trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH > Struct Template Reference
trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH > Struct Template Reference
The command group redefining some member functions to be able to pass the scope and so on to the kernel.
#include <queue.hpp>
Public Member Functions
command_group (::trisycl::handler &cgh, Device &d)
operator::trisycl::handler & ()
Add a conversion to trisycl::handler& so the usual methods such as get_access can still work.
template<typename KernelName , typename Kernel >
void single_task (Kernel k)
Sequential kernel invocation.
template<typename KernelName , int Rank, typename Kernel >
void parallel_for (::trisycl::range< Rank > num_work_items, Kernel k)
Parallel kernel invocation method on a range iteration space.
auto & device_scope ()
Provide access to the device scope from inside the kernel.
template<typename PS = std::remove_reference_t<decltype(d.get_platform())>, typename E = std::enable_if_t<PS::has_some_storage_p>>
auto & platform_scope ()
Provide access to the platform scope from inside the kernel, if any.
command_group (::trisycl::handler &cgh, Device &d)
operator::trisycl::handler & ()
Add a conversion to trisycl::handler& so the usual methods such as get_access can still work.
template<typename KernelName , typename Kernel >
void single_task (Kernel k)
Sequential kernel invocation.
template<typename KernelName , int Rank, typename Kernel >
void parallel_for (::trisycl::range< Rank > num_work_items, Kernel k)
Parallel kernel invocation method on a range iteration space.
auto & device_scope ()
Provide access to the device scope from inside the kernel.
template<typename PS = std::remove_reference_t<decltype(d.get_platform())>, typename E = std::enable_if_t<PS::has_some_storage_p>>
auto & platform_scope ()
Provide access to the platform scope from inside the kernel, if any.
Public Attributes
::trisycl::handler & cgh
The plain SYCL command-group handler.
Device & d
Detailed Description
template<typename Device, typename QueueStorage = empty_queue_scope>
template<typename CGH>
struct trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >
The command group redefining some member functions to be able to pass the scope and so on to the kernel.
Definition at line 150 of file queue.hpp.
Constructor & Destructor Documentation
command_group() [1/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::command_group (::trisycl::handler & cgh, Device & d) inline
Definition at line 156 of file queue.hpp.
      : cgh { cgh }, d { d } {}
command_group() [2/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::command_group (::trisycl::handler & cgh, Device & d) inline
Definition at line 156 of file queue.hpp.
      : cgh { cgh }, d { d } {}
Member Function Documentation
device_scope() [1/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > auto & trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::device_scope () inline
Provide access to the device scope from inside the kernel.
Definition at line 188 of file queue.hpp.
{ return d.get_storage(); }
device_scope() [2/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > auto & trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::device_scope () inline
Provide access to the device scope from inside the kernel.
Definition at line 188 of file queue.hpp.
{ return d.get_storage(); }
operator::trisycl::handler &() [1/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::operator::trisycl::handler & () inline
Add a conversion to trisycl::handler& so the usual methods such as get_access can still work.
Definition at line 162 of file queue.hpp.
{
      return cgh;
    }
operator::trisycl::handler &() [2/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::operator::trisycl::handler & () inline
Add a conversion to trisycl::handler& so the usual methods such as get_access can still work.
Definition at line 162 of file queue.hpp.
{
      return cgh;
    }
parallel_for() [1/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > template<typename KernelName , int Rank, typename Kernel > void trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::parallel_for (::trisycl::range< Rank > num_work_items, Kernel k) inline
Parallel kernel invocation method on a range iteration space.
Definition at line 178 of file queue.hpp.
{
      cgh.parallel_for<KernelName>(num_work_items,
                                   [=, *this] (::trisycl::id<Rank> i) mutable {
                                     k(i, *this);
                                   });
    }
References i, and trisycl::handler::parallel_for().
parallel_for() [2/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > template<typename KernelName , int Rank, typename Kernel > void trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::parallel_for (::trisycl::range< Rank > num_work_items, Kernel k) inline
Parallel kernel invocation method on a range iteration space.
Definition at line 178 of file queue.hpp.
{
      cgh.parallel_for<KernelName>(num_work_items,
                                   [=, *this] (::trisycl::id<Rank> i) mutable {
                                     k(i, *this);
                                   });
    }
References i, and trisycl::handler::parallel_for().
platform_scope() [1/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > template<typename PS = std::remove_reference_t<decltype(d.get_platform())>, typename E = std::enable_if_t<PS::has_some_storage_p>> auto & trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::platform_scope () inline
Provide access to the platform scope from inside the kernel, if any.
Definition at line 194 of file queue.hpp.
{ return d.get_platform().get_storage(); }
platform_scope() [2/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > template<typename PS = std::remove_reference_t<decltype(d.get_platform())>, typename E = std::enable_if_t<PS::has_some_storage_p>> auto & trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::platform_scope () inline
Provide access to the platform scope from inside the kernel, if any.
Definition at line 194 of file queue.hpp.
{ return d.get_platform().get_storage(); }
single_task() [1/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > template<typename KernelName , typename Kernel > void trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::single_task (Kernel k) inline
Sequential kernel invocation.
Definition at line 169 of file queue.hpp.
{
      cgh.single_task<KernelName>([=, *this] () mutable {
          k(*this);
        });
    }
References trisycl::handler::single_task().
single_task() [2/2]
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > template<typename KernelName , typename Kernel > void trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::single_task (Kernel k) inline
Sequential kernel invocation.
Definition at line 169 of file queue.hpp.
{
      cgh.single_task<KernelName>([=, *this] () mutable {
          k(*this);
        });
    }
References trisycl::handler::single_task().
Member Data Documentation
cgh
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > trisycl::handler & trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::cgh
The plain SYCL command-group handler.
Definition at line 153 of file queue.hpp.
d
template<typename Device , typename QueueStorage = empty_queue_scope> template<typename CGH > Device & trisycl::vendor::trisycl::scope::queue< Device, QueueStorage >::command_group< CGH >::d
Definition at line 154 of file queue.hpp.
The documentation for this struct was generated from the following files:
include/sycl/vendor/triSYCL/scope/queue.hpp
include/triSYCL/vendor/triSYCL/scope/queue.hpp