triSYCL implementation of SYCL: trisycl::detail::shared_ptr_implementation< Parent, Implementation > Struct Template Reference
trisycl::detail::shared_ptr_implementation< Parent, Implementation > Struct Template Reference
Provide an implementation as shared_ptr with total ordering and hashing to be used with algorithms and in (un)ordered containers.
#include <shared_ptr_implementation.hpp>
Public Member Functions
shared_ptr_implementation (std::shared_ptr< Implementation > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (Implementation *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Public Attributes
std::shared_ptr< Implementation > implementation
The implementation forward everything to this... implementation.
Friends
bool operator== (const Parent &lhs, const Parent &rhs)
Equality operator.
bool operator< (const Parent &lhs, const Parent &rhs)
Inferior operator.
Detailed Description
template<typename Parent, typename Implementation>
struct trisycl::detail::shared_ptr_implementation< Parent, Implementation >
Provide an implementation as shared_ptr with total ordering and hashing to be used with algorithms and in (un)ordered containers.
To be used, a Parent class wanting an Implementation needs to inherit from.
The implementation ends up in a member really named "implementation".
public detail::shared_ptr_implementation<Parent, Implementation>
and also inject in std namespace a specialization for
hash<Parent>
Definition at line 38 of file shared_ptr_implementation.hpp.
Constructor & Destructor Documentation
shared_ptr_implementation() [1/3]
template<typename Parent , typename Implementation > trisycl::detail::shared_ptr_implementation< Parent, Implementation >::shared_ptr_implementation (std::shared_ptr< Implementation > i) inline
The implementation directly as a shared pointer.
Definition at line 44 of file shared_ptr_implementation.hpp.
    : implementation { i } {}
shared_ptr_implementation() [2/3]
template<typename Parent , typename Implementation > trisycl::detail::shared_ptr_implementation< Parent, Implementation >::shared_ptr_implementation (Implementation * i) inline
The implementation takes the ownership from a raw pointer.
Definition at line 49 of file shared_ptr_implementation.hpp.
: implementation { i } {}
shared_ptr_implementation() [3/3]
template<typename Parent , typename Implementation > trisycl::detail::shared_ptr_implementation< Parent, Implementation >::shared_ptr_implementation () default
Keep all other constructors to have usual shared_ptr behaviour.
Member Function Documentation
hash()
template<typename Parent , typename Implementation > auto trisycl::detail::shared_ptr_implementation< Parent, Implementation >::hash () const inline
Forward the hashing for unordered containers to the implementation.
Definition at line 87 of file shared_ptr_implementation.hpp.
                    {
    return std::hash<decltype(implementation)>{}(implementation);
  }
References trisycl::detail::shared_ptr_implementation< Parent, Implementation >::implementation.
Referenced by std::hash< trisycl::device >::operator()(), std::hash< trisycl::event >::operator()(), std::hash< trisycl::kernel >::operator()(), and std::hash< trisycl::queue >::operator()().
Friends And Related Function Documentation
operator<
template<typename Parent , typename Implementation > bool operator< (const Parent & lhs, const Parent & rhs) friend
Inferior operator.
This is generalized by boost::less_than_comparable from boost::totally_ordered to implement the equality comparable concept
Use recipe for hidden friends from P1601R0: "Recommendations for Specifying “Hidden Friends""
Todo:
Add this to the spec
Definition at line 81 of file shared_ptr_implementation.hpp.
{
    return lhs.implementation < rhs.implementation;
  }
operator==
template<typename Parent , typename Implementation > bool operator== (const Parent & lhs, const Parent & rhs) friend
Equality operator.
This is generalized by boost::equality_comparable from boost::totally_ordered to implement the equality comparable concept
Use recipe for hidden friends from P1601R0: "Recommendations for Specifying “Hidden Friends""
Definition at line 65 of file shared_ptr_implementation.hpp.
{
    return lhs.implementation == rhs.implementation;
  }
Member Data Documentation
implementation
template<typename Parent , typename Implementation > std::shared_ptr<Implementation> trisycl::detail::shared_ptr_implementation< Parent, Implementation >::implementation
The implementation forward everything to this... implementation.
Definition at line 41 of file shared_ptr_implementation.hpp.
Referenced by trisycl::detail::shared_ptr_implementation< Parent, Implementation >::hash(), trisycl::handler::parallel_for(), and trisycl::handler::single_task().
The documentation for this struct was generated from the following file:
include/triSYCL/detail/shared_ptr_implementation.hpp