triSYCL implementation of SYCL: trisycl::vendor::xilinx::graphics::palette Struct Reference
trisycl::vendor::xilinx::graphics::palette Struct Reference
Color palette to project a linear data space to an RGB color space.
#include <graphics.hpp>
Public Types
enum kind { gray , rainbow , gray , rainbow }
enum kind { gray , rainbow , gray , rainbow }
Public Member Functions
palette (kind k=gray, int phase=0, int frequency_log2=0, int clip=-1)
Create a palette.
void gray_palette ()
void rainbow_palette ()
void update ()
void set (kind new_k, int new_phase, int new_frequency_log2, int new_clip)
Set palette parameters and update.
rgb palettize (double data, double min_value, double max_value)
Transform a value into an RGB color according to the palette.
void decrease_clip ()
void increase_clip ()
void decrease_frequency ()
void increase_frequency ()
void decrease_phase ()
void increase_phase ()
bool handle_key_press_event (GdkEventKey &event)
Handle with any key pressed.
palette (kind k=gray, int phase=0, int frequency_log2=0, int clip=-1)
Create a palette.
void gray_palette ()
void rainbow_palette ()
void update ()
void set (kind new_k, int new_phase, int new_frequency_log2, int new_clip)
Set palette parameters and update.
rgb palettize (double data, double min_value, double max_value)
Transform a value into an RGB color according to the palette.
void decrease_clip ()
void increase_clip ()
void decrease_frequency ()
void increase_frequency ()
void decrease_phase ()
void increase_phase ()
bool handle_key_press_event (GdkEventKey &event)
Handle with any key pressed.
Public Attributes
std::array< rgb, size > color_mapping
kind k
int phase
int clip
int frequency_log2
Static Public Attributes
static constexpr int size = 256
Detailed Description
Color palette to project a linear data space to an RGB color space.
Reimplement the palette concept by Nicolas Paris in PompC & HyperC back from the 90's... :-)
Definition at line 146 of file graphics.hpp.
Member Enumeration Documentation
kind [1/2]
enum trisycl::vendor::xilinx::graphics::palette::kind
Enumerator
gray
rainbow
gray
rainbow
Definition at line 150 of file graphics.hpp.
{ gray, rainbow };
kind [2/2]
enum trisycl::vendor::xilinx::graphics::palette::kind
Enumerator
gray
rainbow
gray
rainbow
Definition at line 150 of file graphics.hpp.
{ gray, rainbow };
Constructor & Destructor Documentation
palette() [1/2]
trisycl::vendor::xilinx::graphics::palette::palette (kind k = gray, int phase = 0, int frequency_log2 = 0, int clip = -1) inline
Create a palette.
Parameters
[in] k is the kind of palette
[in] phase is optional and allows the palette to have a phase shift instead of starting at 0
[in] clip is optional and specifies a value to be enhanced
Definition at line 165 of file graphics.hpp.
    : k { k }, phase { phase } , clip { clip }, frequency_log2{frequency_log2} {
      update();
    }
References update().
palette() [2/2]
trisycl::vendor::xilinx::graphics::palette::palette (kind k = gray, int phase = 0, int frequency_log2 = 0, int clip = -1) inline
Create a palette.
Parameters
[in] k is the kind of palette
[in] phase is optional and allows the palette to have a phase shift instead of starting at 0
[in] clip is optional and specifies a value to be enhanced
Definition at line 165 of file graphics.hpp.
    : k { k }, phase { phase } , clip { clip }, frequency_log2{frequency_log2} {
      update();
    }
References update().
Member Function Documentation
decrease_clip() [1/2]
void trisycl::vendor::xilinx::graphics::palette::decrease_clip () inline
Definition at line 272 of file graphics.hpp.
                       {
    --clip;
    update();
  }
References clip, and update().
Referenced by handle_key_press_event().
decrease_clip() [2/2]
void trisycl::vendor::xilinx::graphics::palette::decrease_clip () inline
Definition at line 272 of file graphics.hpp.
                       {
    --clip;
    update();
  }
References clip, and update().
decrease_frequency() [1/2]
void trisycl::vendor::xilinx::graphics::palette::decrease_frequency () inline
Definition at line 284 of file graphics.hpp.
{
    --frequency_log2;
    update();
  }
References frequency_log2, and update().
Referenced by handle_key_press_event().
decrease_frequency() [2/2]
void trisycl::vendor::xilinx::graphics::palette::decrease_frequency () inline
Definition at line 284 of file graphics.hpp.
{
    --frequency_log2;
    update();
  }
References frequency_log2, and update().
decrease_phase() [1/2]
void trisycl::vendor::xilinx::graphics::palette::decrease_phase () inline
Definition at line 296 of file graphics.hpp.
{
    --phase;
    update();
  }
References phase, and update().
Referenced by handle_key_press_event().
decrease_phase() [2/2]
void trisycl::vendor::xilinx::graphics::palette::decrease_phase () inline
Definition at line 296 of file graphics.hpp.
{
    --phase;
    update();
  }
References phase, and update().
gray_palette() [1/2]
void trisycl::vendor::xilinx::graphics::palette::gray_palette () inline
Definition at line 172 of file graphics.hpp.
                      {
    for (int i = 0; auto &e : color_mapping) {
      if (i == clip)
        // Put a full red color for the selected value
        e = { 255, 0, 0 };
      else {
        int j;
        // There is no bidirectional shift operator in C++
        if (frequency_log2 < 0)
          // Divide the step by 2^{-fl}
          j = i >> -frequency_log2;
        else
          // Multiply the step by 2^{fl}
          j = i << frequency_log2;
        auto v = static_cast<std::uint8_t>(j + phase);
        // A non-saturated "gray" of luminosity v
        e = { v,  v,  v };
      }
      ++i;
    }
  }
References clip, color_mapping, frequency_log2, i, and phase.
Referenced by update().
gray_palette() [2/2]
void trisycl::vendor::xilinx::graphics::palette::gray_palette () inline
Definition at line 172 of file graphics.hpp.
                      {
    for (int i = 0; auto &e : color_mapping) {
      if (i == clip)
        // Put a full red color for the selected value
        e = { 255, 0, 0 };
      else {
        int j;
        // There is no bidirectional shift operator in C++
        if (frequency_log2 < 0)
          // Divide the step by 2^{-fl}
          j = i >> -frequency_log2;
        else
          // Multiply the step by 2^{fl}
          j = i << frequency_log2;
        auto v = static_cast<std::uint8_t>(j + phase);
        // A non-saturated "gray" of luminosity v
        e = { v,  v,  v };
      }
      ++i;
    }
  }
References clip, color_mapping, frequency_log2, i, and phase.
handle_key_press_event() [1/2]
bool trisycl::vendor::xilinx::graphics::palette::handle_key_press_event (GdkEventKey & event) inline
Handle with any key pressed.
Definition at line 309 of file graphics.hpp.
{
    /* Only listen to keys without modifiers (no control, alt...) but
       still allows shift */
    if (!(event.state
          & gtk_accelerator_get_default_mod_mask()
          & ~GDK_SHIFT_MASK)) {
      switch (event.keyval) {
      case GDK_KEY_0:
      case GDK_KEY_KP_0:
        k = gray;
        update();
        break;
      case GDK_KEY_1:
      case GDK_KEY_KP_1:
        k = rainbow;
        update();
        break;
      case GDK_KEY_minus:
      case GDK_KEY_KP_Subtract:
      case GDK_KEY_underscore:
        decrease_frequency();
        break;
      case GDK_KEY_plus:
      case GDK_KEY_KP_Add:
      case GDK_KEY_equal:
      case GDK_KEY_KP_Equal:
        increase_frequency();
        break;
      case GDK_KEY_h:
        increase_phase();
        break;
      case GDK_KEY_H:
        increase_phase();
        decrease_clip();
        break;
      case GDK_KEY_j:
        decrease_clip();
        break;
      case GDK_KEY_k:
        increase_clip();
        break;
      case GDK_KEY_l:
        decrease_phase();
        break;
      case GDK_KEY_L:
        decrease_phase();
        increase_clip();
        break;
      default:
        // Not a key press for us: let the other listeners to handle
        return false;
      }
      // We have handled the event: do not go on with any other listener
      return true;
    }
    // Not the right modifiers: let the other listeners to handle
    return false;
  }
References decrease_clip(), decrease_frequency(), decrease_phase(), gray, increase_clip(), increase_frequency(), increase_phase(), k, rainbow, and update().
Referenced by trisycl::vendor::xilinx::graphics::image_grid::on_key_press_event().
handle_key_press_event() [2/2]
bool trisycl::vendor::xilinx::graphics::palette::handle_key_press_event (GdkEventKey & event) inline
Handle with any key pressed.
Definition at line 309 of file graphics.hpp.
{
    /* Only listen to keys without modifiers (no control, alt...) but
       still allows shift */
    if (!(event.state
          & gtk_accelerator_get_default_mod_mask()
          & ~GDK_SHIFT_MASK)) {
      switch (event.keyval) {
      case GDK_KEY_0:
      case GDK_KEY_KP_0:
        k = gray;
        update();
        break;
      case GDK_KEY_1:
      case GDK_KEY_KP_1:
        k = rainbow;
        update();
        break;
      case GDK_KEY_minus:
      case GDK_KEY_KP_Subtract:
      case GDK_KEY_underscore:
        decrease_frequency();
        break;
      case GDK_KEY_plus:
      case GDK_KEY_KP_Add:
      case GDK_KEY_equal:
      case GDK_KEY_KP_Equal:
        increase_frequency();
        break;
      case GDK_KEY_h:
        increase_phase();
        break;
      case GDK_KEY_H:
        increase_phase();
        decrease_clip();
        break;
      case GDK_KEY_j:
        decrease_clip();
        break;
      case GDK_KEY_k:
        increase_clip();
        break;
      case GDK_KEY_l:
        decrease_phase();
        break;
      case GDK_KEY_L:
        decrease_phase();
        increase_clip();
        break;
      default:
        // Not a key press for us: let the other listeners to handle
        return false;
      }
      // We have handled the event: do not go on with any other listener
      return true;
    }
    // Not the right modifiers: let the other listeners to handle
    return false;
  }
References decrease_clip(), decrease_frequency(), decrease_phase(), gray, increase_clip(), increase_frequency(), increase_phase(), k, rainbow, and update().
increase_clip() [1/2]
void trisycl::vendor::xilinx::graphics::palette::increase_clip () inline
Definition at line 278 of file graphics.hpp.
                       {
    ++clip;
    update();
  }
References clip, and update().
Referenced by handle_key_press_event().
increase_clip() [2/2]
void trisycl::vendor::xilinx::graphics::palette::increase_clip () inline
Definition at line 278 of file graphics.hpp.
                       {
    ++clip;
    update();
  }
References clip, and update().
increase_frequency() [1/2]
void trisycl::vendor::xilinx::graphics::palette::increase_frequency () inline
Definition at line 290 of file graphics.hpp.
{
    ++frequency_log2;
    update();
  }
References frequency_log2, and update().
Referenced by handle_key_press_event().
increase_frequency() [2/2]
void trisycl::vendor::xilinx::graphics::palette::increase_frequency () inline
Definition at line 290 of file graphics.hpp.
{
    ++frequency_log2;
    update();
  }
References frequency_log2, and update().
increase_phase() [1/2]
void trisycl::vendor::xilinx::graphics::palette::increase_phase () inline
Definition at line 302 of file graphics.hpp.
{
    ++phase;
    update();
  }
References phase, and update().
Referenced by handle_key_press_event().
increase_phase() [2/2]
void trisycl::vendor::xilinx::graphics::palette::increase_phase () inline
Definition at line 302 of file graphics.hpp.
{
    ++phase;
    update();
  }
References phase, and update().
palettize() [1/2]
rgb trisycl::vendor::xilinx::graphics::palette::palettize (double data, double min_value, double max_value) inline
Transform a value into an RGB color according to the palette.
Definition at line 265 of file graphics.hpp.
{
    std::uint8_t v = (data - min_value)*255/(max_value - min_value);
    // Write the same value for RGB to have a grey level
    return color_mapping[v];
  }
References color_mapping.
Referenced by trisycl::vendor::xilinx::graphics::image_grid::update_tile_data_image().
palettize() [2/2]
rgb trisycl::vendor::xilinx::graphics::palette::palettize (double data, double min_value, double max_value) inline
Transform a value into an RGB color according to the palette.
Definition at line 265 of file graphics.hpp.
{
    std::uint8_t v = (data - min_value)*255/(max_value - min_value);
    // Write the same value for RGB to have a grey level
    return color_mapping[v];
  }
References color_mapping.
rainbow_palette() [1/2]
void trisycl::vendor::xilinx::graphics::palette::rainbow_palette () inline
Definition at line 196 of file graphics.hpp.
{
    Gdk::RGBA color;
    for (int i = 0; auto &e : color_mapping) {
      // Put the selected value as black
      double luminosity = !(i == clip);
      int j;
      // There is no bidirectional shift operator in C++
      if (frequency_log2 < 0)
        // Divide the step by 2^{-fl}
        j = i >> -frequency_log2;
      else
        // Multiply the step by 2^{fl}
        j = i << frequency_log2;
      auto v = static_cast<std::uint8_t>(j + phase);
      color.set_hsv(360.*v/size, 1, luminosity);
      e = { static_cast<std::uint8_t>(color.get_red_u() >> 8),
            static_cast<std::uint8_t>(color.get_green_u() >> 8),
            static_cast<std::uint8_t>(color.get_blue_u() >> 8) };
      ++i;
    }
  }
References clip, color, color_mapping, frequency_log2, i, phase, and size.
Referenced by update().
rainbow_palette() [2/2]
void trisycl::vendor::xilinx::graphics::palette::rainbow_palette () inline
Definition at line 196 of file graphics.hpp.
{
    Gdk::RGBA color;
    for (int i = 0; auto &e : color_mapping) {
      // Put the selected value as black
      double luminosity = !(i == clip);
      int j;
      // There is no bidirectional shift operator in C++
      if (frequency_log2 < 0)
        // Divide the step by 2^{-fl}
        j = i >> -frequency_log2;
      else
        // Multiply the step by 2^{fl}
        j = i << frequency_log2;
      auto v = static_cast<std::uint8_t>(j + phase);
      color.set_hsv(360.*v/size, 1, luminosity);
      e = { static_cast<std::uint8_t>(color.get_red_u() >> 8),
            static_cast<std::uint8_t>(color.get_green_u() >> 8),
            static_cast<std::uint8_t>(color.get_blue_u() >> 8) };
      ++i;
    }
  }
References clip, color, color_mapping, frequency_log2, i, phase, and size.
set() [1/2]
void trisycl::vendor::xilinx::graphics::palette::set (kind new_k, int new_phase, int new_frequency_log2, int new_clip) inline
Set palette parameters and update.
Parameters
[in] new_k is the kind of palette
[in] new_phase allows the palette to have a phase shift instead of starting at 0
[in] new_clip specifies a value to be enhanced
Definition at line 254 of file graphics.hpp.
{
    k = new_k;
    phase = new_phase;
    clip = new_clip;
    frequency_log2 = new_frequency_log2;
    update();
  }
References clip, frequency_log2, k, phase, and update().
set() [2/2]
void trisycl::vendor::xilinx::graphics::palette::set (kind new_k, int new_phase, int new_frequency_log2, int new_clip) inline
Set palette parameters and update.
Parameters
[in] new_k is the kind of palette
[in] new_phase allows the palette to have a phase shift instead of starting at 0
[in] new_clip specifies a value to be enhanced
Definition at line 254 of file graphics.hpp.
{
    k = new_k;
    phase = new_phase;
    clip = new_clip;
    frequency_log2 = new_frequency_log2;
    update();
  }
References clip, frequency_log2, k, phase, and update().
update() [1/2]
void trisycl::vendor::xilinx::graphics::palette::update () inline
Definition at line 221 of file graphics.hpp.
                {
    // Implement modulo arithmetic on interval [-1, size - 1]
    if (clip < -1)
      clip = size - 1;
    else if (clip >= size)
        clip = -1;
    // The frequency can only evolve in this interval
    frequency_log2 = std::clamp(frequency_log2, -8, 7);
    /* The phase can evolve modulo size. When there are some negative
       numbers it is implementation dependent but that is enough for
       this GUI */
    phase = phase % size;
    switch (k) {
      case gray:
        gray_palette();
        break;
      case rainbow:
        rainbow_palette();
        break;
    }
  }
References clip, frequency_log2, gray, gray_palette(), k, phase, rainbow, rainbow_palette(), and size.
Referenced by decrease_clip(), decrease_frequency(), decrease_phase(), handle_key_press_event(), increase_clip(), increase_frequency(), increase_phase(), palette(), and set().
update() [2/2]
void trisycl::vendor::xilinx::graphics::palette::update () inline
Definition at line 221 of file graphics.hpp.
                {
    // Implement modulo arithmetic on interval [-1, size - 1]
    if (clip < -1)
      clip = size - 1;
    else if (clip >= size)
        clip = -1;
    // The frequency can only evolve in this interval
    frequency_log2 = std::clamp(frequency_log2, -8, 7);
    /* The phase can evolve modulo size. When there are some negative
       numbers it is implementation dependent but that is enough for
       this GUI */
    phase = phase % size;
    switch (k) {
      case gray:
        gray_palette();
        break;
      case rainbow:
        rainbow_palette();
        break;
    }
  }
References clip, frequency_log2, gray, gray_palette(), k, phase, rainbow, rainbow_palette(), and size.
Member Data Documentation
clip
int trisycl::vendor::xilinx::graphics::palette::clip
Definition at line 153 of file graphics.hpp.
Referenced by decrease_clip(), gray_palette(), increase_clip(), rainbow_palette(), set(), and update().
color_mapping
std::array< rgb, size > trisycl::vendor::xilinx::graphics::palette::color_mapping
Definition at line 148 of file graphics.hpp.
Referenced by gray_palette(), palettize(), and rainbow_palette().
frequency_log2
int trisycl::vendor::xilinx::graphics::palette::frequency_log2
Definition at line 154 of file graphics.hpp.
Referenced by decrease_frequency(), gray_palette(), increase_frequency(), rainbow_palette(), set(), and update().
k
kind trisycl::vendor::xilinx::graphics::palette::k
Definition at line 151 of file graphics.hpp.
Referenced by handle_key_press_event(), set(), and update().
phase
int trisycl::vendor::xilinx::graphics::palette::phase
Definition at line 152 of file graphics.hpp.
Referenced by decrease_phase(), gray_palette(), increase_phase(), rainbow_palette(), set(), and update().
size
static constexpr int trisycl::vendor::xilinx::graphics::palette::size = 256 static constexpr
Definition at line 147 of file graphics.hpp.
Referenced by rainbow_palette(), and update().
The documentation for this struct was generated from the following files:
include/sycl/vendor/Xilinx/graphics.hpp
include/triSYCL/vendor/Xilinx/graphics.hpp