triSYCL implementation of OpenCL SYCL: cl::sycl::detail::shared_ptr_implementation< Parent, Implementation > Struct Template Reference
cl::sycl::detail::shared_ptr_implementation< Parent, Implementation > Struct Template Reference
Provide an implementation as shared_ptr with total ordering and hashing to be used with algorithms and in (un)ordered containers.
#include <shared_ptr_implementation.hpp>
Public Member Functions
shared_ptr_implementation (std::shared_ptr< Implementation > i)
The implementation directly as a shared pointer.
shared_ptr_implementation (Implementation *i)
The implementation takes the ownership from a raw pointer.
shared_ptr_implementation ()=default
Keep all other constructors to have usual shared_ptr behaviour.
bool operator== (const Parent &other) const
Equality operator.
bool operator< (const Parent &other) const
Inferior operator.
auto hash () const
Forward the hashing for unordered containers to the implementation.
Public Attributes
std::shared_ptr< Implementation > implementation
The implementation forward everything to this... implementation.
Detailed Description
template<typename Parent, typename Implementation>
struct cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >
Provide an implementation as shared_ptr with total ordering and hashing to be used with algorithms and in (un)ordered containers.
To be used, a Parent class wanting an Implementation needs to inherit from.
The implementation ends up in a member really named "implementation".
public detail::shared_ptr_implementation<Parent, Implementation>
and also inject in std namespace a specialization for
hash<Parent>
Definition at line 40 of file shared_ptr_implementation.hpp.
Constructor & Destructor Documentation
shared_ptr_implementation() [1/3]
template<typename Parent, typename Implementation> cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >::shared_ptr_implementation (std::shared_ptr< Implementation > i) inline
The implementation directly as a shared pointer.
Definition at line 46 of file shared_ptr_implementation.hpp.
     : implementation { i } {}
shared_ptr_implementation() [2/3]
template<typename Parent, typename Implementation> cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >::shared_ptr_implementation (Implementation * i) inline
The implementation takes the ownership from a raw pointer.
Definition at line 51 of file shared_ptr_implementation.hpp.
 : implementation { i } {}
shared_ptr_implementation() [3/3]
template<typename Parent, typename Implementation> cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >::shared_ptr_implementation () default
Keep all other constructors to have usual shared_ptr behaviour.
Referenced by cl::sycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::pipe< T > >::shared_ptr_implementation().
Member Function Documentation
hash()
template<typename Parent, typename Implementation> auto cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >::hash () const inline
Forward the hashing for unordered containers to the implementation.
Definition at line 83 of file shared_ptr_implementation.hpp.
Referenced by std::hash< cl::sycl::kernel >::operator()(), std::hash< cl::sycl::platform >::operator()(), std::hash< cl::sycl::context >::operator()(), std::hash< cl::sycl::device >::operator()(), and std::hash< cl::sycl::queue >::operator()().
                     {
     return std::hash<decltype(implementation)>{}(implementation);
   }
operator<()
template<typename Parent, typename Implementation> bool cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >::operator< (const Parent & other) const inline
Inferior operator.
This is generalized by boost::less_than_comparable from boost::totally_ordered to implement the equality comparable concept
Todo:
Add this to the spec
Definition at line 77 of file shared_ptr_implementation.hpp.
{
     return implementation < other.implementation;
   }
operator==()
template<typename Parent, typename Implementation> bool cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >::operator== (const Parent & other) const inline
Equality operator.
This is generalized by boost::equality_comparable from boost::totally_ordered to implement the equality comparable concept
Definition at line 64 of file shared_ptr_implementation.hpp.
{
     return implementation == other.implementation;
   }
Member Data Documentation
implementation
template<typename Parent, typename Implementation> std::shared_ptr<Implementation> cl::sycl::detail::shared_ptr_implementation< Parent, Implementation >::implementation
The implementation forward everything to this... implementation.
Definition at line 43 of file shared_ptr_implementation.hpp.
Referenced by cl::sycl::detail::shared_ptr_implementation< static_pipe< T, Capacity >, detail::pipe< T > >::hash(), and cl::sycl::handler::single_task().
The documentation for this struct was generated from the following file:
include/CL/sycl/detail/shared_ptr_implementation.hpp