triSYCL implementation of SYCL: trisycl::detail::task Struct Reference
trisycl::detail::task Struct Reference
The abstraction to represent SYCL tasks executing inside command_group.
#include <task.hpp>
Public Member Functions
task (const std::shared_ptr< detail::queue > &q)
Create a task from a submitting queue.
void schedule (std::function< void(void)> f)
Add a new task to the task graph and schedule for execution.
void wait_for_producers ()
Wait for the required producer tasks to be ready.
void release_buffers ()
Release the buffers that have been used by this task.
void notify_consumers ()
Notify the waiting tasks that we are done.
void wait ()
Wait for this task to be ready.
void add_buffer (std::shared_ptr< detail::buffer_base > &buf, bool is_write_mode)
Register a buffer to this task.
void prelude ()
Execute the prologues.
void postlude ()
Execute the epilogues.
void add_prelude (const std::function< void(void)> &f)
Add a function to the prelude to run before kernel execution.
void add_postlude (const std::function< void(void)> &f)
Add a function to the postlude to run after kernel execution.
auto get_queue ()
Get the queue behind the task to run a kernel on.
void set_kernel (const std::shared_ptr< trisycl::detail::kernel > &k)
Set the OpenCL-compatible kernel running this task if any.
trisycl::detail::kernel & get_kernel ()
Get the kernel running if any.
void set_arg (std::size_t arg_index, std::size_t arg_size, const void *scalar_value)
Set a kernel argument by address.
template<typename T >
void set_arg (std::size_t arg_index, const T &scalar_value)
Set a kernel argument by value.
auto get_compute_buffer (std::size_t order)
Get the Boost.Compute buffer for an accessor of the task.
std::size_t register_accessor (std::weak_ptr< detail::accessor_base > a)
Register an accessor and return its registration order.
Public Attributes
std::vector< std::shared_ptr< detail::buffer_base > > buffers_in_use
List of the buffers used by this task.
std::vector< std::shared_ptr< detail::task > > producer_tasks
The tasks producing the buffers used by this task.
std::vector< std::function< void(void)> > prologues
Keep track of any prologue to be executed before the kernel.
std::vector< std::function< void(void)> > epilogues
Keep track of any epilogue to be executed after the kernel.
bool execution_ended = false
Store if the execution ended, to be notified by task_ready.
std::condition_variable ready
To signal when this task is ready.
std::mutex ready_mutex
To protect the access to the condition variable.
std::shared_ptr< detail::queue > owner_queue
Keep track of the queue used to submission to notify kernel completion or to run OpenCL kernels on.
std::shared_ptr< detail::kernel > kernel
The OpenCL-compatible kernel run by this task, if any.
std::vector< std::weak_ptr< detail::accessor_base > > accessors
The accessors indexed by their creation order.
Additional Inherited Members
Static Public Member Functions inherited from trisycl::detail::debug< task >
static auto constexpr type_pretty_name ()
Get the pretty name of T itself.
Detailed Description
The abstraction to represent SYCL tasks executing inside command_group.
"enable_shared_from_this" allows to access the shared_ptr behind the scene.
Definition at line 35 of file task.hpp.
Constructor & Destructor Documentation
task()
trisycl::detail::task::task (const std::shared_ptr< detail::queue > & q) inline
Create a task from a submitting queue.
Definition at line 78 of file task.hpp.
    : owner_queue { q } {}
Member Function Documentation
add_buffer()
void trisycl::detail::task::add_buffer (std::shared_ptr< detail::buffer_base > & buf, bool is_write_mode) inline
Register a buffer to this task.
This is how the dependency graph is incrementally built.
Definition at line 176 of file task.hpp.
{
    TRISYCL_DUMP_T("Add buffer " << buf << " in task " << this);
    /* Keep track of the use of the buffer to notify its release at
       the end of the execution */
    buffers_in_use.push_back(buf);
    // To be sure the buffer does not disappear before the kernel can run
    buf->use();
    std::shared_ptr<detail::task> latest_producer;
    if (is_write_mode) {
      /* Set this task as the latest producer of the buffer so that
         another kernel may wait on this task */
      latest_producer = buf->set_latest_producer(shared_from_this());
    }
    else
      latest_producer = buf->get_latest_producer();
    /* If the buffer is to be produced by a task, add the task in the
       producer list to wait on it before running the task core
       If a buffer is accessed first in write mode and then in read mode,
       the task will add itself as a producer and will wait for itself
       when calling \c wait_for_producers, we avoid this by checking that
       \c latest_producer is not \c this
    */
    if (latest_producer && latest_producer != shared_from_this())
      producer_tasks.push_back(latest_producer);
  }
References buffers_in_use, producer_tasks, and TRISYCL_DUMP_T.
add_postlude()
void trisycl::detail::task::add_postlude (const std::function< void(void)> & f) inline
Add a function to the postlude to run after kernel execution.
Definition at line 238 of file task.hpp.
{
    epilogues.push_back(f);
  }
References epilogues.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::register_accessor().
add_prelude()
void trisycl::detail::task::add_prelude (const std::function< void(void)> & f) inline
Add a function to the prelude to run before kernel execution.
Definition at line 230 of file task.hpp.
{
    TRISYCL_DUMP_T("task::add_prelude");
    prologues.push_back(f);
  }
References prologues, and TRISYCL_DUMP_T.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::register_accessor().
get_compute_buffer()
auto trisycl::detail::task::get_compute_buffer (std::size_t order) inline
Get the Boost.Compute buffer for an accessor of the task.
Definition at line 293 of file task.hpp.
{
    return accessors[order].lock()->get_cl_buffer();
  }
References accessors.
Referenced by trisycl::drt::serialize_accessor_arg().
get_kernel()
trisycl::detail::kernel & trisycl::detail::task::get_kernel () inline
Get the kernel running if any.
Todo:
Specify this error in the spec
Definition at line 259 of file task.hpp.
{
    if (!kernel)
      throw non_cl_error("Cannot use an OpenCL kernel in this context");
    return *kernel;
  }
References kernel.
Referenced by set_arg().
get_queue()
auto trisycl::detail::task::get_queue () inline
Get the queue behind the task to run a kernel on.
Definition at line 244 of file task.hpp.
                   {
    return owner_queue;
  }
References owner_queue.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::copy_in_cl_buffer(), trisycl::detail::accessor< T, Dimensions, Mode, Target >::get_cl_buffer(), trisycl::detail::accessor< T, Dimensions, Mode, Target >::register_accessor(), and trisycl::drt::set_kernel().
notify_consumers()
void trisycl::detail::task::notify_consumers () inline
Notify the waiting tasks that we are done.
Definition at line 149 of file task.hpp.
{
    TRISYCL_DUMP_T("Notify all the task waiting for this task " << this);
   {
     std::unique_lock<std::mutex> ul { ready_mutex };
     execution_ended = true;
   }
    /* \todo Verify that the memory model with the notify does not
       require some fence or atomic */
    ready.notify_all();
  }
References execution_ended, ready, ready_mutex, and TRISYCL_DUMP_T.
Referenced by schedule().
postlude()
void trisycl::detail::task::postlude () inline
Execute the epilogues.
Definition at line 220 of file task.hpp.
                  {
    for (const auto &p : epilogues)
      p();
    /* Free the functors that may own an accessor owning a buffer
       preventing the command group to complete */
    epilogues.clear();
  }
References epilogues, and p.
Referenced by schedule().
prelude()
void trisycl::detail::task::prelude () inline
Execute the prologues.
Definition at line 208 of file task.hpp.
                 {
    TRISYCL_DUMP_T("task::prelude");
    for (const auto &p : prologues)
      p();
    /* Free the functors that may own an accessor owning a buffer
       preventing the command group to complete */
    prologues.clear();
  }
References p, prologues, and TRISYCL_DUMP_T.
Referenced by schedule().
register_accessor()
std::size_t trisycl::detail::task::register_accessor (std::weak_ptr< detail::accessor_base > a) inline
Register an accessor and return its registration order.
I would prefer to name this method register but this is a C++ keyword...
Definition at line 304 of file task.hpp.
{
  accessors.push_back(a);
  return accessors.size() - 1;
}
References a, and accessors.
Referenced by trisycl::detail::accessor< T, Dimensions, Mode, Target >::register_accessor().
release_buffers()
void trisycl::detail::task::release_buffers () inline
Release the buffers that have been used by this task.
Definition at line 140 of file task.hpp.
{
    TRISYCL_DUMP_T("Task " << this << " releases the written buffers");
    for (auto b: buffers_in_use)
      b->release();
    buffers_in_use.clear();
  }
References b, buffers_in_use, and TRISYCL_DUMP_T.
Referenced by schedule().
schedule()
void trisycl::detail::task::schedule (std::function< void(void)> f) inline
Add a new task to the task graph and schedule for execution.
Detach the thread since it will synchronize by its own means
Todo:
This is an issue if there is an exception in the kernel
Definition at line 83 of file task.hpp.
{
    /* To keep a copy of the task shared_ptr after the end of the
       command group, capture it by copy in the following lambda.
    */
    auto execution = [f = std::move(f), task = shared_from_this()] {
      // Wait for the required tasks to be ready
      task->wait_for_producers();
      task->prelude();
      TRISYCL_DUMP_T("Execute the kernel");
      // Execute the kernel
      f();
      task->postlude();
      // Release the buffers that have been written by this task
      task->release_buffers();
      // Notify the waiting tasks that we are done
      task->notify_consumers();
      // Notify the queue we are done
      task->owner_queue->kernel_end();
      TRISYCL_DUMP_T("Task thread exit");
    };
    /* Notify the queue that there is a kernel submitted to the
       queue. Do not do it in the task contructor so that we can deal
       with command group without kernel and if we put it inside the
       thread, the queue may have finished before the thread is
       scheduled */
    owner_queue->kernel_start();
    /* \todo it may be implementable with packaged_task that would
       deal with exceptions in kernels
    */
#ifndef TRISYCL_NO_ASYNC
    /* If in asynchronous execution mode, execute the functor in a new
       thread */
    std::thread thread(execution);
    TRISYCL_DUMP_T("Task thread started");
    /** Detach the thread since it will synchronize by its own means
        \todo This is an issue if there is an exception in the kernel
    */
    thread.detach();
#else
    // Just a synchronous execution otherwise
    execution();
#endif
  }
References notify_consumers(), owner_queue, postlude(), prelude(), release_buffers(), TRISYCL_DUMP_T, and wait_for_producers().
set_arg() [1/2]
template<typename T > void trisycl::detail::task::set_arg (std::size_t arg_index, const T & scalar_value) inline
Set a kernel argument by value.
Definition at line 281 of file task.hpp.
{
#ifdef TRISYCL_OPENCL
    // Forward to the OpenCL kernel
    get_kernel().get_boost_compute().set_arg(arg_index, scalar_value);
#else
    throw non_cl_error("Not compiled with OpenCL support");
#endif
  }
References trisycl::detail::kernel::get_boost_compute(), and get_kernel().
set_arg() [2/2]
void trisycl::detail::task::set_arg (std::size_t arg_index, std::size_t arg_size, const void * scalar_value) inline
Set a kernel argument by address.
Definition at line 267 of file task.hpp.
{
#ifdef TRISYCL_OPENCL
    // Forward to the OpenCL kernel
    get_kernel().get_boost_compute().set_arg(arg_index,
                                             arg_size,
                                             scalar_value);
#else
    throw non_cl_error("Not compiled with OpenCL support");
#endif
  }
References trisycl::detail::kernel::get_boost_compute(), and get_kernel().
Referenced by trisycl::drt::serialize_accessor_arg(), and trisycl::drt::serialize_arg().
set_kernel()
void trisycl::detail::task::set_kernel (const std::shared_ptr< trisycl::detail::kernel > & k) inline
Set the OpenCL-compatible kernel running this task if any.
Definition at line 250 of file task.hpp.
{
    kernel = k;
  }
Referenced by trisycl::drt::set_kernel().
wait()
void trisycl::detail::task::wait () inline
Wait for this task to be ready.
This is to be called from another thread
Definition at line 165 of file task.hpp.
              {
    TRISYCL_DUMP_T("The task wait for task " << this << " to end");
    std::unique_lock<std::mutex> ul { ready_mutex };
    ready.wait(ul, [&] { return execution_ended; });
  }
References execution_ended, ready, ready_mutex, and TRISYCL_DUMP_T.
wait_for_producers()
void trisycl::detail::task::wait_for_producers () inline
Wait for the required producer tasks to be ready.
Definition at line 130 of file task.hpp.
{
    TRISYCL_DUMP_T("Task " << this << " waits for the producer tasks");
    for (auto &t : producer_tasks)
      t->wait();
    // We can let the producers rest in peace
    producer_tasks.clear();
  }
References producer_tasks, and TRISYCL_DUMP_T.
Referenced by schedule().
Member Data Documentation
accessors
std::vector<std::weak_ptr<detail::accessor_base> > trisycl::detail::task::accessors
The accessors indexed by their creation order.
This is used to relate a kernel parameter of a kernel generated by the device compiler to its accessor.
Definition at line 74 of file task.hpp.
Referenced by get_compute_buffer(), and register_accessor().
buffers_in_use
std::vector<std::shared_ptr<detail::buffer_base> > trisycl::detail::task::buffers_in_use
List of the buffers used by this task.
Todo:
Use a set to check that some buffers are not used many times at least on writing
Definition at line 43 of file task.hpp.
Referenced by add_buffer(), and release_buffers().
epilogues
std::vector<std::function<void(void)> > trisycl::detail::task::epilogues
Keep track of any epilogue to be executed after the kernel.
Definition at line 52 of file task.hpp.
Referenced by add_postlude(), and postlude().
execution_ended
bool trisycl::detail::task::execution_ended = false
Store if the execution ended, to be notified by task_ready.
Definition at line 55 of file task.hpp.
Referenced by notify_consumers(), and wait().
kernel
std::shared_ptr<detail::kernel> trisycl::detail::task::kernel
The OpenCL-compatible kernel run by this task, if any.
Definition at line 68 of file task.hpp.
Referenced by get_kernel().
owner_queue
std::shared_ptr<detail::queue> trisycl::detail::task::owner_queue
Keep track of the queue used to submission to notify kernel completion or to run OpenCL kernels on.
Definition at line 65 of file task.hpp.
Referenced by get_queue(), and schedule().
producer_tasks
std::vector<std::shared_ptr<detail::task> > trisycl::detail::task::producer_tasks
The tasks producing the buffers used by this task.
Definition at line 46 of file task.hpp.
Referenced by add_buffer(), and wait_for_producers().
prologues
std::vector<std::function<void(void)> > trisycl::detail::task::prologues
Keep track of any prologue to be executed before the kernel.
Definition at line 49 of file task.hpp.
Referenced by add_prelude(), and prelude().
ready
std::condition_variable trisycl::detail::task::ready
To signal when this task is ready.
Definition at line 58 of file task.hpp.
Referenced by notify_consumers(), and wait().
ready_mutex
std::mutex trisycl::detail::task::ready_mutex
To protect the access to the condition variable.
Definition at line 61 of file task.hpp.
Referenced by notify_consumers(), and wait().
The documentation for this struct was generated from the following file:
include/triSYCL/command_group/detail/task.hpp