triSYCL implementation of OpenCL SYCL: cl::sycl::detail::task Struct Reference
cl::sycl::detail::task Struct Reference
The abstraction to represent SYCL tasks executing inside command_group.
#include <task.hpp>
Public Member Functions
task (const std::shared_ptr< detail::queue > &q)
Create a task from a submitting queue.
void schedule (std::function< void(void)> f)
Add a new task to the task graph and schedule for execution.
void wait_for_producers ()
Wait for the required producer tasks to be ready.
void release_buffers ()
Release the buffers that have been used by this task.
void notify_consumers ()
Notify the waiting tasks that we are done.
void wait ()
Wait for this task to be ready.
void add_buffer (std::shared_ptr< detail::buffer_base > &buf, bool is_write_mode)
Register a buffer to this task.
void prelude ()
Execute the prologues.
void postlude ()
Execute the epilogues.
void add_prelude (const std::function< void(void)> &f)
Add a function to the prelude to run before kernel execution.
void add_postlude (const std::function< void(void)> &f)
Add a function to the postlude to run after kernel execution.
auto get_queue ()
Get the queue behind the task to run a kernel on.
void set_kernel (const std::shared_ptr< cl::sycl::detail::kernel > &k)
Set the kernel running this task if any.
cl::sycl::detail::kernel & get_kernel ()
Get the kernel running if any.
Public Attributes
std::vector< std::shared_ptr< detail::buffer_base > > buffers_in_use
List of the buffers used by this task.
std::vector< std::shared_ptr< detail::task > > producer_tasks
The tasks producing the buffers used by this task.
std::vector< std::function< void(void)> > prologues
Keep track of any prologue to be executed before the kernel.
std::vector< std::function< void(void)> > epilogues
Keep track of any epilogue to be executed after the kernel.
bool execution_ended = false
Store if the execution ended, to be notified by task_ready.
std::condition_variable ready
To signal when this task is ready.
std::mutex ready_mutex
To protect the access to the condition variable.
std::shared_ptr< detail::queue > owner_queue
Keep track of the queue used to submission to notify kernel completion or to run OpenCL kernels on.
std::shared_ptr< cl::sycl::detail::kernel > kernel
Detailed Description
The abstraction to represent SYCL tasks executing inside command_group.
"enable_shared_from_this" allows to access the shared_ptr behind the scene.
Definition at line 34 of file task.hpp.
Constructor & Destructor Documentation
cl::sycl::detail::task::task (const std::shared_ptr< detail::queue > & q) inline
Create a task from a submitting queue.
Definition at line 70 of file task.hpp.
     : owner_queue { q } {}
Member Function Documentation
void cl::sycl::detail::task::add_buffer (std::shared_ptr< detail::buffer_base > & buf, bool is_write_mode) inline
Register a buffer to this task.
This is how the dependency graph is incrementally built.
Definition at line 167 of file task.hpp.
References TRISYCL_DUMP_T.
{
     TRISYCL_DUMP_T("Add buffer " << buf << " in task " << this);
     /* Keep track of the use of the buffer to notify its release at
        the end of the execution */
     buffers_in_use.push_back(buf);
     // To be sure the buffer does not disappear before the kernel can run
     buf->use();
     std::shared_ptr<detail::task> latest_producer;
     if (is_write_mode) {
       /* Set this task as the latest producer of the buffer so that
          another kernel may wait on this task */
       latest_producer = buf->set_latest_producer(shared_from_this());
     }
     else
       latest_producer = buf->get_latest_producer();
     /* If the buffer is to be produced by a task, add the task in the
        producer list to wait on it before running the task core */
     if (latest_producer)
       producer_tasks.push_back(latest_producer);
   }
void cl::sycl::detail::task::add_postlude (const std::function< void(void)> & f) inline
Add a function to the postlude to run after kernel execution.
Definition at line 219 of file task.hpp.
{
     epilogues.push_back(f);
   }
void cl::sycl::detail::task::add_prelude (const std::function< void(void)> & f) inline
Add a function to the prelude to run before kernel execution.
Definition at line 213 of file task.hpp.
{
     prologues.push_back(f);
   }
cl::sycl::detail::kernel& cl::sycl::detail::task::get_kernel () inline
Get the kernel running if any.
Todo:
Specify this error in the spec
Definition at line 240 of file task.hpp.
References kernel.
{
     if (!kernel)
       throw non_cl_error("Cannot use an OpenCL kernel in this context");
     return *kernel;
   }
auto cl::sycl::detail::task::get_queue () inline
Get the queue behind the task to run a kernel on.
Definition at line 225 of file task.hpp.
References owner_queue.
                    {
     return owner_queue;
   }
void cl::sycl::detail::task::notify_consumers () inline
Notify the waiting tasks that we are done.
Definition at line 143 of file task.hpp.
References TRISYCL_DUMP_T.
Referenced by schedule().
{
     TRISYCL_DUMP_T("Notify all the task waiting for this task " << this);
     execution_ended = true;
     /* \todo Verify that the memory model with the notify does not
        require some fence or atomic */
     ready.notify_all();
   }
void cl::sycl::detail::task::postlude () inline
Execute the epilogues.
Definition at line 203 of file task.hpp.
Referenced by schedule().
                   {
     for (const auto &p : epilogues)
       p();
     /* Free the functors that may own an accessor owning a buffer
        preventing the command group to complete */
     epilogues.clear();
   }
void cl::sycl::detail::task::prelude () inline
Execute the prologues.
Definition at line 193 of file task.hpp.
Referenced by schedule().
                  {
     for (const auto &p : prologues)
       p();
     /* Free the functors that may own an accessor owning a buffer
        preventing the command group to complete */
     prologues.clear();
   }
void cl::sycl::detail::task::release_buffers () inline
Release the buffers that have been used by this task.
Definition at line 134 of file task.hpp.
References TRISYCL_DUMP_T.
Referenced by schedule().
{
     TRISYCL_DUMP_T("Task " << this << " releases the written buffers");
     for (auto b: buffers_in_use)
       b->release();
     buffers_in_use.clear();
   }
void cl::sycl::detail::task::schedule (std::function< void(void)> f) inline
Add a new task to the task graph and schedule for execution.
Detach the thread since it will synchronize by its own means
Todo:
This is an issue if there is an exception in the kernel
Definition at line 75 of file task.hpp.
References notify_consumers(), postlude(), prelude(), release_buffers(), TRISYCL_DUMP_T, and wait_for_producers().
{
     /* To keep a copy of the task shared_ptr after the end of the
        command group, capture it by copy in the following lambda. This
        should be easier in C++17 with move semantics on capture
     */
     auto task = shared_from_this();
     auto execution = [=] {
       // Wait for the required tasks to be ready
       task->wait_for_producers();
       task->prelude();
       TRISYCL_DUMP_T("Execute the kernel");
       // Execute the kernel
       f();
       task->postlude();
       // Release the buffers that have been written by this task
       task->release_buffers();
       // Notify the waiting tasks that we are done
       task->notify_consumers();
       // Notify the queue we are done
       owner_queue->kernel_end();
       TRISYCL_DUMP_T("Task thread exit");
     };
     /* Notify the queue that there is a kernel submitted to the
        queue. Do not do it in the task contructor so that we can deal
        with command group without kernel and if we put it inside the
        thread, the queue may have finished before the thread is
        scheduled */
     owner_queue->kernel_start();
     /* \todo it may be implementable with packaged_task that would
        deal with exceptions in kernels
     */
 #ifndef TRISYCL_NO_ASYNC
     /* If in asynchronous execution mode, execute the functor in a new
        thread */
     std::thread thread(execution);
     TRISYCL_DUMP_T("Task thread started");
     /** Detach the thread since it will synchronize by its own means
         \todo This is an issue if there is an exception in the kernel
     */
     thread.detach();
 #else
     // Just a synchronous execution otherwise
     execution();
 #endif
   }
void cl::sycl::detail::task::set_kernel (const std::shared_ptr< cl::sycl::detail::kernel > & k) inline
Set the kernel running this task if any.
Definition at line 231 of file task.hpp.
{
     kernel = k;
   }
void cl::sycl::detail::task::wait () inline
Wait for this task to be ready.
This is to be called from another thread
Definition at line 156 of file task.hpp.
References execution_ended, and TRISYCL_DUMP_T.
               {
     TRISYCL_DUMP_T("The task wait for task " << this << " to end");
     std::unique_lock<std::mutex> ul { ready_mutex };
     ready.wait(ul, [&] { return execution_ended; });
   }
void cl::sycl::detail::task::wait_for_producers () inline
Wait for the required producer tasks to be ready.
Definition at line 124 of file task.hpp.
References TRISYCL_DUMP_T.
Referenced by schedule().
{
     TRISYCL_DUMP_T("Task " << this << " waits for the producer tasks");
     for (auto &t : producer_tasks)
       t->wait();
     // We can let the producers rest in peace
     producer_tasks.clear();
   }
Member Data Documentation
std::vector<std::shared_ptr<detail::buffer_base> > cl::sycl::detail::task::buffers_in_use
List of the buffers used by this task.
Todo:
Use a set to check that some buffers are not used many times at least on writing
Definition at line 42 of file task.hpp.
std::vector<std::function<void(void)> > cl::sycl::detail::task::epilogues
Keep track of any epilogue to be executed after the kernel.
Definition at line 51 of file task.hpp.
bool cl::sycl::detail::task::execution_ended = false
Store if the execution ended, to be notified by task_ready.
Definition at line 54 of file task.hpp.
Referenced by wait().
std::shared_ptr<cl::sycl::detail::kernel> cl::sycl::detail::task::kernel
Definition at line 66 of file task.hpp.
Referenced by get_kernel().
std::shared_ptr<detail::queue> cl::sycl::detail::task::owner_queue
Keep track of the queue used to submission to notify kernel completion or to run OpenCL kernels on.
Definition at line 64 of file task.hpp.
Referenced by get_queue().
std::vector<std::shared_ptr<detail::task> > cl::sycl::detail::task::producer_tasks
The tasks producing the buffers used by this task.
Definition at line 45 of file task.hpp.
std::vector<std::function<void(void)> > cl::sycl::detail::task::prologues
Keep track of any prologue to be executed before the kernel.
Definition at line 48 of file task.hpp.
std::condition_variable cl::sycl::detail::task::ready
To signal when this task is ready.
Definition at line 57 of file task.hpp.
std::mutex cl::sycl::detail::task::ready_mutex
To protect the access to the condition variable.
Definition at line 60 of file task.hpp.
The documentation for this struct was generated from the following file:
include/CL/sycl/command_group/detail/task.hpp