triSYCL implementation of SYCL: trisycl::vendor::xilinx::graphics::image_grid Struct Reference
trisycl::vendor::xilinx::graphics::image_grid Struct Reference
An application window displaying a grid of tiled images.
#include <graphics.hpp>
Public Member Functions
image_grid (int nx, int ny, int image_x, int image_y, int zoom)
Create a grid of tiled images.
bool on_key_press_event (GdkEventKey *event) override
Deal with the key pressed.
void submit (std::function< void(void)> f)
Submit some work to the graphics thread.
template<typename MDspan , typename RangeValue , typename = typename MDspan::extents_type>
void update_tile_data_image (int x, int y, const MDspan &data, RangeValue min_value, RangeValue max_value)
Update the image of a tile.
template<typename DataType , typename RangeValue >
void update_tile_data_image (int x, int y, const DataType *data, RangeValue min_value, RangeValue max_value)
Update the image of a tile of size image_y by image_x from a pointer.
palette & get_palette ()
Return the palette used to render the value.
bool is_done_barrier ()
Test if the window has been closed after synchronizing with a barrier accross all the tiles.
image_grid (int nx, int ny, int image_x, int image_y, int zoom)
Create a grid of tiled images.
bool on_key_press_event (GdkEventKey *event) override
Deal with the key pressed.
void submit (std::function< void(void)> f)
Submit some work to the graphics thread.
template<typename MDspan , typename RangeValue , typename = typename MDspan::extents_type>
void update_tile_data_image (int x, int y, const MDspan &data, RangeValue min_value, RangeValue max_value)
Update the image of a tile.
template<typename DataType , typename RangeValue >
void update_tile_data_image (int x, int y, const DataType *data, RangeValue min_value, RangeValue max_value)
Update the image of a tile of size image_y by image_x from a pointer.
palette & get_palette ()
Return the palette used to render the value.
bool is_done_barrier ()
Test if the window has been closed after synchronizing with a barrier accross all the tiles.
Public Member Functions inherited from trisycl::vendor::xilinx::graphics::frame_grid
frame_grid (int nx, int ny)
Create a grid of tiles.
void set_close_action (std::function< void(void)> f)
Set a function to be called on close.
auto & get_frame (int x, int y)
Get the frame at a given grid position.
frame_grid (int nx, int ny)
Create a grid of tiles.
void set_close_action (std::function< void(void)> f)
Set a function to be called on close.
auto & get_frame (int x, int y)
Get the frame at a given grid position.
Public Attributes
std::vector< Gtk::Image > images
The linearized 2D vector of images.
int image_x
Horizontal image size in pixels.
int image_y
Vertical image size in pixels.
int zoom
The image pixel zooming factor for both dimension.
Glib::Dispatcher dispatcher
Dispatcher to invoke something in the graphics thread in a safe way.
std::mutex dispatch_protection
Protection against concurrent update.
std::condition_variable cv
The condition variable used to queue up graphics update submission.
std::function< void(void)> work_to_dispatch
What to dispatch.
palette p
The RGB palette used to render the image values.
bool done_snapshot
A global done state across all the tile to allow a global shutdown.
std::atomic_flag done_has_been_sampled
Set to true once "done" state has been sampled.
boost::barrier done_barrier { static_cast<unsigned int>(nx*ny) }
Barrier to compute the global done state across the tiles.
Public Attributes inherited from trisycl::vendor::xilinx::graphics::frame_grid
Gtk::ScrolledWindow sw
Nice to have some scroll bars around when the main window is too small.
Gtk::Grid grid
The container to represent the grid of tile images.
Gtk::Button close_button { "Close" }
A close button in case the closing function is not provided by the window manager.
std::vector< Gtk::Frame > frames
The linearized 2D vector of frames used to decorate the tile images with some frames with the tile names.
int nx
Number of frame columns.
int ny
Number of frame lines.
std::function< void(void)> close_action
An action to do when the window is closed.
std::atomic< bool > done = false
Set to true by the closing handler.
Detailed Description
An application window displaying a grid of tiled images.
Definition at line 372 of file graphics.hpp.
Constructor & Destructor Documentation
image_grid() [1/2]
trisycl::vendor::xilinx::graphics::image_grid::image_grid (int nx, int ny, int image_x, int image_y, int zoom) inline
Create a grid of tiled images.
Parameters
[in] nx is the numer of tiles horizontally
[in] ny is the numer of tiles vertically
[in] image_x is the horizontal image pixel size
[in] image_y is the vertical image pixel size
[in] zoom is the zooming factor applied to image pixels, both horizontally and vertically
Definition at line 422 of file graphics.hpp.
    : frame_grid { nx , ny }
    , image_x { image_x }
    , image_y { image_y }
    , zoom { zoom }
  {
    for (int y = 0; y < ny; ++y)
      for (int x = 0; x < nx; ++x) {
        auto &f = get_frame(x, y);
        auto pb = Gdk::Pixbuf::create(Gdk::Colorspace::COLORSPACE_RGB
                                    , false //< has_alpha
                                    , 8 //< bits_per_sample
                                    , image_x*zoom //< width
                                    , image_y*zoom //< height
                                      );
        images.emplace_back(pb);
        // Display the frame with the lower y to the South
        f.add(images.back());
      }
    // Hook a generic dispatcher
    dispatcher.connect([&] {
        {
          // Only 1 customer at a time
          std::lock_guard lock { dispatch_protection };
          // Skip the work when done to avoid dead lock
          if (done)
            // Wake-up everybody waiting for sending some work to
            // realize that they have to give up on their hope
            cv.notify_all();
          else
            work_to_dispatch();
          // Discard the previous work
          work_to_dispatch = nullptr;
        }
        // We can serve the next customer
        cv.notify_one();
      });
    // Go live
    show_all_children();
  }
References cv, dispatch_protection, dispatcher, trisycl::vendor::xilinx::graphics::frame_grid::done, trisycl::vendor::xilinx::graphics::frame_grid::get_frame(), image_x, image_y, images, trisycl::vendor::xilinx::graphics::frame_grid::nx, trisycl::vendor::xilinx::graphics::frame_grid::ny, work_to_dispatch, x, trisycl::y, and zoom.
image_grid() [2/2]
trisycl::vendor::xilinx::graphics::image_grid::image_grid (int nx, int ny, int image_x, int image_y, int zoom) inline
Create a grid of tiled images.
Parameters
[in] nx is the numer of tiles horizontally
[in] ny is the numer of tiles vertically
[in] image_x is the horizontal image pixel size
[in] image_y is the vertical image pixel size
[in] zoom is the zooming factor applied to image pixels, both horizontally and vertically
Definition at line 422 of file graphics.hpp.
    : frame_grid { nx , ny }
    , image_x { image_x }
    , image_y { image_y }
    , zoom { zoom }
  {
    for (int y = 0; y < ny; ++y)
      for (int x = 0; x < nx; ++x) {
        auto &f = get_frame(x, y);
        auto pb = Gdk::Pixbuf::create(Gdk::Colorspace::COLORSPACE_RGB
                                    , false //< has_alpha
                                    , 8 //< bits_per_sample
                                    , image_x*zoom //< width
                                    , image_y*zoom //< height
                                      );
        images.emplace_back(pb);
        // Display the frame with the lower y to the South
        f.add(images.back());
      }
    // Hook a generic dispatcher
    dispatcher.connect([&] {
        {
          // Only 1 customer at a time
          std::lock_guard lock { dispatch_protection };
          // Skip the work when done to avoid dead lock
          if (done)
            // Wake-up everybody waiting for sending some work to
            // realize that they have to give up on their hope
            cv.notify_all();
          else
            work_to_dispatch();
          // Discard the previous work
          work_to_dispatch = nullptr;
        }
        // We can serve the next customer
        cv.notify_one();
      });
    // Go live
    show_all_children();
  }
References cv, dispatch_protection, dispatcher, trisycl::vendor::xilinx::graphics::frame_grid::done, trisycl::vendor::xilinx::graphics::frame_grid::get_frame(), image_x, image_y, images, trisycl::vendor::xilinx::graphics::frame_grid::nx, trisycl::vendor::xilinx::graphics::frame_grid::ny, work_to_dispatch, x, trisycl::y, and zoom.
Member Function Documentation
get_palette() [1/2]
palette & trisycl::vendor::xilinx::graphics::image_grid::get_palette () inline
Return the palette used to render the value.
Definition at line 571 of file graphics.hpp.
{
    return p;
  }
References p.
get_palette() [2/2]
palette & trisycl::vendor::xilinx::graphics::image_grid::get_palette () inline
Return the palette used to render the value.
Definition at line 571 of file graphics.hpp.
{
    return p;
  }
References p.
is_done_barrier() [1/2]
bool trisycl::vendor::xilinx::graphics::image_grid::is_done_barrier () inline
Test if the window has been closed after synchronizing with a barrier accross all the tiles.
Definition at line 578 of file graphics.hpp.
{
    // Only 1 thread sample the graphics status
    if (done_has_been_sampled.test_and_set())
      done_snapshot = done;
    // Then wait for everybody to synchronize
    done_barrier.count_down_and_wait();
    // Reinitialize the flag for the next iteration
    done_has_been_sampled.clear();
    return done_snapshot;
  }
References trisycl::vendor::xilinx::graphics::frame_grid::done, done_barrier, done_has_been_sampled, and done_snapshot.
is_done_barrier() [2/2]
bool trisycl::vendor::xilinx::graphics::image_grid::is_done_barrier () inline
Test if the window has been closed after synchronizing with a barrier accross all the tiles.
Definition at line 578 of file graphics.hpp.
{
    // Only 1 thread sample the graphics status
    if (done_has_been_sampled.test_and_set())
      done_snapshot = done;
    // Then wait for everybody to synchronize
    done_barrier.count_down_and_wait();
    // Reinitialize the flag for the next iteration
    done_has_been_sampled.clear();
    return done_snapshot;
  }
References trisycl::vendor::xilinx::graphics::frame_grid::done, done_barrier, done_has_been_sampled, and done_snapshot.
on_key_press_event() [1/2]
bool trisycl::vendor::xilinx::graphics::image_grid::on_key_press_event (GdkEventKey * event) inline override
Deal with the key pressed.
Definition at line 467 of file graphics.hpp.
{
    // Forward to the palette for action
    return p.handle_key_press_event(*event);
  }
References trisycl::vendor::xilinx::graphics::palette::handle_key_press_event(), and p.
on_key_press_event() [2/2]
bool trisycl::vendor::xilinx::graphics::image_grid::on_key_press_event (GdkEventKey * event) inline override
Deal with the key pressed.
Definition at line 467 of file graphics.hpp.
{
    // Forward to the palette for action
    return p.handle_key_press_event(*event);
  }
References trisycl::vendor::xilinx::graphics::palette::handle_key_press_event(), and p.
submit() [1/2]
void trisycl::vendor::xilinx::graphics::image_grid::submit (std::function< void(void)> f) inline
Submit some work to the graphics thread.
Definition at line 473 of file graphics.hpp.
{
    std::unique_lock lock { dispatch_protection };
    // Wait for no work being dispatched or the end
    cv.wait(lock, [&] { return !work_to_dispatch || done; } );
    // Do not submit anything if we are in the shutdown process already
    if (!done) {
      work_to_dispatch = std::move(f);
      // Ask the graphics thread for some work
      dispatcher.emit();
    }
  };
References cv, dispatch_protection, dispatcher, trisycl::vendor::xilinx::graphics::frame_grid::done, and work_to_dispatch.
Referenced by update_tile_data_image().
submit() [2/2]
void trisycl::vendor::xilinx::graphics::image_grid::submit (std::function< void(void)> f) inline
Submit some work to the graphics thread.
Definition at line 473 of file graphics.hpp.
{
    std::unique_lock lock { dispatch_protection };
    // Wait for no work being dispatched or the end
    cv.wait(lock, [&] { return !work_to_dispatch || done; } );
    // Do not submit anything if we are in the shutdown process already
    if (!done) {
      work_to_dispatch = std::move(f);
      // Ask the graphics thread for some work
      dispatcher.emit();
    }
  };
References cv, dispatch_protection, dispatcher, trisycl::vendor::xilinx::graphics::frame_grid::done, and work_to_dispatch.
update_tile_data_image() [1/4]
template<typename DataType , typename RangeValue > void trisycl::vendor::xilinx::graphics::image_grid::update_tile_data_image (int x, int y, const DataType * data, RangeValue min_value, RangeValue max_value) inline
Update the image of a tile of size image_y by image_x from a pointer.
Parameters
[in] x is the tile horizontal id
[in] y is the tile vertical id
[in] data is a pointer to the pixels to be drawns
[in] min_value is the value represented with minimum of graphics palette color
[in] max_value is the value represented with maximum of graphics palette color
Definition at line 560 of file graphics.hpp.
{
    // Wrap the pointed area into an MDspan
    const std::mdspan md { data, image_y, image_x };
    update_tile_data_image(x, y, md, min_value, max_value);
  }
References image_x, image_y, update_tile_data_image(), x, and trisycl::y.
update_tile_data_image() [2/4]
template<typename DataType , typename RangeValue > void trisycl::vendor::xilinx::graphics::image_grid::update_tile_data_image (int x, int y, const DataType * data, RangeValue min_value, RangeValue max_value) inline
Update the image of a tile of size image_y by image_x from a pointer.
Parameters
[in] x is the tile horizontal id
[in] y is the tile vertical id
[in] data is a pointer to the pixels to be drawns
[in] min_value is the value represented with minimum of graphics palette color
[in] max_value is the value represented with maximum of graphics palette color
Definition at line 560 of file graphics.hpp.
{
    // Wrap the pointed area into an MDspan
    const std::mdspan md { data, image_y, image_x };
    update_tile_data_image(x, y, md, min_value, max_value);
  }
References image_x, image_y, update_tile_data_image(), x, and trisycl::y.
update_tile_data_image() [3/4]
template<typename MDspan , typename RangeValue , typename = typename MDspan::extents_type> void trisycl::vendor::xilinx::graphics::image_grid::update_tile_data_image (int x, int y, const MDspan & data, RangeValue min_value, RangeValue max_value) inline
Update the image of a tile.
Parameters
[in] x is the tile horizontal id
[in] y is the tile vertical id
[in] data is a 2D MDspan of extent at most image_y by image_x. Only the pixels of the extents are drawn
[in] min_value is the value represented with minimum of graphics palette color
[in] max_value is the value represented with maximum of graphics palette color
Definition at line 506 of file graphics.hpp.
{
    /* Painful: first I cannot use a std::unique_ptr because the
       std::function below needs to be copy-constructible, then the
       std::make_shared taking an array size comes only in C++20 while
       it is available for std::make_unique in C++17... */
    std::shared_ptr<std::uint8_t[]> d { new std::uint8_t[3*image_x*image_y] };
    std::mdspan output { reinterpret_cast<rgb*>(d.get()), image_y, image_x };
    // For each pixel of the md_span or of the image, which one is smaller
    for (int j = 0; j < std::min(static_cast<int>(data.extent(0)), image_y);
         ++j)
      for (int i = 0; i < std::min(static_cast<int>(data.extent(1)), image_x);
           ++i) {
        /* Mirror the image vertically to display the pixels in a
           mathematical sense */
        output[image_y - 1 - j, i] =
            p.palettize(data[j, i], min_value, max_value);
      }
    // Send the graphics updating code
    submit([=, this] {
        // Create a first buffer, allowing later zooming
        auto pb = Gdk::Pixbuf::create_from_data(d.get()
                                              , Gdk::Colorspace::COLORSPACE_RGB
                                              , false//< has_alpha
                                              , 8 //< bits_per_sample
                                              , image_x //< width
                                              , image_y //< height
                                              , image_x*3 //< rowstride
                                            );
        // Update the pixel buffer of the image with some zooming
        images.at(x + nx*y).set(pb->scale_simple(image_x*zoom,
                                                 image_y*zoom,
                                                 Gdk::INTERP_NEAREST));
      });
  }
References i, image_x, image_y, images, trisycl::vendor::xilinx::graphics::frame_grid::nx, p, trisycl::vendor::xilinx::graphics::palette::palettize(), submit(), x, trisycl::y, and zoom.
Referenced by update_tile_data_image().
update_tile_data_image() [4/4]
template<typename MDspan , typename RangeValue , typename = typename MDspan::extents_type> void trisycl::vendor::xilinx::graphics::image_grid::update_tile_data_image (int x, int y, const MDspan & data, RangeValue min_value, RangeValue max_value) inline
Update the image of a tile.
Parameters
[in] x is the tile horizontal id
[in] y is the tile vertical id
[in] data is a 2D MDspan of extent at most image_y by image_x. Only the pixels of the extents are drawn
[in] min_value is the value represented with minimum of graphics palette color
[in] max_value is the value represented with maximum of graphics palette color
Definition at line 506 of file graphics.hpp.
{
    /* Painful: first I cannot use a std::unique_ptr because the
       std::function below needs to be copy-constructible, then the
       std::make_shared taking an array size comes only in C++20 while
       it is available for std::make_unique in C++17... */
    std::shared_ptr<std::uint8_t[]> d { new std::uint8_t[3*image_x*image_y] };
    std::mdspan output { reinterpret_cast<rgb*>(d.get()), image_y, image_x };
    // For each pixel of the md_span or of the image, which one is smaller
    for (int j = 0; j < std::min(static_cast<int>(data.extent(0)), image_y);
         ++j)
      for (int i = 0; i < std::min(static_cast<int>(data.extent(1)), image_x);
           ++i) {
        /* Mirror the image vertically to display the pixels in a
           mathematical sense */
        output[image_y - 1 - j, i] =
            p.palettize(data[j, i], min_value, max_value);
      }
    // Send the graphics updating code
    submit([=, this] {
        // Create a first buffer, allowing later zooming
        auto pb = Gdk::Pixbuf::create_from_data(d.get()
                                              , Gdk::Colorspace::COLORSPACE_RGB
                                              , false//< has_alpha
                                              , 8 //< bits_per_sample
                                              , image_x //< width
                                              , image_y //< height
                                              , image_x*3 //< rowstride
                                            );
        // Update the pixel buffer of the image with some zooming
        images.at(x + nx*y).set(pb->scale_simple(image_x*zoom,
                                                 image_y*zoom,
                                                 Gdk::INTERP_NEAREST));
      });
  }
References i, image_x, image_y, images, trisycl::vendor::xilinx::graphics::frame_grid::nx, p, trisycl::vendor::xilinx::graphics::palette::palettize(), submit(), x, trisycl::y, and zoom.
Member Data Documentation
cv
std::condition_variable trisycl::vendor::xilinx::graphics::image_grid::cv
The condition variable used to queue up graphics update submission.
Definition at line 392 of file graphics.hpp.
Referenced by image_grid(), and submit().
dispatch_protection
std::mutex trisycl::vendor::xilinx::graphics::image_grid::dispatch_protection
Protection against concurrent update.
Definition at line 389 of file graphics.hpp.
Referenced by image_grid(), and submit().
dispatcher
Glib::Dispatcher trisycl::vendor::xilinx::graphics::image_grid::dispatcher
Dispatcher to invoke something in the graphics thread in a safe way.
Definition at line 386 of file graphics.hpp.
Referenced by image_grid(), and submit().
done_barrier
boost::barrier trisycl::vendor::xilinx::graphics::image_grid::done_barrier { static_cast<unsigned int>(nx*ny) }
Barrier to compute the global done state across the tiles.
Definition at line 407 of file graphics.hpp.
Referenced by is_done_barrier().
done_has_been_sampled
std::atomic_flag trisycl::vendor::xilinx::graphics::image_grid::done_has_been_sampled
Set to true once "done" state has been sampled.
Definition at line 404 of file graphics.hpp.
Referenced by is_done_barrier().
done_snapshot
bool trisycl::vendor::xilinx::graphics::image_grid::done_snapshot
A global done state across all the tile to allow a global shutdown.
Definition at line 401 of file graphics.hpp.
Referenced by is_done_barrier().
image_x
int trisycl::vendor::xilinx::graphics::image_grid::image_x
Horizontal image size in pixels.
Definition at line 377 of file graphics.hpp.
Referenced by image_grid(), and update_tile_data_image().
image_y
int trisycl::vendor::xilinx::graphics::image_grid::image_y
Vertical image size in pixels.
Definition at line 380 of file graphics.hpp.
Referenced by image_grid(), and update_tile_data_image().
images
std::vector< Gtk::Image > trisycl::vendor::xilinx::graphics::image_grid::images
The linearized 2D vector of images.
Definition at line 374 of file graphics.hpp.
Referenced by image_grid(), and update_tile_data_image().
p
palette trisycl::vendor::xilinx::graphics::image_grid::p
The RGB palette used to render the image values.
Definition at line 398 of file graphics.hpp.
Referenced by get_palette(), on_key_press_event(), and update_tile_data_image().
work_to_dispatch
std::function< void(void)> trisycl::vendor::xilinx::graphics::image_grid::work_to_dispatch
What to dispatch.
Definition at line 395 of file graphics.hpp.
Referenced by image_grid(), and submit().
zoom
int trisycl::vendor::xilinx::graphics::image_grid::zoom
The image pixel zooming factor for both dimension.
Definition at line 383 of file graphics.hpp.
Referenced by image_grid(), and update_tile_data_image().
The documentation for this struct was generated from the following files:
include/sycl/vendor/Xilinx/graphics.hpp
include/triSYCL/vendor/Xilinx/graphics.hpp