triSYCL implementation of OpenCL SYCL: cl::sycl::detail::buffer_base Struct Reference
cl::sycl::detail::buffer_base Struct Reference
Factorize some template independent buffer aspects in a base class.
#include <buffer_base.hpp>
Public Member Functions
buffer_base (bool read_only)
Create a buffer base.
~buffer_base ()
The destructor wait for not being used anymore.
void wait ()
Wait for this buffer to be ready, which is no longer in use.
void use ()
Mark this buffer in use by a task.
void release ()
A task has released the buffer.
std::shared_ptr< detail::task > get_latest_producer ()
Return the latest producer for the buffer.
std::shared_ptr< detail::task > set_latest_producer (std::weak_ptr< detail::task > newer_latest_producer)
Return the latest producer for the buffer and set another future producer.
std::shared_ptr< detail::task > add_to_task (handler *command_group_handler, bool is_write_mode)
Add a buffer to the task running the command group.
Public Attributes
bool read_only
If the data are read-only, store the information for later optimization.
std::atomic< size_t > number_of_users
std::weak_ptr< detail::task > latest_producer
Track the latest task to produce this buffer.
std::mutex latest_producer_mutex
To protect the access to latest_producer.
std::condition_variable ready
To signal when this buffer ready.
std::mutex ready_mutex
To protect the access to the condition variable.
boost::optional< std::promise< void > > notify_buffer_destructor
If the SYCL user buffer destructor is blocking, use this to block until this buffer implementation is destroyed.
Detailed Description
Factorize some template independent buffer aspects in a base class.
Definition at line 41 of file buffer_base.hpp.
Constructor & Destructor Documentation
cl::sycl::detail::buffer_base::buffer_base (bool read_only) inline
Create a buffer base.
Definition at line 68 of file buffer_base.hpp.
                               : read_only { read_only },
                                 number_of_users { 0 } {}
cl::sycl::detail::buffer_base::~buffer_base () inline
The destructor wait for not being used anymore.
Definition at line 73 of file buffer_base.hpp.
References wait().
                  {
     wait();
     // If there is the last SYCL user buffer waiting, notify it
     if (notify_buffer_destructor)
       notify_buffer_destructor->set_value();
   }
Member Function Documentation
std::shared_ptr<detail::task> cl::sycl::detail::buffer_base::add_to_task (handler * command_group_handler, bool is_write_mode) inline
Add a buffer to the task running the command group.
Definition at line 130 of file buffer_base.hpp.
References cl::sycl::detail::add_buffer_to_task().
{
     return add_buffer_to_task(command_group_handler,
                               shared_from_this(),
                               is_write_mode);
   }
std::shared_ptr<detail::task> cl::sycl::detail::buffer_base::get_latest_producer () inline
Return the latest producer for the buffer.
Definition at line 107 of file buffer_base.hpp.
{
     std::lock_guard<std::mutex> lg { latest_producer_mutex };
     // Return the valid shared_ptr to the task, if any
     return latest_producer.lock();
   }
void cl::sycl::detail::buffer_base::release () inline
A task has released the buffer.
Definition at line 99 of file buffer_base.hpp.
                  {
     if (--number_of_users == 0)
       // Notify the host consumers or the buffer destructor that it is ready
       ready.notify_all();
   }
std::shared_ptr<detail::task> cl::sycl::detail::buffer_base::set_latest_producer (std::weak_ptr< detail::task > newer_latest_producer) inline
Return the latest producer for the buffer and set another future producer.
Definition at line 118 of file buffer_base.hpp.
{
     std::lock_guard<std::mutex> lg { latest_producer_mutex };
     using std::swap;
     swap(newer_latest_producer, latest_producer);
     // Return the valid shared_ptr to the previous producing task, if any
     return newer_latest_producer.lock();
   }
void cl::sycl::detail::buffer_base::use () inline
Mark this buffer in use by a task.
Definition at line 92 of file buffer_base.hpp.
References number_of_users.
              {
     // Increment the use count
     ++number_of_users;
   }
void cl::sycl::detail::buffer_base::wait () inline
Wait for this buffer to be ready, which is no longer in use.
Definition at line 82 of file buffer_base.hpp.
Referenced by ~buffer_base().
               {
     std::unique_lock<std::mutex> ul { ready_mutex };
     ready.wait(ul, [&] {
         // When there is no producer for this buffer, we are ready to use it
         return number_of_users == 0;
       });
   }
Member Data Documentation
std::weak_ptr<detail::task> cl::sycl::detail::buffer_base::latest_producer
Track the latest task to produce this buffer.
Definition at line 50 of file buffer_base.hpp.
std::mutex cl::sycl::detail::buffer_base::latest_producer_mutex
To protect the access to latest_producer.
Definition at line 52 of file buffer_base.hpp.
boost::optional<std::promise<void> > cl::sycl::detail::buffer_base::notify_buffer_destructor
If the SYCL user buffer destructor is blocking, use this to block until this buffer implementation is destroyed.
Use a void promise since there is no value to send, only waiting
Definition at line 64 of file buffer_base.hpp.
Referenced by cl::sycl::detail::buffer< T, Dimensions >::get_destructor_future().
std::atomic<size_t> cl::sycl::detail::buffer_base::number_of_users
Definition at line 47 of file buffer_base.hpp.
Referenced by use().
bool cl::sycl::detail::buffer_base::read_only
If the data are read-only, store the information for later optimization.
Todo:
Replace this by a static read-only type for the buffer
Definition at line 44 of file buffer_base.hpp.
std::condition_variable cl::sycl::detail::buffer_base::ready
To signal when this buffer ready.
Definition at line 55 of file buffer_base.hpp.
std::mutex cl::sycl::detail::buffer_base::ready_mutex
To protect the access to the condition variable.
Definition at line 57 of file buffer_base.hpp.
The documentation for this struct was generated from the following file:
include/CL/sycl/buffer/detail/buffer_base.hpp