triSYCL implementation of SYCL: trisycl::vendor::trisycl::random::xorshift< Nbits > Struct Template Reference
trisycl::vendor::trisycl::random::xorshift< Nbits > Struct Template Reference
A possible implementation of the xorshift RNGs from.
#include <xorshift.hpp>
Public Types
using value_type = std::remove_const_t< decltype(initial_state)>
The type of the internal state of the generator.
using result_type = value_type
The type of the result.
using value_type = std::remove_const_t< decltype(initial_state)>
The type of the internal state of the generator.
using result_type = value_type
The type of the result.
Public Member Functions
xorshift (const value_type &s)
Initialize the internal state from a user-given value.
xorshift ()=default
const result_type & operator() ()
Compute a new pseudo random integer.
xorshift (const value_type &s)
Initialize the internal state from a user-given value.
xorshift ()=default
const result_type & operator() ()
Compute a new pseudo random integer.
Static Public Member Functions
static auto constexpr min ()
The minimum returned value.
static auto constexpr max ()
The maximum returned value.
static auto constexpr min ()
The minimum returned value.
static auto constexpr max ()
The maximum returned value.
Public Attributes
value_type state = initial_state
The internal state of the pseudo random generator.
Static Public Attributes
static auto constexpr bit_size = Nbits
Bit size of the random generator data type.
static auto constexpr initial_state
The default initial internal state of the pseudo random generator.
Detailed Description
template<int Nbits = 32>
struct trisycl::vendor::trisycl::random::xorshift< Nbits >
A possible implementation of the xorshift RNGs from.
Marsaglia, George (July 2003). "Xorshift RNGs". Journal of Statistical Software. 8 (14). doi:10.18637/jss.v008.i14
Panneton, François; L'Écuyer, Pierre (October 2005). "On the xorshift random number generators" (PDF). ACM Transactions on Modeling and Computer Simulation. 15 (4):346–361. doi:10.1145/1113316.1113319
Definition at line 34 of file xorshift.hpp.
Member Typedef Documentation
result_type [1/2]
template<int Nbits = 32> using trisycl::vendor::trisycl::random::xorshift< Nbits >::result_type = value_type
The type of the result.
Definition at line 60 of file xorshift.hpp.
result_type [2/2]
template<int Nbits = 32> using trisycl::vendor::trisycl::random::xorshift< Nbits >::result_type = value_type
The type of the result.
Definition at line 60 of file xorshift.hpp.
value_type [1/2]
template<int Nbits = 32> using trisycl::vendor::trisycl::random::xorshift< Nbits >::value_type = std::remove_const_t<decltype(initial_state)>
The type of the internal state of the generator.
Definition at line 57 of file xorshift.hpp.
value_type [2/2]
template<int Nbits = 32> using trisycl::vendor::trisycl::random::xorshift< Nbits >::value_type = std::remove_const_t<decltype(initial_state)>
The type of the internal state of the generator.
Definition at line 57 of file xorshift.hpp.
Constructor & Destructor Documentation
xorshift() [1/4]
template<int Nbits = 32> trisycl::vendor::trisycl::random::xorshift< Nbits >::xorshift (const value_type & s) inline
Initialize the internal state from a user-given value.
Do not use the value 0 or the output is always 0
Definition at line 86 of file xorshift.hpp.
    : state { s }
  {}
xorshift() [2/4]
template<int Nbits = 32> trisycl::vendor::trisycl::random::xorshift< Nbits >::xorshift () default
xorshift() [3/4]
template<int Nbits = 32> trisycl::vendor::trisycl::random::xorshift< Nbits >::xorshift (const value_type & s) inline
Initialize the internal state from a user-given value.
Do not use the value 0 or the output is always 0
Definition at line 86 of file xorshift.hpp.
    : state { s }
  {}
xorshift() [4/4]
template<int Nbits = 32> trisycl::vendor::trisycl::random::xorshift< Nbits >::xorshift () default
Member Function Documentation
max() [1/2]
template<int Nbits = 32> static auto constexpr trisycl::vendor::trisycl::random::xorshift< Nbits >::max () inline static constexpr
The maximum returned value.
Definition at line 77 of file xorshift.hpp.
{
    return std::numeric_limits<result_type>::max();
  };
References trisycl::max().
max() [2/2]
template<int Nbits = 32> static auto constexpr trisycl::vendor::trisycl::random::xorshift< Nbits >::max () inline static constexpr
The maximum returned value.
Definition at line 77 of file xorshift.hpp.
{
    return std::numeric_limits<result_type>::max();
  };
References trisycl::max().
min() [1/2]
template<int Nbits = 32> static auto constexpr trisycl::vendor::trisycl::random::xorshift< Nbits >::min () inline static constexpr
The minimum returned value.
Definition at line 70 of file xorshift.hpp.
{
    // It cannot return 0
    return std::numeric_limits<result_type>::min() + 1;
  };
References trisycl::min().
min() [2/2]
template<int Nbits = 32> static auto constexpr trisycl::vendor::trisycl::random::xorshift< Nbits >::min () inline static constexpr
The minimum returned value.
Definition at line 70 of file xorshift.hpp.
{
    // It cannot return 0
    return std::numeric_limits<result_type>::min() + 1;
  };
References trisycl::min().
operator()() [1/2]
template<int Nbits = 32> const result_type & trisycl::vendor::trisycl::random::xorshift< Nbits >::operator() () inline
Compute a new pseudo random integer.
Definition at line 95 of file xorshift.hpp.
{
    if constexpr (bit_size == 32) {
      /* Pick the one of type "I" with best bit equidistribution from
         Panneton & L'Écuyer, Section "5.1 Equidistribution
         properties"
         X4 = (I + Ra )(I + Lb )(I + Rc )
      */
      state ^= state >> 7;
      state ^= state << 1;
      state ^= state >> 9;
    }
    else if constexpr (bit_size == 64) {
      /* The xor64 from Marsaglia, p. 4 Section "3 Application to
         Xorshift RNGs" */
      state ^= state << 13;
      state ^= state >> 7;
      state ^= state << 17;
    }
    else if constexpr (bit_size == 128) {
      // The xor128 from Marsaglia, p. 5 Section "4 Summary"
      auto t = state[0]^(state[0]<<11);
      state[0] = state[1];
      state[1] = state[2];
      state[2] = state[3];
      state[3] = state[3]^(state[3]>>19)^(t^(t>>8));
    }
    else
      // Just to error in that case
      return nullptr;
    return state;
  }
References trisycl::vendor::trisycl::random::xorshift< Nbits >::bit_size, and trisycl::vendor::trisycl::random::xorshift< Nbits >::state.
operator()() [2/2]
template<int Nbits = 32> const result_type & trisycl::vendor::trisycl::random::xorshift< Nbits >::operator() () inline
Compute a new pseudo random integer.
Definition at line 95 of file xorshift.hpp.
{
    if constexpr (bit_size == 32) {
      /* Pick the one of type "I" with best bit equidistribution from
         Panneton & L'Écuyer, Section "5.1 Equidistribution
         properties"
         X4 = (I + Ra )(I + Lb )(I + Rc )
      */
      state ^= state >> 7;
      state ^= state << 1;
      state ^= state >> 9;
    }
    else if constexpr (bit_size == 64) {
      /* The xor64 from Marsaglia, p. 4 Section "3 Application to
         Xorshift RNGs" */
      state ^= state << 13;
      state ^= state >> 7;
      state ^= state << 17;
    }
    else if constexpr (bit_size == 128) {
      // The xor128 from Marsaglia, p. 5 Section "4 Summary"
      auto t = state[0]^(state[0]<<11);
      state[0] = state[1];
      state[1] = state[2];
      state[2] = state[3];
      state[3] = state[3]^(state[3]>>19)^(t^(t>>8));
    }
    else
      // Just to error in that case
      return nullptr;
    return state;
  }
References trisycl::vendor::trisycl::random::xorshift< Nbits >::bit_size, and trisycl::vendor::trisycl::random::xorshift< Nbits >::state.
Member Data Documentation
bit_size
template<int Nbits = 32> static auto constexpr trisycl::vendor::trisycl::random::xorshift< Nbits >::bit_size = Nbits static constexpr
Bit size of the random generator data type.
Definition at line 36 of file xorshift.hpp.
Referenced by trisycl::vendor::trisycl::random::xorshift< Nbits >::operator()().
initial_state
template<int Nbits = 32> static auto constexpr trisycl::vendor::trisycl::random::xorshift< Nbits >::initial_state static constexpr
Initial value:
= [] {
    if constexpr (bit_size == 32) {
      return std::uint32_t { 2463534242 };
    } else if constexpr (bit_size == 64) {
      return std::uint64_t { 88172645463325252 };
    } else if constexpr (bit_size == 128) {
      return std::array<std::uint32_t, 4>
        { 123456789, 362436069, 521288629, 88675123 };
    } else
      return nullptr;
  }()
The default initial internal state of the pseudo random generator.
Definition at line 39 of file xorshift.hpp.
state
template<int Nbits = 32> value_type trisycl::vendor::trisycl::random::xorshift< Nbits >::state = initial_state
The internal state of the pseudo random generator.
Definition at line 66 of file xorshift.hpp.
Referenced by trisycl::vendor::trisycl::random::xorshift< Nbits >::operator()().
The documentation for this struct was generated from the following files:
include/sycl/vendor/triSYCL/random/xorshift.hpp
include/triSYCL/vendor/triSYCL/random/xorshift.hpp