triSYCL implementation of SYCL: trisycl::detail::queue Struct Reference
trisycl::detail::queue Struct Reference abstract
Some implementation details about the SYCL queue.
#include <queue.hpp>
Public Member Functions
queue ()
Initialize the queue with 0 running kernel.
void wait_for_kernel_execution ()
Wait for all kernel completion.
void kernel_start ()
Signal that a new kernel started on this queue.
void kernel_end ()
Signal that a new kernel finished on this queue.
virtual cl_command_queue get () const =0
Return the underlying OpenCL command queue after doing a retain.
virtual boost::compute::command_queue & get_boost_compute ()=0
Return the underlying Boost.Compute command queue.
virtual trisycl::context get_context () const =0
Return the SYCL queue's context.
virtual trisycl::device get_device () const =0
Return the SYCL device the queue is associated with.
virtual bool is_host () const =0
Return whether the queue is executing on a SYCL host device.
virtual ~queue ()
Wait for all kernel completion before the queue destruction.
Public Attributes
std::atomic< size_t > running_kernels
Track the number of kernels still running to wait for their completion.
std::condition_variable finished
To signal when all the kernels have completed.
std::mutex finished_mutex
To protect the access to the condition variable.
Detailed Description
Some implementation details about the SYCL queue.
Definition at line 28 of file queue.hpp.
Constructor & Destructor Documentation
queue()
trisycl::detail::queue::queue () inline
Initialize the queue with 0 running kernel.
Definition at line 39 of file queue.hpp.
 : running_kernels { 0 } {}
~queue()
virtual trisycl::detail::queue::~queue () inline virtual
Wait for all kernel completion before the queue destruction.
Todo:
Update according spec since queue destruction is non blocking
Definition at line 118 of file queue.hpp.
References wait_for_kernel_execution().
                    {
     wait_for_kernel_execution();
   }
Member Function Documentation
get()
virtual cl_command_queue trisycl::detail::queue::get () const pure virtual
Return the underlying OpenCL command queue after doing a retain.
This memory object is expected to be released by the developer.
Retain a reference to the returned cl_command_queue object.
Caller should release it when finished.
If the queue is a SYCL host queue then an exception is thrown.
Implemented in trisycl::detail::host_queue, and trisycl::detail::opencl_queue.
get_boost_compute()
virtual boost::compute::command_queue& trisycl::detail::queue::get_boost_compute () pure virtual
Return the underlying Boost.Compute command queue.
Implemented in trisycl::detail::host_queue, and trisycl::detail::opencl_queue.
Referenced by kernel_end().
get_context()
virtual trisycl::context trisycl::detail::queue::get_context () const pure virtual
Return the SYCL queue's context.
Report errors using SYCL exception classes.
Implemented in trisycl::detail::host_queue, and trisycl::detail::opencl_queue.
Referenced by kernel_end().
get_device()
virtual trisycl::device trisycl::detail::queue::get_device () const pure virtual
Return the SYCL device the queue is associated with.
Report errors using SYCL exception classes.
Implemented in trisycl::detail::host_queue, and trisycl::detail::opencl_queue.
Referenced by kernel_end().
is_host()
virtual bool trisycl::detail::queue::is_host () const pure virtual
Return whether the queue is executing on a SYCL host device.
Implemented in trisycl::detail::host_queue, and trisycl::detail::opencl_queue.
Referenced by kernel_end().
kernel_end()
void trisycl::detail::queue::kernel_end () inline
Signal that a new kernel finished on this queue.
Definition at line 61 of file queue.hpp.
References get_boost_compute(), get_context(), get_device(), is_host(), and TRISYCL_DUMP_T.
                     {
     TRISYCL_DUMP_T("A kernel of the queue ended");
     std::unique_lock<std::mutex> ul { finished_mutex };
     if (--running_kernels == 0) {
       // Micro-optimization: unlock before the notification
       // https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all
       ul.unlock();
       /* It was the last kernel running, so signal the queue just in
          case it was working for it for completion
          In some cases several threads might want to wait for the
          same queue, because of this \c notify_one is not be enough
          and a \c notify_all is needed
       */
       finished.notify_all();
     }
   }
kernel_start()
void trisycl::detail::queue::kernel_start () inline
Signal that a new kernel started on this queue.
Definition at line 53 of file queue.hpp.
References running_kernels, and TRISYCL_DUMP_T.
                       {
     TRISYCL_DUMP_T("A kernel has been added to the queue");
     // One more kernel
     ++running_kernels;
   }
wait_for_kernel_execution()
void trisycl::detail::queue::wait_for_kernel_execution () inline
Wait for all kernel completion.
Definition at line 42 of file queue.hpp.
References TRISYCL_DUMP_T.
Referenced by ~queue().
{
     TRISYCL_DUMP_T("Queue waiting for kernel completion");
     std::unique_lock<std::mutex> ul { finished_mutex };
     finished.wait(ul, [&] {
         // When there is no kernel running in this queue, we are ready to go
         return running_kernels == 0;
       });
   }
Member Data Documentation
finished
std::condition_variable trisycl::detail::queue::finished
To signal when all the kernels have completed.
Definition at line 33 of file queue.hpp.
finished_mutex
std::mutex trisycl::detail::queue::finished_mutex
To protect the access to the condition variable.
Definition at line 35 of file queue.hpp.
running_kernels
std::atomic<size_t> trisycl::detail::queue::running_kernels
Track the number of kernels still running to wait for their completion.
Definition at line 30 of file queue.hpp.
Referenced by kernel_start().
The documentation for this struct was generated from the following file:
include/triSYCL/queue/detail/queue.hpp