triSYCL implementation of SYCL: trisycl::vendor::xilinx::acap::aie::detail::device< Layout > Struct Template Reference
trisycl::vendor::xilinx::acap::aie::detail::device< Layout > Struct Template Reference
Create a SYCL-like device view of an AI Engine CGRA with some layout.
#include <device.hpp>
Public Types
using geo = geography< Layout >
The geography of the CGRA.
using cass = typename geo::core_axi_stream_switch
Naming shortcut for the core AXI stream switch.
using csp = typename cass::slave_port_layout
Naming shortcut for the slave ports of the core AXI stream switch.
using cmp = typename cass::master_port_layout
Naming shortcut for the master ports of the core AXI stream switch.
using sass = typename geo::shim_axi_stream_switch
Naming shortcut for the shim AXI stream switch.
using ssp = typename sass::slave_port_layout
Naming shortcut for the slave ports of the shim AXI stream switch.
using smp = typename sass::master_port_layout
Naming shortcut for the master ports of the shim AXI stream switch.
using geo = geography< Layout >
The geography of the CGRA.
using cass = typename geo::core_axi_stream_switch
Naming shortcut for the core AXI stream switch.
using csp = typename cass::slave_port_layout
Naming shortcut for the slave ports of the core AXI stream switch.
using cmp = typename cass::master_port_layout
Naming shortcut for the master ports of the core AXI stream switch.
using sass = typename geo::shim_axi_stream_switch
Naming shortcut for the shim AXI stream switch.
using ssp = typename sass::slave_port_layout
Naming shortcut for the slave ports of the shim AXI stream switch.
using smp = typename sass::master_port_layout
Naming shortcut for the master ports of the shim AXI stream switch.
Public Member Functions
auto & tile (int x, int y)
Access to the common infrastructure part of a tile.
template<typename F >
void for_each_tile_index (F &&f)
Apply a function for each tile index of the device.
template<typename F >
void for_each_tile (F &&f)
Apply a function for each tile infrastructure of the device.
template<typename F >
void for_each_tile_x_index (F &&f)
Apply a function for each x tile index of the device.
template<typename F >
void for_each_tile_y_index (F &&f)
Apply a function for each y tile index of the device.
auto & mem (int x, int y)
Shortcut to access to the common infrastructure part of a tile memory.
auto & shim (int x)
Access to the shim tile.
auto & cascade ()
Access the cascade connections.
template<typename SrcPort , typename DstPort >
void connect (SrcPort &&src, DstPort &&dst)
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
template<typename F >
void for_each_tile_neighborhood (F &&f)
Apply a function on all the AXI stream of the neighborhood of each tile.
device ()
Build some device level infrastructure.
auto display (const std::string &file_name={})
Display the device layout.
auto & tile (int x, int y)
Access to the common infrastructure part of a tile.
template<typename F >
void for_each_tile_index (F &&f)
Apply a function for each tile index of the device.
template<typename F >
void for_each_tile (F &&f)
Apply a function for each tile infrastructure of the device.
template<typename F >
void for_each_tile_x_index (F &&f)
Apply a function for each x tile index of the device.
template<typename F >
void for_each_tile_y_index (F &&f)
Apply a function for each y tile index of the device.
auto & mem (int x, int y)
Shortcut to access to the common infrastructure part of a tile memory.
auto & shim (int x)
Access to the shim tile.
auto & cascade ()
Access the cascade connections.
template<typename SrcPort , typename DstPort >
void connect (SrcPort &&src, DstPort &&dst)
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
template<typename F >
void for_each_tile_neighborhood (F &&f)
Apply a function on all the AXI stream of the neighborhood of each tile.
device ()
Build some device level infrastructure.
auto display (const std::string &file_name={})
Display the device layout.
Public Attributes
cascade_stream< geo > cs
The cascade stream infrastructure of the CGRA.
::trisycl::detail::fiber_pool fiber_executor
A fiber pool executor to run the infrastructure powered by TRISYCL_XILINX_AIE_FIBER_EXECUTOR_THREADS std::thread.
aie::tile_infrastructure< geo > ti [geo::y_size][geo::x_size]
Keep track of all the (non detail) infrastructure tiles of this device.
shim_tile< device > shims [geo::x_size]
The shim tiles on the lower row of the tile array.
Detailed Description
template<typename Layout>
struct trisycl::vendor::xilinx::acap::aie::detail::device< Layout >
Create a SYCL-like device view of an AI Engine CGRA with some layout.
Parameters
Layout is the layout description of the machine to instantiate with the physical size
Definition at line 41 of file device.hpp.
Member Typedef Documentation
cass [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cass = typename geo::core_axi_stream_switch
Naming shortcut for the core AXI stream switch.
Definition at line 47 of file device.hpp.
cass [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cass = typename geo::core_axi_stream_switch
Naming shortcut for the core AXI stream switch.
Definition at line 47 of file device.hpp.
cmp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cmp = typename cass::master_port_layout
Naming shortcut for the master ports of the core AXI stream switch.
Definition at line 53 of file device.hpp.
cmp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cmp = typename cass::master_port_layout
Naming shortcut for the master ports of the core AXI stream switch.
Definition at line 53 of file device.hpp.
csp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::csp = typename cass::slave_port_layout
Naming shortcut for the slave ports of the core AXI stream switch.
Definition at line 50 of file device.hpp.
csp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::csp = typename cass::slave_port_layout
Naming shortcut for the slave ports of the core AXI stream switch.
Definition at line 50 of file device.hpp.
geo [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::geo = geography<Layout>
The geography of the CGRA.
Definition at line 44 of file device.hpp.
geo [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::geo = geography<Layout>
The geography of the CGRA.
Definition at line 44 of file device.hpp.
sass [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::sass = typename geo::shim_axi_stream_switch
Naming shortcut for the shim AXI stream switch.
Definition at line 56 of file device.hpp.
sass [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::sass = typename geo::shim_axi_stream_switch
Naming shortcut for the shim AXI stream switch.
Definition at line 56 of file device.hpp.
smp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::smp = typename sass::master_port_layout
Naming shortcut for the master ports of the shim AXI stream switch.
Definition at line 62 of file device.hpp.
smp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::smp = typename sass::master_port_layout
Naming shortcut for the master ports of the shim AXI stream switch.
Definition at line 62 of file device.hpp.
ssp [1/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::ssp = typename sass::slave_port_layout
Naming shortcut for the slave ports of the shim AXI stream switch.
Definition at line 59 of file device.hpp.
ssp [2/2]
template<typename Layout > using trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::ssp = typename sass::slave_port_layout
Naming shortcut for the slave ports of the shim AXI stream switch.
Definition at line 59 of file device.hpp.
Constructor & Destructor Documentation
device() [1/2]
template<typename Layout > trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device () inline
Build some device level infrastructure.
Make the connections around the shim tiles
Definition at line 226 of file device.hpp.
           {
    // Initialize all the tiles with their network connections first
    for_each_tile_index([&](auto x, auto y) {
      // Create & start the tile infrastructure
      tile(x, y) = { x, y, *this, fiber_executor };
    });
    for_each_tile_x_index([&](auto x) {
      // Start the shim infrastructure
      shim(x).start(x, fiber_executor);
    });
    // Only then we can connect the inter-core tile AXI stream NoC
    for_each_tile_neighborhood(
        [&](auto x, auto y, auto nx, auto ny, auto m, auto s) {
          tile(x, y).output(m) = tile(nx, ny).input(s);
        });
    /// Make the connections around the shim tiles
    for_each_tile_x_index([&](auto x) {
      // The connection from shim tile to core tile
      for (auto [o, i] :
           ranges::views::zip(sass::m_north_range, cass::s_south_range))
        shim(x).output(o) = tile(x, 0).input(i);
      // The connection from core tile to shim tile
      for (auto [o, i] :
           ranges::views::zip(cass::m_south_range, sass::s_north_range))
        tile(x, 0).output(o) = shim(x).input(i);
      if (!geo::is_east_column(x))
        for (auto [o, i] :
             ranges::views::zip(sass::m_east_range, sass::s_west_range))
          shim(x).output(o) = shim(x + 1).input(i);
      if (!geo::is_west_column(x))
        for (auto [o, i] :
             ranges::views::zip(sass::m_west_range, sass::s_east_range))
          shim(x).output(o) = shim(x - 1).input(i);
    });
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::fiber_executor, trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_neighborhood(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_x_index(), i, trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_east_column(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_west_column(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile(), x, and trisycl::y.
device() [2/2]
template<typename Layout > trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device () inline
Build some device level infrastructure.
Make the connections around the shim tiles
Definition at line 226 of file device.hpp.
           {
    // Initialize all the tiles with their network connections first
    for_each_tile_index([&](auto x, auto y) {
      // Create & start the tile infrastructure
      tile(x, y) = { x, y, *this, fiber_executor };
    });
    for_each_tile_x_index([&](auto x) {
      // Start the shim infrastructure
      shim(x).start(x, fiber_executor);
    });
    // Only then we can connect the inter-core tile AXI stream NoC
    for_each_tile_neighborhood(
        [&](auto x, auto y, auto nx, auto ny, auto m, auto s) {
          tile(x, y).output(m) = tile(nx, ny).input(s);
        });
    /// Make the connections around the shim tiles
    for_each_tile_x_index([&](auto x) {
      // The connection from shim tile to core tile
      for (auto [o, i] :
           ranges::views::zip(sass::m_north_range, cass::s_south_range))
        shim(x).output(o) = tile(x, 0).input(i);
      // The connection from core tile to shim tile
      for (auto [o, i] :
           ranges::views::zip(cass::m_south_range, sass::s_north_range))
        tile(x, 0).output(o) = shim(x).input(i);
      if (!geo::is_east_column(x))
        for (auto [o, i] :
             ranges::views::zip(sass::m_east_range, sass::s_west_range))
          shim(x).output(o) = shim(x + 1).input(i);
      if (!geo::is_west_column(x))
        for (auto [o, i] :
             ranges::views::zip(sass::m_west_range, sass::s_east_range))
          shim(x).output(o) = shim(x - 1).input(i);
    });
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::fiber_executor, trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_neighborhood(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_x_index(), i, trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_east_column(), trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_west_column(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile(), x, and trisycl::y.
Member Function Documentation
cascade() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cascade () inline
Access the cascade connections.
Todo:
To remove?
Definition at line 165 of file device.hpp.
{ return cs; }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cs.
cascade() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cascade () inline
Access the cascade connections.
Todo:
To remove?
Definition at line 165 of file device.hpp.
{ return cs; }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cs.
connect() [1/2]
template<typename Layout > template<typename SrcPort , typename DstPort > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::connect (SrcPort && src, DstPort && dst) inline
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
This is used to speed up communication in emulation and to skip the need of a routing planner.
Todo:
To deprecate and implement in another way?
Parameters
[in] T is the type of the data to be transferred
[in] SrcPort is the type of the source port, such as port::tile or port::shim
[in] DstPort is the type of the destination port, such as port::tile or port::shim
Exceptions
trisycl::runtime_error if some coordinates or port numbers are invalid
Todo:
Refactor, make the difference between user & physical ports
Definition at line 190 of file device.hpp.
{
    static_assert(std::is_same_v<SrcPort, port::tile> ||
                      std::is_same_v<SrcPort, port::shim>,
                  "SrcPort type should be port::tile or port::shim");
    static_assert(std::is_same_v<DstPort, port::tile> ||
                      std::is_same_v<DstPort, port::shim>,
                  "DstPort type should be port::tile or port::shim");
    // Get the destination in the final switch
    auto channel = [&] {
      if constexpr (std::is_same_v<DstPort, port::tile>)
        return tile(dst.x, dst.y).in_connection(dst.port);
      else if constexpr (std::is_same_v<DstPort, port::shim>)
        return shim(dst.x).bli_in_connection(dst.port);
    }();
    // And connect the source  port to it
    if constexpr (std::is_same_v<SrcPort, port::tile>)
      tile(src.x, src.y).out_connection(src.port) = channel;
    else if constexpr (std::is_same_v<SrcPort, port::shim>)
      shim(src.x).bli_out_connection(src.port) = channel;
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim(), src, and trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile().
connect() [2/2]
template<typename Layout > template<typename SrcPort , typename DstPort > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::connect (SrcPort && src, DstPort && dst) inline
Connect the ports of 2 tiles or shims together with an hyperspace switched circuit, jumping over the underlying routing infrastructure.
This is used to speed up communication in emulation and to skip the need of a routing planner.
Todo:
To deprecate and implement in another way?
Parameters
[in] T is the type of the data to be transferred
[in] SrcPort is the type of the source port, such as port::tile or port::shim
[in] DstPort is the type of the destination port, such as port::tile or port::shim
Exceptions
trisycl::runtime_error if some coordinates or port numbers are invalid
Todo:
Refactor, make the difference between user & physical ports
Definition at line 190 of file device.hpp.
{
    static_assert(std::is_same_v<SrcPort, port::tile> ||
                      std::is_same_v<SrcPort, port::shim>,
                  "SrcPort type should be port::tile or port::shim");
    static_assert(std::is_same_v<DstPort, port::tile> ||
                      std::is_same_v<DstPort, port::shim>,
                  "DstPort type should be port::tile or port::shim");
    // Get the destination in the final switch
    auto channel = [&] {
      if constexpr (std::is_same_v<DstPort, port::tile>)
        return tile(dst.x, dst.y).in_connection(dst.port);
      else if constexpr (std::is_same_v<DstPort, port::shim>)
        return shim(dst.x).bli_in_connection(dst.port);
    }();
    // And connect the source  port to it
    if constexpr (std::is_same_v<SrcPort, port::tile>)
      tile(src.x, src.y).out_connection(src.port) = channel;
    else if constexpr (std::is_same_v<SrcPort, port::shim>)
      shim(src.x).bli_out_connection(src.port) = channel;
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim(), src, and trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile().
display() [1/2]
template<typename Layout > auto trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::display (const std::string & file_name = {}) inline
Display the device layout.
Parameters
[in] file_name is the name of the file to write the LaTeX drawing into or use std::cerr by default
The LaTeX generation is handled by a LaTeX context
Definition at line 269 of file device.hpp.
                                            {}) {
    // Compute the drawing size starting with the individual tile size
    auto tile_size = tile(0, 0).display_size();
    // And expanding according to the device size. Add 1 in each
    // dimension to fit in the page because of the borders
    auto x_size = tile_size.x() * geo::x_size + 1;
    auto y_size = tile_size.y() * geo::y_size + 1;
    /// The LaTeX generation is handled by a LaTeX context
    latex::context c { { x_size, y_size }, file_name };
    for_each_tile_index([&](auto x, auto y) { tile(x, y).display(c); });
    // Connect each tile to its neighbors
    for_each_tile_neighborhood(
        [&](auto x, auto y, auto nx, auto ny, auto m, auto s) {
          c.add((boost::format { R"(
    \draw (node cs:name=TileX%1%Y%2%M%3%)
       -- (node cs:name=TileX%4%Y%5%S%6%);)" } %
                 x % y % c.clean_node(magic_enum::enum_name(m)) % nx % ny %
                 c.clean_node(magic_enum::enum_name(s)))
                    .str());
        });
display() [2/2]
template<typename Layout > auto trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::display (const std::string & file_name = {}) inline
Display the device layout.
Parameters
[in] file_name is the name of the file to write the LaTeX drawing into or use std::cerr by default
The LaTeX generation is handled by a LaTeX context
Definition at line 269 of file device.hpp.
                                            {}) {
    // Compute the drawing size starting with the individual tile size
    auto tile_size = tile(0, 0).display_size();
    // And expanding according to the device size. Add 1 in each
    // dimension to fit in the page because of the borders
    auto x_size = tile_size.x() * geo::x_size + 1;
    auto y_size = tile_size.y() * geo::y_size + 1;
    /// The LaTeX generation is handled by a LaTeX context
    latex::context c { { x_size, y_size }, file_name };
    for_each_tile_index([&](auto x, auto y) { tile(x, y).display(c); });
    // Connect each tile to its neighbors
    for_each_tile_neighborhood(
        [&](auto x, auto y, auto nx, auto ny, auto m, auto s) {
          c.add((boost::format { R"(
    \draw (node cs:name=TileX%1%Y%2%M%3%)
       -- (node cs:name=TileX%4%Y%5%S%6%);)" } %
                 x % y % c.clean_node(magic_enum::enum_name(m)) % nx % ny %
                 c.clean_node(magic_enum::enum_name(s)))
                    .str());
        });
for_each_tile() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile (F && f) inline
Apply a function for each tile infrastructure of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 110 of file device.hpp.
{
    for_each_tile_index([&](auto x, auto y) { f(tile(x, y)); });
  };
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile(), x, and trisycl::y.
for_each_tile() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile (F && f) inline
Apply a function for each tile infrastructure of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 110 of file device.hpp.
{
    for_each_tile_index([&](auto x, auto y) { f(tile(x, y)); });
  };
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile(), x, and trisycl::y.
for_each_tile_index() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index (F && f) inline
Apply a function for each tile index of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 98 of file device.hpp.
{
    for (auto [x, y] :
         ranges::views::cartesian_product(ranges::views::iota(0, geo::x_size),
                                          ranges::views::iota(0, geo::y_size)))
      f(x, y);
  };
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size, trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_size.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile(), and trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_neighborhood().
for_each_tile_index() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index (F && f) inline
Apply a function for each tile index of the device.
Parameters
f is a callable that is to be called like f(x,y) for each tile
Definition at line 98 of file device.hpp.
{
    for (auto [x, y] :
         ranges::views::cartesian_product(ranges::views::iota(0, geo::x_size),
                                          ranges::views::iota(0, geo::y_size)))
      f(x, y);
  };
References x, trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size, trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_size.
for_each_tile_neighborhood() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_neighborhood (F && f) inline
Apply a function on all the AXI stream of the neighborhood of each tile.
Definition at line 212 of file device.hpp.
{
    for_each_tile_index([&](auto x, auto y) {
      // No CTAD yet with Boost::Hana and Clang++-10 (but works with g++-9)
      boost::hana::for_each(
          geo::core_axi_stream_switch::interconnect, [&](auto connections) {
            auto [dx, dy, master_range, slave_range] = connections;
            if (geo::is_x_y_valid(x + dx, y + dy))
              for (auto [o, i] : ranges::views::zip(master_range, slave_range))
                f(x, y, x + dx, y + dy, o, i);
          });
    });
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), i, trisycl::vendor::xilinx::acap::aie::geography< Layout >::core_axi_stream_switch::interconnect, trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_y_valid(), x, and trisycl::y.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device().
for_each_tile_neighborhood() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_neighborhood (F && f) inline
Apply a function on all the AXI stream of the neighborhood of each tile.
Definition at line 212 of file device.hpp.
{
    for_each_tile_index([&](auto x, auto y) {
      // No CTAD yet with Boost::Hana and Clang++-10 (but works with g++-9)
      boost::hana::for_each(
          geo::core_axi_stream_switch::interconnect, [&](auto connections) {
            auto [dx, dy, master_range, slave_range] = connections;
            if (geo::is_x_y_valid(x + dx, y + dy))
              for (auto [o, i] : ranges::views::zip(master_range, slave_range))
                f(x, y, x + dx, y + dy, o, i);
          });
    });
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_index(), i, trisycl::vendor::xilinx::acap::aie::geography< Layout >::core_axi_stream_switch::interconnect, trisycl::vendor::xilinx::acap::aie::geography< Layout >::is_x_y_valid(), x, and trisycl::y.
for_each_tile_x_index() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_x_index (F && f) inline
Apply a function for each x tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each horizontal index value
Definition at line 119 of file device.hpp.
{
    for (auto x : ranges::views::iota(0, geo::x_size))
      f(x);
  };
References x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device().
for_each_tile_x_index() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_x_index (F && f) inline
Apply a function for each x tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each horizontal index value
Definition at line 119 of file device.hpp.
{
    for (auto x : ranges::views::iota(0, geo::x_size))
      f(x);
  };
References x, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::x_size.
for_each_tile_y_index() [1/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_y_index (F && f) inline
Apply a function for each y tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each vertical index value
Definition at line 129 of file device.hpp.
{
    for (auto y : ranges::views::iota(0, geo::y_size))
      f(y);
  };
References trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_size.
for_each_tile_y_index() [2/2]
template<typename Layout > template<typename F > void trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile_y_index (F && f) inline
Apply a function for each y tile index of the device.
Parameters
f is a callable that is to be called like f(x) for each vertical index value
Definition at line 129 of file device.hpp.
{
    for (auto y : ranges::views::iota(0, geo::y_size))
      f(y);
  };
References trisycl::y, and trisycl::vendor::xilinx::acap::aie::geography< Layout >::y_size.
mem() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::mem (int x, int y) inline
Shortcut to access to the common infrastructure part of a tile memory.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 142 of file device.hpp.
{
    return tile(x, y).mem();
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile(), x, and trisycl::y.
mem() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::mem (int x, int y) inline
Shortcut to access to the common infrastructure part of a tile memory.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 142 of file device.hpp.
{
    return tile(x, y).mem();
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile(), x, and trisycl::y.
shim() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim (int x) inline
Access to the shim tile.
Parameters
[in] x is the horizontal coordinate of the shim tile
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 158 of file device.hpp.
                    {
    geo::validate_x(x);
    return shims[x];
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shims, trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x(), and x.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::connect(), and trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device().
shim() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim (int x) inline
Access to the shim tile.
Parameters
[in] x is the horizontal coordinate of the shim tile
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 158 of file device.hpp.
                    {
    geo::validate_x(x);
    return shims[x];
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shims, trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x(), and x.
tile() [1/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile (int x, int y) inline
Access to the common infrastructure part of a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 88 of file device.hpp.
{
    geo::validate_x_y(x, y);
    return ti[y][x];
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::ti, trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x_y(), x, and trisycl::y.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::connect(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device(), trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::for_each_tile(), and trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::mem().
tile() [2/2]
template<typename Layout > auto & trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile (int x, int y) inline
Access to the common infrastructure part of a tile.
Parameters
[in] x is the horizontal tile coordinate
[in] y is the vertical tile coordinate
Exceptions
trisycl::runtime_error if the coordinate is invalid
Definition at line 88 of file device.hpp.
{
    geo::validate_x_y(x, y);
    return ti[y][x];
  }
References trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::ti, trisycl::vendor::xilinx::acap::aie::geography< Layout >::validate_x_y(), x, and trisycl::y.
Member Data Documentation
cs
template<typename Layout > cascade_stream<geo> trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cs
The cascade stream infrastructure of the CGRA.
Todo:
remove and distribute it instead
Todo:
remove and distribute it instead
Definition at line 66 of file device.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::cascade().
fiber_executor
template<typename Layout > ::trisycl::detail::fiber_pool trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::fiber_executor
Initial value:
{
    1, ::trisycl::detail::fiber_pool::sched::round_robin, false
  }
A fiber pool executor to run the infrastructure powered by TRISYCL_XILINX_AIE_FIBER_EXECUTOR_THREADS std::thread.
Definition at line 70 of file device.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::device().
shims
template<typename Layout > shim_tile<device> trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shims[geo::x_size]
The shim tiles on the lower row of the tile array.
For now we consider only homogeneous shim tiles.
Definition at line 150 of file device.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::shim().
ti
template<typename Layout > aie::tile_infrastructure<geo> trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::ti[geo::y_size][geo::x_size]
Keep track of all the (non detail) infrastructure tiles of this device.
Definition at line 78 of file device.hpp.
Referenced by trisycl::vendor::xilinx::acap::aie::detail::device< Layout >::tile().
The documentation for this struct was generated from the following files:
include/sycl/vendor/Xilinx/acap/aie/device/detail/device.hpp
include/triSYCL/vendor/Xilinx/acap/aie/device/detail/device.hpp