var searchData=
[
  ['debug_0',['debug',['../group__debug__trace.html#structtrisycl_1_1detail_1_1debug',1,'trisycl::detail']]],
  ['debug_3c_20accessor_3c_20t_2c_20dimensions_2c_20mode_2c_20access_3a_3atarget_3a_3alocal_20_3e_20_3e_1',['debug&lt; accessor&lt; T, Dimensions, Mode, access::target::local &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20accessor_3c_20t_2c_20dimensions_2c_20mode_2c_20target_20_3e_20_3e_2',['debug&lt; accessor&lt; T, Dimensions, Mode, Target &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20axi_5fstream_5fswitch_3c_20axi_5fss_5fgeo_20_3e_20_3e_3',['debug&lt; axi_stream_switch&lt; axi_ss_geo &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20axi_5fstream_5fswitch_3c_20axistreamgeography_20_3e_20_3e_4',['debug&lt; axi_stream_switch&lt; AXIStreamGeography &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20buffer_3c_20t_2c_201_20_3e_20_3e_5',['debug&lt; buffer&lt; T, 1 &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20buffer_3c_20t_2c_201_2c_20buffer_5fallocator_3c_20std_3a_3aremove_5fconst_5ft_3c_20t_20_3e_20_3e_20_3e_20_3e_6',['debug&lt; buffer&lt; T, 1, buffer_allocator&lt; std::remove_const_t&lt; T &gt; &gt; &gt; &gt;',['../classdetail_1_1debug_3_01buffer_3_01T_00_011_00_01buffer__allocator_3_01std_1_1remove__const__t_3_01T_01_4_01_4_01_4_01_4.html',1,'detail']]],
  ['debug_3c_20buffer_5fwaiter_3c_20t_2c_201_2c_20buffer_5fallocator_3c_20std_3a_3aremove_5fconst_5ft_3c_20t_20_3e_20_3e_20_3e_20_3e_7',['debug&lt; buffer_waiter&lt; T, 1, buffer_allocator&lt; std::remove_const_t&lt; T &gt; &gt; &gt; &gt;',['../classdetail_1_1debug_3_01buffer__waiter_3_01T_00_011_00_01buffer__allocator_3_01std_1_1remove__ced304ddc047a8cabb638d52c96e3ea66.html',1,'detail']]],
  ['debug_3c_20communicator_5fport_20_3e_8',['debug&lt; communicator_port &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20detail_3a_3aevent_20_3e_9',['debug&lt; detail::event &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20detail_3a_3akernel_20_3e_10',['debug&lt; detail::kernel &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20detail_3a_3aprogram_20_3e_11',['debug&lt; detail::program &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20detail_3a_3aqueue_20_3e_12',['debug&lt; detail::queue &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20detail_3a_3asycl_5f2_5f2_3a_3apipe_5faccessor_3c_20datatype_2c_20accessmode_2c_20target_20_3e_20_3e_13',['debug&lt; detail::sycl_2_2::pipe_accessor&lt; DataType, AccessMode, Target &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20detail_3a_3asycl_5f2_5f2_3a_3apipe_5faccessor_3c_20t_2c_20accessmode_2c_20target_20_3e_20_3e_14',['debug&lt; detail::sycl_2_2::pipe_accessor&lt; T, AccessMode, Target &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20detail_3a_3asycl_5f2_5f2_3a_3apipe_5freservation_3c_20pipeaccessor_20_3e_20_3e_15',['debug&lt; detail::sycl_2_2::pipe_reservation&lt; PipeAccessor &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20handler_20_3e_16',['debug&lt; handler &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20host_5fqueue_20_3e_17',['debug&lt; host_queue &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20opencl_5fkernel_20_3e_18',['debug&lt; opencl_kernel &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20opencl_5fqueue_20_3e_19',['debug&lt; opencl_queue &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20pipe_3c_20t_20_3e_20_3e_20',['debug&lt; pipe&lt; T &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20pipe_3c_20value_5ftype_20_3e_20_3e_21',['debug&lt; pipe&lt; value_type &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20queue_20_3e_22',['debug&lt; queue &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20receiving_5fdma_3c_20axistreamswitch_20_3e_20_3e_23',['debug&lt; receiving_dma&lt; AXIStreamSwitch &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20sending_5fdma_3c_20axistreamswitch_20_3e_20_3e_24',['debug&lt; sending_dma&lt; AXIStreamSwitch &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20specializeddma_20_3e_25',['debug&lt; SpecializedDMA &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20static_5fpipe_3c_20data_5ftype_2c_20capacity_20_3e_20_3e_26',['debug&lt; static_pipe&lt; data_type, Capacity &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20static_5fpipe_3c_20int_2c_20capacity_20_3e_20_3e_27',['debug&lt; static_pipe&lt; int, Capacity &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20static_5fpipe_3c_20t_2c_20capacity_20_3e_20_3e_28',['debug&lt; static_pipe&lt; T, Capacity &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['debug_3c_20task_20_3e_29',['debug&lt; task &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['default_5ferror_5fhandler_30',['default_error_handler',['../structtrisycl_1_1trisycl_1_1default__error__handler.html',1,'trisycl::trisycl']]],
  ['device_31',['device',['../group__execution.html#classtrisycl_1_1detail_1_1device',1,'trisycl::detail::device'],['../group__execution.html#classtrisycl_1_1device',1,'trisycl::device'],['../group__execution.html#classtrisycl_1_1facade_1_1device',1,'trisycl::facade::device&lt; UserFacing, ImplementationDetail &gt;'],['../group__vendor__trisycl__scope.html#classtrisycl_1_1vendor_1_1trisycl_1_1scope_1_1detail_1_1device',1,'trisycl::vendor::trisycl::scope::detail::device&lt; DeviceStorage, ScopedPlatform &gt;'],['../group__vendor__trisycl__scope.html#classtrisycl_1_1vendor_1_1trisycl_1_1scope_1_1device',1,'trisycl::vendor::trisycl::scope::device&lt; DeviceStorage, ScopedPlatform &gt;'],['../structtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1detail_1_1device.html',1,'trisycl::vendor::xilinx::acap::aie::detail::device&lt; Layout &gt;'],['../classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1device.html',1,'trisycl::vendor::xilinx::acap::aie::device&lt; Layout &gt;']]],
  ['device_3c_20device_2c_20detail_3a_3adevice_20_3e_32',['device&lt; device, detail::device &gt;',['../group__execution.html',1,'trisycl::facade']]],
  ['device_3c_20device_3c_20layout_20_3e_2c_20detail_3a_3adevice_3c_20layout_20_3e_20_3e_33',['device&lt; device&lt; Layout &gt;, detail::device&lt; Layout &gt; &gt;',['../group__execution.html',1,'trisycl::facade']]],
  ['device_3c_20tile_5finfrastructure_3c_20geo_20_3e_2c_20detail_3a_3atile_5finfrastructure_3c_20geo_20_3e_20_3e_34',['device&lt; tile_infrastructure&lt; geo &gt;, detail::tile_infrastructure&lt; geo &gt; &gt;',['../group__execution.html',1,'trisycl::facade']]],
  ['device_3c_20tile_5finfrastructure_3c_20geography_20_3e_2c_20detail_3a_3atile_5finfrastructure_3c_20geography_20_3e_20_3e_35',['device&lt; tile_infrastructure&lt; Geography &gt;, detail::tile_infrastructure&lt; Geography &gt; &gt;',['../group__execution.html',1,'trisycl::facade']]],
  ['device_3c_20tile_5finfrastructure_3c_20trisycl_3a_3avendor_3a_3axilinx_3a_3aacap_3a_3aaie_3a_3ageography_20_3e_2c_20detail_3a_3atile_5finfrastructure_3c_20trisycl_3a_3avendor_3a_3axilinx_3a_3aacap_3a_3aaie_3a_3ageography_20_3e_20_3e_36',['device&lt; tile_infrastructure&lt; trisycl::vendor::xilinx::acap::aie::geography &gt;, detail::tile_infrastructure&lt; trisycl::vendor::xilinx::acap::aie::geography &gt; &gt;',['../group__execution.html',1,'trisycl::facade']]],
  ['device_5ferror_37',['device_error',['../group__error__handling.html#classtrisycl_1_1device__error',1,'trisycl']]],
  ['device_5fselector_38',['device_selector',['../group__execution.html#classtrisycl_1_1device__selector',1,'trisycl']]],
  ['device_5ftype_5fselector_39',['device_type_selector',['../group__execution.html#classtrisycl_1_1device__type__selector',1,'trisycl']]],
  ['device_5ftypename_5fselector_40',['device_typename_selector',['../group__execution.html#classtrisycl_1_1device__typename__selector',1,'trisycl']]],
  ['display_5fvector_41',['display_vector',['../group__debug__trace.html#structtrisycl_1_1detail_1_1display__vector',1,'trisycl::detail']]],
  ['display_5fvector_3c_20_3a_3atrisycl_3a_3avec_3c_20datatype_2c_20numelements_20_3e_20_3e_42',['display_vector&lt; ::trisycl::vec&lt; DataType, NumElements &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['display_5fvector_3c_20finaltype_20_3e_43',['display_vector&lt; FinalType &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['display_5fvector_3c_20id_3c_201_20_3e_20_3e_44',['display_vector&lt; id&lt; 1 &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['display_5fvector_3c_20id_3c_20dimensions_20_3e_20_3e_45',['display_vector&lt; id&lt; Dimensions &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['display_5fvector_3c_20range_3c_201_20_3e_20_3e_46',['display_vector&lt; range&lt; 1 &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['display_5fvector_3c_20range_3c_20dimensions_20_3e_20_3e_47',['display_vector&lt; range&lt; Dimensions &gt; &gt;',['../group__debug__trace.html',1,'trisycl::detail']]],
  ['dma_48',['dma',['../classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1dma.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['dma_3c_20axistreamswitch_2c_20receiving_5fdma_3c_20axistreamswitch_20_3e_20_3e_49',['dma&lt; AXIStreamSwitch, receiving_dma&lt; AXIStreamSwitch &gt; &gt;',['../classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1dma.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['dma_3c_20axistreamswitch_2c_20sending_5fdma_3c_20axistreamswitch_20_3e_20_3e_50',['dma&lt; AXIStreamSwitch, sending_dma&lt; AXIStreamSwitch &gt; &gt;',['../classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1dma.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['dma_5fdsl_51',['dma_dsl',['../group__aie.html#classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1dma__dsl',1,'trisycl::vendor::xilinx::acap::aie']]]
];
