var searchData=
[
  ['palette_0',['palette',['../structtrisycl_1_1vendor_1_1xilinx_1_1graphics_1_1palette.html',1,'trisycl::vendor::xilinx::graphics']]],
  ['parallel_5ffor_5fiterate_1',['parallel_for_iterate',['../group__parallelism.html#structtrisycl_1_1detail_1_1parallel__for__iterate',1,'trisycl::detail']]],
  ['parallel_5ffor_5fiterate_3c_200_2c_20range_2c_20parallelforfunctor_2c_20id_20_3e_2',['parallel_for_iterate&lt; 0, Range, ParallelForFunctor, Id &gt;',['../group__parallelism.html#structtrisycl_1_1detail_1_1parallel__for__iterate_3_010_00_01Range_00_01ParallelForFunctor_00_01Id_01_4',1,'trisycl::detail']]],
  ['param_5ftraits_3',['param_traits',['../structtrisycl_1_1info_1_1param__traits.html',1,'trisycl::info']]],
  ['partition_5farray_4',['partition_array',['../group__Xilinx.html#structtrisycl_1_1vendor_1_1xilinx_1_1partition__array',1,'trisycl::vendor::xilinx']]],
  ['pipe_5',['pipe',['../group__old__data.html#classtrisycl_1_1detail_1_1sycl__2__2_1_1pipe',1,'trisycl::detail::sycl_2_2::pipe&lt; T &gt;'],['../group__data.html#classtrisycl_1_1pipe',1,'trisycl::pipe&lt; Name, T, MinCapacity, SizeT &gt;'],['../group__old__data.html#classtrisycl_1_1sycl__2__2_1_1pipe',1,'trisycl::sycl_2_2::pipe&lt; T &gt;']]],
  ['pipe_3c_20value_5ftype_20_3e_6',['pipe&lt; value_type &gt;',['../group__old__data.html',1,'trisycl::detail::sycl_2_2']]],
  ['pipe_5faccessor_7',['pipe_accessor',['../group__old__data.html#classtrisycl_1_1detail_1_1sycl__2__2_1_1pipe__accessor',1,'trisycl::detail::sycl_2_2']]],
  ['pipe_5faccessor_3c_20datatype_2c_20accessmode_2c_20access_3a_3atarget_3a_3ablocking_5fpipe_20_3e_8',['pipe_accessor&lt; DataType, AccessMode, access::target::blocking_pipe &gt;',['../group__old__data.html',1,'trisycl::detail::sycl_2_2']]],
  ['pipe_5faccessor_3c_20datatype_2c_20accessmode_2c_20access_3a_3atarget_3a_3apipe_20_3e_9',['pipe_accessor&lt; DataType, AccessMode, access::target::pipe &gt;',['../group__old__data.html',1,'trisycl::detail::sycl_2_2']]],
  ['pipe_5ferror_10',['pipe_error',['../group__error__handling.html#classtrisycl_1_1pipe__error',1,'trisycl']]],
  ['pipe_5freservation_11',['pipe_reservation',['../group__old__data.html#classtrisycl_1_1detail_1_1sycl__2__2_1_1pipe__reservation',1,'trisycl::detail::sycl_2_2::pipe_reservation&lt; PipeAccessor &gt;'],['../group__old__data.html#structtrisycl_1_1sycl__2__2_1_1pipe__reservation',1,'trisycl::sycl_2_2::pipe_reservation&lt; PipeAccessor &gt;']]],
  ['platform_12',['platform',['../group__execution.html#classtrisycl_1_1detail_1_1platform',1,'trisycl::detail::platform'],['../group__execution.html#classtrisycl_1_1platform',1,'trisycl::platform'],['../group__vendor__trisycl__scope.html#classtrisycl_1_1vendor_1_1trisycl_1_1scope_1_1detail_1_1platform',1,'trisycl::vendor::trisycl::scope::detail::platform&lt; PlatformStorage &gt;'],['../group__vendor__trisycl__scope.html#classtrisycl_1_1vendor_1_1trisycl_1_1scope_1_1platform',1,'trisycl::vendor::trisycl::scope::platform&lt; PlatformStorage &gt;']]],
  ['platform_5ferror_13',['platform_error',['../group__error__handling.html#classtrisycl_1_1platform__error',1,'trisycl']]],
  ['pool_5fctx_14',['pool_ctx',['../structtrisycl_1_1detail_1_1pooled__shared__work_1_1pool__ctx.html',1,'trisycl::detail::pooled_shared_work::pool_ctx'],['../structtrisycl_1_1detail_1_1pooled__work__stealing_1_1pool__ctx.html',1,'trisycl::detail::pooled_work_stealing::pool_ctx']]],
  ['pooled_5fshared_5fwork_15',['pooled_shared_work',['../classtrisycl_1_1detail_1_1pooled__shared__work.html',1,'trisycl::detail']]],
  ['pooled_5fwork_5fstealing_16',['pooled_work_stealing',['../classtrisycl_1_1detail_1_1pooled__work__stealing.html',1,'trisycl::detail']]],
  ['port_17',['port',['../structtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1port.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['port_5freceiver_18',['port_receiver',['../classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1port__receiver.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['profiling_5ferror_19',['profiling_error',['../group__error__handling.html#classtrisycl_1_1profiling__error',1,'trisycl']]],
  ['program_20',['program',['../classtrisycl_1_1detail_1_1program.html',1,'trisycl::detail::program'],['../structtrisycl_1_1drt_1_1code_1_1program.html',1,'trisycl::drt::code::program'],['../classtrisycl_1_1program.html',1,'trisycl::program'],['../group__aie.html#structtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1program',1,'trisycl::vendor::xilinx::acap::aie::program&lt; AIEDevice, Tile, Memory &gt;']]],
  ['property_21',['property',['../classtrisycl_1_1detail_1_1property.html',1,'trisycl::detail']]],
  ['property_5flist_22',['property_list',['../classtrisycl_1_1property__list.html',1,'trisycl']]]
];
