var searchData=
[
  ['cache_0',['cache',['../classtrisycl_1_1detail_1_1cache.html',1,'trisycl::detail']]],
  ['cache_3c_20cl_5fcommand_5fqueue_2c_20trisycl_3a_3adetail_3a_3aopencl_5fqueue_20_3e_1',['cache&lt; cl_command_queue, trisycl::detail::opencl_queue &gt;',['../classtrisycl_1_1detail_1_1cache.html',1,'trisycl::detail']]],
  ['cache_3c_20cl_5fcontext_2c_20trisycl_3a_3adetail_3a_3aopencl_5fcontext_20_3e_2',['cache&lt; cl_context, trisycl::detail::opencl_context &gt;',['../classtrisycl_1_1detail_1_1cache.html',1,'trisycl::detail']]],
  ['cache_3c_20cl_5fdevice_5fid_2c_20trisycl_3a_3adetail_3a_3aopencl_5fdevice_20_3e_3',['cache&lt; cl_device_id, trisycl::detail::opencl_device &gt;',['../classtrisycl_1_1detail_1_1cache.html',1,'trisycl::detail']]],
  ['cache_3c_20cl_5fevent_2c_20trisycl_3a_3adetail_3a_3aopencl_5fevent_20_3e_4',['cache&lt; cl_event, trisycl::detail::opencl_event &gt;',['../classtrisycl_1_1detail_1_1cache.html',1,'trisycl::detail']]],
  ['cache_3c_20cl_5fkernel_2c_20trisycl_3a_3adetail_3a_3aopencl_5fkernel_20_3e_5',['cache&lt; cl_kernel, trisycl::detail::opencl_kernel &gt;',['../classtrisycl_1_1detail_1_1cache.html',1,'trisycl::detail']]],
  ['cache_3c_20cl_5fplatform_5fid_2c_20trisycl_3a_3adetail_3a_3aopencl_5fplatform_20_3e_6',['cache&lt; cl_platform_id, trisycl::detail::opencl_platform &gt;',['../classtrisycl_1_1detail_1_1cache.html',1,'trisycl::detail']]],
  ['cascade_5fstream_7',['cascade_stream',['../group__aie.html#structtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1cascade__stream',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['cascade_5fstream_3c_20trisycl_3a_3avendor_3a_3axilinx_3a_3aacap_3a_3aaie_3a_3ageography_20_3e_8',['cascade_stream&lt; trisycl::vendor::xilinx::acap::aie::geography &gt;',['../group__aie.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['cgh_5ft_9',['cgh_t',['../structtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1tile__infrastructure_1_1cgh__t.html',1,'trisycl::vendor::xilinx::acap::aie::tile_infrastructure']]],
  ['cl_5fexception_10',['cl_exception',['../group__error__handling.html#classtrisycl_1_1cl__exception',1,'trisycl']]],
  ['command_5fgroup_11',['command_group',['../structtrisycl_1_1vendor_1_1trisycl_1_1scope_1_1queue_1_1command__group.html',1,'trisycl::vendor::trisycl::scope::queue']]],
  ['communicator_5fport_12',['communicator_port',['../classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1communicator__port.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['compile_5fprogram_5ferror_13',['compile_program_error',['../group__error__handling.html#classtrisycl_1_1compile__program__error',1,'trisycl']]],
  ['complete_14',['complete',['../structtrisycl_1_1vendor_1_1xilinx_1_1partition_1_1complete.html',1,'trisycl::vendor::xilinx::partition']]],
  ['connection_15',['connection',['../structtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1connection.html',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['container_5felement_5faspect_16',['container_element_aspect',['../group__helpers.html#structtrisycl_1_1detail_1_1container__element__aspect',1,'trisycl::detail']]],
  ['container_5felement_5faspect_3c_20accessor_3a_3avalue_5ftype_20_3e_17',['container_element_aspect&lt; Accessor::value_type &gt;',['../group__helpers.html',1,'trisycl::detail']]],
  ['container_5felement_5faspect_3c_20buffer_3a_3avalue_5ftype_20_3e_18',['container_element_aspect&lt; Buffer::value_type &gt;',['../group__helpers.html',1,'trisycl::detail']]],
  ['container_5felement_5faspect_3c_20datatype_20_3e_19',['container_element_aspect&lt; DataType &gt;',['../group__helpers.html',1,'trisycl::detail']]],
  ['context_20',['context',['../group__execution.html#classtrisycl_1_1context',1,'trisycl::context'],['../group__execution.html#classtrisycl_1_1detail_1_1context',1,'trisycl::detail::context'],['../classtrisycl_1_1vendor_1_1xilinx_1_1latex_1_1context.html',1,'trisycl::vendor::xilinx::latex::context']]],
  ['core_5faxi_5fstream_5fswitch_21',['core_axi_stream_switch',['../structtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1geography_1_1core__axi__stream__switch.html',1,'trisycl::vendor::xilinx::acap::aie::geography']]],
  ['cout_22',['cout',['../group__data.html#classtrisycl_1_1vendor_1_1trisycl_1_1pipe_1_1cout',1,'trisycl::vendor::trisycl::pipe']]],
  ['cyclic_23',['cyclic',['../structtrisycl_1_1vendor_1_1xilinx_1_1partition_1_1cyclic.html',1,'trisycl::vendor::xilinx::partition']]]
];
