var searchData=
[
  ['accessor_0',['accessor',['../group__data.html#classtrisycl_1_1accessor',1,'trisycl::accessor&lt; DataType, Dimensions, AccessMode, Target &gt;'],['../group__data.html#classtrisycl_1_1detail_1_1accessor',1,'trisycl::detail::accessor&lt; T, Dimensions, Mode, Target &gt;'],['../group__device__runtime.html#classtrisycl_1_1drt_1_1accessor',1,'trisycl::drt::accessor&lt; Accessor &gt;'],['../group__execution.html#classtrisycl_1_1facade_1_1accessor',1,'trisycl::facade::accessor&lt; AccessorMixIn &gt;'],['../group__execution.html#classtrisycl_1_1mixin_1_1accessor',1,'trisycl::mixin::accessor&lt; T, Dimensions &gt;'],['../classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1accessor.html',1,'trisycl::vendor::xilinx::acap::aie::accessor&lt; Buffer &gt;']]],
  ['accessor_3c_20buffer_3a_3avalue_5ftype_2c_20buffer_3a_3arank_28_29_2c_20access_3a_3amode_3a_3aread_5fwrite_2c_20access_3a_3atarget_3a_3ahost_5fbuffer_20_3e_1',['accessor&lt; Buffer::value_type, Buffer::rank(), access::mode::read_write, access::target::host_buffer &gt;',['../group__data.html',1,'trisycl']]],
  ['accessor_3c_20datatype_2c_201_2c_20accessmode_2c_20access_3a_3atarget_3a_3ablocking_5fpipe_20_3e_2',['accessor&lt; DataType, 1, AccessMode, access::target::blocking_pipe &gt;',['../group__old__data.html#classtrisycl_1_1accessor_3_01DataType_00_011_00_01AccessMode_00_01access_1_1target_1_1blocking__pipe_01_4',1,'trisycl']]],
  ['accessor_3c_20datatype_2c_201_2c_20accessmode_2c_20access_3a_3atarget_3a_3apipe_20_3e_3',['accessor&lt; DataType, 1, AccessMode, access::target::pipe &gt;',['../group__old__data.html#classtrisycl_1_1accessor_3_01DataType_00_011_00_01AccessMode_00_01access_1_1target_1_1pipe_01_4',1,'trisycl']]],
  ['accessor_3c_20datatype_2c_20dimensions_2c_20access_3a_3amode_3a_3aread_5fwrite_2c_20access_3a_3atarget_3a_3ahost_5fbuffer_20_3e_4',['accessor&lt; DataType, Dimensions, access::mode::read_write, access::target::host_buffer &gt;',['../group__data.html',1,'trisycl']]],
  ['accessor_3c_20mixin_3a_3aaccessor_3c_20t_2c_20dimensions_20_3e_20_3e_5',['accessor&lt; mixin::accessor&lt; T, Dimensions &gt; &gt;',['../group__execution.html',1,'trisycl::facade']]],
  ['accessor_3c_20t_2c_201_20_3e_6',['accessor&lt; T, 1 &gt;',['../group__execution.html',1,'trisycl::mixin']]],
  ['accessor_3c_20t_2c_20dimensions_2c_20mode_2c_20access_3a_3atarget_3a_3ahost_5fbuffer_20_3e_7',['accessor&lt; T, Dimensions, Mode, access::target::host_buffer &gt;',['../group__data.html',1,'trisycl::detail']]],
  ['accessor_3c_20t_2c_20dimensions_2c_20mode_2c_20access_3a_3atarget_3a_3alocal_20_3e_8',['accessor&lt; T, Dimensions, Mode, access::target::local &gt;',['../group__data.html#classtrisycl_1_1detail_1_1accessor_3_01T_00_01Dimensions_00_01Mode_00_01access_1_1target_1_1local_01_4',1,'trisycl::detail']]],
  ['accessor_5fbase_9',['accessor_base',['../group__data.html#classtrisycl_1_1detail_1_1accessor__base',1,'trisycl::detail']]],
  ['accessor_5ferror_10',['accessor_error',['../group__error__handling.html#classtrisycl_1_1accessor__error',1,'trisycl']]],
  ['accessormixin_11',['AccessorMixIn',['../classAccessorMixIn.html',1,'']]],
  ['address_5fspace_5farray_12',['address_space_array',['../group__address__spaces.html#structtrisycl_1_1detail_1_1address__space__array',1,'trisycl::detail']]],
  ['address_5fspace_5fbase_13',['address_space_base',['../group__address__spaces.html#structtrisycl_1_1detail_1_1address__space__base',1,'trisycl::detail']]],
  ['address_5fspace_5ffundamental_14',['address_space_fundamental',['../group__address__spaces.html#structtrisycl_1_1detail_1_1address__space__fundamental',1,'trisycl::detail']]],
  ['address_5fspace_5fobject_15',['address_space_object',['../group__address__spaces.html#structtrisycl_1_1detail_1_1address__space__object',1,'trisycl::detail']]],
  ['address_5fspace_5fptr_16',['address_space_ptr',['../group__address__spaces.html#structtrisycl_1_1detail_1_1address__space__ptr',1,'trisycl::detail']]],
  ['address_5fspace_5fvariable_17',['address_space_variable',['../group__address__spaces.html#structtrisycl_1_1detail_1_1address__space__variable',1,'trisycl::detail']]],
  ['alignment_18',['alignment',['../classtrisycl_1_1detail_1_1alignment.html',1,'trisycl::detail']]],
  ['alignment_3c_3a_3atrisycl_3a_3avec_3c_20datatype_2c_20numelements_20_3e_20_3e_19',['alignment&lt;::trisycl::vec&lt; DataType, NumElements &gt; &gt;',['../classtrisycl_1_1detail_1_1alignment_3_1_1trisycl_1_1vec_3_01DataType_00_01NumElements_01_4_01_4.html',1,'trisycl::detail']]],
  ['application_20',['application',['../structtrisycl_1_1vendor_1_1xilinx_1_1graphics_1_1application.html',1,'trisycl::vendor::xilinx::graphics']]],
  ['async_5fexception_21',['async_exception',['../group__error__handling.html#structtrisycl_1_1async__exception',1,'trisycl']]],
  ['axi_5fpacket_22',['axi_packet',['../group__aie.html#classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1axi__packet',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['axi_5fstream_5fswitch_23',['axi_stream_switch',['../group__aie.html#classtrisycl_1_1vendor_1_1xilinx_1_1acap_1_1aie_1_1axi__stream__switch',1,'trisycl::vendor::xilinx::acap::aie']]],
  ['axi_5fstream_5fswitch_3c_20axi_5fss_5fgeo_20_3e_24',['axi_stream_switch&lt; axi_ss_geo &gt;',['../group__aie.html',1,'trisycl::vendor::xilinx::acap::aie']]]
];
