var searchData=
[
  ['debug',['debug',['../group__debug__trace.html#structcl_1_1sycl_1_1detail_1_1debug',1,'cl::sycl::detail']]],
  ['debug_3c_20accessor_3c_20t_2c_20dimensions_2c_20mode_2c_20target_20_3e_20_3e',['debug&lt; accessor&lt; T, Dimensions, Mode, Target &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20buffer_3c_20t_2c_20dimensions_20_3e_20_3e',['debug&lt; buffer&lt; T, Dimensions &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20buffer_3c_20t_2c_20dimensions_2c_20allocator_20_3e_20_3e',['debug&lt; buffer&lt; T, Dimensions, Allocator &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20buffer_5fwaiter_3c_20t_2c_20dimensions_2c_20allocator_20_3e_20_3e',['debug&lt; buffer_waiter&lt; T, Dimensions, Allocator &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20detail_3a_3akernel_20_3e',['debug&lt; detail::kernel &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20detail_3a_3apipe_5faccessor_3c_20datatype_2c_20accessmode_2c_20target_20_3e_20_3e',['debug&lt; detail::pipe_accessor&lt; DataType, AccessMode, Target &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20detail_3a_3apipe_5faccessor_3c_20t_2c_20accessmode_2c_20target_20_3e_20_3e',['debug&lt; detail::pipe_accessor&lt; T, AccessMode, Target &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20detail_3a_3apipe_5freservation_3c_20pipeaccessor_20_3e_20_3e',['debug&lt; detail::pipe_reservation&lt; PipeAccessor &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20detail_3a_3aqueue_20_3e',['debug&lt; detail::queue &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20host_5fqueue_20_3e',['debug&lt; host_queue &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20opencl_5fkernel_20_3e',['debug&lt; opencl_kernel &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20opencl_5fqueue_20_3e',['debug&lt; opencl_queue &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20pipe_3c_20t_20_3e_20_3e',['debug&lt; pipe&lt; T &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20pipe_3c_20value_5ftype_20_3e_20_3e',['debug&lt; pipe&lt; value_type &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20queue_20_3e',['debug&lt; queue &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20static_5fpipe_3c_20t_2c_20capacity_20_3e_20_3e',['debug&lt; static_pipe&lt; T, Capacity &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['debug_3c_20task_20_3e',['debug&lt; task &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['default_5ferror_5fhandler',['default_error_handler',['../structcl_1_1sycl_1_1trisycl_1_1default__error__handler.html',1,'cl::sycl::trisycl']]],
  ['device',['device',['../group__execution.html#classcl_1_1sycl_1_1detail_1_1device',1,'cl::sycl::detail']]],
  ['device',['device',['../group__execution.html#classcl_1_1sycl_1_1device',1,'cl::sycl']]],
  ['device_5ferror',['device_error',['../group__error__handling.html#classcl_1_1sycl_1_1device__error',1,'cl::sycl']]],
  ['device_5fselector',['device_selector',['../group__execution.html#classcl_1_1sycl_1_1device__selector',1,'cl::sycl']]],
  ['device_5ftype_5fselector',['device_type_selector',['../group__execution.html#classcl_1_1sycl_1_1device__type__selector',1,'cl::sycl']]],
  ['device_5ftypename_5fselector',['device_typename_selector',['../group__execution.html#classcl_1_1sycl_1_1device__typename__selector',1,'cl::sycl']]],
  ['display_5fvector',['display_vector',['../group__debug__trace.html#structcl_1_1sycl_1_1detail_1_1display__vector',1,'cl::sycl::detail']]],
  ['display_5fvector_3c_20finaltype_20_3e',['display_vector&lt; FinalType &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['display_5fvector_3c_20id_3c_20dims_20_3e_20_3e',['display_vector&lt; id&lt; dims &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['display_5fvector_3c_20range_3c_20dims_20_3e_20_3e',['display_vector&lt; range&lt; dims &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]],
  ['display_5fvector_3c_20vec_3c_20datatype_2c_20numelements_20_3e_20_3e',['display_vector&lt; vec&lt; DataType, NumElements &gt; &gt;',['../group__debug__trace.html',1,'cl::sycl::detail']]]
];
